# 2) New clips for Film Tagging -- fast

Captures new clips (frame capture), builds the play calls, and writes the **Film Tagging** batches for the coaches. **No automatic Titles** (the tag model is not run -- the last automatic answers are kept), no player tracking, no brief. Commit and push the data folder when it finishes.
**Settings live in `parser_nb.ipynb`** -- this notebook runs that notebook's own cells (only the ones this job needs), so change a setting there and **save it** (Ctrl+S) before running this one. Run this notebook from the same folder as `parser_nb.ipynb`. The full notebook still works as before for a complete run.

In [2]:
import os
PARSER_LIB = os.path.join(os.getcwd(), "parser_lib")
exec(open(os.path.join(PARSER_LIB, "00_parser_modes.py"), encoding="utf-8").read())
run_parser("tagging")

=== TAGGING: New clips for Film Tagging, fast (no automatic Titles, no tracking) ===
EXTRA_GAMES is set: the run's date is 2026-3-8, the day after UWW's last game on file (03/07/26) -- every game on file counts as played, the extra game is next. (REFERENCE_DATE is ignored while EXTRA_GAMES is set.)
Input directory: ./inputs
Output directory: ../data
LLM comparisons: disabled
Reference date: 2026-3-8
Before scout: yes -- ignoring the upcoming opponent's own scouting report for this run
APP_BASE_URL taken from UWW_APP_URL in .env
  APP_BASE_URL normalized: 'uwwmensbball-new.streamlit.app' -> https://uwwmensbball-new.streamlit.app
Brief links -> https://uwwmensbball-new.streamlit.app
Found 26 schedule MHTML file(s) in ./inputs:
 - Alma Scots - Schedule.html
 - Aurora Spartans - Schedule.html
 - Carroll (WI) Pioneers - Schedule.html
 - Coe Kohawks - Schedule.html
 - Elmhurst Bluejays - Schedule.html
 - Eureka Red Devils - Schedule.html
 - Hope Flying Dutchmen - Schedule.html
 - Lawrence Vikings - Schedule.html
 - Loras Duhawks - Schedule.html
 - MSOE Raiders - Schedule_2025.html
 - Ripon Red Hawks - Schedule.html
 - Simpson Storm - Schedule.html
 - St. Thomas (TX) Celts - Schedule.html
 - UW-Eau Claire Blugolds - Schedule.html
 - UW-La Crosse Eagles - Schedule.html
 - UW-Oshkosh Titans - Schedule.html
 - UW-Platteville Pioneers - Schedule.html
 - UW-River Falls Falcons - Schedule.html
 - UW-Stevens Point Pointers - Schedule.html
 - UW-Stout Blue Devils - Schedule.html
 - UW-Whitewater - Schedule.mhtml
 - UW-Whitewater - Schedule_2023.html
 - UW-Whitewater - Schedule_2024.html
 - Washington-St. Louis Bears - Schedule_2025.html
 - Wheaton (IL) Thunder - Schedule_2025.html
 - Wheaton Thunder - Schedule_2025.html
Detected season 2025 from UWW's local schedule snapshot -- using FASTSCOUT_DOCS_SEASON='25' for any live-scrape URLs below (was hardcoded to '25').
Skipping live scrape for UW-Whitewater's own schedule -- a local schedule file already exists: UW-Whitewater - Schedule.mhtml

Every game already has a local scouting-report PDF, or is missing required data -- nothing to download from FastScout. (29 raw game(s) found; 0 missing opponent_url, 0 missing a parseable date.)
  UW-Whitewater Warhawks (UW-Whitewater - Schedule.mhtml): 29 game(s) -- scouted opponents: ['St. Thomas (TX) Celts', 'Eureka Red Devils', 'Aurora Spartans', 'Simpson Storm', 'Ripon Red Hawks', 'Lawrence Vikings', 'Carroll (WI) Pioneers', 'Hope Flying Dutchmen', 'Alma Scots', 'Elmhurst Bluejays', 'Coe Kohawks', 'UW-River Falls Falcons', 'UW-La Crosse Eagles', 'UW-Stout Blue Devils', 'UW-Platteville Pioneers', 'UW-Eau Claire Blugolds', 'UW-Oshkosh Titans', 'UW-Stevens Point Pointers', 'UW-Platteville Pioneers', 'UW-Eau Claire Blugolds', 'UW-La Crosse Eagles', 'UW-Stout Blue Devils', 'Loras Duhawks', 'Washington-St. Louis Bears']
  EXTRA_GAMES: Carroll (WI) Pioneers -- FastScout team page found on a saved schedule as 'Carroll (WI) Pioneers': https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw?league=NCAAB-III&season=25
  EXTRA_GAMES: added Carroll (WI) Pioneers as the UPCOMING game (game, real date Nov 7, 2026), placed on Sun, Mar 08, 1 day(s) after UWW's last 2025-26 game

Fetching 20 opponent schedule(s) (scrape opponent_url, MHTML backup on failure):
    [login] navigating to https://fastscout.fastmodelsports.com/teams/myTeam/analytics/dashboard?league=NCAAB-III&season=25
    [auth-retry] got redirected to identity.hudl.com while waiting on https://fastscout.fastmodelsports.com/teams/myTeam/analytics/dashboard?league=NCAAB-III&season=25 -- logging in and retrying
    [auth-retry] login_to_fastscout returned, now at https://fastscout.fastmodelsports.com/#access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZaYjBkN0VpWG9TQ0FhUTdYaW90SCJ9.eyJodHRwczovL2lkZW50aXR5Lmh1ZGwuY29tL2Nvbm5lY3Rpb25fbmFtZSI6InByb2QtaHVkbC11c2Vycy10ZXJyYWZvcm0iLCJodHRwczovL2lkZW50aXR5Lmh1ZGwuY29tL3VzZXJfaWQiOiI2NDM1MDQ3IiwiaHR0cHM6Ly9pZGVudGl0eS5odWRsLmNvbS90b2siOiJpZCIsImh0dHBzOi8vaWRlbnRpdHkuaHVkbC5jb20vaXNfc3lzYWRtaW4iOmZhbHNlLCJodHRwczovL2lkZW50aXR5Lmh1ZGwuY29tL2ludGVybmFsX2lkX2h1ZGwiOiI2NDM1MDQ3IiwiZ2l2ZW5fbmFtZSI6IkNvcmV5IiwiZmFtaWx5X25hbWUiOiJGcml0c2NoIiwibmlja25hbWUiOiJmcml0c2NoY20yNyIsIm5hbWUiOiJmcml0c2NoY20yN0BnbWFpbC5jb20iLCJwaWN0dXJlIjoiaHR0cHM6Ly9zLmdyYXZhdGFyLmNvbS9hdmF0YXIvOTY3OWI2Mzk1N2E1ZTJmZmE2NjMyYWZhYjVmMGExYTU_cz00ODAmcj1wZyZkPWh0dHBzJTNBJTJGJTJGY2RuLmF1dGgwLmNvbSUyRmF2YXRhcnMlMkZmci5wbmciLCJ1cGRhdGVkX2F0IjoiMjAyNi0xMC0yOFQyMzoxNjoyNC45OTZaIiwiZW1haWwiOiJmcml0c2NoY20yN0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5odWRsLmNvbS8iLCJhdWQiOiJ1UFJyRFVpWkZOU3d2RnJ0cnVsQ3lBWDBwaDZBckx6VSIsInN1YiI6ImF1dGgwfGh1ZGx8NjQzNTA0NyIsImlhdCI6MTc5MzIyOTM4NSwiZXhwIjoxNzk0NDM4OTg1LCJzaWQiOiJmWDV1cFNTdkJlM1lMSGdOMkpSZlZlMTVSRG9BS1VTUiIsImNfaGFzaCI6InR3bXJPVm5oQkpnak5UdDk4czhkckEiLCJub25jZSI6IjYxZTExYmNjLWZmZTYtNGJiZC04Y2IyLTNmYzhkZDM0NWUzNyJ9.T8xzWZX5Q1S0kl8rgjawekkK3yWzwT4kcfzUs94perTLOh8cT5ex8hsmbkHRqJT3qf3Nf3EP5QBEE6nlswwrOIX04T1drIf8n-HMyEH7JuQ4vSP0TB6EDW6pjpz2nHFNwLPBaFdtObvdy0DXqucF_ajR_3oT5YkCkTbEK5676Gozbvotb9MeEIEfLdqK5cLiACcAZslmIcbJOAjAqAIV_3RfG_h7MyAsIcOQA4REgInCPoC4hud0fdQbvcQQx--Jucw8LHqWfeVsM_ghohewutYCgUi0Ruqfmrh7nNM9QEQofWhvO1pkOwW1tLZLNB40Nxf6QujisEKksmTD3YLA9A&token_type=Bearer&expires_at=1794438985 -- re-navigating to https://fastscout.fastmodelsports.com/teams/myTeam/analytics/dashboard?league=NCAAB-III&season=25
    [auth-retry] re-navigated, now at https://fastscout.fastmodelsports.com/teams/myTeam/analytics/dashboard?league=NCAAB-III&season=25 -- waiting for 'text=SCHEDULE'
    [login] confirmed logged in, landed on https://fastscout.fastmodelsports.com/teams/myTeam/analytics/dashboard?league=NCAAB-III&season=26
    [login] WARNING: requested season='25' but FastScout's "myTeam" redirect landed on season='26' instead -- this account's "current" season has moved on. Any view reached via "myTeam" from here (e.g. the live schedule scrape below) may now be showing season 26 data instead of season 25. Verify the scraped schedule's games actually belong to the intended season before trusting this run's output.
    [save] myTeam analytics dashboard (diagnostic) -> myTeam - Analytics Dashboard.html
  Skipping live scrape for Ripon Red Hawks -- a local schedule file already exists.
  Skipping live scrape for St. Thomas (TX) Celts -- a local schedule file already exists.
  Skipping live scrape for Eureka Red Devils -- a local schedule file already exists.
  Skipping live scrape for Aurora Spartans -- a local schedule file already exists.
  Skipping live scrape for Simpson Storm -- a local schedule file already exists.
  Skipping live scrape for Elmhurst Bluejays -- a local schedule file already exists.
  Skipping live scrape for Lawrence Vikings -- a local schedule file already exists.
  Skipping live scrape for Carroll (WI) Pioneers -- a local schedule file already exists.
  Skipping live scrape for Hope Flying Dutchmen -- a local schedule file already exists.
  Skipping live scrape for Alma Scots -- a local schedule file already exists.
  Skipping live scrape for Coe Kohawks -- a local schedule file already exists.
  Skipping live scrape for UW-Oshkosh Titans -- a local schedule file already exists.
  Skipping live scrape for UW-Stevens Point Pointers -- a local schedule file already exists.
  Skipping live scrape for UW-River Falls Falcons -- a local schedule file already exists.
  Skipping live scrape for UW-La Crosse Eagles -- a local schedule file already exists.
  Skipping live scrape for UW-Stout Blue Devils -- a local schedule file already exists.
  Skipping live scrape for UW-Platteville Pioneers -- a local schedule file already exists.
  Skipping live scrape for UW-Eau Claire Blugolds -- a local schedule file already exists.
  Skipping live scrape for Loras Duhawks -- a local schedule file already exists.
  Skipping live scrape for Washington-St. Louis Bears -- a local schedule file already exists.
  Falling back to local backup MHTML for Ripon Red Hawks: Ripon Red Hawks - Schedule.html
  Ripon Red Hawks (Ripon Red Hawks - Schedule.html): 26 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for St. Thomas (TX) Celts: St. Thomas (TX) Celts - Schedule.html
  St. Thomas (TX) Celts (St. Thomas (TX) Celts - Schedule.html): 30 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Eureka Red Devils: Eureka Red Devils - Schedule.html
  Eureka Red Devils (Eureka Red Devils - Schedule.html): 27 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Aurora Spartans: Aurora Spartans - Schedule.html
  Aurora Spartans (Aurora Spartans - Schedule.html): 29 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Simpson Storm: Simpson Storm - Schedule.html
  Simpson Storm (Simpson Storm - Schedule.html): 26 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Elmhurst Bluejays: Elmhurst Bluejays - Schedule.html
  Elmhurst Bluejays (Elmhurst Bluejays - Schedule.html): 28 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Lawrence Vikings: Lawrence Vikings - Schedule.html
  Lawrence Vikings (Lawrence Vikings - Schedule.html): 26 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Carroll (WI) Pioneers: Carroll (WI) Pioneers - Schedule.html
  Carroll (WI) Pioneers (Carroll (WI) Pioneers - Schedule.html): 26 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Hope Flying Dutchmen: Hope Flying Dutchmen - Schedule.html
  Hope Flying Dutchmen (Hope Flying Dutchmen - Schedule.html): 28 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Alma Scots: Alma Scots - Schedule.html
  Alma Scots (Alma Scots - Schedule.html): 27 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Coe Kohawks: Coe Kohawks - Schedule.html
  Coe Kohawks (Coe Kohawks - Schedule.html): 29 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for UW-Oshkosh Titans: UW-Oshkosh Titans - Schedule.html
  UW-Oshkosh Titans (UW-Oshkosh Titans - Schedule.html): 26 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for UW-Stevens Point Pointers: UW-Stevens Point Pointers - Schedule.html
  UW-Stevens Point Pointers (UW-Stevens Point Pointers - Schedule.html): 28 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for UW-River Falls Falcons: UW-River Falls Falcons - Schedule.html
  UW-River Falls Falcons (UW-River Falls Falcons - Schedule.html): 26 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for UW-La Crosse Eagles: UW-La Crosse Eagles - Schedule.html
  UW-La Crosse Eagles (UW-La Crosse Eagles - Schedule.html): 30 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for UW-Stout Blue Devils: UW-Stout Blue Devils - Schedule.html
  UW-Stout Blue Devils (UW-Stout Blue Devils - Schedule.html): 27 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for UW-Platteville Pioneers: UW-Platteville Pioneers - Schedule.html
  UW-Platteville Pioneers (UW-Platteville Pioneers - Schedule.html): 29 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for UW-Eau Claire Blugolds: UW-Eau Claire Blugolds - Schedule.html
  UW-Eau Claire Blugolds (UW-Eau Claire Blugolds - Schedule.html): 25 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Loras Duhawks: Loras Duhawks - Schedule.html
  Loras Duhawks (Loras Duhawks - Schedule.html): 29 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Washington-St. Louis Bears: Washington-St. Louis Bears - Schedule_2025.html
  Washington-St. Louis Bears (Washington-St. Louis Bears - Schedule_2025.html): 27 game(s) -- all games before 2026-3-8
Synergy game IDs: 28 of 29 played UWW game(s), 560 game row(s) in all -- no video link on FastScout for: Wed, Feb 18 UW-Stevens Point Pointers
            date                opponent                        team  \
0     Fri, Nov 7         Ripon Red Hawks      UW-Whitewater Warhawks
1    Fri, Nov 14   St. Thomas (TX) Celts      UW-Whitewater Warhawks
2    Sat, Nov 15       Eureka Red Devils      UW-Whitewater Warhawks
3    Wed, Nov 19         Aurora Spartans      UW-Whitewater Warhawks
4    Tue, Nov 25           Simpson Storm      UW-Whitewater Warhawks
..           ...                     ...                         ...
574  Fri, Feb 20             NYU Violets  Washington-St. Louis Bears
575  Sun, Feb 22         Brandeis Judges  Washington-St. Louis Bears
576  Sat, Feb 28         Chicago Maroons  Washington-St. Louis Bears
577   Fri, Mar 6   Transylvania Pioneers  Washington-St. Louis Bears
578   Sat, Mar 7  UW-Whitewater Warhawks  Washington-St. Louis Bears

          location                                       opponent_url  \
0             Away  https://fastscout.fastmodelsports.com/teams/NY...
1    Neutral Court  https://fastscout.fastmodelsports.com/teams/an...
2    Neutral Court  https://fastscout.fastmodelsports.com/teams/jV...
3             Home  https://fastscout.fastmodelsports.com/teams/Ux...
4             Home  https://fastscout.fastmodelsports.com/teams/gJ...
..             ...                                                ...
574           Away  https://fastscout.fastmodelsports.com/teams/CI...
575           Away  https://fastscout.fastmodelsports.com/teams/K6...
576           Home  https://fastscout.fastmodelsports.com/teams/PN...
577           Home  https://fastscout.fastmodelsports.com/teams/S1...
578           Home  https://fastscout.fastmodelsports.com/teams/YN...

                                              game_url  \
0    https://fastscout.fastmodelsports.com/teams/YN...
1    https://fastscout.fastmodelsports.com/teams/YN...
2    https://fastscout.fastmodelsports.com/teams/YN...
3    https://fastscout.fastmodelsports.com/teams/YN...
4    https://fastscout.fastmodelsports.com/teams/YN...
..                                                 ...
574  https://fastscout.fastmodelsports.com/teams/LU...
575  https://fastscout.fastmodelsports.com/teams/LU...
576  https://fastscout.fastmodelsports.com/teams/LU...
577  https://fastscout.fastmodelsports.com/teams/LU...
578  https://fastscout.fastmodelsports.com/teams/LU...

                                             video_url  \
0    https://editor-web.synergysports.com/video?pla...
1    https://editor-web.synergysports.com/video?pla...
2    https://editor-web.synergysports.com/video?pla...
3    https://editor-web.synergysports.com/video?pla...
4    https://editor-web.synergysports.com/video?pla...
..                                                 ...
574  https://editor-web.synergysports.com/video?pla...
575  https://editor-web.synergysports.com/video?pla...
576  https://editor-web.synergysports.com/video?pla...
577  https://editor-web.synergysports.com/video?pla...
578  https://editor-web.synergysports.com/video?pla...

              synergy_game_id  \
0    68dce749ed0cee8bbd101a32
1    68deda8125423a1fd110a592
2    68dd65d8fe000370dae0eae6
3    68dc5148e106e7b276af199f
4    68d7de383c744037aaf49e8f
..                        ...
574  68da98aa7a1c5eda71dddf2f
575  68da98aa7a1c5eda71dddf30
576  68da977db2494e65efbde77b
577  69a629f1a90179f1552e9b46
578  69abb6434a361ba0101bd122

                                  synergy_boxscore_url outcome  team_score  \
0    https://apps.synergysports.com/basketball/game...       W        76.0
1    https://apps.synergysports.com/basketball/game...       L        73.0
2    https://apps.synergysports.com/basketball/game...       W       116.0
3    https://apps.synergysports.com/basketball/game...       W        82.0
4    https://apps.synergysports.com/basketball/game...       W       100.0
..                                                 ...     ...         ...
574  https://apps.synergysports.com/basketball/game...       W        84.0
575  https://apps.synergysports.com/basketball/game...       W        74.0
576  https://apps.synergysports.com/basketball/game...       W        82.0
577  https://apps.synergysports.com/basketball/game...       W        82.0
578  https://apps.synergysports.com/basketball/game...       W        74.0

     opponent_score  point_margin   season Upcoming game_type  note
0              58.0          18.0  2025-26       No      None  None
1              81.0          -8.0  2025-26       No      None  None
2              73.0          43.0  2025-26       No      None  None
3              73.0           9.0  2025-26       No      None  None
4              78.0          22.0  2025-26       No      None  None
..              ...           ...      ...      ...       ...   ...
574            74.0          10.0  2025-26       No       NaN   NaN
575            68.0           6.0  2025-26       No       NaN   NaN
576            73.0           9.0  2025-26       No       NaN   NaN
577            47.0          35.0  2025-26       No       NaN   NaN
578            71.0           3.0  2025-26       No       NaN   NaN

[579 rows x 17 columns]
  [time] 02_parse_every_team_schedule_scrape_live_from: 1.0 min
    jersey_number                  PLAYER  GP-GS   MIN      FGM-A    FG%  \
0            14.0            Mikey Wildes    4-0     2    0.0-0.2     0%
1            24.0           Richie Warren  29-24    22    3.5-8.1  43.2%
2             0.0            Isaac Verges  27-26    23    3.5-6.7  52.5%
3            23.0          Mauryon Turner      -     -          -      -
4            23.0         Maurquis Turner    3-0     3    0.7-1.0  66.7%
5            40.0  Tyshawn Teague-Johnson   18-1    11    1.7-3.9  42.9%
6            35.0           Rashad Rogers   19-2     9    0.8-1.7  48.5%
7             5.0         Isaiah Robinson   20-0     8    0.4-1.0  33.3%
8            12.0              Jake Quast   28-0    16    2.0-4.0  51.4%
9            30.0           Matthew McKay    3-0     2    0.7-0.7   100%
10            2.0           Kelton McEwen   28-0    11    1.1-2.6  41.7%
11           21.0            Brock Marino  28-27    21    3.2-6.1  52.3%
12           15.0           Collin Madson  29-29    33   5.8-10.5  55.6%
13           25.0          Tristian Lynch    2-0     4    0.5-1.5  33.3%
14           11.0            JR Lukenbill   26-6    13    1.1-2.3  45.9%
15            1.0         Agape Keyes Jr.    6-0     4    0.5-2.0    25%
16            3.0              Zay Howard    3-0     1    0.0-0.7     0%
17           33.0         Trent Grunewald    6-0     4    0.2-1.2  14.3%
18           30.0          Spencer Cullum      -     -          -      -
19           10.0         Darius Chestnut   18-0    10    1.3-2.5  51.1%
20           22.0         Joey Berezowitz   29-1    14    1.2-2.4  49.3%
21           32.0               Luke Bara  29-29    24    3.2-8.2  38.7%
22           20.0          Austin Ambrose    8-0     9    1.1-2.5    45%
23            NaN              Team Total     29  5825  27.3-57.3  47.6%
24            NaN                Opponent     29  5825  24.3-53.6  45.4%

       3PM-A    3P%   3P-R      FTM-A    FT%   PTS   ORB   DRB   REB   AST  \
0    0.0-0.0      -     0%    0.0-0.0      -   0.0   0.0   0.2   0.2   0.2
1    0.3-1.2    25%  15.3%    1.3-2.1    65%   8.7   1.5   3.4   4.9   1.1
2    0.4-1.2  37.5%  17.7%    2.3-3.3  71.6%   9.8   1.5   2.9   4.4   1.9
3          -      -      -          -      -     -     -     -     -     -
4    0.0-0.0      -     0%    0.0-0.7     0%   1.3   0.0   0.3   0.3   0.0
5    0.4-1.0  38.9%  25.7%    0.4-1.2  36.4%   4.2   0.9   1.1   2.0   0.3
6    0.1-0.4  28.6%  21.2%    0.5-0.7  69.2%   2.3   0.6   1.4   2.1   0.5
7    0.2-0.6  23.1%  61.9%    0.2-0.5    50%   1.1   0.2   0.3   0.5   0.6
8    0.4-1.1  31.2%  28.8%    1.8-2.8  64.9%   6.2   1.4   1.5   2.9   0.6
9    0.0-0.0      -     0%    0.0-0.3     0%   1.3   0.7   0.0   0.7   0.0

                             category         stat_cols                                                        example_phrases                                                             why_chosen
0           Ball Security / Turnovers                TO  ball security, turnover, protect/take care of the ball, limit turn...  Directly named -- "ball security"/"turnovers" have a 1:1 stat colu...
1                          Rebounding     REB, ORB, DRB  own the paint, bully/dominate the glass, rebound, board, second ch...  "Glass"/"board"/"crash"/"own the paint" possession language in thi...
2                Three-Point Shooting        3PM-A, 3P%  three, 3 pt, 3pt, perimeter shooting, spacing, shooting ability, s...  Direct stat match for perimeter shot volume/efficiency. Expanded w...
3                         Free Throws        FTM-A, FT%                                     free throw, ft line, getting to ft  Direct stat match. Added "ft line" / "getting to ft" from Aurora (...
4                  Fouls / Discipline                PF                                           foul, wall up, drawing fouls  Direct stat match for foul-discipline emphasis. Added "wall up" (A...
5             Ball Movement / Assists               AST   assist, ball movement, share the ball, playmaking, playmaker, create  Direct stat match for offensive ball-sharing emphasis. Added "play...
6           Paint Protection / Blocks               BLK                               block, protect the rim, paint protection                 Direct stat match for interior shot-blocking emphasis.
7   Perimeter Defense / Ball Pressure               STL  steal, press capable, full court press, force turnovers, force to'...  Renamed from "Ball Pressure / Steals" once Aurora/Eureka/Elmhurst ...
8                      Scoring Inside  FG2M, FG2A, FG2%  dominate the paint, attack the paint, live in the paint, attack th...  Interior-scoring emphasis -- uses derived 2PT FG stats (FGM-FG3M, ...
9               Field Goal Efficiency        FGM-A, FG%                                                    limit their scoring  Overall shooting efficiency emphasis -- used when the scouting not...
10           (intentionally unmapped)                 -  communication screening action / communicate screens & actions (Ri...  No corresponding stat exists in a season box score for screen-navi...

No season boxscore table found for 'Hope Flying Dutchmen'.
Adding 64 box-score-only player(s) with no scouting writeup (defaulted to role=Bench):

                 opponent jersey_number              name
8   St. Thomas (TX) Celts           #23        Jaden Ross
10  St. Thomas (TX) Celts           #11   Tamarcus Butler
11  St. Thomas (TX) Celts           #13     Legborsi Mato
18      Eureka Red Devils           #35    Max Richardson
20      Eureka Red Devils           #20        Nolan Kerr
21      Eureka Red Devils           #22        Tony Mabon
22      Eureka Red Devils           #15   Amare Brokemond
23      Eureka Red Devils            #3     Blake Logsdon
24      Eureka Red Devils            #0     Colin DeLaere
25      Eureka Red Devils            #1     Dylan Logsdon
33        Aurora Spartans            #0      Cullen Rauls
36        Aurora Spartans           #30         Alex Ross
37        Aurora Spartans           #21   Isaiah Thompson
46          Simpson Storm           #35  Nathaniel Winter
47          Simpson Storm           #15       Seth Gipple

  ... 49 more row(s) of 64 (SHOW_ROWS = 15)
Scouting-report player statistics are disabled by design (PDF reports are last-season data) -- player_profiles stat columns start blank and are only filled in by the PBP-derived override further down this notebook, from real current-season games.
                       opponent jersey_number                name     role  \
0         St. Thomas (TX) Celts           #10       Angel Johnson  Starter
1         St. Thomas (TX) Celts            #1      Corey Thompson  Starter
2         St. Thomas (TX) Celts            #0      Nathan Kongolo  Starter
3         St. Thomas (TX) Celts           #12    Nicholas Buffalo  Starter
4         St. Thomas (TX) Celts           #25     Charles Gitonga  Starter
..                          ...           ...                 ...      ...
221               Loras Duhawks           #35          Dylan Kurt    Bench
222               Loras Duhawks           #15        Brock Massey    Bench
223               Loras Duhawks           #30        Patrick Coen    Bench
224               Loras Duhawks           #22  Patrick Quarnstrom    Bench
225  Washington-St. Louis Bears           #15          Jake Davis    Bench

                      notes_tags_display  \
0                              playmaker
1    slasher_driver, three_point_shooter
2                         slasher_driver
3              rebounder, slasher_driver
4                         slasher_driver
..                                   ...
221
222
223
224
225

                         keys_tags_display   PTS   REB   AST   FG%   3P%
0    anticipate_move, deny_catch_and_shoot  None  None  None  None  None
1                          anticipate_move  None  None  None  None  None
2                          anticipate_move  None  None  None  None  None
3                         box_out_priority  None  None  None  None  None
4                          anticipate_move  None  None  None  None  None
..                                     ...   ...   ...   ...   ...   ...
221                                         None  None  None  None  None
222                                         None  None  None  None  None
223                                         None  None  None  None  None
224                                         None  None  None  None  None
225                                         None  None  None  None  None

[226 rows x 11 columns]
Opponent production by role (Starter vs Bench) for the stat(s) behind each matched Keys-to-Victory category:
Empty DataFrame
Columns: [opponent, outcome, category, role, stat, players_with_data, avg_per_player, role_total]
Index: []
No count-type stats available yet to compare Starter vs Bench totals for the matched categories.
Roster targets this run: ['UW-Whitewater Warhawks', 'Ripon Red Hawks', 'St. Thomas (TX) Celts', 'Eureka Red Devils', 'Aurora Spartans', 'Simpson Storm', 'Elmhurst Bluejays', 'Lawrence Vikings', 'Carroll (WI) Pioneers', 'Hope Flying Dutchmen', 'Alma Scots', 'Coe Kohawks', 'UW-Oshkosh Titans', 'UW-Stevens Point Pointers', 'UW-River Falls Falcons', 'UW-La Crosse Eagles', 'UW-Stout Blue Devils', 'UW-Platteville Pioneers', 'UW-Eau Claire Blugolds', 'Loras Duhawks', 'Washington-St. Louis Bears']
  Skipping live roster scrape for UW-Whitewater Warhawks -- a local roster file already exists.
  Skipping live roster scrape for Ripon Red Hawks -- a local roster file already exists.
  Skipping live roster scrape for St. Thomas (TX) Celts -- a local roster file already exists.
  Skipping live roster scrape for Eureka Red Devils -- a local roster file already exists.
  Skipping live roster scrape for Aurora Spartans -- a local roster file already exists.
  Skipping live roster scrape for Simpson Storm -- a local roster file already exists.
  Skipping live roster scrape for Elmhurst Bluejays -- a local roster file already exists.
  Skipping live roster scrape for Lawrence Vikings -- a local roster file already exists.
  Skipping live roster scrape for Carroll (WI) Pioneers -- a local roster file already exists.
  Skipping live roster scrape for Hope Flying Dutchmen -- a local roster file already exists.
  Skipping live roster scrape for Alma Scots -- a local roster file already exists.
  Skipping live roster scrape for Coe Kohawks -- a local roster file already exists.
  Skipping live roster scrape for UW-Oshkosh Titans -- a local roster file already exists.
  Skipping live roster scrape for UW-Stevens Point Pointers -- a local roster file already exists.
  Skipping live roster scrape for UW-River Falls Falcons -- a local roster file already exists.
  Skipping live roster scrape for UW-La Crosse Eagles -- a local roster file already exists.
  Skipping live roster scrape for UW-Stout Blue Devils -- a local roster file already exists.
  Skipping live roster scrape for UW-Platteville Pioneers -- a local roster file already exists.
  Skipping live roster scrape for UW-Eau Claire Blugolds -- a local roster file already exists.
  Skipping live roster scrape for Loras Duhawks -- a local roster file already exists.
  Skipping live roster scrape for Washington-St. Louis Bears -- a local roster file already exists.
    [roster] UW-Whitewater Warhawks: 19 photo(s) matched by name in the URL, 2 fell back to page position (lower confidence -- spot-check these).
    [roster] St. Thomas (TX) Celts: 20 photo(s) matched by name in the URL, 1 fell back to page position (lower confidence -- spot-check these).
    [roster] Eureka Red Devils: 25 photo(s) matched by name in the URL, 6 fell back to page position (lower confidence -- spot-check these).
    [roster] Aurora Spartans: 23 photo(s) matched by name in the URL, 4 fell back to page position (lower confidence -- spot-check these).
    [roster] Carroll (WI) Pioneers: 16 photo(s) matched by name in the URL, 2 fell back to page position (lower confidence -- spot-check these).
    [roster] UW-Stevens Point Pointers: 18 photo(s) matched by name in the URL, 2 fell back to page position (lower confidence -- spot-check these).
    [roster] UW-River Falls Falcons: 15 photo(s) matched by name in the URL, 1 fell back to page position (lower confidence -- spot-check these).
    [roster] UW-La Crosse Eagles: 16 photo(s) matched by name in the URL, 1 fell back to page position (lower confidence -- spot-check these).
    [roster] UW-Stout Blue Devils: 19 photo(s) matched by name in the URL, 1 fell back to page position (lower confidence -- spot-check these).
    [roster] UW-Platteville Pioneers: 18 photo(s) matched by name in the URL, 1 fell back to page position (lower confidence -- spot-check these).

live_rosters: 453 player(s) across 21 team(s).

                        value
team
Alma Scots                 29
Aurora Spartans            27
Carroll (WI) Pioneers      18
Coe Kohawks                23
Elmhurst Bluejays          25
Eureka Red Devils          31
Hope Flying Dutchmen       19
Lawrence Vikings           20
Loras Duhawks              20
Ripon Red Hawks            26
Simpson Storm              21
St. Thomas (TX) Celts      21
UW-Eau Claire Blugolds     20
UW-La Crosse Eagles        17
UW-Oshkosh Titans          22

  ... 6 more row(s) of 21 (SHOW_ROWS = 15)
Carroll (WI) Pioneers's games before facing UW-Whitewater on 2026-03-08:
           date   game_date                          opponent outcome  \
0    Fri, Nov 7  2025-11-07        Washington-St. Louis Bears       L
1   Wed, Nov 12  2025-11-12                 Beloit Buccaneers       W
2   Fri, Nov 14  2025-11-14  Wisconsin-Superior Yellowjackets       W
3   Sat, Nov 15  2025-11-15           UW-Platteville Pioneers       L
4   Sat, Nov 22  2025-11-22                 UW-Oshkosh Titans       L
5   Tue, Nov 25  2025-11-25                      MSOE Raiders       W
6    Wed, Dec 3  2025-12-03                North Park Vikings       W
7    Sat, Dec 6  2025-12-06                Carthage Firebirds       L
8   Sat, Dec 13  2025-12-13            UW-Whitewater Warhawks       L
9   Sat, Dec 20  2025-12-20                Marian (WI) Sabres       W
10  Tue, Dec 30  2025-12-30                   Edgewood Eagles       W
11   Sat, Jan 3  2026-01-03          Illinois Wesleyan Titans       L
12   Wed, Jan 7  2026-01-07              Wheaton (IL) Thunder       L
13  Sat, Jan 10  2026-01-10                 Millikin Big Blue       W
14  Wed, Jan 14  2026-01-14                 Elmhurst Bluejays       W
15  Sat, Jan 17  2026-01-17            Augustana (IL) Vikings       L
16  Wed, Jan 21  2026-01-21      North Central (IL) Cardinals       L
17  Sat, Jan 24  2026-01-24          Illinois Wesleyan Titans       L
18  Wed, Jan 28  2026-01-28                North Park Vikings       L
19  Sat, Jan 31  2026-01-31              Wheaton (IL) Thunder       W
20   Sat, Feb 7  2026-02-07            Augustana (IL) Vikings       W
21  Wed, Feb 11  2026-02-11      North Central (IL) Cardinals       W
22  Sat, Feb 14  2026-02-14                 Millikin Big Blue       W
23  Wed, Feb 18  2026-02-18                 Elmhurst Bluejays       L
24  Sat, Feb 21  2026-02-21                Carthage Firebirds       L
25  Tue, Feb 24  2026-02-24                 Elmhurst Bluejays       L

    team_score  opponent_score  \
0         78.0            90.0
1         63.0            61.0
2         96.0            69.0
3         80.0            88.0
4         76.0            85.0
5         93.0            80.0
6         81.0            78.0
7         76.0            81.0
8         60.0            64.0
9         75.0            67.0
10        95.0            68.0
11        68.0            72.0
12        84.0            85.0
13        67.0            65.0
14        92.0            61.0
15        73.0            80.0
16        78.0            82.0
17        58.0            60.0
18        82.0            84.0
19        90.0            84.0
20        94.0            84.0
21        74.0            54.0
22        76.0            68.0
23        69.0            81.0
24        67.0            71.0
25        85.0            95.0

                                                                                                                                                                 video_url  \
0   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d939197965f79863570a32%2ffullgamevideo%2fclips
1   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d939197965f79863570a33%2ffullgamevideo%2fclips
2   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d939197965f79863570a34%2ffullgamevideo%2fclips
3   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d939197965f79863570a35%2ffullgamevideo%2fclips
4   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d939197965f79863570a36%2ffullgamevideo%2fclips
5   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d939197965f79863570a37%2ffullgamevideo%2fclips
6   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d939197965f79863570a38%2ffullgamevideo%2fclips
7   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a39%2ffullgamevideo%2fclips
8   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a3a%2ffullgamevideo%2fclips
9   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a3b%2ffullgamevideo%2fclips
10  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a3c%2ffullgamevideo%2fclips
11  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a3d%2ffullgamevideo%2fclips
12  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a3e%2ffullgamevideo%2fclips
13  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a3f%2ffullgamevideo%2fclips
14  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a40%2ffullgamevideo%2fclips
15  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d936c2736bdd6d038060a6%2ffullgamevideo%2fclips
16  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a41%2ffullgamevideo%2fclips
17  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a42%2ffullgamevideo%2fclips
18  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a43%2ffullgamevideo%2fclips
19  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a44%2ffullgamevideo%2fclips
20  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d936c2736bdd6d038060ab%2ffullgamevideo%2fclips
21  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a45%2ffullgamevideo%2fclips
22  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a46%2ffullgamevideo%2fclips
23  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a47%2ffullgamevideo%2fclips
24  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a48%2ffullgamevideo%2fclips
25  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f699dc391dc2261b6874ffc39%2ffullgamevideo%2fclips

             synergy_game_id  \
0   68d939197965f79863570a32
1   68d939197965f79863570a33
2   68d939197965f79863570a34
3   68d939197965f79863570a35
4   68d939197965f79863570a36
5   68d939197965f79863570a37
6   68d939197965f79863570a38
7   68d9391a7965f79863570a39
8   68d9391a7965f79863570a3a
9   68d9391a7965f79863570a3b
10  68d9391a7965f79863570a3c
11  68d9391a7965f79863570a3d
12  68d9391a7965f79863570a3e
13  68d9391a7965f79863570a3f
14  68d9391a7965f79863570a40
15  68d936c2736bdd6d038060a6
16  68d9391a7965f79863570a41
17  68d9391a7965f79863570a42
18  68d9391a7965f79863570a43
19  68d9391a7965f79863570a44
20  68d936c2736bdd6d038060ab
21  68d9391a7965f79863570a45
22  68d9391a7965f79863570a46
23  68d9391a7965f79863570a47
24  68d9391a7965f79863570a48
25  699dc391dc2261b6874ffc39

                                                                 synergy_boxscore_url  \
0   https://apps.synergysports.com/basketball/games/68d939197965f79863570a32/boxscore
1   https://apps.synergysports.com/basketball/games/68d939197965f79863570a33/boxscore
2   https://apps.synergysports.com/basketball/games/68d939197965f79863570a34/boxscore
3   https://apps.synergysports.com/basketball/games/68d939197965f79863570a35/boxscore
4   https://apps.synergysports.com/basketball/games/68d939197965f79863570a36/boxscore
5   https://apps.synergysports.com/basketball/games/68d939197965f79863570a37/boxscore
6   https://apps.synergysports.com/basketball/games/68d939197965f79863570a38/boxscore
7   https://apps.synergysports.com/basketball/games/68d9391a7965f79863570a39/boxscore
8   https://apps.synergysports.com/basketball/games/68d9391a7965f79863570a3a/boxscore
9   https://apps.synergysports.com/basketball/games/68d9391a7965f79863570a3b/boxscore
10  https://apps.synergysports.com/basketball/games/68d9391a7965f79863570a3c/boxscore
11  https://apps.synergysports.com/basketball/games/68d9391a7965f79863570a3d/boxscore
12  https://apps.synergysports.com/basketball/games/68d9391a7965f79863570a3e/boxscore
13  https://apps.synergysports.com/basketball/games/68d9391a7965f79863570a3f/boxscore
14  https://apps.synergysports.com/basketball/games/68d9391a7965f79863570a40/boxscore
15  https://apps.synergysports.com/basketball/games/68d936c2736bdd6d038060a6/boxscore
16  https://apps.synergysports.com/basketball/games/68d9391a7965f79863570a41/boxscore
17  https://apps.synergysports.com/basketball/games/68d9391a7965f79863570a42/boxscore
18  https://apps.synergysports.com/basketball/games/68d9391a7965f79863570a43/boxscore
19  https://apps.synergysports.com/basketball/games/68d9391a7965f79863570a44/boxscore
20  https://apps.synergysports.com/basketball/games/68d936c2736bdd6d038060ab/boxscore
21  https://apps.synergysports.com/basketball/games/68d9391a7965f79863570a45/boxscore
22  https://apps.synergysports.com/basketball/games/68d9391a7965f79863570a46/boxscore
23  https://apps.synergysports.com/basketball/games/68d9391a7965f79863570a47/boxscore
24  https://apps.synergysports.com/basketball/games/68d9391a7965f79863570a48/boxscore
25  https://apps.synergysports.com/basketball/games/699dc391dc2261b6874ffc39/boxscore

                                                                                                                               game_url  \
0   https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/1f69KFVqQ6-cXtyHThDxXg/boxscore?league=NCAAB-III&season=25
1   https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/9I36BUL_Rxa37scfLt6K5g/boxscore?league=NCAAB-III&season=25
2   https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/HNDFNCfIRRisRNCwty05cg/boxscore?league=NCAAB-III&season=25
3   https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/mMISp1iKRae92trz1YNVeg/boxscore?league=NCAAB-III&season=25
4   https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/WAyn3uWZRoWrom5G9VYzuA/boxscore?league=NCAAB-III&season=25
5   https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/nC6FeaglTNqQh3ro7WGHMQ/boxscore?league=NCAAB-III&season=25
6   https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/UMv7BugcTDqdIiCxUiw2TA/boxscore?league=NCAAB-III&season=25
7   https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/0xKuCL3XQ-e060NntPa6vw/boxscore?league=NCAAB-III&season=25
8   https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/au9j7soeTl2RmUly4t-vRg/boxscore?league=NCAAB-III&season=25
9   https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/FcZnncV0SpiNWHPDZIztRA/boxscore?league=NCAAB-III&season=25
10  https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/L2S6NX1sTmSBZeNTjwNFcg/boxscore?league=NCAAB-III&season=25
11  https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/L0VZ5y82QuaxE-BNc5iy8g/boxscore?league=NCAAB-III&season=25
12  https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/auMExbXKTI2SOivcRw-0iA/boxscore?league=NCAAB-III&season=25
13  https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/eQ7t0KFdQselRLjiwqOvVw/boxscore?league=NCAAB-III&season=25
14  https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/BWvAoE-mQzKJhGzgBqm2LA/boxscore?league=NCAAB-III&season=25
15  https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/eSatsCZxQuKeEdmYT3v7bA/boxscore?league=NCAAB-III&season=25
16  https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/_KvpvJgkQt6nFHlEhaX2Cg/boxscore?league=NCAAB-III&season=25
17  https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/FR0-U6F7Q4GrrGoYtBycBA/boxscore?league=NCAAB-III&season=25
18  https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/XZO_uQq2TmS6otWPlWdJMw/boxscore?league=NCAAB-III&season=25
19  https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/h9QY9YxpQg6A_z7rcfdu3g/boxscore?league=NCAAB-III&season=25
20  https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/a-PS99-IQDOPJRHGdCgV2w/boxscore?league=NCAAB-III&season=25
21  https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/muEVUtjSQt2IQmWamvIRVA/boxscore?league=NCAAB-III&season=25
22  https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/u5gq7Jd1R_qh5ofXXxPtUg/boxscore?league=NCAAB-III&season=25
23  https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/XL53wiagROKjCZoadNDUSw/boxscore?league=NCAAB-III&season=25
24  https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/xK3PiAe4ROSXmHuUbxDMcA/boxscore?league=NCAAB-III&season=25
25  https://fastscout.fastmodelsports.com/teams/nkIaCaMjQNOs1x2nMHrryw/games/AePUrWVST22Qq6WWsqKYHQ/boxscore?league=NCAAB-III&season=25

         location
0            Away
1            Home
2   Neutral Court
3            Away
4            Home
5            Away
6            Home
7            Away
8            Away
9            Home
10           Home
11           Away
12           Away
13           Home
14           Home
15           Away
16           Away
17           Home
18           Away
19           Home
20           Home
21           Home
22           Away
23           Away
24           Home
25           Away

Video links for these games (raw full-game film, independent of any manually-tagged _video.mhtml export):
  2025-11-07 vs Washington-St. Louis Bears: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d939197965f79863570a32%2ffullgamevideo%2fclips
  2025-11-12 vs Beloit Buccaneers: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d939197965f79863570a33%2ffullgamevideo%2fclips
  2025-11-14 vs Wisconsin-Superior Yellowjackets: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d939197965f79863570a34%2ffullgamevideo%2fclips
  2025-11-15 vs UW-Platteville Pioneers: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d939197965f79863570a35%2ffullgamevideo%2fclips
  2025-11-22 vs UW-Oshkosh Titans: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d939197965f79863570a36%2ffullgamevideo%2fclips
  2025-11-25 vs MSOE Raiders: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d939197965f79863570a37%2ffullgamevideo%2fclips
  2025-12-03 vs North Park Vikings: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d939197965f79863570a38%2ffullgamevideo%2fclips
  2025-12-06 vs Carthage Firebirds: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a39%2ffullgamevideo%2fclips
  2025-12-13 vs UW-Whitewater Warhawks: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a3a%2ffullgamevideo%2fclips
  2025-12-20 vs Marian (WI) Sabres: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a3b%2ffullgamevideo%2fclips
  2025-12-30 vs Edgewood Eagles: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a3c%2ffullgamevideo%2fclips
  2026-01-03 vs Illinois Wesleyan Titans: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a3d%2ffullgamevideo%2fclips
  2026-01-07 vs Wheaton (IL) Thunder: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a3e%2ffullgamevideo%2fclips
  2026-01-10 vs Millikin Big Blue: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a3f%2ffullgamevideo%2fclips
  2026-01-14 vs Elmhurst Bluejays: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a40%2ffullgamevideo%2fclips
  2026-01-17 vs Augustana (IL) Vikings: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d936c2736bdd6d038060a6%2ffullgamevideo%2fclips
  2026-01-21 vs North Central (IL) Cardinals: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a41%2ffullgamevideo%2fclips
  2026-01-24 vs Illinois Wesleyan Titans: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a42%2ffullgamevideo%2fclips
  2026-01-28 vs North Park Vikings: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a43%2ffullgamevideo%2fclips
  2026-01-31 vs Wheaton (IL) Thunder: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a44%2ffullgamevideo%2fclips
  2026-02-07 vs Augustana (IL) Vikings: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d936c2736bdd6d038060ab%2ffullgamevideo%2fclips
  2026-02-11 vs North Central (IL) Cardinals: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a45%2ffullgamevideo%2fclips
  2026-02-14 vs Millikin Big Blue: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a46%2ffullgamevideo%2fclips
  2026-02-18 vs Elmhurst Bluejays: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a47%2ffullgamevideo%2fclips
  2026-02-21 vs Carthage Firebirds: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a48%2ffullgamevideo%2fclips

,opponent,game_date,event_order,period,time_remaining,time_remaining_seconds,team,event_type,raw_text,uww_score,opp_score,player,shot_type,shot_desc,foul_type,turnover_type,ft_num,ft_total
0,Washington-St. Louis Bears,2025-11-07,0,None,None,NaN,None,period_marker,Start 1st Half,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Washington-St. Louis Bears,2025-11-07,1,H1,19:59 (H1),1199.0,Washington-St. Louis Bears,jump_ball_won,Calvin Kapral Wins Jump Ball,0.0,0.0,Calvin Kapral,NaN,NaN,NaN,NaN,NaN,NaN
2,Washington-St. Louis Bears,2025-11-07,2,H1,19:59 (H1),1199.0,Carroll (WI) Pioneers,jump_ball_lost,Jacob Naber Loses Jump Ball,0.0,0.0,Jacob Naber,NaN,NaN,NaN,NaN,NaN,NaN
3,Washington-St. Louis Bears,2025-11-07,3,H1,19:46 (H1),1186.0,Washington-St. Louis Bears,missed_shot,Calvin Kapral Misses 2PT Layup,0.0,0.0,Calvin Kapral,2,Layup,NaN,NaN,NaN,NaN
4,Washington-St. Louis Bears,2025-11-07,4,H1,19:39 (H1),1179.0,Carroll (WI) Pioneers,rebound_defensive,Evan Bland Defensive Rebound,0.0,0.0,Evan Bland,NaN,NaN,NaN,NaN,NaN,NaN
5,Washington-St. Louis Bears,2025-11-07,5,H1,19:31 (H1),1171.0,Carroll (WI) Pioneers,made_shot,Lamar Smith Makes 3PT Jump Shot,3.0,0.0,Lamar Smith,3,Jump Shot,NaN,NaN,NaN,NaN
6,Washington-St. Louis Bears,2025-11-07,6,H1,19:31 (H1),1171.0,Carroll (WI) Pioneers,assist,Evan Bland Assists,3.0,0.0,Evan Bland,NaN,NaN,NaN,NaN,NaN,NaN
7,Washington-St. Louis Bears,2025-11-07,7,H1,19:23 (H1),1163.0,Carroll (WI) Pioneers,foul,Evan Bland Commits Personal Foul,3.0,0.0,Evan Bland,NaN,NaN,Personal Foul,NaN,NaN,NaN
8,Washington-St. Louis Bears,2025-11-07,8,H1,19:14 (H1),1154.0,Washington-St. Louis Bears,turnover,Connor May Turnover (Bad Pass),3.0,0.0,Connor May,NaN,NaN,NaN,Bad Pass,NaN,NaN
9,Washington-St. Louis Bears,2025-11-07,9,H1,19:14 (H1),1154.0,Carroll (WI) Pioneers,steal,Michael McNabb Steals,3.0,0.0,Michael McNabb,NaN,NaN,NaN,NaN,NaN,NaN
10,Washington-St. Louis Bears,2025-11-07,10,H1,18:59 (H1),1139.0,Carroll (WI) Pioneers,missed_shot,Peyton McKenna Misses 3PT Jump Shot,3.0,0.0,Peyton McKenna,3,Jump Shot,NaN,NaN,NaN,NaN
11,Washington-St. Louis Bears,2025-11-07,11,H1,18:56 (H1),1136.0,Washington-St. Louis Bears,rebound_defensive,Calvin Kapral Defensive Rebound,3.0,0.0,Calvin Kapral,NaN,NaN,NaN,NaN,NaN,NaN
12,Washington-St. Louis Bears,2025-11-07,12,H1,18:50 (H1),1130.0,Washington-St. Louis Bears,missed_shot,Ryan Cohen Misses 3PT Jump Shot,3.0,0.0,Ryan Cohen,3,Jump Shot,NaN,NaN,NaN,NaN
13,Washington-St. Louis Bears,2025-11-07,13,H1,18:46 (H1),1126.0,Carroll (WI) Pioneers,rebound_defensive,Lamar Smith Defensive Rebound,3.0,0.0,Lamar Smith,NaN,NaN,NaN,NaN,NaN,NaN
14,Washington-St. Louis Bears,2025-11-07,14,H1,18:34 (H1),1114.0,Carroll (WI) Pioneers,missed_shot,Jacob Naber Misses 2PT Layup,3.0,0.0,Jacob Naber,2,Layup,NaN,NaN,NaN,NaN
15,Washington-St. Louis Bears,2025-11-07,15,H1,18:31 (H1),1111.0,Washington-St. Louis Bears,rebound_defensive,Calvin Kapral Defensive Rebound,3.0,0.0,Calvin Kapral,NaN,NaN,NaN,NaN,NaN,NaN
16,Washington-St. Louis Bears,2025-11-07,16,H1,18:15 (H1),1095.0,Washington-St. Louis Bears,missed_shot,Will Grudzinski Misses 3PT Jump Shot,3.0,0.0,Will Grudzinski,3,Jump Shot,NaN,NaN,NaN,NaN
17,Washington-St. Louis Bears,2025-11-07,17,H1,18:11 (H1),1091.0,Washington-St. Louis Bears,rebound_offensive,Calvin Kapral Offensive Rebound,3.0,0.0,Calvin Kapral,NaN,NaN,NaN,NaN,NaN,NaN
18,Washington-St. Louis Bears,2025-11-07,18,H1,18:07 (H1),1087.0,Washington-St. Louis Bears,made_shot,Will Grudzinski Makes 2PT Layup,3.0,2.0,Will Grudzinski,2,Layup,NaN,NaN,NaN,NaN
19,Washington-St. Louis Bears,2025-11-07,19,H1,17:52 (H1),1072.0,Carroll (WI) Pioneers,turnover,Evan Bland Turnover (Lost Ball),3.0,2.0,Evan Bland,NaN,NaN,NaN,Lost Ball,NaN,NaN

  ... 13,436 more row(s) of 13,456 (SHOW_ROWS = 20)
  Washington-St. Louis Bears: matched 227/243 eligible pbp events to 235 video sub-events (247 clips)
  Beloit Buccaneers: matched 186/215 eligible pbp events to 198 video sub-events (209 clips)
  Wisconsin-Superior Yellowjackets: matched 201/224 eligible pbp events to 212 video sub-events (217 clips)
  UW-Platteville Pioneers: matched 208/229 eligible pbp events to 221 video sub-events (226 clips)
  UW-Oshkosh Titans: matched 230/253 eligible pbp events to 240 video sub-events (245 clips)
  MSOE Raiders: matched 198/205 eligible pbp events to 202 video sub-events (210 clips)
  North Park Vikings: matched 193/213 eligible pbp events to 198 video sub-events (208 clips)
  Carthage Firebirds: matched 194/202 eligible pbp events to 196 video sub-events (210 clips)
  UW-Whitewater Warhawks: matched 214/235 eligible pbp events to 220 video sub-events (229 clips)
  Marian (WI) Sabres: matched 188/207 eligible pbp events to 196 video sub-events (204 clips)
  Edgewood Eagles: matched 212/225 eligible pbp events to 221 video sub-events (229 clips)
  Illinois Wesleyan Titans: matched 199/219 eligible pbp events to 206 video sub-events (217 clips)
  Wheaton (IL) Thunder: matched 207/229 eligible pbp events to 215 video sub-events (223 clips)
  Millikin Big Blue: matched 214/232 eligible pbp events to 216 video sub-events (226 clips)
  Elmhurst Bluejays: matched 187/207 eligible pbp events to 191 video sub-events (200 clips)
  Augustana (IL) Vikings: matched 213/232 eligible pbp events to 223 video sub-events (231 clips)
  North Central (IL) Cardinals: matched 230/258 eligible pbp events to 240 video sub-events (244 clips)
  Illinois Wesleyan Titans: matched 181/196 eligible pbp events to 182 video sub-events (194 clips)
  North Park Vikings: matched 182/199 eligible pbp events to 186 video sub-events (196 clips)
  Wheaton (IL) Thunder: matched 215/239 eligible pbp events to 226 video sub-events (223 clips)
  Augustana (IL) Vikings: matched 217/231 eligible pbp events to 222 video sub-events (226 clips)
  North Central (IL) Cardinals: matched 190/221 eligible pbp events to 211 video sub-events (216 clips)
  Millikin Big Blue: matched 194/206 eligible pbp events to 199 video sub-events (211 clips)
  Elmhurst Bluejays: matched 215/229 eligible pbp events to 219 video sub-events (224 clips)
  Carthage Firebirds: matched 225/235 eligible pbp events to 225 video sub-events (230 clips)
  Elmhurst Bluejays: matched 219/234 eligible pbp events to 226 video sub-events (227 clips)

Tagged-video coverage for Carroll (WI) Pioneers: 26 of 26 game(s) before facing UWW contributed tagged shots.

     game_date                                vs                                                             video_file  pbp_rows  clips  matched why
0   2025-11-07        Washington-St. Louis Bears  11_7_25 Carroll (WI) Pioneers @ Washington-St. Louis Bears_video.html       543    247      227
1   2025-11-12                 Beloit Buccaneers          11_12_25 Beloit Buccaneers @ Carroll (WI) Pioneers_video.html       500    209      186
2   2025-11-14  Wisconsin-Superior Yellowjackets  11_14_25 Carroll (WI) Pioneers @ Wisconsin-Superior Yellowjackets_...       535    217      201
3   2025-11-15           UW-Platteville Pioneers    11_15_25 Carroll (WI) Pioneers @ UW-Platteville Pioneers_video.html       544    226      208
4   2025-11-22                 UW-Oshkosh Titans          11_22_25 UW-Oshkosh Titans @ Carroll (WI) Pioneers_video.html       872    245      230
5   2025-11-25                      MSOE Raiders               11_25_25 Carroll (WI) Pioneers @ MSOE Raiders_video.html       477    210      198
6   2025-12-03                North Park Vikings          12_3_25 North Park Vikings @ Carroll (WI) Pioneers_video.html       465    208      193
7   2025-12-06                Carthage Firebirds          12_6_25 Carroll (WI) Pioneers @ Carthage Firebirds_video.html       466    210      194
8   2025-12-13            UW-Whitewater Warhawks              12_13_25 Carroll (WI) Pioneers @ UW-Whitewater_video.html       495    229      214
9   2025-12-20                Marian (WI) Sabres         12_20_25 Marian (WI) Sabres @ Carroll (WI) Pioneers_video.html       450    204      188
10  2025-12-30                   Edgewood Eagles            12_30_25 Edgewood Eagles @ Carroll (WI) Pioneers_video.html       545    229      212
11  2026-01-03          Illinois Wesleyan Titans     1_3_26 Carroll (WI) Pioneers @ Illinois Wesleyan Titans_video.html       501    217      199
12  2026-01-07              Wheaton (IL) Thunder         1_7_26 Carroll (WI) Pioneers @ Wheaton (IL) Thunder_video.html       502    223      207
13  2026-01-10                 Millikin Big Blue           1_10_26 Millikin Big Blue @ Carroll (WI) Pioneers_video.html       509    226      214
14  2026-01-14                 Elmhurst Bluejays           1_14_26 Elmhurst Bluejays @ Carroll (WI) Pioneers_video.html       470    200      187

  ... 11 more row(s) of 26 (SHOW_ROWS = 15)

Games with a video-tagging file: ['Washington-St. Louis Bears', 'Beloit Buccaneers', 'Wisconsin-Superior Yellowjackets', 'UW-Platteville Pioneers', 'UW-Oshkosh Titans', 'MSOE Raiders', 'North Park Vikings', 'Carthage Firebirds', 'UW-Whitewater Warhawks', 'Marian (WI) Sabres', 'Edgewood Eagles', 'Illinois Wesleyan Titans', 'Wheaton (IL) Thunder', 'Millikin Big Blue', 'Elmhurst Bluejays', 'Augustana (IL) Vikings', 'North Central (IL) Cardinals', 'Illinois Wesleyan Titans', 'North Park Vikings', 'Wheaton (IL) Thunder', 'Augustana (IL) Vikings', 'North Central (IL) Cardinals', 'Millikin Big Blue', 'Elmhurst Bluejays', 'Carthage Firebirds', 'Elmhurst Bluejays']
pbp_events_upcoming rows with a matched video description: 5339 of 13456

,opponent,game_date,event_order,period,time_remaining,time_remaining_seconds,team,event_type,raw_text,uww_score,opp_score,player,shot_type,shot_desc,foul_type,turnover_type,ft_num,ft_total,video_description,video_result,video_player,video_clip_number
3,Washington-St. Louis Bears,2025-11-07,3,H1,19:46 (H1),1186.0,Washington-St. Louis Bears,missed_shot,Calvin Kapral Misses 2PT Layup,0.0,0.0,Calvin Kapral,2,Layup,NaN,NaN,NaN,NaN,34 Calvin Kapral > Post-Up > Right Block > Left Shoulder > Dribble...,Miss 2 Pts,Calvin Kapral,1.0
5,Washington-St. Louis Bears,2025-11-07,5,H1,19:31 (H1),1171.0,Carroll (WI) Pioneers,made_shot,Lamar Smith Makes 3PT Jump Shot,3.0,0.0,Lamar Smith,3,Jump Shot,NaN,NaN,NaN,NaN,15 Evan Bland > P&R Ball Handler > High P&R > Dribble Off Pick > D...,Make 3 Pts,Lamar Smith,3.0
7,Washington-St. Louis Bears,2025-11-07,7,H1,19:23 (H1),1163.0,Carroll (WI) Pioneers,foul,Evan Bland Commits Personal Foul,3.0,0.0,Evan Bland,NaN,NaN,Personal Foul,NaN,NaN,NaN,3 Josh Kim > Non Possession > Non Shooting Foul,Non Shooting Foul,Josh Kim,4.0
8,Washington-St. Louis Bears,2025-11-07,8,H1,19:14 (H1),1154.0,Washington-St. Louis Bears,turnover,Connor May Turnover (Bad Pass),3.0,0.0,Connor May,NaN,NaN,NaN,Bad Pass,NaN,NaN,21 Connor May > Transition > First Middle > Turnover,Turnover,Connor May,5.0
10,Washington-St. Louis Bears,2025-11-07,10,H1,18:59 (H1),1139.0,Carroll (WI) Pioneers,missed_shot,Peyton McKenna Misses 3PT Jump Shot,3.0,0.0,Peyton McKenna,3,Jump Shot,NaN,NaN,NaN,NaN,12 Peyton McKenna > Spot-Up > No Dribble Jumper > Guarded > Long/3...,Miss 3 Pts,Peyton McKenna,6.0
12,Washington-St. Louis Bears,2025-11-07,12,H1,18:50 (H1),1130.0,Washington-St. Louis Bears,missed_shot,Ryan Cohen Misses 3PT Jump Shot,3.0,0.0,Ryan Cohen,3,Jump Shot,NaN,NaN,NaN,NaN,11 Ryan Cohen > Spot-Up > No Dribble Jumper > Open > Long/3pt > Mi...,Miss 3 Pts,Ryan Cohen,7.0
14,Washington-St. Louis Bears,2025-11-07,14,H1,18:34 (H1),1114.0,Carroll (WI) Pioneers,missed_shot,Jacob Naber Misses 2PT Layup,3.0,0.0,Jacob Naber,2,Layup,NaN,NaN,NaN,NaN,41 Jacob Naber > ISO > Right > Drives Right > To Basket > Miss 2 Pts,Miss 2 Pts,Jacob Naber,8.0
16,Washington-St. Louis Bears,2025-11-07,16,H1,18:15 (H1),1095.0,Washington-St. Louis Bears,missed_shot,Will Grudzinski Misses 3PT Jump Shot,3.0,0.0,Will Grudzinski,3,Jump Shot,NaN,NaN,NaN,NaN,32 Will Grudzinski > Spot-Up > No Dribble Jumper > Open > Long/3pt...,Miss 3 Pts,Will Grudzinski,9.0
18,Washington-St. Louis Bears,2025-11-07,18,H1,18:07 (H1),1087.0,Washington-St. Louis Bears,made_shot,Will Grudzinski Makes 2PT Layup,3.0,2.0,Will Grudzinski,2,Layup,NaN,NaN,NaN,NaN,32 Will Grudzinski > Spot-Up > Drives Right > To Basket > Make 2 Pts,Make 2 Pts,Will Grudzinski,10.0
19,Washington-St. Louis Bears,2025-11-07,19,H1,17:52 (H1),1072.0,Carroll (WI) Pioneers,turnover,Evan Bland Turnover (Lost Ball),3.0,2.0,Evan Bland,NaN,NaN,NaN,Lost Ball,NaN,NaN,15 Evan Bland > Spot-Up > Drives Left > Turnover,Turnover,Evan Bland,11.0
21,Washington-St. Louis Bears,2025-11-07,21,H1,17:40 (H1),1060.0,Washington-St. Louis Bears,missed_shot,Will Grudzinski Misses 3PT Jump Shot,3.0,2.0,Will Grudzinski,3,Jump Shot,NaN,NaN,NaN,NaN,32 Will Grudzinski > Spot-Up > No Dribble Jumper > Guarded > Long/...,Miss 3 Pts,Will Grudzinski,12.0
23,Washington-St. Louis Bears,2025-11-07,23,H1,17:36 (H1),1056.0,Washington-St. Louis Bears,made_shot,Calvin Kapral Makes 2PT Layup,3.0,4.0,Calvin Kapral,2,Layup,NaN,NaN,NaN,NaN,34 Calvin Kapral > Offensive Rebound > Short > Scoring Attempt > A...,Make 2 Pts,Calvin Kapral,13.0
24,Washington-St. Louis Bears,2025-11-07,24,H1,17:19 (H1),1039.0,Carroll (WI) Pioneers,made_shot,Jacob Naber Makes 2PT Driving Layup,5.0,4.0,Jacob Naber,2,Driving Layup,NaN,NaN,NaN,NaN,44 Lamar Smith > Post-Up > Left Block > Defense Commits > Ball Del...,Make 2 Pts,Jacob Naber,14.0
28,Washington-St. Louis Bears,2025-11-07,28,H1,17:00 (H1),1020.0,Washington-St. Louis Bears,missed_shot,Ryan Cohen Misses 3PT Jump Shot,5.0,4.0,Ryan Cohen,3,Jump Shot,NaN,NaN,NaN,NaN,11 Ryan Cohen > Spot-Up > No Dribble Jumper > Guarded > Long/3pt >...,Miss 3 Pts,Ryan Cohen,16.0
30,Washington-St. Louis Bears,2025-11-07,30,H1,16:40 (H1),1000.0,Washington-St. Louis Bears,foul,Connor May Commits Personal Foul,5.0,4.0,Connor May,NaN,NaN,Personal Foul,NaN,NaN,NaN,44 Lamar Smith > No Play Type > To Basket > Foul,Foul,Lamar Smith,17.0
31,Washington-St. Louis Bears,2025-11-07,31,H1,16:40 (H1),1000.0,Carroll (WI) Pioneers,free_throw_made,Lamar Smith Makes Free Throw (1 of 2),6.0,4.0,Lamar Smith,NaN,NaN,NaN,NaN,1,2,44 Lamar Smith > Non Possession > Free Throw,Free Throw,Lamar Smith,18.0
32,Washington-St. Louis Bears,2025-11-07,32,H1,16:40 (H1),1000.0,Carroll (WI) Pioneers,free_throw_made,Lamar Smith Makes Free Throw (2 of 2),7.0,4.0,Lamar Smith,NaN,NaN,NaN,NaN,2,2,44 Lamar Smith > Non Possession > Free Throw,Free Throw,Lamar Smith,19.0
39,Washington-St. Louis Bears,2025-11-07,39,H1,16:25 (H1),985.0,Washington-St. Louis Bears,missed_shot,Connor May Misses 2PT Jump Shot,7.0,4.0,Connor May,2,Jump Shot,NaN,NaN,NaN,NaN,21 Connor May > Spot-Up > Drives Left > Dribble Jumper > Medium/17...,Miss 2 Pts,Connor May,20.0
43,Washington-St. Louis Bears,2025-11-07,43,H1,16:15 (H1),975.0,Washington-St. Louis Bears,made_shot,George Gale Makes 2PT,7.0,6.0,George Gale,2,None,NaN,NaN,NaN,NaN,33 George Gale > Offensive Rebound > Short > Scoring Attempt > At ...,Make 2 Pts,George Gale,21.0
44,Washington-St. Louis Bears,2025-11-07,44,H1,16:08 (H1),968.0,Carroll (WI) Pioneers,turnover,Michael McNabb Turnover,7.0,6.0,Michael McNabb,NaN,NaN,NaN,None,NaN,NaN,4 Michael McNabb > P&R Ball Handler > Right P&R > Side > Go Away f...,Turnover,Michael McNabb,22.0

  ... 5,319 more row(s) of 5,339 (SHOW_ROWS = 20)
Carroll (WI) Pioneers's own events across their 26 games before Whitewater: 6418
Their opponents' events across those same games: 6932

Carroll (WI) Pioneers's shot-type tendencies (volume + efficiency, tagged by play_type/guarded) across their last 26 games:

   shot_type      shot_desc         play_type guarded  attempts  makes  fg_pct
0          3      Jump Shot           Spot-Up     Yes       191     73    38.2
1          2          Layup        Transition     N/A       126     84    66.7
2          3      Jump Shot           Spot-Up      No       104     41    39.4
3          2          Layup           Spot-Up     N/A        82     39    47.6
4          2          Layup               Cut     N/A        69     53    76.8
5          2  Driving Layup        Transition     N/A        66     53    80.3
6          2          Layup           Post-Up     N/A        56     24    42.9
7          2          Layup  P&R Ball Handler     N/A        55     27    49.1
8          2  Driving Layup           Spot-Up     N/A        51     32    62.7
9          3      Jump Shot        Transition     Yes        46     10    21.7
10         3      Jump Shot        Transition      No        45     15    33.3
11         3      Jump Shot  P&R Ball Handler     N/A        41      9    22.0
12         2          Layup          Hand Off     N/A        36     18    50.0
13         2  Driving Layup  P&R Ball Handler     N/A        29     17    58.6
14         3      Jump Shot          Hand Off     Yes        26     12    46.2

  ... 89 more row(s) of 104 (SHOW_ROWS = 15)

Carroll (WI) Pioneers's shot attempts by play type:

            play_type  attempts  makes  fg_pct
0             Spot-Up       490    204    41.6
1          Transition       347    181    52.2
2    P&R Ball Handler       162     59    36.4
3            Hand Off       132     50    37.9
4             Post-Up        93     44    47.3
5                 Cut        92     63    68.5
6                 ISO        47     24    51.1
7        P&R Roll Man        33     19    57.6
8          Off Screen        31     10    32.3
9   Offensive Rebound        29     20    69.0
10       No Play Type        18     11    61.1

Carroll (WI) Pioneers's shot attempts by contest level:

  guarded  attempts  makes  fg_pct
0     N/A       992    515    51.9
1     Yes       291    101    34.7
2      No       191     69    36.1

Carroll (WI) Pioneers's turnover types (342 total, tagged by play_type):

     turnover_type         play_type  count
3         Bad Pass      No Play Type     50
9         Bad Pass        Transition     26
20       Lost Ball        Transition     20
5         Bad Pass  P&R Ball Handler     20
19       Lost Ball           Spot-Up     20
8         Bad Pass           Spot-Up     17
16       Lost Ball  P&R Ball Handler     16
11       Lost Ball          Hand Off     15
22  Offensive Foul      No Play Type      9
13       Lost Ball      No Play Type      9
18       Lost Ball           Post-Up      9
12       Lost Ball               ISO      6
1         Bad Pass          Hand Off      6
10       Lost Ball               Cut      5
27  Offensive Foul        Transition      5

  ... 20 more row(s) of 35 (SHOW_ROWS = 15)

Carroll (WI) Pioneers's foul types (487 total, with video_description):

         foul_type                                          video_description  count
155  Personal Foul       21 Caiden Lecce > Non Possession > Non Shooting Foul      4
53   Personal Foul                      10 Ryan Johnson > No Play Type > Foul      4
219  Personal Foul     30 Alejandro Diaz > Non Possession > Non Shooting Foul      4
15   Personal Foul        0 Isaac Verges > Non Possession > Non Shooting Foul      3
250  Personal Foul    4 Kyan VanderWoude > Non Possession > Non Shooting Foul      3
30   Personal Foul                 1 Dominic Trelenberg > No Play Type > Foul      3
292  Personal Foul  5 Jonathan Burroughs > Non Possession > Non Shooting Foul      3
279  Personal Foul        5 Andre Klaver > Non Possession > Non Shooting Foul      3
156  Personal Foul                     21 Carter Thomas > No Play Type > Foul      3
160  Personal Foul         21 Connor May > Non Possession > Non Shooting Foul      3
185  Personal Foul       23 Cam Atkinson > Non Possession > Non Shooting Foul      2
244  Personal Foul                        4 EJ Marshall > No Play Type > Foul      2
232  Personal Foul    33 Miles Hettinger > Non Possession > Non Shooting Foul      2
235  Personal Foul                      34 Carson Grier > No Play Type > Foul      2
238  Personal Foul       34 Ray Maurchie > Non Possession > Non Shooting Foul      2

  ... 296 more row(s) of 311 (SHOW_ROWS = 15)

Carroll (WI) Pioneers's top scorers across their last 26 games (from play-by-play):

           player  total_points_across_26_games
0  Michael McNabb                         558.0
1     Lamar Smith                         436.0
2  Peyton McKenna                         266.0
3     Jacob Naber                         247.0
4   Dennis Estepp                         166.0
5      Evan Bland                         141.0
6    Lucas Parker                         121.0
7    Jimmy Tarjan                          47.0
8      Cai Joseph                          16.0
9      Greg Smith                          12.0

UWW's own scouting notes for Carroll (WI) Pioneers [SOURCE: SCOUTING REPORT]:
  KEYS TO VICTORY: 1. TRANSITION DEFENSE!!! | 2. SQUEEZE & LIMIT #4 (Guard 1 on 1 + Gap Help) | 3. ATTACK THE PAINT OFFENSIVELY!!
  TEAM STRENGTHS: 1. Fast paced offense (quick ball movement & cutting) | 2. Main scorer #4 capable of carrying offense (23 ppg) | 3. Push hard in transition

--- Comparing PBP evidence to the stated Keys to Victory [SOURCE: SCOUTING REPORT] ---

KEY 1 [SCOUTING REPORT] -- COMMUNICATE SCREENS & ACTIONS:
  Not directly measurable from play-by-play event types (no screen-action tagging) -- this is a
  communication/technique key tied to their offensive scheme (per the scout's own Offensive Scheme notes),
  not something the event log alone can confirm or refute.

KEY 2 [SCOUTING REPORT] -- DOMINATE THE PAINT:
  Their own rebounding split across their 26 games: [{'rebound_type': 'defensive', 'count': 658}, {'rebound_type': 'offensive', 'count': 324}]
  Their layup-area attempts (Layup + Driving Layup): 744 of 1453 total FGA
  Blocks recorded against them by opponents: 102
  Compare against their own Defensive Scheme notes and layup-area conversion rate to judge whether this key
  is supported by the evidence.

KEY 3 [SCOUTING REPORT] -- GUARD 1 ON 1:
  Measured 3PT jump-shot rate: 582 attempts at 33.5%.
  Scoring balance (top 5 scorers): [{'player': 'Michael McNabb', 'total_points_across_26_games': 558.0}, {'player': 'Lamar Smith', 'total_points_across_26_games': 436.0}, {'player': 'Peyton McKenna', 'total_points_across_26_games': 266.0}, {'player': 'Jacob Naber', 'total_points_across_26_games': 247.0}, {'player': 'Dennis Estepp', 'total_points_across_26_games': 166.0}]
  Compare against the scout's own TEAM STRENGTHS note on shooting/scoring balance to judge whether
  over-helping creates open catch-and-shoot looks that straight man coverage would limit.


--- New Keys to Victory, derived from PBP data/tendencies [SOURCE: PBP-DERIVED] ---

DATA-KEY 1 [PBP-DERIVED] -- TAKE AWAY THEIR MOST EFFICIENT HIGH-VOLUME ACTIONS:
  Offensive Rebound: 69.0% on 29 attempts; Cut: 68.5% on 92 attempts
  Each is 5+ points above their 47.1% overall clip on 15+ attempts. Offensive Rebound: hit a body on every shot before going to the ball. Cut: jump to the ball on every pass and see man and ball -- no back-cuts behind ball-watchers.

DATA-KEY 2 [PBP-DERIVED] -- FUNNEL THEM INTO THEIR WORST HIGH-VOLUME LOOKS:
  Off Screen: 32.3% on 31 attempts; P&R Ball Handler: 36.4% on 162 attempts
  Each is 5+ points below their 47.1% overall clip -- don't help off these actions; make them keep taking them.

DATA-KEY 3 [PBP-DERIVED] -- PRESSURE THE ACTIONS THEY TURN IT OVER ON:
  P&R Ball Handler: 48 TO in 210 uses (22.9% vs 13.8% across all actions); ISO: 12 TO in 59 uses (20.3% vs 13.8% across all actions)
  Loosest actions per use, not the most common ones -- load ball pressure and gap help onto these specifically rather than pressing everything.


Structured PBP-derived keys, ready for CSV export:

,opponent,key_number,title,source,supporting_stats,recommendation
0,Carroll (WI) Pioneers,1,Take away their most efficient high-volume actions,PBP-DERIVED,Offensive Rebound: 69.0% on 29 attempts; Cut: 68.5% on 92 attempts,Each is 5+ points above their 47.1% overall clip on 15+ attempts. ...
1,Carroll (WI) Pioneers,2,Funnel them into their worst high-volume looks,PBP-DERIVED,Off Screen: 32.3% on 31 attempts; P&R Ball Handler: 36.4% on 162 a...,Each is 5+ points below their 47.1% overall clip -- don't help off...
2,Carroll (WI) Pioneers,3,Pressure the actions they turn it over on,PBP-DERIVED,P&R Ball Handler: 48 TO in 210 uses (22.9% vs 13.8% across all act...,"Loosest actions per use, not the most common ones -- load ball pre..."

Carroll (WI) Pioneers's video-tagged play types, across their 26 games before Whitewater (1474 video-matched attempts):

            play_type  attempts  makes  fg_pct
0             Spot-Up       490    204    41.6
1          Transition       347    181    52.2
2    P&R Ball Handler       162     59    36.4
3            Hand Off       132     50    37.9
4             Post-Up        93     44    47.3
5                 Cut        92     63    68.5
6                 ISO        47     24    51.1
7        P&R Roll Man        33     19    57.6
8          Off Screen        31     10    32.3
9   Offensive Rebound        29     20    69.0
10       No Play Type        18     11    61.1

Weakest high-volume play type (>= 10 attempts): 'Off Screen' at 32.3% (10/31)

'Off Screen' shot-quality breakdown (31 attempts):

By shot mechanic:

             shot_mechanic  attempts  makes  fg_pct
0          Catch-and-shoot        23      6    26.1
1      Drive to the basket         6      3    50.0
2  Pull-up off the dribble         2      1    50.0

By contest level:

                                                 contest  attempts  makes  fg_pct
0                                                Guarded        15      3    20.0
1  Not tagged (contest recorded only on catch-and-shoot)         8      4    50.0
2                                                   Open         8      3    37.5

By shot distance:

   distance  attempts  makes  fg_pct
0  Long/3pt        25      7    28.0
1       N/A         6      3    50.0

Per-player 'Off Screen' volume/efficiency, with catch-and-shoot% and guarded% of those attempts:

           player  attempts  makes  fg_pct  pct_catch_and_shoot  pct_guarded
4  Peyton McKenna        16      3    18.8                 87.5         68.8
3  Michael McNabb         7      3    42.9                 42.9         28.6
2    Lucas Parker         5      2    40.0                100.0         40.0
1     Lamar Smith         2      1    50.0                  0.0          0.0
0   Dennis Estepp         1      1   100.0                100.0          0.0

LLM comparison skipped (use_llm=False) -- using tag-based similarity only.
Loaded player comparison algorithms (version 2026-07-29-portable). use_llm=False

Scouted opponents and their game number on the schedule:
  Game #1: Ripon Red Hawks
  Game #2: St. Thomas (TX) Celts
  Game #3: Eureka Red Devils
  Game #4: Aurora Spartans
  Game #5: Simpson Storm
  Game #6: Elmhurst Bluejays
  Game #7: Lawrence Vikings
  Game #8: Carroll (WI) Pioneers
  Game #9: Hope Flying Dutchmen
  Game #10: Alma Scots
  Game #11: Coe Kohawks
  Game #12: UW-Oshkosh Titans
  Game #13: UW-Stevens Point Pointers
  Game #14: UW-River Falls Falcons
  Game #15: UW-La Crosse Eagles
  Game #16: UW-Stout Blue Devils
  Game #17: UW-Platteville Pioneers
  Game #18: UW-Eau Claire Blugolds
  Game #28: Loras Duhawks
  Game #29: Washington-St. Louis Bears

Target (most recently scouted game): Carroll (WI) Pioneers (game #8)
Previous scouted opponents to compare against: ['St. Thomas (TX) Celts', 'Eureka Red Devils', 'Aurora Spartans', 'Simpson Storm', 'Ripon Red Hawks', 'Lawrence Vikings', 'Elmhurst Bluejays']

player_notes-derived tag frequency and rarity-based importance weight (rarer tags count more toward similarity):

                   tag  count  importance_weight
0  three_point_shooter     91              1.903
1       slasher_driver     81              2.018
2          post_scorer     22              3.289
3            rebounder      7              4.346
4      catch_and_shoot      5              4.633
5            playmaker      4              4.816
6           high_usage      3              5.039
7    physical_finisher      3              5.039
8      pull_up_shooter      3              5.039
9               cutter      1              5.732

keys_to_defending-derived tag frequency and rarity-based importance weight:

                     tag  count  importance_weight
0   deny_catch_and_shoot     53              2.436
1        anticipate_move     38              2.761
2           post_defense     16              3.592
3           help_defense     10              4.027
4       box_out_priority      8              4.228
5    physical_discipline      8              4.228
6       pressure_disrupt      7              4.346
7     transition_defense      7              4.346
8          keep_in_front      6              4.479
9              deny_cuts      2              5.326
10     screen_navigation      1              5.732

       target_player target_position        target_opponent target_game_date  \
0       Lucas Parker               G  Carroll (WI) Pioneers      Sat, Dec 13
1        Lamar Smith               F  Carroll (WI) Pioneers      Sat, Dec 13
2         Evan Bland               G  Carroll (WI) Pioneers      Sat, Dec 13
3        Jacob Naber               F  Carroll (WI) Pioneers      Sat, Dec 13
4     Michael McNabb               G  Carroll (WI) Pioneers      Sat, Dec 13
5     Peyton McKenna               G  Carroll (WI) Pioneers      Sat, Dec 13
6      Dennis Estepp               G  Carroll (WI) Pioneers      Sat, Dec 13
7         Greg Smith               F  Carroll (WI) Pioneers      Sat, Dec 13
8   Andrew Hollerich            None  Carroll (WI) Pioneers      Sat, Dec 13
9         Cai Joseph            None  Carroll (WI) Pioneers      Sat, Dec 13
10       Evan Oleson            None  Carroll (WI) Pioneers      Sat, Dec 13

     compared_player      compared_opponent compared_game_date  \
0      Talen Pearson      Elmhurst Bluejays         Tue, Dec 2
1        Reyce Allen  St. Thomas (TX) Celts        Fri, Nov 14
2      Isaac Averill          Simpson Storm        Tue, Nov 25
3   Devon Richardson        Aurora Spartans        Wed, Nov 19
4      Juan Madrigal        Aurora Spartans        Wed, Nov 19
5     Hogan Demovsky       Lawrence Vikings        Wed, Dec 10
6        Gevon Grant        Aurora Spartans        Wed, Nov 19
7         Landon Key       Lawrence Vikings        Wed, Dec 10
8     Garret Rodgers  St. Thomas (TX) Celts        Fri, Nov 14
9     Garret Rodgers  St. Thomas (TX) Celts        Fri, Nov 14
10    Garret Rodgers  St. Thomas (TX) Celts        Fri, Nov 14

   compared_position  similarity_score  stat_similarity  ... target_PTS  \
0                  G             13.17              1.0  ...       None
1                  F             12.67              1.0  ...       None
2                  G             12.17              1.0  ...       None
3                  C             11.50              1.0  ...       None
4                  G             11.17              1.0  ...       None
5                  G             11.17              1.0  ...       None
6                  G             10.00              1.0  ...       None
7                  F              9.50              1.0  ...       None
8                  F              3.50              1.0  ...       None
9                  F              3.50              1.0  ...       None
10                 F              3.50              1.0  ...       None

   compared_PTS target_REB compared_REB target_AST compared_AST target_FG%  \
0          None       None         None       None         None       None
1          None       None         None       None         None       None
2          None       None         None       None         None       None
3          None       None         None       None         None       None
4          None       None         None       None         None       None
5          None       None         None       None         None       None
6          None       None         None       None         None       None
7          None       None         None       None         None       None
8          None       None         None       None         None       None
9          None       None         None       None         None       None
10         None       None         None       None         None       None

   compared_FG% target_3P% compared_3P%
0          None       None         None
1          None       None         None
2          None       None         None
3          None       None         None
4          None       None         None
5          None       None         None
6          None       None         None
7          None       None         None
8          None       None         None
9          None       None         None
10         None       None         None

[11 rows x 22 columns]
Most comparable previously-scouted player for each Carroll (WI) Pioneers player (scouted Sat, Dec 13):

Lucas Parker (G) -> Talen Pearson of Elmhurst Bluejays on Tue, Dec 2 (G), score=13.17 -- shared NOTES tags: three_point_shooter; shared KEYS tags: deny_catch_and_shoot
    Season-stat similarity contribution: 1.0 (0-1 scale, weighted x3 into the score above)
    No season stats available for Talen Pearson (no PDF scout report for Elmhurst Bluejays).
    No season stats available for Lucas Parker (no PDF scout report for Carroll (WI) Pioneers yet).
Lamar Smith (F) -> Reyce Allen of St. Thomas (TX) Celts on Fri, Nov 14 (F), score=12.67 -- shared NOTES tags: slasher_driver; shared KEYS tags: anticipate_move
    Season-stat similarity contribution: 1.0 (0-1 scale, weighted x3 into the score above)
    No season stats available for Reyce Allen (no PDF scout report for St. Thomas (TX) Celts).
    No season stats available for Lamar Smith (no PDF scout report for Carroll (WI) Pioneers yet).
Evan Bland (G) -> Isaac Averill of Simpson Storm on Tue, Nov 25 (G), score=12.17 -- shared NOTES tags: slasher_driver; shared KEYS tags: anticipate_move
    Season-stat similarity contribution: 1.0 (0-1 scale, weighted x3 into the score above)
    No season stats available for Isaac Averill (no PDF scout report for Simpson Storm).
    No season stats available for Evan Bland (no PDF scout report for Carroll (WI) Pioneers yet).
Jacob Naber (F) -> Devon Richardson of Aurora Spartans on Wed, Nov 19 (C), score=11.5 -- shared NOTES tags: post_scorer; no shared keys tags
    Season-stat similarity contribution: 1.0 (0-1 scale, weighted x3 into the score above)
    No season stats available for Devon Richardson (no PDF scout report for Aurora Spartans).
    No season stats available for Jacob Naber (no PDF scout report for Carroll (WI) Pioneers yet).
Michael McNabb (G) -> Juan Madrigal of Aurora Spartans on Wed, Nov 19 (G), score=11.17 -- shared NOTES tags: slasher_driver, three_point_shooter; no shared keys tags
    Season-stat similarity contribution: 1.0 (0-1 scale, weighted x3 into the score above)
    No season stats available for Juan Madrigal (no PDF scout report for Aurora Spartans).
    No season stats available for Michael McNabb (no PDF scout report for Carroll (WI) Pioneers yet).
Peyton McKenna (G) -> Hogan Demovsky of Lawrence Vikings on Wed, Dec 10 (G), score=11.17 -- shared NOTES tags: three_point_shooter; no shared keys tags
    Season-stat similarity contribution: 1.0 (0-1 scale, weighted x3 into the score above)
    No season stats available for Hogan Demovsky (no PDF scout report for Lawrence Vikings).
    No season stats available for Peyton McKenna (no PDF scout report for Carroll (WI) Pioneers yet).
Dennis Estepp (G) -> Gevon Grant of Aurora Spartans on Wed, Nov 19 (G), score=10.0 -- no shared notes tags; shared KEYS tags: transition_defense
    Season-stat similarity contribution: 1.0 (0-1 scale, weighted x3 into the score above)
    No season stats available for Gevon Grant (no PDF scout report for Aurora Spartans).
    No season stats available for Dennis Estepp (no PDF scout report for Carroll (WI) Pioneers yet).
Greg Smith (F) -> Landon Key of Lawrence Vikings on Wed, Dec 10 (F), score=9.5 -- no shared notes tags; shared KEYS tags: help_defense
    Season-stat similarity contribution: 1.0 (0-1 scale, weighted x3 into the score above)
    No season stats available for Landon Key (no PDF scout report for Lawrence Vikings).
    No season stats available for Greg Smith (no PDF scout report for Carroll (WI) Pioneers yet).
Andrew Hollerich (None) -> Garret Rodgers of St. Thomas (TX) Celts on Fri, Nov 14 (F), score=3.5 -- no shared notes tags; no shared keys tags
    Season-stat similarity contribution: 1.0 (0-1 scale, weighted x3 into the score above)
    No season stats available for Garret Rodgers (no PDF scout report for St. Thomas (TX) Celts).
    No season stats available for Andrew Hollerich (no PDF scout report for Carroll (WI) Pioneers yet).
Cai Joseph (None) -> Garret Rodgers of St. Thomas (TX) Celts on Fri, Nov 14 (F), score=3.5 -- no shared notes tags; no shared keys tags
    Season-stat similarity contribution: 1.0 (0-1 scale, weighted x3 into the score above)
    No season stats available for Garret Rodgers (no PDF scout report for St. Thomas (TX) Celts).
    No season stats available for Cai Joseph (no PDF scout report for Carroll (WI) Pioneers yet).
Evan Oleson (None) -> Garret Rodgers of St. Thomas (TX) Celts on Fri, Nov 14 (F), score=3.5 -- no shared notes tags; no shared keys tags
    Season-stat similarity contribution: 1.0 (0-1 scale, weighted x3 into the score above)
    No season stats available for Garret Rodgers (no PDF scout report for St. Thomas (TX) Celts).
    No season stats available for Evan Oleson (no PDF scout report for Carroll (WI) Pioneers yet).
LLM-based comparison was skipped (USE_LLM=False). Set the USE_LLM config variable to True to run this cell.
LLM-based comparison was skipped (USE_LLM=False). Set the USE_LLM config variable to True to run this cell.
LLM-based comparison was skipped (USE_LLM=False), so there is no LLM score to blend with the tag-based score. Set the USE_LLM config variable to True to run this cell.
       target_player target_position target_role        target_opponent  \
0       Lucas Parker               G       Bench  Carroll (WI) Pioneers
1        Lamar Smith               F     Starter  Carroll (WI) Pioneers
2         Evan Bland               G       Bench  Carroll (WI) Pioneers
3        Jacob Naber               F     Starter  Carroll (WI) Pioneers
4     Michael McNabb               G     Starter  Carroll (WI) Pioneers
5     Peyton McKenna               G     Starter  Carroll (WI) Pioneers
6      Dennis Estepp               G     Starter  Carroll (WI) Pioneers
7         Greg Smith               F       Bench  Carroll (WI) Pioneers
8   Andrew Hollerich            None       Bench  Carroll (WI) Pioneers
9         Cai Joseph            None       Bench  Carroll (WI) Pioneers
10       Evan Oleson            None       Bench  Carroll (WI) Pioneers

   target_game_date      compared_opponent compared_game_date  \
0       Sat, Dec 13      Elmhurst Bluejays         Tue, Dec 2
1       Sat, Dec 13  St. Thomas (TX) Celts        Fri, Nov 14
2       Sat, Dec 13          Simpson Storm        Tue, Nov 25
3       Sat, Dec 13        Aurora Spartans        Wed, Nov 19
4       Sat, Dec 13        Aurora Spartans        Wed, Nov 19
5       Sat, Dec 13       Lawrence Vikings        Wed, Dec 10
6       Sat, Dec 13        Aurora Spartans        Wed, Nov 19
7       Sat, Dec 13       Lawrence Vikings        Wed, Dec 10
8       Sat, Dec 13  St. Thomas (TX) Celts        Fri, Nov 14
9       Sat, Dec 13  St. Thomas (TX) Celts        Fri, Nov 14
10      Sat, Dec 13  St. Thomas (TX) Celts        Fri, Nov 14

     compared_player compared_position compared_role  ...  target_PTS  \
0      Talen Pearson                 G         Bench  ...        None
1        Reyce Allen                 F         Bench  ...        None
2      Isaac Averill                 G         Bench  ...        None
3   Devon Richardson                 C       Starter  ...        None
4      Juan Madrigal                 G       Starter  ...        None
5     Hogan Demovsky                 G       Starter  ...        None
6        Gevon Grant                 G         Bench  ...        None
7         Landon Key                 F         Bench  ...        None
8     Garret Rodgers                 F         Bench  ...        None
9     Garret Rodgers                 F         Bench  ...        None
10    Garret Rodgers                 F         Bench  ...        None

   compared_PTS target_REB  compared_REB  target_AST  compared_AST target_FG%  \
0          None       None          None        None          None       None
1          None       None          None        None          None       None
2          None       None          None        None          None       None
3          None       None          None        None          None       None
4          None       None          None        None          None       None
5          None       None          None        None          None       None
6          None       None          None        None          None       None
7          None       None          None        None          None       None
8          None       None          None        None          None       None
9          None       None          None        None          None       None
10         None       None          None        None          None       None

    compared_FG% target_3P% compared_3P%
0           None       None         None
1           None       None         None
2           None       None         None
3           None       None         None
4           None       None         None
5           None       None         None
6           None       None         None
7           None       None         None
8           None       None         None
9           None       None         None
10          None       None         None

[11 rows x 28 columns]
Found 29 UW-Whitewater play-by-play file(s):
 - 11_14_25 UW-Whitewater @ St. Thomas (TX) Celts_pbp.html
 - 11_15_25 UW-Whitewater @ Eureka Red Devils_pbp.html
 - 11_19_25 Aurora Spartans @ UW-Whitewater_pbp.html
 - 11_25_25 Simpson Storm @ UW-Whitewater_pbp.html
 - 11_7_25 UW-Whitewater @ Ripon Red Hawks_pbp.html
 - 12_10_25 UW-Whitewater @ Lawrence Vikings_pbp.html
 - 12_13_25 Carroll (WI) Pioneers @ UW-Whitewater_pbp.html
 - 12_19_25 UW-Whitewater @ Hope Flying Dutchmen_pbp.html
 - 12_20_25 UW-Whitewater @ Alma Scots_pbp.html
 - 12_2_25 Elmhurst Bluejays @ UW-Whitewater_pbp.html
 - 12_30_25 UW-Whitewater @ Coe Kohawks_pbp.html
 - 1_10_26 UW-Whitewater @ UW-River Falls Falcons_pbp.html
 - 1_14_26 UW-Whitewater @ UW-La Crosse Eagles_pbp.html
 - 1_17_26 UW-Stout Blue Devils @ UW-Whitewater_pbp.html
 - 1_21_26 UW-Whitewater @ UW-Platteville Pioneers_pbp.html
 - 1_24_26 UW-Eau Claire Blugolds @ UW-Whitewater_pbp.html
 - 1_28_26 UW-Whitewater @ UW-Oshkosh Titans_pbp.html
 - 1_3_26 UW-Oshkosh Titans @ UW-Whitewater_pbp.html
 - 1_7_26 UW-Stevens Point Pointers @ UW-Whitewater_pbp.html
 - 2_11_26 UW-Platteville Pioneers @ UW-Whitewater_pbp.html
 - 2_14_26 UW-Whitewater @ UW-Eau Claire Blugolds_pbp.html
 - 2_18_26 UW-Stevens Point Pointers @ UW-Whitewater_pbp.html
 - 2_21_26 UW-River Falls Falcons @ UW-Whitewater_pbp.html
 - 2_26_26 UW-Platteville Pioneers @ UW-Whitewater_pbp.html
 - 2_28_26 UW-La Crosse Eagles @ UW-Whitewater_pbp.html
 - 2_4_26 UW-La Crosse Eagles @ UW-Whitewater_pbp.html
 - 2_7_26 UW-Whitewater @ UW-Stout Blue Devils_pbp.html
 - 3_6_26 UW-Whitewater @ Loras Duhawks_pbp.html
 - 3_7_26 UW-Whitewater @ Washington-St. Louis Bears_pbp.html
  Parsed 'St. Thomas (TX) Celts': 444 events
  Parsed 'Eureka Red Devils': 496 events
  WARNING: Detected swapped columns for 'Aurora Spartans' (UWW roster found in right column) -- auto-corrected
  Parsed 'Aurora Spartans': 515 events
  WARNING: Detected swapped columns for 'Simpson Storm' (UWW roster found in right column) -- auto-corrected
  Parsed 'Simpson Storm': 542 events
  Parsed 'Ripon Red Hawks': 482 events
  Parsed 'Lawrence Vikings': 508 events
  WARNING: Detected swapped columns for 'Carroll (WI) Pioneers' (UWW roster found in right column) -- auto-corrected
  Parsed 'Carroll (WI) Pioneers': 495 events
  Parsed 'Hope Flying Dutchmen': 557 events
  Parsed 'Alma Scots': 465 events
  WARNING: Detected swapped columns for 'Elmhurst Bluejays' (UWW roster found in right column) -- auto-corrected
  Parsed 'Elmhurst Bluejays': 430 events
  Parsed 'Coe Kohawks': 423 events
  Parsed 'UW-River Falls Falcons': 484 events
  Parsed 'UW-La Crosse Eagles': 536 events
  WARNING: Detected swapped columns for 'UW-Stout Blue Devils' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-Stout Blue Devils': 480 events
  Parsed 'UW-Platteville Pioneers': 435 events
  WARNING: Detected swapped columns for 'UW-Eau Claire Blugolds' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-Eau Claire Blugolds': 495 events
  Parsed 'UW-Oshkosh Titans': 846 events
  WARNING: Detected swapped columns for 'UW-Oshkosh Titans' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-Oshkosh Titans': 845 events
  WARNING: Detected swapped columns for 'UW-Stevens Point Pointers' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-Stevens Point Pointers': 493 events
  WARNING: Detected swapped columns for 'UW-Platteville Pioneers' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-Platteville Pioneers': 428 events
  Parsed 'UW-Eau Claire Blugolds': 450 events
  WARNING: Detected swapped columns for 'UW-Stevens Point Pointers' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-Stevens Point Pointers': 467 events
  WARNING: Detected swapped columns for 'UW-River Falls Falcons' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-River Falls Falcons': 470 events
  WARNING: Detected swapped columns for 'UW-Platteville Pioneers' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-Platteville Pioneers': 476 events
  WARNING: Detected swapped columns for 'UW-La Crosse Eagles' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-La Crosse Eagles': 449 events
  WARNING: Detected swapped columns for 'UW-La Crosse Eagles' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-La Crosse Eagles': 478 events
  Parsed 'UW-Stout Blue Devils': 488 events
  WARNING: Detected swapped columns for 'Loras Duhawks' (UWW roster found in right column) -- auto-corrected
  Parsed 'Loras Duhawks': 495 events
  Parsed 'Washington-St. Louis Bears': 393 events

Every play-by-play line was classified.

,opponent,game_date,event_order,period,time_remaining,time_remaining_seconds,team,event_type,raw_text,uww_score,opp_score,player,shot_type,shot_desc,turnover_type,foul_type,ft_num,ft_total
0,St. Thomas (TX) Celts,2025-11-14,0,None,None,NaN,None,period_marker,Start 1st Half,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,St. Thomas (TX) Celts,2025-11-14,1,H1,19:58 (H1),1198.0,St. Thomas (TX) Celts,jump_ball_won,Charles Gitonga Wins Jump Ball,0.0,0.0,Charles Gitonga,NaN,NaN,NaN,NaN,NaN,NaN
2,St. Thomas (TX) Celts,2025-11-14,2,H1,19:58 (H1),1198.0,UW-Whitewater,jump_ball_lost,Brock Marino Loses Jump Ball,0.0,0.0,Brock Marino,NaN,NaN,NaN,NaN,NaN,NaN
3,St. Thomas (TX) Celts,2025-11-14,3,H1,19:34 (H1),1174.0,St. Thomas (TX) Celts,made_shot,Corey Thompson Makes 2PT Turnaround Jump Shot,0.0,2.0,Corey Thompson,2,Turnaround Jump Shot,NaN,NaN,NaN,NaN
4,St. Thomas (TX) Celts,2025-11-14,4,H1,19:22 (H1),1162.0,UW-Whitewater,turnover,Isaac Verges Turnover (Lost Ball),0.0,2.0,Isaac Verges,NaN,NaN,Lost Ball,NaN,NaN,NaN
5,St. Thomas (TX) Celts,2025-11-14,5,H1,19:22 (H1),1162.0,St. Thomas (TX) Celts,steal,Angel Johnson Steals,0.0,2.0,Angel Johnson,NaN,NaN,NaN,NaN,NaN,NaN
6,St. Thomas (TX) Celts,2025-11-14,6,H1,19:16 (H1),1156.0,St. Thomas (TX) Celts,missed_shot,Nathan Kongolo Misses 3PT Jump Shot,0.0,2.0,Nathan Kongolo,3,Jump Shot,NaN,NaN,NaN,NaN
7,St. Thomas (TX) Celts,2025-11-14,7,H1,19:14 (H1),1154.0,UW-Whitewater,rebound_defensive,Collin Madson Defensive Rebound,0.0,2.0,Collin Madson,NaN,NaN,NaN,NaN,NaN,NaN
8,St. Thomas (TX) Celts,2025-11-14,8,H1,19:09 (H1),1149.0,UW-Whitewater,turnover,Isaac Verges Turnover (Bad Pass),0.0,2.0,Isaac Verges,NaN,NaN,Bad Pass,NaN,NaN,NaN
9,St. Thomas (TX) Celts,2025-11-14,9,H1,19:09 (H1),1149.0,St. Thomas (TX) Celts,steal,Nathan Kongolo Steals,0.0,2.0,Nathan Kongolo,NaN,NaN,NaN,NaN,NaN,NaN
10,St. Thomas (TX) Celts,2025-11-14,10,H1,19:05 (H1),1145.0,St. Thomas (TX) Celts,made_shot,Angel Johnson Makes 2PT Layup,0.0,4.0,Angel Johnson,2,Layup,NaN,NaN,NaN,NaN
11,St. Thomas (TX) Celts,2025-11-14,11,H1,19:05 (H1),1145.0,St. Thomas (TX) Celts,assist,Nathan Kongolo Assists,0.0,4.0,Nathan Kongolo,NaN,NaN,NaN,NaN,NaN,NaN
12,St. Thomas (TX) Celts,2025-11-14,12,H1,18:34 (H1),1114.0,UW-Whitewater,missed_shot,Isaac Verges Misses 2PT Layup,0.0,4.0,Isaac Verges,2,Layup,NaN,NaN,NaN,NaN
13,St. Thomas (TX) Celts,2025-11-14,13,H1,18:31 (H1),1111.0,St. Thomas (TX) Celts,rebound_defensive,Nicholas Buffalo Defensive Rebound,0.0,4.0,Nicholas Buffalo,NaN,NaN,NaN,NaN,NaN,NaN
14,St. Thomas (TX) Celts,2025-11-14,14,H1,18:22 (H1),1102.0,St. Thomas (TX) Celts,missed_shot,Corey Thompson Misses 2PT Layup,0.0,4.0,Corey Thompson,2,Layup,NaN,NaN,NaN,NaN
15,St. Thomas (TX) Celts,2025-11-14,15,H1,18:19 (H1),1099.0,St. Thomas (TX) Celts,rebound_offensive,Corey Thompson Offensive Rebound,0.0,4.0,Corey Thompson,NaN,NaN,NaN,NaN,NaN,NaN
16,St. Thomas (TX) Celts,2025-11-14,16,H1,18:18 (H1),1098.0,St. Thomas (TX) Celts,turnover,Corey Thompson Turnover,0.0,4.0,Corey Thompson,NaN,NaN,None,NaN,NaN,NaN
17,St. Thomas (TX) Celts,2025-11-14,17,H1,18:04 (H1),1084.0,UW-Whitewater,made_shot,Collin Madson Makes 2PT Layup,2.0,4.0,Collin Madson,2,Layup,NaN,NaN,NaN,NaN
18,St. Thomas (TX) Celts,2025-11-14,18,H1,18:04 (H1),1084.0,UW-Whitewater,assist,Luke Bara Assists,2.0,4.0,Luke Bara,NaN,NaN,NaN,NaN,NaN,NaN
19,St. Thomas (TX) Celts,2025-11-14,19,H1,17:43 (H1),1063.0,St. Thomas (TX) Celts,made_shot,Angel Johnson Makes 2PT Pull Up Jump Shot,2.0,6.0,Angel Johnson,2,Pull Up Jump Shot,NaN,NaN,NaN,NaN

  ... 14,545 more row(s) of 14,565 (SHOW_ROWS = 20)
Found 1 playbook catalog file(s):
 - UW-Whitewater - Plays.mhtml

Parsed 27 play(s) across 9 series and 17 family/families.

        series play_family       play_name aliases
0         ELOB        ELOB            "20"      20
1         Snap        Snap  20 Snap (flip)
2         Snap        Snap       30 (flip)
3         Snap        Snap         40 Snap
4         Over     Cheetah         Cheetah
5       Bursts       Cobra           Cobra
6       Bursts         Fox             Fox
7   Transition         Get             Get
8     Specials    Kentucky        Kentucky
9     Specials     Panther  Panther 2 "P2"      P2
10    Specials     Panther  Panther-4 "P4"      P4
11    Specials     Panther     Panther "P"       P
12        Over         Pin       Pin Flair
13     Entries      Pistol          Pistol
14  Transition       Pitch           Pitch

  ... 12 more row(s) of 27 (SHOW_ROWS = 15)
Found 0 coach-note/play-log CSV(s):
Lineup column check: 0 game(s) had our lineup in the opponent's column and were corrected.

,opponent,period,time_remaining,team,event_type,raw_text,uww_lineup,opp_lineup
0,St. Thomas (TX) Celts,None,None,None,period_marker,Start 1st Half,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
1,St. Thomas (TX) Celts,H1,19:58 (H1),St. Thomas (TX) Celts,jump_ball_won,Charles Gitonga Wins Jump Ball,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
2,St. Thomas (TX) Celts,H1,19:58 (H1),UW-Whitewater,jump_ball_lost,Brock Marino Loses Jump Ball,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
3,St. Thomas (TX) Celts,H1,19:34 (H1),St. Thomas (TX) Celts,made_shot,Corey Thompson Makes 2PT Turnaround Jump Shot,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
4,St. Thomas (TX) Celts,H1,19:22 (H1),UW-Whitewater,turnover,Isaac Verges Turnover (Lost Ball),"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
5,St. Thomas (TX) Celts,H1,19:22 (H1),St. Thomas (TX) Celts,steal,Angel Johnson Steals,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
6,St. Thomas (TX) Celts,H1,19:16 (H1),St. Thomas (TX) Celts,missed_shot,Nathan Kongolo Misses 3PT Jump Shot,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
7,St. Thomas (TX) Celts,H1,19:14 (H1),UW-Whitewater,rebound_defensive,Collin Madson Defensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
8,St. Thomas (TX) Celts,H1,19:09 (H1),UW-Whitewater,turnover,Isaac Verges Turnover (Bad Pass),"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
9,St. Thomas (TX) Celts,H1,19:09 (H1),St. Thomas (TX) Celts,steal,Nathan Kongolo Steals,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
10,St. Thomas (TX) Celts,H1,19:05 (H1),St. Thomas (TX) Celts,made_shot,Angel Johnson Makes 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
11,St. Thomas (TX) Celts,H1,19:05 (H1),St. Thomas (TX) Celts,assist,Nathan Kongolo Assists,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
12,St. Thomas (TX) Celts,H1,18:34 (H1),UW-Whitewater,missed_shot,Isaac Verges Misses 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
13,St. Thomas (TX) Celts,H1,18:31 (H1),St. Thomas (TX) Celts,rebound_defensive,Nicholas Buffalo Defensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
14,St. Thomas (TX) Celts,H1,18:22 (H1),St. Thomas (TX) Celts,missed_shot,Corey Thompson Misses 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
15,St. Thomas (TX) Celts,H1,18:19 (H1),St. Thomas (TX) Celts,rebound_offensive,Corey Thompson Offensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
16,St. Thomas (TX) Celts,H1,18:18 (H1),St. Thomas (TX) Celts,turnover,Corey Thompson Turnover,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
17,St. Thomas (TX) Celts,H1,18:04 (H1),UW-Whitewater,made_shot,Collin Madson Makes 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
18,St. Thomas (TX) Celts,H1,18:04 (H1),UW-Whitewater,assist,Luke Bara Assists,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
19,St. Thomas (TX) Celts,H1,17:43 (H1),St. Thomas (TX) Celts,made_shot,Angel Johnson Makes 2PT Pull Up Jump Shot,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
20,St. Thomas (TX) Celts,H1,17:19 (H1),UW-Whitewater,made_shot,JR Lukenbill Makes 3PT Jump Shot,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
21,St. Thomas (TX) Celts,H1,17:19 (H1),UW-Whitewater,assist,Collin Madson Assists,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
22,St. Thomas (TX) Celts,H1,17:05 (H1),UW-Whitewater,foul,Luke Bara Commits Personal Foul,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
23,St. Thomas (TX) Celts,H1,16:55 (H1),St. Thomas (TX) Celts,made_shot,Angel Johnson Makes 2PT Driving Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
24,St. Thomas (TX) Celts,H1,16:37 (H1),UW-Whitewater,missed_shot,Luke Bara Misses 3PT Jump Shot,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
25,St. Thomas (TX) Celts,H1,16:34 (H1),St. Thomas (TX) Celts,rebound_defensive,Charles Gitonga Defensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
26,St. Thomas (TX) Celts,H1,16:17 (H1),St. Thomas (TX) Celts,missed_shot,Nicholas Buffalo Misses 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
27,St. Thomas (TX) Celts,H1,16:15 (H1),St. Thomas (TX) Celts,rebound_offensive,Nicholas Buffalo Offensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
28,St. Thomas (TX) Celts,H1,16:13 (H1),St. Thomas (TX) Celts,missed_shot,Nicholas Buffalo Misses 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
29,St. Thomas (TX) Celts,H1,16:11 (H1),UW-Whitewater,rebound_defensive,Brock Marino Defensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."

  ... 14,535 more row(s) of 14,565 (SHOW_ROWS = 30)

Lineup size check (every non-null value should be exactly 5 players):
 uww_lineup sizes: {5: 14565}
 opp_lineup sizes: {5: 14565}
                         opponent  \
4376                   Alma Scots
4453                   Alma Scots
4393                   Alma Scots
4355                   Alma Scots
4341                   Alma Scots
...                           ...
14242  Washington-St. Louis Bears
14172  Washington-St. Louis Bears
14490  Washington-St. Louis Bears
14282  Washington-St. Louis Bears
14511  Washington-St. Louis Bears

                                                                            opp_lineup  \
4376   Donovan Collins, Josh Elliott, Joss Bradley, Luciano Guerrazzi, Preston Malpass
4453   Donovan Collins, Josh Elliott, Joss Bradley, Korbin Heitzman, Luciano Guerrazzi
4393   Donovan Collins, Josh Elliott, Korbin Heitzman, Luciano Guerrazzi, Raine Rodich
4355   Donovan Collins, Elijah Sykes, Joss Bradley, Luciano Guerrazzi, Preston Malpass
4341   Elijah Sykes, Joss Bradley, Korbin Heitzman, Luciano Guerrazzi, Preston Malpass
...                                                                                ...
14242            Anthony Przybilla, George Gale, Josh Kim, Theo Rocca, Will Grudzinski
14172                      Calvin Kapral, Connor May, Josh Kim, Ryan Cohen, Yogi Oliff
14490                Anthony Przybilla, Connor May, Ryan Cohen, Theo Rocca, Yogi Oliff
14282               Anthony Przybilla, Connor May, George Gale, Ryan Cohen, Yogi Oliff
14511                  Anthony Przybilla, Connor May, Josh Kim, Ryan Cohen, Theo Rocca

                                                                                                                                                                                           opp_lineup_summary
4376                   3 Bench / 2 Starter | Pos: 3 Guard, 2 Forward/Post | Style: three_point_shooter x3, slasher_driver x1 | Defend: deny_catch_and_shoot x2, transition_defense x1, physical_discipline x1
4453          3 Starter / 2 Bench | Pos: 3 Guard, 2 Forward/Post | Style: three_point_shooter x2, slasher_driver x2, post_scorer x1 | Defend: post_defense x2, deny_catch_and_shoot x1, transition_defense x1
4393                    4 Starter / 1 Bench | Pos: 3 Guard, 2 Forward/Post | Style: slasher_driver x2, three_point_shooter x2, post_scorer x1 | Defend: post_defense x2, anticipate_move x1, keep_in_front x1
4355                         4 Bench / 1 Starter | Pos: 3 Guard, 2 Forward/Post | Style: three_point_shooter x3, slasher_driver x2 | Defend: deny_catch_and_shoot x3, physical_discipline x1, post_defense x1
4341         4 Bench / 1 Starter | Pos: 3 Forward/Post, 2 Guard | Style: slasher_driver x3, three_point_shooter x2, post_scorer x1 | Defend: post_defense x2, deny_catch_and_shoot x2, physical_discipline x1
...                                                                                                                                                                                                       ...
14242            4 Bench / 1 Starter | Pos: 3 Guard, 2 Forward/Post | Style: slasher_driver x4, three_point_shooter x3, post_scorer x1 | Defend: deny_catch_and_shoot x2, anticipate_move x1, post_defense x1
14172                   5 Starter | Pos: 3 Guard, 2 Forward/Post | Style: three_point_shooter x4, slasher_driver x3, catch_and_shoot x1 | Defend: anticipate_move x2, keep_in_front x1, transition_defense x1
14490         3 Starter / 2 Bench | Pos: 3 Guard, 2 Forward/Post | Style: three_point_shooter x4, slasher_driver x3, catch_and_shoot x1 | Defend: keep_in_front x1, transition_defense x1, anticipate_move x1
14282         3 Starter / 2 Bench | Pos: 3 Forward/Post, 2 Guard | Style: three_point_shooter x3, slasher_driver x2, catch_and_shoot x1 | Defend: keep_in_front x1, transition_defense x1, anticipate_move x1
14511  3 Starter / 2 Bench | Pos: 3 Guard, 2 Forward/Post | Style: three_point_shooter x4, slasher_driver x3, catch_and_shoot x1 | Defend: anticipate_move x2, transition_defense x1, deny_catch_and_shoot x1

[472 rows x 3 columns]
Skipping 144 video file(s) for games UWW didn't play in (handled by the opponent prior-games cell).
Found 28 video-tagging file(s):
 - 11_14_25 UW-Whitewater @ St. Thomas (TX) Celts_video.html
 - 11_15_25 UW-Whitewater @ Eureka Red Devils_video.html
 - 11_19_25 Aurora Spartans @ UW-Whitewater_video.html
 - 11_25_25 Simpson Storm @ UW-Whitewater_video.html
 - 11_7_25 UW-Whitewater @ Ripon Red Hawks_video.html
 - 12_10_25 UW-Whitewater @ Lawrence Vikings_video.html
 - 12_13_25 Carroll (WI) Pioneers @ UW-Whitewater_video.html
 - 12_19_25 UW-Whitewater @ Hope Flying Dutchmen_video.html
 - 12_20_25 UW-Whitewater @ Alma Scots_video.html
 - 12_2_25 Elmhurst Bluejays @ UW-Whitewater_video.html
 - 12_30_25 UW-Whitewater @ Coe Kohawks_video.html
 - 1_10_26 UW-Whitewater @ UW-River Falls Falcons_video.html
 - 1_14_26 UW-Whitewater @ UW-La Crosse Eagles_video.html
 - 1_17_26 UW-Stout Blue Devils @ UW-Whitewater_video.html
 - 1_21_26 UW-Whitewater @ UW-Platteville Pioneers_video.html
 - 1_24_26 UW-Eau Claire Blugolds @ UW-Whitewater_video.html
 - 1_28_26 UW-Whitewater @ UW-Oshkosh Titans_video.html
 - 1_3_26 UW-Oshkosh Titans @ UW-Whitewater_video.html
 - 1_7_26 UW-Stevens Point Pointers @ UW-Whitewater_video.html
 - 2_11_26 UW-Platteville Pioneers @ UW-Whitewater_video.html
 - 2_14_26 UW-Whitewater @ UW-Eau Claire Blugolds_video.html
 - 2_21_26 UW-River Falls Falcons @ UW-Whitewater_video.html
 - 2_26_26 UW-Platteville Pioneers @ UW-Whitewater_video.html
 - 2_28_26 UW-La Crosse Eagles @ UW-Whitewater_video.html
 - 2_4_26 UW-La Crosse Eagles @ UW-Whitewater_video.html
 - 2_7_26 UW-Whitewater @ UW-Stout Blue Devils_video.html
 - 3_6_26 UW-Whitewater @ Loras Duhawks_video.html
 - 3_7_26 UW-Whitewater @ Washington-St. Louis Bears_video.html
  St. Thomas (TX) Celts: matched 195/222 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 53/55 are free throws, and 28/41 are fouls). video log had 213 taggable sub-events of these types.
  Eureka Red Devils: matched 208/223 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 38/38 are free throws, and 25/31 are fouls). video log had 220 taggable sub-events of these types.
  Aurora Spartans: matched 213/242 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 55/63 are free throws, and 41/51 are fouls). video log had 224 taggable sub-events of these types.
  Simpson Storm: matched 200/220 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 34/34 are free throws, and 20/32 are fouls). video log had 210 taggable sub-events of these types.
  Ripon Red Hawks: matched 200/217 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 49/49 are free throws, and 30/40 are fouls). video log had 208 taggable sub-events of these types.
  Lawrence Vikings: matched 208/227 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 46/46 are free throws, and 30/41 are fouls). video log had 213 taggable sub-events of these types.
  Carroll (WI) Pioneers: matched 214/235 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 45/45 are free throws, and 34/45 are fouls). video log had 220 taggable sub-events of these types.
  Hope Flying Dutchmen: matched 239/258 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 67/67 are free throws, and 40/50 are fouls). video log had 249 taggable sub-events of these types.
  Alma Scots: matched 194/214 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 34/34 are free throws, and 19/32 are fouls). video log had 203 taggable sub-events of these types.
  Elmhurst Bluejays: matched 190/202 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 35/37 are free throws, and 25/34 are fouls). video log had 198 taggable sub-events of these types.
  Coe Kohawks: matched 195/213 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 36/36 are free throws, and 29/35 are fouls). video log had 199 taggable sub-events of these types.
  UW-River Falls Falcons: matched 196/214 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 34/34 are free throws, and 26/36 are fouls). video log had 202 taggable sub-events of these types.
  UW-La Crosse Eagles: matched 231/244 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 58/58 are free throws, and 38/44 are fouls). video log had 237 taggable sub-events of these types.
  UW-Stout Blue Devils: matched 191/214 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 35/35 are free throws, and 26/37 are fouls). video log had 197 taggable sub-events of these types.
  UW-Platteville Pioneers: matched 183/196 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 39/39 are free throws, and 28/37 are fouls). video log had 191 taggable sub-events of these types.
  UW-Eau Claire Blugolds: matched 217/230 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 50/50 are free throws, and 35/44 are fouls). video log had 221 taggable sub-events of these types.
  UW-Oshkosh Titans: matched 236/256 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 59/59 are free throws, and 35/51 are fouls). video log had 242 taggable sub-events of these types.
  UW-Oshkosh Titans: matched 234/252 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 61/61 are free throws, and 40/47 are fouls). video log had 241 taggable sub-events of these types.
  UW-Stevens Point Pointers: matched 220/237 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 60/60 are free throws, and 32/48 are fouls). video log had 228 taggable sub-events of these types.
  UW-Platteville Pioneers: matched 164/176 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 20/20 are free throws, and 19/26 are fouls). video log had 165 taggable sub-events of these types.
  UW-Eau Claire Blugolds: matched 194/212 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 48/48 are free throws, and 31/40 are fouls). video log had 203 taggable sub-events of these types.
  UW-River Falls Falcons: matched 189/202 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 42/42 are free throws, and 28/35 are fouls). video log had 198 taggable sub-events of these types.
  UW-Platteville Pioneers: matched 184/201 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 41/42 are free throws, and 26/38 are fouls). video log had 191 taggable sub-events of these types.
  UW-La Crosse Eagles: matched 198/216 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 51/51 are free throws, and 28/39 are fouls). video log had 203 taggable sub-events of these types.
  UW-La Crosse Eagles: matched 208/227 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 54/56 are free throws, and 32/46 are fouls). video log had 214 taggable sub-events of these types.
  UW-Stout Blue Devils: matched 216/224 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 59/59 are free throws, and 39/43 are fouls). video log had 219 taggable sub-events of these types.
  Loras Duhawks: matched 220/238 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 54/56 are free throws, and 38/42 are fouls). video log had 232 taggable sub-events of these types.
  Washington-St. Louis Bears: matched 169/175 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 18/18 are free throws, and 17/19 are fouls). video log had 171 taggable sub-events of these types.
                 opponent  event_order                   team  \
0   St. Thomas (TX) Celts            0                   None
1   St. Thomas (TX) Celts            1  St. Thomas (TX) Celts
2   St. Thomas (TX) Celts            2          UW-Whitewater
3   St. Thomas (TX) Celts            3  St. Thomas (TX) Celts
4   St. Thomas (TX) Celts            4          UW-Whitewater
5   St. Thomas (TX) Celts            5  St. Thomas (TX) Celts
6   St. Thomas (TX) Celts            6  St. Thomas (TX) Celts
7   St. Thomas (TX) Celts            7          UW-Whitewater
8   St. Thomas (TX) Celts            8          UW-Whitewater
9   St. Thomas (TX) Celts            9  St. Thomas (TX) Celts
10  St. Thomas (TX) Celts           10  St. Thomas (TX) Celts
11  St. Thomas (TX) Celts           11  St. Thomas (TX) Celts
12  St. Thomas (TX) Celts           12          UW-Whitewater
13  St. Thomas (TX) Celts           13  St. Thomas (TX) Celts
14  St. Thomas (TX) Celts           14  St. Thomas (TX) Celts
15  St. Thomas (TX) Celts           15  St. Thomas (TX) Celts
16  St. Thomas (TX) Celts           16  St. Thomas (TX) Celts
17  St. Thomas (TX) Celts           17          UW-Whitewater
18  St. Thomas (TX) Celts           18          UW-Whitewater
19  St. Thomas (TX) Celts           19  St. Thomas (TX) Celts

              player         event_type  \
0                NaN      period_marker
1    Charles Gitonga      jump_ball_won
2       Brock Marino     jump_ball_lost
3     Corey Thompson          made_shot
4       Isaac Verges           turnover
5      Angel Johnson              steal
6     Nathan Kongolo        missed_shot
7      Collin Madson  rebound_defensive
8       Isaac Verges           turnover
9     Nathan Kongolo              steal
10     Angel Johnson          made_shot
11    Nathan Kongolo             assist
12      Isaac Verges        missed_shot
13  Nicholas Buffalo  rebound_defensive
14    Corey Thompson        missed_shot
15    Corey Thompson  rebound_offensive
16    Corey Thompson           turnover
17     Collin Madson          made_shot
18         Luke Bara             assist
19     Angel Johnson          made_shot

                                         raw_text  video_clip_number  \
0                                  Start 1st Half                NaN
1                  Charles Gitonga Wins Jump Ball                NaN
2                    Brock Marino Loses Jump Ball                NaN
3   Corey Thompson Makes 2PT Turnaround Jump Shot                1.0
4               Isaac Verges Turnover (Lost Ball)                2.0
5                            Angel Johnson Steals                NaN
6             Nathan Kongolo Misses 3PT Jump Shot                3.0
7                 Collin Madson Defensive Rebound                NaN
8                Isaac Verges Turnover (Bad Pass)                4.0
9                           Nathan Kongolo Steals                NaN
10                  Angel Johnson Makes 2PT Layup                5.0
11                         Nathan Kongolo Assists                NaN
12                  Isaac Verges Misses 2PT Layup                6.0
13             Nicholas Buffalo Defensive Rebound                NaN
14                Corey Thompson Misses 2PT Layup                7.0
15               Corey Thompson Offensive Rebound                NaN
16                        Corey Thompson Turnover                8.0
17                  Collin Madson Makes 2PT Layup                9.0
18                              Luke Bara Assists                NaN
19      Angel Johnson Makes 2PT Pull Up Jump Shot               10.0

   video_result    video_player  \
0           NaN             NaN
1           NaN             NaN
2           NaN             NaN
3    Make 2 Pts  Corey Thompson
4      Turnover    Isaac Verges
5           NaN             NaN
6    Miss 3 Pts  Nathan Kongolo
7           NaN             NaN
8      Turnover    Isaac Verges
9           NaN             NaN
10   Make 2 Pts   Angel Johnson
11          NaN             NaN
12   Miss 2 Pts    Isaac Verges
13          NaN             NaN
14   Miss 2 Pts  Corey Thompson
15          NaN             NaN
16     Turnover  Corey Thompson
17   Make 2 Pts   Collin Madson
18          NaN             NaN
19   Make 2 Pts   Angel Johnson

                                                                                                           video_description
0                                                                                                                        NaN
1                                                                                                                        NaN
2                                                                                                                        NaN
3                                                       1 Corey Thompson > ISO > Top > Drives Right > To Basket > Make 2 Pts
4                                                                                   0 Isaac Verges > No Play Type > Turnover
5                                                                                                                        NaN
6                            0 Nathan Kongolo > Transition > Left Wing > No Dribble Jumper > Guarded > Long/3pt > Miss 3 Pts
7                                                                                                                        NaN

      opponent   game_date           team                  player  started  PTS  FGM  FGA  FG3M  FG3A  FTM  FTA  OREB  DREB  REB  AST  STL  BLK  TO  PF    FG%    3P%    FT%
0   Alma Scots  2025-12-20     Alma Scots         Donovan Collins     True   17    5   10     5     9    2    3     0     0    0    1    0    0   0   0   50.0   55.6   66.7
16  Alma Scots  2025-12-20  UW-Whitewater         Joey Berezowitz    False   16    6    8     4     5    0    0     2     0    2    0    2    0   0   0   75.0   80.0    NaN
4   Alma Scots  2025-12-20     Alma Scots         Korbin Heitzman     True   14    4   10     0     1    6    8     5    11   16    1    0    1   6   4   40.0    0.0   75.0
11  Alma Scots  2025-12-20  UW-Whitewater           Collin Madson     True   13    4    7     0     0    5    6     1     5    6    3    2    0   0   2   57.1    NaN   83.3
15  Alma Scots  2025-12-20  UW-Whitewater              Jake Quast    False   11    5    7     1     2    0    1     0     3    3    0    3    0   2   3   71.4   50.0    0.0
12  Alma Scots  2025-12-20  UW-Whitewater         Darius Chestnut    False   10    4    4     2     2    0    0     0     0    0    0    0    0   0   2  100.0  100.0    NaN
2   Alma Scots  2025-12-20     Alma Scots            Josh Elliott     True    9    3    7     2     6    1    1     0     3    3    0    1    0   3   1   42.9   33.3  100.0
13  Alma Scots  2025-12-20  UW-Whitewater            Isaac Verges     True    9    4    7     1     2    0    0     0     2    2    1    0    0   1   3   57.1   50.0    NaN
23  Alma Scots  2025-12-20  UW-Whitewater  Tyshawn Teague-Johnson    False    9    4    7     1     1    0    1     1     2    3    2    0    0   2   1   57.1  100.0    0.0
1   Alma Scots  2025-12-20     Alma Scots            Elijah Sykes    False    7    3    9     1     4    0    0     0     0    0    2    1    0   1   0   33.3   25.0    NaN
10  Alma Scots  2025-12-20  UW-Whitewater            Brock Marino     True    7    1    6     0     0    5    6     1     1    2    1    4    0   1   3   16.7    NaN   83.3
6   Alma Scots  2025-12-20     Alma Scots       Luciano Guerrazzi    False    5    2    2     1     1    0    0     1     1    2    1    1    1   5   1  100.0  100.0    NaN
21  Alma Scots  2025-12-20  UW-Whitewater           Richie Warren     True    5    1    6     0     1    3    3     2     2    4    2    3    1   1   2   16.7    0.0  100.0
3   Alma Scots  2025-12-20     Alma Scots            Joss Bradley    False    3    0    2     0     0    3    4     1     1    2    4    0    1   0   2    0.0    NaN   75.0
9   Alma Scots  2025-12-20  UW-Whitewater         Agape Keyes Jr.    False    3    1    1     1     1    0    0     0     0    0    0    1    0   0   1  100.0  100.0    NaN

  ... 684 more row(s) of 699 (SHOW_ROWS = 15)

Found 0 official box-score file(s) to cross-validate against:

Validating PBP-reconstructed per-player box score against the official box-score file, where available:

Every played, scouted game in uww_team_schedule has a box score in pbp_box_score. No gaps found.
Validating lineup-level PTS totals against the schedule:

  St. Thomas (TX) Celts 2025-11-14: lineup box score 73-81 vs. schedule 73.0-81.0 [OK]
  Eureka Red Devils 2025-11-15: lineup box score 116-73 vs. schedule 116.0-73.0 [OK]
  Aurora Spartans 2025-11-19: lineup box score 82-73 vs. schedule 82.0-73.0 [OK]
  Simpson Storm 2025-11-25: lineup box score 100-78 vs. schedule 100.0-78.0 [OK]
  Ripon Red Hawks 2025-11-07: lineup box score 76-58 vs. schedule 76.0-58.0 [OK]
  Lawrence Vikings 2025-12-10: lineup box score 88-58 vs. schedule 88.0-58.0 [OK]
  Carroll (WI) Pioneers 2025-12-13: lineup box score 64-60 vs. schedule 64.0-60.0 [OK]
  Hope Flying Dutchmen 2025-12-19: lineup box score 95-92 vs. schedule 95.0-92.0 [OK]
  Alma Scots 2025-12-20: lineup box score 90-61 vs. schedule 90.0-61.0 [OK]
  Elmhurst Bluejays 2025-12-02: lineup box score 88-72 vs. schedule 88.0-72.0 [OK]
  Coe Kohawks 2025-12-30: lineup box score 73-86 vs. schedule 73.0-86.0 [OK]
  UW-River Falls Falcons 2026-01-10: lineup box score 67-59 vs. schedule 67.0-59.0 [OK]
  UW-La Crosse Eagles 2026-01-14: lineup box score 63-60 vs. schedule 63.0-60.0 [OK]
  UW-Stout Blue Devils 2026-01-17: lineup box score 72-54 vs. schedule 72.0-54.0 [OK]
  UW-Platteville Pioneers 2026-01-21: lineup box score 60-70 vs. schedule 60.0-70.0 [OK]
  UW-Eau Claire Blugolds 2026-01-24: lineup box score 83-76 vs. schedule 83.0-76.0 [OK]
  UW-Oshkosh Titans 2026-01-28: lineup box score 101-91 vs. schedule 101.0-91.0 [OK]
  UW-Oshkosh Titans 2026-01-03: lineup box score 78-90 vs. schedule 78.0-90.0 [OK]
  UW-Stevens Point Pointers 2026-01-07: lineup box score 71-79 vs. schedule 71.0-79.0 [OK]
  UW-Platteville Pioneers 2026-02-11: lineup box score 66-51 vs. schedule 66.0-51.0 [OK]
  UW-Eau Claire Blugolds 2026-02-14: lineup box score 76-68 vs. schedule 76.0-68.0 [OK]
  UW-Stevens Point Pointers 2026-02-18: lineup box score 80-70 vs. schedule 80.0-70.0 [OK]
  UW-River Falls Falcons 2026-02-21: lineup box score 69-62 vs. schedule 69.0-62.0 [OK]
  UW-Platteville Pioneers 2026-02-26: lineup box score 66-56 vs. schedule 66.0-56.0 [OK]
  UW-La Crosse Eagles 2026-02-28: lineup box score 78-81 vs. schedule 78.0-81.0 [OK]
  UW-La Crosse Eagles 2026-02-04: lineup box score 65-68 vs. schedule 65.0-68.0 [OK]
  UW-Stout Blue Devils 2026-02-07: lineup box score 78-77 vs. schedule 78.0-77.0 [OK]
  Loras Duhawks 2026-03-06: lineup box score 85-76 vs. schedule 85.0-76.0 [OK]
  Washington-St. Louis Bears 2026-03-07: lineup box score 71-74 vs. schedule 71.0-74.0 [OK]

,opponent,game_date,team,lineup,MIN,+/-,PTS,FGM,FGA,FG3M,FG3A,FTM,FTA,OREB,DREB,REB,AST,STL,BLK,TO,PF,FG%,3P%,FT%
6,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Korbin Heitzman, Logan St. Martin, ...",12.62,-14.0,11,2,13,2,6,5,6,4,7,11,1,1,0,9,4,15.4,33.3,83.3
8,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Korbin Heitzman, Preston Malpass, R...",3.42,-0.0,9,4,6,1,2,0,1,1,1,2,2,0,0,1,1,66.7,50.0,0.0
9,Alma Scots,2025-12-20,Alma Scots,"Elijah Sykes, Josh Elliott, Joss Bradley, Korbin Heitzman, Logan S...",3.74,1.0,9,3,4,1,2,2,2,0,3,3,1,0,1,3,2,75.0,50.0,100.0
2,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Elijah Sykes, Luciano Guerrazzi, Preston Malpass,...",3.44,-0.0,8,3,6,2,4,0,0,1,1,2,3,3,0,2,1,50.0,50.0,NaN
4,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Joss Bradley, Korbin Heitzman, Luci...",3.55,-6.0,6,1,4,1,4,3,4,2,3,5,1,1,1,2,1,25.0,25.0,75.0
3,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Joss Bradley, Korbin Heitzman, Loga...",3.34,-4.0,5,2,3,0,0,1,2,0,2,2,1,0,2,1,3,66.7,NaN,50.0
0,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Elijah Sykes, Joss Bradley, Korbin Heitzman, Luci...",1.87,2.0,4,2,4,0,0,0,0,0,1,1,1,0,0,0,0,50.0,NaN,NaN
1,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Elijah Sykes, Joss Bradley, Luciano Guerrazzi, Pr...",1.95,3.0,3,1,2,1,1,0,0,0,3,3,1,0,0,1,1,50.0,100.0,NaN
5,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Joss Bradley, Luciano Guerrazzi, Pr...",1.45,-1.0,3,1,2,1,2,0,0,1,1,2,1,0,0,1,1,50.0,50.0,NaN
10,Alma Scots,2025-12-20,Alma Scots,"Elijah Sykes, Josh Elliott, Joss Bradley, Korbin Heitzman, Luciano...",1.82,-4.0,3,1,2,0,1,1,2,2,0,2,0,0,0,1,0,50.0,0.0,50.0
7,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Korbin Heitzman, Luciano Guerrazzi,...",0.03,-0.0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,NaN,NaN,NaN
11,Alma Scots,2025-12-20,Alma Scots,"Elijah Sykes, Josh Elliott, Korbin Heitzman, Preston Malpass, Rain...",1.30,-3.0,0,0,3,0,2,0,0,1,1,2,0,0,0,0,0,0.0,0.0,NaN
12,Alma Scots,2025-12-20,Alma Scots,"Elijah Sykes, Joss Bradley, Korbin Heitzman, Luciano Guerrazzi, Pr...",1.20,-3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,NaN,NaN,NaN
17,Alma Scots,2025-12-20,UW-Whitewater,"Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren",12.04,8.0,21,7,17,1,3,6,7,4,5,9,3,6,0,2,5,41.2,33.3,85.7
22,Alma Scots,2025-12-20,UW-Whitewater,"Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren, Tyshawn ...",3.62,3.0,11,4,7,3,4,0,0,0,2,2,2,1,0,0,1,57.1,75.0,NaN

  ... 1,020 more row(s) of 1,035 (SHOW_ROWS = 15)
Carroll (WI) Pioneers season 5-man lineup box scores (22 game(s) of PBP data, 152 distinct units):
                                                                         lineup  \
0          Evan Bland, Jacob Naber, Lamar Smith, Michael McNabb, Peyton McKenna
1       Dennis Estepp, Jacob Naber, Lamar Smith, Michael McNabb, Peyton McKenna
2      Dennis Estepp, Jacob Naber, Lucas Parker, Michael McNabb, Peyton McKenna
3      Dennis Estepp, Jimmy Tarjan, Lamar Smith, Michael McNabb, Peyton McKenna
4          Dennis Estepp, Greg Smith, Lamar Smith, Lucas Parker, Peyton McKenna
..                                                                          ...
147          Cai Joseph, Dennis Estepp, Evan Bland, Lamar Smith, Peyton McKenna
148            Cai Joseph, Evan Oleson, Greg Smith, Lamar Smith, Peyton McKenna
149        Evan Bland, Evan Oleson, Jacob Naber, Michael McNabb, Peyton McKenna
150          Cai Joseph, Jacob Naber, Jimmy Tarjan, Lamar Smith, Michael McNabb
151  Andrew Hollerich, Evan Oleson, Jacob Naber, Michael McNabb, Peyton McKenna

     GP    MIN   +/-  PTS  FGM  FGA   FG%  FG3M  FG3A  ...  FTA   FT%  OREB  \
0    21  204.8 -78.0  435  163  331  49.2    44   113  ...   92  70.7    75
1    22  154.6 -10.0  316  112  248  45.2    20    83  ...  101  71.3    48
2    14   33.4  -4.0   71   25   53  47.2     8    21  ...   15  86.7     7
3    13   27.7  -8.0   74   27   43  62.8     5    12  ...   21  71.4     6
4    12   27.5   4.0   59   19   44  43.2    13    27  ...   11  72.7     9
..   ..    ...   ...  ...  ...  ...   ...   ...   ...  ...  ...   ...   ...
147   1    0.1   0.0    0    0    0   NaN     0     0  ...    0   NaN     0
148   1    0.0   0.0    0    0    0   NaN     0     0  ...    0   NaN     0
149   1    0.0   2.0    0    0    0   NaN     0     0  ...    0   NaN     0
150   1    0.0  -2.0    0    0    0   NaN     0     0  ...    0   NaN     0
151   1    0.0   0.0    0    0    0   NaN     0     0  ...    0   NaN     0

     DREB  REB  AST  STL  BLK  TO  PF
0     132  207   85   47   15  68  88
1     101  149   43   38    8  48  62
2      21   28   12    9    0  15  19
3      26   32   13    7    3   4  21
4      18   27   13    5    3   8   5
..    ...  ...  ...  ...  ...  ..  ..
147     1    1    0    0    0   0   0
148     0    0    0    0    0   0   0
149     0    0    0    0    0   0   1
150     0    0    0    0    0   0   1
151     0    0    0    0    0   0   0

[152 rows x 22 columns]
Frame archive: 32,487 tracking frame(s) are packed in clip videos -- unpacked automatically when a step reads them.
Frame capture: UWW -- working on 2026-03-07 Washington-St. Louis Bears (45 of 167 clips still untagged -- Analytics > Film Tagging); its next game waits until the coaches finish it.
Frame capture: game pages still to capture -- 1 of the upcoming opponent's (Carroll (WI) Pioneers), 0 of UWW's; UWW games first (VISION_CAPTURE_FIRST), newest first.
Frame capture: 1 game page(s) (all clips)
  [export] 2026-02-24 Carroll (WI) Pioneers vs Elmhurst Bluejays: export 'Carroll(WI)@Elmhurst - Feb 24, 2026'
  [export] Carroll(WI)@Elmhurst - Feb 24, 2026: the export STOPPED at 201 of 234 clip videos (nothing new for 92 min) -- using the 201 there. Disk: 1687.1 GB free; the other 33 clips need about 0.5 GB. Most likely the disk filled up: free space (or set SYNERGY_EXPORT_DIR to the big drive), then export the game again in Synergy Editor (Ctrl+E) into the same folder, or move this folder away so the next run exports it again.
  [export] 2026-02-24 Carroll (WI) Pioneers vs Elmhurst Bluejays: 234 clips in the export (176 after skipping free throws); tracking frames 1920 wide, 4 a second
    25 clip(s) registered (35s)
    50 clip(s) registered (70s)
    75 clip(s) registered (110s)
    100 clip(s) registered (155s)
    125 clip(s) registered (222s)
    150 clip(s) registered (302s)
  [export] 2026-02-24 Carroll (WI) Pioneers vs Elmhurst Bluejays: 160 clip(s) from the export, 0 kept from the earlier web capture, 16 with errors (see the 'error' column) (335s)
  Frames are under ./inputs\_vision_frames -- open a few to check they show the play.
Clips with frames: 1831 of 1861 in uww_clip_frames.csv -- 16 with capture errors (see the 'error' column)
  (15 more row(s) with errors are from an old TEST capture of 2026-03-06 Loras Duhawks -- replaced when that game is captured)
  Capture errors (first 3): clip video not in the export (the export stopped before it, or it is still being written) | clip video not in the export (the export stopped before it, or it is still being written) | clip video not in the export (the export stopped before it, or it is still being written)
  [time] 46_frame_capture: 6.2 min
  Captured clips with no Title: 1298 clip(s) from 9 game(s) not in uww_plays.csv added as play calls (322 placed on the play-by-play clock through the video-tagging match; the rest have no half / clock, so no lineups). The app's Play review is where they get tagged.
  Blank Team on 56 clip(s) (Synergy's Non Shooting Foul clips): filled with the named player's own team -- 55 from his other clips in the game, 0 from the play-by-play (he drew the foul, so his team had the ball)
  Play clips by game type: UWW 784 clip(s) in 6 game(s), Opponent 160 clip(s) in 1 game(s), Other 1098 clip(s) in 6 game(s)
  [saves] fetched branch 'saves': 0 new saved review file(s) copied into data/play_review_saves (47 on the branch; its newest commit: 2026-10-28 11:15:51 -0500  Play review: 2026-02-21|Millikin@WheatonIL by Corey)
  [saves] 46 saved review file(s) read from play_review_saves:
    2025-12-30|WWW@COE: 1 file(s) by Corey (latest 2026-10-05 13:45 UTC) -- 20 play(s) with coach answers
    2026-01-03|WOS@WWW: 12 file(s) by Corey, someone (latest 2026-10-10 00:18 UTC) -- 77 play(s) with coach answers
    2026-02-21|Millikin@WheatonIL: 4 file(s) by Corey (latest 2026-10-28 16:15 UTC) -- 1 play(s) with coach answers
    2026-02-24|WheatonIL@NorthPark: 7 file(s) by Coach Jake, Corey (latest 2026-10-27 14:07 UTC) -- 115 play(s) with coach answers
    2026-02-26|MarianWI@MSOE: 2 file(s) by Coach Jake, CoreyTEST (latest 2026-10-21 15:41 UTC) -- 14 play(s) with coach answers
    2026-03-07|UWWhitewater@Wash(StLouis): 20 file(s) by COACH JAKE, Coach Jake, Corey (latest 2026-10-27 13:54 UTC) -- 137 play(s) with coach answers
  Film Tagging: answers saved before the tracking reset, and test saves, are set aside (TITLE_CHECKS_BEFORE_RESET = True uses the old ones again):
    - 2026-01-03|WOS@WWW by unknown coach, saved 2026-10-01T17:23:50.635Z -- before the restart on the Synergy exports
    - 2026-01-03|WOS@WWW by unknown coach, saved 2026-09-30T18:14:20.554Z -- before the restart on the Synergy exports
    - 2026-01-03|WOS@WWW by unknown coach, saved 2026-10-01T19:48:37.750Z -- before the restart on the Synergy exports
    - 2026-01-03|WOS@WWW by Corey, saved 2026-10-07T19:03:11+00:00 -- before the restart on the Synergy exports
    - 2026-01-03|WOS@WWW by Corey, saved 2026-10-09T00:23:56+00:00 -- before the restart on the Synergy exports
    - 2026-01-03|WOS@WWW by Corey, saved 2026-10-10T00:18:04+00:00 -- before the restart on the Synergy exports
    - 2026-02-26|MarianWI@MSOE by CoreyTEST, saved 2026-10-13T21:18:09+00:00 -- a test save
  App tags: 122 clip(s) tagged in the app (no Title) and 0 coach Title(s) corrected in the app -- used in every play-call table like a Title; 18 play(s) with more than one action recorded
  Lineups: 19 clip(s) with no matched play-by-play event got their uww lineup from the game clock
  Lineups: 19 clip(s) with no matched play-by-play event got their opp lineup from the game clock
  Upcoming-opponent games: 77 clip(s) are the OTHER team's offense -- kept, but excluded from Carroll (WI) Pioneers's play-call scouting.
  Lineups: 16 clip(s) with no matched play-by-play event got their self lineup from the game clock
  Lineups: 16 clip(s) with no matched play-by-play event got their their lineup from the game clock
  App tags: 100 clip(s) tagged in the app (no Title) and 0 coach Title(s) corrected in the app -- used in every play-call table like a Title; 2 play(s) with more than one action recorded
  Frames matched to 1831 of 2042 clip(s) (1861 captured).
    captured page '2025-12-20 Alma Scots': 174 clip(s), 174 matched to tagged clips
    captured page '2025-12-30 Coe Kohawks': 175 clip(s), 175 matched to tagged clips
    captured page '2026-01-03 UW-Oshkosh Titans': 196 clip(s), 196 matched to tagged clips
    captured page '2026-02-21 MSOE Raiders vs Aurora Spartans': 165 clip(s), 165 matched to tagged clips
    captured page '2026-02-21 Wheaton (IL) Thunder vs Millikin B': 179 clip(s), 179 matched to tagged clips
    captured page '2026-02-24 Carroll (WI) Pioneers vs Elmhurst ': 176 clip(s), 160 matched to tagged clips
    captured page '2026-02-24 MSOE Raiders vs Lakeland Muskies': 179 clip(s), 179 matched to tagged clips
    captured page '2026-02-24 Wheaton (IL) Thunder vs North Park': 244 clip(s), 244 matched to tagged clips
    captured page '2026-02-26 MSOE Raiders vs Marian (WI) Sabres': 191 clip(s), 191 matched to tagged clips
    captured page '2026-03-06 Loras Duhawks': 15 clip(s), 1 matched to tagged clips
    captured page '2026-03-07 Washington-St. Louis Bears': 167 clip(s), 167 matched to tagged clips
    tagged game 2026-01-03 WEC@WSP: 140 clip(s), no frames -- a game between two other teams (not UWW or the upcoming opponent), which Frame capture doesn't capture; used from its Titles only
  (frame check: 34 non-possession line(s) (free throws, no violation) in 2025-12-20 WWW@AC have no clip on Synergy's page and are not counted)
  (frame check: 36 non-possession line(s) (free throws, no violation) in 2025-12-30 WWW@COE have no clip on Synergy's page and are not counted)
  (frame check: 1 non-possession line(s) (free throws, no violation) in 2026-01-03 WOS@WWW have no clip on Synergy's page and are not counted)
  play_call_summary: 144 offensive row(s), 124 defensive.
  screen_coverage: 103 tagged screen coverage(s) -- Defenses UWW faced: 54, UWW defense: 49
  screen defense by defender: 5 row(s) (defenders with 2+ tagged screens); action reads: 70 row(s) from Film Tagging's Actions / Players -- 2 team(s), 0 defender reaction row(s)
UWW games: 784 clip(s) across 5 game(s); decoded {'No call': 526, 'App tag': 116, 'Clean': 83, 'Untagged': 58, 'Partial': 1}; matched to play-by-play 679/784 ({'synergy string': 561, 'player + clock': 77, 'clip order + foul by the defense': 24, 'clip order + player': 11, 'clock + result': 6}).
  First unmatched clips (date, period, clock, player, result):

     game_date period  Clock           player                result
0   2025-12-20     H1    NaN  Donovan Collins          No Violation
3   2025-12-20     H1  19:11     Brock Marino            Miss 2 Pts
5   2025-12-20     H1    NaN    Collin Madson          No Violation
8   2025-12-20     H1    NaN    Richie Warren            Free Throw
21  2025-12-20     H1    NaN  Korbin Heitzman  Shot Clock Violation
29  2025-12-20     H1    NaN  Korbin Heitzman            Free Throw

  ... 99 more row(s) of 105 (SHOW_ROWS = 6)
  Most-called: {'5 Out Motion': 95, 'Ball Screen': 15, 'BLOB Line Motion': 7, 'BLOB': 7, 'BLOB Box Motion': 6, 'BLOB Set': 6}
  Shot clock estimated for 679/784 clip(s) (needs a matched pbp event).
  Defense tagged on 264/784 clip(s): {'Man-to-Man': 263, 'ZONE': 1}; press on 67, coverage called on 216.
    Possessions: 399 offensive, 385 defensive -> 163 defense-faced tag(s), 101 defense-played tag(s).
upcoming-opponent games: 160 clip(s) across 1 game(s); decoded {'Untagged': 160}; matched to play-by-play 141/160 ({'synergy string': 108, 'player + clock': 16, 'clock + result': 12, 'clip order + foul by the defense': 3, 'clip order + player': 2}).
  First unmatched clips (date, period, clock, player, result):

     game_date period Clock             player        result
7   2026-02-24   None  None  Sebastian Blachut  No Violation
44  2026-02-24     H1  None      Dennis Estepp  No Violation
48  2026-02-24     H1  None        Lamar Smith    Make 2 Pts
75  2026-02-24     H1  None      Dennis Estepp    Make 3 Pts
78  2026-02-24     H1  None        Aidyn Boone          Foul
81  2026-02-24     H1  None        Jacob Naber          Foul

  ... 13 more row(s) of 19 (SHOW_ROWS = 6)
  Most-called: {}
  Shot clock estimated for 141/160 clip(s) (needs a matched pbp event).
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  CLIP ORDER CHECK: 38 clip(s) sit at a spot in the game video that doesn't match their game clock (captured at the wrong place?):

     game_date game_code period  clip_number  video_start_s   clock                                                            description
0   2025-12-20    WWW@AC     H1            4          356.5  1151.0  21 Brock Marino > Post-Up > Left Block > Right Shoulder > Dribble ...
1   2025-12-20    WWW@AC     H1           12          465.5  1084.0                            24 Richie Warren > Cut > Flash > Miss 2 Pts
2   2025-12-20    WWW@AC     H2          145         4755.5   609.0        12 Jake Quast > Spot-Up > Drives Right > To Basket > Miss 2 Pts
3   2025-12-20    WWW@AC     H2          179         5566.3   238.0  2 Kelton Mcewen > Transition > Ballhandler > Dribble Jumper > Long...
4   2025-12-30   WWW@COE     H2          466         5734.7   810.0                4 Deuce Walters > No Play Type > To Basket > Miss 2 Pts
5   2026-01-03   WOS@WWW     H2           85         2060.2  1191.0                   2 Joey LaChapell > Spot-Up > Drives Right > Turnover
6   2026-01-03   WOS@WWW     H2           87         2088.5  1177.0                      32 Luke Bara > Non Possession > Non Shooting Foul
7   2026-01-03   WOS@WWW     H2           88         2108.6  1175.0                            21 Brock Marino > Cut > Basket > Make 2 Pts
8   2026-01-03   WOS@WWW     H2           89         2118.2  1163.0  4 Michael Metcalf-Grassman > Spot-Up > Drives Right > To Basket > ...
9   2026-01-03   WOS@WWW     H2           90         2130.6  1139.0                              21 Brock Marino > No Play Type > Turnover
10  2026-01-03   WOS@WWW     H2           93         2153.9  1130.0  21 Carter Thomas > Spot-Up > No Dribble Jumper > Guarded > Long/3p...
11  2026-01-03   WOS@WWW     H2           91         2156.0  1134.0  4 Michael Metcalf-Grassman > Transition > Ballhandler > To Basket ...
12  2026-01-03   WOS@WWW     H2           95         2196.9  1104.0                           24 Richie Warren > Cut > Basket > Miss 2 Pts
13  2026-01-03   WOS@WWW     H2           96         2220.4  1087.0  23 Oskar Kangas > P&R Ball Handler > Right P&R > Baseline > Dribbl...
14  2026-01-03   WOS@WWW     H2           97         2236.5  1067.0  15 Collin Madson > ISO > Right > Drives Right > To Basket > Miss 2...

  ... 23 more row(s) of 38 (SHOW_ROWS = 15)
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  [reuse] uww_player_tracks: the last run's 44,090 row(s)
  [reuse] uww_tracking_report: the last run's 2 row(s)
  [reuse] uww_trk_event_candidates: the last run's 23 row(s)
  [reuse] uww_trk_lineup_slots: the last run's 4,080 row(s)
  [reuse] player tracking (switched off this run): the last run's results put back on 167 clip(s) (18 column(s))
  [reuse] tag model (switched off this run): the last run's results put back on 784 clip(s) (21 column(s))
  [reuse] uww_tag_model_report: the last run's 10 row(s)
  Automatic answers used for untagged plays / prefilled in Film Tagging: defense, situation | offered as 'not sure' only: formation, play_call, press, primary_action, ball_screen_coverage, offball_coverage, screener, screen_defender
  Tag model history: 1 field(s) changed since the last run -> uww_tag_model_history.csv (the app: Analytics > Film Tagging > How good is the automatic tagging?)
Film Tagging: checking which of 873 captured clip(s) still have their film on disk...
Film Tagging: reading the coaches' saved answers...
Film Tagging: answer lists -- Situation 7, Formation 20, Play call 37, Main action 41, Defense 2, Press 6, Ball-screen coverage 16, Off-ball coverage 17, Screener 36, Screen defender 34
Film Tagging: removed the open batch for 2026-01-03 UWOshkosh@UWWhitewater from the app -- not part of this run (answers already saved are kept)
Film Tagging: 2026-02-24 Carroll(WI)@Elmhurst: making the video of each of 83 play(s) for the app...
  [film tagging] Carroll(WI)@Elmhurst play videos made: 0 / 83 (0%) -- 0.0 min so far
  [film tagging] Carroll(WI)@Elmhurst play videos made: 3 / 83 (3%) -- 0.5 min so far, ~13.4 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 5 / 83 (6%) -- 1.2 min so far, ~18.9 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 8 / 83 (9%) -- 1.8 min so far, ~16.8 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 10 / 83 (12%) -- 2.1 min so far, ~15.2 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 13 / 83 (15%) -- 2.6 min so far, ~14.0 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 15 / 83 (18%) -- 3.0 min so far, ~13.6 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 19 / 83 (22%) -- 3.5 min so far, ~11.8 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 20 / 83 (24%) -- 3.6 min so far, ~11.5 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 24 / 83 (28%) -- 4.2 min so far, ~10.3 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 25 / 83 (30%) -- 4.4 min so far, ~10.1 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 29 / 83 (34%) -- 5.0 min so far, ~9.3 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 30 / 83 (36%) -- 5.1 min so far, ~9.1 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 34 / 83 (40%) -- 5.7 min so far, ~8.2 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 35 / 83 (42%) -- 5.8 min so far, ~8.0 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 38 / 83 (45%) -- 6.4 min so far, ~7.6 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 40 / 83 (48%) -- 6.6 min so far, ~7.1 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 44 / 83 (53%) -- 7.3 min so far, ~6.4 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 48 / 83 (57%) -- 7.8 min so far, ~5.7 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 50 / 83 (60%) -- 8.2 min so far, ~5.4 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 54 / 83 (65%) -- 8.7 min so far, ~4.7 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 55 / 83 (66%) -- 8.9 min so far, ~4.5 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 58 / 83 (69%) -- 9.5 min so far, ~4.1 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 60 / 83 (72%) -- 9.8 min so far, ~3.8 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 64 / 83 (77%) -- 10.4 min so far, ~3.1 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 65 / 83 (78%) -- 10.5 min so far, ~2.9 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 68 / 83 (81%) -- 11.0 min so far, ~2.4 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 70 / 83 (84%) -- 11.2 min so far, ~2.1 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 74 / 83 (89%) -- 11.8 min so far, ~1.4 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 75 / 83 (90%) -- 12.0 min so far, ~1.3 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 78 / 83 (93%) -- 12.6 min so far, ~0.8 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 80 / 83 (96%) -- 13.1 min so far, ~0.5 min left
  [film tagging] Carroll(WI)@Elmhurst play videos made: 83 / 83 (100%) -- 13.5 min so far
  [film tagging] copying Carroll(WI)@Elmhurst's batch into the app's data folder...
  [play review] copied to the app: ../data\play_tag\tag_2026_02_24_Carroll_WI_Elmhurst (233 MB) -- commit and push it with the data
Film Tagging: 2026-02-24 Carroll(WI)@Elmhurst: 83 clip(s) to tag -- the scouted team's offense (every untagged play; the rest once those are tagged) (of 160 untagged) -- in the app: Analytics > Film Tagging
  [saves] fetched branch 'saves': 0 new saved review file(s) copied into data/play_review_saves (47 on the branch; its newest commit: 2026-10-28 11:15:51 -0500  Play review: 2026-02-21|Millikin@WheatonIL by Corey)
Film Tagging -- tagging progress by game (Titles + app tags):
  2026-02-24 Carroll(WI)@Elmhurst: 0 of 160 clip(s) tagged, 160 to go
  2026-03-07 UWWhitewater@Wash(StLouis): 122 of 167 clip(s) tagged, 45 to go
Film Tagging: 4 game(s) with film left out -- not part of this run (the upcoming opponent's games and our most recent game; PLAY_TAG_RUN_ONLY = False tags every game): 2025-12-20 WWW@AC; 2025-12-30 WWW@COE; 2026-01-03 UWOshkosh@UWWhitewater; 2026-01-03 WOS@WWW
  [answer lists] updated in 4 open batch(es) in the app -- commit and push the data
  [time] 55c_play_review: 13.7 min
Run time: 22 min across 47 section(s) -- the slowest:
    13.7 min  55c_play_review
     6.2 min  46_frame_capture
     1.0 min  02_parse_every_team_schedule_scrape_live_from
     0.3 min  36_parse_play_by_play_mhtml_files_into
     0.3 min  47_play_calls
     0.2 min  26_parse_play_by_play_events_for_opponent
     0.2 min  46a_frame_archive
     0.1 min  08_parse_each_opponent_fastscout_scoutbuilder
     0.1 min  21_roster_pages
     0.1 min  41b_offensive_roles
     0.0 min  41_attach_video_tagging_clip_descriptions_2
     0.0 min  28_attach_video_tagging_clip_descriptions
[tagging] saved 1 table(s) to ../data -- commit and push the data folder for the app
[tagging] skipped 46 section(s) this job doesn't need: 48_jersey_number_recognizer, 49_jersey_number_reader_test, 50c_outfit_check, 50d_reid_check, 51_court_mapping, 54_tracking_insights, 55_court_insights, 55d_defensive_roles, 55e_film_quality, 56_compute_biggest_scoring_runs_and_largest, 57_surface_clutch_time_events_with_lineup, 58_cross_reference_actual_pbp_turnovers, 59_cross_reference_actual_pbp_rebounding, 60_compute_scoring_margin_and_minutes_played, 61_add_minutes_played_onto_reconstructed_box, 62_identify_lineups_on_court_during_each_team, 63_season_wide_5_man_lineup_analysis_across, 64_uww_performance_vs_opponent_lineup_profile, 65_diagnose_spot_up_struggles, 66_check_contest_mechanic_patterns_across_all, 67_contest_level, 68_investigate_why_guarded_catch_and_shoot, 69_structured_coaching_flags_recommendations, 70_expected_box_score_for_upcoming_game, 71_reconstruct_box_score_for_opponent_games, 72_minutes_played_for_upcoming_opponent_prior, 73_replace_upcoming_opponent_pdf_scouting, 74_replace_upcoming_opponent_team_totals_with, 75_back_fill_past_scouted_opponents_player, 76_rebuild_player_comparisons_with_pbp, 77_rebuild_player_comparisons_with_pbp_2, 78_rebuild_player_comparisons_with_pbp_3, 79_head_to_head, 80_head_to_head_2, 81_extract_and_save_team_logos_from_pbp_mhtml, 82_extract_player_headshots_from_scouting, 83_assemble_every_key_to_victory_into_one, 84_style_matchups, 85_scouting_notes_and_keys_to_defending, 86_game_plan, 86b_two_for_one, 87_build_html_scouting_brief_for_upcoming, 88_tracking_review_export, 46a_frame_archive, 89_cleanup, 90_model_versions

### Continue

In [4]:
# Continue from a section after an error, e.g.:
# run_parser("tagging", start_at="55c_play_review")