
## UW-Whitewater Scouting Parser (portable version)

Parses UW-Whitewater's own schedule/box-score, each scouted opponent's schedule and FastScout "ScoutBuilder" game-plan PDF, and (further down) play-by-play + video-tagging exports -- turning them into player/lineup-level scouting data, cross-checked against actual results. Ported from a Databricks notebook to run locally via Databricks Connect (Playwright/asyncio/subprocess-based scraping runs on the local machine, not the remote cluster); Databricks-only APIs (`dbutils`, `display()`, widgets, Spark table writes) were swapped for plain Python equivalents everywhere.

### Configuration

Edit `INPUT_DIR`/`OUTPUT_DIR`/`USE_LLM`/`reference_date_str` below for your local setup -- everything downstream reads from these instead of hardcoded paths or Databricks widgets.

In [3]:
# --- Setup: the parser's code lives in parser_lib\ (one .py file per section) --------------------------------------
# Each section cell below holds only its SETTINGS and then runs its code with run_section("<file>"). The code runs
# inside this notebook exactly as if it were still in the cell -- every function and table it makes is available to
# the cells after it. To change how something works, open parser_lib\<file>.py; to change a setting, edit the cell.
import os
PARSER_LIB = os.path.join(os.getcwd(), "parser_lib")


def run_section(name):
    """Run parser_lib/<name>.py inside this notebook (same variables as if the code were in the cell)."""
    path = os.path.join(PARSER_LIB, name if name.endswith(".py") else name + ".py")
    if not os.path.exists(path):
        raise FileNotFoundError(f"{path} not found -- keep the parser_lib folder next to this notebook")
    with open(path, encoding="utf-8") as fh:
        src = fh.read()
    exec(compile(src, path, "exec"), globals())

In [4]:
# UW-Whitewater Schedule and Scout Report Parser -- Portable Version
# Code: parser_lib\01_uw_whitewater_scouting_parser.py  --  settings below, then the section runs.
# --- Configuration -- edit these to match your local setup ---
INPUT_DIR = "./inputs"    # directory containing MHTML/PDF input files
OUTPUT_DIR = "../data"    # directory to write CSV output files
USE_LLM = False            # set True to enable LLM-based player comparisons (requires OPENAI_API_KEY)
APP_BASE_URL = "" or os.environ.get("UWW_APP_URL", "")
SHOW_ROWS = 15            # most tables print as a neat table capped at this many rows (the full table is still in memory / the CSVs)

run_section("01_uw_whitewater_scouting_parser")

Input directory: ./inputs
Output directory: ../data
LLM comparisons: disabled
Reference date: 2026-1-7
Before scout: yes -- ignoring the upcoming opponent's own scouting report for this run
WARNING: APP_BASE_URL is blank -- the scouting brief will render every app link as dead "(in the app)" text. Set APP_BASE_URL in this cell (or the UWW_APP_URL env var) to make the brief's links actually open the app.


### Legacy install/restart cells (disabled)

These two cells mirror the original Databricks notebook's `%pip install lxml` + `dbutils.library.restartPython()` steps, kept only for parity -- both are commented out here since the portable setup installs dependencies via `requirements.txt` ahead of time, and there's no Databricks kernel to restart outside the web UI.

In [6]:
# %pip install -q lxml

In [7]:
# dbutils.library.restartPython()


### Parse every team's schedule; scrape live from FastScout with a local backup fallback

The largest cell in this notebook -- kept as one block rather than split further, since it's a single, carefully-debugged live-scraping engine and separating it risks pulling apart tightly-coupled state (like the shared Playwright session) from the functions that manage it. It:

* Defines the MHTML/HTML loading helpers (`load_html_snapshot`, `_save_scraped_html`) shared by every other scraping step in this notebook (schedules, scouting-report PDFs, play-by-play, video tagging).
* Defines the one shared, lazily-opened, self-healing FastScout Playwright session (`run_in_fastscout_session`) -- reused everywhere else a live scrape is needed instead of opening a new browser per call.
* Scrapes UW-Whitewater's own schedule and every opponent's schedule live (skipping the live scrape when a local backup file already exists), falling back to a local `"<Team> - Schedule.mhtml"`/`".html"` snapshot when live scraping is unavailable or fails.
* Downloads any missing scouting-report PDF straight from FastScout.
* Produces `schedule`, `team_schedules`, and `scouted_opponents`, used throughout the rest of the notebook.

In [9]:
# Every team's own FastScout schedule snapshot (MHTML) lives in INPUT_DIR alongside per-game pbp/video/box
# Code: parser_lib\02_parse_every_team_schedule_scrape_live_from.py  --  settings below, then the section runs.
FASTSCOUT_ORIGIN = "https://fastscout.fastmodelsports.com"
FASTSCOUT_DOCS_LEAGUE = "NCAAB-III"
FASTSCOUT_DOCS_SEASON = "25"

run_section("02_parse_every_team_schedule_scrape_live_from")

Found 22 schedule MHTML file(s) in ./inputs:
 - Alma Scots - Schedule.html
 - Aurora Spartans - Schedule.html
 - Carroll (WI) Pioneers - Schedule.html
 - Coe Kohawks - Schedule.html
 - Elmhurst Bluejays - Schedule.html
 - Eureka Red Devils - Schedule.html
 - Hope Flying Dutchmen - Schedule.html
 - Lawrence Vikings - Schedule.html
 - Loras Duhawks - Schedule.html
 - Ripon Red Hawks - Schedule.html
 - Simpson Storm - Schedule.html
 - St. Thomas (TX) Celts - Schedule.html
 - UW-Eau Claire Blugolds - Schedule.html
 - UW-La Crosse Eagles - Schedule.html
 - UW-Oshkosh Titans - Schedule.html
 - UW-Platteville Pioneers - Schedule.html
 - UW-River Falls Falcons - Schedule.html
 - UW-Stevens Point Pointers - Schedule.html
 - UW-Stout Blue Devils - Schedule.html
 - UW-Whitewater - Schedule.mhtml
 - UW-Whitewater - Schedule_2023.html
 - UW-Whitewater - Schedule_2024.html
  [before_scout=yes] Ignoring 12 scouting report(s) dated on/after 2026-1-7: ['1_10_26 UW-Whitewater @ UW-River Falls Falcons_scout.html', '1_14_26 UW-Whitewater @ UW-La Crosse Eagles_scout.html', '1_17_26 UW-Stout Blue Devils @ UW-Whitewater_scout.html', '1_21_26 UW-Whitewater @ UW-Platteville Pioneers_scout.html', '1_24_26 UW-Eau Claire Blugolds @ UW-Whitewater_scout.html', '1_7_26 UW-Stevens Point Pointers @ UW-Whitewater_scout.html', '2_11_26 UW-Platteville Pioneers @ UW-Whitewater_scout.html', '2_14_26 UW-Whitewater @ UW-Eau Claire Blugolds_scout.html', '2_4_26 UW-La Crosse Eagles @ UW-Whitewater_scout.html', '2_7_26 UW-Whitewater @ UW-Stout Blue Devils_scout.html', '3_6_26 UW-Whitewater @ Loras Duhawks_scout.html', '3_7_26 UW-Whitewater @ Washington-St. Louis Bears_scout.html']
Detected season 2025 from UWW's local schedule snapshot -- using FASTSCOUT_DOCS_SEASON='25' for any live-scrape URLs below (was hardcoded to '25').
Skipping live scrape for UW-Whitewater's own schedule -- a local schedule file already exists: UW-Whitewater - Schedule.mhtml
Excluding 16 game(s) scheduled beyond the next upcoming game -- not downloading those reports yet.
[before_scout=yes] Not downloading a scouting report for the upcoming 01/07/26 game.

Every game already has a local scouting-report PDF, or is missing required data -- nothing to download from FastScout. (29 raw game(s) found; 0 missing opponent_url, 0 missing a parseable date.)
  [before_scout=yes] Ignoring 12 scouting report(s) dated on/after 2026-1-7: ['1_10_26 UW-Whitewater @ UW-River Falls Falcons_scout.html', '1_14_26 UW-Whitewater @ UW-La Crosse Eagles_scout.html', '1_17_26 UW-Stout Blue Devils @ UW-Whitewater_scout.html', '1_21_26 UW-Whitewater @ UW-Platteville Pioneers_scout.html', '1_24_26 UW-Eau Claire Blugolds @ UW-Whitewater_scout.html', '1_7_26 UW-Stevens Point Pointers @ UW-Whitewater_scout.html', '2_11_26 UW-Platteville Pioneers @ UW-Whitewater_scout.html', '2_14_26 UW-Whitewater @ UW-Eau Claire Blugolds_scout.html', '2_4_26 UW-La Crosse Eagles @ UW-Whitewater_scout.html', '2_7_26 UW-Whitewater @ UW-Stout Blue Devils_scout.html', '3_6_26 UW-Whitewater @ Loras Duhawks_scout.html', '3_7_26 UW-Whitewater @ Washington-St. Louis Bears_scout.html']
  UW-Whitewater Warhawks (UW-Whitewater - Schedule.mhtml): 13 game(s) -- scouted opponents: ['St. Thomas (TX) Celts', 'Eureka Red Devils', 'Aurora Spartans', 'Simpson Storm', 'Ripon Red Hawks', 'Lawrence Vikings', 'Carroll (WI) Pioneers', 'Hope Flying Dutchmen', 'Alma Scots', 'Elmhurst Bluejays', 'Coe Kohawks', 'UW-Oshkosh Titans']

Fetching 13 opponent schedule(s) (scrape opponent_url, MHTML backup on failure):
    [login] navigating to https://fastscout.fastmodelsports.com/teams/myTeam/analytics/dashboard?league=NCAAB-III&season=25
    [auth-retry] got redirected to identity.hudl.com while waiting on https://fastscout.fastmodelsports.com/teams/myTeam/analytics/dashboard?league=NCAAB-III&season=25 -- logging in and retrying
    [auth-retry] login_to_fastscout returned, now at https://fastscout.fastmodelsports.com/#access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZaYjBkN0VpWG9TQ0FhUTdYaW90SCJ9.eyJodHRwczovL2lkZW50aXR5Lmh1ZGwuY29tL2Nvbm5lY3Rpb25fbmFtZSI6InByb2QtaHVkbC11c2Vycy10ZXJyYWZvcm0iLCJodHRwczovL2lkZW50aXR5Lmh1ZGwuY29tL3VzZXJfaWQiOiI2NDM1MDQ3IiwiaHR0cHM6Ly9pZGVudGl0eS5odWRsLmNvbS90b2siOiJpZCIsImh0dHBzOi8vaWRlbnRpdHkuaHVkbC5jb20vaXNfc3lzYWRtaW4iOmZhbHNlLCJodHRwczovL2lkZW50aXR5Lmh1ZGwuY29tL2ludGVybmFsX2lkX2h1ZGwiOiI2NDM1MDQ3IiwiZ2l2ZW5fbmFtZSI6IkNvcmV5IiwiZmFtaWx5X25hbWUiOiJGcml0c2NoIiwibmlja25hbWUiOiJmcml0c2NoY20yNyIsIm5hbWUiOiJmcml0c2NoY20yN0BnbWFpbC5jb20iLCJwaWN0dXJlIjoiaHR0cHM6Ly9zLmdyYXZhdGFyLmNvbS9hdmF0YXIvOTY3OWI2Mzk1N2E1ZTJmZmE2NjMyYWZhYjVmMGExYTU_cz00ODAmcj1wZyZkPWh0dHBzJTNBJTJGJTJGY2RuLmF1dGgwLmNvbSUyRmF2YXRhcnMlMkZmci5wbmciLCJ1cGRhdGVkX2F0IjoiMjAyNi0xMC0wN1QxNDo0OTo1NC4wNjRaIiwiZW1haWwiOiJmcml0c2NoY20yN0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5odWRsLmNvbS8iLCJhdWQiOiJ1UFJyRFVpWkZOU3d2RnJ0cnVsQ3lBWDBwaDZBckx6VSIsInN1YiI6ImF1dGgwfGh1ZGx8NjQzNTA0NyIsImlhdCI6MTc5MTM4NDU5NCwiZXhwIjoxNzkyNTk0MTk0LCJzaWQiOiJGdXo1c3FLNUtwX05XSTFVSWNWTHZGOGRYOHNrcWdvVSIsImNfaGFzaCI6ImN5dkRnVGxBZmxTcUExckdwR2JGYlEiLCJub25jZSI6IjA4YmZmMzkyLTM3ZmEtNDM5Ni04ZDgxLTQwMmRiNThmNTY3ZSJ9.Ir6Vx2S4DI_yQ47QURQwG19wgOsN0KjxoPgfomFIgLj_VW0YN65jjHHBPmN6TiRrxlHCWwL9HbCJL_BoU-IT-EuTAXiwJlPO1SdB7Pw42w8f08mT-e56oOoSUzfPAgxPmQ9H1YAIYwYEiVk9OYknfYM9QPXUAerbDSWataUj-0BFKuzv82S8kkROcF8MjVR6ecuT7Ix6QjUmQ6FeoqChZuxpeyI2xdMx60ZIHNo0jLzefmFiOcbA7qKwFkDoWtsc6XOhNq9FppZw_wsuIo85ixXJcdLzeCbx75gJEFbrlJGUnnPYsYvlqtm_Z8KufIn4zVBZn1amA5gFaKiyxriedA&token_type=Bearer&expires_at=1792594194 -- re-navigating to https://fastscout.fastmodelsports.com/teams/myTeam/analytics/dashboard?league=NCAAB-III&season=25
    [auth-retry] re-navigated, now at https://fastscout.fastmodelsports.com/teams/myTeam/analytics/dashboard?league=NCAAB-III&season=25 -- waiting for 'text=SCHEDULE'
    [login] confirmed logged in, landed on https://fastscout.fastmodelsports.com/teams/myTeam/analytics/dashboard?league=NCAAB-III&season=26
    [login] WARNING: requested season='25' but FastScout's "myTeam" redirect landed on season='26' instead -- this account's "current" season has moved on. Any view reached via "myTeam" from here (e.g. the live schedule scrape below) may now be showing season 26 data instead of season 25. Verify the scraped schedule's games actually belong to the intended season before trusting this run's output.
    [save] myTeam analytics dashboard (diagnostic) -> myTeam - Analytics Dashboard.html
  Skipping live scrape for Ripon Red Hawks -- a local schedule file already exists.
  Skipping live scrape for St. Thomas (TX) Celts -- a local schedule file already exists.
  Skipping live scrape for Eureka Red Devils -- a local schedule file already exists.
  Skipping live scrape for Aurora Spartans -- a local schedule file already exists.
  Skipping live scrape for Simpson Storm -- a local schedule file already exists.
  Skipping live scrape for Elmhurst Bluejays -- a local schedule file already exists.
  Skipping live scrape for Lawrence Vikings -- a local schedule file already exists.
  Skipping live scrape for Carroll (WI) Pioneers -- a local schedule file already exists.
  Skipping live scrape for Hope Flying Dutchmen -- a local schedule file already exists.
  Skipping live scrape for Alma Scots -- a local schedule file already exists.
  Skipping live scrape for Coe Kohawks -- a local schedule file already exists.
  Skipping live scrape for UW-Oshkosh Titans -- a local schedule file already exists.
  Skipping live scrape for UW-Stevens Point Pointers -- a local schedule file already exists.
  Falling back to local backup MHTML for Ripon Red Hawks: Ripon Red Hawks - Schedule.html
  Ripon Red Hawks (Ripon Red Hawks - Schedule.html): 14 game(s) -- all games before 2026-1-7
  Falling back to local backup MHTML for St. Thomas (TX) Celts: St. Thomas (TX) Celts - Schedule.html
  St. Thomas (TX) Celts (St. Thomas (TX) Celts - Schedule.html): 12 game(s) -- all games before 2026-1-7
  Falling back to local backup MHTML for Eureka Red Devils: Eureka Red Devils - Schedule.html
  Eureka Red Devils (Eureka Red Devils - Schedule.html): 14 game(s) -- all games before 2026-1-7
  Falling back to local backup MHTML for Aurora Spartans: Aurora Spartans - Schedule.html
  Aurora Spartans (Aurora Spartans - Schedule.html): 12 game(s) -- all games before 2026-1-7
  Falling back to local backup MHTML for Simpson Storm: Simpson Storm - Schedule.html
  Simpson Storm (Simpson Storm - Schedule.html): 13 game(s) -- all games before 2026-1-7
  Falling back to local backup MHTML for Elmhurst Bluejays: Elmhurst Bluejays - Schedule.html
  Elmhurst Bluejays (Elmhurst Bluejays - Schedule.html): 12 game(s) -- all games before 2026-1-7
  Falling back to local backup MHTML for Lawrence Vikings: Lawrence Vikings - Schedule.html
  Lawrence Vikings (Lawrence Vikings - Schedule.html): 13 game(s) -- all games before 2026-1-7
  Falling back to local backup MHTML for Carroll (WI) Pioneers: Carroll (WI) Pioneers - Schedule.html
  Carroll (WI) Pioneers (Carroll (WI) Pioneers - Schedule.html): 12 game(s) -- all games before 2026-1-7
  Falling back to local backup MHTML for Hope Flying Dutchmen: Hope Flying Dutchmen - Schedule.html
  Hope Flying Dutchmen (Hope Flying Dutchmen - Schedule.html): 11 game(s) -- all games before 2026-1-7
  Falling back to local backup MHTML for Alma Scots: Alma Scots - Schedule.html
  Alma Scots (Alma Scots - Schedule.html): 13 game(s) -- all games before 2026-1-7
  Falling back to local backup MHTML for Coe Kohawks: Coe Kohawks - Schedule.html
  Coe Kohawks (Coe Kohawks - Schedule.html): 15 game(s) -- all games before 2026-1-7
  Falling back to local backup MHTML for UW-Oshkosh Titans: UW-Oshkosh Titans - Schedule.html
  UW-Oshkosh Titans (UW-Oshkosh Titans - Schedule.html): 12 game(s) -- all games before 2026-1-7
  Falling back to local backup MHTML for UW-Stevens Point Pointers: UW-Stevens Point Pointers - Schedule.html
  UW-Stevens Point Pointers (UW-Stevens Point Pointers - Schedule.html): 13 game(s) -- all games before 2026-1-7
            date                opponent                       team  \
0     Fri, Nov 7         Ripon Red Hawks     UW-Whitewater Warhawks
1    Fri, Nov 14   St. Thomas (TX) Celts     UW-Whitewater Warhawks
2    Sat, Nov 15       Eureka Red Devils     UW-Whitewater Warhawks
3    Wed, Nov 19         Aurora Spartans     UW-Whitewater Warhawks
4    Tue, Nov 25           Simpson Storm     UW-Whitewater Warhawks
..           ...                     ...                        ...
174  Sat, Dec 13           Olivet Comets  UW-Stevens Point Pointers
175  Sat, Dec 20  Hardin-Simmons Cowboys  UW-Stevens Point Pointers
176  Sun, Dec 21     Trinity (TX) Tigers  UW-Stevens Point Pointers
177  Mon, Dec 29        Lakeland Muskies  UW-Stevens Point Pointers
178   Sat, Jan 3  UW-Eau Claire Blugolds  UW-Stevens Point Pointers

          location                                       opponent_url  \
0             Away  https://fastscout.fastmodelsports.com/teams/NY...
1    Neutral Court  https://fastscout.fastmodelsports.com/teams/an...
2    Neutral Court  https://fastscout.fastmodelsports.com/teams/jV...
3             Home  https://fastscout.fastmodelsports.com/teams/Ux...
4             Home  https://fastscout.fastmodelsports.com/teams/gJ...
..             ...                                                ...
174           Away  https://fastscout.fastmodelsports.com/teams/s7...
175  Neutral Court  https://fastscout.fastmodelsports.com/teams/J7...
176           Away  https://fastscout.fastmodelsports.com/teams/tQ...
177           Home  https://fastscout.fastmodelsports.com/teams/2V...
178           Home  https://fastscout.fastmodelsports.com/teams/u9...

                                              game_url  \
0    https://fastscout.fastmodelsports.com/teams/YN...
1    https://fastscout.fastmodelsports.com/teams/YN...
2    https://fastscout.fastmodelsports.com/teams/YN...
3    https://fastscout.fastmodelsports.com/teams/YN...
4    https://fastscout.fastmodelsports.com/teams/YN...
..                                                 ...
174  https://fastscout.fastmodelsports.com/teams/Oq...
175  https://fastscout.fastmodelsports.com/teams/Oq...
176  https://fastscout.fastmodelsports.com/teams/Oq...
177  https://fastscout.fastmodelsports.com/teams/Oq...
178  https://fastscout.fastmodelsports.com/teams/Oq...

                                             video_url outcome  team_score  \
0    https://editor-web.synergysports.com/video?pla...       W        76.0
1    https://editor-web.synergysports.com/video?pla...       L        73.0
2    https://editor-web.synergysports.com/video?pla...       W       116.0
3    https://editor-web.synergysports.com/video?pla...       W        82.0
4    https://editor-web.synergysports.com/video?pla...       W       100.0
..                                                 ...     ...         ...
174  https://editor-web.synergysports.com/video?pla...       W        76.0
175  https://editor-web.synergysports.com/video?pla...       W        65.0
176  https://editor-web.synergysports.com/video?pla...       W        74.0
177  https://editor-web.synergysports.com/video?pla...       W        87.0
178  https://editor-web.synergysports.com/video?pla...       W        78.0

     opponent_score  point_margin   season Upcoming
0              58.0          18.0  2025-26       No
1              81.0          -8.0  2025-26       No
2              73.0          43.0  2025-26       No
3              73.0           9.0  2025-26       No
4              78.0          22.0  2025-26       No
..              ...           ...      ...      ...
174            63.0          13.0  2025-26       No
175            61.0           4.0  2025-26       No
176            66.0           8.0  2025-26       No
177            70.0          17.0  2025-26       No
178            75.0           3.0  2025-26       No

[179 rows x 13 columns]


### Preview `schedule`

In [11]:
schedule

,date,opponent,team,location,opponent_url,game_url,video_url,outcome,team_score,opponent_score,point_margin,season,Upcoming
0,"Fri, Nov 7",Ripon Red Hawks,UW-Whitewater Warhawks,Away,https://fastscout.fastmodelsports.com/teams/NY...,https://fastscout.fastmodelsports.com/teams/YN...,https://editor-web.synergysports.com/video?pla...,W,76.0,58.0,18.0,2025-26,No
1,"Fri, Nov 14",St. Thomas (TX) Celts,UW-Whitewater Warhawks,Neutral Court,https://fastscout.fastmodelsports.com/teams/an...,https://fastscout.fastmodelsports.com/teams/YN...,https://editor-web.synergysports.com/video?pla...,L,73.0,81.0,-8.0,2025-26,No
2,"Sat, Nov 15",Eureka Red Devils,UW-Whitewater Warhawks,Neutral Court,https://fastscout.fastmodelsports.com/teams/jV...,https://fastscout.fastmodelsports.com/teams/YN...,https://editor-web.synergysports.com/video?pla...,W,116.0,73.0,43.0,2025-26,No
3,"Wed, Nov 19",Aurora Spartans,UW-Whitewater Warhawks,Home,https://fastscout.fastmodelsports.com/teams/Ux...,https://fastscout.fastmodelsports.com/teams/YN...,https://editor-web.synergysports.com/video?pla...,W,82.0,73.0,9.0,2025-26,No
4,"Tue, Nov 25",Simpson Storm,UW-Whitewater Warhawks,Home,https://fastscout.fastmodelsports.com/teams/gJ...,https://fastscout.fastmodelsports.com/teams/YN...,https://editor-web.synergysports.com/video?pla...,W,100.0,78.0,22.0,2025-26,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,"Sat, Dec 13",Olivet Comets,UW-Stevens Point Pointers,Away,https://fastscout.fastmodelsports.com/teams/s7...,https://fastscout.fastmodelsports.com/teams/Oq...,https://editor-web.synergysports.com/video?pla...,W,76.0,63.0,13.0,2025-26,No
175,"Sat, Dec 20",Hardin-Simmons Cowboys,UW-Stevens Point Pointers,Neutral Court,https://fastscout.fastmodelsports.com/teams/J7...,https://fastscout.fastmodelsports.com/teams/Oq...,https://editor-web.synergysports.com/video?pla...,W,65.0,61.0,4.0,2025-26,No
176,"Sun, Dec 21",Trinity (TX) Tigers,UW-Stevens Point Pointers,Away,https://fastscout.fastmodelsports.com/teams/tQ...,https://fastscout.fastmodelsports.com/teams/Oq...,https://editor-web.synergysports.com/video?pla...,W,74.0,66.0,8.0,2025-26,No
177,"Mon, Dec 29",Lakeland Muskies,UW-Stevens Point Pointers,Home,https://fastscout.fastmodelsports.com/teams/2V...,https://fastscout.fastmodelsports.com/teams/Oq...,https://editor-web.synergysports.com/video?pla...,W,87.0,70.0,17.0,2025-26,No
178,"Sat, Jan 3",UW-Eau Claire Blugolds,UW-Stevens Point Pointers,Home,https://fastscout.fastmodelsports.com/teams/u9...,https://fastscout.fastmodelsports.com/teams/Oq...,https://editor-web.synergysports.com/video?pla...,W,78.0,75.0,3.0,2025-26,No


### Extract UW-Whitewater's season player box-score stats

Reads the second `<table>` on the schedule page (`tables[1]`, captured while parsing UWW's own schedule in the previous cell) -- season-long per-player averages, not per-game data.

In [13]:
stats_raw = pd.read_html(StringIO(str(tables[1])))[0]

# This table comes from FastScout's live-rendered "season player box-score" widget (see the extensive
# lazy-load/virtualization workarounds for it elsewhere in this notebook -- it's a genuinely quirky piece of
# markup to scrape). Confirmed downstream (the Streamlit app crashing with "truth value of a Series is
# ambiguous" the moment it read a "PTS" cell out of this table): pd.read_html can come back with two columns
# sharing the exact same header text -- e.g. a sortable-column control or a hidden group label that doesn't
# survive read_html's flattening, so what LOOKS like one header cell in the browser produces two identically-
# named columns here. Any df[col] or row[col] access on a duplicated name then silently returns a Series
# instead of a scalar instead of raising, so this is worth catching loudly right at the source rather than
# letting it surface downstream as a cryptic app crash.
_dupe_cols = stats_raw.columns[stats_raw.columns.duplicated()].unique().tolist()
if _dupe_cols:
    print(f"WARNING: stats_raw has duplicate column name(s) {_dupe_cols} -- keeping the FIRST occurrence of "
          f"each and dropping the rest. If the dropped column actually held different data (e.g. a genuine "
          f"second stat under the same header text) this silently loses it -- inspect stats_raw.columns and "
          f"the raw `tables[1]` HTML directly if that seems possible for this table.")
    stats_raw = stats_raw.loc[:, ~stats_raw.columns.duplicated()]

# Drop the leading unnamed/blank columns (they held player headshot/jersey-icon cells with no text)
stats = stats_raw.drop(columns=[c for c in stats_raw.columns if c.startswith("Unnamed")])
stats = stats.rename(columns={"#": "jersey_number"})

print(stats)

    jersey_number                  PLAYER  GP-GS   MIN      FGM-A    FG%  \
0            14.0            Mikey Wildes    4-0     2    0.0-0.2     0%
1            24.0           Richie Warren  29-24    22    3.5-8.1  43.2%
2             0.0            Isaac Verges  27-26    23    3.5-6.7  52.5%
3            23.0          Mauryon Turner      -     -          -      -
4            23.0         Maurquis Turner    3-0     3    0.7-1.0  66.7%
5            40.0  Tyshawn Teague-Johnson   18-1    11    1.7-3.9  42.9%
6            35.0           Rashad Rogers   19-2     9    0.8-1.7  48.5%
7             5.0         Isaiah Robinson   20-0     8    0.4-1.0  33.3%
8            12.0              Jake Quast   28-0    16    2.0-4.0  51.4%
9            30.0           Matthew McKay    3-0     2    0.7-0.7   100%
10            2.0           Kelton McEwen   28-0    11    1.1-2.6  41.7%
11           21.0            Brock Marino  28-27    21    3.2-6.1  52.3%
12           15.0           Collin Madson  29-29    33   5.8-10.5  55.6%
13           25.0          Tristian Lynch    2-0     4    0.5-1.5  33.3%
14           11.0            JR Lukenbill   26-6    13    1.1-2.3  45.9%
15            1.0         Agape Keyes Jr.    6-0     4    0.5-2.0    25%
16            3.0              Zay Howard    3-0     1    0.0-0.7     0%
17           33.0         Trent Grunewald    6-0     4    0.2-1.2  14.3%
18           30.0          Spencer Cullum      -     -          -      -
19           10.0         Darius Chestnut   18-0    10    1.3-2.5  51.1%
20           22.0         Joey Berezowitz   29-1    14    1.2-2.4  49.3%
21           32.0               Luke Bara  29-29    24    3.2-8.2  38.7%
22           20.0          Austin Ambrose    8-0     9    1.1-2.5    45%
23            NaN              Team Total     29  5825  27.3-57.3  47.6%
24            NaN                Opponent     29  5825  24.3-53.6  45.4%

       3PM-A    3P%   3P-R      FTM-A    FT%   PTS   ORB   DRB   REB   AST  \
0    0.0-0.0      -     0%    0.0-0.0      -   0.0   0.0   0.2   0.2   0.2
1    0.3-1.2    25%  15.3%    1.3-2.1    65%   8.7   1.5   3.4   4.9   1.1
2    0.4-1.2  37.5%  17.7%    2.3-3.3  71.6%   9.8   1.5   2.9   4.4   1.9
3          -      -      -          -      -     -     -     -     -     -
4    0.0-0.0      -     0%    0.0-0.7     0%   1.3   0.0   0.3   0.3   0.0
5    0.4-1.0  38.9%  25.7%    0.4-1.2  36.4%   4.2   0.9   1.1   2.0   0.3
6    0.1-0.4  28.6%  21.2%    0.5-0.7  69.2%   2.3   0.6   1.4   2.1   0.5
7    0.2-0.6  23.1%  61.9%    0.2-0.5    50%   1.1   0.2   0.3   0.5   0.6
8    0.4-1.1  31.2%  28.8%    1.8-2.8  64.9%   6.2   1.4   1.5   2.9   0.6
9    0.0-0.0      -     0%    0.0-0.3     0%   1.3   0.7   0.0   0.7   0.0
10   0.8-1.9  39.6%  73.6%    0.6-0.9  65.4%   3.5   0.1   0.2   0.3   0.5
11   0.3-0.9  34.6%  15.1%    2.1-4.0  53.2%   8.9   1.2   4.2   5.4   0.6
12   1.7-3.7  45.3%  34.9%    4.7-5.8  80.4%  18.0   1.4   3.9   5.4   1.1
13   0.0-1.0     0%  66.7%    0.0-0.0      -   1.0   0.0   0.5   0.5   0.0
14   0.3-0.8  33.3%  34.4%    0.5-0.8  54.5%   2.9   0.7   1.0   1.7   0.6
15   0.5-1.2  42.9%  58.3%    0.0-0.0      -   1.5   0.2   0.0   0.2   0.2
16   0.0-0.3     0%    50%    0.0-0.0      -   0.0   0.0   0.0   0.0   0.3
17   0.0-0.5     0%  42.9%    0.0-0.0      -   0.3   0.3   1.0   1.3   0.3
18         -      -      -          -      -     -     -     -     -     -
19   0.5-1.0    50%    40%    0.5-0.8  64.3%   3.6   0.4   0.7   1.1   0.3
20   0.7-1.6  44.4%  65.2%    0.4-0.4  91.7%   3.4   0.4   0.7   1.2   1.4
21   2.0-5.4  37.3%  66.4%    1.8-2.0  89.7%  10.2   0.2   1.3   1.6   1.3
22   0.2-1.2    20%    50%    0.2-0.8  33.3%   2.8   0.2   1.5   1.8   0.1
23  7.6-20.3  37.6%  35.4%  16.2-23.8  68.3%  78.4  11.1  22.7  33.9  10.2
24  6.4-20.2  31.6%  37.6%  15.8-22.2    71%  70.8   9.4  21.6  31.0  10.7

      TO  STL  BLK    PF
0    0.0  0.0  0.0   0.2
1    0.9  0.8  1.0   3.0
2    1.6  1.1  0.1   2.0
3      -    -    -     -
4    0.3  0.3  0.0   0.7
5    0.6  0.1  0.3   1.2
6    0.6  0.3  0.4   1.5
7    0.2  1.2  0.0   1.2
8    0.8  1.0  0.1   2.0
9    0.3  0.7  0.0   1.0
10   0.3  0.2  0.0   0.7
11   1.4  0.6  0.2   2.4
12   1.2  1.2  0.1   1.6
13   0.0  0.0  0.0   1.0
14   0.5  0.4  0.2   1.7
15   0.0  0.2  0.0   0.8
16   0.0  0.3  0.0   0.3
17   0.3  0.0  0.0   0.0
18     -    -    -     -
19   0.7  0.3  0.1   0.8
20   0.5  1.2  0.1   1.0
21   1.3  0.7  0.0   1.8
22   0.8  0.1  0.2   1.5
23  10.6  8.6  2.3  19.6
24  13.5  5.3  3.2  19.7


### Investigate `playerStatTable` tile widgets (Top Rebounders/Scorers/3PT/FT)

The season stats table above (`tables[1]`) is FastScout's plain per-player-averages `<table>` -- it does NOT cover the separate "Top Rebounders" / "Top Scorers" / "Top 3PT" / "Top FT" leaderboard TILES that also appear somewhere on this schedule page (a different UI widget, presumably div/card-based rather than a `<table>`, so `pd.read_html` over `page_tables` would never see it). This diagnostic cell re-parses the same saved schedule snapshot (`uww_mhtml_path`) with a fresh, full-page `BeautifulSoup` parse and searches for any element that looks like those tiles -- by class name and by known label text -- so their real markup can be confirmed before writing extraction logic for them. Run this cell (it only reads the already-saved local backup file, no live scrape needed) and share the printed output.

In [15]:
# --- Diagnostic: locate the "Top Rebounders/Scorers/3PT/FT" tile widgets on the schedule page -------------
# Code: parser_lib\03_investigate_playerstattable_tile_widgets.py  --  settings below, then the section runs.
TILE_LABELS = ["Top Rebounders", "Top Scorers", "Top 3PT", "Top FT", "Top Assists", "Leaders"]

run_section("03_investigate_playerstattable_tile_widgets")

Elements with a 'stat'-like class attribute (excluding <table> itself):
  found 27
  <tr class=['stat-table-row', 'stat-table-row']> -- text preview: '# PLAYER GP-GS MIN FGM-A FG% 3PM-A 3P% 3P-R FTM-A FT% PTS ORB DRB REB AST TO STL'
  <tr class=['stat-table-row', 'stat-table-row', 'no-border-row']> -- text preview: '14 Mikey Wildes 4 - 0 2 0.0 - 0.2 0% 0.0 - 0.0 - 0% 0.0 - 0.0 - 0.0 0.0 0.2 0.2 '
  <tr class=['stat-table-row', 'stat-table-row', 'no-border-row']> -- text preview: '24 Richie Warren 29 - 24 22 3.5 - 8.1 43.2% 0.3 - 1.2 25% 15.3% 1.3 - 2.1 65% 8.'
  <tr class=['stat-table-row', 'stat-table-row', 'no-border-row']> -- text preview: '0 Isaac Verges 27 - 26 23 3.5 - 6.7 52.5% 0.4 - 1.2 37.5% 17.7% 2.3 - 3.3 71.6% '
  <tr class=['stat-table-row', 'stat-table-row', 'no-border-row']> -- text preview: '23 Mauryon Turner - - - - - - - - - - - - - - - - - -'
  <tr class=['stat-table-row', 'stat-table-row', 'no-border-row']> -- text preview: '23 Maurquis Turner 3 - 0 3 0.7 - 1.0 66.7% 0.0 - 0.0 - 0% 0.0 - 0.7 0% 1.3 0.0 0'
  <tr class=['stat-table-row', 'stat-table-row', 'no-border-row']> -- text preview: '40 Tyshawn Teague-Johnson 18 - 1 11 1.7 - 3.9 42.9% 0.4 - 1.0 38.9% 25.7% 0.4 - '
  <tr class=['stat-table-row', 'stat-table-row', 'no-border-row']> -- text preview: '35 Rashad Rogers 19 - 2 9 0.8 - 1.7 48.5% 0.1 - 0.4 28.6% 21.2% 0.5 - 0.7 69.2% '
  <tr class=['stat-table-row', 'stat-table-row', 'no-border-row']> -- text preview: '5 Isaiah Robinson 20 - 0 8 0.4 - 1.0 33.3% 0.2 - 0.6 23.1% 61.9% 0.2 - 0.5 50% 1'
  <tr class=['stat-table-row', 'stat-table-row', 'no-border-row']> -- text preview: '12 Jake Quast 28 - 0 16 2.0 - 4.0 51.4% 0.4 - 1.1 31.2% 28.8% 1.8 - 2.8 64.9% 6.'
  <tr class=['stat-table-row', 'stat-table-row', 'no-border-row']> -- text preview: '30 Matthew McKay 3 - 0 2 0.7 - 0.7 100% 0.0 - 0.0 - 0% 0.0 - 0.3 0% 1.3 0.7 0.0 '
  <tr class=['stat-table-row', 'stat-table-row', 'no-border-row']> -- text preview: '2 Kelton McEwen 28 - 0 11 1.1 - 2.6 41.7% 0.8 - 1.9 39.6% 73.6% 0.6 - 0.9 65.4% '
  <tr class=['stat-table-row', 'stat-table-row', 'no-border-row']> -- text preview: '21 Brock Marino 28 - 27 21 3.2 - 6.1 52.3% 0.3 - 0.9 34.6% 15.1% 2.1 - 4.0 53.2%'
  <tr class=['stat-table-row', 'stat-table-row', 'no-border-row']> -- text preview: '15 Collin Madson 29 - 29 33 5.8 - 10.5 55.6% 1.7 - 3.7 45.3% 34.9% 4.7 - 5.8 80.'
  <tr class=['stat-table-row', 'stat-table-row', 'no-border-row']> -- text preview: '25 Tristian Lynch 2 - 0 4 0.5 - 1.5 33.3% 0.0 - 1.0 0% 66.7% 0.0 - 0.0 - 1.0 0.0'

Elements whose text contains a known tile label ['Top Rebounders', 'Top Scorers', 'Top 3PT', 'Top FT', 'Top Assists', 'Leaders']:
  (none found in this saved snapshot -- these tiles may not exist on this page, may use different wording, or may not have been present/loaded when this snapshot was captured)

Total <table> elements on this page: 3


### Investigate the `myTeam` analytics/dashboard landing page for the same tile widgets

The diagnostic above found nothing on the SCHEDULE tab -- no `playerStatTable`-style tile widget, and no "Top Rebounders/Scorers/3PT/FT" text anywhere on that page. `_ensure_fastscout_login` (Cell 4) now also saves a diagnostic snapshot of the login's actual LANDING page -- `.../teams/myTeam/analytics/dashboard?...` -- to `myTeam - Analytics Dashboard.html` every time a live FastScout session bootstraps, since that's a different page from SCHEDULE that nothing has captured or searched yet. This cell re-runs the same tile-detection search against that file, once it exists locally (requires a live session with credentials to have run at least once).

In [17]:
# 04_investigate_myteam_analytics_dashboard
# Code: parser_lib\04_investigate_myteam_analytics_dashboard.py  --  settings below, then the section runs.

run_section("04_investigate_myteam_analytics_dashboard")

Elements with a 'stat'-like class attribute (excluding <table> itself):
  found 4
  <div class=['Tile', 'teamStatsLineup', 'top-left-tile']> -- text preview: 'LINEUP STATS Loading...'
  <div class=['teamStatsLineup']> -- text preview: 'Loading...'
  <div class=['Tile', 'teamAdvancedStatsTable', 'top-left-tile']> -- text preview: 'ADVANCED STATS Loading...'
  <div class=['teamAdvancedStatsTable']> -- text preview: 'Loading...'

Elements whose text contains a known tile label ['Top Rebounders', 'Top Scorers', 'Top 3PT', 'Top FT', 'Top Assists', 'Leaders']:
  [Leaders] <a class=['helvetica-neue-bold', 'uppercase']> -- text preview: 'Leaders'

Total <table> elements on this page: 0

In [18]:
# 05_investigate_myteam_analytics_dashboard_2
# Code: parser_lib\05_investigate_myteam_analytics_dashboard_2.py  --  settings below, then the section runs.

run_section("05_investigate_myteam_analytics_dashboard_2")

Elements with a 'stat'-like class attribute (excluding <table> itself):
  found 4
  <div class=['Tile', 'teamStatsLineup', 'top-left-tile']> -- text preview: 'LINEUP STATS Loading...'
  <div class=['teamStatsLineup']> -- text preview: 'Loading...'
  <div class=['Tile', 'teamAdvancedStatsTable', 'top-left-tile']> -- text preview: 'ADVANCED STATS Loading...'
  <div class=['teamAdvancedStatsTable']> -- text preview: 'Loading...'

Elements whose text contains a known tile label ['Top Rebounders', 'Top Scorers', 'Top 3PT', 'Top FT', 'Top Assists', 'Leaders']:
  [Leaders] <a class=['helvetica-neue-bold', 'uppercase']> -- text preview: 'Leaders'

Total <table> elements on this page: 0

In [19]:
# 06_investigate_myteam_analytics_dashboard_3
# Code: parser_lib\06_investigate_myteam_analytics_dashboard_3.py  --  settings below, then the section runs.

run_section("06_investigate_myteam_analytics_dashboard_3")

Elements with a 'stat'-like class attribute (excluding <table> itself):
  found 4
  <div class=['Tile', 'teamStatsLineup', 'top-left-tile']> -- text preview: 'LINEUP STATS Loading...'
  <div class=['teamStatsLineup']> -- text preview: 'Loading...'
  <div class=['Tile', 'teamAdvancedStatsTable', 'top-left-tile']> -- text preview: 'ADVANCED STATS Loading...'
  <div class=['teamAdvancedStatsTable']> -- text preview: 'Loading...'

Elements whose text contains a known tile label ['Top Rebounders', 'Top Scorers', 'Top 3PT', 'Top FT', 'Top Assists', 'Leaders']:
  [Leaders] <a class=['helvetica-neue-bold', 'uppercase']> -- text preview: 'Leaders'

Total <table> elements on this page: 0

In [20]:
# 07_investigate_myteam_analytics_dashboard_4
# Code: parser_lib\07_investigate_myteam_analytics_dashboard_4.py  --  settings below, then the section runs.

run_section("07_investigate_myteam_analytics_dashboard_4")

Elements with a 'stat'-like class attribute (excluding <table> itself):
  found 4
  <div class=['Tile', 'teamStatsLineup', 'top-left-tile']> -- text preview: 'LINEUP STATS Loading...'
  <div class=['teamStatsLineup']> -- text preview: 'Loading...'
  <div class=['Tile', 'teamAdvancedStatsTable', 'top-left-tile']> -- text preview: 'ADVANCED STATS Loading...'
  <div class=['teamAdvancedStatsTable']> -- text preview: 'Loading...'

Elements whose text contains a known tile label ['Top Rebounders', 'Top Scorers', 'Top 3PT', 'Top FT', 'Top Assists', 'Leaders']:
  [Leaders] <a class=['helvetica-neue-bold', 'uppercase']> -- text preview: 'Leaders'

Total <table> elements on this page: 0


### Summarize UW-Whitewater's season record and home/away/neutral splits

`schedule` spans every team found in `schedules_dir` (UWW's own games plus each opponent's) -- filtered down to just UWW's own rows before aggregating the win/loss record and average point-margin splits by location.

In [22]:
# "schedule" now spans every team found in schedules_dir (UWW's own games plus any opponent's, e.g.
# Elmhurst) -- this record/splits summary is specifically about UW-Whitewater, so filter down to just its
# rows before aggregating; otherwise the win/loss counts and splits below would blend in other teams' games too.
uww_schedule = schedule[schedule["team"] == "UW-Whitewater Warhawks"]

record_counts = uww_schedule["outcome"].value_counts()
print("Overall record (W-L):", f"{record_counts.get('W', 0)}-{record_counts.get('L', 0)}")

split_summary = (
    uww_schedule.groupby(["location", "outcome"])
    .size()
    .unstack(fill_value=0)
    .assign(games=lambda d: d.sum(axis=1))
)
print(split_summary.reset_index())

avg_margin_by_location = uww_schedule.groupby("location")["point_margin"].mean().round(1)
print(avg_margin_by_location.reset_index().rename(columns={"point_margin": "avg_point_margin"}))

Overall record (W-L): 9-3
outcome       location  L  W  games
0                 Away  1  4      5
1                 Home  1  4      5
2        Neutral Court  1  1      2
        location  avg_point_margin
0           Away              13.4
1           Home               7.8
2  Neutral Court              17.5


### Parse each opponent's FastScout "ScoutBuilder" game-plan report

Scouting reports are sourced exclusively from PDF exports (MHTML snapshots leave live-data stat widgets empty). Since `ai_parse_document()` only runs on serverless AI Functions compute, this falls back to `pdfplumber` and reconstructs the same `section_header`/`text`/`table` element schema used by every downstream cell, looping over every `"*_scout.pdf"` file found in `INPUT_DIR`.

In [24]:
# FastScout "ScoutBuilder" game-plan reports, now sourced EXCLUSIVELY from PDF exports -- MHTML is retired.
# Code: parser_lib\08_parse_each_opponent_fastscout_scoutbuilder.py  --  settings below, then the section runs.
PLAYER_LINE_RE = re.compile(r"^#\d+\s*•")
PAGE_NUM_RE = re.compile(r"^\d+\s+of\s+\d+$")

run_section("08_parse_each_opponent_fastscout_scoutbuilder")

  [before_scout=yes] Ignoring 12 scouting report(s) dated on/after 2026-1-7: ['1_10_26 UW-Whitewater @ UW-River Falls Falcons_scout.html', '1_14_26 UW-Whitewater @ UW-La Crosse Eagles_scout.html', '1_17_26 UW-Stout Blue Devils @ UW-Whitewater_scout.html', '1_21_26 UW-Whitewater @ UW-Platteville Pioneers_scout.html', '1_24_26 UW-Eau Claire Blugolds @ UW-Whitewater_scout.html', '1_7_26 UW-Stevens Point Pointers @ UW-Whitewater_scout.html', '2_11_26 UW-Platteville Pioneers @ UW-Whitewater_scout.html', '2_14_26 UW-Whitewater @ UW-Eau Claire Blugolds_scout.html', '2_4_26 UW-La Crosse Eagles @ UW-Whitewater_scout.html', '2_7_26 UW-Whitewater @ UW-Stout Blue Devils_scout.html', '3_6_26 UW-Whitewater @ Loras Duhawks_scout.html', '3_7_26 UW-Whitewater @ Washington-St. Louis Bears_scout.html']
Found 0 PDF scout report(s) and 12 HTML scout report(s):
 - 11_14_25 UW-Whitewater @ St. Thomas (TX) Celts_scout.html
 - 11_15_25 UW-Whitewater @ Eureka Red Devils_scout.html
 - 11_19_25 Aurora Spartans @ UW-Whitewater_scout.html
 - 11_25_25 Simpson Storm @ UW-Whitewater_scout.html
 - 11_7_25 UW-Whitewater @ Ripon Red Hawks_scout.html
 - 12_10_25 UW-Whitewater @ Lawrence Vikings_scout.html
 - 12_13_25 Carroll (WI) Pioneers @ UW-Whitewater_scout.html
 - 12_19_25 UW-Whitewater @ Hope Flying Dutchmen_scout.html
 - 12_20_25 UW-Whitewater @ Alma Scots_scout.html
 - 12_2_25 Elmhurst Bluejays @ UW-Whitewater_scout.html
 - 12_30_25 UW-Whitewater @ Coe Kohawks_scout.html
 - 1_3_26 UW-Oshkosh Titans @ UW-Whitewater_scout.html
  Parsed 'St. Thomas (TX) Celts' (.html): 151 elements, 1 tables
  Parsed 'Eureka Red Devils' (.html): 116 elements, 1 tables
  Parsed 'Aurora Spartans' (.html): 146 elements, 1 tables
  Parsed 'Simpson Storm' (.html): 138 elements, 1 tables
  Parsed 'Ripon Red Hawks' (.html): 129 elements, 1 tables
  Parsed 'Lawrence Vikings' (.html): 136 elements, 1 tables
  Parsed 'Carroll (WI) Pioneers' (.html): 139 elements, 1 tables
  Parsed 'Hope Flying Dutchmen' (.html): 0 elements, 0 tables
  Parsed 'Alma Scots' (.html): 140 elements, 1 tables
  Parsed 'Elmhurst Bluejays' (.html): 138 elements, 1 tables
  Parsed 'Coe Kohawks' (.html): 143 elements, 1 tables
  Parsed 'UW-Oshkosh Titans' (.html): 149 elements, 1 tables


### Extract each opponent's roster, player notes, and keys to defending

Parses the `"#<jersey> • <name> • <pos> • <height> • <weight> • <class>"` identity lines out of each scouting report's parsed elements, along with the "Player Notes" and "Keys to Defending" text that follows each player. Starter/bench role is read from the report's own "BENCH" section header when present, falling back to roster order (1st-5th = Starter) for reports that omit it.

In [26]:
# Player identity lines in the PDF's parsed text look like "#<jersey> \u2022 <name> \u2022 <pos> \u2022 <height> \u2022 <weight> \u2022
# Code: parser_lib\09_extract_each_opponent_roster.py  --  settings below, then the section runs.
PLAYER_LINE_RE = re.compile(r"^#(\d+)\s*\u2022\s*(.+?)\s*\u2022\s*([A-Z/]+)\s*\u2022\s*(\d+'\d+\")\s*\u2022\s*(.*?)\s*\u2022\s*([A-Z]+)$")
STARTERS_BY_ORDER_CUTOFF = 5

run_section("09_extract_each_opponent_roster")

                 opponent   game_date jersey_number               name  \
0   St. Thomas (TX) Celts  2025-11-14           #10      Angel Johnson
1   St. Thomas (TX) Celts  2025-11-14            #1     Corey Thompson
2   St. Thomas (TX) Celts  2025-11-14            #0     Nathan Kongolo
3   St. Thomas (TX) Celts  2025-11-14           #12   Nicholas Buffalo
4   St. Thomas (TX) Celts  2025-11-14           #25    Charles Gitonga
..                    ...         ...           ...                ...
88      UW-Oshkosh Titans  2026-01-03           #13  Logan Rindfleisch
89      UW-Oshkosh Titans  2026-01-03            #1    Aiden Hawkinson
90      UW-Oshkosh Titans  2026-01-03           #23       Oskar Kangas
91      UW-Oshkosh Titans  2026-01-03           #12  Jonah Rindfleisch
92      UW-Oshkosh Titans  2026-01-03            #5          Matt Imig

   position height   weight class_year     role  \
0         G   6'2"     None         SR  Starter
1         G   6'2"     None         JR  Starter
2       G/F   6'4"     None         SO  Starter
3         F   6'6"     None         JR  Starter
4         F   6'8"     None         JR  Starter
..      ...    ...      ...        ...      ...
88        G   6'5"  190 lbs         SO    Bench
89        G   6'3"  180 lbs         FR    Bench
90        F   6'5"  205 lbs         FR    Bench
91        F   6'8"  215 lbs         SR    Bench
92        G   6'1"  180 lbs         SR    Bench

                                  player_notes  \
0           PG, looking to create most touches
1     LH Shooter/Driver (Main shooting threat)
2                            RH Driver/slasher
3   Scores from dump offs on drives & O-Boards
4                               Driver/slasher
..                                         ...
88                              Driver/shooter
89                                     Shooter
90                                     Shooter
91                              Rebounds hard!
92                 Shooter (C&S & off dribble)

                   keys_to_defending  has_scouting_report
0    Anticipate drive after closeout                 True
1   Anticipate LHD & finish attempts                 True
2                     Anticipate RHD                 True
3                         Box out!!!                 True
4   Anticipate RHD & finish attempts                 True
..                               ...                  ...
88                     No rhythm 3's                 True
89                      No C & S 3's                 True
90      Early high hand on closeouts                 True
91                        BOX OUT!!!                 True
92                      No C & S 3's                 True

[93 rows x 12 columns]


### Extract UW-Whitewater's offensive and defensive game plan for each opponent

Pulls the "TEAM STRENGTHS" / "KEYS TO VICTORY" / defensive-scheme / offensive-scheme sections out of each scouting report's parsed elements, grouped under a consistent `section_group` label so they can be compared across opponents.

In [28]:
# PDF elements already separate section_header from text cleanly (no banner/page-chrome noise mixed in, unlike
# Code: parser_lib\10_extract_uw_whitewater_offensive_and.py  --  settings below, then the section runs.

run_section("10_extract_uw_whitewater_offensive_and")

                  opponent                                    category  \
0    St. Thomas (TX) Celts                          Game Plan Overview
1    St. Thomas (TX) Celts                          Game Plan Overview
2    St. Thomas (TX) Celts  Offensive Game Plan (vs. Opponent Defense)
3    St. Thomas (TX) Celts  Offensive Game Plan (vs. Opponent Defense)
4    St. Thomas (TX) Celts  Offensive Game Plan (vs. Opponent Defense)
..                     ...                                         ...
148      UW-Oshkosh Titans  Defensive Game Plan (vs. Opponent Offense)
149      UW-Oshkosh Titans  Defensive Game Plan (vs. Opponent Offense)
150      UW-Oshkosh Titans  Defensive Game Plan (vs. Opponent Offense)
151      UW-Oshkosh Titans  Defensive Game Plan (vs. Opponent Offense)
152      UW-Oshkosh Titans  Defensive Game Plan (vs. Opponent Offense)

                               topic  \
0                     TEAM STRENGTHS
1                    KEYS TO VICTORY
2           Overall Defensive Scheme
3        Attacking their man defense
4          Ball Screen & DHO Defense
..                               ...
148           Defending Their Action
149  Ball Screen Actions & Personnel
150          Ball Screen Coverage(s)
151  Potential Adjustments (Offense)
152                      ELOB & SLOB

                                                                                                                                                     notes
0                                                   Extremely active hands defensively | Multiple guys that can create & get to rim | Crash the glass hard
1                                                            1. BALL SECURITY | 2. LIMIT THEIR SCORING @ THE RIM/IN THE PAINT | 3. BULLY THEM ON THE GLASS
2    M2M | VERY active with hands (15 steals per game) | Heavy ball pressure/great at tracing ball | Jump passing lanes | No middle/funnel to sidelines...
3    Attack Transition Opportunities | Great screening & Physical cuts! | Cobra's, Rhino's, & Swirls available | Drive to post | Aggressive Drive & Pat...
4                                                               Ice or Switch Ball screens | Really aggressive in Ice (more of a trap) | Switch most DHO's
..                                                                                                                                                     ...
148  TRANSITION DEFENSE!!! | Stop the ball early | Sprint & locate shooters | Early gaps & help side | Defend the high side ball screen | Guards- Climb...
149    Ball screens most possessions (High side ball screen) | Big sets touch & go ball screen | Looking to hit the Big on the short roll (around FT line)
150                                                                                                                      14X - Low Peel Switch when needed
151                                                                                                                                              15X | 13X
152

[153 rows x 4 columns]


### Team efficiency narrative (deprecated -- PDF exports don't carry it)

The FASTINTELLIGENCE panel (ORtg/DRtg/Pace + percentile narrative) is a ScoutBuilder UI-only widget that never appears in the printable/PDF report. Kept as an empty placeholder with the same schema as before so nothing downstream breaks, now that scouting reports are sourced exclusively from PDFs.

In [30]:
# The "FASTINTELLIGENCE" panel (ORtg/DRtg/Pace + national-percentile narrative) is ScoutBuilder's UI-only
# "Scout Assistant" widget -- it is NOT part of the printable report, so it never appears in the PDF export
# (confirmed: 0 of the Ripon PDF's 133 parsed elements mention ORtg/DRtg/FASTINTELLIGENCE). This metric is no
# longer available now that scouting reports are sourced exclusively from PDFs. Kept as an empty placeholder
# (same schema as before) so nothing downstream breaks.

# all_team_stats = pd.DataFrame(columns=["opponent", "ORtg", "DRtg", "Pace", "offense_narrative", "defense_narrative"])

print(
    "Team efficiency narrative (ORtg/DRtg/Pace/FASTINTELLIGENCE) is not captured in the PDF export -- it's a\n"
    "UI-only panel that isn't part of the printable ScoutBuilder report, and is no longer available now that\n"
    "scouting reports are sourced exclusively from PDFs."
)

Team efficiency narrative (ORtg/DRtg/Pace/FASTINTELLIGENCE) is not captured in the PDF export -- it's a
UI-only panel that isn't part of the printable ScoutBuilder report, and is no longer available now that
scouting reports are sourced exclusively from PDFs.


### Cross-reference each scouted opponent's report against the actual result

Since the FASTINTELLIGENCE narrative is gone (see previous cell), this instead reads each opponent's season-average points scored/allowed straight from their PDF's own boxscore table ("Team Total" and "Opponent" rows) to sanity-check the scouting report against what actually happened.

In [32]:
# The FASTINTELLIGENCE narrative used previously is gone (see prior cell), so this now cross-references each
# Code: parser_lib\11_cross_reference_each_scouted_opponent.py  --  settings below, then the section runs.

run_section("11_cross_reference_each_scouted_opponent")

                 opponent         date       location outcome  \
0   St. Thomas (TX) Celts  Fri, Nov 14  Neutral Court       L
1       Eureka Red Devils  Sat, Nov 15  Neutral Court       W
2         Aurora Spartans  Wed, Nov 19           Home       W
3           Simpson Storm  Tue, Nov 25           Home       W
4         Ripon Red Hawks   Fri, Nov 7           Away       W
5        Lawrence Vikings  Wed, Dec 10           Away       W
6   Carroll (WI) Pioneers  Sat, Dec 13           Home       W
7              Alma Scots  Sat, Dec 20           Away       W
8       Elmhurst Bluejays   Tue, Dec 2           Home       W
9             Coe Kohawks  Tue, Dec 30           Away       L
10      UW-Oshkosh Titans   Sat, Jan 3           Home       L

   opp_season_avg_ppg  opp_actual_ppg opp_ppg_vs_average  uww_points  \
0                None            81.0               None        73.0
1                None            73.0               None       116.0
2                None            73.0               None        82.0
3                None            78.0               None       100.0
4                None            58.0               None        76.0
5                None            58.0               None        88.0
6                None            60.0               None        64.0
7                None            61.0               None        90.0
8                None            72.0               None        88.0
9                None            86.0               None        73.0
10               None            90.0               None        78.0

   opp_season_avg_ppg_allowed uww_ppg_vs_opp_avg_allowed  point_margin
0                        None                       None          -8.0
1                        None                       None          43.0
2                        None                       None           9.0
3                        None                       None          22.0
4                        None                       None          18.0
5                        None                       None          30.0
6                        None                       None           4.0
7                        None                       None          29.0
8                        None                       None          16.0
9                        None                       None         -13.0
10                       None                       None         -12.0

(opp_season_avg_ppg / opp_ppg_vs_average / opp_season_avg_ppg_allowed / uww_ppg_vs_opp_avg_allowed are always blank now -- team/player statistics from the scouting report are no longer used; see the blanking earlier in this cell.)

St. Thomas (TX) Celts (Fri, Nov 14, Neutral Court): UWW 73.0 - St. Thomas (TX) Celts 81.0 (L, margin -8)
  Pre-game keys to victory: 1. BALL SECURITY | 2. LIMIT THEIR SCORING @ THE RIM/IN THE PAINT | 3. BULLY THEM ON THE GLASS
  No season-average PPG available for comparison (scouting-report statistics are not used).
  No season-average points-allowed figure available for comparison (scouting-report statistics are not used).

Eureka Red Devils (Sat, Nov 15, Neutral Court): UWW 116.0 - Eureka Red Devils 73.0 (W, margin +43)
  Pre-game keys to victory: 1. EARLY GAP / HELP SIDE | 2. KEEP THE BALL IN FRONT (ACTIVE HANDS) | 3. OWN THE PAINT
  No season-average PPG available for comparison (scouting-report statistics are not used).
  No season-average points-allowed figure available for comparison (scouting-report statistics are not used).

Aurora Spartans (Wed, Nov 19, Home): UWW 82.0 - Aurora Spartans 73.0 (W, margin +9)
  Pre-game keys to victory: 1. GUARD YOUR YARD (+ Early Gap Help) | 2. WALL UP, DON'T FOUL | 3. ATTACK THE PAINT!!!
  No season-average PPG available for comparison (scouting-report statistics are not used).
  No season-average points-allowed figure available for comparison (scouting-report statistics are not used).

Simpson Storm (Tue, Nov 25, Home): UWW 100.0 - Simpson Storm 78.0 (W, margin +22)
  Pre-game keys to victory: 1. TAKE AWAY PERSONNEL TENDANCIES | 2. LIVE IN THE PAINT!!! | 3. DOMINATE THE GLASS
  No season-average PPG available for comparison (scouting-report statistics are not used).
  No season-average points-allowed figure available for comparison (scouting-report statistics are not used).

Ripon Red Hawks (Fri, Nov 7, Away): UWW 76.0 - Ripon Red Hawks 58.0 (W, margin +18)
  Pre-game keys to victory: 1. DOMINATE THE GLASS | 2. ATTACK THE BASKET | 3. COMMUNICATION SCREENING ACTION!!!
  No season-average PPG available for comparison (scouting-report statistics are not used).
  No season-average points-allowed figure available for comparison (scouting-report statistics are not used).

Lawrence Vikings (Wed, Dec 10, Away): UWW 88.0 - Lawrence Vikings 58.0 (W, margin +30)
  Pre-game keys to victory: 1. DRIVE DOWN 3PT ATTEMPTS!!! | 2. FINISH DEFENSIVE POSSESSIONS (LATE CLOCK) | 3. ATTACK THE PAINT
  No season-average PPG available for comparison (scouting-report statistics are not used).
  No season-average points-allowed figure available for comparison (scouting-report statistics are not used).

Carroll (WI) Pioneers (Sat, Dec 13, Home): UWW 64.0 - Carroll (WI) Pioneers 60.0 (W, margin +4)
  Pre-game keys to victory: 1. TRANSITION DEFENSE!!! | 2. SQUEEZE & LIMIT #4 (Guard 1 on 1 + Gap Help) | 3. ATTACK THE PAINT OFFENSIVELY!!
  No season-average PPG available for comparison (scouting-report statistics are not used).
  No season-average points-allowed figure available for comparison (scouting-report statistics are not used).

Alma Scots (Sat, Dec 20, Away): UWW 90.0 - Alma Scots 61.0 (W, margin +29)
  Pre-game keys to victory: 1. CONTAIN #11 | 2. GREAT WALL UPS & LIMIT FOULS | 3. ATTACK MISMATCHES (after switches)
  No season-average PPG available for comparison (scouting-report statistics are not used).
  No season-average points-allowed figure available for comparison (scouting-report statistics are not used).

Elmhurst Bluejays (Tue, Dec 2, Home): UWW 88.0 - Elmhurst Bluejays 72.0 (W, margin +16)
  Pre-game keys to victory: 1. COMMUNICATE SCREENS & ACTIONS | 2. DOMINATE THE PAINT | 3. GUARD 1 ON 1
  No season-average PPG available for comparison (scouting-report statistics are not used).
  No season-average points-allowed figure available for comparison (scouting-report statistics are not used).

Coe Kohawks (Tue, Dec 30, Away): UWW 73.0 - Coe Kohawks 86.0 (L, margin -13)
  Pre-game keys to victory: 1. ATTACK THE PAINT | 2. BALL SCREEN DEFENSE (DISRUPTIVE & CONNECTED) | 3. DOMINATE REBS & FTs
  No season-average PPG available for comparison (scouting-report statistics are not used).
  No season-average points-allowed figure available for comparison (scouting-report statistics are not used).

UW-Oshkosh Titans (Sat, Jan 3, Home): UWW 78.0 - UW-Oshkosh Titans 90.0 (L, margin -12)
  Pre-game keys to victory: 1. WIN THE POSSESSION BATTLE (TO's & Rebounds) | 2. ATTACK & EXECUTE OFFENSIVELY | 3. MULTIPLE EFFORTS DEFENSIVELY (never stop!!)
  No season-average PPG available for comparison (scouting-report statistics are not used).
  No season-average points-allowed figure available for comparison (scouting-report statistics are not used).


### Win/loss splits by Keys-to-Victory category, with side attribution

Tags each matched "Keys to Victory" phrase with a side -- UWW (what Whitewater does proactively: attack, score, rebound, share) or OPP (what Whitewater does to contain the opponent: guard, force turnovers, limit, pressure) -- then breaks down win/loss outcomes by category and side.

In [34]:
# Win/loss splits by "Keys to Victory" category WITH SIDE ATTRIBUTION (UWW vs OPP).
# Code: parser_lib\12_win_loss_splits_by_keys_to_victory.py  --  settings below, then the section runs.

run_section("12_win_loss_splits_by_keys_to_victory")

Per-game 'Keys to Victory' categories detected WITH SIDE ATTRIBUTION:
  UWW = what Whitewater does proactively (attack, score, rebound, share)
  OPP = what Whitewater does to contain the opponent (guard, force TOs, limit, pressure)
                 opponent outcome                           category side
0   St. Thomas (TX) Celts       L          Ball Security / Turnovers  UWW
1   St. Thomas (TX) Celts       L              Field Goal Efficiency  OPP
2   St. Thomas (TX) Celts       L                         Rebounding  UWW
3       Eureka Red Devils       W  Perimeter Defense / Ball Pressure  OPP
4       Eureka Red Devils       W                         Rebounding  UWW
5         Aurora Spartans       W                 Fouls / Discipline  OPP
6         Aurora Spartans       W  Perimeter Defense / Ball Pressure  OPP
7         Aurora Spartans       W                     Scoring Inside  UWW
8           Simpson Storm       W                         Rebounding  UWW
9           Simpson Storm       W                     Scoring Inside  UWW
10        Ripon Red Hawks       W                         Rebounding  UWW
11        Ripon Red Hawks       W                     Scoring Inside  UWW
12       Lawrence Vikings       W                     Scoring Inside  UWW
13       Lawrence Vikings       W               Three-Point Shooting  OPP
14  Carroll (WI) Pioneers       W  Perimeter Defense / Ball Pressure  OPP
15  Carroll (WI) Pioneers       W                     Scoring Inside  UWW
16             Alma Scots       W                 Fouls / Discipline  OPP
17      Elmhurst Bluejays       W  Perimeter Defense / Ball Pressure  OPP
18      Elmhurst Bluejays       W                     Scoring Inside  UWW
19            Coe Kohawks       L                     Scoring Inside  UWW
20      UW-Oshkosh Titans       L                         Rebounding  UWW

Win/loss splits by category + side (UWW vs OPP emphasis):
                    display_label side                           category  \
0           UWW: Protect the Ball  UWW          Ball Security / Turnovers
1  OPP: Limit Their FG Efficiency  OPP              Field Goal Efficiency
2            OPP: They Draw Fouls  OPP                 Fouls / Discipline
3            OPP: On-Ball Defense  OPP  Perimeter Defense / Ball Pressure
4           UWW: Crash the Boards  UWW                         Rebounding
5           UWW: Attack the Paint  UWW                     Scoring Inside
6     OPP: Contest Their Shooting  OPP               Three-Point Shooting

   games  wins  losses  win_pct
0      1     0       1    0.000
1      1     0       1    0.000
2      2     2       0    1.000
3      4     4       0    1.000
4      5     3       2    0.600
5      7     6       1    0.857
6      1     1       0    1.000


### Keys-to-Victory category reference

Documents WHY each category exists: which Keys-to-Victory phrases trigger it, which stat column(s) it's graded on, and cases where a phrase is deliberately left unmapped because no stat in a season box score can measure it. Update this table any time a new KTV phrase pattern shows up.

In [36]:
# --- Keys-to-Victory category reference -----------------------------------------------------------------------
# Code: parser_lib\13_keys_to_victory_category_reference.py  --  settings below, then the section runs.

run_section("13_keys_to_victory_category_reference")

                             category         stat_cols                                                        example_phrases                                                             why_chosen
0           Ball Security / Turnovers                TO  ball security, turnover, protect/take care of the ball, limit turn...  Directly named -- "ball security"/"turnovers" have a 1:1 stat colu...
1                          Rebounding     REB, ORB, DRB  own the paint, bully/dominate the glass, rebound, board, second ch...  "Glass"/"board"/"crash"/"own the paint" possession language in thi...
2                Three-Point Shooting        3PM-A, 3P%  three, 3 pt, 3pt, perimeter shooting, spacing, shooting ability, s...  Direct stat match for perimeter shot volume/efficiency. Expanded w...
3                         Free Throws        FTM-A, FT%                                     free throw, ft line, getting to ft  Direct stat match. Added "ft line" / "getting to ft" from Aurora (...
4                  Fouls / Discipline                PF                                           foul, wall up, drawing fouls  Direct stat match for foul-discipline emphasis. Added "wall up" (A...
5             Ball Movement / Assists               AST   assist, ball movement, share the ball, playmaking, playmaker, create  Direct stat match for offensive ball-sharing emphasis. Added "play...
6           Paint Protection / Blocks               BLK                               block, protect the rim, paint protection                 Direct stat match for interior shot-blocking emphasis.
7   Perimeter Defense / Ball Pressure               STL  steal, press capable, full court press, force turnovers, force to'...  Renamed from "Ball Pressure / Steals" once Aurora/Eureka/Elmhurst ...
8                      Scoring Inside  FG2M, FG2A, FG2%  dominate the paint, attack the paint, live in the paint, attack th...  Interior-scoring emphasis -- uses derived 2PT FG stats (FGM-FG3M, ...
9               Field Goal Efficiency        FGM-A, FG%                                                    limit their scoring  Overall shooting efficiency emphasis -- used when the scouting not...
10           (intentionally unmapped)                 -  communication screening action / communicate screens & actions (Ri...  No corresponding stat exists in a season box score for screen-navi...


### Build per-player scouting profiles: position, height, and playing-style tags

Builds a comparable `player_profiles` entry for every scouted player -- normalized position group, height in inches, and a set of playing-style tags mined from their free-text scouting notes (player notes + keys to defending). Box-score-only players with no scouting writeup are added with a default Bench role so they aren't silently dropped from later lineup analysis.

In [38]:
# Build a comparable "player profile" for every scouted player: normalized position group, height in inches,
# Code: parser_lib\14_build_per_player_scouting_profiles.py  --  settings below, then the section runs.

run_section("14_build_per_player_scouting_profiles")

No season boxscore table found for 'Hope Flying Dutchmen'.
Adding 38 box-score-only player(s) with no scouting writeup (defaulted to role=Bench):

                 opponent jersey_number              name
8   St. Thomas (TX) Celts           #23        Jaden Ross
10  St. Thomas (TX) Celts           #11   Tamarcus Butler
11  St. Thomas (TX) Celts           #13     Legborsi Mato
18      Eureka Red Devils           #35    Max Richardson
20      Eureka Red Devils           #20        Nolan Kerr
21      Eureka Red Devils           #22        Tony Mabon
22      Eureka Red Devils           #15   Amare Brokemond
23      Eureka Red Devils            #3     Blake Logsdon
24      Eureka Red Devils            #0     Colin DeLaere
25      Eureka Red Devils            #1     Dylan Logsdon
33        Aurora Spartans            #0      Cullen Rauls
36        Aurora Spartans           #30         Alex Ross
37        Aurora Spartans           #21   Isaiah Thompson
46          Simpson Storm           #35  Nathaniel Winter
47          Simpson Storm           #15       Seth Gipple

  ... 23 more row(s) of 38 (SHOW_ROWS = 15)
Scouting-report player statistics are disabled by design (PDF reports are last-season data) -- player_profiles stat columns start blank and are only filled in by the PBP-derived override further down this notebook, from real current-season games.
                  opponent jersey_number                 name     role  \
0    St. Thomas (TX) Celts           #10        Angel Johnson  Starter
1    St. Thomas (TX) Celts            #1       Corey Thompson  Starter
2    St. Thomas (TX) Celts            #0       Nathan Kongolo  Starter
3    St. Thomas (TX) Celts           #12     Nicholas Buffalo  Starter
4    St. Thomas (TX) Celts           #25      Charles Gitonga  Starter
..                     ...           ...                  ...      ...
126      UW-Oshkosh Titans           #34          AJ Ohrmundt    Bench
127      UW-Oshkosh Titans           #30         Adam Guyette    Bench
128      UW-Oshkosh Titans           #22          Reed Seckar    Bench
129      UW-Oshkosh Titans           #24            Max Tutas    Bench
130      UW-Oshkosh Titans           #44  Tristan Johanknecht    Bench

                      notes_tags_display  \
0                              playmaker
1    slasher_driver, three_point_shooter
2                         slasher_driver
3              rebounder, slasher_driver
4                         slasher_driver
..                                   ...
126
127
128
129
130

                         keys_tags_display   PTS   REB   AST   FG%   3P%
0    anticipate_move, deny_catch_and_shoot  None  None  None  None  None
1                          anticipate_move  None  None  None  None  None
2                          anticipate_move  None  None  None  None  None
3                         box_out_priority  None  None  None  None  None
4                          anticipate_move  None  None  None  None  None
..                                     ...   ...   ...   ...   ...   ...
126                                         None  None  None  None  None
127                                         None  None  None  None  None
128                                         None  None  None  None  None
129                                         None  None  None  None  None
130                                         None  None  None  None  None

[131 rows x 11 columns]


### Break out Keys-to-Victory categories by opponent starter vs. bench role

For each per-game Keys-to-Victory category (from the win/loss-splits cell above), breaks out the scouted opponent's own production in that category by role -- Starter vs. Bench -- to show whether an emphasis like "own the glass" was really driven by starters or bench depth.

In [40]:
# For each per-game "Keys to Victory" category (from the win/loss-splits cell above), break out the SCOUTED
# Code: parser_lib\15_break_out_keys_to_victory_categories_by.py  --  settings below, then the section runs.
CATEGORY_TO_STAT_COLS = {}
COUNT_STATS = {"TO", "REB", "AST", "STL", "BLK", "PTS"}

run_section("15_break_out_keys_to_victory_categories_by")

Opponent production by role (Starter vs Bench) for the stat(s) behind each matched Keys-to-Victory category:
Empty DataFrame
Columns: [opponent, outcome, category, role, stat, players_with_data, avg_per_player, role_total]
Index: []
No count-type stats available yet to compare Starter vs Bench totals for the matched categories.


### Play-by-play parsing functions

Each game's play-by-play is a separate MHTML snapshot of FastScout's playByPlay page (same "Save as Webpage, Single File" format as the season schedule), uploaded as `"<date> UW-Whitewater @ <Opponent>_pbp.mhtml"` (or `"<date> <Opponent> @ UW-Whitewater_pbp.mhtml"` for home games). `parse_pbp_html`/`parse_pbp_mhtml` parse that table; `scrape_pbp_live` is the live-scrape fallback, reused by every PBP-fetching cell further down.

In [42]:
# --- Play-by-play (PBP) parsing functions -------------------------------------------------------------------
# Code: parser_lib\16_play_by_play_parsing_functions.py  --  settings below, then the section runs.

run_section("16_play_by_play_parsing_functions")

### Classify each raw play-by-play text string into an event type

The 4-column layout is "Time | UW-Whitewater | Score | \<Opponent\>" -- almost every row has exactly one of the two team-text columns filled in (one atomic event per row), alongside the running score. A handful of event strings are team-level with no player name at all (a shot-clock/backcourt turnover, or a held-ball jump ball) -- those get matched by exact text instead of a regex.

In [44]:
# The 4-column layout is "Time | UW-Whitewater | Score | <Opponent>" -- almost every row has exactly ONE of the
# Code: parser_lib\17_classify_each_raw_play_by_play_text_string.py  --  settings below, then the section runs.

run_section("17_classify_each_raw_play_by_play_text_string")

### Turn the raw 4-column play-by-play table into one row per event

`build_pbp_events` carries the running score forward onto every row and labels each row with which team it belongs to. `self_column` must be resolved per-file (see `resolve_self_column` later on) since FastScout puts the exporting team's own events in a fixed column regardless of home/away, but which raw column that is varies by whose account captured the snapshot.

In [46]:
# Code: parser_lib\18_turn_raw_4_column_play_by_play_table_into.py  --  settings below, then the section runs.

run_section("18_turn_raw_4_column_play_by_play_table_into")

### Extract the opponent name from a `_pbp.mhtml` filename

In [48]:
# --- A GAME IS (opponent, game_date), NEVER opponent ALONE ---------------------------------------
# Code: parser_lib\19_extract_opponent_name_from_pbp_mhtml.py  --  settings below, then the section runs.
GAME_KEYS = ["opponent", "game_date"]

run_section("19_extract_opponent_name_from_pbp_mhtml")


### Identify the upcoming opponent

Read the single "Upcoming" row off `schedule` (built in Cell 4) to get the opponent's full name, then match it against `scouted_opponents` to get the short name used throughout the rest of this notebook (filenames, `player_profiles`, etc).

In [50]:
# Identify the upcoming opponent from the schedule
# Code: parser_lib\20_identify_upcoming_opponent.py  --  settings below, then the section runs.

run_section("20_identify_upcoming_opponent")

No scout report on file for the next scheduled opponent (UW-Stevens Point Pointers) -- using the schedule's own name for them as the short name, so their prior-game PBP (season leaders, team stats, lineups) is still built. Only the scouting-report-sourced output (game plan, keys to victory, player notes, tag-based comparisons) will be missing.


### Roster pages: photo, jersey number, position, height, class year -- bio fields only, never stats

FastScout has a team roster page at the same kind of URL as the schedule/games page (a team's base URL with
`/roster`), for UW-Whitewater and for every opponent. This scrapes it for **photo, jersey number, position,
height and class year only** -- any table on that page that looks like a stat table (PPG, RPG, minutes, ...)
is dropped before anything is read, so no game or season stat is ever pulled from these pages.

Selectors (`#myTeamRoster`, the "ROSTER" nav tab) are best-effort guesses modeled on the schedule tab's own
pattern, since this environment has no live FastScout access to confirm them against. If they're wrong, this
cell reports exactly what it tried and falls back safely -- `uww_live_rosters.csv` comes back empty and
downstream tables (Personnel Details) keep using the sample placeholder, rather than the run failing.

In [52]:
# --- Roster pages: player photo, number, position, height, class year -- for UWW and every opponent ------
# Code: parser_lib\21_roster_pages.py  --  settings below, then the section runs.

run_section("21_roster_pages")

Roster targets this run: ['UW-Whitewater Warhawks', 'Ripon Red Hawks', 'St. Thomas (TX) Celts', 'Eureka Red Devils', 'Aurora Spartans', 'Simpson Storm', 'Elmhurst Bluejays', 'Lawrence Vikings', 'Carroll (WI) Pioneers', 'Hope Flying Dutchmen', 'Alma Scots', 'Coe Kohawks', 'UW-Oshkosh Titans', 'UW-Stevens Point Pointers']
  Skipping live roster scrape for UW-Whitewater Warhawks -- a local roster file already exists.
  Skipping live roster scrape for Ripon Red Hawks -- a local roster file already exists.
  Skipping live roster scrape for St. Thomas (TX) Celts -- a local roster file already exists.
  Skipping live roster scrape for Eureka Red Devils -- a local roster file already exists.
  Skipping live roster scrape for Aurora Spartans -- a local roster file already exists.
  Skipping live roster scrape for Simpson Storm -- a local roster file already exists.
  Skipping live roster scrape for Elmhurst Bluejays -- a local roster file already exists.
  Skipping live roster scrape for Lawrence Vikings -- a local roster file already exists.
  Skipping live roster scrape for Carroll (WI) Pioneers -- a local roster file already exists.
  Skipping live roster scrape for Hope Flying Dutchmen -- a local roster file already exists.
  Skipping live roster scrape for Alma Scots -- a local roster file already exists.
  Skipping live roster scrape for Coe Kohawks -- a local roster file already exists.
  Skipping live roster scrape for UW-Oshkosh Titans -- a local roster file already exists.
  Skipping live roster scrape for UW-Stevens Point Pointers -- a local roster file already exists.
    [roster] UW-Whitewater Warhawks: 19 photo(s) matched by name in the URL, 2 fell back to page position (lower confidence -- spot-check these).
    [roster] St. Thomas (TX) Celts: 20 photo(s) matched by name in the URL, 1 fell back to page position (lower confidence -- spot-check these).
    [roster] Eureka Red Devils: 25 photo(s) matched by name in the URL, 6 fell back to page position (lower confidence -- spot-check these).
    [roster] Aurora Spartans: 23 photo(s) matched by name in the URL, 4 fell back to page position (lower confidence -- spot-check these).
    [roster] Carroll (WI) Pioneers: 16 photo(s) matched by name in the URL, 2 fell back to page position (lower confidence -- spot-check these).
    [roster] UW-Stevens Point Pointers: 18 photo(s) matched by name in the URL, 2 fell back to page position (lower confidence -- spot-check these).

live_rosters: 323 player(s) across 14 team(s).

                           value
team
Alma Scots                    29
Aurora Spartans               27
Carroll (WI) Pioneers         18
Coe Kohawks                   23
Elmhurst Bluejays             25
Eureka Red Devils             31
Hope Flying Dutchmen          19
Lawrence Vikings              20
Ripon Red Hawks               26
Simpson Storm                 21
St. Thomas (TX) Celts         21
UW-Oshkosh Titans             22
UW-Stevens Point Pointers     20
UW-Whitewater Warhawks        21


### Locate the opponent's own schedule backup file

`schedule` only has ONE row per opponent (their single game vs UWW), so it can't tell us what this opponent's own games looked like before they played Whitewater. `_schedule_file_for` finds their own "\<Team\> - Schedule.mhtml"/".html" backup file on disk -- used only as a fallback (see the next cell, which prefers the schedule Cell 4 already scraped/parsed live).

In [54]:
# `schedule` only has ONE row per opponent (their single game vs UWW), so it can't tell us what THIS
# Code: parser_lib\22_locate_opponent_own_schedule_backup_file.py  --  settings below, then the section runs.

run_section("22_locate_opponent_own_schedule_backup_file")


### Resolve the opponent's parsed schedule from Cell 4

Cell 4 already scraped and parsed every opponent's own schedule into `team_schedules` this run (live from FastScout, with a local MHTML backup only as a last resort) -- reuse that in-memory result instead of re-deriving a file path and re-parsing HTML from scratch. A live-scraped opponent schedule IS cached to disk too, via `scrape_rendered_html`'s `save_path` in Cell 4 -- this cell just prefers the in-memory `team_schedules` result already parsed THIS run.

In [56]:
# Live-scraped opponent schedules ARE cached to disk too (scrape_rendered_html's save_path writes
# "<Team> - Schedule.html" via _save_scraped_html). This cell just prefers the in-memory team_schedules
# result already parsed THIS run.
# CONFIRMED BUG (fixed here): upcoming_opponent/upcoming_opponent_short can now legitimately be None
# (see the "Identify the upcoming opponent" cell above -- a fully historical run with no next game, or
# one where the next scheduled opponent has no scout report on file). .lower() on either raised
# AttributeError. Skips this lookup the same way the rest of this notebook already treats "no upcoming
# opponent identified" -- opp_team_schedule falls back to None rather than crashing.
if upcoming_opponent is None or upcoming_opponent_short is None:
    opp_team_schedule = None
else:
    opp_team_schedule = next(
        (
            ts for ts in team_schedules
            if not ts.empty and (
                ts["team"].iloc[0].lower() in upcoming_opponent.lower()
                or upcoming_opponent_short.lower() in ts["team"].iloc[0].lower()
            )
        ),
        None,
    )

### Build `opp_schedule`

Prefer the live-scraped/parsed entry already sitting in `team_schedules` (from Cell 4) over a local backup file -- a live scrape never gets written back to disk as "<Team> - Schedule.mhtml", so a file-only lookup would report "not found" even right after a fully successful live scrape.

In [58]:
# Code: parser_lib\23_build_opp_schedule.py  --  settings below, then the section runs.

run_section("23_build_opp_schedule")

### Find the opponent's games before they played UW-Whitewater

Also print each game's raw video link and check whether a local `_pbp`/`_video` file already exists for it -- these are the games the next two cells try to fill in via a live scrape when a file is missing.

In [60]:
# Code: parser_lib\24_find_opponent_games_before_they_played_uw.py  --  settings below, then the section runs.

run_section("24_find_opponent_games_before_they_played_uw")

UW-Stevens Point Pointers's games before facing UW-Whitewater on 2026-01-07:
           date   game_date                        opponent outcome  \
0    Sat, Nov 1  2025-11-01  Northern Michigan Wildcats EXH       L
1    Sat, Nov 8  2025-11-08                    MSOE Raiders       W
2   Wed, Nov 12  2025-11-12                   St. Olaf Oles       W
3   Sat, Nov 15  2025-11-15                 Edgewood Eagles       W
4   Fri, Nov 21  2025-11-21        Bethany Lutheran Vikings       W
5   Sat, Nov 22  2025-11-22               Millikin Big Blue       W
6   Sat, Nov 29  2025-11-29              North Park Vikings       L
7    Sat, Dec 6  2025-12-06         North Central (MN) Rams       W
8   Sat, Dec 13  2025-12-13                   Olivet Comets       W
9   Sat, Dec 20  2025-12-20          Hardin-Simmons Cowboys       W
10  Sun, Dec 21  2025-12-21             Trinity (TX) Tigers       W
11  Mon, Dec 29  2025-12-29                Lakeland Muskies       W
12   Sat, Jan 3  2026-01-03          UW-Eau Claire Blugolds       W

    team_score  opponent_score  \
0         80.0            84.0
1         79.0            59.0
2         74.0            63.0
3         86.0            75.0
4         78.0            67.0
5         69.0            63.0
6        114.0           115.0
7         78.0            65.0
8         76.0            63.0
9         65.0            61.0
10        74.0            66.0
11        87.0            70.0
12        78.0            75.0

                                                                                                                                                                 video_url  \
0                                                                                                                                                                     None
1   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68dc8153c5675505f18412ed%2ffullgamevideo%2fclips
2   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68de19249955a679080f5fd9%2ffullgamevideo%2fclips
3   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68dc6d688653217cea48c779%2ffullgamevideo%2fclips
4   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9e430a237673855e83039%2ffullgamevideo%2fclips
5   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f69247e3e8e4f8e2ecf0697f1%2ffullgamevideo%2fclips
6   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9bc58012933168a26c35c%2ffullgamevideo%2fclips
7   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d986704a58b24fe360cb34%2ffullgamevideo%2fclips
8   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68da9b01177e5b59c384386f%2ffullgamevideo%2fclips
9   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68dedf309956db1d1cceef60%2ffullgamevideo%2fclips
10  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68dee05b761a87a3fd788e84%2ffullgamevideo%2fclips
11  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68dc77f55c056b698025a72d%2ffullgamevideo%2fclips
12  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68dedf309956db1d1cceef5b%2ffullgamevideo%2fclips

                                                                                                                               game_url  \
0   https://fastscout.fastmodelsports.com/teams/OqTWpgCzTV-VyfWtEnIp-g/games/Xj7IAuL7QACX4ePQvkBOew/boxscore?league=NCAAB-III&season=25
1   https://fastscout.fastmodelsports.com/teams/OqTWpgCzTV-VyfWtEnIp-g/games/JiBSEdfDSmag_v5NEE2STw/boxscore?league=NCAAB-III&season=25
2   https://fastscout.fastmodelsports.com/teams/OqTWpgCzTV-VyfWtEnIp-g/games/Zi2aarWVSUCvqW21HOfUSg/boxscore?league=NCAAB-III&season=25
3   https://fastscout.fastmodelsports.com/teams/OqTWpgCzTV-VyfWtEnIp-g/games/woJlA6EKQmCNpHYiEF3G_w/boxscore?league=NCAAB-III&season=25
4   https://fastscout.fastmodelsports.com/teams/OqTWpgCzTV-VyfWtEnIp-g/games/KekJKPN7T1m30g-K1hwXpQ/boxscore?league=NCAAB-III&season=25
5   https://fastscout.fastmodelsports.com/teams/OqTWpgCzTV-VyfWtEnIp-g/games/_FQGNNpyRN6LwV_4MzKTTA/boxscore?league=NCAAB-III&season=25
6   https://fastscout.fastmodelsports.com/teams/OqTWpgCzTV-VyfWtEnIp-g/games/F-2fhSPWS1CXttcSKxhiow/boxscore?league=NCAAB-III&season=25
7   https://fastscout.fastmodelsports.com/teams/OqTWpgCzTV-VyfWtEnIp-g/games/kOmjPEFXRqOPqOs-VRXglA/boxscore?league=NCAAB-III&season=25
8   https://fastscout.fastmodelsports.com/teams/OqTWpgCzTV-VyfWtEnIp-g/games/gHtVWxuXSOyVRFa7WtI8kw/boxscore?league=NCAAB-III&season=25
9   https://fastscout.fastmodelsports.com/teams/OqTWpgCzTV-VyfWtEnIp-g/games/C45KGsNpQZSa7e7nRtN29Q/boxscore?league=NCAAB-III&season=25
10  https://fastscout.fastmodelsports.com/teams/OqTWpgCzTV-VyfWtEnIp-g/games/DjvlSPjfTxKh7UJZN4d11Q/boxscore?league=NCAAB-III&season=25
11  https://fastscout.fastmodelsports.com/teams/OqTWpgCzTV-VyfWtEnIp-g/games/yuR0aV4pSZOe7Gd36PmExA/boxscore?league=NCAAB-III&season=25
12  https://fastscout.fastmodelsports.com/teams/OqTWpgCzTV-VyfWtEnIp-g/games/MkuVmax0RIqOcEyYFMF8mg/boxscore?league=NCAAB-III&season=25

         location
0            Away
1            Away
2            Away
3            Home
4            Home
5            Home
6            Away
7            Home
8            Away
9   Neutral Court
10           Away
11           Home
12           Home

Video links for these games (raw full-game film, independent of any manually-tagged _video.mhtml export):
  2025-11-01 vs Northern Michigan Wildcats EXH: (no video_url)
  2025-11-08 vs MSOE Raiders: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68dc8153c5675505f18412ed%2ffullgamevideo%2fclips
  2025-11-12 vs St. Olaf Oles: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68de19249955a679080f5fd9%2ffullgamevideo%2fclips
  2025-11-15 vs Edgewood Eagles: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68dc6d688653217cea48c779%2ffullgamevideo%2fclips
  2025-11-21 vs Bethany Lutheran Vikings: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9e430a237673855e83039%2ffullgamevideo%2fclips
  2025-11-22 vs Millikin Big Blue: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f69247e3e8e4f8e2ecf0697f1%2ffullgamevideo%2fclips
  2025-11-29 vs North Park Vikings: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9bc58012933168a26c35c%2ffullgamevideo%2fclips
  2025-12-06 vs North Central (MN) Rams: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d986704a58b24fe360cb34%2ffullgamevideo%2fclips
  2025-12-13 vs Olivet Comets: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68da9b01177e5b59c384386f%2ffullgamevideo%2fclips
  2025-12-20 vs Hardin-Simmons Cowboys: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68dedf309956db1d1cceef60%2ffullgamevideo%2fclips
  2025-12-21 vs Trinity (TX) Tigers: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68dee05b761a87a3fd788e84%2ffullgamevideo%2fclips
  2025-12-29 vs Lakeland Muskies: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68dc77f55c056b698025a72d%2ffullgamevideo%2fclips
  2026-01-03 vs UW-Eau Claire Blugolds: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68dedf309956db1d1cceef5b%2ffullgamevideo%2fclips

Missing _pbp or _video files for the following games before the Whitewater matchup:
  2025-11-01 vs Northern Michigan Wildcats EXH: pbp_found=True, video_found=False

### Live-scrape any missing play-by-play files as a fallback

Reuses the one shared FastScout Playwright session from Cell 4 (`run_in_fastscout_session`) rather than opening its own browser+thread.

In [62]:
# Code: parser_lib\25_live_scrape_any_missing_play_by_play_files.py  --  settings below, then the section runs.

run_section("25_live_scrape_any_missing_play_by_play_files")

### Parse play-by-play events for the opponent's prior games

Builds `pbp_events_upcoming` from every local (or just-cached, live-scraped) `_pbp` file found for these prior games.

In [64]:
# Code: parser_lib\26_parse_play_by_play_events_for_opponent.py  --  settings below, then the section runs.

run_section("26_parse_play_by_play_events_for_opponent")

,opponent,game_date,event_order,period,time_remaining,time_remaining_seconds,team,event_type,raw_text,uww_score,opp_score,player,shot_type,shot_desc,turnover_type,foul_type,ft_num,ft_total
0,Northern Michigan Wildcats EXH,2025-11-01,0,None,None,NaN,None,period_marker,Start 1st Half,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Northern Michigan Wildcats EXH,2025-11-01,1,H1,19:57 (H1),1197.0,UW-Stevens Point Pointers,jump_ball_won,Cal Krohn Wins Jump Ball,0.0,0.0,Cal Krohn,NaN,NaN,NaN,NaN,NaN,NaN
2,Northern Michigan Wildcats EXH,2025-11-01,2,H1,19:57 (H1),1197.0,Northern Michigan Wildcats EXH,jump_ball_lost,Dylan Kuehl Loses Jump Ball,0.0,0.0,Dylan Kuehl,NaN,NaN,NaN,NaN,NaN,NaN
3,Northern Michigan Wildcats EXH,2025-11-01,3,H1,19:20 (H1),1160.0,UW-Stevens Point Pointers,made_shot,Cal Krohn Makes 2PT Jump Shot,2.0,0.0,Cal Krohn,2,Jump Shot,NaN,NaN,NaN,NaN
4,Northern Michigan Wildcats EXH,2025-11-01,4,H1,19:10 (H1),1150.0,Northern Michigan Wildcats EXH,turnover,Dylan Kuehl Turnover (Bad Pass),2.0,0.0,Dylan Kuehl,NaN,NaN,Bad Pass,NaN,NaN,NaN
5,Northern Michigan Wildcats EXH,2025-11-01,5,H1,19:02 (H1),1142.0,UW-Stevens Point Pointers,made_shot,Seth Miron Makes 3PT Jump Shot,5.0,0.0,Seth Miron,3,Jump Shot,NaN,NaN,NaN,NaN
6,Northern Michigan Wildcats EXH,2025-11-01,6,H1,19:02 (H1),1142.0,UW-Stevens Point Pointers,assist,Logan Baumgartner Assists,5.0,0.0,Logan Baumgartner,NaN,NaN,NaN,NaN,NaN,NaN
7,Northern Michigan Wildcats EXH,2025-11-01,7,H1,18:46 (H1),1126.0,Northern Michigan Wildcats EXH,made_shot,Dylan Kuehl Makes 2PT Dunk,5.0,2.0,Dylan Kuehl,2,Dunk,NaN,NaN,NaN,NaN
8,Northern Michigan Wildcats EXH,2025-11-01,8,H1,18:46 (H1),1126.0,Northern Michigan Wildcats EXH,assist,Bennett Basich Assists,5.0,2.0,Bennett Basich,NaN,NaN,NaN,NaN,NaN,NaN
9,Northern Michigan Wildcats EXH,2025-11-01,9,H1,18:33 (H1),1113.0,UW-Stevens Point Pointers,made_shot,Carter Combs Makes 3PT Jump Shot,8.0,2.0,Carter Combs,3,Jump Shot,NaN,NaN,NaN,NaN
10,Northern Michigan Wildcats EXH,2025-11-01,10,H1,18:33 (H1),1113.0,UW-Stevens Point Pointers,assist,Seth Miron Assists,8.0,2.0,Seth Miron,NaN,NaN,NaN,NaN,NaN,NaN
11,Northern Michigan Wildcats EXH,2025-11-01,11,H1,18:17 (H1),1097.0,Northern Michigan Wildcats EXH,foul,Cal Klesmit Commits Offensive Foul,8.0,2.0,Cal Klesmit,NaN,NaN,NaN,Offensive Foul,NaN,NaN
12,Northern Michigan Wildcats EXH,2025-11-01,12,H1,18:17 (H1),1097.0,Northern Michigan Wildcats EXH,turnover,Cal Klesmit Turnover (Offensive Foul),8.0,2.0,Cal Klesmit,NaN,NaN,Offensive Foul,NaN,NaN,NaN
13,Northern Michigan Wildcats EXH,2025-11-01,13,H1,17:52 (H1),1072.0,UW-Stevens Point Pointers,turnover,Seth Miron Turnover (Bad Pass),8.0,2.0,Seth Miron,NaN,NaN,Bad Pass,NaN,NaN,NaN
14,Northern Michigan Wildcats EXH,2025-11-01,14,H1,17:52 (H1),1072.0,Northern Michigan Wildcats EXH,steal,Sam Privet Steals,8.0,2.0,Sam Privet,NaN,NaN,NaN,NaN,NaN,NaN
15,Northern Michigan Wildcats EXH,2025-11-01,15,H1,17:46 (H1),1066.0,Northern Michigan Wildcats EXH,made_shot,Sam Privet Makes 2PT Dunk,8.0,4.0,Sam Privet,2,Dunk,NaN,NaN,NaN,NaN
16,Northern Michigan Wildcats EXH,2025-11-01,16,H1,17:38 (H1),1058.0,UW-Stevens Point Pointers,made_shot,Logan Baumgartner Makes 2PT Layup,10.0,4.0,Logan Baumgartner,2,Layup,NaN,NaN,NaN,NaN
17,Northern Michigan Wildcats EXH,2025-11-01,17,H1,17:38 (H1),1058.0,Northern Michigan Wildcats EXH,foul,Sam Privet Commits Personal Foul,10.0,4.0,Sam Privet,NaN,NaN,NaN,Personal Foul,NaN,NaN
18,Northern Michigan Wildcats EXH,2025-11-01,18,H1,17:38 (H1),1058.0,UW-Stevens Point Pointers,free_throw_made,Logan Baumgartner Makes Free Throw (1 of 1),11.0,4.0,Logan Baumgartner,NaN,NaN,NaN,NaN,1,1
19,Northern Michigan Wildcats EXH,2025-11-01,19,H1,17:27 (H1),1047.0,UW-Stevens Point Pointers,foul,Logan Baumgartner Commits Personal Foul,11.0,4.0,Logan Baumgartner,NaN,NaN,NaN,Personal Foul,NaN,NaN

  ... 6,479 more row(s) of 6,499 (SHOW_ROWS = 20)


### Shared video-tagging helper functions

Hoisted here (rather than defined inline where first used) so cell run-order doesn't matter -- `parse_video_mhtml`, `expand_clip_to_subevents`, `global_align`, `RESULT_TO_KEY`, and `FREE_THROW_EVENT_TYPES` are reused both by the opponent's-own-games attachment below and by the later cell that attaches video tags onto UWW's own `pbp_events`.

In [66]:
# --- Shared video-tagging helper functions, hoisted here so cell run-order doesn't matter -------------------
# Code: parser_lib\27_shared_video_tagging_helper_functions.py  --  settings below, then the section runs.
AND1_SHOT_RE = re.compile(r"Make (2|3) Pts Foul")
FREE_THROW_EVENT_TYPES = {"free_throw_made", "free_throw_missed"}
# Confirmed-by-video-review manual overrides -- keyed by (opponent_short, video clip "No.") -> the pbp_events
# "event_order" it actually corresponds to.
CONFIRMED_CLIP_EVENT_OVERRIDES = {
    ("Ripon", 120): 271,
    ("Ripon", 164): 371,
}
VIDEO_SCRAPE_RETRY_DAYS = 3

run_section("27_shared_video_tagging_helper_functions")


### Attach video-tagging clip descriptions onto the opponent's prior-game events

Reuses the helpers from the cell above to align each `_video` export's clip descriptions onto `pbp_events_upcoming`. Only the per-game team resolution differs from the later UWW version: these are the opponent's own games against a varying actual opponent each time, not always UW-Whitewater vs. them.

In [68]:
# --- Attach video-tagging clip descriptions onto pbp_events_upcoming, same method as pbp_events uses --------
# Code: parser_lib\28_attach_video_tagging_clip_descriptions.py  --  settings below, then the section runs.

run_section("28_attach_video_tagging_clip_descriptions")

  MSOE Raiders: matched 166/181 eligible pbp events to 173 video sub-events (183 clips)
  St. Olaf Oles: matched 183/195 eligible pbp events to 187 video sub-events (193 clips)
  Edgewood Eagles: matched 234/257 eligible pbp events to 244 video sub-events (246 clips)
  Bethany Lutheran Vikings: matched 210/234 eligible pbp events to 220 video sub-events (224 clips)
  Millikin Big Blue: matched 190/207 eligible pbp events to 197 video sub-events (198 clips)
  North Park Vikings: matched 267/293 eligible pbp events to 280 video sub-events (300 clips)
  North Central (MN) Rams: matched 207/223 eligible pbp events to 211 video sub-events (222 clips)
  Olivet Comets: matched 158/169 eligible pbp events to 199 video sub-events (202 clips)
  Hardin-Simmons Cowboys: matched 178/213 eligible pbp events to 206 video sub-events (215 clips)
  Trinity (TX) Tigers: matched 207/234 eligible pbp events to 225 video sub-events (240 clips)
  Lakeland Muskies: matched 192/204 eligible pbp events to 198 video sub-events (209 clips)
  UW-Eau Claire Blugolds: matched 191/213 eligible pbp events to 203 video sub-events (207 clips)

Tagged-video coverage for UW-Stevens Point Pointers: 12 of 13 game(s) before facing UWW contributed tagged shots.

     game_date                              vs                                                             video_file  pbp_rows  clips  matched                                      why
0   2025-11-01  Northern Michigan Wildcats EXH                                                                              531      0        0  no _video file found and no live scrape
1   2025-11-08                    MSOE Raiders            11_8_25 UW-Stevens Point Pointers @ MSOE Raiders_video.html       456    183      166
2   2025-11-12                   St. Olaf Oles          11_12_25 UW-Stevens Point Pointers @ St. Olaf Oles_video.html       437    193      183
3   2025-11-15                 Edgewood Eagles        11_15_25 Edgewood Eagles @ UW-Stevens Point Pointers_video.html       548    246      234
4   2025-11-21        Bethany Lutheran Vikings  11_21_25 Bethany Lutheran Vikings @ UW-Stevens Point Pointers_vide...       547    224      210
5   2025-11-22               Millikin Big Blue      11_22_25 Millikin Big Blue @ UW-Stevens Point Pointers_video.html       451    198      190
6   2025-11-29              North Park Vikings     11_29_25 UW-Stevens Point Pointers @ North Park Vikings_video.html       630    300      267
7   2025-12-06         North Central (MN) Rams  12_6_25 North Central (MN) Rams @ UW-Stevens Point Pointers_video....       483    222      207
8   2025-12-13                   Olivet Comets          12_13_25 UW-Stevens Point Pointers @ Olivet Comets_video.html       488    202      158
9   2025-12-20          Hardin-Simmons Cowboys  12_20_25 UW-Stevens Point Pointers @ Hardin-Simmons Cowboys_video....       481    215      178
10  2025-12-21             Trinity (TX) Tigers    12_21_25 UW-Stevens Point Pointers @ Trinity (TX) Tigers_video.html       523    240      207
11  2025-12-29                Lakeland Muskies       12_29_25 Lakeland Muskies @ UW-Stevens Point Pointers_video.html       478    209      192
12  2026-01-03          UW-Eau Claire Blugolds   1_3_26 UW-Eau Claire Blugolds @ UW-Stevens Point Pointers_video.html       446    207      191

1 game(s) contributed nothing -- reasons above. The most common cause is a filename the glob can't see: it needs BOTH the no-leading-zero date ("1_10_26", not "01_10_26") and "UW-Stevens Point Pointers" in the name, e.g. "1_10_26 UW-Stevens Point Pointers @ Coe_video.mhtml".

Games with a video-tagging file: ['MSOE Raiders', 'St. Olaf Oles', 'Edgewood Eagles', 'Bethany Lutheran Vikings', 'Millikin Big Blue', 'North Park Vikings', 'North Central (MN) Rams', 'Olivet Comets', 'Hardin-Simmons Cowboys', 'Trinity (TX) Tigers', 'Lakeland Muskies', 'UW-Eau Claire Blugolds']
pbp_events_upcoming rows with a matched video description: 2383 of 6499

,opponent,game_date,event_order,period,time_remaining,time_remaining_seconds,team,event_type,raw_text,uww_score,opp_score,player,shot_type,shot_desc,turnover_type,foul_type,ft_num,ft_total,video_description,video_result,video_player,video_clip_number
534,MSOE Raiders,2025-11-08,3,H1,19:39 (H1),1179.0,UW-Stevens Point Pointers,made_shot,Logan Baumgartner Makes 3PT Jump Shot,3.0,0.0,Logan Baumgartner,3,Jump Shot,NaN,NaN,NaN,NaN,15 Logan Baumgartner > Spot-Up > No Dribble Jumper > Guarded > Lon...,Make 3 Pts,Logan Baumgartner,1.0
536,MSOE Raiders,2025-11-08,5,H1,19:19 (H1),1159.0,MSOE Raiders,missed_shot,Jonathan Burroughs Misses 2PT Jump Shot,3.0,0.0,Jonathan Burroughs,2,Jump Shot,NaN,NaN,NaN,NaN,5 Jonathan Burroughs > Hand Off > From Stationary > Top > Dribble ...,Miss 2 Pts,Jonathan Burroughs,2.0
538,MSOE Raiders,2025-11-08,7,H1,19:02 (H1),1142.0,UW-Stevens Point Pointers,missed_shot,Seth Miron Misses 3PT Jump Shot,3.0,0.0,Seth Miron,3,Jump Shot,NaN,NaN,NaN,NaN,2 Seth Miron > Spot-Up > No Dribble Jumper > Guarded > Long/3pt > ...,Miss 3 Pts,Seth Miron,3.0
540,MSOE Raiders,2025-11-08,9,H1,18:50 (H1),1130.0,UW-Stevens Point Pointers,missed_shot,Cal Krohn Misses 2PT Jump Shot,3.0,0.0,Cal Krohn,2,Jump Shot,NaN,NaN,NaN,NaN,12 Cal Krohn > Post-Up > Right Block > Right Shoulder > Dribble Mo...,Miss 2 Pts,Cal Krohn,4.0
542,MSOE Raiders,2025-11-08,11,H1,18:29 (H1),1109.0,MSOE Raiders,missed_shot,Carson Cordelli Misses 3PT Jump Shot,3.0,0.0,Carson Cordelli,3,Jump Shot,NaN,NaN,NaN,NaN,42 Carson Cordelli > Spot-Up > No Dribble Jumper > Open > Long/3pt...,Miss 3 Pts,Carson Cordelli,5.0
544,MSOE Raiders,2025-11-08,13,H1,18:18 (H1),1098.0,UW-Stevens Point Pointers,missed_shot,Logan Baumgartner Misses 3PT Jump Shot,3.0,0.0,Logan Baumgartner,3,Jump Shot,NaN,NaN,NaN,NaN,15 Logan Baumgartner > Off Screen > To Shooter's Left > Straight >...,Miss 3 Pts,Logan Baumgartner,6.0
546,MSOE Raiders,2025-11-08,15,H1,18:03 (H1),1083.0,MSOE Raiders,made_shot,Chase Cummings Makes 2PT Layup,3.0,2.0,Chase Cummings,2,Layup,NaN,NaN,NaN,NaN,25 Chase Cummings > Transition > Right Wing > To Basket > Make 2 P...,1 Pts,Chase Cummings,7.0
549,MSOE Raiders,2025-11-08,18,H1,18:03 (H1),1083.0,MSOE Raiders,free_throw_made,Chase Cummings Makes Free Throw (1 of 1),3.0,3.0,Chase Cummings,NaN,NaN,NaN,NaN,1,1,25 Chase Cummings > Transition > Right Wing > To Basket > Make 2 P...,1 Pts,Chase Cummings,7.0
550,MSOE Raiders,2025-11-08,19,H1,17:54 (H1),1074.0,UW-Stevens Point Pointers,missed_shot,Seth Miron Misses 2PT Jump Shot,3.0,3.0,Seth Miron,2,Jump Shot,NaN,NaN,NaN,NaN,2 Seth Miron > Spot-Up > Drives Left > To Basket > Miss 2 Pts,Miss 2 Pts,Seth Miron,9.0
552,MSOE Raiders,2025-11-08,21,H1,17:42 (H1),1062.0,UW-Stevens Point Pointers,foul,Josiah Butler Commits Personal Foul,3.0,3.0,Josiah Butler,NaN,NaN,NaN,Personal Foul,NaN,NaN,5 Jonathan Burroughs > Non Possession > Non Shooting Foul,Non Shooting Foul,Jonathan Burroughs,10.0
553,MSOE Raiders,2025-11-08,22,H1,17:29 (H1),1049.0,MSOE Raiders,missed_shot,Matus Dopirak Misses 2PT Jump Shot,3.0,3.0,Matus Dopirak,2,Jump Shot,NaN,NaN,NaN,NaN,25 Chase Cummings > P&R Ball Handler > Left P&R > Side > Dribble O...,Miss 2 Pts,Matus Dopirak,11.0
555,MSOE Raiders,2025-11-08,24,H1,17:25 (H1),1045.0,MSOE Raiders,made_shot,Jonathan Burroughs Makes 3PT Jump Shot,3.0,6.0,Jonathan Burroughs,3,Jump Shot,NaN,NaN,NaN,NaN,5 Jonathan Burroughs > Spot-Up > No Dribble Jumper > Open > Long/3...,Make 3 Pts,Jonathan Burroughs,12.0
557,MSOE Raiders,2025-11-08,26,H1,17:00 (H1),1020.0,UW-Stevens Point Pointers,missed_shot,Seth Miron Misses 2PT Jump Shot,3.0,6.0,Seth Miron,2,Jump Shot,NaN,NaN,NaN,NaN,2 Seth Miron > Post-Up > Left Block > Left Shoulder > Dribble Move...,Miss 2 Pts,Seth Miron,13.0
559,MSOE Raiders,2025-11-08,28,H1,16:53 (H1),1013.0,MSOE Raiders,turnover,Chase Cummings Turnover (Lost Ball),3.0,6.0,Chase Cummings,NaN,NaN,Lost Ball,NaN,NaN,NaN,25 Chase Cummings > Transition > Left Wing > Turnover,Turnover,Chase Cummings,14.0
566,MSOE Raiders,2025-11-08,35,H1,16:26 (H1),986.0,MSOE Raiders,missed_shot,Matus Dopirak Misses 2PT Jump Shot,3.0,6.0,Matus Dopirak,2,Jump Shot,NaN,NaN,NaN,NaN,25 Chase Cummings > Post-Up > Left Block > Left Shoulder > Dribble...,Miss 2 Pts,Matus Dopirak,16.0
568,MSOE Raiders,2025-11-08,37,H1,16:19 (H1),979.0,MSOE Raiders,foul,Carson Cordelli Commits Personal Foul,3.0,6.0,Carson Cordelli,NaN,NaN,NaN,Personal Foul,NaN,NaN,4 Josiah Butler > Transition > Left Wing > To Basket > Foul,Foul,Josiah Butler,17.0
569,MSOE Raiders,2025-11-08,38,H1,16:19 (H1),979.0,UW-Stevens Point Pointers,free_throw_made,Josiah Butler Makes Free Throw (1 of 2),4.0,6.0,Josiah Butler,NaN,NaN,NaN,NaN,1,2,4 Josiah Butler > Non Possession > Free Throw,Free Throw,Josiah Butler,18.0
570,MSOE Raiders,2025-11-08,39,H1,16:19 (H1),979.0,UW-Stevens Point Pointers,free_throw_made,Josiah Butler Makes Free Throw (2 of 2),5.0,6.0,Josiah Butler,NaN,NaN,NaN,NaN,2,2,4 Josiah Butler > Non Possession > Free Throw,Free Throw,Josiah Butler,19.0
573,MSOE Raiders,2025-11-08,42,H1,15:57 (H1),957.0,MSOE Raiders,turnover,Chase Cummings Turnover (Lost Ball),5.0,6.0,Chase Cummings,NaN,NaN,Lost Ball,NaN,NaN,NaN,25 Chase Cummings > No Play Type > Turnover,Turnover,Chase Cummings,20.0
576,MSOE Raiders,2025-11-08,45,H1,15:44 (H1),944.0,UW-Stevens Point Pointers,made_shot,Josiah Butler Makes 2PT Jump Shot,7.0,6.0,Josiah Butler,2,Jump Shot,NaN,NaN,NaN,NaN,4 Josiah Butler > Post-Up > Right Block > Left Shoulder > Dribble ...,Make 2 Pts,Josiah Butler,21.0

  ... 2,363 more row(s) of 2,383 (SHOW_ROWS = 20)


### Scout the upcoming opponent's own tendencies from their prior games

Splits `pbp_events_upcoming` into the opponent's own events vs. their opponents' events, then summarizes shot-type volume/efficiency by play type and contest level -- the opponent's own tendencies heading into the Whitewater game.

In [70]:
# --- Scout the upcoming opponent's own tendencies from their games before facing Whitewater -------------------
# Code: parser_lib\29_scout_upcoming_opponent_own_tendencies.py  --  settings below, then the section runs.

run_section("29_scout_upcoming_opponent_own_tendencies")

UW-Stevens Point Pointers's own events across their 13 games before Whitewater: 3220
Their opponents' events across those same games: 3221

UW-Stevens Point Pointers's shot-type tendencies (volume + efficiency, tagged by play_type/guarded) across their last 13 games:

   shot_type  shot_desc         play_type guarded  attempts  makes  fg_pct
0          3  Jump Shot           Spot-Up     Yes        78     22    28.2
1          3  Jump Shot           Spot-Up      No        75     23    30.7
2          2      Layup               Cut     N/A        67     48    71.6
3          2      Layup           Post-Up     N/A        66     42    63.6
4          2      Layup        Transition     N/A        32     20    62.5
5          2  Jump Shot           Spot-Up     N/A        27      9    33.3
6          2  Jump Shot           Post-Up     N/A        26     14    53.8
7          2      Layup               ISO     N/A        22     19    86.4
8          2  Jump Shot               Cut     N/A        19      9    47.4
9          2  Jump Shot               ISO     N/A        16      5    31.2
10         2      Layup           Spot-Up     N/A        16      9    56.2
11         2      Layup  P&R Ball Handler     N/A        14     11    78.6
12         3  Jump Shot  P&R Ball Handler     N/A        14      4    28.6
13         3  Jump Shot        Off Screen     Yes        12      2    16.7
14         3  Jump Shot           Spot-Up     N/A        11      1     9.1

  ... 56 more row(s) of 71 (SHOW_ROWS = 15)

UW-Stevens Point Pointers's shot attempts by play type:

            play_type  attempts  makes  fg_pct
0             Spot-Up       223     74    33.2
1                 Cut       106     66    62.3
2             Post-Up        99     57    57.6
3          Transition        63     34    54.0
4                 ISO        55     30    54.5
5    P&R Ball Handler        39     18    46.2
6          Off Screen        30     11    36.7
7            Hand Off        23     11    47.8
8   Offensive Rebound        18     14    77.8
9        P&R Roll Man         7      4    57.1
10       No Play Type         3      2    66.7

UW-Stevens Point Pointers's shot attempts by contest level:

  guarded  attempts  makes  fg_pct
0     N/A       447    252    56.4
1     Yes       113     33    29.2
2      No       106     36    34.0

UW-Stevens Point Pointers's turnover types (138 total, tagged by play_type):

     turnover_type          play_type  count
0         Bad Pass       No Play Type     18
12       Lost Ball            Post-Up     11
8        Lost Ball       No Play Type      9
16  Offensive Foul       No Play Type      7
14       Lost Ball         Transition      4
13       Lost Ball            Spot-Up      3
1         Bad Pass   P&R Ball Handler      3
2         Bad Pass            Post-Up      3
6        Lost Ball           Hand Off      3
19  Offensive Foul            Spot-Up      3
5        Lost Ball                Cut      2
21          Travel           Hand Off      2
7        Lost Ball                ISO      2
26          Travel            Post-Up      2
10       Lost Ball  Offensive Rebound      2

  ... 14 more row(s) of 29 (SHOW_ROWS = 15)

UW-Stevens Point Pointers's foul types (253 total, with video_description):

         foul_type                                                      video_description  count
93   Personal Foul               3 Carrington Mcneal > Non Possession > Non Shooting Foul      4
17   Personal Foul               0 Matthew Alexander > Non Possession > Non Shooting Foul      3
80   Personal Foul                     21 Liam Roche > Non Possession > Non Shooting Foul      2
126  Personal Foul              5 Jonathan Burroughs > Non Possession > Non Shooting Foul      2
106  Personal Foul                 3 Nate Straughter > Non Possession > Non Shooting Foul      2
41   Personal Foul                   11 Joey Jendusa > Non Possession > Non Shooting Foul      2
122  Personal Foul                42 Carson Cordelli > Non Possession > Non Shooting Foul      2
84   Personal Foul                 23 Jack Brockmann > Non Possession > Non Shooting Foul      2
90   Personal Foul                 25 Chase Cummings > Non Possession > Non Shooting Foul      1
91   Personal Foul                   3 Asher Fleming > Non Possession > Non Shooting Foul      1
92   Personal Foul  3 Asher Fleming > P&R Ball Handler > Right P&R > Side > Go Away fr...      1
0             Foul            11 Sean Shenker > Transition > Leak Outs > To Basket > Foul      1
94   Personal Foul                      3 Carrington Mcneal > Post-Up > Left Block > Foul      1
88   Personal Foul  24 Kobe Kirk > Post-Up > Flash Middle > Post Pin > No Dribble Move...      1
95   Personal Foul                       3 Dean Balo > Non Possession > Non Shooting Foul      1

  ... 123 more row(s) of 138 (SHOW_ROWS = 15)

UW-Stevens Point Pointers's top scorers across their last 13 games (from play-by-play):

              player  total_points_across_13_games
0      Josiah Butler                         215.0
1          Cal Krohn                         205.0
2         Seth Miron                         198.0
3  Logan Baumgartner                         122.0
4       Carter Combs                          70.0
5       Isaiah Moore                          58.0
6         Max Raimer                          53.0
7        Josh Bocher                          47.0
8         Grant Manz                          30.0
9        Drew Daoust                          12.0


### Compare PBP-derived opponent tendencies to UWW's own scouting keys

Cross-checks the tendencies just derived from actual play-by-play against UWW's own scouting-report notes (`TEAM STRENGTHS` / `KEYS TO VICTORY`) for this opponent, to see whether the scouted keys hold up against what they've actually done on the floor.

In [72]:
# --- Compare our PBP-derived findings to UWW's own scouting keys for the upcoming opponent ---------------------
# Code: parser_lib\30_compare_pbp_derived_opponent_tendencies_to.py  --  settings below, then the section runs.

run_section("30_compare_pbp_derived_opponent_tendencies_to")

UWW's own scouting notes for UW-Stevens Point Pointers [SOURCE: SCOUTING REPORT]:

--- Comparing PBP evidence to the stated Keys to Victory [SOURCE: SCOUTING REPORT] ---

KEY 1 [SCOUTING REPORT] -- COMMUNICATE SCREENS & ACTIONS:
  Not directly measurable from play-by-play event types (no screen-action tagging) -- this is a
  communication/technique key tied to their offensive scheme (per the scout's own Offensive Scheme notes),
  not something the event log alone can confirm or refute.

KEY 2 [SCOUTING REPORT] -- DOMINATE THE PAINT:
  Their own rebounding split across their 13 games: [{'rebound_type': 'defensive', 'count': 319}, {'rebound_type': 'offensive', 'count': 186}]
  Their layup-area attempts (Layup + Driving Layup): 262 of 645 total FGA
  Blocks recorded against them by opponents: 25
  Compare against their own Defensive Scheme notes and layup-area conversion rate to judge whether this key
  is supported by the evidence.

KEY 3 [SCOUTING REPORT] -- GUARD 1 ON 1:
  Measured 3PT jump-shot rate: 244 attempts at 29.5%.
  Scoring balance (top 5 scorers): [{'player': 'Josiah Butler', 'total_points_across_13_games': 215.0}, {'player': 'Cal Krohn', 'total_points_across_13_games': 205.0}, {'player': 'Seth Miron', 'total_points_across_13_games': 198.0}, {'player': 'Logan Baumgartner', 'total_points_across_13_games': 122.0}, {'player': 'Carter Combs', 'total_points_across_13_games': 70.0}]
  Compare against the scout's own TEAM STRENGTHS note on shooting/scoring balance to judge whether
  over-helping creates open catch-and-shoot looks that straight man coverage would limit.


--- New Keys to Victory, derived from PBP data/tendencies [SOURCE: PBP-DERIVED] ---

DATA-KEY 1 [PBP-DERIVED] -- TAKE AWAY THEIR MOST EFFICIENT HIGH-VOLUME ACTIONS:
  Offensive Rebound: 77.8% on 18 attempts; Cut: 62.3% on 106 attempts
  Each is 5+ points above their 48.5% overall clip on 15+ attempts. Offensive Rebound: hit a body on every shot before going to the ball. Cut: jump to the ball on every pass and see man and ball -- no back-cuts behind ball-watchers.

DATA-KEY 2 [PBP-DERIVED] -- FUNNEL THEM INTO THEIR WORST HIGH-VOLUME LOOKS:
  Spot-Up: 33.2% on 223 attempts; Off Screen: 36.7% on 30 attempts
  Each is 5+ points below their 48.5% overall clip -- don't help off these actions; make them keep taking them.

DATA-KEY 3 [PBP-DERIVED] -- PRESSURE THE ACTIONS THEY TURN IT OVER ON:
  Hand Off: 5 TO in 28 uses (17.9% vs 8.6% across all actions); Post-Up: 19 TO in 118 uses (16.1% vs 8.6% across all actions)
  Loosest actions per use, not the most common ones -- load ball pressure and gap help onto these specifically rather than pressing everything.


Structured PBP-derived keys, ready for CSV export:

,opponent,key_number,title,source,supporting_stats,recommendation
0,UW-Stevens Point Pointers,1,Take away their most efficient high-volume actions,PBP-DERIVED,Offensive Rebound: 77.8% on 18 attempts; Cut: 62.3% on 106 attempts,Each is 5+ points above their 48.5% overall clip on 15+ attempts. ...
1,UW-Stevens Point Pointers,2,Funnel them into their worst high-volume looks,PBP-DERIVED,Spot-Up: 33.2% on 223 attempts; Off Screen: 36.7% on 30 attempts,Each is 5+ points below their 48.5% overall clip -- don't help off...
2,UW-Stevens Point Pointers,3,Pressure the actions they turn it over on,PBP-DERIVED,Hand Off: 5 TO in 28 uses (17.9% vs 8.6% across all actions); Post...,"Loosest actions per use, not the most common ones -- load ball pre..."


### Diagnose the opponent's weakest video-tagged play type

Same method as UWW's own play-type diagnosis (later in the notebook) -- surfaces which play type the opponent has been least efficient at across their games before facing Whitewater, using video-tagged clip data.

In [74]:
# --- Diagnose the upcoming opponent's weakest video-tagged play type, same method as UWW's own diagnosis -------
# Code: parser_lib\31_diagnose_opponent_weakest_video_tagged.py  --  settings below, then the section runs.
HIGH_VOLUME_MIN_ATTEMPTS = 10
# The tagger's own vocabulary doesn't name every shot; these two labels mark where it runs out. Kept as
# named constants so the "best shot type" logic can recognise a residual bucket instead of presenting it as
# a real shot type.
UNCLASSIFIED_SHOT_MECHANIC = "Unclassified (no mechanic tag)"
NO_CONTEST_TAG = "Not tagged (contest recorded only on catch-and-shoot)"

run_section("31_diagnose_opponent_weakest_video_tagged")

UW-Stevens Point Pointers's video-tagged play types, across their 13 games before Whitewater (666 video-matched attempts):

            play_type  attempts  makes  fg_pct
0             Spot-Up       223     74    33.2
1                 Cut       106     66    62.3
2             Post-Up        99     57    57.6
3          Transition        63     34    54.0
4                 ISO        55     30    54.5
5    P&R Ball Handler        39     18    46.2
6          Off Screen        30     11    36.7
7            Hand Off        23     11    47.8
8   Offensive Rebound        18     14    77.8
9        P&R Roll Man         7      4    57.1
10       No Play Type         3      2    66.7

Weakest high-volume play type (>= 10 attempts): 'Spot-Up' at 33.2% (74/223)

'Spot-Up' shot-quality breakdown (223 attempts):

By shot mechanic:

             shot_mechanic  attempts  makes  fg_pct
0          Catch-and-shoot       163     50    30.7
2  Pull-up off the dribble        33     11    33.3
1      Drive to the basket        27     13    48.1

By contest level:

                                                 contest  attempts  makes  fg_pct
2                                                   Open        82     26    31.7
0                                                Guarded        81     24    29.6
1  Not tagged (contest recorded only on catch-and-shoot)        60     24    40.0

By shot distance:

            distance  attempts  makes  fg_pct
0           Long/3pt       166     46    27.7
2                N/A        27     13    48.1
3     Short to < 17'        16      8    50.0
1  Medium/17' to <3p        14      7    50.0

Per-player 'Spot-Up' volume/efficiency, with catch-and-shoot% and guarded% of those attempts:

               player  attempts  makes  fg_pct  pct_catch_and_shoot  pct_guarded
10  Logan Baumgartner        50     16    32.0                 92.0         62.0
12         Seth Miron        43     14    32.6                 83.7         39.5
9       Josiah Butler        36     11    30.6                 61.1         19.4
6        Isaiah Moore        23      9    39.1                 69.6         26.1
3        Carter Combs        21     10    47.6                 71.4         42.9
11         Max Raimer        15      4    26.7                 66.7         26.7
2           Cal Krohn        12      5    41.7                 25.0          8.3
4         Drew Daoust         7      1    14.3                100.0         28.6
14          Tyler Orr         6      1    16.7                 83.3         50.0
8         Josh Bocher         5      2    40.0                 40.0         20.0
0   Austin Schaumburg         1      0     0.0                  0.0          0.0
1      Brandon Tilley         1      0     0.0                  0.0          0.0
5          Grant Manz         1      1   100.0                  0.0          0.0
7        James Jacobs         1      0     0.0                100.0          0.0
13       Shane Tarjan         1      0     0.0                  0.0          0.0


### Load player comparison algorithms and compute tag rarity weights

Portable replacement for `%run UW Whitewater Player Comparison Algorithms` -- imports `build_player_comparison_artifacts` from `player_comparison.py` (reloaded each run so edits to that file are picked up), and identifies the target opponent (the most recently scouted game) to compare its players against every other scouted opponent's roster.

In [76]:
# Portable replacement for "%run UW Whitewater Player Comparison Algorithms" -- imports the same helper logic
# Code: parser_lib\32_load_player_comparison_algorithms_and.py  --  settings below, then the section runs.

run_section("32_load_player_comparison_algorithms_and")

WARNING: upcoming opponent 'UW-Stevens Point Pointers' has no scout report loaded (scouted: ['Alma Scots', 'Aurora Spartans', 'Carroll (WI) Pioneers', 'Coe Kohawks', 'Elmhurst Bluejays', 'Eureka Red Devils', 'Hope Flying Dutchmen', 'Lawrence Vikings', 'Ripon Red Hawks', 'Simpson Storm', 'St. Thomas (TX) Celts', 'UW-Oshkosh Titans']) -- player comparisons will be empty for them. Add their scout report to INPUT_DIR and re-run.
LLM comparison skipped (use_llm=False) -- using tag-based similarity only.
Loaded player comparison algorithms (version 2026-07-29-portable). use_llm=False

Scouted opponents and their game number on the schedule:
  Game #1: Ripon Red Hawks
  Game #2: St. Thomas (TX) Celts
  Game #3: Eureka Red Devils
  Game #4: Aurora Spartans
  Game #5: Simpson Storm
  Game #6: Elmhurst Bluejays
  Game #7: Lawrence Vikings
  Game #8: Carroll (WI) Pioneers
  Game #9: Hope Flying Dutchmen
  Game #10: Alma Scots
  Game #11: Coe Kohawks
  Game #12: UW-Oshkosh Titans

Target (most recently scouted game): UW-Stevens Point Pointers (game #None)
Previous scouted opponents to compare against: ['St. Thomas (TX) Celts', 'Eureka Red Devils', 'Aurora Spartans', 'Simpson Storm', 'Ripon Red Hawks', 'Lawrence Vikings', 'Carroll (WI) Pioneers', 'Hope Flying Dutchmen', 'Alma Scots', 'Elmhurst Bluejays', 'Coe Kohawks', 'UW-Oshkosh Titans']

player_notes-derived tag frequency and rarity-based importance weight (rarer tags count more toward similarity):

                   tag  count  importance_weight
0  three_point_shooter     46              2.033
1       slasher_driver     41              2.145
2          post_scorer     11              3.398
3            rebounder      6              3.937
4      catch_and_shoot      4              4.273
5           high_usage      3              4.497
6            playmaker      3              4.497
7      pull_up_shooter      3              4.497
8               cutter      1              5.190

keys_to_defending-derived tag frequency and rarity-based importance weight:

                     tag  count  importance_weight
0   deny_catch_and_shoot     33              2.356
1        anticipate_move     24              2.664
2           post_defense      7              3.803
3       box_out_priority      6              3.937
4          keep_in_front      5              4.091
5     transition_defense      5              4.091
6           help_defense      4              4.273
7    physical_discipline      3              4.497
8              deny_cuts      1              5.190
9       pressure_disrupt      1              5.190
10     screen_navigation      1              5.190


### Surface tag-based best match per target-opponent player

Displays each target player's single most comparable previously-scouted player, ranked by the tag-based similarity score (playing-style tags, notes/keys overlap, and stat similarity) computed in the cell above.

In [78]:
# CONFIRMED BUG (fixed here): for the very first scouted game of the season there's no PREVIOUS opponent to
# Code: parser_lib\33_surface_tag_based_best_match_per_target.py  --  settings below, then the section runs.

run_section("33_surface_tag_based_best_match_per_target")

No player comparisons available for UW-Stevens Point Pointers yet -- there's no previously-scouted opponent on record to compare their players against. Expected for the first scouted game of the season; comparisons will start appearing once a second opponent has been scouted.


### Compare players using an LLM over their full scouting-note text

An alternative to the tag-based comparison above: sends each target/candidate player's full scouting-note text to an LLM for a similarity judgment. Only runs when `USE_LLM=True` in the Configuration cell (requires `OPENAI_API_KEY`) -- skipped by default.

In [80]:
if not use_llm:
    print("LLM-based comparison was skipped (USE_LLM=False). Set the USE_LLM config variable to True to run this cell.")
else:
    if skipped_targets or skipped_candidates:
        print(f"Skipping {skipped_targets} target player(s) and {skipped_candidates} candidate player(s) with no "
              "scouting report text (box-score-only players) -- the LLM comparison only runs on scouted players.\n")

    print(llm_player_comparison.sort_values(["target_player", "llm_notes_similarity_score"], ascending=[True, False]))

LLM-based comparison was skipped (USE_LLM=False). Set the USE_LLM config variable to True to run this cell.


### Surface the LLM's best match per player, and compare it to the tag-based pick

Shows whether the LLM's top match agrees with the tag-based pick from earlier. Also skipped when `USE_LLM=False`.

In [82]:
# 34_surface_llm_best_match_per_player
# Code: parser_lib\34_surface_llm_best_match_per_player.py  --  settings below, then the section runs.

run_section("34_surface_llm_best_match_per_player")

LLM-based comparison was skipped (USE_LLM=False). Set the USE_LLM config variable to True to run this cell.


### Blend the tag-based and LLM similarity scores

Combines both scores into one ranked list per target player. Skipped when `USE_LLM=False`, since there's no LLM score to blend in.

In [84]:
# 35_blend_tag_based_and_llm_similarity_scores
# Code: parser_lib\35_blend_tag_based_and_llm_similarity_scores.py  --  settings below, then the section runs.

run_section("35_blend_tag_based_and_llm_similarity_scores")

LLM-based comparison was skipped (USE_LLM=False), so there is no LLM score to blend with the tag-based score. Set the USE_LLM config variable to True to run this cell.


### Display best matches

Prints `best_matches` (the tag-based result) on its own -- a plain re-display of the table already shown two cells above, kept as a quick standalone reference.

In [86]:
print(best_matches)

Empty DataFrame
Columns: []
Index: []


### Parse play-by-play MHTML files into a unified event log

Runs `parse_pbp_mhtml`/`build_pbp_events`/`opponent_from_pbp_filename` (defined earlier) over every `"*_pbp.mhtml"` file in `INPUT_DIR`, resolving each file's `self_column` per-game, to build `pbp_events` -- UW-Whitewater's own play-by-play across every scouted game so far.

In [88]:
# --- Play-by-play (PBP) data -----------------------------------------------------------------------------
# Code: parser_lib\36_parse_play_by_play_mhtml_files_into.py  --  settings below, then the section runs.

run_section("36_parse_play_by_play_mhtml_files_into")

Found 28 UW-Whitewater play-by-play file(s):
 - 11_14_25 UW-Whitewater @ St. Thomas (TX) Celts_pbp.html
 - 11_15_25 UW-Whitewater @ Eureka Red Devils_pbp.html
 - 11_19_25 Aurora Spartans @ UW-Whitewater_pbp.html
 - 11_25_25 Simpson Storm @ UW-Whitewater_pbp.html
 - 11_7_25 UW-Whitewater @ Ripon Red Hawks_pbp.html
 - 12_10_25 UW-Whitewater @ Lawrence Vikings_pbp.html
 - 12_13_25 Carroll (WI) Pioneers @ UW-Whitewater_pbp.html
 - 12_19_25 UW-Whitewater @ Hope Flying Dutchmen_pbp.html
 - 12_20_25 UW-Whitewater @ Alma Scots_pbp.html
 - 12_2_25 Elmhurst Bluejays @ UW-Whitewater_pbp.html
 - 12_30_25 UW-Whitewater @ Coe Kohawks_pbp.html
 - 1_10_26 UW-Whitewater @ UW-River Falls Falcons_pbp.html
 - 1_14_26 UW-Whitewater @ UW-La Crosse Eagles_pbp.html
 - 1_17_26 UW-Stout Blue Devils @ UW-Whitewater_pbp.html
 - 1_21_26 UW-Whitewater @ UW-Platteville Pioneers_pbp.html
 - 1_24_26 UW-Eau Claire Blugolds @ UW-Whitewater_pbp.html
 - 1_28_26 UW-Whitewater @ UW-Oshkosh Titans_pbp.html
 - 1_3_26 UW-Oshkosh Titans @ UW-Whitewater_pbp.html
 - 1_7_26 UW-Stevens Point Pointers @ UW-Whitewater_pbp.html
 - 2_11_26 UW-Platteville Pioneers @ UW-Whitewater_pbp.html
 - 2_14_26 UW-Whitewater @ UW-Eau Claire Blugolds_pbp.html
 - 2_18_26 UW-Stevens Point Pointers @ UW-Whitewater_pbp.html
 - 2_21_26 UW-River Falls Falcons @ UW-Whitewater_pbp.html
 - 2_26_26 UW-Platteville Pioneers @ UW-Whitewater_pbp.html
 - 2_28_26 UW-La Crosse Eagles @ UW-Whitewater_pbp.html
 - 2_4_26 UW-La Crosse Eagles @ UW-Whitewater_pbp.html
 - 2_7_26 UW-Whitewater @ UW-Stout Blue Devils_pbp.html
 - 3_6_26 UW-Whitewater @ Loras Duhawks_pbp.html
  Parsed 'St. Thomas (TX) Celts': 444 events
  Parsed 'Eureka Red Devils': 496 events
  WARNING: Detected swapped columns for 'Aurora Spartans' (UWW roster found in right column) -- auto-corrected
  Parsed 'Aurora Spartans': 515 events
  WARNING: Detected swapped columns for 'Simpson Storm' (UWW roster found in right column) -- auto-corrected
  Parsed 'Simpson Storm': 542 events
  Parsed 'Ripon Red Hawks': 482 events
  Parsed 'Lawrence Vikings': 508 events
  WARNING: Detected swapped columns for 'Carroll (WI) Pioneers' (UWW roster found in right column) -- auto-corrected
  Parsed 'Carroll (WI) Pioneers': 495 events
  Parsed 'Hope Flying Dutchmen': 557 events
  Parsed 'Alma Scots': 465 events
  WARNING: Detected swapped columns for 'Elmhurst Bluejays' (UWW roster found in right column) -- auto-corrected
  Parsed 'Elmhurst Bluejays': 430 events
  Parsed 'Coe Kohawks': 423 events
  Parsed 'UW-River Falls Falcons': 484 events
  Parsed 'UW-La Crosse Eagles': 536 events
  WARNING: Detected swapped columns for 'UW-Stout Blue Devils' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-Stout Blue Devils': 480 events
  Parsed 'UW-Platteville Pioneers': 435 events
  WARNING: Detected swapped columns for 'UW-Eau Claire Blugolds' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-Eau Claire Blugolds': 495 events
  Parsed 'UW-Oshkosh Titans': 846 events
  WARNING: Detected swapped columns for 'UW-Oshkosh Titans' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-Oshkosh Titans': 845 events
  WARNING: Detected swapped columns for 'UW-Stevens Point Pointers' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-Stevens Point Pointers': 493 events
  WARNING: Detected swapped columns for 'UW-Platteville Pioneers' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-Platteville Pioneers': 428 events
  Parsed 'UW-Eau Claire Blugolds': 450 events
  WARNING: Detected swapped columns for 'UW-Stevens Point Pointers' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-Stevens Point Pointers': 467 events
  WARNING: Detected swapped columns for 'UW-River Falls Falcons' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-River Falls Falcons': 470 events
  WARNING: Detected swapped columns for 'UW-Platteville Pioneers' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-Platteville Pioneers': 476 events
  WARNING: Detected swapped columns for 'UW-La Crosse Eagles' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-La Crosse Eagles': 449 events
  WARNING: Detected swapped columns for 'UW-La Crosse Eagles' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-La Crosse Eagles': 478 events
  Parsed 'UW-Stout Blue Devils': 488 events
  WARNING: Detected swapped columns for 'Loras Duhawks' (UWW roster found in right column) -- auto-corrected
  Parsed 'Loras Duhawks': 495 events
Dropped 7970 pbp_events row(s) with a game_date on/after reference_date (2026-1-7) -- not yet 'played' in this simulation.

Every play-by-play line was classified.

,opponent,game_date,event_order,period,time_remaining,time_remaining_seconds,team,event_type,raw_text,uww_score,opp_score,player,shot_type,shot_desc,turnover_type,foul_type,ft_num,ft_total
0,St. Thomas (TX) Celts,2025-11-14,0,None,None,NaN,None,period_marker,Start 1st Half,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,St. Thomas (TX) Celts,2025-11-14,1,H1,19:58 (H1),1198.0,St. Thomas (TX) Celts,jump_ball_won,Charles Gitonga Wins Jump Ball,0.0,0.0,Charles Gitonga,NaN,NaN,NaN,NaN,NaN,NaN
2,St. Thomas (TX) Celts,2025-11-14,2,H1,19:58 (H1),1198.0,UW-Whitewater,jump_ball_lost,Brock Marino Loses Jump Ball,0.0,0.0,Brock Marino,NaN,NaN,NaN,NaN,NaN,NaN
3,St. Thomas (TX) Celts,2025-11-14,3,H1,19:34 (H1),1174.0,St. Thomas (TX) Celts,made_shot,Corey Thompson Makes 2PT Turnaround Jump Shot,0.0,2.0,Corey Thompson,2,Turnaround Jump Shot,NaN,NaN,NaN,NaN
4,St. Thomas (TX) Celts,2025-11-14,4,H1,19:22 (H1),1162.0,UW-Whitewater,turnover,Isaac Verges Turnover (Lost Ball),0.0,2.0,Isaac Verges,NaN,NaN,Lost Ball,NaN,NaN,NaN
5,St. Thomas (TX) Celts,2025-11-14,5,H1,19:22 (H1),1162.0,St. Thomas (TX) Celts,steal,Angel Johnson Steals,0.0,2.0,Angel Johnson,NaN,NaN,NaN,NaN,NaN,NaN
6,St. Thomas (TX) Celts,2025-11-14,6,H1,19:16 (H1),1156.0,St. Thomas (TX) Celts,missed_shot,Nathan Kongolo Misses 3PT Jump Shot,0.0,2.0,Nathan Kongolo,3,Jump Shot,NaN,NaN,NaN,NaN
7,St. Thomas (TX) Celts,2025-11-14,7,H1,19:14 (H1),1154.0,UW-Whitewater,rebound_defensive,Collin Madson Defensive Rebound,0.0,2.0,Collin Madson,NaN,NaN,NaN,NaN,NaN,NaN
8,St. Thomas (TX) Celts,2025-11-14,8,H1,19:09 (H1),1149.0,UW-Whitewater,turnover,Isaac Verges Turnover (Bad Pass),0.0,2.0,Isaac Verges,NaN,NaN,Bad Pass,NaN,NaN,NaN
9,St. Thomas (TX) Celts,2025-11-14,9,H1,19:09 (H1),1149.0,St. Thomas (TX) Celts,steal,Nathan Kongolo Steals,0.0,2.0,Nathan Kongolo,NaN,NaN,NaN,NaN,NaN,NaN
10,St. Thomas (TX) Celts,2025-11-14,10,H1,19:05 (H1),1145.0,St. Thomas (TX) Celts,made_shot,Angel Johnson Makes 2PT Layup,0.0,4.0,Angel Johnson,2,Layup,NaN,NaN,NaN,NaN
11,St. Thomas (TX) Celts,2025-11-14,11,H1,19:05 (H1),1145.0,St. Thomas (TX) Celts,assist,Nathan Kongolo Assists,0.0,4.0,Nathan Kongolo,NaN,NaN,NaN,NaN,NaN,NaN
12,St. Thomas (TX) Celts,2025-11-14,12,H1,18:34 (H1),1114.0,UW-Whitewater,missed_shot,Isaac Verges Misses 2PT Layup,0.0,4.0,Isaac Verges,2,Layup,NaN,NaN,NaN,NaN
13,St. Thomas (TX) Celts,2025-11-14,13,H1,18:31 (H1),1111.0,St. Thomas (TX) Celts,rebound_defensive,Nicholas Buffalo Defensive Rebound,0.0,4.0,Nicholas Buffalo,NaN,NaN,NaN,NaN,NaN,NaN
14,St. Thomas (TX) Celts,2025-11-14,14,H1,18:22 (H1),1102.0,St. Thomas (TX) Celts,missed_shot,Corey Thompson Misses 2PT Layup,0.0,4.0,Corey Thompson,2,Layup,NaN,NaN,NaN,NaN
15,St. Thomas (TX) Celts,2025-11-14,15,H1,18:19 (H1),1099.0,St. Thomas (TX) Celts,rebound_offensive,Corey Thompson Offensive Rebound,0.0,4.0,Corey Thompson,NaN,NaN,NaN,NaN,NaN,NaN
16,St. Thomas (TX) Celts,2025-11-14,16,H1,18:18 (H1),1098.0,St. Thomas (TX) Celts,turnover,Corey Thompson Turnover,0.0,4.0,Corey Thompson,NaN,NaN,None,NaN,NaN,NaN
17,St. Thomas (TX) Celts,2025-11-14,17,H1,18:04 (H1),1084.0,UW-Whitewater,made_shot,Collin Madson Makes 2PT Layup,2.0,4.0,Collin Madson,2,Layup,NaN,NaN,NaN,NaN
18,St. Thomas (TX) Celts,2025-11-14,18,H1,18:04 (H1),1084.0,UW-Whitewater,assist,Luke Bara Assists,2.0,4.0,Luke Bara,NaN,NaN,NaN,NaN,NaN,NaN
19,St. Thomas (TX) Celts,2025-11-14,19,H1,17:43 (H1),1063.0,St. Thomas (TX) Celts,made_shot,Angel Johnson Makes 2PT Pull Up Jump Shot,2.0,6.0,Angel Johnson,2,Pull Up Jump Shot,NaN,NaN,NaN,NaN

  ... 6,182 more row(s) of 6,202 (SHOW_ROWS = 20)


### Load coach-tagged "recap" CSVs: per-clip Text Overlay notes (play calls, execution grades)

Some games have a companion `"<matchup>_recap.csv"` export from the video-tagging tool -- one row per
tagged clip, with a `Text Overlay` field holding the coach's own note for that specific play (an offensive
play call and how it was executed, or a defensive breakdown of what went right/wrong). Each row also carries
enough identifying info (period, game clock, team, player) to attach it onto the matching `pbp_events` row
for that same play, so the note shows up in context on the play-by-play rather than as a disconnected list.

Every note is ALSO kept in its own standalone `coach_notes` table regardless of whether it successfully
matched a `pbp_events` row -- a handful of clips have no captured game clock (a between-play/summary note),
which can't be matched to a specific play but shouldn't be silently discarded either; season-wide analytics
(most-called plays, common flagged themes) read from this full table, not just the matched subset.

In [90]:
# --- Playbook catalog: the team's own play index (Hudl "Plays" page, saved as MHTML) -------------------
# Code: parser_lib\37_load_coach_tagged_recap_csvs.py  --  settings below, then the section runs.
PLAYS_CATALOG_COLS = ["season", "team", "series", "play_name", "base_name", "play_family", "aliases", "match_keys"]

run_section("37_load_coach_tagged_recap_csvs")

Found 1 playbook catalog file(s):
 - UW-Whitewater - Plays.mhtml

Parsed 27 play(s) across 9 series and 17 family/families.

        series play_family       play_name aliases
0         ELOB        ELOB            "20"      20
1         Snap        Snap  20 Snap (flip)
2         Snap        Snap       30 (flip)
3         Snap        Snap         40 Snap
4         Over     Cheetah         Cheetah
5       Bursts       Cobra           Cobra
6       Bursts         Fox             Fox
7   Transition         Get             Get
8     Specials    Kentucky        Kentucky
9     Specials     Panther  Panther 2 "P2"      P2
10    Specials     Panther  Panther-4 "P4"      P4
11    Specials     Panther     Panther "P"       P
12        Over         Pin       Pin Flair
13     Entries      Pistol          Pistol
14  Transition       Pitch           Pitch

  ... 12 more row(s) of 27 (SHOW_ROWS = 15)

In [91]:
# --- Parse "*_recap.csv" (single-game coach notes) and "*_plays_*.csv" (season-wide play-call log) exports,
# Code: parser_lib\38_load_coach_tagged_recap_csvs_2.py  --  settings below, then the section runs.

run_section("38_load_coach_tagged_recap_csvs_2")

Found 0 coach-note/play-log CSV(s):


### Reconstruct the on-court 5-man lineup for both teams at every event

Walks each game's `pbp_events` in order, tracking substitutions to derive `uww_lineup`/`opp_lineup` -- the 5 players on the floor for each team at the moment of every event.

In [93]:
# --- On-court 5-man lineups for both teams, at every point in the play-by-play -----------------------------
# Code: parser_lib\39_reconstruct_on_court_5_man_lineup_for_both.py  --  settings below, then the section runs.
TEAM_LEVEL_EVENT_TYPES = {"team_deadball_rebound_offensive", "team_deadball_rebound_defensive", "timeout"}

run_section("39_reconstruct_on_court_5_man_lineup_for_both")

Lineup column check: 0 game(s) had our lineup in the opponent's column and were corrected.

,opponent,period,time_remaining,team,event_type,raw_text,uww_lineup,opp_lineup
0,St. Thomas (TX) Celts,None,None,None,period_marker,Start 1st Half,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
1,St. Thomas (TX) Celts,H1,19:58 (H1),St. Thomas (TX) Celts,jump_ball_won,Charles Gitonga Wins Jump Ball,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
2,St. Thomas (TX) Celts,H1,19:58 (H1),UW-Whitewater,jump_ball_lost,Brock Marino Loses Jump Ball,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
3,St. Thomas (TX) Celts,H1,19:34 (H1),St. Thomas (TX) Celts,made_shot,Corey Thompson Makes 2PT Turnaround Jump Shot,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
4,St. Thomas (TX) Celts,H1,19:22 (H1),UW-Whitewater,turnover,Isaac Verges Turnover (Lost Ball),"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
5,St. Thomas (TX) Celts,H1,19:22 (H1),St. Thomas (TX) Celts,steal,Angel Johnson Steals,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
6,St. Thomas (TX) Celts,H1,19:16 (H1),St. Thomas (TX) Celts,missed_shot,Nathan Kongolo Misses 3PT Jump Shot,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
7,St. Thomas (TX) Celts,H1,19:14 (H1),UW-Whitewater,rebound_defensive,Collin Madson Defensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
8,St. Thomas (TX) Celts,H1,19:09 (H1),UW-Whitewater,turnover,Isaac Verges Turnover (Bad Pass),"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
9,St. Thomas (TX) Celts,H1,19:09 (H1),St. Thomas (TX) Celts,steal,Nathan Kongolo Steals,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
10,St. Thomas (TX) Celts,H1,19:05 (H1),St. Thomas (TX) Celts,made_shot,Angel Johnson Makes 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
11,St. Thomas (TX) Celts,H1,19:05 (H1),St. Thomas (TX) Celts,assist,Nathan Kongolo Assists,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
12,St. Thomas (TX) Celts,H1,18:34 (H1),UW-Whitewater,missed_shot,Isaac Verges Misses 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
13,St. Thomas (TX) Celts,H1,18:31 (H1),St. Thomas (TX) Celts,rebound_defensive,Nicholas Buffalo Defensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
14,St. Thomas (TX) Celts,H1,18:22 (H1),St. Thomas (TX) Celts,missed_shot,Corey Thompson Misses 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
15,St. Thomas (TX) Celts,H1,18:19 (H1),St. Thomas (TX) Celts,rebound_offensive,Corey Thompson Offensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
16,St. Thomas (TX) Celts,H1,18:18 (H1),St. Thomas (TX) Celts,turnover,Corey Thompson Turnover,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
17,St. Thomas (TX) Celts,H1,18:04 (H1),UW-Whitewater,made_shot,Collin Madson Makes 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
18,St. Thomas (TX) Celts,H1,18:04 (H1),UW-Whitewater,assist,Luke Bara Assists,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
19,St. Thomas (TX) Celts,H1,17:43 (H1),St. Thomas (TX) Celts,made_shot,Angel Johnson Makes 2PT Pull Up Jump Shot,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
20,St. Thomas (TX) Celts,H1,17:19 (H1),UW-Whitewater,made_shot,JR Lukenbill Makes 3PT Jump Shot,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
21,St. Thomas (TX) Celts,H1,17:19 (H1),UW-Whitewater,assist,Collin Madson Assists,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
22,St. Thomas (TX) Celts,H1,17:05 (H1),UW-Whitewater,foul,Luke Bara Commits Personal Foul,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
23,St. Thomas (TX) Celts,H1,16:55 (H1),St. Thomas (TX) Celts,made_shot,Angel Johnson Makes 2PT Driving Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
24,St. Thomas (TX) Celts,H1,16:37 (H1),UW-Whitewater,missed_shot,Luke Bara Misses 3PT Jump Shot,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
25,St. Thomas (TX) Celts,H1,16:34 (H1),St. Thomas (TX) Celts,rebound_defensive,Charles Gitonga Defensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
26,St. Thomas (TX) Celts,H1,16:17 (H1),St. Thomas (TX) Celts,missed_shot,Nicholas Buffalo Misses 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
27,St. Thomas (TX) Celts,H1,16:15 (H1),St. Thomas (TX) Celts,rebound_offensive,Nicholas Buffalo Offensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
28,St. Thomas (TX) Celts,H1,16:13 (H1),St. Thomas (TX) Celts,missed_shot,Nicholas Buffalo Misses 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
29,St. Thomas (TX) Celts,H1,16:11 (H1),UW-Whitewater,rebound_defensive,Brock Marino Defensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."

  ... 6,172 more row(s) of 6,202 (SHOW_ROWS = 30)

Lineup size check (every non-null value should be exactly 5 players):
 uww_lineup sizes: {5: 6202}
 opp_lineup sizes: {5: 6202}


### Classify each on-court opponent lineup using scouting-report tags

Adds `opp_lineup_summary`, describing the specific opponent lineup on the floor at any moment: role composition (Starter/Bench), position composition, and each player's most common notes/keys tags from `player_profiles`. No equivalent exists for `uww_lineup` -- UW-Whitewater isn't a scouted opponent, so there's no scouting-report data to classify our own lineups with.

In [95]:
# --- Classify each on-court OPPONENT 5-man unit using its players' scouting-report data -----------------------
# Code: parser_lib\40_classify_each_on_court_opponent_lineup.py  --  settings below, then the section runs.

run_section("40_classify_each_on_court_opponent_lineup")

               opponent  \
4355         Alma Scots
4453         Alma Scots
4393         Alma Scots
4376         Alma Scots
4341         Alma Scots
...                 ...
6181  UW-Oshkosh Titans
5380  UW-Oshkosh Titans
5357  UW-Oshkosh Titans
5789  UW-Oshkosh Titans
6190  UW-Oshkosh Titans

                                                                                     opp_lineup  \
4355            Donovan Collins, Elijah Sykes, Joss Bradley, Luciano Guerrazzi, Preston Malpass
4453            Donovan Collins, Josh Elliott, Joss Bradley, Korbin Heitzman, Luciano Guerrazzi
4393            Donovan Collins, Josh Elliott, Korbin Heitzman, Luciano Guerrazzi, Raine Rodich
4376            Donovan Collins, Josh Elliott, Joss Bradley, Luciano Guerrazzi, Preston Malpass
4341            Elijah Sykes, Joss Bradley, Korbin Heitzman, Luciano Guerrazzi, Preston Malpass
...                                                                                         ...
6181            Aiden Hawkinson, Brandon Beck, Carter Thomas, Joey LaChapell, Jonah Rindfleisch
5380             Aiden Hawkinson, Jonah Rindfleisch, Logan Rindfleisch, Matt Imig, Oskar Kangas
5357          Brandon Beck, Carter Thomas, Joey LaChapell, Michael Metcalf-Grassman, Nate Nazos
5789     Aiden Hawkinson, Jay Dalton, Jonah Rindfleisch, Michael Metcalf-Grassman, Oskar Kangas
6190  Aiden Hawkinson, Brandon Beck, Carter Thomas, Jonah Rindfleisch, Michael Metcalf-Grassman

                                                                                                                                                                                     opp_lineup_summary
4355                   4 Bench / 1 Starter | Pos: 3 Guard, 2 Forward/Post | Style: three_point_shooter x3, slasher_driver x2 | Defend: deny_catch_and_shoot x3, physical_discipline x1, post_defense x1
4453    3 Starter / 2 Bench | Pos: 3 Guard, 2 Forward/Post | Style: three_point_shooter x2, slasher_driver x2, post_scorer x1 | Defend: post_defense x2, deny_catch_and_shoot x1, transition_defense x1
4393              4 Starter / 1 Bench | Pos: 3 Guard, 2 Forward/Post | Style: slasher_driver x2, three_point_shooter x2, post_scorer x1 | Defend: post_defense x2, anticipate_move x1, keep_in_front x1
4376             3 Bench / 2 Starter | Pos: 3 Guard, 2 Forward/Post | Style: three_point_shooter x3, slasher_driver x1 | Defend: deny_catch_and_shoot x2, transition_defense x1, physical_discipline x1
4341   4 Bench / 1 Starter | Pos: 3 Forward/Post, 2 Guard | Style: slasher_driver x3, three_point_shooter x2, post_scorer x1 | Defend: post_defense x2, deny_catch_and_shoot x2, physical_discipline x1
...                                                                                                                                                                                                 ...
6181  3 Starter / 2 Bench | Pos: 3 Guard, 2 Forward/Post | Style: three_point_shooter x4, slasher_driver x3, rebounder x1 | Defend: deny_catch_and_shoot x3, transition_defense x1, box_out_priority x1
5380                                     5 Bench | Pos: 3 Guard, 2 Forward/Post | Style: three_point_shooter x4, slasher_driver x1, rebounder x1 | Defend: deny_catch_and_shoot x3, box_out_priority x1
5357                                 5 Starter | Pos: 4 Guard, 1 Forward/Post | Style: slasher_driver x4, three_point_shooter x4, playmaker x1 | Defend: deny_catch_and_shoot x3, transition_defense x1
5789              4 Bench / 1 Starter | Pos: 2 Guard, 2 Forward/Post, 1 Unknown | Style: three_point_shooter x2, slasher_driver x1, rebounder x1 | Defend: deny_catch_and_shoot x2, box_out_priority x1
6190                         3 Starter / 2 Bench | Pos: 3 Guard, 2 Forward/Post | Style: slasher_driver x3, three_point_shooter x3, rebounder x1 | Defend: deny_catch_and_shoot x3, box_out_priority x1

[232 rows x 3 columns]


### Attach video-tagging clip descriptions onto `pbp_events`

Same global order-preserving alignment used for the opponent's prior games earlier, applied here to UWW's own `pbp_events` against each `_video` export. The next cell just displays the result.

In [97]:
# --- Attach video-tagging clip descriptions ("*_video.mhtml") onto pbp_events ---------------------------------
# Code: parser_lib\41_attach_video_tagging_clip_descriptions_2.py  --  settings below, then the section runs.
ATTEMPTED_EVENT_TYPES = {"made_shot", "missed_shot", "turnover", "foul"} | FREE_THROW_EVENT_TYPES

run_section("41_attach_video_tagging_clip_descriptions_2")

Skipping 29 video-tagging file(s) dated on/after reference_date (2026-1-7).
Skipping 59 video file(s) for games UWW didn't play in (handled by the opponent prior-games cell).
Found 12 video-tagging file(s):
 - 11_14_25 UW-Whitewater @ St. Thomas (TX) Celts_video.html
 - 11_15_25 UW-Whitewater @ Eureka Red Devils_video.html
 - 11_19_25 Aurora Spartans @ UW-Whitewater_video.html
 - 11_25_25 Simpson Storm @ UW-Whitewater_video.html
 - 11_7_25 UW-Whitewater @ Ripon Red Hawks_video.html
 - 12_10_25 UW-Whitewater @ Lawrence Vikings_video.html
 - 12_13_25 Carroll (WI) Pioneers @ UW-Whitewater_video.html
 - 12_19_25 UW-Whitewater @ Hope Flying Dutchmen_video.html
 - 12_20_25 UW-Whitewater @ Alma Scots_video.html
 - 12_2_25 Elmhurst Bluejays @ UW-Whitewater_video.html
 - 12_30_25 UW-Whitewater @ Coe Kohawks_video.html
 - 1_3_26 UW-Oshkosh Titans @ UW-Whitewater_video.html
  St. Thomas (TX) Celts: matched 195/222 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 53/55 are free throws, and 28/41 are fouls). video log had 213 taggable sub-events of these types.
  Eureka Red Devils: matched 208/223 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 38/38 are free throws, and 25/31 are fouls). video log had 220 taggable sub-events of these types.
  Aurora Spartans: matched 213/242 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 55/63 are free throws, and 41/51 are fouls). video log had 224 taggable sub-events of these types.
  Simpson Storm: matched 200/220 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 34/34 are free throws, and 20/32 are fouls). video log had 210 taggable sub-events of these types.
  Ripon Red Hawks: matched 200/217 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 49/49 are free throws, and 30/40 are fouls). video log had 208 taggable sub-events of these types.
  Lawrence Vikings: matched 208/227 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 46/46 are free throws, and 30/41 are fouls). video log had 213 taggable sub-events of these types.
  Carroll (WI) Pioneers: matched 214/235 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 45/45 are free throws, and 34/45 are fouls). video log had 220 taggable sub-events of these types.
  Hope Flying Dutchmen: matched 239/258 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 67/67 are free throws, and 40/50 are fouls). video log had 249 taggable sub-events of these types.
  Alma Scots: matched 194/214 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 34/34 are free throws, and 19/32 are fouls). video log had 203 taggable sub-events of these types.
  Elmhurst Bluejays: matched 190/202 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 35/37 are free throws, and 25/34 are fouls). video log had 198 taggable sub-events of these types.
  Coe Kohawks: matched 195/213 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 36/36 are free throws, and 29/35 are fouls). video log had 199 taggable sub-events of these types.
  UW-Oshkosh Titans: matched 234/252 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 61/61 are free throws, and 40/47 are fouls). video log had 241 taggable sub-events of these types.
                 opponent  event_order                   team  \
0   St. Thomas (TX) Celts            0                   None
1   St. Thomas (TX) Celts            1  St. Thomas (TX) Celts
2   St. Thomas (TX) Celts            2          UW-Whitewater
3   St. Thomas (TX) Celts            3  St. Thomas (TX) Celts
4   St. Thomas (TX) Celts            4          UW-Whitewater
5   St. Thomas (TX) Celts            5  St. Thomas (TX) Celts
6   St. Thomas (TX) Celts            6  St. Thomas (TX) Celts
7   St. Thomas (TX) Celts            7          UW-Whitewater
8   St. Thomas (TX) Celts            8          UW-Whitewater
9   St. Thomas (TX) Celts            9  St. Thomas (TX) Celts
10  St. Thomas (TX) Celts           10  St. Thomas (TX) Celts
11  St. Thomas (TX) Celts           11  St. Thomas (TX) Celts
12  St. Thomas (TX) Celts           12          UW-Whitewater
13  St. Thomas (TX) Celts           13  St. Thomas (TX) Celts
14  St. Thomas (TX) Celts           14  St. Thomas (TX) Celts
15  St. Thomas (TX) Celts           15  St. Thomas (TX) Celts
16  St. Thomas (TX) Celts           16  St. Thomas (TX) Celts
17  St. Thomas (TX) Celts           17          UW-Whitewater
18  St. Thomas (TX) Celts           18          UW-Whitewater
19  St. Thomas (TX) Celts           19  St. Thomas (TX) Celts

              player         event_type  \
0                NaN      period_marker
1    Charles Gitonga      jump_ball_won
2       Brock Marino     jump_ball_lost
3     Corey Thompson          made_shot
4       Isaac Verges           turnover
5      Angel Johnson              steal
6     Nathan Kongolo        missed_shot
7      Collin Madson  rebound_defensive
8       Isaac Verges           turnover
9     Nathan Kongolo              steal
10     Angel Johnson          made_shot
11    Nathan Kongolo             assist
12      Isaac Verges        missed_shot
13  Nicholas Buffalo  rebound_defensive
14    Corey Thompson        missed_shot
15    Corey Thompson  rebound_offensive
16    Corey Thompson           turnover
17     Collin Madson          made_shot
18         Luke Bara             assist
19     Angel Johnson          made_shot

                                         raw_text  video_clip_number  \
0                                  Start 1st Half                NaN
1                  Charles Gitonga Wins Jump Ball                NaN
2                    Brock Marino Loses Jump Ball                NaN
3   Corey Thompson Makes 2PT Turnaround Jump Shot                1.0
4               Isaac Verges Turnover (Lost Ball)                2.0
5                            Angel Johnson Steals                NaN
6             Nathan Kongolo Misses 3PT Jump Shot                3.0
7                 Collin Madson Defensive Rebound                NaN
8                Isaac Verges Turnover (Bad Pass)                4.0
9                           Nathan Kongolo Steals                NaN
10                  Angel Johnson Makes 2PT Layup                5.0
11                         Nathan Kongolo Assists                NaN
12                  Isaac Verges Misses 2PT Layup                6.0
13             Nicholas Buffalo Defensive Rebound                NaN
14                Corey Thompson Misses 2PT Layup                7.0
15               Corey Thompson Offensive Rebound                NaN
16                        Corey Thompson Turnover                8.0
17                  Collin Madson Makes 2PT Layup                9.0
18                              Luke Bara Assists                NaN
19      Angel Johnson Makes 2PT Pull Up Jump Shot               10.0

   video_result    video_player  \
0           NaN             NaN
1           NaN             NaN
2           NaN             NaN
3    Make 2 Pts  Corey Thompson
4      Turnover    Isaac Verges
5           NaN             NaN
6    Miss 3 Pts  Nathan Kongolo
7           NaN             NaN
8      Turnover    Isaac Verges
9           NaN             NaN
10   Make 2 Pts   Angel Johnson
11          NaN             NaN
12   Miss 2 Pts    Isaac Verges
13          NaN             NaN
14   Miss 2 Pts  Corey Thompson
15          NaN             NaN
16     Turnover  Corey Thompson
17   Make 2 Pts   Collin Madson
18          NaN             NaN
19   Make 2 Pts   Angel Johnson

                                                                                                           video_description
0                                                                                                                        NaN
1                                                                                                                        NaN
2                                                                                                                        NaN
3                                                       1 Corey Thompson > ISO > Top > Drives Right > To Basket > Make 2 Pts
4                                                                                   0 Isaac Verges > No Play Type > Turnover
5                                                                                                                        NaN
6                            0 Nathan Kongolo > Transition > Left Wing > No Dribble Jumper > Guarded > Long/3pt > Miss 3 Pts
7                                                                                                                        NaN
8                                                                                   0 Isaac Verges > No Play Type > Turnover
9                                                                                                                        NaN
10                                                     10 Angel Johnson > Transition > First Middle > To Basket > Make 2 Pts
11                                                                                                                       NaN
12                                                           0 Isaac Verges > Spot-Up > Drives Left > To Basket > Miss 2 Pts
13                                                                                                                       NaN
14                    1 Corey Thompson > P&R Ball Handler > Left P&R > Baseline > Go Away from Pick > To Basket > Miss 2 Pts
15                                                                                                                       NaN
16                                                                    1 Corey Thompson > Offensive Rebound > Long > Turnover
17                                                                              15 Collin Madson > Cut > Basket > Make 2 Pts
18                                                                                                                       NaN
19  10 Angel Johnson > P&R Ball Handler > Right P&R > Side > Dribble Off Pick > Dribble Jumper > Short to < 17' > Make 2 Pts

220 still-unmatched row(s) among attempted event types across 12 game(s) with a video-tagging file (15 bare team-level turnover(s) with no player excluded -- never matchable):
  St. Thomas (TX) Celts: 27 unmatched
  Eureka Red Devils: 15 unmatched
  Aurora Spartans: 28 unmatched
  Simpson Storm: 20 unmatched
  Ripon Red Hawks: 16 unmatched
  Lawrence Vikings: 17 unmatched
  Carroll (WI) Pioneers: 20 unmatched
  Hope Flying Dutchmen: 19 unmatched
  Alma Scots: 18 unmatched
  Elmhurst Bluejays: 12 unmatched
  Coe Kohawks: 15 unmatched
  UW-Oshkosh Titans: 13 unmatched
               opponent  event_order period time_remaining               team  \
4051         Alma Scots           12     H1     18:44 (H1)         Alma Scots
4072         Alma Scots           33     H1     16:25 (H1)         Alma Scots
4162         Alma Scots          123     H1     08:22 (H1)      UW-Whitewater
4165         Alma Scots          126     H1     08:04 (H1)      UW-Whitewater
4225         Alma Scots          186     H1     03:54 (H1)      UW-Whitewater
...                 ...          ...    ...            ...                ...
5901  UW-Oshkosh Titans          544     H2     12:28 (H2)      UW-Whitewater
5903  UW-Oshkosh Titans          546     H2     12:27 (H2)      UW-Whitewater
5929  UW-Oshkosh Titans          572     H2     11:34 (H2)      UW-Whitewater
5930  UW-Oshkosh Titans          573     H2     11:25 (H2)  UW-Oshkosh Titans
6098  UW-Oshkosh Titans          741     H2     03:35 (H2)  UW-Oshkosh Titans

                        player   event_type  \
4051           Korbin Heitzman         foul
4072           Korbin Heitzman  missed_shot
4162                Jake Quast         foul
4165              Isaac Verges         foul
4225             Collin Madson    made_shot
...                        ...          ...
5901             Richie Warren  missed_shot
5903                Jake Quast    made_shot
5929             Richie Warren    made_shot
5930              Oskar Kangas  missed_shot
6098  Michael Metcalf-Grassman         foul

                                            raw_text
4051           Korbin Heitzman Commits Personal Foul
4072                Korbin Heitzman Misses 2PT Layup
4162                Jake Quast Commits Personal Foul
4165             Isaac Verges Commits Offensive Foul
4225                   Collin Madson Makes 2PT Layup
...                                              ...
5901                        Richie Warren Misses 2PT
5903                            Jake Quast Makes 2PT
5929                         Richie Warren Makes 2PT
5930               Oskar Kangas Misses 3PT Jump Shot
6098  Michael Metcalf-Grassman Commits Personal Foul

[220 rows x 8 columns]
No unmatched clips found in the video-tagging files.

Timing: live scraping 0s, parsing + aligning 1s.

### Offensive roles: every player in one of BBall Index's 12 offensive roles

Guards/wings: Primary Ball Handler, Secondary Ball Handler, Shot Creator, Slasher, Athletic Finisher, Off Screen Shooter, Movement Shooter, Stationary Shooter. Bigs: Versatile Big, Post Scorer, Stretch Big, Roll & Cut Big ([definitions](https://www.bball-index.com/offensive-archetypes/)). From Synergy play types where the video descriptions exist, otherwise the play-by-play, otherwise the roster position. Cut-offs below are Division III starting points -- adjust them to taste.

In [99]:
# --- Offensive roles: every player (UWW and opponents) in one of BBall Index's 12 offensive roles ----------------------
# Code: parser_lib\41b_offensive_roles.py  --  settings below, then the section runs.
RUN_OFFENSIVE_ROLES = True
ROLE_MIN_POSS = 20             # fewer scoring possessions than this -> the role is marked "low sample"
ROLE_MIN_VIDEO_POSS = 8        # Synergy play types are used once a player has this many described possessions
# bigs: big-man plays = post-ups + rolls + cuts + putbacks
ROLE_BIG_SHARE = 0.40          # a big if big-man plays are at least this share ...
ROLE_BIG_HEIGHT_IN = 79        # ... or a forward (no G) at least this tall (6'7") ...
ROLE_BIG_SHARE_TALL = 0.25     # ... with at least this share (a listed C is always a big)
ROLE_GUARD_BIG_SHARE = 0.60    # a listed guard (G, G/F) is a big only with this share of big-man plays ...
ROLE_GUARD_BIG_HEIGHT_IN = 78  # ... and at least this tall (6'6")
ROLE_POST_SHARE = 0.15         # posts up this much -> Post Scorer / Versatile Big
ROLE_BIG_3PA_RATE = 0.25       # 3s are this share of his shots -> Stretch Big / Versatile Big
# guards / wings (checked in this order)
ROLE_ISO_SHARE = 0.20          # Shot Creator
ROLE_ONBALL_MIN = 0.35         # ball handler: PnR ball handler + isolation + transition ball handling
ROLE_PRIMARY_TEAM_SHARE = 0.25 # ... Primary if he runs at least this share of his team's on-ball possessions
ROLE_DRIVE_SHARE = 0.35        # Slasher (and 3s under ROLE_SHOOTER_3PA_RATE)
ROLE_FINISHER_SHARE = 0.30     # Athletic Finisher: cuts + putbacks + transition finishing ...
ROLE_FINISHER_MAX_3PA = 0.35   # ... and 3s under this share
ROLE_OFFSCREEN_SHARE = 0.20    # Off Screen Shooter: off screen + handoff
ROLE_SHOOTER_3PA_RATE = 0.40   # shooters
ROLE_MOVING_SHARE = 0.35       # Movement Shooter if this share of his 3s are off the dribble / transition / relocating
ROLE_ASSIST_BALLHANDLER = 0.25 # play-by-play only: assists per possession that mark a ball handler

run_section("41b_offensive_roles")

Offensive roles: 456 player(s) -- 110 from Synergy play types, 187 from the play-by-play only, 159 from roster position only (274 marked low sample)
  roles: Stationary Shooter 119; Secondary Ball Handler 104; Roll & Cut Big 80; Slasher 49; Athletic Finisher 33; Primary Ball Handler 28; Off Screen Shooter 13; Post Scorer 12; Movement Shooter 10; Versatile Big 3; Shot Creator 3; Stretch Big 2
  Alma Scots: Korbin Heitzman = Slasher; Donovan Collins = Off Screen Shooter; Elijah Sykes = Primary Ball Handler; Josh Elliott = Off Screen Shooter; Luciano Guerrazzi = Stationary Shooter; Raine Rodich = Slasher; Preston Malpass = Stationary Shooter; Logan St. Martin = Stretch Big; Joss Bradley = Slasher
  Aurora Spartans: Mekhi Doby = Primary Ball Handler; Juan Madrigal = Off Screen Shooter; Cullen Rauls = Primary Ball Handler; Devon Richardson = Post Scorer; Jeffery Hillmer = Athletic Finisher; Zerrick Johnson = Slasher; Larry Carthan = Roll & Cut Big; Bryden Gryzmala = Slasher; Isaiah Thompson = Stationary Shooter
  Bethany Lutheran Vikings: Elliot Whitney = Primary Ball Handler; Jack Brockmann = Slasher; Max Briggs = Stationary Shooter; Will Walter = Movement Shooter; Rysley Borman = Stationary Shooter; Cooper Mensink = Stationary Shooter; Amory Peterson = Athletic Finisher; Blue Smaller = Slasher; Cole Johnson = Roll & Cut Big
  Carroll (WI) Pioneers: Lamar Smith = Slasher; Michael McNabb = Slasher; Dennis Estepp = Movement Shooter; Peyton McKenna = Stationary Shooter; Jacob Naber = Slasher; Cai Joseph = Athletic Finisher; Evan Bland = Slasher; Jimmy Tarjan = Slasher; Greg Smith = Slasher
  Coe Kohawks: Deuce Walters = Primary Ball Handler; Cooper Nailor = Off Screen Shooter; Jackson Bowman = Roll & Cut Big; Kanyon Bryte = Roll & Cut Big; Ryan Dolphin = Movement Shooter; C. Reece Breitenbach = Stationary Shooter; Jackson Newell = Roll & Cut Big; Austin Beeson = Stationary Shooter; Jay Akin = Athletic Finisher
  Edgewood Eagles: Matt Kirk = Primary Ball Handler; Trent Tousana = Primary Ball Handler; Hunter Hardyman = Stationary Shooter; Payton Bowser = Off Screen Shooter; Kaleb Walter = Athletic Finisher; Isaiah Hubanks = Stationary Shooter; Jonah Anderson = Roll & Cut Big; AC Strok = Stationary Shooter; Logan Steffensmeier = Slasher
  Elmhurst Bluejays: Dominic Trelenberg = Stretch Big; Sebastian Blachut = Primary Ball Handler; Vinnie Adjahoungbeta = Stationary Shooter; Aidyn Boone = Stationary Shooter; EJ Marshall = Stationary Shooter; Luke Smith = Stationary Shooter; Talen Pearson = Stationary Shooter; Jack Cherry = Slasher; Jeffrey Williams = Stationary Shooter
  Eureka Red Devils: Jaxson Provost = Movement Shooter; Jacob Gonzalez = Primary Ball Handler; Ben Carter = Stationary Shooter; Micah Bruer = Primary Ball Handler; Amare Brokemond = Athletic Finisher; Jonah Lauff = Stationary Shooter; Andrew Coker = Athletic Finisher; Colin DeLaere = Stationary Shooter; Max Richardson = Stationary Shooter
  Hardin-Simmons Cowboys: Chris Bryant = Roll & Cut Big; Matthew Alexander = Primary Ball Handler; Asher Fleming = Post Scorer; Jamar Ingram = Slasher; DJ Jones = Stationary Shooter; Gavin Davis = Stationary Shooter; Tyler Williams = Slasher; Andrew Messenger = Slasher; Trevion Howell = Stationary Shooter
  Hope Flying Dutchmen: Parker Hovey = Stationary Shooter; Brendan Cargill = Movement Shooter; Marcus Wourman = Primary Ball Handler; Orion Yant = Slasher; Brady Miller = Athletic Finisher; Justice Mims = Athletic Finisher; Avery Sanchez = Athletic Finisher; Charles Howell = Roll & Cut Big; Jared Ryg = Slasher
  Lakeland Muskies: Asanjai Hunter = Primary Ball Handler; Jaxson Dillon = Off Screen Shooter; Gage Cornell = Stationary Shooter; Peyton Mrotek = Stationary Shooter; Delon Zollicoffer-White = Athletic Finisher; Parker Braun = Stationary Shooter; Adison Mittelstadt = Stationary Shooter; Max Justic = Stationary Shooter; Emmitt Konieczny = Stationary Shooter
  Lawrence Vikings: CJ Campbell = Movement Shooter; Casey Schoenecker = Post Scorer; Hogan Demovsky = Stationary Shooter; Nicholas Gouriotis = Versatile Big; Jackson Weber = Athletic Finisher; Nathan Valentine = Stationary Shooter; Caleb Nash = Athletic Finisher; Nolan Koch = Roll & Cut Big; Cameron Nash = Stationary Shooter
  MSOE Raiders: Chase Cummings = Stationary Shooter; Jonathan Burroughs = Primary Ball Handler; Joey Jendusa = Slasher; Matus Dopirak = Slasher; Carson Cordelli = Athletic Finisher; Quinn Rosenberg = Stationary Shooter; Isaac Wit = Stationary Shooter; CJ Valente = Post Scorer; Daniel Franklin IV = Stationary Shooter
  Millikin Big Blue: Lane Thomann = Off Screen Shooter; Nate Straughter = Off Screen Shooter; Ian Winkler = Primary Ball Handler; McGrady Noyes = Athletic Finisher; Caden Nichols = Stationary Shooter; Tionne Spates = Roll & Cut Big; Chris Ketchum = Roll & Cut Big; Kobe Anderson = Slasher; Eli Stipp = Roll & Cut Big
  North Central (MN) Rams: Carrington McNeal = Stationary Shooter; Carmello McNeal = Slasher; Jaquan Adams = Off Screen Shooter; Jax Effertz = Stationary Shooter; Remy Wedgeworth-Brown = Slasher; Jayden Livingston = Stationary Shooter; Jamisen Young = Athletic Finisher; Elijah Smith = Roll & Cut Big; Josh Hoffman = Stationary Shooter
  North Park Vikings: Kolden Vanlandingham = Primary Ball Handler; William Bates = Stationary Shooter; Jalen Houston = Off Screen Shooter; Lazario Cornish = Athletic Finisher; Julian Campbell = Versatile Big; Mike Vuckovic = Stationary Shooter; Jerome Smith, Jr. = Stationary Shooter; Marquis Vance = Stationary Shooter; Harrison Long = Stationary Shooter
  Northern Michigan Wildcats EXH: Aidan Bellisle = Stationary Shooter; Isaiah Allen = Stationary Shooter; Brooks Hinson = Stationary Shooter; Keller Hanson = Stationary Shooter; Dylan Kuehl = Stationary Shooter; Trevor Polite = Stationary Shooter; Cal Klesmit = Athletic Finisher; Ross Robertson = Athletic Finisher; Sam Privet = Athletic Finisher
  Olivet Comets: Nathan Richardson = Primary Ball Handler; Sean Shenker = Primary Ball Handler; Conner Schipper = Post Scorer; Porter Kretschman = Slasher; Lee Hardy = Athletic Finisher; Mike Okello = Athletic Finisher; Evan Honnen = Stationary Shooter; Alex Genuise = Stationary Shooter
  Ripon Red Hawks: Seth Bunders = Primary Ball Handler; Kolby Williams = Post Scorer; Michael Asman = Stationary Shooter; CJ Brown = Stationary Shooter; Jack Field = Stationary Shooter; Jarton Davis = Stationary Shooter; Sam Leoni = Stationary Shooter; Anton Kilde = Slasher; Jake Thomsen = Stationary Shooter
  Simpson Storm: Levi Gurwell = Primary Ball Handler; Cam Henderson = Primary Ball Handler; Bo Huston = Primary Ball Handler; Jachin Mertes = Athletic Finisher; Seth Gipple = Stationary Shooter; Marcus Haupert = Post Scorer; Spencer Holley = Stationary Shooter; Colton Rasmussen = Stationary Shooter; Brogan Fuller = Athletic Finisher
  St. Olaf Oles: Kobe Kirk = Primary Ball Handler; Rex Lamb = Stationary Shooter; AJ Uhl = Primary Ball Handler; Liam Madigan = Off Screen Shooter; Liam Roche = Post Scorer; Luther Tostrud = Stationary Shooter; Chris Willis = Stationary Shooter; Cooper Carlson = Athletic Finisher; Jaxon Strinmoen = Stationary Shooter
  St. Thomas (TX) Celts: Angel Johnson = Shot Creator; Corey Thompson = Shot Creator; Nathan Kongolo = Shot Creator; Garrett Rodgers = Post Scorer; Nicholas Buffalo = Roll & Cut Big; Jaden Ross = Slasher; Reyce Allen = Athletic Finisher; Charles Gitonga = Stationary Shooter; Omar Gayle = Slasher
  Trinity (TX) Tigers: Dean Balo = Primary Ball Handler; Jackson Lawson = Stationary Shooter; Trent Medearis = Primary Ball Handler; Elias DeMent = Slasher; Will Bronson = Roll & Cut Big; Ben Estis = Stationary Shooter; Gabe Parr = Roll & Cut Big; Carter Ruck = Stationary Shooter; Zach Fenn = Stationary Shooter
  UW-Eau Claire Blugolds: Kenji Scales = Stationary Shooter; Carter Lichtsinn = Stationary Shooter; Andre Renta = Primary Ball Handler; Xavier Lewis = Athletic Finisher; Luke Reder = Roll & Cut Big; Will Boser = Stationary Shooter; Roan Demovsky = Roll & Cut Big; Tyler Haney = Stationary Shooter
  UW-Oshkosh Titans: Michael Metcalf-Grassman = Slasher; Brandon Beck = Stationary Shooter; Logan Rindfleisch = Slasher; Carter Thomas = Stationary Shooter; Joey LaChapell = Slasher; Matt Imig = Stationary Shooter; Oskar Kangas = Stationary Shooter; Aiden Hawkinson = Stationary Shooter; Nate Nazos = Stationary Shooter
  UW-Stevens Point Pointers: Seth Miron = Stationary Shooter; Josiah Butler = Movement Shooter; Cal Krohn = Post Scorer; Logan Baumgartner = Stationary Shooter; Carter Combs = Stationary Shooter; Isaiah Moore = Stationary Shooter; Max Raimer = Movement Shooter; Josh Bocher = Roll & Cut Big; Grant Manz = Roll & Cut Big
  UW-Whitewater: Collin Madson = Primary Ball Handler; Richie Warren = Roll & Cut Big; Luke Bara = Secondary Ball Handler; Brock Marino = Post Scorer; Jake Quast = Slasher; Isaac Verges = Secondary Ball Handler; Darius Chestnut = Stationary Shooter; JR Lukenbill = Stationary Shooter; Kelton McEwen = Off Screen Shooter

In [100]:
print(pbp_events[['period','time_remaining','event_order','uww_score','opp_score','team','player','event_type','raw_text','shot_type','shot_desc','video_clip_number','video_description','video_player','video_result']])

     period time_remaining  event_order  uww_score  opp_score  \
0      None           None            0        NaN        NaN
1        H1     19:58 (H1)            1        0.0        0.0
2        H1     19:58 (H1)            2        0.0        0.0
3        H1     19:34 (H1)            3        0.0        2.0
4        H1     19:22 (H1)            4        0.0        2.0
...     ...            ...          ...        ...        ...
6197     H2     00:19 (H2)          840       78.0       90.0
6198     H2     00:19 (H2)          841       78.0       90.0
6199     H2     00:10 (H2)          842       78.0       90.0
6200     H2     00:08 (H2)          843       78.0       90.0
6201     H2           None          844        NaN        NaN

                       team                    player         event_type  \
0                      None                       NaN      period_marker
1     St. Thomas (TX) Celts           Charles Gitonga      jump_ball_won
2             UW-Whitewater              Brock Marino     jump_ball_lost
3     St. Thomas (TX) Celts            Corey Thompson          made_shot
4             UW-Whitewater              Isaac Verges           turnover
...                     ...                       ...                ...
6197      UW-Oshkosh Titans  Michael Metcalf-Grassman            sub_out
6198      UW-Oshkosh Titans                Nate Nazos             sub_in
6199          UW-Whitewater           Darius Chestnut        missed_shot
6200      UW-Oshkosh Titans             Carter Thomas  rebound_defensive
6201                   None                       NaN      period_marker

                                           raw_text shot_type  \
0                                    Start 1st Half       NaN
1                    Charles Gitonga Wins Jump Ball       NaN
2                      Brock Marino Loses Jump Ball       NaN
3     Corey Thompson Makes 2PT Turnaround Jump Shot         2
4                 Isaac Verges Turnover (Lost Ball)       NaN
...                                             ...       ...
6197              Michael Metcalf-Grassman Subs Out       NaN
6198                             Nate Nazos Subs In       NaN
6199           Darius Chestnut Misses 3PT Jump Shot         3
6200                Carter Thomas Defensive Rebound       NaN
6201                                   End 2nd Half       NaN

                 shot_desc  video_clip_number  \
0                      NaN                NaN
1                      NaN                NaN
2                      NaN                NaN
3     Turnaround Jump Shot                1.0
4                      NaN                2.0
...                    ...                ...
6197                   NaN                NaN
6198                   NaN                NaN
6199             Jump Shot              256.0
6200                   NaN                NaN
6201                   NaN                NaN

                                                                                                      video_description  \
0                                                                                                                   NaN
1                                                                                                                   NaN
2                                                                                                                   NaN
3                                                  1 Corey Thompson > ISO > Top > Drives Right > To Basket > Make 2 Pts
4                                                                              0 Isaac Verges > No Play Type > Turnover
...                                                                                                                 ...
6197                                                                                                                NaN
6198                                                                                                                NaN
6199  10 Darius Chestnut > Off Screen > To Shooter's Left > Flare > No Dribble Jumper > Guarded > Long/3pt > Miss 3 Pts
6200                                                                                                                NaN
6201                                                                                                                NaN

         video_player video_result
0                 NaN          NaN
1                 NaN          NaN
2                 NaN          NaN
3      Corey Thompson   Make 2 Pts
4        Isaac Verges     Turnover
...               ...          ...
6197              NaN          NaN
6198              NaN          NaN
6199  Darius Chestnut   Miss 3 Pts
6200              NaN          NaN
6201              NaN          NaN

[6202 rows x 15 columns]


### Reconstruct and validate a per-game box score from play-by-play

Aggregates player-level PBP events into a real box score, then sanity-checks each game's reconstructed final score against the schedule's own recorded result.

In [102]:
# --- Reconstruct a real single-game box score from the play-by-play, and sanity-check it against the schedule's
# Code: parser_lib\42_reconstruct_and_validate_per_game_box.py  --  settings below, then the section runs.
# --- Reconstruct a real single-game box score from the play-by-play, and sanity-check it against the schedule's
# final scores ------------------------------------------------------------------------------------------------
TEAM_LEVEL_EVENT_TYPES_BOX = {"team_deadball_rebound_offensive", "team_deadball_rebound_defensive", "timeout"}

run_section("42_reconstruct_and_validate_per_game_box")

Added 10 synthetic TEAM row(s) for 14 bare (unattributed) team-level turnover(s) that would otherwise be missing from the box score entirely.
Validating PBP-reconstructed final scores against the schedule:

  St. Thomas (TX) Celts 2025-11-14: PBP 73-81 vs. schedule 73.0-81.0 [OK]
    UW-Whitewater starters: Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
    St. Thomas (TX) Celts starters: Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Nicholas Buffalo
  Eureka Red Devils 2025-11-15: PBP 116-73 vs. schedule 116.0-73.0 [OK]
    UW-Whitewater starters: Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
    Eureka Red Devils starters: Andrew Coker, Ben Carter, Colin DeLaere, Jaxson Provost, Micah Bruer
  Aurora Spartans 2025-11-19: PBP 82-73 vs. schedule 82.0-73.0 [OK]
    UW-Whitewater starters: Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
    Aurora Spartans starters: Cullen Rauls, Devon Richardson, Jeffery Hillmer, Juan Madrigal, Mekhi Doby
  Simpson Storm 2025-11-25: PBP 100-78 vs. schedule 100.0-78.0 [OK]
    UW-Whitewater starters: Collin Madson, Isaac Verges, Luke Bara, Rashad Rogers, Richie Warren
    Simpson Storm starters: Cam Henderson, Colton Rasmussen, Levi Gurwell, Marcus Haupert, Spencer Holley
  Ripon Red Hawks 2025-11-07: PBP 76-58 vs. schedule 76.0-58.0 [OK]
    UW-Whitewater starters: Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
    Ripon Red Hawks starters: CJ Brown, Kolby Williams, Michael Asman, Sam Leoni, Seth Bunders
  Lawrence Vikings 2025-12-10: PBP 88-58 vs. schedule 88.0-58.0 [OK]
    UW-Whitewater starters: Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren
    Lawrence Vikings starters: CJ Campbell, Casey Schoenecker, Hogan Demovsky, Nathan Valentine, Nicholas Gouriotis
  Carroll (WI) Pioneers 2025-12-13: PBP 64-60 vs. schedule 64.0-60.0 [OK]
    UW-Whitewater starters: Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren
    Carroll (WI) Pioneers starters: Evan Bland, Jacob Naber, Lamar Smith, Michael McNabb, Peyton McKenna
  Hope Flying Dutchmen 2025-12-19: PBP 95-92 vs. schedule 95.0-92.0 [OK]
    UW-Whitewater starters: Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren
    Hope Flying Dutchmen starters: Brendan Cargill, Justice Mims, Marcus Wourman, Orion Yant, Parker Hovey
  Alma Scots 2025-12-20: PBP 90-61 vs. schedule 90.0-61.0 [OK]
    UW-Whitewater starters: Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren
    Alma Scots starters: Donovan Collins, Josh Elliott, Korbin Heitzman, Logan St. Martin, Raine Rodich
  Elmhurst Bluejays 2025-12-02: PBP 88-72 vs. schedule 88.0-72.0 [OK]
    UW-Whitewater starters: Collin Madson, Isaac Verges, Luke Bara, Rashad Rogers, Richie Warren
    Elmhurst Bluejays starters: Aidyn Boone, Dominic Trelenberg, Luke Smith, Sebastian Blachut, Vinnie Adjahoungbeta
  Coe Kohawks 2025-12-30: PBP 73-86 vs. schedule 73.0-86.0 [OK]
    UW-Whitewater starters: Brock Marino, Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren
    Coe Kohawks starters: C. Reece Breitenbach, Cooper Nailor, Deuce Walters, Jackson Bowman, Kanyon Bryte
  UW-Oshkosh Titans 2026-01-03: PBP 78-90 vs. schedule 78.0-90.0 [OK]
    UW-Whitewater starters: Brock Marino, Collin Madson, JR Lukenbill, Luke Bara, Richie Warren
    UW-Oshkosh Titans starters: Brandon Beck, Carter Thomas, Joey LaChapell, Michael Metcalf-Grassman, Nate Nazos

12 game(s) reconcile exactly, 0 do not.

      opponent   game_date           team                  player  started  PTS  FGM  FGA  FG3M  FG3A  FTM  FTA  OREB  DREB  REB  AST  STL  BLK  TO  PF    FG%    3P%    FT%
0   Alma Scots  2025-12-20     Alma Scots         Donovan Collins     True   17    5   10     5     9    2    3     0     0    0    1    0    0   0   0   50.0   55.6   66.7
16  Alma Scots  2025-12-20  UW-Whitewater         Joey Berezowitz    False   16    6    8     4     5    0    0     2     0    2    0    2    0   0   0   75.0   80.0    NaN
4   Alma Scots  2025-12-20     Alma Scots         Korbin Heitzman     True   14    4   10     0     1    6    8     5    11   16    1    0    1   6   4   40.0    0.0   75.0
11  Alma Scots  2025-12-20  UW-Whitewater           Collin Madson     True   13    4    7     0     0    5    6     1     5    6    3    2    0   0   2   57.1    NaN   83.3
15  Alma Scots  2025-12-20  UW-Whitewater              Jake Quast    False   11    5    7     1     2    0    1     0     3    3    0    3    0   2   3   71.4   50.0    0.0
12  Alma Scots  2025-12-20  UW-Whitewater         Darius Chestnut    False   10    4    4     2     2    0    0     0     0    0    0    0    0   0   2  100.0  100.0    NaN
2   Alma Scots  2025-12-20     Alma Scots            Josh Elliott     True    9    3    7     2     6    1    1     0     3    3    0    1    0   3   1   42.9   33.3  100.0
13  Alma Scots  2025-12-20  UW-Whitewater            Isaac Verges     True    9    4    7     1     2    0    0     0     2    2    1    0    0   1   3   57.1   50.0    NaN
23  Alma Scots  2025-12-20  UW-Whitewater  Tyshawn Teague-Johnson    False    9    4    7     1     1    0    1     1     2    3    2    0    0   2   1   57.1  100.0    0.0
1   Alma Scots  2025-12-20     Alma Scots            Elijah Sykes    False    7    3    9     1     4    0    0     0     0    0    2    1    0   1   0   33.3   25.0    NaN
10  Alma Scots  2025-12-20  UW-Whitewater            Brock Marino     True    7    1    6     0     0    5    6     1     1    2    1    4    0   1   3   16.7    NaN   83.3
6   Alma Scots  2025-12-20     Alma Scots       Luciano Guerrazzi    False    5    2    2     1     1    0    0     1     1    2    1    1    1   5   1  100.0  100.0    NaN
21  Alma Scots  2025-12-20  UW-Whitewater           Richie Warren     True    5    1    6     0     1    3    3     2     2    4    2    3    1   1   2   16.7    0.0  100.0
3   Alma Scots  2025-12-20     Alma Scots            Joss Bradley    False    3    0    2     0     0    3    4     1     1    2    4    0    1   0   2    0.0    NaN   75.0
9   Alma Scots  2025-12-20  UW-Whitewater         Agape Keyes Jr.    False    3    1    1     1     1    0    0     0     0    0    0    1    0   0   1  100.0  100.0    NaN

  ... 306 more row(s) of 321 (SHOW_ROWS = 15)

Found 0 official box-score file(s) to cross-validate against:

Validating PBP-reconstructed per-player box score against the official box-score file, where available:


### Diagnostic: which played/scouted games are missing a box score, and why

Cross-references every game in `uww_team_schedule` (UWW's own scouted + played games -- the set the
Streamlit app expects a box score for) against `pbp_box_score`, and prints a specific reason for any gap:
no local `_pbp` file was found for that game, a live-scrape wasn't attempted (no FastScout credentials),
or the game's `opponent` value in `pbp_events` doesn't match how it's spelled in the schedule (the PBP
builder derives `opponent` from the PBP filename itself, via `opponent_from_pbp_filename()` -- a mismatch
there means the game's events exist in `pbp_events` but never get matched up with its schedule row anywhere
downstream, including in the exported CSVs the app reads from). Run this after the box-score cell above to
catch a silently-missing game before it shows up as a mystery in the app instead of here.

In [104]:
# --- Diagnostic: reconcile uww_team_schedule (what the app expects a box score for) against pbp_box_score
# Code: parser_lib\43_diagnostic.py  --  settings below, then the section runs.

run_section("43_diagnostic")

Every played, scouted game in uww_team_schedule has a box score in pbp_box_score. No gaps found.


### Reconstruct a single-game box score by 5-man lineup

Same reconstruction as the cell above, but aggregated by the 5-man lineup on the floor (`uww_lineup`/`opp_lineup`) instead of by individual player -- validated the same way, against the schedule's final scores.

In [106]:
# --- Single-game box score aggregated by 5-MAN LINEUP instead of by individual player -----------------------
# Code: parser_lib\44_reconstruct_single_game_box_score_by_5_man.py  --  settings below, then the section runs.

run_section("44_reconstruct_single_game_box_score_by_5_man")

Validating lineup-level PTS totals against the schedule:

  St. Thomas (TX) Celts 2025-11-14: lineup box score 73-81 vs. schedule 73.0-81.0 [OK]
  Eureka Red Devils 2025-11-15: lineup box score 116-73 vs. schedule 116.0-73.0 [OK]
  Aurora Spartans 2025-11-19: lineup box score 82-73 vs. schedule 82.0-73.0 [OK]
  Simpson Storm 2025-11-25: lineup box score 100-78 vs. schedule 100.0-78.0 [OK]
  Ripon Red Hawks 2025-11-07: lineup box score 76-58 vs. schedule 76.0-58.0 [OK]
  Lawrence Vikings 2025-12-10: lineup box score 88-58 vs. schedule 88.0-58.0 [OK]
  Carroll (WI) Pioneers 2025-12-13: lineup box score 64-60 vs. schedule 64.0-60.0 [OK]
  Hope Flying Dutchmen 2025-12-19: lineup box score 95-92 vs. schedule 95.0-92.0 [OK]
  Alma Scots 2025-12-20: lineup box score 90-61 vs. schedule 90.0-61.0 [OK]
  Elmhurst Bluejays 2025-12-02: lineup box score 88-72 vs. schedule 88.0-72.0 [OK]
  Coe Kohawks 2025-12-30: lineup box score 73-86 vs. schedule 73.0-86.0 [OK]
  UW-Oshkosh Titans 2026-01-03: lineup box score 78-90 vs. schedule 78.0-90.0 [OK]

,opponent,game_date,team,lineup,MIN,+/-,PTS,FGM,FGA,FG3M,FG3A,FTM,FTA,OREB,DREB,REB,AST,STL,BLK,TO,PF,FG%,3P%,FT%
6,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Korbin Heitzman, Logan St. Martin, ...",12.62,-14.0,11,2,13,2,6,5,6,4,7,11,1,1,0,9,4,15.4,33.3,83.3
8,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Korbin Heitzman, Preston Malpass, R...",3.42,-0.0,9,4,6,1,2,0,1,1,1,2,2,0,0,1,1,66.7,50.0,0.0
9,Alma Scots,2025-12-20,Alma Scots,"Elijah Sykes, Josh Elliott, Joss Bradley, Korbin Heitzman, Logan S...",3.74,1.0,9,3,4,1,2,2,2,0,3,3,1,0,1,3,2,75.0,50.0,100.0
2,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Elijah Sykes, Luciano Guerrazzi, Preston Malpass,...",3.44,-0.0,8,3,6,2,4,0,0,1,1,2,3,3,0,2,1,50.0,50.0,NaN
4,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Joss Bradley, Korbin Heitzman, Luci...",3.55,-6.0,6,1,4,1,4,3,4,2,3,5,1,1,1,2,1,25.0,25.0,75.0
3,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Joss Bradley, Korbin Heitzman, Loga...",3.34,-4.0,5,2,3,0,0,1,2,0,2,2,1,0,2,1,3,66.7,NaN,50.0
0,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Elijah Sykes, Joss Bradley, Korbin Heitzman, Luci...",1.87,2.0,4,2,4,0,0,0,0,0,1,1,1,0,0,0,0,50.0,NaN,NaN
1,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Elijah Sykes, Joss Bradley, Luciano Guerrazzi, Pr...",1.95,3.0,3,1,2,1,1,0,0,0,3,3,1,0,0,1,1,50.0,100.0,NaN
5,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Joss Bradley, Luciano Guerrazzi, Pr...",1.45,-1.0,3,1,2,1,2,0,0,1,1,2,1,0,0,1,1,50.0,50.0,NaN
10,Alma Scots,2025-12-20,Alma Scots,"Elijah Sykes, Josh Elliott, Joss Bradley, Korbin Heitzman, Luciano...",1.82,-4.0,3,1,2,0,1,1,2,2,0,2,0,0,0,1,0,50.0,0.0,50.0
7,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Korbin Heitzman, Luciano Guerrazzi,...",0.03,-0.0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,NaN,NaN,NaN
11,Alma Scots,2025-12-20,Alma Scots,"Elijah Sykes, Josh Elliott, Korbin Heitzman, Preston Malpass, Rain...",1.30,-3.0,0,0,3,0,2,0,0,1,1,2,0,0,0,0,0,0.0,0.0,NaN
12,Alma Scots,2025-12-20,Alma Scots,"Elijah Sykes, Joss Bradley, Korbin Heitzman, Luciano Guerrazzi, Pr...",1.20,-3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,NaN,NaN,NaN
17,Alma Scots,2025-12-20,UW-Whitewater,"Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren",12.04,8.0,21,7,17,1,3,6,7,4,5,9,3,6,0,2,5,41.2,33.3,85.7
22,Alma Scots,2025-12-20,UW-Whitewater,"Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren, Tyshawn ...",3.62,3.0,11,4,7,3,4,0,0,0,2,2,2,1,0,0,1,57.1,75.0,NaN

  ... 443 more row(s) of 458 (SHOW_ROWS = 15)


### Aggregate the upcoming opponent's 5-man lineup season box scores

Uses `pbp_events_upcoming` (the opponent's own games, before facing Whitewater) to build their season-aggregated 5-man lineup box scores -- their body of work reconstructed the same way as the cells above, just on the opponent's own games instead of UWW's.

In [108]:
# --- Season-aggregated 5-man lineup box scores for the UPCOMING OPPONENT -----------------------------------
# Code: parser_lib\45_aggregate_upcoming_opponent_5_man_lineup.py  --  settings below, then the section runs.
# --- Season-aggregated 5-man lineup box scores for the UPCOMING OPPONENT -----------------------------------
# Uses pbp_events_upcoming to build the upcoming opponent's 5-man lineup season box scores -- their body of
# work BEFORE they face Whitewater, reconstructed the same way as the cells above but on the opponent's own games.
TEAM_LEVEL_UPCOMING = {"team_deadball_rebound_offensive", "team_deadball_rebound_defensive", "timeout"}

run_section("45_aggregate_upcoming_opponent_5_man_lineup")

UW-Stevens Point Pointers season 5-man lineup box scores (13 game(s) of PBP data, 143 distinct units):
                                                                    lineup  \
0    Cal Krohn, Carter Combs, Josiah Butler, Logan Baumgartner, Seth Miron
1         Cal Krohn, Carter Combs, Isaiah Moore, Josiah Butler, Seth Miron
2          Cal Krohn, Carter Combs, Josh Bocher, Josiah Butler, Seth Miron
3           Cal Krohn, Carter Combs, Josiah Butler, Max Raimer, Seth Miron
4    Cal Krohn, Isaiah Moore, Josiah Butler, Logan Baumgartner, Seth Miron
..                                                                     ...
138       Cal Krohn, Isaiah Moore, Josiah Butler, Max Raimer, Shane Tarjan
139          Cal Krohn, Drew Daoust, Grant Manz, Josiah Butler, Max Raimer
140           Cal Krohn, Josh Bocher, Josiah Butler, Seth Miron, Tyler Orr
141       Carter Combs, Drew Daoust, Josiah Butler, Max Raimer, Seth Miron
142            Cal Krohn, Carter Combs, Josh Bocher, Max Raimer, Tyler Orr

     GP    MIN   +/-  PTS  FGM  FGA   FG%  FG3M  FG3A  ...  FTA   FT%  OREB  \
0    13  130.9 -17.0  296  102  198  51.5    22    73  ...   98  71.4    50
1     7   40.0  -8.0   72   27   53  50.9     1    15  ...   25  68.0    13
2     4   31.8 -14.0   45   16   39  41.0     1    10  ...   15  80.0    10
3     5   15.2 -10.0   37   12   17  70.6     1     4  ...   19  63.2     3
4     5   15.1  11.0   32   11   20  55.0     3     6  ...    9  77.8     2
..   ..    ...   ...  ...  ...  ...   ...   ...   ...  ...  ...   ...   ...
138   1    0.0   0.0    0    0    0   NaN     0     0  ...    0   NaN     0
139   1    0.0   0.0    0    0    0   NaN     0     0  ...    0   NaN     0
140   1    0.0   0.0    0    0    0   NaN     0     0  ...    0   NaN     0
141   1    0.0   0.0    0    0    0   NaN     0     0  ...    0   NaN     0
142   1    0.0   0.0    0    0    0   NaN     0     0  ...    0   NaN     1

     DREB  REB  AST  STL  BLK  TO  PF
0      68  118   52   17    3  30  51
1      26   39   12   10    0   7  24
2      15   25    4    6    4   8  21
3      13   16    7    2    1   4   3
4       5    7    4    7    1   2  12
..    ...  ...  ...  ...  ...  ..  ..
138     0    0    0    0    0   0   0
139     0    0    0    0    0   0   0
140     0    0    0    0    0   0   0
141     0    0    0    0    0   0   0
142     0    1    0    0    0   0   0

[143 rows x 22 columns]

### Frame capture: 5 frames per clip from the live Synergy player

Off by default (`RUN_FRAME_CAPTURE = False`); it then just loads `uww_clip_frames.csv`. When on, it opens each played game's Synergy clip page in Edge, pulls 5 frames from inside every clip straight off the video player, and saves them under `_vision_frames/<date>_<game>/`. Frames already there are reused (the clip isn't played again). The tag model (after the play-calls cell) learns from these frames plus the Synergy description and play-by-play. The old Ollama vision model is gone.

**First run:** set `RUN_FRAME_CAPTURE = True`, `VISION_ONLY_GAME = "1_3_26 UW-Oshkosh Titans @ UW-Whitewater"`, `VISION_TEST_CLIPS = 5`, run, and open a few saved frames to confirm they show the play.

In [110]:
# --- Frame capture: 5 frames per clip from the live Synergy player -------------------------------------------
# Code: parser_lib\46_frame_capture.py  --  settings below, then the section runs.
RUN_FRAME_CAPTURE = True            # True = capture frames for any game not captured yet (~20-40 min a game)
# CONFIRMED CHANGE (before recapturing after the clip-start fix): capture only the first 5 clips, CHECK their frames show
# their own plays (clip 1 = Carter Thomas's turnover from 20:00), then set this back to None for the whole game.
VISION_TEST_CLIPS = 15              # CONFIRMED CHANGE (requested): the first 15 clips of the game (was 5) -- more
                                    # plays to check and more jersey crops for the recognizer; None = the whole game
VISION_ONLY_GAME = "1_3_26 UW-Oshkosh Titans @ UW-Whitewater"  # e.g. "1_3_26 UW-Oshkosh Titans @ UW-Whitewater" = capture ONLY that game (same
                                    # name as its _pbp/_video files); None = every played game, newest first
VISION_RETAG = False                # True = revisit games already captured (clips with frames on disk are still reused)
VISION_FRAMES_PER_CLIP = 5          # the tag model expects this many; changing it means recapturing
VISION_FRAME_MAX_WIDTH = 1024       # the player's own width -- full resolution
VISION_BROWSER_CHANNEL = "msedge"   # "msedge" (always on Windows) or "chrome"; bundled Chromium can't play H.264
VISION_HEADLESS = False             # False = watch it work (recommended until it has run cleanly once)
VISION_PLAYLIST_URLS = []           # optional extra pages: [("label", "https://editor-web.synergysports.com/...")]
VISION_MAX_GAMES_PER_RUN = 2        # newest uncaptured games first
VISION_SKIP_DESCRIPTION = r">\s*Free Throw\s*$"   # clips not worth capturing (free throws)
VISION_TRACK_FPS = 4
# CONFIRMED CHANGE (requested: bigger tracking frames -- jersey numbers were too small to read at 768 wide). 1024 is
# the Synergy player's full width. Frames at a new width go to their own folder (track1024/), so this recaptures
# every game's tracking frames once (and everything built from them); the 768 frames stay on disk untouched.
VISION_TRACK_WIDTH = 1024
VISION_TRACK_JPEG_QUALITY = 0.95   # JPEG quality of newly captured tracking frames (was 0.70; higher = clearer jersey numbers, bigger files)
# CONFIRMED BUG (fixed): 60 frames at 2 a second cut every clip at 30 s -- the end of a long possession (the shot,
# rebound, foul) was never captured. 240 = 60 s at 4 a second.
VISION_TRACK_MAX_FRAMES = 240
VISION_CACHE = os.path.join(INPUT_DIR, "uww_clip_frames.csv")
VISION_FRAMES_DIR = os.path.join(INPUT_DIR, "_vision_frames")
VISION_COLS = ["source_label", "source_url", "position", "clip_game", "clip_date", "team", "player", "result",
               "description", "duration_s", "frame_files", "frames_captured", "track_files", "error", "test_run",
               "captured_at", "video_start_s", "track_times"]
VISION_CAPTURE_VERSION = 2

run_section("46_frame_capture")

Frame capture ONLY '1_3_26 UW-Oshkosh Titans @ UW-Whitewater': 2026-01-03 UW-Oshkosh Titans (https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68deda8125423a1fd110a58b%2ffullgamevideo%2fclips)
Frame capture: every game with a clip page is already in the cache (set VISION_RETAG = True to redo).
Clips with frames: 545 of 545 in uww_clip_frames.csv


### Play calls: decode `uww_plays.csv` (one file, every game) and join it onto the play-by-play

Both files live in `INPUT_DIR` (one of each, always). Each row is one tagged possession; its **Title** holds the play call in shorthand plus where it was run (`OK State- DHO RS- Pat Miller`, `41- BS LS- Reject`, `Blob-Box-Curl`).

* **Decode:** every title becomes situation (Half court / BLOB / SLOB / ATO / Opening set), set or formation, actions in order, primary action, starting spot, finish spot and any player named, with a `decode_quality` (Clean / Partial / Needs review / No call). The raw title is always kept.
* **Join:** each clip matches one play-by-play event of the offense, by Synergy String first, then player + clock, then clock + result. Written onto `pbp_events` (UWW) and `pbp_events_upcoming` (opponent).
* **Points:** from the play-by-play at that clock stamp when matched (free throws count), else from the Result tag.
* **Exports:** `uww_play_calls`, `uww_play_call_summary`, `uww_play_glossary`; UWW clips also feed `uww_coach_notes` for the app's existing play-call analytics.
* **Structured tags (Sept 2026):** `Formation-Call(offensive details): [Press -] Defense (defensive details)`, e.g. `5 out-Motion(pass 5,ds,reject,bs): 122 - m2m (5tl,12drop)`. Numbers in the offense parentheses are positions; numbers in the defense parentheses are the DEFENDER's jersey (`5tl` = defender #5 top-locked the down screen). Each coverage is paired to the screen it answered (`coverage_detail`) and named from rosters/Synergy (`coverage_defenders`). Defense-only possessions are just `m2m` / `122 - m2m`. Tag errors are listed in `decode_note`.
* **Situation:** a situation in the tag wins; otherwise ATO comes from a timeout right before the play in the play-by-play and Transition from Synergy (`situation_source` says which). BLOB vs SLOB can't be derived, so those only come from the tag.
* **Re-decoded every run:** every Title is decoded from its raw text each time the parser runs (uww_play_calls.csv is fully rewritten, never appended), so a change to the tagging standard only needs a change in this cell.
* **Screen coverage:** every defensive detail becomes a row in `uww_screen_coverage` (screen, coverage, defender) and `uww_screen_coverage_summary` (share of each coverage per screen type, and per defender, for each perspective: Opponent defense / UWW defense / defenses each faced). The brief's HOW THEY GUARD SCREENS section and the app's Game Plan tab render it; BALL SCREEN COVERAGE now reads from it too.

* **One plays file:** `uww_plays.csv` holds every tagged clip, UWW games and opponents' games together. Each clip's game decides how it's used: UWW games, the upcoming opponent's games (scouted), and other teams' games (used only to train the tag model). An old `opponent_plays.csv` is merged in if it's still there.

In [112]:
# --- Play calls: uww_plays.csv (every tagged clip, all games), decoded and joined onto the play-by-play ------
# Code: parser_lib\47_play_calls.py  --  settings below, then the section runs.
SCREEN_COVERAGE_RULES = {"thin_screens": 5}   # fewer screens than this in a screen type -> "thin" flag
SCREEN_COVERAGE_COLS = ["side", "scouted_opponent", "perspective", "possession_side", "offense_team", "defense_team",
                        "game_date", "game_code", "period", "player", "play_call", "play_title", "screen_type",
                        "screen_family", "coverage", "defender_jersey", "defender_name", "result", "points",
                        "decode_quality"]
# Stop when captured frames and uww_plays.csv don't line up (a captured game not in uww_plays.csv, or tagged plays
# without frames). A few clips the capture misses are allowed per game; list games to skip on purpose below.
FRAMES_STOP_FOR_GAPS = True
FRAMES_MISSING_PLAYS_ALLOWED = 2      # per game: tagged plays without frames before it stops
FRAMES_STOP_IGNORE_GAMES = []         # e.g. ["WEC@WSP", "Coe"] -- games you've decided not to capture / tag

run_section("47_play_calls")

  uww_plays.csv: WWW@AC 12/20/2025 is in the file twice (416 rows = 2 x 208) -- dropped the second copy (208 rows) so nothing is counted double. Remove it from the file when you can.
  uww_plays.csv: WWW@AC 12/20/2025 had no clip numbers (all 0) -- numbered its 208 rows 1-208 in file order.
  Play clips by game type: UWW 604 clip(s) in 3 game(s), Opponent 140 clip(s) in 1 game(s), Other 0 clip(s) in 0 game(s)
  Upcoming-opponent games: 68 clip(s) are the OTHER team's offense -- kept, but excluded from UW-Stevens Point Pointers's play-call scouting.
  Frames matched to 533 of 744 clip(s) (545 captured).
    captured page '2025-12-20 Alma Scots': 174 clip(s), 174 matched to tagged clips
    captured page '2025-12-30 Coe Kohawks': 175 clip(s), 175 matched to tagged clips
    captured page '2026-01-03 UW-Oshkosh Titans': 196 clip(s), 184 matched to tagged clips
    tagged game 2026-01-03 WEC@WSP: 140 clip(s), NO frames -- capture it (Frame capture, VISION_ONLY_GAME = that game)
  (frame check: 34 non-possession line(s) (free throws, no violation) in 2025-12-20 WWW@AC have no clip on Synergy's page and are not counted)
  (frame check: 36 non-possession line(s) (free throws, no violation) in 2025-12-30 WWW@COE have no clip on Synergy's page and are not counted)
  (frame check: 1 non-possession line(s) (free throws, no violation) in 2026-01-03 WOS@WWW have no clip on Synergy's page and are not counted)
  ====================================================================================================
  NOTE (test capture -- not stopping): the captured frames and uww_plays.csv don't line up yet.
  Tagged games with NO frames -- run Frame capture for each (VISION_ONLY_GAME = that game):
    - 2026-01-03 WEC@WSP: 140 tagged play(s), NO frames
  Then rerun from the Frame capture cell (or this cell, if only uww_plays.csv changed).
  To go on without a game, add it to FRAMES_STOP_IGNORE_GAMES (e.g. "WEC@WSP"); to turn this check off, FRAMES_STOP_FOR_GAPS = False.
  ====================================================================================================
  play_call_summary: 205 offensive row(s), 220 defensive.
  screen_coverage: 227 tagged screen coverage(s) -- Opponent defense: 123, Defenses opponent faced: 66, UWW defense: 27, Defenses UWW faced: 11
UWW games: 604 clip(s) across 3 game(s); decoded {'No call': 520, 'Clean': 83, 'Partial': 1}; matched to play-by-play 519/604 ({'synergy string': 444, 'player + clock': 53, 'clip order + foul by the defense': 21, 'clock + result': 1}).
  First unmatched clips (date, period, clock, player, result):

C:\Users\frits\OneDrive\Documents\GitHub\uwwmensbball\parser\parser_lib\47_play_calls.py:2457: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  coach_notes = pd.concat([coach_notes[~_old_log_rows], _pl_cn], ignore_index=True)

     game_date period  Clock           player                result
0   2025-12-20     H1    NaN  Donovan Collins          No Violation
3   2025-12-20     H1  19:11     Brock Marino            Miss 2 Pts
5   2025-12-20     H1    NaN    Collin Madson          No Violation
8   2025-12-20     H1    NaN    Richie Warren            Free Throw
21  2025-12-20     H1    NaN  Korbin Heitzman  Shot Clock Violation
29  2025-12-20     H1    NaN  Korbin Heitzman            Free Throw

  ... 79 more row(s) of 85 (SHOW_ROWS = 6)
  Most-called: {'5 Out Motion': 27, 'Ball Screen': 13, 'BLOB': 7, 'BLOB Line Motion': 6, 'BLOB Box Motion': 6, 'Over': 4}
  Shot clock estimated for 519/604 clip(s) (needs a matched pbp event).
  Defense tagged on 142/604 clip(s): {'Man-to-Man': 142}; press on 67, coverage called on 36.
    Possessions: 310 offensive, 294 defensive -> 80 defense-faced tag(s), 62 defense-played tag(s).
upcoming-opponent games: 140 clip(s) across 1 game(s); decoded {'Partial': 58, 'Clean': 58, 'No call': 23, 'Needs review': 1}; matched to play-by-play 132/140 ({'synergy string': 107, 'player + clock': 16, 'clip order + foul by the defense': 8, 'clock + result': 1}).
  First unmatched clips (date, period, clock, player, result):

      game_date period Clock             player        result
5    2026-01-03     H1   NaN       Xavier Lewis  No Violation
44   2026-01-03     H1   NaN         Seth Miron   Kicked Ball
53   2026-01-03     H1   NaN      Roan Demovsky  No Violation
68   2026-01-03     H1   NaN       James Jacobs  No Violation
105  2026-01-03     H2   NaN  Logan Baumgartner  No Violation
107  2026-01-03     H2   NaN       Xavier Lewis  No Violation

  ... 2 more row(s) of 8 (SHOW_ROWS = 6)
  Most-called: {'Set': 21, 'Chin': 14, '5 Out Motion': 8, 'Ball Screen': 7, 'BLOB Box Motion': 6, '4-1 Motion': 6}
  Shot clock estimated for 132/140 clip(s) (needs a matched pbp event).
  Defense tagged on 130/140 clip(s): {'Man-to-Man': 130}; press on 7, coverage called on 71.
    Possessions: 72 offensive, 68 defensive -> 66 defense-faced tag(s), 64 defense-played tag(s).
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  CLIP ORDER CHECK: 33 clip(s) sit at a spot in the game video that doesn't match their game clock (captured at the wrong place?):

     game_date game_code period  clip_number  video_start_s   clock                                                            description
0   2025-12-20    WWW@AC     H1            4          356.5  1151.0  21 Brock Marino > Post-Up > Left Block > Right Shoulder > Dribble ...
1   2025-12-20    WWW@AC     H1           12          465.5  1084.0                            24 Richie Warren > Cut > Flash > Miss 2 Pts
2   2025-12-20    WWW@AC     H2          145         4755.5   609.0        12 Jake Quast > Spot-Up > Drives Right > To Basket > Miss 2 Pts
3   2025-12-20    WWW@AC     H2          179         5566.3   238.0  2 Kelton Mcewen > Transition > Ballhandler > Dribble Jumper > Long...
4   2025-12-30   WWW@COE     H2          466         5734.7   810.0                4 Deuce Walters > No Play Type > To Basket > Miss 2 Pts
5   2026-01-03   WOS@WWW     H2           85         2060.2  1191.0                   2 Joey LaChapell > Spot-Up > Drives Right > Turnover
6   2026-01-03   WOS@WWW     H2           87         2088.5  1177.0                      32 Luke Bara > Non Possession > Non Shooting Foul
7   2026-01-03   WOS@WWW     H2           88         2108.6  1175.0                            21 Brock Marino > Cut > Basket > Make 2 Pts
8   2026-01-03   WOS@WWW     H2           89         2118.2  1163.0  4 Michael Metcalf-Grassman > Spot-Up > Drives Right > To Basket > ...
9   2026-01-03   WOS@WWW     H2           90         2130.6  1139.0                              21 Brock Marino > No Play Type > Turnover
10  2026-01-03   WOS@WWW     H2           93         2153.9  1130.0  21 Carter Thomas > Spot-Up > No Dribble Jumper > Guarded > Long/3p...
11  2026-01-03   WOS@WWW     H2           91         2156.0  1134.0  4 Michael Metcalf-Grassman > Transition > Ballhandler > To Basket ...
12  2026-01-03   WOS@WWW     H2           95         2196.9  1104.0                           24 Richie Warren > Cut > Basket > Miss 2 Pts
13  2026-01-03   WOS@WWW     H2           96         2220.4  1087.0  23 Oskar Kangas > P&R Ball Handler > Right P&R > Baseline > Dribbl...
14  2026-01-03   WOS@WWW     H2           97         2236.5  1067.0  15 Collin Madson > ISO > Right > Drives Right > To Basket > Miss 2...

  ... 18 more row(s) of 33 (SHOW_ROWS = 15)
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Jersey-number recognizer: trained on your film

A small image model (ResNet-18) that reads a player's jersey number from his chest crop, trained on a growing set in `INPUT_DIR/jersey_training/`: chest crops of players PaddleOCR named by number (including frames it couldn't read), extra data you add (`JERSEY_TRAIN_EXTRA_DIRS`, e.g. Roboflow's NBA set), and optionally your checks (kept as the TEST set by default). `JERSEY_TRAIN_ADD_FRAMES` adds this run's crops; `JERSEY_TRAIN_NOW = "auto"` retrains when the set changed. It becomes the "trained" reader in the Jersey-number reader test below.

In [114]:
# --- Jersey-number recognizer: a small image model trained on YOUR film ---------------------------------------------
# Code: parser_lib\48_jersey_number_recognizer.py  --  settings below, then the section runs.
RUN_JERSEY_RECOGNIZER = True
JERSEY_TRAIN_DIR = os.path.join(INPUT_DIR, "jersey_training")
JERSEY_TRAIN_ADD_FRAMES = True       # add this run's labeled crops (confident jersey-number tracks + coach checks)
JERSEY_TRAIN_CROPS_PER_TRACK = 8     # crops taken from each player track named by jersey number
JERSEY_TRAIN_NEAR_READ_S = 2.0       # ...only within this many seconds of a frame where the number was actually READ
                                     # (a track can drift onto a teammate later in the clip -- those frames would teach
                                     # the model the wrong number)
JERSEY_TRAIN_MIN_SHARPNESS = 15.0    # skip very blurry crops (e.g. a player behind the ball)
JERSEY_TRAIN_USE_COACH = "half"      # "half" = half your checked players train it, half stay the test; True = all; False = none
JERSEY_TRAIN_FROM_OWN_READS = False   # never learn from its own readings (it would reinforce its own mistakes)
JERSEY_TRAIN_EXTRA_DIRS = []         # more labeled crops: e.g. [r"C:\data\nba_jersey_numbers"] (<number>/ folders or JSONL)
JERSEY_TRAIN_ROBOFLOW_API_KEY = ""   # optional: your Roboflow API key -> downloads Roboflow's NBA jersey-number set once
JERSEY_TRAIN_ROBOFLOW_VERSION = 7
JERSEY_TRAIN_NOW = "auto"            # "auto" = retrain when the training set changed; True = retrain now; False = keep model
JERSEY_TRAIN_EPOCHS = 12
JERSEY_TRAIN_MIN_IMAGES = 40         # below this many training crops, don't train yet
JERSEY_MODEL_PATH = os.path.join(JERSEY_TRAIN_DIR, "jersey_recognizer.pt")

run_section("48_jersey_number_recognizer")

Jersey-number recognizer: nothing new since the last run (no new checks, extra data or settings) -- skipped. JERSEY_TRAIN_NOW = True forces a run.

### Jersey-number reader test

Scores each jersey-number reader against an answer key of 66 chest crops (from the first 5 Oshkosh possessions) whose numbers were read by eye. Player tracking uses the best reader, and uses jersey numbers at all only if it scores at least `TRACK_READER_MIN_ACCURACY`. Add more answer-key crops in `INPUT_DIR/jersey_answer_key.csv`.

In [116]:
# --- Jersey-number reader test: which reader can actually read these jerseys? ------------------------------------
# Code: parser_lib\49_jersey_number_reader_test.py  --  settings below, then the section runs.
RUN_JERSEY_READER_TEST = True
# CONFIRMED CHANGE (requested: work only off the trained recognizer -- EasyOCR and PaddleOCR removed; the slowest part
# of a full-game run). To bring them back: ["easyocr_find", "paddle_find", "trained"].
JERSEY_READER_ENGINES = ["trained"]
JERSEY_TROCR_MODEL = "microsoft/trocr-small-printed"
JERSEY_READER_ACCURACY = {}       # share of ALL answer-key crops read exactly right
JERSEY_READER_PRECISION = {}      # share right among the crops it gave an answer for (at its chosen confidence)
JERSEY_READER_ANSWERS = {}
JERSEY_READER_CONF = {}           # lowest confidence at which it is right JERSEY_READER_TARGET_PRECISION of the time
JERSEY_READER_TARGET_PRECISION = 0.85
JERSEY_READER_MIN_ANSWERS = 6
JERSEY_READER_BEST = None
JERSEY_READER_COACH_RIGHT = {}    # right answers on the coach-checked players (the same crops for every reader)

run_section("49_jersey_number_reader_test")

  coach checks: 9 file(s) found (C:\Users\frits\OneDrive\Documents\GitHub\uwwmensbball\data\play_review_saves\oct-1st.json; C:\Users\frits\OneDrive\Documents\GitHub\uwwmensbball\data\play_review_saves\play_review_2025_12_30_WWW_COE_2025_12_30_WWW_COE_20261001_130211_players_Corey_20261005_134527.json; C:\Users\frits\OneDrive\Documents\GitHub\uwwmensbball\data\play_review_saves\play_review_2026_01_03_WOS_WWW_20260930_084913-2.json); 572 check(s), 460 with a jersey number for the real player, 460 with their frame on disk, 460 matched to a saved detection (detections file: detections_yolo11s_pt_1024_tiles3x2.pkl)
Jersey-number reader test: 221 answer-key crop(s) (221 with their frame on disk, 0 from saved answers; 221 added from coach checks)
  trained     : on YOUR 221 checked players: 118 right, 103 wrong, 0 no answer
  trained     : [221 crops] answered 221/221; right when it answers 53% (118/221 at confidence >= 0.0); wrong answers: 2->21 x4, 4->21 x3, 21->15 x3, 1->5 x3
  best reader: trained -- 118 of your checked players read right; right 53% of the time it answers (221 answers at confidence >= 0.0); answers 53% of all crops correctly

### Player tracking: names on the players, and who screened / who defended it

Follows every player through each clip's tracking frames (captured at `VISION_TRACK_FPS` per second), tells the teams apart by jersey color, names players using Synergy's named player + the ball as anchors, matches every other track to the five on the floor (play-by-play lineups) by appearance, and looks for the screen: the screener, the player screened for, his defender, and the screener's defender. Every run prints a name check (how often it names a Synergy-named player correctly when that answer is hidden) so it's clear how far to trust it. Drawings with names: `_tracking/checks/`. Results go on `uww_play_calls.csv` as `track_*` columns (the tag model learns from them) and one row per track in `uww_player_tracks.csv`.

In [118]:
# --- Player tracking: follow every player through the clip, put names on them, find the screen ----------------
# Code: parser_lib\50_player_tracking.py  --  settings below, then the section runs.
RUN_PLAYER_TRACKING = True
TRACK_DETECTOR = "yolo11s.pt"      # was yolo11s.pt (and yolo11n.pt before): a bigger detector finds more small / overlapping players; downloads once (~40 MB), detection is slower
TRACK_DETECT_SIZE = 1024           # was 768 (the old frame width); the tracking frames are 1024 px wide now
TRACK_PERSON_CONF = 0.18           # was 0.25: keeps fainter detections (partly hidden / far players); the later filters remove false boxes
TRACK_BALL_CONF = 0.10             # the ball is small and blurry; a low bar, then the best one per frame
TRACK_MIN_FRAMES = 3               # shorter tracks are noise
TRACK_EMBED_MODEL = "facebook/dinov2-small"
TRACK_EMBED_CROPS = 4              # crops per track used for its fingerprint (fewer = faster; 4 is plenty)
TRACK_NAME_MIN_CONF = 0.40         # below this a track stays unnamed
TRACK_CHECKS = 8                   # clips drawn with names/boxes into _tracking/checks/
TRACK_DIR = os.path.join(INPUT_DIR, "_tracking")
TRACK_HOME_WEARS_LIGHT = True
TRACK_UWW_GAME_CODE = "WWW"        # UW-Whitewater's code in the export's Game column ("WOS@WWW" = UWW at home)
TRACK_TEAM_COLORS = {}             # manual override: {"<team name or part of it>": "light" or "dark"}
# CONFIRMED CHANGE (requested: remove what isn't earning its time). Shooting-pose anchors found a handful of players per
# game at most, never verified -- off (saves running the pose model). True brings them back.
TRACK_USE_POSE_ANCHORS = False
# Appearance fingerprints (a DINOv2 "look" per player) -- the slowest step of tracking (~10-15 min a full game) -- and the
# appearance name check has never passed (37% at best). Jersey numbers, coach checks, lineups and play-boundary linking
# do the naming. False skips the fingerprints entirely; True brings them (and appearance names, if the check passes) back.
TRACK_USE_APPEARANCE = False
TRACK_USE_COURT = True
TRACK_COURT_MARGIN_FT = 2.0
TRACK_INBOUND_MARGIN_FT = 10.0         # keep the inbounder: a standing person up to this many feet BEHIND a baseline (0 = off)
TRACK_INBOUND_OPEN_S = 2.0              # ...only in the first seconds of a clip (when the ball is thrown in)
TRACK_INBOUND_Y_FT = (8.0, 42.0)        # ...and only across this part of the baseline (feet from the sideline)
TRACK_MAX_SPEED_FTS = 24.0         # a sprinting player covers ~24 ft a second
TRACK_KEEP_ALIVE_S = 1.0           # seconds a track may go unseen and still continue (was 2 frames at 2 a second)
TRACK_RIM_ANCHOR_FT = 8.0          # "closest to the basket" must be within this many feet of it
TRACK_USE_RIM_ANCHORS = False
TRACK_DETECT_TILES = 3
TRACK_DETECT_UPSCALE = 2.0
TRACK_READ_NUMBERS = True
TRACK_OCR_ENGINE = "auto"          # "auto" = the best reader in the Jersey-number reader test; or "easyocr" / "trocr"
TRACK_READER_MIN_ACCURACY = 0.60   # (older gate, used only if the reader test's right-when-it-answers isn't available)
TRACK_READER_MIN_PRECISION = 0.80  # numbers are used if the reader is right at least this often WHEN IT ANSWERS
TRACK_OCR_CROPS_FIND = 4           # crops per track for the slower whole-chest reader
TRACK_OCR_CROPS_PADDLE = 6         # PaddleOCR reads ~0.3 s a crop: more chances per player to catch the number facing us
TRACK_OCR_CROPS_TRAINED = 10       # the trained recognizer reads a crop in milliseconds: read more per player
TRACK_OCR_MIN_TRACK_S = 2.0
TRACK_OCR_CROPS = 6                # chest crops read per track (the tallest, clearest boxes); each is read twice
TRACK_NUMBER_MIN_VOTES = 2         # agreeing reads needed to name a track by number (1 if the read is very sure)
TRACK_NEAR_MARGIN_FT = 0.5         # the camera-side sideline: fans sit right behind it, so almost no margin
TRACK_FAR_MARGIN_FT = -1.5         # far sideline (bench / coaches stand just behind it): negative = cut off inside the line; 0 = at the line
TRACK_MIN_STANDING = 0.62
TRACK_EDGE_ZONE_FT = 3.0
TRACK_TEAM_SURE_RATIO = 0.75       # a detection is "unsure" if its nearest team color is > 75% as far as the next          # seated people measured 0.43-0.59; crouching / partly hidden players 0.66+
TRACK_OCR_MIN_CONF = 0.3           # reads below this confidence aren't counted at all
TRACK_SINGLE_DIGIT_VOTES = 3
TRACK_APPEARANCE_MIN_CHECK = 0.60  # with five to choose from, guessing is right 20% of the time -- 60% means real signal
TRACK_APPEARANCE_MIN_TRIES = 20    # ...and on at least this many hidden trusted names
TRACK_BEST_GUESS = True
TRACK_USE_COACH_CHECKS = True
TRACK_BEST_GUESS_CONF = 0.30
TRACK_LIKENESS_WEIGHT = 2.0
TRACK_SOLVE_LINEUPS = True
TRACK_LINK_POSSESSIONS = True
TRACK_LINK_EVIDENCE = "numbers+coach"   # names carried along linked possessions start only from jersey numbers + coach checks; "all" = also Synergy / pose / play-by-play anchors (old behavior)
TRACK_LOCK_NAMES = True            # a very clear jersey number (or coach check) names the same player's other pieces/clips: where he has been and where he goes
TRACK_LOCK_MIN_CONF = 0.9          # a number read counts as 'locked' at this confidence (0.9 = three agreeing reads; coach checks always lock)
TRACK_LOCK_MAX_GAP_S = 3.0         # a piece of the path may start/end up to this many seconds after/before the locked one
TRACK_LOCK_MAX_COST = 0.6          # how close the join must be (0 = same spot, 1 = exactly a sprint away); lower = more careful
TRACK_LOCK_WEIGHT = 3.0            # evidence weight of a followed name in the lineup matching
TRACK_USE_PBP_EVENTS = "review"
TRACK_PBP_WINDOW_S = 6             # events within this many clock-seconds of the clip's clock
TRACK_PBP_REBOUND_FT = 12          # a rebounder is within this many feet of the rim
TRACK_PBP_NEAR_FT = 6              # a stealer / blocker / fouler is within this many feet of the other player
TRACK_PBP_MARGIN_FT = 2.5          # ...and at least this much closer than the next player on his team
TRACK_PBP_WEIGHT = 1.0
TRACK_PBP_CROWD_FT = 3.0           # review: at a steal, UWW players stood bunched and one box drifted between teammates
                                   # (#32/#21/#11/#14 on one track) -- skip the event if a teammate is this close
TRACK_LINK_FT = 3.0                # same court spot = within this many feet at the same moment
TRACK_LINK_MAX_DT = 0.3            # frames from two clips count as "the same moment" within this many seconds
TRACK_LINK_MIN_MOMENTS = 3         # shared moments needed to link two tracks
TRACK_LINK_WEIGHT = 1.5            # evidence weight of a name carried over from a linked possession
TRACK_LINK_BOUNDARY_S = 0.5        # clips this close (or overlapping) are back-to-back plays
TRACK_LINK_BOUNDARY_FT = 2.5       # ...and the same player stands within this many feet across the boundary
TRACK_EXACT_READ_WEIGHT = 2.0      # a read equal to one of the five numbers (single digits count half)
TRACK_PARTIAL_READ_WEIGHT = 0.7    # a read that fits only some of the five numbers (split between them)
TRACK_ANCHOR_WEIGHT = 1.0          # the Synergy-named anchor
TRACK_MIN_READ_CONF = 0.15         # partial reads below this confidence are ignored
TRACK_MIN_NAME_EVIDENCE = 0.5      # a track needs at least this much evidence for a name (one ambiguous digit is 0.33)
TRACK_MIN_NAME_MARGIN = 0.3        # ...and its best name must beat its second-best by this much (no coin flips)
TRACK_POSE_MODEL = "yolo11n-pose.pt"   # ~6 MB, downloads once

run_section("50_player_tracking")

  [tracking] filled 83 team lineup(s) for clips with no game clock, from the clips just before and after them (same five on both sides = nobody subbed)
  [tracking] step 1: player and ball detections for 533 clip(s) (46,158 frames; saved ones are reused)...
  [tracking]   court mapping available for 36,653 of 46,158 frame(s)
  [tracking] step 2: finding the players in 533 clip(s) and sorting them into teams...
  [tracking]   set aside 102,384 seated or partly hidden people (shorter than a standing player there)
  [tracking] step 3: following players through 533 clip(s) (never across teams)...
  [tracking]   clips tracked: 159 / 533 (29%) -- 0.1 min so far, ~0.3 min left
  [tracking]   clips tracked: 212 / 533 (39%) -- 0.2 min so far, ~0.2 min left
  [tracking]   clips tracked: 265 / 533 (49%) -- 0.2 min so far, ~0.2 min left
  [tracking]   clips tracked: 318 / 533 (59%) -- 0.2 min so far, ~0.2 min left
  [tracking]   clips tracked: 371 / 533 (69%) -- 0.3 min so far, ~0.1 min left
  [tracking]   clips tracked: 424 / 533 (79%) -- 0.3 min so far, ~0.1 min left
  [tracking]   clips tracked: 477 / 533 (89%) -- 0.3 min so far, ~0.0 min left
  [tracking]   clips tracked: 530 / 533 (99%) -- 0.4 min so far, ~0.0 min left
  [tracking]   clips tracked: 533 / 533 (100%) -- 0.4 min so far, ~0.0 min left
  [tracking]   kept 620,492 of 1,804,265 people detected (7.5 players per frame after setting aside referees/coaches/fans); 31,195 tracks, 58.5 per clip (10 players + 3 refs is ideal)
  [tracking] step 4: finding the Synergy-named player in each clip (ball, then shooting pose)...
  [tracking]   note: the ball-based guess disagreed with 'home team wears light (UW-Whitewater)' for 2026-01-03|WOS@WWW -- using home team wears light (UW-Whitewater)
  [tracking]   note: the ball-based guess disagreed with 'home team wears light (Alma Scots)' for 2025-12-20|WWW@AC -- using home team wears light (Alma Scots)
  [tracking]   note: the ball-based guess disagreed with 'home team wears light (Coe Kohawks)' for 2025-12-30|WWW@COE -- using home team wears light (Coe Kohawks)
  [tracking]   anchors from a finish at the rim: 0 (switched off -- TRACK_USE_RIM_ANCHORS)
  [tracking]   anchors from the FIRST player Synergy names (the early ball handler): 31
  [tracking]   coach checks: 572 saved, 484 matched to this run's tracks. How often each naming method was RIGHT on the boxes checked: best guess 89/448 (20%); jersey number 48/68 (71%); coach checked 11/14 (79%); lineup matching 1/9 (11%); Synergy 0/8 (0%); linked possession 0/6 (0%); not named 0/1 (0%)
  [tracking]   coach checks: 34 player(s) moved to the other team ("wrong team")
  [tracking]   Synergy anchor audit: 16 anchor(s) sit on a track a coach checked -- right 4; wrong because it was a teammate 11, a defender / other team 1, not a player 0
  [tracking]     right by number of late frames the ball was at that track: 2 frame(s): 2/9; 3 frame(s): 1/3; 4 frame(s): 0/2; 5 frame(s): 0/1
  [tracking]   named anchors so far: 193 of 533 clip(s) (0 by shooting pose)
  [tracking] step 5: appearance fingerprints skipped (TRACK_USE_APPEARANCE = False)
  [tracking] step 5b: jersey numbers NOT used -- the best reader (trained) is right 53% of the time it answers (221 answers), below 80%. Players are named only where Synergy names them.
  [tracking] step 5d: play-by-play events point at 164 player(s) (rebound defensive 72, rebound offensive 50, foul 26, steal 9, block 7); where the player was already known they agreed 1 of 1 time(s) -- REVIEW mode: saved for checking, not used for names
  [tracking] step 5e: 397 track(s) locked to a name by a clear jersey number or a coach check; following those players through the clip named 121 more piece(s) of their paths
  [tracking] step 5a: linking possessions that show the same moments of the game...
  [tracking]   following linked players through their other clips named 24 more piece(s)
  [tracking]   231 pairs of clips meet or overlap in the game video (202 back-to-back play boundaries); 966 track links made; 888 linked players; a name reached 161 more track(s) through the links
  [tracking] step 5c: matching each team's tracks to its five on the floor (numbers, partial numbers, anchors, then elimination)...
  [tracking]   named 473 track(s) from evidence (Synergy anchors only -- numbers are off) and 1 more by elimination; agreement with Synergy anchors (anchor hidden): --
  [tracking]   jersey-number conflicts between sources (this game's number is used): Aleks Jajic: #0 in this game / current roster, #1 elsewhere; Aleks Jajic: #1 in this game / current roster, #0 elsewhere; Austin Beeson: #25 in this game / current roster, #99 elsewhere; Austin Beeson: #99 in this game / current roster, #25 elsewhere
  [tracking] step 6: matching every player to the five on the floor...
  [tracking]   2025-12-20|WWW@AC: 0 track(s) named; checking appearance against 0 trusted name(s)...
  [tracking]   appearance name check 0/0 -- too few trusted names to check it (needs 20): appearance-only names are left blank (0 dropped); keeping 0 named by jersey number or Synergy
  [tracking]   2025-12-30|WWW@COE: 91 track(s) named; checking appearance against 0 trusted name(s)...
  [tracking]   appearance name check 0/0 -- too few trusted names to check it (needs 20): appearance-only names are left blank (0 dropped); keeping 91 named by jersey number or Synergy
  [tracking]   2026-01-03|WOS@WWW: 249 track(s) named; checking appearance against 0 trusted name(s)...
  [tracking]   appearance name check 0/0 -- too few trusted names to check it (needs 20): appearance-only names are left blank (0 dropped); keeping 249 named by jersey number or Synergy
  [tracking]   17 track(s) lost a name they shared with another track on the floor at the same moment (the track with the stronger evidence keeps it)
  [tracking] step 6b: best guesses from the lineup for 10,330 more track(s) (marked "best guess"; each carries its probability of being that player -- average 20%, calibrated to the 20% the coach checks measured)
  [tracking]   6,179 track(s) beyond the five on the floor set aside as not players (referees, coaches, sideline) -- no unnamed players remain where the lineup is known
  [tracking] where people were lost (diagnostic):
    1,804,265 people detected in the frames used; 620,492 (34%) passed every filter
      -   749,509 ( 41.5%)  off the court (fans, bench, table)
      -   254,426 ( 14.1%)  cut off at the edge of the picture
      -   102,384 (  5.7%)  short for its spot in the picture (seated / partly hidden)
      -    56,546 (  3.1%)  wide box (seated person)
      -    20,908 (  1.2%)  too small or too large for a player
        6,179  beyond the five on the floor (set aside as not players)
       12,832  followed for fewer than TRACK_MIN_FRAMES frames (thrown away)
       44,027  tracks built
    (grey boxes marked with the reason are drawn on the check pictures in _tracking/checks/)
  [tracking] step 7: looking for the screen in 533 clip(s)...
  [tracking]   clips searched for a screen: 106 / 533 (19%) -- 0.1 min so far, ~0.3 min left
  [tracking]   clips searched for a screen: 159 / 533 (29%) -- 0.1 min so far, ~0.3 min left
  [tracking]   clips searched for a screen: 212 / 533 (39%) -- 0.2 min so far, ~0.2 min left
  [tracking]   clips searched for a screen: 265 / 533 (49%) -- 0.2 min so far, ~0.2 min left
  [tracking]   clips searched for a screen: 318 / 533 (59%) -- 0.3 min so far, ~0.2 min left
  [tracking]   clips searched for a screen: 371 / 533 (69%) -- 0.3 min so far, ~0.1 min left
  [tracking]   clips searched for a screen: 424 / 533 (79%) -- 0.4 min so far, ~0.1 min left
  [tracking]   clips searched for a screen: 477 / 533 (89%) -- 0.4 min so far, ~0.0 min left
  [tracking]   clips searched for a screen: 530 / 533 (99%) -- 0.4 min so far, ~0.0 min left
  [tracking]   clips searched for a screen: 533 / 533 (100%) -- 0.4 min so far, ~0.0 min left
  [tracking] step 8: drawing the check images...
  [tracking]   of the five on the floor: 552 of 5,175 player-clips identified from evidence, 4,609 named by best guess only, 14 not on film (no track left for them)
  [tracking]   players on the floor located on the film: 5,161 of 5,175 (100%) -- by best guess 5006, coach checked 298, Synergy 194, followed player 102, linked possession 61, elimination 1
Player tracking:
  2025-12-20|WWW@AC: 174 clips, 8789 tracks. Ball seen in 173 clip(s). Teams by jersey color: home team wears light (Alma Scots). Lineups on 173 clip(s), Synergy's player found in that lineup on 171. Named anchors: 0 (0 by shooting pose, 0 by finish at the rim). 78 tracks named (78 by lineup matching on Synergy only -- jersey numbers off, 0 by elimination). Name check (appearance): -- right. Synergy anchor vs jersey number: -- agree.
  2025-12-30|WWW@COE: 175 clips, 12743 tracks. Ball seen in 171 clip(s). Teams by jersey color: home team wears light (Coe Kohawks). Lineups on 168 clip(s), Synergy's player found in that lineup on 159. Named anchors: 0 (0 by shooting pose, 0 by finish at the rim). 183 tracks named (103 by lineup matching on Synergy only -- jersey numbers off, 0 by elimination). Name check (appearance): -- right. Synergy anchor vs jersey number: -- agree.
  2026-01-03|WOS@WWW: 184 clips, 9663 tracks. Ball seen in 181 clip(s). Teams by jersey color: home team wears light (UW-Whitewater). Lineups on 175 clip(s), Synergy's player found in that lineup on 169. Named anchors: 0 (0 by shooting pose, 0 by finish at the rim). 477 tracks named (292 by lineup matching on Synergy only -- jersey numbers off, 1 by elimination). Name check (appearance): -- right. Synergy anchor vs jersey number: -- agree.
  Screens found: 424 clip(s). Check images: ./inputs\_tracking\checks

### Detector compare (optional)
Runs the old and the new person detector on ~20 sample pictures and shows how many players each finds, how long each takes on this computer, and side-by-side pictures. Works on its own (no need to run the Player tracking cell first) and reuses any detections already saved.

In [120]:
# Detector compare: old vs new player detector on a small sample (run this INSTEAD of waiting for all frames to be detected)
COMPARE_FRAMES = 20                       # pictures to test, spread across the tracked clips
COMPARE_OLD = ("yolo11s.pt", 768)         # the earlier detector and its size
COMPARE_NEW = ("yolo11s.pt", 1024)
run_section("50b_detector_compare")

Detector compare: 20 frame(s) spread across 533 tracked clips; OLD = yolo11s.pt at 768, NEW = yolo11s.pt at 1024 (3 tiles, upscale 2 for both).
  running the OLD detector...
    0 of 20 frame(s) were already detected in the old detector's saved results
  running the NEW detector...
    20 of 20 frame(s) were already detected in the new detector's saved results
  NOTE: 5 of 20 picture(s) have no court mapping (homography), so nobody was counted in them; that is why a count can look low. Those pictures: ['Dec_19_2025_UWWhitewater@Alma/track1024v2/165_37ed10f7_t046.jpg', 'Dec_29_2025_UWWhitewater@CoeCollege/track1024v2/119_982b4480_t008.jpg', 'Dec_29_2025_UWWhitewater@CoeCollege/track1024v2/41_2a9cefa9_t048.jpg', 'Dec_29_2025_UWWhitewater@CoeCollege/track1024v2/75_d8c15c07_t044.jpg', 'Jan_2_2026_UWOshkosh@UWWhitewater/track1024v2/211_639f50f3_t058.jpg']

People found ON THE COURT per frame (10 players + 3 referees is the ideal ~13):
  OLD yolo11s.pt: average 11.9   |   NEW yolo11s.pt: average 12.4
  NEW found more in 7 frame(s), fewer in 4, the same in 9.
  Side-by-side pictures (old left, new right): ./inputs\_tracking\detector_compare

In [121]:
# Delete the saved detections of the two detectors we are no longer using (yolo11s at 768 and yolo11m at 1024).
# The tracking step keeps one file per detector / size in _tracking; only these two are removed -- yolo11s at 1024 is kept.
import glob, os
for _pat in ("detections_yolo11s_pt_768*.pkl", "detections_yolo11m_pt_1024*.pkl"):
    for _f in glob.glob(os.path.join(TRACK_DIR, _pat)):
        _mb = os.path.getsize(_f) / 1e6
        os.remove(_f)
        print(f"deleted {os.path.basename(_f)} ({_mb:.0f} MB)")
print("done")

done

### Court mapping: every tracked player on the court, in feet

**Calibrate once per gym:** the first run writes `court_calibration/calibrate_<game>.html`. Open it in a browser, click a landmark on the court diagram, then the same spot in the picture — 4+ landmarks per frame, one frame at each basket — and press **Save calibration**. The parser picks the file up from your Downloads folder. After that every frame is mapped automatically (matched to the calibrated frames on the floor's fixed features), and every home game in that gym reuses the same calibration. Each run reports frames mapped, the calibration error in feet, and how many players land on the court.

In [123]:
# --- Court mapping: every tracked player's position ON THE COURT, in feet ----------------------------------------
# Code: parser_lib\51_court_mapping.py  --  settings below, then the section runs.
RUN_COURT_MAPPING = True
COURT_CAL_DIR = os.path.join(INPUT_DIR, "court_calibration")
COURT_SEARCH_DOWNLOADS = True       # look for court_calibration_*.json in your Downloads folder too
COURT_REF_FRAMES = 8                # frames offered in the calibration page per game
COURT_ORB_FEATURES = 2000
COURT_MIN_INLIERS = 30              # fewer matched floor features than this = don't trust the match
COURT_MIN_IN_BOUNDS = 0.7           # share of players that must land on the court for a frame to count
COURT_STOP_FOR_CALIBRATION = True    # stop the notebook when a gym needs its one-time calibration (False = carry on without it)
COURT_OPEN_CALIBRATION_PAGE = True   # open the calibration page in your browser when that happens

run_section("51_court_mapping")

  [court] step 1: reading calibration files from ./inputs\court_calibration and your Downloads folder...
  [court]   found 3 calibration file(s): 2025-12-20|WWW@AC (8 frame(s)), 2025-12-30|WWW@COE (8 frame(s)), 2026-01-03|WOS@WWW (5 frame(s))
  [court]   gym 'AC': 7 usable calibrated frame(s), average click error 0.12 ft
  [court]   gym 'COE': 7 usable calibrated frame(s), average click error 0.32 ft
  [court]   gym 'WWW': 5 usable calibrated frame(s), average click error 0.52 ft
  [court] step 2: 2025-12-20|WWW@AC: placing 14,252 frame(s) on the court (14,252 already done in an earlier run, 0 to match against 7 calibrated frame(s))...
  [court]   2025-12-20|WWW@AC: 11,603 of 14,252 frame(s) on the court (81%, 0 of them via the frame before)
  [court] step 2: 2025-12-30|WWW@COE: placing 15,406 frame(s) on the court (15,406 already done in an earlier run, 0 to match against 7 calibrated frame(s))...
  [court]   2025-12-30|WWW@COE: 9,079 of 15,406 frame(s) on the court (59%, 0 of them via the frame before)
  [court] step 2: 2026-01-03|WOS@WWW: placing 16,500 frame(s) on the court (16,500 already done in an earlier run, 0 to match against 5 calibrated frame(s))...
  [court]   2026-01-03|WOS@WWW: 15,971 of 16,500 frame(s) on the court (97%, 0 of them via the frame before)
  [court] step 3: moving 31,195 player track(s) onto the court...
  [court]   tracks placed: 18,714 / 31,195 (59%) -- 0.1 min so far, ~0.1 min left
  [court]   tracks placed: 21,833 / 31,195 (69%) -- 0.1 min so far, ~0.0 min left
  [court]   tracks placed: 24,952 / 31,195 (79%) -- 0.1 min so far, ~0.0 min left
  [court]   tracks placed: 28,071 / 31,195 (89%) -- 0.1 min so far, ~0.0 min left
  [court]   tracks placed: 31,190 / 31,195 (99%) -- 0.1 min so far, ~0.0 min left
  [court]   tracks placed: 31,195 / 31,195 (100%) -- 0.1 min so far, ~0.0 min left
  [court] step 4: turning every possession so the offense attacks the same basket...
  2025-12-20|WWW@AC: 81% of 14252 frames on the court (0 via the frame before); calibration error 0.12 ft over 7 frame(s); 100% of mapped players land on the court.
  2025-12-30|WWW@COE: 59% of 15406 frames on the court (0 via the frame before); calibration error 0.32 ft over 7 frame(s); 100% of mapped players land on the court.
  2026-01-03|WOS@WWW: 97% of 16500 frames on the court (0 via the frame before); calibration error 0.52 ft over 5 frame(s); 100% of mapped players land on the court.

### Tag model: learns the coaches' Titles (retrained every run)

Every clip with a decoded coach Title is training data. One small classifier per field (formation, play call, defense, press, situation, primary action, ball-screen and off-ball coverage) learns from the Synergy description, game context, and the clip's 5 frames, and predicts every clip with a confidence. Confident predictions become the **Suggested Title** (never replaces the coach's Title).

**Retraining:** leave `TAG_MODEL_RETRAIN = True` and just run the parser after the coaches tag more games. `TAG_MODEL_HOLDOUT_GAMES` scores the model on a game it never trained on; `TAG_MODEL_EXCLUDE_GAMES` keeps a game's tags out of training. Results: `uww_tag_model_report.csv` (this run) and `_tag_model/history.csv` (every retrain).

**Player positions:** a person detector (YOLO) finds the players in every saved frame, splits them into teams by jersey color, and turns each frame into spacing numbers (spread, where on the floor, how tight each team is to the other, same-team pairs touching). `TAG_MODEL_USE_POSITIONS` turns it on/off; drawings of the detected boxes for a few clips are saved to `_tag_model/position_checks/` to check by eye.

**Lineups:** both teams' five on the floor (from the play-by-play) are inputs, and the model also predicts WHO: the screener (learned from Synergy's roll-man / pick-and-pop clips, which name him) and the screen defender (learned from the coaches' jersey tags like `5tl`). Both are limited to the five on the floor for that clip.

In [125]:
# --- Tag model: learns the coaches' Titles, retrained every run ---------------------------------------------
# Code: parser_lib\53_tag_model.py  --  settings below, then the section runs.
RUN_TAG_MODEL = True
TAG_MODEL_RETRAIN = "auto"          # "auto" = retrain a field only when its training data changed since the saved
                                    # model (speed); True = always retrain; False = always reuse the saved model
TAG_MODEL_USE_FRAMES = True         # False = Synergy description + context only (no image model needed)
TAG_MODEL_FRAME_ENCODER = "facebook/dinov2-small"   # pretrained image model (~90 MB download, runs on CPU)
TAG_MODEL_FRAME_PCA = 32            # numbers kept per clip from its 5 frames (more needs more tagged clips)
TAG_MODEL_MIN_CONFIDENCE = 0.60     # below this, a field is left blank in the Suggested Title
TAG_MODEL_MIN_CLASS_EXAMPLES = 5    # an answer needs this many tagged examples before the model learns it
TAG_MODEL_MIN_TRAIN_ROWS = 30       # a field needs this many tagged clips before it's trained at all
TAG_MODEL_C = 1.0                   # set per field each run from TAG_MODEL_C_OPTIONS (see the Run section)
TAG_MODEL_HOLDOUT_GAMES = []        # e.g. ["1_3_26 UW-Oshkosh Titans @ UW-Whitewater"]: never trained on, scored only
TAG_MODEL_VALIDATION_PLAYS = 20     # coach-tagged plays NEVER trained on -- the coaches compare their automatic Titles
TAG_MODEL_EXCLUDE_GAMES = []        # games whose tags should NOT be learned from (e.g. a sloppy early game)
TAG_MODEL_AUTO_INSTALL = True       # pip-install scikit-learn / torch / transformers if missing or too old
TAG_MODEL_MIN_TRANSFORMERS = (4, 40)  # oldest transformers that loads DINOv2
TAG_MODEL_DIR = os.path.join(INPUT_DIR, "_tag_model")
# field -> lineup column: the prediction can only be one of the five players in that lineup on that clip.
TAG_MODEL_LINEUP_LIMITED = {"screener": "offense_lineup", "screen_defender": "defense_lineup"}
TAG_MODEL_FRAME_SIZE = (224, 392)   # ~16:9, the full frame; bigger = more detail, slower
TAG_MODEL_USE_POSITIONS = True
TAG_MODEL_DETECTOR = "yolo11n.pt"   # small, fast; "yolo11s.pt" is more accurate on small far-away players, slower
TAG_MODEL_DETECT_CONF = 0.30        # lowest detector confidence kept
TAG_MODEL_DETECT_SIZE = 1024        # detection resolution (the player's full width)
TAG_MODEL_POSITION_CHECKS = 12      # save this many clips' frames with the boxes drawn, to check it by eye
TAG_MODEL_C_OPTIONS = [0.05, 0.2, 1.0]
TAG_MODEL_REVIEW_OVERRIDES_TITLE = True   # a Play review answer that disagrees with the coach's Title is what the model learns

run_section("53_tag_model")

  [tag model] review answers: 43 added as labels where the coach's Title had none, 11 overriding the coach's Title (TAG_MODEL_REVIEW_OVERRIDES_TITLE)
  [tag model] new answers typed in reviews (not seen before -- check for typos): ball_screen_coverage: 'NO ball screens'; ball_screen_coverage: 'No Screens'; ball_screen_coverage: 'No ball'; ball_screen_coverage: 'None'; ball_screen_coverage: 'Switch at the end'; ball_screen_coverage: 'They went over'; ball_screen_coverage: 'none'; formation: 'There's not really one'; offball_coverage: 'No Off ball coded'; offball_coverage: 'No Screens'; offball_coverage: 'No screens'; offball_coverage: 'None'
  Frames: 545 clip(s) captured (uww_clip_frames.csv) -> 533 matched to a clip in uww_plays.csv -> 533 with all 5 frames -> 533 found on disk -> 533 turned into numbers
Tag model: 317 coach-tagged clip(s) across 2 game(s) (0 from other teams' games); frames for 533 clip(s).
  Positions: players found in 533 clip(s), ~8.8 player(s) per frame on average (10 on the floor + refs = best case). Check the boxes: ./inputs\_tag_model\position_checks
  [tag model] 20 coach-tagged play(s) kept OUT of training for validation (TAG_MODEL_VALIDATION_PLAYS; list in ./inputs\_tag_model\validation_plays.csv)
  [tag model] on the 20 validation plays (never trained on): formation 6/13; play_call 8/16; defense 20/20 (confident: 100% of 20); press 17/20 (confident: 84% of 19); situation 11/20 (confident: 55% of 20); primary_action 2/9 (confident: 50% of 4); ball_screen_coverage 0/7; offball_coverage 0/2 (confident: 0% of 2); screener 0/2; screen_defender 3/4 (confident: 75% of 4)
  formation               32% right (always-most-common: 53%)  n=111  | confident on 89%, 33% right  -> using most common answer (5 Out) -- model not better yet
  play_call               38% right (always-most-common: 47%)  n=128  | confident on 48%, 28% right  -> using most common answer (Motion) -- model not better yet
  defense                only one answer tagged so far (Man-to-Man): predicted for every clip at 100%
  press                   75% right (always-most-common: 74%)  n=247  | confident on 100%, 75% right  [context+positions]
  situation               75% right (always-most-common: 75%)  n=296  | confident on 93%, 77% right  -> using most common answer (Half court) -- model not better yet
  primary_action          41% right (always-most-common: 39%)  n=74  | confident on 62%, 35% right  [context]
  ball_screen_coverage    32% right (always-most-common: 32%)  n=71  | confident on 55%, 36% right  -> using most common answer (Stay) -- model not better yet
  offball_coverage        26% right (always-most-common: 66%)  n=35  | confident on 100%, 26% right  -> using most common answer (Over) -- model not better yet
  screener               not trained: needs 30+ tagged clips over 2+ answers (has 0 over 0)
  screen_defender         42% right (always-most-common: 26%)  n=38  | confident on 55%, 52% right  [context]
  Scored on: each of 2 tagged games held out in turn
  Suggested Titles: 744 clip(s), 427 of them not tagged by a coach yet.

### Tracking insights: matchups, help, screens, sets, inbounds, zone/press, coverage plan, spacing

Every scouting table built from the player tracking: who guards whom, how far each defender helps, every tracked screen (who screened, for whom, both defenders, the coverage), who screens for whom and what the screener does after, recurring offensive alignments (sets), inbounds alignments, zone layouts and press traps, UWW's planned vs actual coverage (`staff_inputs/uww_coverage_plan.csv`; template in `staff_input_templates/`), and UWW's spacing by lineup. Distances are **approximate feet** (the picture's own player heights are the ruler) until court mapping is added. The brief and the app only render these tables.

In [127]:
# --- Tracking insights: every scouting table built from the player tracking -----------------------------------
# Code: parser_lib\54_tracking_insights.py  --  settings below, then the section runs.
TI_FEET_PER_PLAYER = 6.5    # a player's height in feet (the picture's own ruler)
TI_DEPTH_SQUASH = 1.8       # up/down in the picture covers ~1.8x more floor than left/right
TI_WEAK_SIDE_FT = 18        # the ball is "on the other side" when a defender's man is this far from it
TI_TRAP_FT = 5              # two defenders this close to the ball = a trap
TI_CROWD_FT = 6             # two offensive teammates this close (not screening) = crowded
TI_MIN_SET_PLAYERS = 4      # players needed at the set moment to describe an alignment
TRACK_BRIEF_TEAM = None     # e.g. "UW-Oshkosh": whose film the brief's FROM THE FILM section shows (None = the

run_section("54_tracking_insights")

Tracking insights: matchups 748, help 63, screens 424, screen_coverage 376, screen_pairs 272, sets 32, set_clips 423, inbounds 23, zone_press 252, coverage_execution 234, spacing 40, roles 6103, clips 533, matchups_raw 3891, help_raw 17888, matchups_by_game 748, help_by_game 87, screen_coverage_by_game 458, screen_pairs_by_game 309, sets_by_game 46, inbounds_by_game 23, zone_press_by_game 252, coverage_execution_by_game 234, spacing_by_game 48

C:\Users\frits\OneDrive\Documents\GitHub\uwwmensbball\parser\parser_lib\54_tracking_insights.py:603: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  _ti_tables[_n + "_by_game"] = pd.concat(_lst, ignore_index=True) if _lst else pd.DataFrame()

### Court insights: shot chart, heat maps, screen locations, paint help, zone shapes, trap spots, corners/paint spacing, play diagrams

Everything that needs real court positions, from the court-mapped tracks. Includes a built-in check: whether each tracked shot lands on the side of the 3-pt line Synergy called it. The brief and the app only render these tables; the play diagrams (numbered players, paths, dribbles, passes, screens) are also what a FastDraw export will use.

In [129]:
# --- Court insights: everything that needs real court positions ------------------------------------------------
# Code: parser_lib\55_court_insights.py  --  settings below, then the section runs.

run_section("55_court_insights")

  [court] tracked shots: 89 placed, 225 set aside (spot didn't match the shot in the play-by-play)
Court insights: 527 possession(s) on the court -- shots 314, shot_zones 76, heat 9250, screens 396, screen_zones 199, help 63, zone_press 250, spacing 39, diagrams 526, report 3, shot_zones_by_game 95, heat_by_game 12823, screen_zones_by_game 199, help_by_game 87, zone_press_by_game 250, spacing_by_game 47
  Check: 52% of 314 tracked shots land on the right side of the 3-pt line for what Synergy called them (low = the court mapping or the shooter pick needs work).

### Play review: check the players and the automatic Title together, on 20 random plays per game

One page per game and run (`inputs\play_review\<game>\run_<date_time>\review.html`): for each play a GIF with every player's box and number, a Synergy link, the start and end pictures (correct / really … / really … on the other team / wrong team / not a player), and the Title review. One Save (`play_review_<game>_<run>.json`, picked up from Downloads) holds both.

In [131]:
# --- Play review: the player checks and the Title review together, on 20 random plays per game ------------------------
# Code: parser_lib\55c_play_review.py  --  settings below, then the section runs.
RUN_PLAY_REVIEW = True
PLAY_REVIEW_PLAYS_PER_GAME = 20
PLAY_REVIEW_SEED = None                # None = a NEW random set every run; a number (e.g. 7) = the same set again
PLAY_REVIEW_SKIP_REVIEWED = True       # leave out plays already reviewed (player checks or Title answers saved)
PLAY_REVIEW_REQUIRE_SAVED = True       # a new run for a game only when its open review has both parts saved in the app
PLAY_REVIEW_ONLY_GAME = None           # e.g. "WOS" = one game; None = every tracked game
PLAY_REVIEW_VIDEO = "mp4"              # each play as a short video with boxes + numbers: "mp4" (small, play/pause), "gif", or None
PLAY_REVIEW_VIDEO_WIDTH = 560          # pixels wide
PLAY_REVIEW_PICTURE_WIDTH = 1640        # width of the review pictures in the app (they are drawn 1640 wide; was shrunk to 1100)
PLAY_REVIEW_PICTURE_QUALITY = 92       # JPEG quality of the review pictures (was 72)
PLAY_REVIEW_PICTURES = 1                 # pictures per play for the player checks: 1 = the frame with the most players visible; 2 = start + end
PLAY_REVIEW_CROPS = True               # a zoomed head-and-chest close-up of every box, beside its row in the app
PLAY_REVIEW_CROP_HEIGHT = 220          # pixels tall

run_section("55c_play_review")

Play review: 2026-01-03 WEC@WSP left out -- no frames captured for it
Play review -- how often each field of the automatic Title was RIGHT on the plays reviewed so far: Main action 5/19 (26%); Situation 13/17 (76%); Formation 9/11 (82%); Play call 10/14 (71%); Press 6/7 (86%); Defense 19/19 (100%); Ball-screen coverage 1/15 (7%); Off-ball coverage 2/14 (14%); Screen defender 0/3 (0%)
Play review: 2025-12-20 WWW@AC -- no new run: its open review (run 20261006_091440) isn't finished yet (its Title checks and its player checks both need saving in the app, on Previous Games and Analytics > Player Number Tracking).
Play review: 2025-12-30 WWW@COE -- no new run: its open review (run 20261001_130211) isn't finished yet (its Title checks and its player checks both need saving in the app, on Previous Games and Analytics > Player Number Tracking).
Play review: 2026-01-03 WOS@WWW -- no new run: its open review (run 20261001_163018) isn't finished yet (its Title checks and its player checks both need saving in the app, on Previous Games and Analytics > Player Number Tracking).

### Defensive roles: every player in one of BBall Index's 7 defensive roles

Point of Attack, Wing Stopper, Chaser, Helper, Low Activity, Mobile Big, Anchor Big ([definitions](https://www.bball-index.com/defensive-roles/)). Credited only from what names the defender for sure: coaches' coverage tags with his jersey number, film tracking where his name came from evidence (never a best guess), and play-by-play blocks / steals. Cut-offs below are Division III starting points.

In [133]:
# --- Defensive roles: every player (UWW and opponents) in one of BBall Index's 7 defensive roles -----------------------
# Code: parser_lib\55d_defensive_roles.py  --  settings below, then the section runs.
RUN_DEFENSIVE_ROLES = True
DROLE_USE_TRACKING = True             # film matchups / screens / help -- only where the defender's name is from evidence
DROLE_MIN_ACTIONS = 4                 # credited defensive actions before a role isn't "low sample"
DROLE_MIN_COVERAGES = 3               # a big's ball-screen coverages before switch/hedge vs drop decides Mobile / Anchor
DROLE_MATCHUP_WEIGHT = 1.0            # weight of one tracked possession guarding someone (vs one tagged coverage)
DROLE_ONBALL_OVER_CHASE = 1.0         # on-ball actions must be at least this times his chasing actions -> on-ball role
DROLE_BIG_HEIGHT_IN = 79              # a forward (no G) this tall is a big (6'7"); a listed C always is
DROLE_WING_HEIGHT_IN = 77             # a non-big this tall (6'5") or listed F is a wing -> Wing Stopper, not Point of Attack
DROLE_ANCHOR_BLOCKS_PER_GAME = 1.0    # a big with few tagged coverages but this many blocks a game -> Anchor Big
DROLE_HELPER_STOCKS_PER_GAME = 2.0    # steals + blocks a game -> Helper
DROLE_LOW_STOCKS_PER_GAME = 0.7       # under this, and few actions -> Low Activity

run_section("55d_defensive_roles")

Defensive roles: 506 player(s) -- 317 from play-by-play only, 141 from position only, 29 from film tracking, 18 from coach tags, 1 from coach tags + film (6 marked low sample)
  roles: Low Activity 183; Point of Attack 149; Mobile Big 67; Helper 45; Anchor Big 30; Wing Stopper 20; Chaser 12


### Compute biggest scoring runs and largest lead/deficit, with lineups

Finds each game's biggest scoring run and largest lead/deficit for both teams, along with which 5-man lineup was on the floor for each.

In [135]:
# --- Scoring runs and largest lead/deficit per game, with the 5-man lineups on the floor for each ------------
# Code: parser_lib\56_compute_biggest_scoring_runs_and_largest.py  --  settings below, then the section runs.

run_section("56_compute_biggest_scoring_runs_and_largest")

                 opponent   game_date  uww_biggest_run  \
0              Alma Scots  2025-12-20                8
1         Aurora Spartans  2025-11-19               13
2   Carroll (WI) Pioneers  2025-12-13                7
3             Coe Kohawks  2025-12-30                7
4       Elmhurst Bluejays  2025-12-02               10
5       Eureka Red Devils  2025-11-15               12
6    Hope Flying Dutchmen  2025-12-19                8
7        Lawrence Vikings  2025-12-10                9
8         Ripon Red Hawks  2025-11-07                7
9           Simpson Storm  2025-11-25               15
10  St. Thomas (TX) Celts  2025-11-14                6
11      UW-Oshkosh Titans  2026-01-03                7

                                                                                                                                              uww_run_uww_lineup  \
0                   Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren / Brock Marino, Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren
1               Collin Madson, Joey Berezowitz, Kelton McEwen, Rashad Rogers, Richie Warren / Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
2                  Brock Marino, Collin Madson, Isaac Verges, Jake Quast, Kelton McEwen / Brock Marino, Collin Madson, Darius Chestnut, Isaac Verges, Jake Quast
3   Brock Marino, Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren / Darius Chestnut, JR Lukenbill, Kelton McEwen, Rashad Rogers, Tyshawn Teague-Johnson
4                                                                                           Collin Madson, Isaac Verges, Luke Bara, Rashad Rogers, Richie Warren
5         Darius Chestnut, JR Lukenbill, Jake Quast, Joey Berezowitz, Rashad Rogers / Darius Chestnut, Jake Quast, Joey Berezowitz, Rashad Rogers, Richie Warren
6                                                                                          Collin Madson, Isaac Verges, Jake Quast, Kelton McEwen, Rashad Rogers
7               Collin Madson, JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton McEwen / Brock Marino, JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton McEwen
8                                                                                            Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren
9            Darius Chestnut, JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton McEwen / Collin Madson, JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton McEwen
10            Collin Madson, Jake Quast, Joey Berezowitz, Kelton McEwen, Richie Warren / JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton McEwen, Richie Warren
11                                                                                           Brock Marino, Collin Madson, JR Lukenbill, Luke Bara, Richie Warren

                                                                                                                                                                                                                                                                                             uww_run_opp_lineup  \
0                                                                                                                                                                                                                                Donovan Collins, Josh Elliott, Korbin Heitzman, Logan St. Martin, Raine Rodich
1                                                                         Cullen Rauls, Isaiah Thompson, Jeffery Hillmer, Juan Madrigal, Mekhi Doby / Isaiah Thompson, Jeffery Hillmer, Juan Madrigal, Mekhi Doby, Zerrick Johnson / Cullen Rauls, Devon Richardson, Jeffery Hillmer, Juan Madrigal, Mekhi Doby
2                                                                                                                                                                                                                                       Dennis Estepp, Jacob Naber, Lamar Smith, Michael McNabb, Peyton McKenna
3                                                                                                                                                                                                                              C. Reece Breitenbach, Cooper Nailor, Deuce Walters, Jackson Bowman, Kanyon Bryte
4                                                                                                                                                                                                                          Aidyn Boone, Dominic Trelenberg, Luke Smith, Sebastian Blachut, Vinnie Adjahoungbeta
5                                                                                                                                                          Blake Logsdon, Damuzha Moore, Jacob Gonzalez, Jonah Lauff, Max Richardson / Andrew Wells, Damuzha Moore, Jacob Gonzalez, Jaxson Provost, Jonah Lauff
6   Brady Miller, Charles Howell, Marcus Wourman, Orion Yant, Simon Neuhaus / Brady Miller, Justice Mims, Marcus Wourman, Orion Yant, Simon Neuhaus / Brady Miller, Justice Mims, Marcus Wourman, Orion Yant, Parker Hovey / Avery Sanchez, Brady Miller, Justice Mims, Orion Yant, Parker Hovey / Avery San...
7                                                                                                                                           CJ Campbell, Casey Schoenecker, Hogan Demovsky, Matai Edgecombe, Nathan Valentine / Cameron Nash, Casey Schoenecker, Hogan Demovsky, Jackson Weber, Matai Edgecombe
8                                                                                                                                                                                                                                                  CJ Brown, Jack Field, Michael Asman, Sam Leoni, Seth Bunders
9   Bo Huston, Jachin Mertes, Levi Gurwell, Marcus Haupert, Spencer Holley / Caleb Dyvig, Cam Henderson, Jachin Mertes, Levi Gurwell, Seth Gipple / Brogan Fuller, Caleb Dyvig, Cam Henderson, Jachin Mertes, Levi Gurwell / Bo Huston, Brogan Fuller, Caleb Dyvig, Cam Henderson, Jachin Mertes / Bo Huston...
10                                                                                                                                                                                                                                        Garrett Rodgers, Jaden Ross, Omar Gayle, Reyce Allen, Tamarcus Butler
11                                                                                                                                              Brandon Beck, Carter Thomas, Joey LaChapell, Michael Metcalf-Grassman, Nate Nazos / Aiden Hawkinson, Jay Dalton, Logan Rindfleisch, Oskar Kangas, Vitorio Dante

    opponent_biggest_run  \
0                      8
1                     10
2                      8
3                     13
4                      7
5                      5
6                     14
7                      7
8                     10
9                     11
10                     6
11                    15

                                                                                                                                                                                                                                                                                   opp_run_uww_lineup  \
0                                             Jake Quast, Joey Berezowitz, Kelton McEwen, Rashad Rogers, Tyshawn Teague-Johnson / Isaac Verges, Jake Quast, Joey Berezowitz, Rashad Rogers, Tyshawn Teague-Johnson / Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren, Tyshawn Teague-Johnson
1                                                                                                                                                           Brock Marino, Collin Madson, Isaac Verges, Jake Quast, Joey Berezowitz / Brock Marino, Collin Madson, Isaac Verges, Jake Quast, Luke Bara
2   Brock Marino, Darius Chestnut, Isaac Verges, Jake Quast, Kelton McEwen / Brock Marino, Collin Madson, Darius Chestnut, Isaac Verges, Jake Quast / Collin Madson, Darius Chestnut, Isaac Verges, Jake Quast, Richie Warren / Collin Madson, Isaac Verges, Jake Quast, Kelton McEwen, Richie Warren
3                                                                                                                                            Collin Madson, Darius Chestnut, JR Lukenbill, Luke Bara, Tyshawn Teague-Johnson / Brock Marino, Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren
4                                                                                                                                                                                                                                 Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren
5                                                                                                                                                                                                                                  Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
6                                                                                  Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren / Brock Marino, Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren / Brock Marino, Collin Madson, Jake Quast, Joey Berezowitz, Luke Bara
7                                                                                                                                                                                                                            Collin Madson, Jake Quast, Joey Berezowitz, Kelton McEwen, Rashad Rogers
8                                                                                                                                                                                                                                  Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
9                                                    Agape Keyes Jr., Isaiah Robinson, Matthew McKay, Trent Grunewald, Tristian Lynch / Agape Keyes Jr., Isaiah Robinson, Mikey Wildes, Trent Grunewald, Tristian Lynch / Agape Keyes Jr., Isaiah Robinson, Mikey Wildes, Trent Grunewald, Zay Howard
10                                                                                                                                                  Brock Marino, Collin Madson, Jake Quast, Joey Berezowitz, Richie Warren / Collin Madson, JR Lukenbill, Jake Quast, Joey Berezowitz, Richie Warren
11                                                                                                                                                 Brock Marino, Collin Madson, Darius Chestnut, Luke Bara, Richie Warren / Collin Madson, Darius Chestnut, JR Lukenbill, Jake Quast, Joey Berezowitz

                                                                                                                                                                                                                                                                                             opp_run_opp_lineup  \
0                                                                                                                                                                                                                               Donovan Collins, Elijah Sykes, Luciano Guerrazzi, Preston Malpass, Raine Rodich
1                                                                                                                                                  Cullen Rauls, Devon Richardson, Jeffery Hillmer, Juan Madrigal, Zerrick Johnson / Cullen Rauls, Devon Richardson, Juan Madrigal, Mekhi Doby, Zerrick Johnson
2                                                                                                                                                                                                                                       Dennis Estepp, Jacob Naber, Lamar Smith, Michael McNabb, Peyton McKenna
3                                                                                                                                                  Austin Beeson, Cooper Nailor, Deuce Walters, Jackson Bowman, Kanyon Bryte / C. Reece Breitenbach, Cooper Nailor, Deuce Walters, Jackson Bowman, Kanyon Bryte
4                                                                                                                                          Aidyn Boone, Dominic Trelenberg, Jack Cherry, Sebastian Blachut, Talen Pearson / Dominic Trelenberg, Jack Cherry, Jeffrey Williams, Sebastian Blachut, Talen Pearson
5                                                                                                                                                                                                                                          Andrew Coker, Ben Carter, Colin DeLaere, Jaxson Provost, Micah Bruer
6                                                                                                                                                                                                                                       Brendan Cargill, Justice Mims, Marcus Wourman, Orion Yant, Parker Hovey
7                                                                                                                                                                                                                          CJ Campbell, Casey Schoenecker, Hogan Demovsky, Nathan Valentine, Nicholas Gouriotis
8                                                                                                                                                                                                                                              CJ Brown, Kolby Williams, Michael Asman, Sam Leoni, Seth Bunders
9   Brogan Fuller, Cam Henderson, Levi Gurwell, Marcus Haupert, Seth Gipple / Brogan Fuller, Cam Henderson, Levi Gurwell, Logan Kowalski, Seth Gipple / Caleb Dyvig, Cam Henderson, Logan Kowalski, Michael Kasperbauer, Seth Gipple / Caleb Dyvig, Logan Kowalski, Mateo Dzolota, Michael Kasperbauer, Seth...
10                                                                                                                                                                                                                                  Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Reyce Allen
11                                                              Aiden Hawkinson, Jonah Rindfleisch, Matt Imig, Oskar Kangas, Vitorio Dante / Brandon Beck, Carter Thomas, Joey LaChapell, Michael Metcalf-Grassman, Nate Nazos / Aiden Hawkinson, Jonah Rindfleisch, Logan Rindfleisch, Matt Imig, Oskar Kangas

    uww_largest_lead  \
0                 29
1                 23
2                 17
3                  6
4                 22
5                 46
6                  6
7                 32
8                 20
9                 33
10                13
11                 4

                                                                   uww_lead_uww_lineup  \
0     Agape Keyes Jr., Isaiah Robinson, Mauryon Turner, Rashad Rogers, Trent Grunewald
1                   Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
2            Brock Marino, Collin Madson, JR Lukenbill, Joey Berezowitz, Kelton McEwen
3     JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton McEwen, Tyshawn Teague-Johnson
4                     Collin Madson, Isaac Verges, JR Lukenbill, Jake Quast, Luke Bara
5            Agape Keyes Jr., Mikey Wildes, Rashad Rogers, Trent Grunewald, Zay Howard
6                Collin Madson, Isaac Verges, Jake Quast, Kelton McEwen, Rashad Rogers
7   Agape Keyes Jr., Austin Ambrose, Darius Chestnut, Isaiah Robinson, Trent Grunewald
8       Agape Keyes Jr., Isaiah Robinson, Kelton McEwen, Mauryon Turner, Rashad Rogers
9      Agape Keyes Jr., Isaiah Robinson, Matthew McKay, Rashad Rogers, Trent Grunewald
10              Brock Marino, Isaac Verges, JR Lukenbill, Kelton McEwen, Richie Warren
11                 Brock Marino, Collin Madson, JR Lukenbill, Luke Bara, Richie Warren

                                                                        uww_lead_opp_lineup  \
0           Donovan Collins, Josh Elliott, Joss Bradley, Korbin Heitzman, Luciano Guerrazzi
1                Cullen Rauls, Devon Richardson, Jeffery Hillmer, Juan Madrigal, Mekhi Doby
2                  Dennis Estepp, Jacob Naber, Jimmy Tarjan, Michael McNabb, Peyton McKenna
3            Aaron Foote, C. Reece Breitenbach, Cooper Nailor, Jackson Bowman, Ryan Dolphin
4   Dominic Trelenberg, Jack Cherry, Sebastian Blachut, Talen Pearson, Vinnie Adjahoungbeta
5      Amare Brokemond, Dylan Logsdon, Joel Ewald, Mussie Hayelom, Nicholaus Harris-Huntley
6                    Avery Sanchez, Brady Miller, Brendan Cargill, Orion Yant, Parker Hovey
7                           Caleb Nash, Damian Cejka, Jackson Weber, Landon Key, Nolan Koch
8                     Anton Kilde, Christian Wilson, Jackson Flowers, Joey Daun, Landon Lee
9              Bo Huston, Caleb Dyvig, Colton Rasmussen, Jachin Mertes, Michael Kasperbauer
10        Angel Johnson, Charles Gitonga, Corey Thompson, Nicholas Buffalo, Tamarcus Butler
11        Brandon Beck, Carter Thomas, Joey LaChapell, Michael Metcalf-Grassman, Nate Nazos

    opponent_largest_lead  \
0                       3
1                       4
2                       6
3                      26
4                       3
5                       1
6                      12
7                       2
8                      10
9                       0
10                     12
11                     12

                                                          opp_lead_uww_lineup  \
0         Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren
1     Collin Madson, Joey Berezowitz, Luke Bara, Rashad Rogers, Richie Warren
2   Brock Marino, Collin Madson, JR Lukenbill, Joey Berezowitz, Kelton McEwen
3      Brock Marino, Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren
4        Collin Madson, Isaac Verges, Luke Bara, Rashad Rogers, Richie Warren
5          Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
6         Brock Marino, Collin Madson, Jake Quast, Joey Berezowitz, Luke Bara
7         Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren
8          Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
9        Collin Madson, Isaac Verges, Luke Bara, Rashad Rogers, Richie Warren
10      Brock Marino, Collin Madson, Jake Quast, Kelton McEwen, Richie Warren
11    Collin Madson, JR Lukenbill, Jake Quast, Joey Berezowitz, Richie Warren

                                                                     opp_lead_opp_lineup
0         Donovan Collins, Josh Elliott, Korbin Heitzman, Logan St. Martin, Raine Rodich
1            Gevon Grant, Jeffery Hillmer, Juan Madrigal, Larry Carthan, Zerrick Johnson
2                       Cai Joseph, Evan Bland, Jacob Naber, Lamar Smith, Peyton McKenna
3       C. Reece Breitenbach, Cooper Nailor, Deuce Walters, Jackson Bowman, Kanyon Bryte
4   Aidyn Boone, Dominic Trelenberg, Luke Smith, Sebastian Blachut, Vinnie Adjahoungbeta
5                   Andrew Coker, Ben Carter, Colin DeLaere, Jaxson Provost, Micah Bruer
6                Brendan Cargill, Justice Mims, Marcus Wourman, Orion Yant, Parker Hovey
7   CJ Campbell, Casey Schoenecker, Hogan Demovsky, Nathan Valentine, Nicholas Gouriotis
8                       CJ Brown, Kolby Williams, Michael Asman, Sam Leoni, Seth Bunders
9          Cam Henderson, Colton Rasmussen, Levi Gurwell, Marcus Haupert, Spencer Holley
10         Corey Thompson, Garrett Rodgers, Jaden Ross, Nathan Kongolo, Nicholas Buffalo


### Surface clutch-time events with lineup context

Filters `pbp_events` down to the last 5 minutes of the 2nd half or any overtime with the score within 8 points, alongside the lineups on the floor for each event.

In [137]:
# --- Clutch-time event log: last 5 minutes of the 2nd half or any overtime, with the score within 8 points ----
# Code: parser_lib\57_surface_clutch_time_events_with_lineup.py  --  settings below, then the section runs.

run_section("57_surface_clutch_time_events_with_lineup")

                   opponent period time_remaining               team  \
442   St. Thomas (TX) Celts     H2     00:19 (H2)      UW-Whitewater
1356        Aurora Spartans     H2     04:53 (H2)    Aurora Spartans
1357        Aurora Spartans     H2     04:53 (H2)    Aurora Spartans
1358        Aurora Spartans     H2     04:32 (H2)      UW-Whitewater
1360        Aurora Spartans     H2     04:24 (H2)    Aurora Spartans
...                     ...    ...            ...                ...
6146      UW-Oshkosh Titans     H2     01:32 (H2)      UW-Whitewater
6172      UW-Oshkosh Titans     H2     01:00 (H2)      UW-Whitewater
6173      UW-Oshkosh Titans     H2     01:00 (H2)      UW-Whitewater
6177      UW-Oshkosh Titans     H2     00:54 (H2)      UW-Whitewater
6178      UW-Oshkosh Titans     H2     00:54 (H2)  UW-Oshkosh Titans

               player       event_type  \
442         Luke Bara        made_shot
1356    Juan Madrigal        made_shot
1357       Mekhi Doby           assist
1358     Brock Marino      missed_shot
1360     Cullen Rauls        made_shot
...               ...              ...
6146     JR Lukenbill             foul
6172        Luke Bara        made_shot
6173  Darius Chestnut           assist
6177  Joey Berezowitz             foul
6178   Joey LaChapell  free_throw_made

                                      raw_text  uww_score  opp_score  \
442      Luke Bara Makes 3PT Pull Up Jump Shot       73.0       81.0
1356         Juan Madrigal Makes 3PT Jump Shot       70.0       62.0
1357                        Mekhi Doby Assists       70.0       62.0
1358         Brock Marino Misses 3PT Jump Shot       70.0       62.0
1360              Cullen Rauls Makes 2PT Layup       70.0       64.0
...                                        ...        ...        ...
6146        JR Lukenbill Commits Personal Foul       74.0       82.0
6172             Luke Bara Makes 3PT Jump Shot       78.0       85.0
6173                   Darius Chestnut Assists       78.0       85.0
6177     Joey Berezowitz Commits Personal Foul       78.0       85.0
6178  Joey LaChapell Makes Free Throw (1 of 2)       78.0       86.0

                                                                     uww_lineup  \
442        Collin Madson, JR Lukenbill, Kelton McEwen, Luke Bara, Richie Warren
1356           Brock Marino, Collin Madson, Isaac Verges, Jake Quast, Luke Bara
1357           Brock Marino, Collin Madson, Isaac Verges, Jake Quast, Luke Bara
1358           Brock Marino, Collin Madson, Isaac Verges, Jake Quast, Luke Bara
1360           Brock Marino, Collin Madson, Isaac Verges, Jake Quast, Luke Bara
...                                                                         ...
6146   Collin Madson, Darius Chestnut, JR Lukenbill, Joey Berezowitz, Luke Bara
6172  Collin Madson, Darius Chestnut, Joey Berezowitz, Luke Bara, Richie Warren
6173  Collin Madson, Darius Chestnut, Joey Berezowitz, Luke Bara, Richie Warren
6177  Collin Madson, Darius Chestnut, Joey Berezowitz, Luke Bara, Richie Warren
6178  Collin Madson, Darius Chestnut, Joey Berezowitz, Luke Bara, Richie Warren

                                                                                  opp_lineup
442         Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Nicholas Buffalo
1356              Cullen Rauls, Devon Richardson, Juan Madrigal, Mekhi Doby, Zerrick Johnson
1357              Cullen Rauls, Devon Richardson, Juan Madrigal, Mekhi Doby, Zerrick Johnson
1358              Cullen Rauls, Devon Richardson, Juan Madrigal, Mekhi Doby, Zerrick Johnson
1360              Cullen Rauls, Devon Richardson, Juan Madrigal, Mekhi Doby, Zerrick Johnson
...                                                                                      ...
6146  Aiden Hawkinson, Brandon Beck, Carter Thomas, Joey LaChapell, Michael Metcalf-Grassman
6172      Aiden Hawkinson, Brandon Beck, Carter Thomas, Michael Metcalf-Grassman, Nate Nazos
6173      Aiden Hawkinson, Brandon Beck, Carter Thomas, Michael Metcalf-Grassman, Nate Nazos
6177  Aiden Hawkinson, Brandon Beck, Carter Thomas, Joey LaChapell, Michael Metcalf-Grassman
6178  Aiden Hawkinson, Brandon Beck, Carter Thomas, Joey LaChapell, Michael Metcalf-Grassman

[134 rows x 11 columns]

Clutch-time points scored, by team:
                opponent   game_date                   team  points
0        Aurora Spartans  2025-11-19        Aurora Spartans      14
1        Aurora Spartans  2025-11-19          UW-Whitewater      10
2  Carroll (WI) Pioneers  2025-12-13  Carroll (WI) Pioneers       8
3  Carroll (WI) Pioneers  2025-12-13          UW-Whitewater       3
4   Hope Flying Dutchmen  2025-12-19   Hope Flying Dutchmen      16
5   Hope Flying Dutchmen  2025-12-19          UW-Whitewater      18
6  St. Thomas (TX) Celts  2025-11-14          UW-Whitewater       3
7      UW-Oshkosh Titans  2026-01-03      UW-Oshkosh Titans       1
8      UW-Oshkosh Titans  2026-01-03          UW-Whitewater       7

UWW's 5-man lineup(s) used in clutch time, by game:
  Aurora Spartans 2025-11-19: ['Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara', 'Brock Marino, Collin Madson, Isaac Verges, Jake Quast, Luke Bara', 'Brock Marino, Isaac Verges, JR Lukenbill, Jake Quast, Luke Bara', 'Collin Madson, Isaac Verges, JR Lukenbill, Jake Quast, Luke Bara']
  Carroll (WI) Pioneers 2025-12-13: ['Brock Marino, Collin Madson, Darius Chestnut, Isaac Verges, Jake Quast', 'Collin Madson, Darius Chestnut, Isaac Verges, Jake Quast, Richie Warren', 'Collin Madson, Isaac Verges, Jake Quast, Kelton McEwen, Richie Warren']
  Hope Flying Dutchmen 2025-12-19: ['Brock Marino, Collin Madson, Isaac Verges, Jake Quast, Tyshawn Teague-Johnson', 'Brock Marino, Collin Madson, Isaac Verges, Kelton McEwen, Luke Bara', 'Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren', 'Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Tyshawn Teague-Johnson', 'Brock Marino, Isaac Verges, Luke Bara, Richie Warren, Tyshawn Teague-Johnson', 'Brock Marino, Joey Berezowitz, Kelton McEwen, Luke Bara, Tyshawn Teague-Johnson', 'Collin Madson, Isaac Verges, Jake Quast, Kelton McEwen, Rashad Rogers']
  St. Thomas (TX) Celts 2025-11-14: ['Collin Madson, JR Lukenbill, Kelton McEwen, Luke Bara, Richie Warren']
  UW-Oshkosh Titans 2026-01-03: ['Collin Madson, Darius Chestnut, JR Lukenbill, Joey Berezowitz, Luke Bara', 'Collin Madson, Darius Chestnut, Joey Berezowitz, Luke Bara, Richie Warren', 'Collin Madson, JR Lukenbill, Joey Berezowitz, Luke Bara, Richie Warren', 'Collin Madson, Jake Quast, Joey Berezowitz, Luke Bara, Richie Warren']


### Cross-reference actual PBP turnovers against the Keys-to-Victory splits, by lineup

Compares each game's actual PBP-derived turnover counts (and margin) against UWW's season averages and against whether turnovers were called out as a pre-game key, then breaks the win/loss record down by who actually won the turnover battle.

In [139]:
# --- Cross-reference ACTUAL PBP turnover counts against the Keys-to-Victory splits -----------------------
# Code: parser_lib\58_cross_reference_actual_pbp_turnovers.py  --  settings below, then the section runs.

run_section("58_cross_reference_actual_pbp_turnovers")

                 opponent outcome  ball_security_was_a_key  \
0   St. Thomas (TX) Celts       L                     True
1       Eureka Red Devils       W                    False
2         Aurora Spartans       W                    False
3           Simpson Storm       W                    False
4         Ripon Red Hawks       W                    False
5        Lawrence Vikings       W                    False
6   Carroll (WI) Pioneers       W                    False
7    Hope Flying Dutchmen    None                    False
8              Alma Scots       W                    False
9       Elmhurst Bluejays       W                    False
10            Coe Kohawks       L                    False
11      UW-Oshkosh Titans       L                    False

    uww_actual_turnovers uww_season_avg_turnovers uww_vs_season_avg  \
0                     15                     None              None
1                     10                     None              None
2                      9                     None              None
3                      9                     None              None
4                     12                     None              None
5                      9                     None              None
6                     16                     None              None
7                     13                     None              None
8                     11                     None              None
9                      8                     None              None
10                    10                     None              None
11                    11                     None              None

    opponent_actual_turnovers uww_season_avg_turnovers_forced  \
0                           8                            None
1                          17                            None
2                          16                            None
3                          17                            None
4                          14                            None
5                          16                            None
6                          22                            None
7                          12                            None
8                          23                            None
9                          12                            None
10                         14                            None
11                         15                            None

    turnover_margin_uww_favor
0                          -7
1                           7
2                           7
3                           8
4                           2
5                           7
6                           6
7                          -1
8                          12
9                           4
10                          4
11                          4
Actual PBP turnovers vs. the Keys-to-Victory 'Ball Security / Turnovers' emphasis:

St. Thomas (TX) Celts (L): ball security WAS called out as a pre-game key.
    UWW committed 15 turnovers this game vs. their N/A season average (N/A).
    St. Thomas (TX) Celts committed 8 turnovers (UWW forces N/A/gm on average).
    Turnover margin (opponent TOs minus UWW TOs): -7 (against UWW)

Eureka Red Devils (W): ball security was NOT called out as a pre-game key.
    UWW committed 10 turnovers this game vs. their N/A season average (N/A).
    Eureka Red Devils committed 17 turnovers (UWW forces N/A/gm on average).
    Turnover margin (opponent TOs minus UWW TOs): +7 (in UWW's favor)

Aurora Spartans (W): ball security was NOT called out as a pre-game key.
    UWW committed 9 turnovers this game vs. their N/A season average (N/A).
    Aurora Spartans committed 16 turnovers (UWW forces N/A/gm on average).
    Turnover margin (opponent TOs minus UWW TOs): +7 (in UWW's favor)

Simpson Storm (W): ball security was NOT called out as a pre-game key.
    UWW committed 9 turnovers this game vs. their N/A season average (N/A).
    Simpson Storm committed 17 turnovers (UWW forces N/A/gm on average).
    Turnover margin (opponent TOs minus UWW TOs): +8 (in UWW's favor)

Ripon Red Hawks (W): ball security was NOT called out as a pre-game key.
    UWW committed 12 turnovers this game vs. their N/A season average (N/A).
    Ripon Red Hawks committed 14 turnovers (UWW forces N/A/gm on average).
    Turnover margin (opponent TOs minus UWW TOs): +2 (in UWW's favor)

Lawrence Vikings (W): ball security was NOT called out as a pre-game key.
    UWW committed 9 turnovers this game vs. their N/A season average (N/A).
    Lawrence Vikings committed 16 turnovers (UWW forces N/A/gm on average).
    Turnover margin (opponent TOs minus UWW TOs): +7 (in UWW's favor)

Carroll (WI) Pioneers (W): ball security was NOT called out as a pre-game key.
    UWW committed 16 turnovers this game vs. their N/A season average (N/A).
    Carroll (WI) Pioneers committed 22 turnovers (UWW forces N/A/gm on average).
    Turnover margin (opponent TOs minus UWW TOs): +6 (in UWW's favor)

Hope Flying Dutchmen (None): ball security was NOT called out as a pre-game key.
    UWW committed 13 turnovers this game vs. their N/A season average (N/A).
    Hope Flying Dutchmen committed 12 turnovers (UWW forces N/A/gm on average).
    Turnover margin (opponent TOs minus UWW TOs): -1 (against UWW)

Alma Scots (W): ball security was NOT called out as a pre-game key.
    UWW committed 11 turnovers this game vs. their N/A season average (N/A).
    Alma Scots committed 23 turnovers (UWW forces N/A/gm on average).
    Turnover margin (opponent TOs minus UWW TOs): +12 (in UWW's favor)

Elmhurst Bluejays (W): ball security was NOT called out as a pre-game key.
    UWW committed 8 turnovers this game vs. their N/A season average (N/A).
    Elmhurst Bluejays committed 12 turnovers (UWW forces N/A/gm on average).
    Turnover margin (opponent TOs minus UWW TOs): +4 (in UWW's favor)

Coe Kohawks (L): ball security was NOT called out as a pre-game key.
    UWW committed 10 turnovers this game vs. their N/A season average (N/A).
    Coe Kohawks committed 14 turnovers (UWW forces N/A/gm on average).
    Turnover margin (opponent TOs minus UWW TOs): +4 (in UWW's favor)

UW-Oshkosh Titans (L): ball security was NOT called out as a pre-game key.
    UWW committed 11 turnovers this game vs. their N/A season average (N/A).
    UW-Oshkosh Titans committed 15 turnovers (UWW forces N/A/gm on average).
    Turnover margin (opponent TOs minus UWW TOs): +4 (in UWW's favor)

Win/loss record by who actually won the turnover battle (PBP-verified, once enough games have PBP data):
   won_turnover_battle  games  wins  losses  win_pct
0                False      1     0       1      0.0
1                 True     10     8       2      0.8

UWW turnovers by 5-man lineup on the floor:
                opponent  \
42  Hope Flying Dutchmen
81     UW-Oshkosh Titans
60       Ripon Red Hawks
37     Eureka Red Devils
26           Coe Kohawks
..                   ...
44  Hope Flying Dutchmen
45  Hope Flying Dutchmen
47  Hope Flying Dutchmen
48      Lawrence Vikings
84     UW-Oshkosh Titans

                                                                           uww_lineup  \
42                Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren
81                Brock Marino, Collin Madson, JR Lukenbill, Luke Bara, Richie Warren
60                 Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
37                 Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
26   Darius Chestnut, JR Lukenbill, Jake Quast, Kelton McEwen, Tyshawn Teague-Johnson
..                                                                                ...
44    Brock Marino, Joey Berezowitz, Kelton McEwen, Luke Bara, Tyshawn Teague-Johnson
45            Collin Madson, Darius Chestnut, Luke Bara, Rashad Rogers, Richie Warren
47                 Collin Madson, Jake Quast, Kelton McEwen, Luke Bara, Rashad Rogers
48  Agape Keyes Jr., Darius Chestnut, Isaiah Robinson, Rashad Rogers, Trent Grunewald
84   Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren, Tyshawn Teague-Johnson

    turnovers
42          5
81          5
60          4
37          4
26          4
..        ...
44          1
45          1
47          1
48          1
84          1

[85 rows x 3 columns]

Opponent turnovers by their 5-man lineup on the floor:
                  opponent  \
5               Alma Scots
107      UW-Oshkosh Titans
52       Eureka Red Devils
32   Carroll (WI) Pioneers
29   Carroll (WI) Pioneers
..                     ...
41             Coe Kohawks
40             Coe Kohawks
38             Coe Kohawks
36             Coe Kohawks
108      UW-Oshkosh Titans

                                                                                 opp_lineup  \
5            Donovan Collins, Josh Elliott, Korbin Heitzman, Logan St. Martin, Raine Rodich
107       Brandon Beck, Carter Thomas, Joey LaChapell, Michael Metcalf-Grassman, Nate Nazos
52                     Andrew Coker, Ben Carter, Colin DeLaere, Jaxson Provost, Micah Bruer
32                     Evan Bland, Jacob Naber, Lamar Smith, Michael McNabb, Peyton McKenna
29                  Dennis Estepp, Jacob Naber, Lamar Smith, Michael McNabb, Peyton McKenna
..                                                                                      ...
41                 Cooper Nailor, Deuce Walters, Jackson Bowman, Kanyon Bryte, Ryan Dolphin
40        C. Reece Breitenbach, Cooper Nailor, Jackson Bowman, Jackson Newell, Ryan Dolphin
38                Austin Beeson, Cooper Nailor, Deuce Walters, Jackson Bowman, Kanyon Bryte
36                       Aleks Jajic, Austin Beeson, Jackson Newell, Jay Akin, Zach Strauss
108  Carter Thomas, Joey LaChapell, Logan Rindfleisch, Michael Metcalf-Grassman, Nate Nazos

     turnovers
5            9
107          7
52           7
32           5
29           4
..         ...
41           1
40           1
38           1
36           1
108          1

[109 rows x 3 columns]


### Cross-reference actual PBP rebounding against the Keys-to-Victory splits, by lineup

Same cross-reference as the turnover cell above, but for rebounding -- actual PBP rebound totals/margin vs. season averages and the pre-game "Rebounding" key, plus the win/loss split by who won the rebound battle, and rebounds broken down by 5-man lineup.

In [141]:
# --- Cross-reference ACTUAL PBP rebounding totals against the Keys-to-Victory splits ----------------------
# Code: parser_lib\59_cross_reference_actual_pbp_rebounding.py  --  settings below, then the section runs.

run_section("59_cross_reference_actual_pbp_rebounding")

                 opponent outcome  rebounding_was_a_key  uww_actual_reb  \
0   St. Thomas (TX) Celts       L                  True              27
1       Eureka Red Devils       W                  True              38
2         Aurora Spartans       W                 False              30
3           Simpson Storm       W                  True              32
4         Ripon Red Hawks       W                  True              36
5        Lawrence Vikings       W                 False              36
6   Carroll (WI) Pioneers       W                 False              37
7    Hope Flying Dutchmen    None                 False              34
8              Alma Scots       W                 False              27
9       Elmhurst Bluejays       W                 False              29
10            Coe Kohawks       L                 False              27
11      UW-Oshkosh Titans       L                  True              35

   uww_season_avg_reb uww_vs_season_avg_reb  uww_actual_oreb  uww_actual_dreb  \
0                None                  None               10               17
1                None                  None               12               26
2                None                  None                9               21
3                None                  None                8               24
4                None                  None               12               24
5                None                  None               11               25
6                None                  None               18               19
7                None                  None               17               17
8                None                  None                9               18
9                None                  None                4               25
10               None                  None               16               11
11               None                  None               14               21

    opponent_actual_reb uww_season_avg_reb_allowed  opponent_actual_oreb  \
0                    25                       None                    10
1                    22                       None                     6
2                    29                       None                     8
3                    27                       None                     9
4                    18                       None                     5
5                    30                       None                     8
6                    28                       None                     7
7                    22                       None                     9
8                    30                       None                     8
9                    26                       None                     6
10                   28                       None                    11
11                   26                       None                     5

    opponent_actual_dreb  rebound_margin_uww_favor
0                     15                         2
1                     16                        16
2                     21                         1
3                     18                         5
4                     13                        18
5                     22                         6
6                     21                         9
7                     13                        12
8                     22                        -3
9                     20                         3
10                    17                        -1
11                    21                         9
Actual PBP rebounding vs. the Keys-to-Victory 'Rebounding' emphasis:

St. Thomas (TX) Celts (L): rebounding WAS called out as a pre-game key.
    UWW grabbed 27 rebounds (10 off. / 17 def.) this game vs. their N/A season average (N/A).
    St. Thomas (TX) Celts grabbed 25 rebounds (10 off. / 15 def.) -- UWW allows N/A/gm on average.
    Rebound margin (UWW minus opponent): +2 (in UWW's favor)

Eureka Red Devils (W): rebounding WAS called out as a pre-game key.
    UWW grabbed 38 rebounds (12 off. / 26 def.) this game vs. their N/A season average (N/A).
    Eureka Red Devils grabbed 22 rebounds (6 off. / 16 def.) -- UWW allows N/A/gm on average.
    Rebound margin (UWW minus opponent): +16 (in UWW's favor)

Aurora Spartans (W): rebounding was NOT called out as a pre-game key.
    UWW grabbed 30 rebounds (9 off. / 21 def.) this game vs. their N/A season average (N/A).
    Aurora Spartans grabbed 29 rebounds (8 off. / 21 def.) -- UWW allows N/A/gm on average.
    Rebound margin (UWW minus opponent): +1 (in UWW's favor)

Simpson Storm (W): rebounding WAS called out as a pre-game key.
    UWW grabbed 32 rebounds (8 off. / 24 def.) this game vs. their N/A season average (N/A).
    Simpson Storm grabbed 27 rebounds (9 off. / 18 def.) -- UWW allows N/A/gm on average.
    Rebound margin (UWW minus opponent): +5 (in UWW's favor)

Ripon Red Hawks (W): rebounding WAS called out as a pre-game key.
    UWW grabbed 36 rebounds (12 off. / 24 def.) this game vs. their N/A season average (N/A).
    Ripon Red Hawks grabbed 18 rebounds (5 off. / 13 def.) -- UWW allows N/A/gm on average.
    Rebound margin (UWW minus opponent): +18 (in UWW's favor)

Lawrence Vikings (W): rebounding was NOT called out as a pre-game key.
    UWW grabbed 36 rebounds (11 off. / 25 def.) this game vs. their N/A season average (N/A).
    Lawrence Vikings grabbed 30 rebounds (8 off. / 22 def.) -- UWW allows N/A/gm on average.
    Rebound margin (UWW minus opponent): +6 (in UWW's favor)

Carroll (WI) Pioneers (W): rebounding was NOT called out as a pre-game key.
    UWW grabbed 37 rebounds (18 off. / 19 def.) this game vs. their N/A season average (N/A).
    Carroll (WI) Pioneers grabbed 28 rebounds (7 off. / 21 def.) -- UWW allows N/A/gm on average.
    Rebound margin (UWW minus opponent): +9 (in UWW's favor)

Hope Flying Dutchmen (None): rebounding was NOT called out as a pre-game key.
    UWW grabbed 34 rebounds (17 off. / 17 def.) this game vs. their N/A season average (N/A).
    Hope Flying Dutchmen grabbed 22 rebounds (9 off. / 13 def.) -- UWW allows N/A/gm on average.
    Rebound margin (UWW minus opponent): +12 (in UWW's favor)

Alma Scots (W): rebounding was NOT called out as a pre-game key.
    UWW grabbed 27 rebounds (9 off. / 18 def.) this game vs. their N/A season average (N/A).
    Alma Scots grabbed 30 rebounds (8 off. / 22 def.) -- UWW allows N/A/gm on average.
    Rebound margin (UWW minus opponent): -3 (against UWW)

Elmhurst Bluejays (W): rebounding was NOT called out as a pre-game key.
    UWW grabbed 29 rebounds (4 off. / 25 def.) this game vs. their N/A season average (N/A).
    Elmhurst Bluejays grabbed 26 rebounds (6 off. / 20 def.) -- UWW allows N/A/gm on average.
    Rebound margin (UWW minus opponent): +3 (in UWW's favor)

Coe Kohawks (L): rebounding was NOT called out as a pre-game key.
    UWW grabbed 27 rebounds (16 off. / 11 def.) this game vs. their N/A season average (N/A).
    Coe Kohawks grabbed 28 rebounds (11 off. / 17 def.) -- UWW allows N/A/gm on average.
    Rebound margin (UWW minus opponent): -1 (against UWW)

UW-Oshkosh Titans (L): rebounding WAS called out as a pre-game key.
    UWW grabbed 35 rebounds (14 off. / 21 def.) this game vs. their N/A season average (N/A).
    UW-Oshkosh Titans grabbed 26 rebounds (5 off. / 21 def.) -- UWW allows N/A/gm on average.
    Rebound margin (UWW minus opponent): +9 (in UWW's favor)

Win/loss record by who actually won the rebound battle (PBP-verified, once enough games have PBP data):
   won_rebound_battle  games  wins  losses  win_pct
0               False      2     1       1    0.500
1                True      9     7       2    0.778

UWW rebounds by 5-man lineup on the floor:
                  opponent  \
44             Coe Kohawks
99         Ripon Red Hawks
27   Carroll (WI) Pioneers
72    Hope Flying Dutchmen
103        Ripon Red Hawks
..                     ...
86        Lawrence Vikings
16         Aurora Spartans
83        Lawrence Vikings
80    Hope Flying Dutchmen
0               Alma Scots

                                                                                   uww_lineup  \
44           Darius Chestnut, JR Lukenbill, Jake Quast, Kelton McEwen, Tyshawn Teague-Johnson
99                   Brock Marino, Collin Madson, Darius Chestnut, Isaac Verges, JR Lukenbill
27                        Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren
72                        Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren
103                        Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
..                                                                                        ...
86                  Brock Marino, Isaiah Robinson, Jake Quast, Kelton McEwen, Trent Grunewald
16                           Brock Marino, Collin Madson, Isaac Verges, Jake Quast, Luke Bara
83                  Brock Marino, Collin Madson, Isaac Verges, Joey Berezowitz, Richie Warren
80                      Collin Madson, Kelton McEwen, Luke Bara, Rashad Rogers, Richie Warren
0    Agape Keyes Jr., Darius Chestnut, Isaiah Robinson, Rashad Rogers, Tyshawn Teague-Johnson

     rebounds
44         14
99         10
27         10
72         10
103         9
..        ...
86          1
16          1
83          1
80          1
0           1

[148 rows x 3 columns]

Opponent rebounds by their 5-man lineup on the floor:
                  opponent  \
112  St. Thomas (TX) Celts
40             Coe Kohawks
75    Hope Flying Dutchmen
121      UW-Oshkosh Titans
120      UW-Oshkosh Titans
..                     ...
56       Elmhurst Bluejays
55       Elmhurst Bluejays
54       Elmhurst Bluejays
52       Elmhurst Bluejays
122      UW-Oshkosh Titans

                                                                                  opp_lineup  \
112         Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Nicholas Buffalo
40          C. Reece Breitenbach, Cooper Nailor, Deuce Walters, Jackson Bowman, Kanyon Bryte
75                   Brendan Cargill, Justice Mims, Marcus Wourman, Orion Yant, Parker Hovey
121        Brandon Beck, Carter Thomas, Joey LaChapell, Michael Metcalf-Grassman, Nate Nazos
120               Aiden Hawkinson, Jonah Rindfleisch, Matt Imig, Oskar Kangas, Vitorio Dante
..                                                                                       ...
56                 EJ Marshall, Jack Cherry, Luke Smith, Talen Pearson, Vinnie Adjahoungbeta
55        Dominic Trelenberg, Jeffrey Williams, Luke Smith, Sebastian Blachut, Talen Pearson
54   Dominic Trelenberg, Jack Cherry, Sebastian Blachut, Talen Pearson, Vinnie Adjahoungbeta
52      Dominic Trelenberg, EJ Marshall, Luke Smith, Sebastian Blachut, Vinnie Adjahoungbeta
122   Carter Thomas, Joey LaChapell, Logan Rindfleisch, Michael Metcalf-Grassman, Nate Nazos

     rebounds
112        16
40         14
75         10
121        10
120        10
..        ...
56          1
55          1
54          1
52          1
122         1

[123 rows x 3 columns]


### Compute scoring margin and minutes played by 5-man lineup combination

Detects lineup-stint boundaries (any substitution for either team) across all of UWW's games, then aggregates minutes played and net scoring margin for each distinct lineup combination.

In [143]:
# --- Scoring margin and minutes played by 5-man lineup combination -----------------------------------------
# Code: parser_lib\60_compute_scoring_margin_and_minutes_played.py  --  settings below, then the section runs.

run_section("60_compute_scoring_margin_and_minutes_played")

              opponent  stint_num  \
0           Alma Scots          1
1           Alma Scots          2
2           Alma Scots          3
3           Alma Scots          4
4           Alma Scots          5
..                 ...        ...
572  UW-Oshkosh Titans         68
573  UW-Oshkosh Titans         69
574  UW-Oshkosh Titans         70
575  UW-Oshkosh Titans         71
576  UW-Oshkosh Titans         72

                                                                    uww_lineup  \
0          Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren
1       Brock Marino, Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren
2       Brock Marino, Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren
3      Brock Marino, Collin Madson, Jake Quast, Joey Berezowitz, Kelton McEwen
4      Brock Marino, Collin Madson, Jake Quast, Joey Berezowitz, Kelton McEwen
..                                                                         ...
572  Collin Madson, Darius Chestnut, Joey Berezowitz, Luke Bara, Richie Warren
573  Collin Madson, Darius Chestnut, Joey Berezowitz, Luke Bara, Richie Warren
574  Collin Madson, Darius Chestnut, Joey Berezowitz, Luke Bara, Richie Warren
575  Collin Madson, Darius Chestnut, Joey Berezowitz, Luke Bara, Richie Warren
576  Collin Madson, Darius Chestnut, Joey Berezowitz, Luke Bara, Richie Warren

                                                                                    opp_lineup  \
0               Donovan Collins, Josh Elliott, Korbin Heitzman, Logan St. Martin, Raine Rodich
1               Donovan Collins, Josh Elliott, Korbin Heitzman, Logan St. Martin, Raine Rodich
2                  Elijah Sykes, Josh Elliott, Joss Bradley, Korbin Heitzman, Logan St. Martin
3                  Elijah Sykes, Josh Elliott, Joss Bradley, Korbin Heitzman, Logan St. Martin
4                 Elijah Sykes, Josh Elliott, Joss Bradley, Korbin Heitzman, Luciano Guerrazzi
..                                                                                         ...
572     Aiden Hawkinson, Brandon Beck, Carter Thomas, Joey LaChapell, Michael Metcalf-Grassman
573            Aiden Hawkinson, Brandon Beck, Carter Thomas, Joey LaChapell, Jonah Rindfleisch
574                Aiden Hawkinson, Brandon Beck, Carter Thomas, Jonah Rindfleisch, Nate Nazos
575  Aiden Hawkinson, Brandon Beck, Carter Thomas, Jonah Rindfleisch, Michael Metcalf-Grassman
576                Aiden Hawkinson, Brandon Beck, Carter Thomas, Jonah Rindfleisch, Nate Nazos

     stint_minutes  uww_margin_change  n_events
0             4.82                2.0        43
1             0.98                2.0        14
2             0.00                0.0         2
3             1.92                1.0        15
4             0.47                3.0         6
..             ...                ...       ...
572           0.10               -2.0         5
573           0.00                0.0         2
574           0.20               -2.0         7
575           0.38               -1.0         8
576           0.18                0.0         3

[577 rows x 7 columns]
Clock check: all 12 game(s) between 35 and 65 elapsed minutes.

UWW's 5-man lineups, ranked by net scoring margin while on the floor:

[Lawrence Vikings] Collin Madson, JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton McEwen
    4.6 min over 6 stint(s), net margin +12 (+2.63/min)

[Simpson Storm] Collin Madson, Darius Chestnut, JR Lukenbill, Luke Bara, Richie Warren
    2.8 min over 3 stint(s), net margin +11 (+3.93/min)

[Eureka Red Devils] Darius Chestnut, Jake Quast, Joey Berezowitz, Rashad Rogers, Richie Warren
    5.9 min over 4 stint(s), net margin +9 (+1.53/min)

[Eureka Red Devils] Brock Marino, Collin Madson, Kelton McEwen, Mauryon Turner, Richie Warren
    3.0 min over 3 stint(s), net margin +9 (+2.96/min)

[Coe Kohawks] Darius Chestnut, JR Lukenbill, Jake Quast, Kelton McEwen, Tyshawn Teague-Johnson
    12.6 min over 7 stint(s), net margin +9 (+0.72/min)

[Simpson Storm] Collin Madson, JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton McEwen
    2.2 min over 4 stint(s), net margin +9 (+4.00/min)

[Hope Flying Dutchmen] Brock Marino, Collin Madson, Isaac Verges, Kelton McEwen, Luke Bara
    0.2 min over 2 stint(s), net margin +8 (+36.36/min)

[Eureka Red Devils] Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
    5.9 min over 2 stint(s), net margin +8 (+1.36/min)

[Alma Scots] Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren
    12.0 min over 5 stint(s), net margin +8 (+0.66/min)

[Ripon Red Hawks] Brock Marino, Collin Madson, Darius Chestnut, Isaac Verges, JR Lukenbill
    6.7 min over 10 stint(s), net margin +7 (+1.05/min)

[Aurora Spartans] Collin Madson, Joey Berezowitz, Kelton McEwen, Rashad Rogers, Richie Warren
    6.2 min over 5 stint(s), net margin +7 (+1.12/min)

[Eureka Red Devils] Brock Marino, JR Lukenbill, Jake Quast, Joey Berezowitz, Luke Bara
    2.9 min over 2 stint(s), net margin +7 (+2.41/min)

[Carroll (WI) Pioneers] Collin Madson, Jake Quast, Joey Berezowitz, Kelton McEwen, Rashad Rogers
    2.3 min over 2 stint(s), net margin +6 (+2.64/min)

[Carroll (WI) Pioneers] Brock Marino, Collin Madson, Isaac Verges, Jake Quast, Kelton McEwen
    1.9 min over 2 stint(s), net margin +5 (+2.63/min)

[Hope Flying Dutchmen] Brock Marino, Collin Madson, Jake Quast, Joey Berezowitz, Kelton McEwen
    1.5 min over 3 stint(s), net margin +5 (+3.29/min)

[Aurora Spartans] Brock Marino, Darius Chestnut, Jake Quast, Joey Berezowitz, Richie Warren
    2.5 min over 4 stint(s), net margin +5 (+2.00/min)

[Carroll (WI) Pioneers] Brock Marino, Darius Chestnut, Jake Quast, Joey Berezowitz, Kelton McEwen
    2.8 min over 2 stint(s), net margin +5 (+1.75/min)

[Elmhurst Bluejays] Collin Madson, Isaac Verges, Luke Bara, Rashad Rogers, Richie Warren
    6.8 min over 4 stint(s), net margin +5 (+0.74/min)

[Elmhurst Bluejays] Collin Madson, Jake Quast, Joey Berezowitz, Kelton McEwen, Richie Warren
    2.9 min over 3 stint(s), net margin +5 (+1.74/min)

[Lawrence Vikings] Brock Marino, JR Lukenbill, Joey Berezowitz, Luke Bara, Richie Warren
    1.5 min over 2 stint(s), net margin +5 (+3.27/min)

[Lawrence Vikings] Collin Madson, Isaac Verges, Jake Quast, Rashad Rogers, Richie Warren
    1.3 min over 3 stint(s), net margin +5 (+3.79/min)

[Elmhurst Bluejays] Collin Madson, Isaac Verges, JR Lukenbill, Jake Quast, Luke Bara
    9.6 min over 11 stint(s), net margin +5 (+0.52/min)

[Alma Scots] Darius Chestnut, Jake Quast, Joey Berezowitz, Kelton McEwen, Tyshawn Teague-Johnson
    4.0 min over 3 stint(s), net margin +5 (+1.24/min)

[Ripon Red Hawks] Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren
    5.2 min over 2 stint(s), net margin +5 (+0.96/min)

[Carroll (WI) Pioneers] Darius Chestnut, Isaac Verges, Jake Quast, Luke Bara, Rashad Rogers
    1.1 min over 2 stint(s), net margin +5 (+4.55/min)

[Simpson Storm] Darius Chestnut, JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton McEwen
    2.5 min over 4 stint(s), net margin +5 (+2.03/min)

[St. Thomas (TX) Celts] Collin Madson, Darius Chestnut, Jake Quast, Joey Berezowitz, Richie Warren
    1.3 min over 2 stint(s), net margin +5 (+3.79/min)

[Aurora Spartans] Collin Madson, Isaac Verges, JR Lukenbill, Jake Quast, Luke Bara
    0.5 min over 6 stint(s), net margin +5 (+10.00/min)

[Eureka Red Devils] Brock Marino, Darius Chestnut, Isaac Verges, JR Lukenbill, Luke Bara
    3.3 min over 1 stint(s), net margin +4 (+1.20/min)

[UW-Oshkosh Titans] Brock Marino, Collin Madson, JR Lukenbill, Luke Bara, Richie Warren
    11.2 min over 16 stint(s), net margin +4 (+0.36/min)

[Eureka Red Devils] Brock Marino, Darius Chestnut, Jake Quast, Joey Berezowitz, Richie Warren
    1.2 min over 2 stint(s), net margin +4 (+3.28/min)

[UW-Oshkosh Titans] Brock Marino, Collin Madson, JR Lukenbill, Jake Quast, Luke Bara
    1.4 min over 3 stint(s), net margin +4 (+2.80/min)

[Eureka Red Devils] Darius Chestnut, JR Lukenbill, Jake Quast, Joey Berezowitz, Rashad Rogers
    1.8 min over 3 stint(s), net margin +4 (+2.26/min)

[St. Thomas (TX) Celts] JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton McEwen, Richie Warren
    1.5 min over 1 stint(s), net margin +4 (+2.63/min)

[Hope Flying Dutchmen] Collin Madson, Isaac Verges, Kelton McEwen, Luke Bara, Rashad Rogers
    1.1 min over 5 stint(s), net margin +4 (+3.81/min)

[Hope Flying Dutchmen] Collin Madson, Joey Berezowitz, Kelton McEwen, Rashad Rogers, Tyshawn Teague-Johnson
    4.0 min over 4 stint(s), net margin +4 (+1.01/min)

[Hope Flying Dutchmen] Collin Madson, Kelton McEwen, Luke Bara, Rashad Rogers, Richie Warren
    0.1 min over 2 stint(s), net margin +4 (+33.33/min)

[Lawrence Vikings] Brock Marino, JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton McEwen
    1.2 min over 2 stint(s), net margin +4 (+3.28/min)

[Lawrence Vikings] Collin Madson, Isaac Verges, JR Lukenbill, Jake Quast, Joey Berezowitz
    1.8 min over 1 stint(s), net margin +4 (+2.25/min)

[Lawrence Vikings] Collin Madson, Jake Quast, Joey Berezowitz, Kelton McEwen, Richie Warren
    1.1 min over 2 stint(s), net margin +4 (+3.51/min)

[Ripon Red Hawks] Austin Ambrose, Collin Madson, Darius Chestnut, Jake Quast, Joey Berezowitz
    1.6 min over 2 stint(s), net margin +4 (+2.58/min)

[Simpson Storm] Collin Madson, Darius Chestnut, Isaac Verges, Rashad Rogers, Richie Warren
    1.0 min over 2 stint(s), net margin +4 (+3.88/min)

[Hope Flying Dutchmen] Brock Marino, Collin Madson, Joey Berezowitz, Kelton McEwen, Tyshawn Teague-Johnson
    1.4 min over 4 stint(s), net margin +4 (+2.94/min)

[St. Thomas (TX) Celts] Brock Marino, Isaac Verges, JR Lukenbill, Kelton McEwen, Richie Warren
    3.0 min over 4 stint(s), net margin +4 (+1.32/min)

[UW-Oshkosh Titans] Collin Madson, Darius Chestnut, Joey Berezowitz, Richie Warren, Tyshawn Teague-Johnson
    1.5 min over 3 stint(s), net margin +4 (+2.76/min)

[Lawrence Vikings] JR Lukenbill, Jake Quast, Joey Berezowitz, Luke Bara, Rashad Rogers
    1.6 min over 2 stint(s), net margin +3 (+1.94/min)

[Ripon Red Hawks] Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Joey Berezowitz
    1.2 min over 3 stint(s), net margin +3 (+2.40/min)

[Elmhurst Bluejays] Collin Madson, Jake Quast, Joey Berezowitz, Luke Bara, Richie Warren
    1.1 min over 2 stint(s), net margin +3 (+2.61/min)

[Eureka Red Devils] Agape Keyes Jr., Mikey Wildes, Rashad Rogers, Trent Grunewald, Zay Howard
    1.9 min over 1 stint(s), net margin +3 (+1.60/min)

[Elmhurst Bluejays] Brock Marino, Collin Madson, Darius Chestnut, Jake Quast, Joey Berezowitz
    0.8 min over 3 stint(s), net margin +3 (+3.53/min)

[Aurora Spartans] Collin Madson, JR Lukenbill, Joey Berezowitz, Kelton McEwen, Rashad Rogers
    1.4 min over 2 stint(s), net margin +3 (+2.11/min)

[Hope Flying Dutchmen] Collin Madson, Isaac Verges, Jake Quast, Kelton McEwen, Rashad Rogers
    6.3 min over 10 stint(s), net margin +3 (+0.47/min)

[UW-Oshkosh Titans] Collin Madson, Jake Quast, Joey Berezowitz, Luke Bara, Richie Warren
    2.2 min over 6 stint(s), net margin +3 (+1.38/min)

[Alma Scots] Darius Chestnut, Jake Quast, Joey Berezowitz, Luke Bara, Tyshawn Teague-Johnson
    2.4 min over 4 stint(s), net margin +3 (+1.27/min)

[Ripon Red Hawks] Austin Ambrose, Collin Madson, Darius Chestnut, Joey Berezowitz, Richie Warren
    1.3 min over 2 stint(s), net margin +3 (+2.34/min)

[Alma Scots] Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren, Tyshawn Teague-Johnson
    3.6 min over 4 stint(s), net margin +3 (+0.83/min)

[Elmhurst Bluejays] Collin Madson, JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton McEwen
    2.8 min over 3 stint(s), net margin +3 (+1.07/min)

[Alma Scots] Collin Madson, Darius Chestnut, Luke Bara, Richie Warren, Tyshawn Teague-Johnson
    1.3 min over 1 stint(s), net margin +3 (+2.31/min)

[Alma Scots] Collin Madson, Darius Chestnut, Joey Berezowitz, Luke Bara, Richie Warren
    3.4 min over 3 stint(s), net margin +3 (+0.89/min)

[St. Thomas (TX) Celts] Collin Madson, Jake Quast, Joey Berezowitz, Kelton McEwen, Richie Warren
    2.3 min over 1 stint(s), net margin +3 (+1.29/min)

[Alma Scots] Agape Keyes Jr., Isaiah Robinson, Rashad Rogers, Trent Grunewald, Tyshawn Teague-Johnson
    0.1 min over 1 stint(s), net margin +3 (+23.08/min)

[Simpson Storm] Collin Madson, JR Lukenbill, Luke Bara, Rashad Rogers, Richie Warren
    1.0 min over 2 stint(s), net margin +3 (+2.91/min)

[Simpson Storm] Agape Keyes Jr., Isaiah Robinson, Matthew McKay, Rashad Rogers, Trent Grunewald
    1.6 min over 2 stint(s), net margin +3 (+1.88/min)

[Eureka Red Devils] Brock Marino, Collin Madson, Isaac Verges, Jake Quast, Luke Bara
    0.4 min over 1 stint(s), net margin +2 (+5.26/min)

[Aurora Spartans] Jake Quast, Joey Berezowitz, Luke Bara, Rashad Rogers, Richie Warren
    0.9 min over 1 stint(s), net margin +2 (+2.17/min)

[Eureka Red Devils] Brock Marino, Darius Chestnut, Isaac Verges, Luke Bara, Mauryon Turner
    1.4 min over 2 stint(s), net margin +2 (+1.45/min)

[Alma Scots] Brock Marino, Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren
    1.0 min over 2 stint(s), net margin +2 (+2.04/min)

[St. Thomas (TX) Celts] Collin Madson, Darius Chestnut, JR Lukenbill, Kelton McEwen, Richie Warren
    2.5 min over 3 stint(s), net margin +2 (+0.79/min)

[Eureka Red Devils] Isaiah Robinson, Kelton McEwen, Rashad Rogers, Richie Warren, Trent Grunewald
    0.5 min over 2 stint(s), net margin +2 (+4.08/min)

[Hope Flying Dutchmen] Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Tyshawn Teague-Johnson
    1.8 min over 2 stint(s), net margin +2 (+1.14/min)

[Aurora Spartans] Brock Marino, Collin Madson, Isaac Verges, Kelton McEwen, Richie Warren
    0.8 min over 1 stint(s), net margin +2 (+2.35/min)

[Simpson Storm] Austin Ambrose, Collin Madson, JR Lukenbill, Luke Bara, Richie Warren
    2.3 min over 1 stint(s), net margin +2 (+0.88/min)

[Simpson Storm] Austin Ambrose, Collin Madson, Darius Chestnut, Isaac Verges, Jake Quast
    2.4 min over 2 stint(s), net margin +2 (+0.83/min)

[Lawrence Vikings] Brock Marino, Collin Madson, Isaac Verges, Joey Berezowitz, Richie Warren
    0.6 min over 1 stint(s), net margin +2 (+3.23/min)

[St. Thomas (TX) Celts] Collin Madson, JR Lukenbill, Kelton McEwen, Luke Bara, Richie Warren
    1.9 min over 1 stint(s), net margin +2 (+1.06/min)

[Elmhurst Bluejays] Collin Madson, Isaac Verges, JR Lukenbill, Jake Quast, Richie Warren
    0.4 min over 1 stint(s), net margin +2 (+5.41/min)

[Carroll (WI) Pioneers] Collin Madson, Darius Chestnut, Isaac Verges, JR Lukenbill, Rashad Rogers
    1.6 min over 2 stint(s), net margin +2 (+1.27/min)

[Alma Scots] Agape Keyes Jr., Darius Chestnut, Isaiah Robinson, Rashad Rogers, Tyshawn Teague-Johnson
    0.3 min over 1 stint(s), net margin +2 (+7.41/min)

[UW-Oshkosh Titans] Brock Marino, Collin Madson, Jake Quast, Joey Berezowitz, Kelton McEwen
    2.4 min over 5 stint(s), net margin +2 (+0.83/min)

[Carroll (WI) Pioneers] Darius Chestnut, Isaac Verges, Jake Quast, Kelton McEwen, Rashad Rogers
    0.5 min over 1 stint(s), net margin +2 (+4.26/min)

[Coe Kohawks] Collin Madson, Jake Quast, Kelton McEwen, Luke Bara, Tyshawn Teague-Johnson
    1.3 min over 2 stint(s), net margin +2 (+1.56/min)

[Elmhurst Bluejays] Collin Madson, Darius Chestnut, Jake Quast, Joey Berezowitz, Richie Warren
    0.7 min over 1 stint(s), net margin +2 (+2.78/min)

[Carroll (WI) Pioneers] Darius Chestnut, Isaac Verges, Jake Quast, Joey Berezowitz, Rashad Rogers
    0.3 min over 2 stint(s), net margin +2 (+6.06/min)

[Coe Kohawks] Agape Keyes Jr., Isaiah Robinson, Matthew McKay, Mikey Wildes, Trent Grunewald
    2.2 min over 3 stint(s), net margin +2 (+0.92/min)

[Ripon Red Hawks] Brock Marino, Collin Madson, Darius Chestnut, Isaac Verges, Richie Warren
    1.4 min over 2 stint(s), net margin +1 (+0.70/min)

[Alma Scots] Agape Keyes Jr., Isaiah Robinson, Mauryon Turner, Rashad Rogers, Trent Grunewald
    3.1 min over 1 stint(s), net margin +1 (+0.32/min)

[Aurora Spartans] Brock Marino, Collin Madson, JR Lukenbill, Joey Berezowitz, Kelton McEwen
    2.2 min over 2 stint(s), net margin +1 (+0.45/min)

[Simpson Storm] Austin Ambrose, Collin Madson, Darius Chestnut, Isaac Verges, Richie Warren
    3.7 min over 4 stint(s), net margin +1 (+0.27/min)

[Simpson Storm] Austin Ambrose, Darius Chestnut, Isaac Verges, Kelton McEwen, Richie Warren
    1.4 min over 2 stint(s), net margin +1 (+0.74/min)

[Ripon Red Hawks] Brock Marino, Collin Madson, Darius Chestnut, Jake Quast, Joey Berezowitz
    1.2 min over 3 stint(s), net margin +1 (+0.80/min)

[Carroll (WI) Pioneers] Darius Chestnut, Jake Quast, Joey Berezowitz, Kelton McEwen, Rashad Rogers
    1.7 min over 3 stint(s), net margin +1 (+0.60/min)

[Lawrence Vikings] Brock Marino, Collin Madson, Jake Quast, Joey Berezowitz, Kelton McEwen
    2.0 min over 4 stint(s), net margin +1 (+0.49/min)

[Eureka Red Devils] Agape Keyes Jr., Isaiah Robinson, Mikey Wildes, Rashad Rogers, Trent Grunewald
    1.9 min over 2 stint(s), net margin +1 (+0.54/min)

[Simpson Storm] Isaiah Robinson, JR Lukenbill, Kelton McEwen, Luke Bara, Rashad Rogers
    2.4 min over 1 stint(s), net margin +1 (+0.42/min)

[Elmhurst Bluejays] Darius Chestnut, JR Lukenbill, Jake Quast, Joey Berezowitz, Richie Warren
    1.4 min over 2 stint(s), net margin +1 (+0.74/min)

[Coe Kohawks] Brock Marino, Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren
    9.3 min over 3 stint(s), net margin +1 (+0.11/min)

[St. Thomas (TX) Celts] Brock Marino, Collin Madson, Jake Quast, Kelton McEwen, Richie Warren
    3.3 min over 2 stint(s), net margin +1 (+0.30/min)

[Carroll (WI) Pioneers] Brock Marino, Collin Madson, JR Lukenbill, Joey Berezowitz, Kelton McEwen
    3.1 min over 5 stint(s), net margin +1 (+0.33/min)

[Ripon Red Hawks] Agape Keyes Jr., Isaac Verges, Kelton McEwen, Mauryon Turner, Rashad Rogers
    0.0 min over 1 stint(s), net margin +0 (+nan/min)

[Ripon Red Hawks] Agape Keyes Jr., Isaiah Robinson, Kelton McEwen, Mauryon Turner, Rashad Rogers
    0.9 min over 1 stint(s), net margin +0 (+0.00/min)

[UW-Oshkosh Titans] Collin Madson, JR Lukenbill, Jake Quast, Joey Berezowitz, Richie Warren
    1.2 min over 1 stint(s), net margin +0 (+0.00/min)

[Alma Scots] Isaac Verges, Jake Quast, Joey Berezowitz, Rashad Rogers, Tyshawn Teague-Johnson
    0.8 min over 1 stint(s), net margin +0 (+0.00/min)

[Aurora Spartans] Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Kelton McEwen
    0.6 min over 2 stint(s), net margin +0 (+0.00/min)

[Ripon Red Hawks] Austin Ambrose, Collin Madson, Darius Chestnut, Isaac Verges, Richie Warren
    0.1 min over 1 stint(s), net margin +0 (+0.00/min)

[Lawrence Vikings] Brock Marino, JR Lukenbill, Jake Quast, Joey Berezowitz, Luke Bara
    1.3 min over 2 stint(s), net margin +0 (+0.00/min)

[Aurora Spartans] Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
    10.2 min over 10 stint(s), net margin +0 (+0.00/min)

[Lawrence Vikings] Brock Marino, Isaiah Robinson, JR Lukenbill, Jake Quast, Kelton McEwen
    0.0 min over 1 stint(s), net margin +0 (+nan/min)

[Lawrence Vikings] Agape Keyes Jr., Brock Marino, Darius Chestnut, Isaiah Robinson, Trent Grunewald
    0.0 min over 1 stint(s), net margin +0 (+nan/min)

[Ripon Red Hawks] Austin Ambrose, Collin Madson, Darius Chestnut, Isaac Verges, Jake Quast
    0.1 min over 3 stint(s), net margin +0 (+0.00/min)

[Ripon Red Hawks] Brock Marino, Darius Chestnut, Jake Quast, Joey Berezowitz, Richie Warren
    0.9 min over 3 stint(s), net margin +0 (+0.00/min)

[Ripon Red Hawks] Austin Ambrose, Collin Madson, Darius Chestnut, JR Lukenbill, Joey Berezowitz
    0.3 min over 1 stint(s), net margin +0 (+0.00/min)

[Ripon Red Hawks] Austin Ambrose, Darius Chestnut, Jake Quast, Joey Berezowitz, Richie Warren
    3.2 min over 4 stint(s), net margin +0 (+0.00/min)

[Ripon Red Hawks] Brock Marino, Darius Chestnut, Isaac Verges, JR Lukenbill, Jake Quast


### Add minutes played onto the reconstructed box score

pbp_box_score (built above, before lineup_stints existed) aggregates scoring/rebounding/etc. events, none
of which map to a player's own on-court time by themselves -- so it never had a MIN column. lineup_stints
already reconstructs exactly that (via substitution tracking, the same 5-man units the Lineup Simulator and
Lineup Scouting features use), so minutes played per player per game is just those stint minutes summed up
for every stint that player's name appears in.

In [145]:
# --- Derive per-player minutes played from lineup_stints and merge onto pbp_box_score ------------------
# Code: parser_lib\61_add_minutes_played_onto_reconstructed_box.py  --  settings below, then the section runs.

run_section("61_add_minutes_played_onto_reconstructed_box")

Matched minutes played for 311 of 321 pbp_box_score row(s).


### Identify the lineups on court during each team's biggest scoring run

For each game's biggest scoring run (computed earlier), lists every lineup substitution either team made mid-run.

In [147]:
# --- Which lineup was on the floor for each team's biggest scoring run -------------------------------------
# Code: parser_lib\62_identify_lineups_on_court_during_each_team.py  --  settings below, then the section runs.

run_section("62_identify_lineups_on_court_during_each_team")

Lineups on the floor during each team's biggest scoring run:

[Alma Scots] Alma Scots's biggest run: 8 points (H1 09:39 (H1) -> H1 07:28 (H1))
    UWW made a substitution mid-run -- lineups on the floor: ['Jake Quast, Joey Berezowitz, Kelton McEwen, Rashad Rogers, Tyshawn Teague-Johnson', 'Isaac Verges, Jake Quast, Joey Berezowitz, Rashad Rogers, Tyshawn Teague-Johnson', 'Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren, Tyshawn Teague-Johnson']
    Alma Scots lineup on the floor the whole run: Donovan Collins, Elijah Sykes, Luciano Guerrazzi, Preston Malpass, Raine Rodich

[Alma Scots] UW-Whitewater's biggest run: 8 points (H1 07:16 (H1) -> H1 06:30 (H1))
    UWW lineup on the floor the whole run: Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren, Tyshawn Teague-Johnson
    Alma Scots lineup on the floor the whole run: Donovan Collins, Elijah Sykes, Luciano Guerrazzi, Preston Malpass, Raine Rodich

[Aurora Spartans] Aurora Spartans's biggest run: 10 points (H2 07:02 (H2) -> H2 04:24 (H2))
    UWW made a substitution mid-run -- lineups on the floor: ['Brock Marino, Collin Madson, Isaac Verges, Jake Quast, Joey Berezowitz', 'Brock Marino, Collin Madson, Isaac Verges, Jake Quast, Luke Bara']
    Aurora Spartans made a substitution mid-run -- lineups on the floor: ['Cullen Rauls, Devon Richardson, Jeffery Hillmer, Juan Madrigal, Zerrick Johnson', 'Cullen Rauls, Devon Richardson, Juan Madrigal, Mekhi Doby, Zerrick Johnson']

[Aurora Spartans] UW-Whitewater's biggest run: 13 points (H1 01:36 (H1) -> H2 18:06 (H2))
    UWW made a substitution mid-run -- lineups on the floor: ['Collin Madson, Joey Berezowitz, Kelton McEwen, Rashad Rogers, Richie Warren', 'Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara']
    Aurora Spartans made a substitution mid-run -- lineups on the floor: ['Cullen Rauls, Isaiah Thompson, Jeffery Hillmer, Juan Madrigal, Mekhi Doby', 'Isaiah Thompson, Jeffery Hillmer, Juan Madrigal, Mekhi Doby, Zerrick Johnson', 'Cullen Rauls, Devon Richardson, Jeffery Hillmer, Juan Madrigal, Mekhi Doby']

[Carroll (WI) Pioneers] Carroll (WI) Pioneers's biggest run: 8 points (H2 03:20 (H2) -> H2 01:43 (H2))
    UWW made a substitution mid-run -- lineups on the floor: ['Brock Marino, Darius Chestnut, Isaac Verges, Jake Quast, Kelton McEwen', 'Brock Marino, Collin Madson, Darius Chestnut, Isaac Verges, Jake Quast', 'Collin Madson, Darius Chestnut, Isaac Verges, Jake Quast, Richie Warren', 'Collin Madson, Isaac Verges, Jake Quast, Kelton McEwen, Richie Warren']
    Carroll (WI) Pioneers lineup on the floor the whole run: Dennis Estepp, Jacob Naber, Lamar Smith, Michael McNabb, Peyton McKenna

[Carroll (WI) Pioneers] UW-Whitewater's biggest run: 7 points (H2 11:16 (H2) -> H2 09:53 (H2))
    UWW lineup on the floor the whole run: Brock Marino, Darius Chestnut, Jake Quast, Joey Berezowitz, Kelton McEwen
    Carroll (WI) Pioneers made a substitution mid-run -- lineups on the floor: ['Cai Joseph, Jacob Naber, Jimmy Tarjan, Lamar Smith, Peyton McKenna', 'Evan Bland, Greg Smith, Lamar Smith, Michael McNabb, Peyton McKenna']

[Coe Kohawks] Coe Kohawks's biggest run: 13 points (H1 01:22 (H1) -> H2 18:18 (H2))
    UWW made a substitution mid-run -- lineups on the floor: ['Collin Madson, Darius Chestnut, JR Lukenbill, Luke Bara, Tyshawn Teague-Johnson', 'Brock Marino, Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren']
    Coe Kohawks made a substitution mid-run -- lineups on the floor: ['Austin Beeson, Cooper Nailor, Deuce Walters, Jackson Bowman, Kanyon Bryte', 'C. Reece Breitenbach, Cooper Nailor, Deuce Walters, Jackson Bowman, Kanyon Bryte']

[Coe Kohawks] UW-Whitewater's biggest run: 7 points (H2 17:14 (H2) -> H2 15:25 (H2))
    UWW made a substitution mid-run -- lineups on the floor: ['Brock Marino, Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren', 'Darius Chestnut, JR Lukenbill, Kelton McEwen, Rashad Rogers, Tyshawn Teague-Johnson']
    Coe Kohawks lineup on the floor the whole run: C. Reece Breitenbach, Cooper Nailor, Deuce Walters, Jackson Bowman, Kanyon Bryte

[Elmhurst Bluejays] Elmhurst Bluejays's biggest run: 7 points (H1 16:20 (H1) -> H1 14:22 (H1))
    UWW lineup on the floor the whole run: Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren
    Elmhurst Bluejays made a substitution mid-run -- lineups on the floor: ['Aidyn Boone, Dominic Trelenberg, Jack Cherry, Sebastian Blachut, Talen Pearson', 'Dominic Trelenberg, Jack Cherry, Jeffrey Williams, Sebastian Blachut, Talen Pearson']

[Elmhurst Bluejays] UW-Whitewater's biggest run: 10 points (H1 18:53 (H1) -> H1 16:54 (H1))
    UWW lineup on the floor the whole run: Collin Madson, Isaac Verges, Luke Bara, Rashad Rogers, Richie Warren
    Elmhurst Bluejays lineup on the floor the whole run: Aidyn Boone, Dominic Trelenberg, Luke Smith, Sebastian Blachut, Vinnie Adjahoungbeta

[Eureka Red Devils] Eureka Red Devils's biggest run: 5 points (H2 19:12 (H2) -> H2 18:32 (H2))
    UWW lineup on the floor the whole run: Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
    Eureka Red Devils lineup on the floor the whole run: Andrew Coker, Ben Carter, Colin DeLaere, Jaxson Provost, Micah Bruer

[Eureka Red Devils] UW-Whitewater's biggest run: 12 points (H1 12:55 (H1) -> H1 10:00 (H1))
    UWW made a substitution mid-run -- lineups on the floor: ['Darius Chestnut, JR Lukenbill, Jake Quast, Joey Berezowitz, Rashad Rogers', 'Darius Chestnut, Jake Quast, Joey Berezowitz, Rashad Rogers, Richie Warren']
    Eureka Red Devils made a substitution mid-run -- lineups on the floor: ['Blake Logsdon, Damuzha Moore, Jacob Gonzalez, Jonah Lauff, Max Richardson', 'Andrew Wells, Damuzha Moore, Jacob Gonzalez, Jaxson Provost, Jonah Lauff']

[Hope Flying Dutchmen] Hope Flying Dutchmen's biggest run: 14 points (H1 17:57 (H1) -> H1 16:11 (H1))
    UWW made a substitution mid-run -- lineups on the floor: ['Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren', 'Brock Marino, Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren', 'Brock Marino, Collin Madson, Jake Quast, Joey Berezowitz, Luke Bara']
    Hope Flying Dutchmen lineup on the floor the whole run: Brendan Cargill, Justice Mims, Marcus Wourman, Orion Yant, Parker Hovey

[Hope Flying Dutchmen] UW-Whitewater's biggest run: 8 points (H2 10:55 (H2) -> H2 08:04 (H2))
    UWW lineup on the floor the whole run: Collin Madson, Isaac Verges, Jake Quast, Kelton McEwen, Rashad Rogers
    Hope Flying Dutchmen made a substitution mid-run -- lineups on the floor: ['Brady Miller, Charles Howell, Marcus Wourman, Orion Yant, Simon Neuhaus', 'Brady Miller, Justice Mims, Marcus Wourman, Orion Yant, Simon Neuhaus', 'Brady Miller, Justice Mims, Marcus Wourman, Orion Yant, Parker Hovey', 'Avery Sanchez, Brady Miller, Justice Mims, Orion Yant, Parker Hovey', 'Avery Sanchez, Brady Miller, Brendan Cargill, Orion Yant, Parker Hovey']

[Lawrence Vikings] Lawrence Vikings's biggest run: 7 points (H2 16:53 (H2) -> H2 15:32 (H2))
    UWW lineup on the floor the whole run: Collin Madson, Jake Quast, Joey Berezowitz, Kelton McEwen, Rashad Rogers
    Lawrence Vikings lineup on the floor the whole run: CJ Campbell, Casey Schoenecker, Hogan Demovsky, Nathan Valentine, Nicholas Gouriotis

[Lawrence Vikings] UW-Whitewater's biggest run: 9 points (H2 07:46 (H2) -> H2 05:54 (H2))
    UWW made a substitution mid-run -- lineups on the floor: ['Collin Madson, JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton McEwen', 'Brock Marino, JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton McEwen']
    Lawrence Vikings made a substitution mid-run -- lineups on the floor: ['CJ Campbell, Casey Schoenecker, Hogan Demovsky, Matai Edgecombe, Nathan Valentine', 'Cameron Nash, Casey Schoenecker, Hogan Demovsky, Jackson Weber, Matai Edgecombe']

[Ripon Red Hawks] Ripon Red Hawks's biggest run: 10 points (H1 19:27 (H1) -> H1 16:13 (H1))
    UWW lineup on the floor the whole run: Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
    Ripon Red Hawks lineup on the floor the whole run: CJ Brown, Kolby Williams, Michael Asman, Sam Leoni, Seth Bunders

[Ripon Red Hawks] UW-Whitewater's biggest run: 7 points (H1 06:53 (H1) -> H1 05:33 (H1))
    UWW lineup on the floor the whole run: Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren
    Ripon Red Hawks lineup on the floor the whole run: CJ Brown, Jack Field, Michael Asman, Sam Leoni, Seth Bunders

[Simpson Storm] Simpson Storm's biggest run: 11 points (H2 03:02 (H2) -> H2 00:03 (H2))
    UWW made a substitution mid-run -- lineups on the floor: ['Agape Keyes Jr., Isaiah Robinson, Matthew McKay, Trent Grunewald, Tristian Lynch', 'Agape Keyes Jr., Isaiah Robinson, Mikey Wildes, Trent Grunewald, Tristian Lynch', 'Agape Keyes Jr., Isaiah Robinson, Mikey Wildes, Trent Grunewald, Zay Howard']
    Simpson Storm made a substitution mid-run -- lineups on the floor: ['Brogan Fuller, Cam Henderson, Levi Gurwell, Marcus Haupert, Seth Gipple', 'Brogan Fuller, Cam Henderson, Levi Gurwell, Logan Kowalski, Seth Gipple', 'Caleb Dyvig, Cam Henderson, Logan Kowalski, Michael Kasperbauer, Seth Gipple', 'Caleb Dyvig, Logan Kowalski, Mateo Dzolota, Michael Kasperbauer, Seth Gipple']

[Simpson Storm] UW-Whitewater's biggest run: 15 points (H2 11:15 (H2) -> H2 08:05 (H2))
    UWW made a substitution mid-run -- lineups on the floor: ['Darius Chestnut, JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton McEwen', 'Collin Madson, JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton McEwen']
    Simpson Storm made a substitution mid-run -- lineups on the floor: ['Bo Huston, Jachin Mertes, Levi Gurwell, Marcus Haupert, Spencer Holley', 'Caleb Dyvig, Cam Henderson, Jachin Mertes, Levi Gurwell, Seth Gipple', 'Brogan Fuller, Caleb Dyvig, Cam Henderson, Jachin Mertes, Levi Gurwell', 'Bo Huston, Brogan Fuller, Caleb Dyvig, Cam Henderson, Jachin Mertes', 'Bo Huston, Brogan Fuller, Caleb Dyvig, Cam Henderson, Marcus Haupert', 'Bo Huston, Brogan Fuller, Cam Henderson, Marcus Haupert, Spencer Holley']

[St. Thomas (TX) Celts] St. Thomas (TX) Celts's biggest run: 6 points (H2 13:54 (H2) -> H2 13:24 (H2))
    UWW made a substitution mid-run -- lineups on the floor: ['Brock Marino, Collin Madson, Jake Quast, Joey Berezowitz, Richie Warren', 'Collin Madson, JR Lukenbill, Jake Quast, Joey Berezowitz, Richie Warren']
    St. Thomas (TX) Celts lineup on the floor the whole run: Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Reyce Allen

[St. Thomas (TX) Celts] UW-Whitewater's biggest run: 6 points (H1 09:06 (H1) -> H1 07:35 (H1))
    UWW made a substitution mid-run -- lineups on the floor: ['Collin Madson, Jake Quast, Joey Berezowitz, Kelton McEwen, Richie Warren', 'JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton McEwen, Richie Warren']
    St. Thomas (TX) Celts lineup on the floor the whole run: Garrett Rodgers, Jaden Ross, Omar Gayle, Reyce Allen, Tamarcus Butler

[UW-Oshkosh Titans] UW-Oshkosh Titans's biggest run: 15 points (H1 14:01 (H1) -> H1 11:29 (H1))
    UWW made a substitution mid-run -- lineups on the floor: ['Brock Marino, Collin Madson, Darius Chestnut, Luke Bara, Richie Warren', 'Collin Madson, Darius Chestnut, JR Lukenbill, Jake Quast, Joey Berezowitz']
    UW-Oshkosh Titans made a substitution mid-run -- lineups on the floor: ['Aiden Hawkinson, Jonah Rindfleisch, Matt Imig, Oskar Kangas, Vitorio Dante', 'Brandon Beck, Carter Thomas, Joey LaChapell, Michael Metcalf-Grassman, Nate Nazos', 'Aiden Hawkinson, Jonah Rindfleisch, Logan Rindfleisch, Matt Imig, Oskar Kangas']

[UW-Oshkosh Titans] UW-Whitewater's biggest run: 7 points (H1 17:41 (H1) -> H1 15:06 (H1))
    UWW lineup on the floor the whole run: Brock Marino, Collin Madson, JR Lukenbill, Luke Bara, Richie Warren
    UW-Oshkosh Titans made a substitution mid-run -- lineups on the floor: ['Brandon Beck, Carter Thomas, Joey LaChapell, Michael Metcalf-Grassman, Nate Nazos', 'Aiden Hawkinson, Jay Dalton, Logan Rindfleisch, Oskar Kangas, Vitorio Dante']

                 opponent   game_date                   team  run_points  \
0              Alma Scots  2025-12-20             Alma Scots           8
1              Alma Scots  2025-12-20          UW-Whitewater           8
2         Aurora Spartans  2025-11-19        Aurora Spartans          10
3         Aurora Spartans  2025-11-19          UW-Whitewater          13
4   Carroll (WI) Pioneers  2025-12-13  Carroll (WI) Pioneers           8
5   Carroll (WI) Pioneers  2025-12-13          UW-Whitewater           7
6             Coe Kohawks  2025-12-30            Coe Kohawks          13
7             Coe Kohawks  2025-12-30          UW-Whitewater           7
8       Elmhurst Bluejays  2025-12-02      Elmhurst Bluejays           7
9       Elmhurst Bluejays  2025-12-02          UW-Whitewater          10
10      Eureka Red Devils  2025-11-15      Eureka Red Devils           5
11      Eureka Red Devils  2025-11-15          UW-Whitewater          12
12   Hope Flying Dutchmen  2025-12-19   Hope Flying Dutchmen          14
13   Hope Flying Dutchmen  2025-12-19          UW-Whitewater           8
14       Lawrence Vikings  2025-12-10       Lawrence Vikings           7
15       Lawrence Vikings  2025-12-10          UW-Whitewater           9
16        Ripon Red Hawks  2025-11-07        Ripon Red Hawks          10
17        Ripon Red Hawks  2025-11-07          UW-Whitewater           7
18          Simpson Storm  2025-11-25          Simpson Storm          11
19          Simpson Storm  2025-11-25          UW-Whitewater          15
20  St. Thomas (TX) Celts  2025-11-14  St. Thomas (TX) Celts           6
21  St. Thomas (TX) Celts  2025-11-14          UW-Whitewater           6
22      UW-Oshkosh Titans  2026-01-03      UW-Oshkosh Titans          15
23      UW-Oshkosh Titans  2026-01-03          UW-Whitewater           7

    start_event_order  end_event_order
0                 104              138
1                 140              147
2                 390              420
3                 228              252
4                 449              477
5                 359              376
6                 194              224
7                 232              254
8                  30               46
9                   6               22
10                255              264
11                 93              119
12                 24               50
13                385              420
14                300              313
15                408              427
16                  5               31
17                149              168
18                500              539
19                359              417
20                280              287
21                 99              111
22                100              156
23                 39               79


### Season-wide 5-man lineup analysis across all games

Combines the lineup-stint data (minutes, margin) across every game played so far into one season-wide view of UWW's most-used and most-effective 5-man combinations.

In [149]:
# --- Season-wide UWW 5-man lineup analysis, combining minutes/margin across ALL games played so far -----------
# Code: parser_lib\63_season_wide_5_man_lineup_analysis_across.py  --  settings below, then the section runs.
MEANINGFUL_MIN_MINUTES = 2.0

run_section("63_season_wide_5_man_lineup_analysis_across")

Season-wide UWW 5-man lineups across 12 game(s) with play-by-play data (163 distinct lineups used):

Most-used lineups overall (by total minutes on the floor):

                                                                uww_lineup  games                                                              opponents  stints  total_minutes  net_margin  margin_per_min
47     Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren      6  [Alma Scots, Carroll (WI) Pioneers, Elmhurst Bluejays, Hope Flying...      30          50.43         2.0            0.04
39      Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara      4  [Aurora Spartans, Eureka Red Devils, Ripon Red Hawks, St. Thomas (...      23          36.97         4.0            0.11
115   Collin Madson, Isaac Verges, Luke Bara, Rashad Rogers, Richie Warren      3               [Elmhurst Bluejays, Hope Flying Dutchmen, Simpson Storm]       9          13.82         3.0            0.22
142  Darius Chestnut, JR Lukenbill, Jake Quast, Kelton McEwen, Tyshawn ...      1                                                          [Coe Kohawks]       7          12.58         9.0            0.72
63   Brock Marino, Collin Madson, Joey Berezowitz, Luke Bara, Richie Wa...      5  [Alma Scots, Aurora Spartans, Coe Kohawks, Elmhurst Bluejays, Hope...       9          12.34        -4.0           -0.32
53     Brock Marino, Collin Madson, JR Lukenbill, Luke Bara, Richie Warren      1                                                    [UW-Oshkosh Titans]      16          11.21         4.0            0.36
104       Collin Madson, Isaac Verges, JR Lukenbill, Jake Quast, Luke Bara      2                                   [Aurora Spartans, Elmhurst Bluejays]      17          10.14        10.0            0.99
55   Brock Marino, Collin Madson, Jake Quast, Joey Berezowitz, Kelton M...      5  [Alma Scots, Carroll (WI) Pioneers, Hope Flying Dutchmen, Lawrence...      16          10.12         1.0            0.10
116  Collin Madson, JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton M...      3                   [Elmhurst Bluejays, Lawrence Vikings, Simpson Storm]      13           9.61        24.0            2.50
123  Collin Madson, Jake Quast, Joey Berezowitz, Kelton McEwen, Rashad ...      2                              [Carroll (WI) Pioneers, Lawrence Vikings]      10           8.84         4.0            0.45

  ... 153 more row(s) of 163 (SHOW_ROWS = 10)

Best net-margin-per-minute UWW lineups season-wide (min 2.0 minutes played):

                                                                uww_lineup  games                                              opponents  stints  total_minutes  net_margin  margin_per_min
95   Collin Madson, Darius Chestnut, JR Lukenbill, Luke Bara, Richie Wa...      1                                        [Simpson Storm]       3           2.80        11.0            3.93
98   Collin Madson, Darius Chestnut, Jake Quast, Joey Berezowitz, Richi...      2             [Elmhurst Bluejays, St. Thomas (TX) Celts]       3           2.04         7.0            3.43
66   Brock Marino, Collin Madson, Kelton McEwen, Mauryon Turner, Richie...      1                                    [Eureka Red Devils]       3           3.04         9.0            2.96
116  Collin Madson, JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton M...      3   [Elmhurst Bluejays, Lawrence Vikings, Simpson Storm]      13           9.61        24.0            2.50
139  Darius Chestnut, JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton...      1                                        [Simpson Storm]       4           2.46         5.0            2.03
74   Brock Marino, Darius Chestnut, Jake Quast, Joey Berezowitz, Richie...      3  [Aurora Spartans, Eureka Red Devils, Ripon Red Hawks]       9           4.64         9.0            1.94
33   Brock Marino, Collin Madson, Darius Chestnut, Jake Quast, Joey Ber...      2                   [Elmhurst Bluejays, Ripon Red Hawks]       6           2.10         4.0            1.90
73   Brock Marino, Darius Chestnut, Jake Quast, Joey Berezowitz, Kelton...      1                                [Carroll (WI) Pioneers]       2           2.85         5.0            1.75
83      Brock Marino, JR Lukenbill, Jake Quast, Joey Berezowitz, Luke Bara      2                  [Eureka Red Devils, Lawrence Vikings]       4           4.17         7.0            1.68
147  Darius Chestnut, Jake Quast, Joey Berezowitz, Rashad Rogers, Richi...      1                                    [Eureka Red Devils]       4           5.90         9.0            1.53

  ... 60 more row(s) of 70 (SHOW_ROWS = 10)

Worst net-margin-per-minute UWW lineups season-wide (min 2.0 minutes played):

                                                                uww_lineup  games                                                              opponents  stints  total_minutes  net_margin  margin_per_min
56     Brock Marino, Collin Madson, Jake Quast, Joey Berezowitz, Luke Bara      3                 [Coe Kohawks, Elmhurst Bluejays, Hope Flying Dutchmen]       4           2.41       -10.0           -4.15
101  Collin Madson, Darius Chestnut, Luke Bara, Rashad Rogers, Richie W...      1                                                 [Hope Flying Dutchmen]       2           2.28        -7.0           -3.07
111      Collin Madson, Isaac Verges, Jake Quast, Luke Bara, Richie Warren      2                          [Hope Flying Dutchmen, St. Thomas (TX) Celts]       2           2.00        -4.0           -2.00
35   Brock Marino, Collin Madson, Darius Chestnut, Luke Bara, Richie Wa...      3                       [Alma Scots, Aurora Spartans, UW-Oshkosh Titans]       7           7.29       -13.0           -1.78
117  Collin Madson, JR Lukenbill, Jake Quast, Joey Berezowitz, Richie W...      2                             [St. Thomas (TX) Celts, UW-Oshkosh Titans]       3           4.19        -6.0           -1.43
61   Brock Marino, Collin Madson, Joey Berezowitz, Kelton McEwen, Richi...      3             [Aurora Spartans, Carroll (WI) Pioneers, Lawrence Vikings]       5           2.18        -3.0           -1.38
42        Brock Marino, Collin Madson, Isaac Verges, Jake Quast, Luke Bara      4  [Aurora Spartans, Elmhurst Bluejays, Eureka Red Devils, St. Thomas...       6           6.03        -8.0           -1.33
28   Austin Ambrose, JR Lukenbill, Jake Quast, Joey Berezowitz, Richie ...      1                                                [St. Thomas (TX) Celts]       4           2.63        -3.0           -1.14
156  JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton McEwen, Tyshawn ...      1                                                          [Coe Kohawks]       2           2.90        -3.0           -1.03
110      Collin Madson, Isaac Verges, Jake Quast, Luke Bara, Rashad Rogers      2                          [Carroll (WI) Pioneers, Hope Flying Dutchmen]       3           2.00        -2.0           -1.00

  ... 60 more row(s) of 70 (SHOW_ROWS = 10)

Lineups that have appeared in MORE than one game (38):
                                                                           uww_lineup  \
47                Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren
63             Brock Marino, Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren
55            Brock Marino, Collin Madson, Jake Quast, Joey Berezowitz, Kelton McEwen
39                 Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
125              Collin Madson, Jake Quast, Joey Berezowitz, Luke Bara, Richie Warren
124          Collin Madson, Jake Quast, Joey Berezowitz, Kelton McEwen, Richie Warren
42                   Brock Marino, Collin Madson, Isaac Verges, Jake Quast, Luke Bara
132  Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren, Tyshawn Teague-Johnson
74          Brock Marino, Darius Chestnut, Jake Quast, Joey Berezowitz, Richie Warren
61         Brock Marino, Collin Madson, Joey Berezowitz, Kelton McEwen, Richie Warren
56                Brock Marino, Collin Madson, Jake Quast, Joey Berezowitz, Luke Bara
35             Brock Marino, Collin Madson, Darius Chestnut, Luke Bara, Richie Warren
116           Collin Madson, JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton McEwen
115              Collin Madson, Isaac Verges, Luke Bara, Rashad Rogers, Richie Warren
38             Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Kelton McEwen
44          Brock Marino, Collin Madson, Isaac Verges, Joey Berezowitz, Richie Warren
103            Collin Madson, Isaac Verges, JR Lukenbill, Jake Quast, Joey Berezowitz
88            Collin Madson, Darius Chestnut, Isaac Verges, Jake Quast, Rashad Rogers
41               Brock Marino, Collin Madson, Isaac Verges, Jake Quast, Kelton McEwen
111                 Collin Madson, Isaac Verges, Jake Quast, Luke Bara, Richie Warren
110                 Collin Madson, Isaac Verges, Jake Quast, Luke Bara, Rashad Rogers
57            Brock Marino, Collin Madson, Jake Quast, Joey Berezowitz, Richie Warren
98         Collin Madson, Darius Chestnut, Jake Quast, Joey Berezowitz, Richie Warren
33          Brock Marino, Collin Madson, Darius Chestnut, Jake Quast, Joey Berezowitz
119        Collin Madson, JR Lukenbill, Joey Berezowitz, Kelton McEwen, Rashad Rogers
83                 Brock Marino, JR Lukenbill, Jake Quast, Joey Berezowitz, Luke Bara
16           Austin Ambrose, Collin Madson, Darius Chestnut, Isaac Verges, Jake Quast
82             Brock Marino, JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton McEwen
120            Collin Madson, JR Lukenbill, Joey Berezowitz, Luke Bara, Richie Warren
17        Austin Ambrose, Collin Madson, Darius Chestnut, Isaac Verges, Richie Warren
117           Collin Madson, JR Lukenbill, Jake Quast, Joey Berezowitz, Richie Warren
107               Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara, Richie Warren
99          Collin Madson, Darius Chestnut, Joey Berezowitz, Luke Bara, Richie Warren
30             Brock Marino, Collin Madson, Darius Chestnut, Isaac Verges, Jake Quast
50          Brock Marino, Collin Madson, JR Lukenbill, Joey Berezowitz, Kelton McEwen
123          Collin Madson, Jake Quast, Joey Berezowitz, Kelton McEwen, Rashad Rogers
104                  Collin Madson, Isaac Verges, JR Lukenbill, Jake Quast, Luke Bara
106              Collin Madson, Isaac Verges, JR Lukenbill, Jake Quast, Richie Warren

     games  \
47       6
63       5
55       5
39       4
125      4
124      4
42       4
132      3
74       3
61       3
56       3
35       3
116      3
115      3
38       2
44       2
103      2
88       2
41       2
111      2
110      2
57       2
98       2
33       2
119      2
83       2
16       2
82       2
120      2
17       2
117      2
107      2
99       2
30       2
50       2
123      2
104      2
106      2

                                                                                                           opponents  \
47   [Alma Scots, Carroll (WI) Pioneers, Elmhurst Bluejays, Hope Flying Dutchmen, Lawrence Vikings, Ripon Red Hawks]
63                               [Alma Scots, Aurora Spartans, Coe Kohawks, Elmhurst Bluejays, Hope Flying Dutchmen]
55                    [Alma Scots, Carroll (WI) Pioneers, Hope Flying Dutchmen, Lawrence Vikings, UW-Oshkosh Titans]
39                                      [Aurora Spartans, Eureka Red Devils, Ripon Red Hawks, St. Thomas (TX) Celts]
125                                       [Coe Kohawks, Elmhurst Bluejays, St. Thomas (TX) Celts, UW-Oshkosh Titans]
124                                  [Elmhurst Bluejays, Lawrence Vikings, St. Thomas (TX) Celts, UW-Oshkosh Titans]
42                                    [Aurora Spartans, Elmhurst Bluejays, Eureka Red Devils, St. Thomas (TX) Celts]
132                                                                     [Alma Scots, Coe Kohawks, UW-Oshkosh Titans]
74                                                             [Aurora Spartans, Eureka Red Devils, Ripon Red Hawks]
61                                                        [Aurora Spartans, Carroll (WI) Pioneers, Lawrence Vikings]
56                                                            [Coe Kohawks, Elmhurst Bluejays, Hope Flying Dutchmen]
35                                                                  [Alma Scots, Aurora Spartans, UW-Oshkosh Titans]
116                                                             [Elmhurst Bluejays, Lawrence Vikings, Simpson Storm]
115                                                         [Elmhurst Bluejays, Hope Flying Dutchmen, Simpson Storm]
38                                                                              [Aurora Spartans, Eureka Red Devils]
44                                                                               [Aurora Spartans, Lawrence Vikings]
103                                                                            [Elmhurst Bluejays, Lawrence Vikings]
88                                                                            [Carroll (WI) Pioneers, Simpson Storm]
41                                                                     [Carroll (WI) Pioneers, Hope Flying Dutchmen]
111                                                                    [Hope Flying Dutchmen, St. Thomas (TX) Celts]
110                                                                    [Carroll (WI) Pioneers, Hope Flying Dutchmen]
57                                                                        [St. Thomas (TX) Celts, UW-Oshkosh Titans]
98                                                                        [Elmhurst Bluejays, St. Thomas (TX) Celts]
33                                                                              [Elmhurst Bluejays, Ripon Red Hawks]
119                                                                                 [Aurora Spartans, Simpson Storm]
83                                                                             [Eureka Red Devils, Lawrence Vikings]
16                                                                                  [Ripon Red Hawks, Simpson Storm]
82                                                                         [Carroll (WI) Pioneers, Lawrence Vikings]
120                                                                           [Elmhurst Bluejays, UW-Oshkosh Titans]
17                                                                                  [Ripon Red Hawks, Simpson Storm]
117                                                                       [St. Thomas (TX) Celts, UW-Oshkosh Titans]
107                                                                       [Elmhurst Bluejays, St. Thomas (TX) Celts]
99                                                                                   [Alma Scots, UW-Oshkosh Titans]
30                                                                          [Carroll (WI) Pioneers, Ripon Red Hawks]
50                                                                          [Aurora Spartans, Carroll (WI) Pioneers]
123                                                                        [Carroll (WI) Pioneers, Lawrence Vikings]
104                                                                             [Aurora Spartans, Elmhurst Bluejays]
106                                                                       [Elmhurst Bluejays, St. Thomas (TX) Celts]

     stints  total_minutes  net_margin  margin_per_min
47       30          50.43         2.0            0.04
63        9          12.34        -4.0           -0.32
55       16          10.12         1.0            0.10
39       23          36.97         4.0            0.11
125      11           5.12         3.0            0.59
124       7           7.48         9.0            1.20
42        6           6.03        -8.0           -1.33
132       8           6.89        -6.0           -0.87
74        9           4.64         9.0            1.94
61        5           2.18        -3.0           -1.38
56        4           2.41       -10.0           -4.15
35        7           7.29       -13.0           -1.78
116      13           9.61        24.0            2.50
115       9          13.82         3.0            0.22
38        3           0.95        -2.0           -2.11
44        2           1.72         2.0            1.16
103       2           1.78         4.0            2.25
88        3           0.79        -2.0           -2.53
41        4           1.90         5.0            2.63
111       2           2.00        -4.0           -2.00
110       3           2.00        -2.0           -1.00
57        4           2.02        -2.0           -0.99
98        3           2.04         7.0            3.43
33        6           2.10         4.0            1.90
119       4           1.42         3.0            2.11
83        4           4.17         7.0            1.68
16        5           2.53         2.0            0.79
82        4           2.87         0.0            0.00
120       3           3.08        -1.0           -0.32
17        5           3.77         1.0            0.27
117       3           4.19        -6.0           -1.43
107       3           4.28        -3.0           -0.70
99       13           4.77         1.0            0.21
30        5           5.20        -5.0           -0.96
50        7           5.30         2.0            0.38
123      10           8.84         4.0            0.45
104      17          10.14        10.0            0.99
106       2           0.42         2.0            4.76

UWW's starting (tip-off) lineup, by game:
                 opponent   game_date  \
0              Alma Scots  2025-12-20
1         Aurora Spartans  2025-11-19
2   Carroll (WI) Pioneers  2025-12-13
3             Coe Kohawks  2025-12-30
4       Elmhurst Bluejays  2025-12-02
5       Eureka Red Devils  2025-11-15
6    Hope Flying Dutchmen  2025-12-19
7        Lawrence Vikings  2025-12-10
8         Ripon Red Hawks  2025-11-07
9           Simpson Storm  2025-11-25
10  St. Thomas (TX) Celts  2025-11-14
11      UW-Oshkosh Titans  2026-01-03

                                                           starting_lineup
0      Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren
1       Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
2      Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren
3   Brock Marino, Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren
4     Collin Madson, Isaac Verges, Luke Bara, Rashad Rogers, Richie Warren
5       Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
6      Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren
7      Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren
8       Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
9     Collin Madson, Isaac Verges, Luke Bara, Rashad Rogers, Richie Warren
10      Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
11     Brock Marino, Collin Madson, JR Lukenbill, Luke Bara, Richie Warren

Starting five has changed across games -- 5 different starting combinations used over 12 game(s).

Distinct UWW 5-man combinations used, by game:
                 opponent   game_date  distinct_lineups_used
0              Alma Scots  2025-12-20                     15
1         Aurora Spartans  2025-11-19                     20
2   Carroll (WI) Pioneers  2025-12-13                     21
3             Coe Kohawks  2025-12-30                     14
4       Elmhurst Bluejays  2025-12-02                     17
5       Eureka Red Devils  2025-11-15                     19
6    Hope Flying Dutchmen  2025-12-19                     23
7        Lawrence Vikings  2025-12-10                     19
8         Ripon Red Hawks  2025-11-07                     18
9           Simpson Storm  2025-11-25                     22
10  St. Thomas (TX) Celts  2025-11-14                     20
11      UW-Oshkosh Titans  2026-01-03                     18


### UWW performance vs. opponent lineup profile and video-tagged play types, season-wide

Merges lineup stints with each opponent lineup's scouting-tag classification (Starter/Bench role mix) to see how UWW's net margin varies against different opponent lineup profiles, season-wide.

In [151]:
# --- UWW performance vs. OPPONENT lineup profile, and video-tagged PLAY TYPES -- both season-wide -------------
# Code: parser_lib\64_uww_performance_vs_opponent_lineup_profile.py  --  settings below, then the section runs.

run_section("64_uww_performance_vs_opponent_lineup_profile")

UWW's season-wide net margin by OPPONENT lineup role composition (Starter/Bench mix on the floor):

                opp_role_bucket  stints  total_minutes  net_margin_for_uww  \
2  Starter-heavy (4-5 starters)     202         209.18                47.0
1          Mixed (2-3 starters)     232         174.67                66.0
3   Unknown (no scouting match)     121          81.60                13.0
0    Bench-heavy (0-1 starters)      22           9.67                15.0

   margin_per_min
2            0.22
1            0.38
3            0.16
0            1.55

UWW's season-wide net margin by the OPPONENT lineup's dominant scouted playing style (a lineup can count toward more than one tag):

        opp_style_tags  stints  total_minutes  net_margin_for_uww  \
7  three_point_shooter     442         364.47               132.0
6       slasher_driver     412         343.32               115.0
3          post_scorer     181         157.80                75.0
2            playmaker      87          80.63               -28.0
1           high_usage      65          71.77                 2.0
5            rebounder      61          50.04                20.0
4      pull_up_shooter      44          48.94                13.0
0      catch_and_shoot      54          38.27                 5.0

   margin_per_min
7            0.36
6            0.33
3            0.48
2           -0.35
1            0.03
5            0.40
4            0.27
0            0.13

UWW's video-tagged shot-attempt play types, season-wide (691 video-matched attempts across 12 game(s)):

            play_type  attempts  makes  fg_pct
9             Spot-Up       205     80    39.0
10         Transition       122     71    58.2
6    P&R Ball Handler        80     34    42.5
8             Post-Up        63     33    52.4
0                 Cut        58     37    63.8
2                 ISO        48     26    54.2
4          Off Screen        35     12    34.3
5   Offensive Rebound        29     26    89.7
7        P&R Roll Man        22     11    50.0
1            Hand Off        21     10    47.6
3        No Play Type         8      4    50.0

For the top 5 most-attempted play types, which UWW lineup ran them most:

      play_type  \
5           Cut
8           Cut
19          Cut
29          Cut
3           Cut
..          ...
406  Transition
407  Transition
408  Transition
409  Transition
410  Transition

                                                                            uww_lineup  \
5                  Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren
8                  Brock Marino, Collin Madson, JR Lukenbill, Luke Bara, Richie Warren
19                    Collin Madson, Isaac Verges, JR Lukenbill, Jake Quast, Luke Bara
29    Darius Chestnut, JR Lukenbill, Jake Quast, Kelton McEwen, Tyshawn Teague-Johnson
3                   Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara
..                                                                                 ...
406         Darius Chestnut, Jake Quast, Joey Berezowitz, Rashad Rogers, Richie Warren
407            JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton McEwen, Richie Warren
408                JR Lukenbill, Jake Quast, Joey Berezowitz, Luke Bara, Richie Warren
409  Jake Quast, Joey Berezowitz, Kelton McEwen, Rashad Rogers, Tyshawn Teague-Johnson
410               Jake Quast, Joey Berezowitz, Luke Bara, Rashad Rogers, Richie Warren

     attempts  makes  fg_pct
5          12      3    25.0
8           3      2    66.7
19          3      3   100.0
29          3      3   100.0
3           2      2   100.0
..        ...    ...     ...
406         1      1   100.0
407         1      1   100.0
408         1      0     0.0
409         1      1   100.0
410         1      1   100.0

[284 rows x 5 columns]

UWW's video-tagged play-type efficiency by individual player, season-wide (every player/play-type combination with at least one attempt):

             player          play_type  attempts  makes  fg_pct
4   Agape Keyes Jr.            Spot-Up         4      1    25.0
5   Agape Keyes Jr.         Transition         4      1    25.0
0   Agape Keyes Jr.       No Play Type         1      1   100.0
1   Agape Keyes Jr.         Off Screen         1      0     0.0
2   Agape Keyes Jr.  Offensive Rebound         1      0     0.0
3   Agape Keyes Jr.   P&R Ball Handler         1      0     0.0
9    Austin Ambrose            Post-Up         3      2    66.7
10   Austin Ambrose            Spot-Up         2      1    50.0
6    Austin Ambrose                Cut         1      1   100.0
7    Austin Ambrose       No Play Type         1      0     0.0
8    Austin Ambrose       P&R Roll Man         1      0     0.0
16     Brock Marino            Post-Up        27     15    55.6
15     Brock Marino       P&R Roll Man        13      7    53.8
11     Brock Marino                Cut         9      3    33.3
17     Brock Marino            Spot-Up         9      5    55.6

  ... 97 more row(s) of 112 (SHOW_ROWS = 15)

Per-player summary -- overall video-tagged volume/efficiency plus each player's single most-used play type, season-wide:

                    player  total_attempts  total_makes  overall_fg_pct  \
3            Collin Madson             121           75            62.0
11               Luke Bara              84           33            39.3
16           Richie Warren              81           33            40.7
2             Brock Marino              69           39            56.5
8               Jake Quast              58           28            48.3
5             Isaac Verges              56           29            51.8
4          Darius Chestnut              40           22            55.0
10           Kelton McEwen              36           13            36.1
7             JR Lukenbill              33           19            57.6
9          Joey Berezowitz              30           14            46.7
19  Tyshawn Teague-Johnson              21           12            57.1
15           Rashad Rogers              17            9            52.9
0          Agape Keyes Jr.              12            3            25.0
6          Isaiah Robinson               9            6            66.7
1           Austin Ambrose               8            4            50.0
17         Trent Grunewald               6            1            16.7
13          Mauryon Turner               3            2            66.7
18          Tristian Lynch               3            1            33.3
20              Zay Howard               2            0             0.0
14            Mikey Wildes               1            0             0.0
12           Matthew McKay               1            1           100.0

   most_used_play_type  attempts_of_that_type  makes_of_that_type
3     P&R Ball Handler                     28                  17
11             Spot-Up                     25                  15
16             Spot-Up                     25                   3
2              Post-Up                     27                  15
8              Spot-Up                     22                   9
5           Transition                     15                  10
4              Spot-Up                     19                   7
10             Spot-Up                     16                   5
7              Spot-Up                     16                   7
9              Spot-Up                     13                   4
19             Spot-Up                      8                   6
15             Post-Up                      7                   4
0              Spot-Up                      4                   1
6           Transition                      4                   4
1              Post-Up                      3                   2
17             Post-Up                      3                   1
13          Transition                      2                   2
18            Hand Off                      1                   0
20    P&R Ball Handler                      1                   0
14    P&R Ball Handler                      1                   0
12   Offensive Rebound                      1                   1

Starters vs. Bench: overall video-tagged shooting, season-wide:

      role  attempts  makes  fg_pct
0    Bench       280    133    47.5
1  Starter       411    211    51.3

Starters vs. Bench shooting, broken down by play type, season-wide:

       role          play_type  attempts  makes  fg_pct
9     Bench            Spot-Up       106     39    36.8
10    Bench         Transition        59     35    59.3
0     Bench                Cut        24     17    70.8
6     Bench   P&R Ball Handler        21      7    33.3
8     Bench            Post-Up        18      6    33.3
2     Bench                ISO        13      7    53.8
5     Bench  Offensive Rebound        13     11    84.6
4     Bench         Off Screen        10      6    60.0
1     Bench           Hand Off         6      1    16.7
7     Bench       P&R Roll Man         6      3    50.0
3     Bench       No Play Type         4      1    25.0
20  Starter            Spot-Up        99     41    41.4
21  Starter         Transition        63     36    57.1
17  Starter   P&R Ball Handler        59     27    45.8
19  Starter            Post-Up        45     27    60.0
13  Starter                ISO        35     19    54.3
11  Starter                Cut        34     20    58.8
15  Starter         Off Screen        25      6    24.0
16  Starter  Offensive Rebound        16     15    93.8
18  Starter       P&R Roll Man        16      8    50.0
12  Starter           Hand Off        15      9    60.0
14  Starter       No Play Type         4      3    75.0


### Diagnose Spot-Up struggles: shot quality vs. shooter-specific

Breaks UWW's season-wide Spot-Up shooting down by shot mechanic (catch-and-shoot vs. pull-up vs. drive) and by contest level (guarded vs. open), to see whether struggles are about shot quality/shot selection rather than any one shooter.

In [153]:
# --- Diagnosing UWW's Spot-Up struggles: is it shot QUALITY (contested/long attempts) or SHOOTER-specific? ----
# Code: parser_lib\65_diagnose_spot_up_struggles.py  --  settings below, then the section runs.
UNCLASSIFIED_SHOT_MECHANIC = "Unclassified (no mechanic tag)"
NO_CONTEST_TAG = "Not tagged (contest recorded only on catch-and-shoot)"

run_section("65_diagnose_spot_up_struggles")

Spot-Up shot-quality breakdown, season-wide (205 video-matched attempts):

By shot mechanic:

             shot_mechanic  attempts  makes  fg_pct
0          Catch-and-shoot       130     53    40.8
1      Drive to the basket        48     21    43.8
2  Pull-up off the dribble        27      6    22.2

By contest level:

                                                 contest  attempts  makes  fg_pct
1  Not tagged (contest recorded only on catch-and-shoot)        75     27    36.0
0                                                Guarded        73     29    39.7
2                                                   Open        57     24    42.1

By shot distance:

            distance  attempts  makes  fg_pct
0           Long/3pt       137     56    40.9
2                N/A        48     21    43.8
3     Short to < 17'        12      3    25.0
1  Medium/17' to <3p         8      0     0.0

Catch-and-shoot Spot-Up jumpers only (130 attempts) -- contest x distance:

   contest           distance  attempts  makes  fg_pct
0  Guarded           Long/3pt        73     29    39.7
1     Open           Long/3pt        54     24    44.4
2     Open  Medium/17' to <3p         3      0     0.0

Per-player Spot-Up volume/efficiency, with their catch-and-shoot% and guarded% of those attempts:
                    player  attempts  makes  fg_pct  pct_catch_and_shoot  \
13           Richie Warren        25      3    12.0                 48.0
11               Luke Bara        25     15    60.0                 76.0
3            Collin Madson        24     13    54.2                 50.0
8               Jake Quast        22      9    40.9                 45.5
4          Darius Chestnut        19      7    36.8                 73.7
10           Kelton McEwen        16      5    31.2                 81.2
7             JR Lukenbill        16      7    43.8                 75.0
5             Isaac Verges        14      2    14.3                 64.3
9          Joey Berezowitz        13      4    30.8                 84.6
2             Brock Marino         9      5    55.6                 33.3
16  Tyshawn Teague-Johnson         8      6    75.0                 37.5
6          Isaiah Robinson         4      2    50.0                 75.0
0          Agape Keyes Jr.         4      1    25.0                 75.0
1           Austin Ambrose         2      1    50.0                100.0
14         Trent Grunewald         2      0     0.0                100.0
12           Rashad Rogers         1      0     0.0                100.0
15          Tristian Lynch         1      0     0.0                100.0

    pct_guarded
13         16.0
11         56.0
3          37.5
8          27.3
4          21.1
10         50.0
7          43.8
5          21.4
9          38.5
2          33.3
16         12.5
6           0.0
0          75.0
1         100.0
14        100.0
12        100.0
15        100.0


### Check contest/mechanic patterns across ALL play types, not just Spot-Up

Extends the same shot-mechanic/contest-level breakdown from the cell above beyond Spot-Up, to every play type -- checking whether the same pattern holds more broadly or is specific to Spot-Up situations.

In [155]:
# --- Does the guarded/open contest pattern hold for catch-and-shoot jumpers on NON-SPOT-UP play types too? ----
# Code: parser_lib\66_check_contest_mechanic_patterns_across_all.py  --  settings below, then the section runs.

run_section("66_check_contest_mechanic_patterns_across_all")

ALL catch-and-shoot jumpers, every play type, season-wide (198 attempts):

Which play types produce catch-and-shoot jumpers, and their efficiency:

          play_type  attempts  makes  fg_pct
5           Spot-Up       130     53    40.8
6        Transition        28     12    42.9
2        Off Screen        27      9    33.3
4      P&R Roll Man         6      2    33.3
0          Hand Off         3      0     0.0
1      No Play Type         2      1    50.0
3  P&R Ball Handler         2      0     0.0

Guarded vs. Open, ALL catch-and-shoot jumpers (every play type combined), season-wide:

   contest  attempts  makes  fg_pct
0  Guarded       108     38    35.2
1     Open        90     39    43.3

Guarded vs. Open catch-and-shoot jumpers, by player, ALL play types combined, season-wide:
                    player  guarded_attempts  guarded_makes  guarded_fg_pct  \
10               Luke Bara              21.0            9.0            42.9
9            Kelton McEwen              18.0            5.0            27.8
3            Collin Madson              15.0            6.0            40.0
4          Darius Chestnut               6.0            3.0            50.0
6             JR Lukenbill               7.0            2.0            28.6
8          Joey Berezowitz               6.0            3.0            50.0
12           Richie Warren               5.0            1.0            20.0
7               Jake Quast               6.0            3.0            50.0
5             Isaac Verges               3.0            0.0             0.0
0          Agape Keyes Jr.               4.0            1.0            25.0
2             Brock Marino               5.0            3.0            60.0
16         Isaiah Robinson               NaN            NaN             NaN
1           Austin Ambrose               3.0            1.0            33.3
11           Rashad Rogers               3.0            0.0             0.0
13         Trent Grunewald               3.0            0.0             0.0
15  Tyshawn Teague-Johnson               1.0            1.0           100.0
14          Tristian Lynch               2.0            0.0             0.0

    open_attempts  open_makes  open_fg_pct  total_attempts
10           13.0         6.0         46.2            34.0
9             6.0         4.0         66.7            24.0
3             8.0         5.0         62.5            23.0
4            13.0         6.0         46.2            19.0
6             9.0         4.0         44.4            16.0
8             9.0         4.0         44.4            15.0
12            9.0         0.0          0.0            14.0
7             6.0         2.0         33.3            12.0
5             8.0         2.0         25.0            11.0
0             3.0         1.0         33.3             7.0
2             NaN         NaN          NaN             5.0
16            4.0         3.0         75.0             4.0
1             NaN         NaN          NaN             3.0
11            NaN         NaN          NaN             3.0
13            NaN         NaN          NaN             3.0
15            2.0         2.0        100.0             3.0
14            NaN         NaN          NaN             2.0

Non-catch-and-shoot attempts (drives, pull-ups, post moves, etc.), by play type and mechanic:

            play_type                    shot_mechanic  attempts  makes  fg_pct
18         Transition              Drive to the basket        80     54    67.5
0                 Cut                Cut to the basket        58     37    63.8
16            Spot-Up              Drive to the basket        48     21    43.8
11   P&R Ball Handler          Pull-up off the dribble        41     18    43.9
15            Post-Up                          Post-up        39     18    46.2
10   P&R Ball Handler              Drive to the basket        37     16    43.2
9   Offensive Rebound  Putback off the offensive glass        29     26    89.7
17            Spot-Up          Pull-up off the dribble        27      6    22.2
3                 ISO              Drive to the basket        26     16    61.5
14            Post-Up              Drive to the basket        24     15    62.5
4                 ISO          Pull-up off the dribble        22     10    45.5
19         Transition          Pull-up off the dribble        14      5    35.7
1            Hand Off              Drive to the basket        13      6    46.2
13       P&R Roll Man   Unclassified (no mechanic tag)         9      5    55.6
12       P&R Roll Man              Drive to the basket         7      4    57.1

  ... 5 more row(s) of 20 (SHOW_ROWS = 15)


### Contest-level (guarded vs. open) Spot-Up breakdown for all shooters

Same guarded-vs-open contest breakdown as the flagged-player diagnosis, but run across every shooter on the roster rather than just the one player originally flagged.

In [157]:
# --- Same contest-level breakdown as the flagged-player note above, generalized to EVERY shooter with Spot-Up
# Code: parser_lib\67_contest_level.py  --  settings below, then the section runs.

run_section("67_contest_level")

Spot-Up shooting by player and contest level, season-wide (every player/contest combination with at least one attempt):

                    player  \
0          Agape Keyes Jr.
1          Agape Keyes Jr.
2           Austin Ambrose
4             Brock Marino
3             Brock Marino
6            Collin Madson
5            Collin Madson
7            Collin Madson
10         Darius Chestnut
9          Darius Chestnut
8          Darius Chestnut
13            Isaac Verges
12            Isaac Verges
11            Isaac Verges
15         Isaiah Robinson
14         Isaiah Robinson
16            JR Lukenbill
18            JR Lukenbill
17            JR Lukenbill
20              Jake Quast
19              Jake Quast
21              Jake Quast
24         Joey Berezowitz
22         Joey Berezowitz
23         Joey Berezowitz
25           Kelton McEwen
27           Kelton McEwen
26           Kelton McEwen
28               Luke Bara
29               Luke Bara
30               Luke Bara
31           Rashad Rogers
33           Richie Warren
34           Richie Warren
32           Richie Warren
35         Trent Grunewald
36          Tristian Lynch
38  Tyshawn Teague-Johnson
39  Tyshawn Teague-Johnson
37  Tyshawn Teague-Johnson

                                                  contest  attempts  makes  \
0                                                 Guarded         3      1
1   Not tagged (contest recorded only on catch-and-shoot)         1      0
2                                                 Guarded         2      1
4   Not tagged (contest recorded only on catch-and-shoot)         6      3
3                                                 Guarded         3      2
6   Not tagged (contest recorded only on catch-and-shoot)        12      7
5                                                 Guarded         9      4
7                                                    Open         3      2
10                                                   Open        10      4
9   Not tagged (contest recorded only on catch-and-shoot)         5      1
8                                                 Guarded         4      2
13                                                   Open         6      1
12  Not tagged (contest recorded only on catch-and-shoot)         5      1
11                                                Guarded         3      0
15                                                   Open         3      2
14  Not tagged (contest recorded only on catch-and-shoot)         1      0
16                                                Guarded         7      2
18                                                   Open         5      3
17  Not tagged (contest recorded only on catch-and-shoot)         4      2
20  Not tagged (contest recorded only on catch-and-shoot)        12      4
19                                                Guarded         6      3
21                                                   Open         4      2
24                                                   Open         6      2
22                                                Guarded         5      2
23  Not tagged (contest recorded only on catch-and-shoot)         2      0
25                                                Guarded         8      2
27                                                   Open         5      3
26  Not tagged (contest recorded only on catch-and-shoot)         3      0
28                                                Guarded        14      9
29  Not tagged (contest recorded only on catch-and-shoot)         6      3
30                                                   Open         5      3
31                                                Guarded         1      0
33  Not tagged (contest recorded only on catch-and-shoot)        13      3
34                                                   Open         8      0
32                                                Guarded         4      0
35                                                Guarded         2      0
36                                                Guarded         1      0
38  Not tagged (contest recorded only on catch-and-shoot)         5      3
39                                                   Open         2      2
37                                                Guarded         1      1

    fg_pct
0     33.3
1      0.0
2     50.0
4     50.0
3     66.7
6     58.3
5     44.4
7     66.7
10    40.0
9     20.0
8     50.0
13    16.7
12    20.0
11     0.0
15    66.7
14     0.0
16    28.6
18    60.0
17    50.0
20    33.3
19    50.0
21    50.0
24    33.3
22    40.0
23     0.0
25    25.0
27    60.0
26     0.0
28    64.3
29    50.0
30    60.0
31     0.0
33    23.1
34     0.0
32     0.0
35     0.0
36     0.0
38    60.0
39   100.0
37   100.0

Guarded vs. Open Spot-Up shooting side-by-side, by player (season-wide):

                    player  guarded_attempts  guarded_makes  guarded_fg_pct  \
10               Luke Bara              14.0            9.0            64.3
4          Darius Chestnut               4.0            2.0            50.0
9            Kelton McEwen               8.0            2.0            25.0
3            Collin Madson               9.0            4.0            44.4
6             JR Lukenbill               7.0            2.0            28.6
12           Richie Warren               4.0            0.0             0.0
8          Joey Berezowitz               5.0            2.0            40.0
7               Jake Quast               6.0            3.0            50.0
5             Isaac Verges               3.0            0.0             0.0
15  Tyshawn Teague-Johnson               1.0            1.0           100.0
0          Agape Keyes Jr.               3.0            1.0            33.3
2             Brock Marino               3.0            2.0            66.7
16         Isaiah Robinson               NaN            NaN             NaN
1           Austin Ambrose               2.0            1.0            50.0
13         Trent Grunewald               2.0            0.0             0.0
11           Rashad Rogers               1.0            0.0             0.0
14          Tristian Lynch               1.0            0.0             0.0

    open_attempts  open_makes  open_fg_pct  total_attempts
10            5.0         3.0         60.0            19.0
4            10.0         4.0         40.0            14.0
9             5.0         3.0         60.0            13.0
3             3.0         2.0         66.7            12.0
6             5.0         3.0         60.0            12.0
12            8.0         0.0          0.0            12.0
8             6.0         2.0         33.3            11.0
7             4.0         2.0         50.0            10.0
5             6.0         1.0         16.7             9.0
15            2.0         2.0        100.0             3.0
0             NaN         NaN          NaN             3.0
2             NaN         NaN          NaN             3.0
16            3.0         2.0         66.7             3.0
1             NaN         NaN          NaN             2.0
13            NaN         NaN          NaN             2.0
11            NaN         NaN          NaN             1.0
14            NaN         NaN          NaN             1.0

### Coaching Flag: contested Spot-Up 3PT rate

**Season-wide (video-tagged data):** review the `player_contest` and `contest_compare` output above for any
player whose Spot-Up attempts skew heavily toward guarded catch-and-shoot looks with little or no open volume.
A skew like this may not reflect poor shooting on the contested look itself (compare the guarded FG% to that
player's season 3P%) -- the flag is more about shot-diet allocation: has he logged any OPEN catch-and-shoot
looks at all this season, or has every attempt come standstill against a set defense.

**Recommendation for coaching staff:** where this pattern shows up, review off-ball actions (relocation,
screens, drive-and-kick reads) to spring that player for easier looks. Treat as a small-sample signal -- 
re-check as more games are logged. (See the structured `coaching_flags_df` a few cells below for the
rule-based, automatically-updating version of this check across the full roster.)


### Investigate why guarded catch-and-shoot jumpers outperform open ones

Digs into the counter-intuitive pattern flagged in the previous note -- guarded catch-and-shoot attempts showing a higher make rate than open ones -- to determine whether it's a real effect or a small-sample artifact.

In [160]:
# --- Why might GUARDED catch-and-shoot jumpers outperform OPEN ones, season-wide? ---------------------------
# Code: parser_lib\68_investigate_why_guarded_catch_and_shoot.py  --  settings below, then the section runs.

run_section("68_investigate_why_guarded_catch_and_shoot")

Two-proportion z-test, Guarded (35.2%, n=108) vs. Open (43.3%, n=90): z=-1.17, p-value=0.242
(p > 0.05 means this gap is NOT statistically distinguishable from random chance at this sample size)

Guarded vs. Open catch-and-shoot FG%, broken out by game:

                 opponent   game_date  contest  attempts  makes  fg_pct
0              Alma Scots  2025-12-20  Guarded         3      1    33.3
1              Alma Scots  2025-12-20     Open        13      8    61.5
2         Aurora Spartans  2025-11-19  Guarded         4      1    25.0
3         Aurora Spartans  2025-11-19     Open        12      5    41.7
4   Carroll (WI) Pioneers  2025-12-13  Guarded        13      3    23.1
5   Carroll (WI) Pioneers  2025-12-13     Open         5      0     0.0
6             Coe Kohawks  2025-12-30  Guarded        12      3    25.0
7             Coe Kohawks  2025-12-30     Open         2      0     0.0
8       Elmhurst Bluejays  2025-12-02  Guarded         3      2    66.7
9       Elmhurst Bluejays  2025-12-02     Open         8      1    12.5
10      Eureka Red Devils  2025-11-15  Guarded         8      4    50.0
11      Eureka Red Devils  2025-11-15     Open        16      9    56.2
12   Hope Flying Dutchmen  2025-12-19  Guarded         7      2    28.6
13   Hope Flying Dutchmen  2025-12-19     Open         5      3    60.0
14       Lawrence Vikings  2025-12-10  Guarded        21      8    38.1

  ... 9 more row(s) of 24 (SHOW_ROWS = 15)

Average SEASON-LONG 3P% of the shooter taking the shot, by contest level (catch-and-shoot 3s only) -- tests whether the defense keys on UWW's better shooters, inflating the Guarded bucket's shooter-quality mix relative to Open:

   contest  attempts  avg_shooter_season_3p_pct
0  Guarded       106                       36.2
1     Open        85                       38.7

### Correction: "Guarded beats Open" is NOT a real team-wide pattern

An earlier pass through this notebook noted that UWW's catch-and-shoot jumpers were hitting at a higher rate
when **guarded** than when **open**, across every play type combined. The investigation above shows this does
**not** reliably hold up as a real tactical signal:

* **Check statistical significance** -- the two-proportion z-test above will show whether a gap this size is
  distinguishable from random chance at the current sample size (re-run as more games are logged; with only a
  few dozen total attempts, most gaps will not be significant).
* **Check whether it's driven by one specific game** -- the `by_game` breakdown above shows whether the pattern
  holds consistently across every logged game, or is really just one cold/hot shooting night skewing the total.
* **Check for a shooter-quality confound** -- the `quality_by_contest` breakdown compares the season-long 3P%
  of the shooters taking Guarded vs. Open looks; if Open shooters actually have a *higher* average season 3P%,
  that's evidence AGAINST guarded shots being intrinsically "better", not for it.

**Takeaway:** treat any aggregate "guarded > open" figure with suspicion until it clears all three checks above.
It should not be cited as evidence that contested shots are preferable to open ones -- individual player
patterns stand on their own volume/allocation evidence, not on this kind of small-sample team-wide claim.
Re-check once more games are logged and the sample grows.


### Structured coaching flags & recommendations database, per player

Consolidates every diagnosis surfaced above (Spot-Up quality, contest-level patterns, and the corrected guarded/open finding) into one structured, per-player table of coaching flags and recommendations.

**Season-stat flags (FG%/3P%/FT%/PPG/MPG/GP-GS) no longer leak games from after reference_date.** They previously read straight from `stats` -- FastScout's live cumulative season-stats page -- which has no date granularity at all and reflects the season total at scrape time. Caught via a real example: Brock Marino's free-throw flag showed "~112 attempts" even though `reference_date` is 2025-11-15 -- 112 FTA across 28 games is a near-full-season total, not something that could have happened by mid-November. These rules now read from `season_asof`, rebuilt from `pbp_box_score`'s real per-game lines and totalled only over games before `reference_date` (that restriction already exists upstream, in the "Play-by-play (PBP) data" cell). The tradeoff: a player whose early games weren't PBP-logged now shows a thinner (or empty) pre-reference-date sample instead of a precise-looking full-season number -- the correct tradeoff for a pre-game report. Team roster membership (names/jersey numbers) is unaffected -- that isn't the same kind of leak as a performance number, so it's still read from the season-stats page.

**Confidence is computed from real sample size, not a fixed label.** Every flag used to carry one of two hardcoded confidence strings -- "High (season-long sample)" on every season-stat-based flag, "Medium (small sample...)" on every per-shot one -- regardless of how many actual attempts backed the number. `confidence_label()` now computes an honest tier (Low/Medium/High) from the real attempt count behind each figure, and a flag whose sample is too thin to mean anything is suppressed rather than shown with false confidence.

**Role no longer falls back to a leaky data source.** An earlier version filled in role "Unknown" for a player with no PBP data by falling back to the season-stats page's GP-GS column -- but that page has the same reference_date leak described above, so that fallback was removed. A player with no PBP-tagged games before reference_date genuinely has an unknown role as of that date, and "Unknown" is the honest answer. Role sort order was also fixed to put Starters first, Bench second, Unknown last, instead of relying on alphabetical string order.

**The generic "seeing the floor" catch-all is a little less generic.** It previously read almost identically for a heavy-minutes rotation player and a deep-bench one -- now includes season PPG (as of reference_date) and splits the framing by usage level.

In [163]:
# --- Structured coaching-flags DATABASE: one row per (player, flag) -- replaces one-off markdown notes and
# Code: parser_lib\69_structured_coaching_flags_recommendations.py  --  settings below, then the section runs.
MIN_ATTEMPTS_TO_FLAG = 5  # absolute floor: below this, a season FG%/3P%/FT% flag doesn't fire at all

run_section("69_structured_coaching_flags_recommendations")

Coaching flags database: 35 flag(s) across 22 player(s) (full roster: 22).
21 of 22 players have at least one Positive flag.
All season-stat rules (FG%/3P%/FT%/PPG/MPG/GP-GS) are now built from pbp_box_score restricted to game_date < reference_date (2026-1-7), not the ungated season-to-date page -- 1 of 22 rostered player(s) have no play-by-play data at all before reference_date and fall back to the 'no data yet' flag rather than a leaked full-season number.

Name reconciliation applied via KNOWN_NAME_ALIASES where the play-by-play spelling and the official season-stats spelling of a player's name differ.

,player,player_key,role,sentiment,category,flag,evidence,recommendation,confidence
6,Brock Marino,brock marino,Starter,Positive,Play-type efficiency,Efficient secondary action: Offensive Rebound,5-for-5 (100%) on Offensive Rebound this season.,"A reliable look worth calling more often, even if not his primary ...","Low (n=5 Offensive Rebound attempts -- small sample, re-check as m..."
5,Brock Marino,brock marino,Starter,Negative,Free-throw shooting,Below-average free-throw shooter with meaningful attempt volume,48.3% FT this season -- 28-for-58 over 11 games (5.3 attempts a ga...,Target free-throw shooting in individual workouts -- meaningful at...,"High (n=58 FT attempts, season-long sample)"
7,Collin Madson,collin madson,Starter,Positive,Play-type efficiency,Efficient secondary action: Cut,3-for-3 (100%) on Cut this season.,"A reliable look worth calling more often, even if not his primary ...","Low (n=3 Cut attempts -- small sample, re-check as more games are ..."
11,Isaac Verges,isaac verges,Starter,Positive,Play-type efficiency,Efficient secondary action: Offensive Rebound,4-for-4 (100%) on Offensive Rebound this season.,"A reliable look worth calling more often, even if not his primary ...","Low (n=4 Offensive Rebound attempts -- small sample, re-check as m..."
10,Isaac Verges,isaac verges,Starter,Negative,Shooting efficiency,Missing predominantly OPEN catch-and-shoot looks,2-for-8 (25%) on open catch-and-shoot attempts this season -- belo...,"Since these are UNCONTESTED misses, treat as a shooting-mechanics/...",Medium (n=8 open catch-and-shoot attempts)
17,JR Lukenbill,jr lukenbill,Starter,Positive,Play-type efficiency,Efficient secondary action: Cut,6-for-6 (100%) on Cut this season.,"A reliable look worth calling more often, even if not his primary ...",Medium (n=6 Cut attempts)
16,JR Lukenbill,jr lukenbill,Starter,Negative,Free-throw shooting,Below-average free-throw shooter with meaningful attempt volume,50.0% FT this season -- 5-for-10 over 10 games (1.0 attempts a game).,Target free-throw shooting in individual workouts -- meaningful at...,Medium (n=10 FT attempts)
15,Joey Berezowitz,joey berezowitz,Starter,Positive,Play-type efficiency,Efficient secondary action: Cut,2-for-3 (67%) on Cut this season.,"A reliable look worth calling more often, even if not his primary ...","Low (n=3 Cut attempts -- small sample, re-check as more games are ..."
20,Luke Bara,luke bara,Starter,Positive,Play-type efficiency,Efficient secondary action: Hand Off,3-for-4 (75%) on Hand Off this season.,"A reliable look worth calling more often, even if not his primary ...","Low (n=4 Hand Off attempts -- small sample, re-check as more games..."
25,Rashad Rogers,rashad rogers,Starter,Positive,Play-type efficiency,Efficient secondary action: Transition,2-for-3 (67%) on Transition this season.,"A reliable look worth calling more often, even if not his primary ...","Low (n=3 Transition attempts -- small sample, re-check as more gam..."
24,Rashad Rogers,rashad rogers,Starter,Negative,Shot selection,Shot diet skewed heavily toward contested catch-and-shoot looks,"0-for-3 (0%) on guarded catch-and-shoot attempts this season, vs. ...",Design more actions to create separation before the catch (relocat...,"Low (n=3 catch-and-shoot attempts -- small sample, re-check as mor..."
28,Richie Warren,richie warren,Starter,Positive,Play-type efficiency,Efficient secondary action: Transition,4-for-5 (80%) on Transition this season.,"A reliable look worth calling more often, even if not his primary ...","Low (n=5 Transition attempts -- small sample, re-check as more gam..."
27,Richie Warren,richie warren,Starter,Negative,Play-type efficiency,Struggles specifically in his most-used action (Spot-Up),3-for-25 (12%) on Spot-Up -- his single most-attempted action this...,"Reduce reliance on Spot-Up as his primary look, or work on the spe...",Medium (n=25 Spot-Up attempts)
26,Richie Warren,richie warren,Starter,Negative,Shooting efficiency,Missing predominantly OPEN catch-and-shoot looks,0-for-9 (0%) on open catch-and-shoot attempts this season -- below...,"Since these are UNCONTESTED misses, treat as a shooting-mechanics/...",Medium (n=9 open catch-and-shoot attempts)
2,Agape Keyes Jr.,agape keyes jr.,Bench,Positive,Season shooting,Respectable 3-point shooter this season,"42.9% 3PT this season (0.5-1.2 per game, 7 attempts).",Worth designing catch-and-shoot looks for him specifically.,"Low (n=7 3PT attempts -- small sample, re-check as more games are ..."

  ... 20 more row(s) of 35 (SHOW_ROWS = 15)


### Expected box score for the upcoming game

Projects an expected box score for the next scouted opponent, combining UWW's season performance, the opponent's own lineup/tendency profile, and the coaching flags database above.

In [165]:
# --- Expected box score for the upcoming game (Elmhurst) ------------------------------------------------------
# Code: parser_lib\70_expected_box_score_for_upcoming_game.py  --  settings below, then the section runs.
UPCOMING_MATCHUP_OPPONENT = upcoming_opponent_short

run_section("70_expected_box_score_for_upcoming_game")

Projected final score: UW-Whitewater 77 - UW-Stevens Point Pointers 76 (margin +1)
  UWW inputs: season PTS/gm=78.4, actual PTS/gm vs scouted opponents=75.0
  UW-Stevens Point Pointers inputs: PBP-derived PTS/gm=75.2, UWW's actual PTS/gm allowed to scouted opponents=75.8

UW-Stevens Point Pointers projected team total: 0.0 pts (scaled from a 60% own-season-average / 40% comp-actual-game blend)
Empty DataFrame
Columns: [name, jersey_number, role, position, MIN, projected_PTS, projected_REB, projected_AST, comp_used, comp_from_game, similarity_score, projection_basis]
Index: []

UW-Whitewater projected team total: 76.7 pts (season averages scaled x0.84 for pace/matchup)
                     opponent   game_date                  PLAYER   MIN  \
0   UW-Stevens Point Pointers  Wed, Jan 7           Collin Madson  33.0
1   UW-Stevens Point Pointers  Wed, Jan 7               Luke Bara  24.0
2   UW-Stevens Point Pointers  Wed, Jan 7            Isaac Verges  23.0
3   UW-Stevens Point Pointers  Wed, Jan 7            Brock Marino  21.0
4   UW-Stevens Point Pointers  Wed, Jan 7           Richie Warren  22.0
5   UW-Stevens Point Pointers  Wed, Jan 7              Jake Quast  16.0
6   UW-Stevens Point Pointers  Wed, Jan 7  Tyshawn Teague-Johnson  11.0
7   UW-Stevens Point Pointers  Wed, Jan 7         Darius Chestnut  10.0
8   UW-Stevens Point Pointers  Wed, Jan 7           Kelton McEwen  11.0
9   UW-Stevens Point Pointers  Wed, Jan 7         Joey Berezowitz  14.0
10  UW-Stevens Point Pointers  Wed, Jan 7            JR Lukenbill  13.0
11  UW-Stevens Point Pointers  Wed, Jan 7          Austin Ambrose   9.0
12  UW-Stevens Point Pointers  Wed, Jan 7           Rashad Rogers   9.0
13  UW-Stevens Point Pointers  Wed, Jan 7         Agape Keyes Jr.   4.0
14  UW-Stevens Point Pointers  Wed, Jan 7           Matthew McKay   2.0
15  UW-Stevens Point Pointers  Wed, Jan 7         Maurquis Turner   3.0
16  UW-Stevens Point Pointers  Wed, Jan 7         Isaiah Robinson   8.0
17  UW-Stevens Point Pointers  Wed, Jan 7          Tristian Lynch   4.0
18  UW-Stevens Point Pointers  Wed, Jan 7         Trent Grunewald   4.0
19  UW-Stevens Point Pointers  Wed, Jan 7              Zay Howard   1.0
20  UW-Stevens Point Pointers  Wed, Jan 7            Mikey Wildes   2.0
21  UW-Stevens Point Pointers  Wed, Jan 7          Mauryon Turner   NaN
22  UW-Stevens Point Pointers  Wed, Jan 7          Spencer Cullum   NaN

    projected_PTS  projected_REB  projected_AST    FG%    3P%    FT%  \
0            15.2            5.4            1.1  55.6%  45.3%  80.4%
1             8.6            1.6            1.3  38.7%  37.3%  89.7%
2             8.3            4.4            1.9  52.5%  37.5%  71.6%
3             7.5            5.4            0.6  52.3%  34.6%  53.2%
4             7.3            4.9            1.1  43.2%    25%    65%
5             5.2            2.9            0.6  51.4%  31.2%  64.9%
6             3.5            2.0            0.3  42.9%  38.9%  36.4%
7             3.0            1.1            0.3  51.1%    50%  64.3%
8             3.0            0.3            0.5  41.7%  39.6%  65.4%
9             2.9            1.2            1.4  49.3%  44.4%  91.7%
10            2.4            1.7            0.6  45.9%  33.3%  54.5%
11            2.4            1.8            0.1    45%    20%  33.3%
12            1.9            2.1            0.5  48.5%  28.6%  69.2%
13            1.3            0.2            0.2    25%  42.9%      -
14            1.1            0.7            0.0   100%      -     0%
15            1.1            0.3            0.0  66.7%      -     0%
16            0.9            0.5            0.6  33.3%  23.1%    50%
17            0.8            0.5            0.0  33.3%     0%      -
18            0.3            1.3            0.3  14.3%     0%      -
19            0.0            0.0            0.3     0%     0%      -
20            0.0            0.2            0.2     0%      -      -
21            NaN            NaN            NaN      -      -      -
22            NaN            NaN            NaN      -      -      -

                                                                                                                                                                                                            projection_basis
0   Own season avg: 18.0 PTS, 5.4 REB, 1.1 AST/gm over 33 min | Scaled x0.84 for this matchup's projected pace (UWW projected team total 77 pts: 50% season PPG 78.4 + 50% actual PPG vs scouted opponents this season 75.0)
1   Own season avg: 10.2 PTS, 1.6 REB, 1.3 AST/gm over 24 min | Scaled x0.84 for this matchup's projected pace (UWW projected team total 77 pts: 50% season PPG 78.4 + 50% actual PPG vs scouted opponents this season 75.0)
2    Own season avg: 9.8 PTS, 4.4 REB, 1.9 AST/gm over 23 min | Scaled x0.84 for this matchup's projected pace (UWW projected team total 77 pts: 50% season PPG 78.4 + 50% actual PPG vs scouted opponents this season 75.0)
3    Own season avg: 8.9 PTS, 5.4 REB, 0.6 AST/gm over 21 min | Scaled x0.84 for this matchup's projected pace (UWW projected team total 77 pts: 50% season PPG 78.4 + 50% actual PPG vs scouted opponents this season 75.0)
4    Own season avg: 8.7 PTS, 4.9 REB, 1.1 AST/gm over 22 min | Scaled x0.84 for this matchup's projected pace (UWW projected team total 77 pts: 50% season PPG 78.4 + 50% actual PPG vs scouted opponents this season 75.0)
5    Own season avg: 6.2 PTS, 2.9 REB, 0.6 AST/gm over 16 min | Scaled x0.84 for this matchup's projected pace (UWW projected team total 77 pts: 50% season PPG 78.4 + 50% actual PPG vs scouted opponents this season 75.0)
6    Own season avg: 4.2 PTS, 2.0 REB, 0.3 AST/gm over 11 min | Scaled x0.84 for this matchup's projected pace (UWW projected team total 77 pts: 50% season PPG 78.4 + 50% actual PPG vs scouted opponents this season 75.0)
7    Own season avg: 3.6 PTS, 1.1 REB, 0.3 AST/gm over 10 min | Scaled x0.84 for this matchup's projected pace (UWW projected team total 77 pts: 50% season PPG 78.4 + 50% actual PPG vs scouted opponents this season 75.0)
8    Own season avg: 3.5 PTS, 0.3 REB, 0.5 AST/gm over 11 min | Scaled x0.84 for this matchup's projected pace (UWW projected team total 77 pts: 50% season PPG 78.4 + 50% actual PPG vs scouted opponents this season 75.0)
9    Own season avg: 3.4 PTS, 1.2 REB, 1.4 AST/gm over 14 min | Scaled x0.84 for this matchup's projected pace (UWW projected team total 77 pts: 50% season PPG 78.4 + 50% actual PPG vs scouted opponents this season 75.0)
10   Own season avg: 2.9 PTS, 1.7 REB, 0.6 AST/gm over 13 min | Scaled x0.84 for this matchup's projected pace (UWW projected team total 77 pts: 50% season PPG 78.4 + 50% actual PPG vs scouted opponents this season 75.0)
11    Own season avg: 2.8 PTS, 1.8 REB, 0.1 AST/gm over 9 min | Scaled x0.84 for this matchup's projected pace (UWW projected team total 77 pts: 50% season PPG 78.4 + 50% actual PPG vs scouted opponents this season 75.0)
12    Own season avg: 2.3 PTS, 2.1 REB, 0.5 AST/gm over 9 min | Scaled x0.84 for this matchup's projected pace (UWW projected team total 77 pts: 50% season PPG 78.4 + 50% actual PPG vs scouted opponents this season 75.0)
13    Own season avg: 1.5 PTS, 0.2 REB, 0.2 AST/gm over 4 min | Scaled x0.84 for this matchup's projected pace (UWW projected team total 77 pts: 50% season PPG 78.4 + 50% actual PPG vs scouted opponents this season 75.0)
14    Own season avg: 1.3 PTS, 0.7 REB, 0.0 AST/gm over 2 min | Scaled x0.84 for this matchup's projected pace (UWW projected team total 77 pts: 50% season PPG 78.4 + 50% actual PPG vs scouted opponents this season 75.0)
15    Own season avg: 1.3 PTS, 0.3 REB, 0.0 AST/gm over 3 min | Scaled x0.84 for this matchup's projected pace (UWW projected team total 77 pts: 50% season PPG 78.4 + 50% actual PPG vs scouted opponents this season 75.0)
16    Own season avg: 1.1 PTS, 0.5 REB, 0.6 AST/gm over 8 min | Scaled x0.84 for this matchup's projected pace (UWW projected team total 77 pts: 50% season PPG 78.4 + 50% actual PPG vs scouted opponents this season 75.0)
17    Own season avg: 1.0 PTS, 0.5 REB, 0.0 AST/gm over 4 min | Scaled x0.84 for this matchup's projected pace (UWW projected team total 77 pts: 50% season PPG 78.4 + 50% actual PPG vs scouted opponents this season 75.0)
18    Own season avg: 0.3 PTS, 1.3 REB, 0.3 AST/gm over 4 min | Scaled x0.84 for this matchup's projected pace (UWW projected team total 77 pts: 50% season PPG 78.4 + 50% actual PPG vs scouted opponents this season 75.0)
19    Own season avg: 0.0 PTS, 0.0 REB, 0.3 AST/gm over 1 min | Scaled x0.84 for this matchup's projected pace (UWW projected team total 77 pts: 50% season PPG 78.4 + 50% actual PPG vs scouted opponents this season 75.0)
20    Own season avg: 0.0 PTS, 0.2 REB, 0.2 AST/gm over 2 min | Scaled x0.84 for this matchup's projected pace (UWW projected team total 77 pts: 50% season PPG 78.4 + 50% actual PPG vs scouted opponents this season 75.0)
21                                                                                                                                             No season stats recorded for this player yet -- insufficient data to project.
22                                                                                                                                             No season stats recorded for this player yet -- insufficient data to project.

UW-Stevens Point Pointers's pre-game keys to victory: n/a
UW-Stevens Point Pointers's team strengths: n/a

Coaching flags on UWW's top-5 projected scorers:
  [Positive] Brock Marino -- Efficient secondary action: Offensive Rebound (5-for-5 (100%) on Offensive Rebound this season.)
  [Negative] Brock Marino -- Below-average free-throw shooter with meaningful attempt volume (48.3% FT this season -- 28-for-58 over 11 games (5.3 attempts a game).)
  [Positive] Collin Madson -- Efficient secondary action: Cut (3-for-3 (100%) on Cut this season.)
  [Positive] Isaac Verges -- Efficient secondary action: Offensive Rebound (4-for-4 (100%) on Offensive Rebound this season.)
  [Negative] Isaac Verges -- Missing predominantly OPEN catch-and-shoot looks (2-for-8 (25%) on open catch-and-shoot attempts this season -- below his season 3P% of 27.3%.)
  [Positive] Luke Bara -- Efficient secondary action: Hand Off (3-for-4 (75%) on Hand Off this season.)
  [Positive] Richie Warren -- Efficient secondary action: Transition (4-for-5 (80%) on Transition this season.)
  [Negative] Richie Warren -- Struggles specifically in his most-used action (Spot-Up) (3-for-25 (12%) on Spot-Up -- his single most-attempted action this season, well below his overall shooting split.)
  [Negative] Richie Warren -- Missing predominantly OPEN catch-and-shoot looks (0-for-9 (0%) on open catch-and-shoot attempts this season -- below his season 3P% of 8.3%.)


### Export tables as CSVs into the app's bundled data directory

Writes every table this notebook produces (schedule, box scores, scouting reports, PBP/lineup analytics, player comparisons, coaching flags, etc.) out as CSVs into `OUTPUT_DIR`, for the Streamlit app to read.


### Reconstruct a box score for the opponent's games before facing UWW

The shot-by-shot video-tagged data for these games already exists (pbp_events_upcoming, built above, and
already exported as uww_opponent_prior_games_pbp for the shot-selection analysis) -- this just aggregates
it into a per-player box score, the exact same way uww_pbp_box_score already does for UWW's own games
(same event_type -> stat mapping, same groupby). This is what lets the app's Last Five Games page show a
full box score when a coach clicks one of the opponent's own results, not just UWW's.

In [168]:
# --- Reconstruct a box score from pbp_events_upcoming, same event_type -> stat mapping as pbp_box_score ---
# Code: parser_lib\71_reconstruct_box_score_for_opponent_games.py  --  settings below, then the section runs.

run_section("71_reconstruct_box_score_for_opponent_games")

Added 7 synthetic TEAM row(s) for 9 bare team-level turnover(s) in the upcoming opponent's prior game(s).
Reconstructed box score for 13 of the upcoming opponent's prior game(s), 305 player-game row(s) total.


### Minutes played for the upcoming opponent's prior games

Reuses the lineup reconstruction and stints already built two cells up (`self_lineup`/`their_lineup`,
`stint_src`, `stints`, `minutes_margin`) instead of redoing that same substitution-tracking pass a second
time -- an earlier version of this cell duplicated that whole algorithm from scratch under different
column names, which was pure waste and a real risk of the two copies quietly drifting apart over time.
`stints`/`minutes_margin` above only cover the upcoming opponent's OWN lineups (that's all the season-box
cell needed); the one genuinely new piece here is doing the same for `their_lineup` (whichever third party
they played each game), so both sides of `pbp_box_score_upcoming` get a MIN column, not just one.

In [170]:
# --- Minutes played for BOTH sides of the upcoming opponent's prior games, reusing cell above's work --------
# Code: parser_lib\72_minutes_played_for_upcoming_opponent_prior.py  --  settings below, then the section runs.

run_section("72_minutes_played_for_upcoming_opponent_prior")

Matched minutes played for 297 of 305 pbp_box_score_upcoming row(s).
Starters detected for 13 of UW-Stevens Point Pointers's prior game(s).


### Replace the upcoming opponent's PDF-scouting-report stats with PBP-derived ones

player_profiles' PTS/REB/AST/etc for a scouted opponent normally come from that opponent's own scouting-
report PDF (a static document, captured once). For the CURRENT upcoming opponent specifically, `pbp_box_
score_upcoming` now holds a fully reconstructed box score for every one of their games before facing UWW --
the exact same games `reference_date` scopes everything else in this notebook to. Overriding their
player_profiles stats with an aggregate of THAT instead makes those numbers correctly reference-date-aware,
the same way everything else already had to be fixed to be.

**Scope, explicitly**: this only replaces the CURRENT upcoming opponent's stats. For an opponent UWW has
ALREADY PLAYED, the only PBP data this notebook has for them is their single game against UWW (from
pbp_box_score) -- not a season's worth of games. Using that as a season-stat substitute would trade one
real problem (a stale PDF snapshot) for a different one (a single noisy game standing in for a season
average), silently. Already-played opponents keep their PDF-sourced stats for now -- a genuine, open
limitation, not something this cell quietly papers over.

In [172]:
# --- Override the upcoming opponent's player_profiles stats with a PBP-derived aggregate ---------------------
# Code: parser_lib\73_replace_upcoming_opponent_pdf_scouting.py  --  settings below, then the section runs.

run_section("73_replace_upcoming_opponent_pdf_scouting")

Replaced PDF-sourced stats with PBP-derived stats for 0 of 0 UW-Stevens Point Pointers player_profiles row(s), from 13 prior game(s) of PBP data.
  Added 19 PBP-only player(s) with no scout-report entry at all (role=Bench): ['Austin Schaumburg', 'Brandon Tilley', 'Cal Krohn', 'Carter Combs', 'Drew Daoust', 'Dylan Taylor', 'Emmitt Huhn', 'Grant Manz', 'Isaiah Moore', 'James Jacobs', 'Josh Bocher', 'Josiah Butler', 'Logan Baumgartner', 'Max Raimer', 'Nick Fox', 'Seth Miron', 'Shane Tarjan', 'Tyler Orr', 'Zach Orr']
  Also added 19 of them to all_rosters (uww_opponent_rosters) so they appear in the app's ROSTER panel, not just the team-stat sums.

  Roster names for UW-Stevens Point Pointers (19): ['Austin Schaumburg', 'Brandon Tilley', 'Cal Krohn', 'Carter Combs', 'Drew Daoust', 'Dylan Taylor', 'Emmitt Huhn', 'Grant Manz', 'Isaiah Moore', 'James Jacobs', 'Josh Bocher', 'Josiah Butler', 'Logan Baumgartner', 'Max Raimer', 'Nick Fox', 'Seth Miron', 'Shane Tarjan', 'Tyler Orr', 'Zach Orr']
  PBP-derived names found (19): ['Austin Schaumburg', 'Brandon Tilley', 'Cal Krohn', 'Carter Combs', 'Drew Daoust', 'Dylan Taylor', 'Emmitt Huhn', 'Grant Manz', 'Isaiah Moore', 'James Jacobs', 'Josh Bocher', 'Josiah Butler', 'Logan Baumgartner', 'Max Raimer', 'Nick Fox', 'Seth Miron', 'Shane Tarjan', 'Tyler Orr', 'Zach Orr']
  Per-player PTS after this override (spot-check against what the app is showing):

C:\Users\frits\OneDrive\Documents\GitHub\uwwmensbball\parser\parser_lib\73_replace_upcoming_opponent_pdf_scouting.py:127: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  player_profiles = pd.concat(

                  name   PTS
142      Josiah Butler  16.5
133          Cal Krohn  15.8
146         Seth Miron  15.2
143  Logan Baumgartner   9.4
141        Josh Bocher   7.8
139       Isaiah Moore   5.8
134       Carter Combs   5.4
144         Max Raimer   4.1
138         Grant Manz   2.3
132     Brandon Tilley   2.0
135        Drew Daoust   1.5
148          Tyler Orr   0.7
140       James Jacobs   0.4
147       Shane Tarjan   0.2
131  Austin Schaumburg   0.0

  ... 4 more row(s) of 19 (SHOW_ROWS = 15)


### Replace the upcoming opponent's TEAM totals with PBP-derived ones too

`team_totals` (team_ppg / opp_ppg_allowed, exported as uww_opponent_team_totals) has the exact same problem
the player-level override two cells up already fixed: `extract_team_totals_from_pdf` reads a "Team Total"
row straight off the same static scouting-report PDF, with no reference_date awareness at all. Same fix,
same scope limit: only the CURRENT upcoming opponent gets overridden, using `pbp_box_score_upcoming`'s own
"TEAM"/per-player rows for their games before facing UWW.

In [174]:
# --- Override the upcoming opponent's team_totals (PPG / opponent-PPG-allowed) with a PBP-derived aggregate --
# Code: parser_lib\74_replace_upcoming_opponent_team_totals_with.py  --  settings below, then the section runs.

run_section("74_replace_upcoming_opponent_team_totals_with")

Added a new PBP-derived team_totals row for UW-Stevens Point Pointers (none existed from a PDF).

C:\Users\frits\OneDrive\Documents\GitHub\uwwmensbball\parser\parser_lib\74_replace_upcoming_opponent_team_totals_with.py:38: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  team_totals = pd.concat([team_totals, pd.DataFrame([{


### Back-fill PAST scouted opponents' player stats from their own prior-game PBP

The override two cells up only touches the **upcoming** opponent. Every previously-scouted opponent keeps
the all-null stat columns set in the player-profiles cell, because scouting-report stats are disabled
parser-wide (they're last-season numbers). That is why every row of `uww_player_comparisons` came out with
an empty `compared_PTS` and a `comparison_method` of "scouting notes, no stats" — the compared side of the
comparison had no stats to compare, for any opponent, ever.

Their prior-game PBP files are already on disk (e.g. Elmhurst's five games before Dec 2). This cell runs
the same chain the upcoming opponent gets — own schedule → games before facing UWW → `_pbp` files →
`build_pbp_events` → `box_score_from_pbp_events` — once per past opponent, and fills their
`player_profiles` stat columns from it. Same cutoff rule as `prev_games`: strictly before the earlier of
their UWW matchup and `reference_date`, so nothing a team did after we played them can leak backwards into
what they looked like when we played them.

In [176]:
# --- Back-fill PAST scouted opponents' player_profiles stats from their own prior-game PBP -----------------
# Code: parser_lib\75_back_fill_past_scouted_opponents_player.py  --  settings below, then the section runs.

run_section("75_back_fill_past_scouted_opponents_player")

  Carroll (WI) Pioneers: no PBP box-score rows for ['Evan Bland'] (left blank rather than guessed)

Back-filled PBP-derived stats for 85 player_profiles row(s) across 8 past opponent(s).

                opponent UWW matchup  prior games on schedule  with _pbp file  players filled  roster rows  no PBP match
0  St. Thomas (TX) Celts  2025-11-14                        2               2              12           12             0
1      Eureka Red Devils  2025-11-15                        3               3              14           14             0
2        Aurora Spartans  2025-11-19                        4               4              12           12             0
3  Carroll (WI) Pioneers  2025-12-13                        8               1              10           11             1
4   Hope Flying Dutchmen  2025-12-19                        8               1               0            0             0
5             Alma Scots  2025-12-20                       11              11              10           10             0
6      Elmhurst Bluejays  2025-12-02                        5               5              10           10             0
7      UW-Oshkosh Titans  2026-01-03                       11              11              17           17             0

Skipped (no data, not an error -- these keep blank stats and their comparisons stay notes-only):
  Simpson Storm: 7 prior game(s) on their schedule, no _pbp file for any of them
  Ripon Red Hawks: no games before 2025-11-07
  Lawrence Vikings: 8 prior game(s) on their schedule, no _pbp file for any of them
  Coe Kohawks: 13 prior game(s) on their schedule, no _pbp file for any of them

Elmhurst spot-check (season stats BEFORE they played UWW on their matchup date):

                     name games_played   PTS  REB AST     FG%    3P%
66             Luke Smith            5  11.6  3.4  15   41.2%  33.3%
67      Sebastian Blachut            5  10.8  2.2  14   41.5%  38.5%
68     Dominic Trelenberg            5  16.4  6.6  14   49.1%  37.0%
69            Aidyn Boone            5  10.0  6.2   3   47.1%  45.5%
70   Vinnie Adjahoungbeta            5  11.6  8.4   9   46.8%  58.3%
71          Talen Pearson            5   2.2  0.8   5   26.3%   9.1%
72            Jack Cherry            5   4.4  1.2   5   46.2%  33.3%
73            EJ Marshall            5   2.2  0.8   4   30.8%  50.0%
74       Jeffrey Williams            5   2.6  0.2   0   71.4%  75.0%
120          Oliver Adams            5   0.6  0.6   0  100.0%      -


### Rebuild player comparisons with PBP-derived stats

The comparison cell near the top runs before the upcoming opponent's stats are replaced with PBP-derived ones. Bench players have no PDF season stats, so their comparisons were decided on size and position alone. Re-running the same function here, after the override, gives them real production evidence.

In [178]:
# --- Rebuild player comparisons now that the upcoming opponent's stats are PBP-derived ----------------------
# Code: parser_lib\76_rebuild_player_comparisons_with_pbp.py  --  settings below, then the section runs.

run_section("76_rebuild_player_comparisons_with_pbp")

WARNING: upcoming opponent 'UW-Stevens Point Pointers' has no scout report loaded (scouted: ['Alma Scots', 'Aurora Spartans', 'Carroll (WI) Pioneers', 'Coe Kohawks', 'Elmhurst Bluejays', 'Eureka Red Devils', 'Hope Flying Dutchmen', 'Lawrence Vikings', 'Ripon Red Hawks', 'Simpson Storm', 'St. Thomas (TX) Celts', 'UW-Oshkosh Titans']) -- player comparisons will be empty for them. Add their scout report to INPUT_DIR and re-run.
LLM comparison skipped (use_llm=False) -- using tag-based similarity only.
Rebuilt player comparisons for UW-Stevens Point Pointers using PBP-derived stats.
  19 of 19 comparisons now have stat evidence (0 gained it in this rebuild -- those were size-and-position guesses before).

  Still thin (19) -- the app labels these so they aren't read as real matches:
    Dylan Taylor -> Dylan Logsdon (26% evidence) -- stats and size (no scouting notes for this player)
    Emmitt Huhn -> Dylan Logsdon (26% evidence) -- stats and size (no scouting notes for this player)
    Nick Fox -> Dylan Logsdon (26% evidence) -- stats and size (no scouting notes for this player)
    Zach Orr -> Andrew Hollerich (26% evidence) -- stats and size (no scouting notes for this player)
    Austin Schaumburg -> Amare Brokemond (26% evidence) -- stats and size (no scouting notes for this player)
    Brandon Tilley -> Alex Ross (26% evidence) -- stats and size (no scouting notes for this player)
    Tyler Orr -> Isaiah Thompson (26% evidence) -- stats and size (no scouting notes for this player)
    Shane Tarjan -> Alex Ross (26% evidence) -- stats and size (no scouting notes for this player)
    Isaiah Moore -> Logan Rindfleisch (48% evidence) -- stats and size (no scouting notes for this player)
    James Jacobs -> Greg Smith (41% evidence) -- stats and size (no scouting notes for this player)
    Logan Baumgartner -> Gevon Grant (63% evidence) -- stats and size (no scouting notes for this player)
    Drew Daoust -> Isaiah Thompson (26% evidence) -- stats and size (no scouting notes for this player)
    Max Raimer -> Jay Dalton (26% evidence) -- stats and size (no scouting notes for this player)
    Josh Bocher -> Reyce Allen (63% evidence) -- stats and size (no scouting notes for this player)
    Grant Manz -> Cai Joseph (26% evidence) -- stats and size (no scouting notes for this player)
    Josiah Butler -> Logan Rindfleisch (48% evidence) -- stats and size (no scouting notes for this player)
    Seth Miron -> Gevon Grant (63% evidence) -- stats and size (no scouting notes for this player)
    Carter Combs -> Reyce Allen (63% evidence) -- stats and size (no scouting notes for this player)
    Cal Krohn -> Gevon Grant (63% evidence) -- stats and size (no scouting notes for this player)

  Comparisons for players with no scouting-report entry:
    Dylan Taylor -> Dylan Logsdon of Eureka Red Devils (score 3.5, 26% evidence)
    Emmitt Huhn -> Dylan Logsdon of Eureka Red Devils (score 3.5, 26% evidence)
    Nick Fox -> Dylan Logsdon of Eureka Red Devils (score 3.5, 26% evidence)
    Zach Orr -> Andrew Hollerich of Carroll (WI) Pioneers (score 3.5, 26% evidence)
    Austin Schaumburg -> Amare Brokemond of Eureka Red Devils (score 3.45, 26% evidence)
    Brandon Tilley -> Alex Ross of Aurora Spartans (score 3.35, 26% evidence)
    Tyler Orr -> Isaiah Thompson of Aurora Spartans (score 3.24, 26% evidence)
    Shane Tarjan -> Alex Ross of Aurora Spartans (score 3.21, 26% evidence)
    Isaiah Moore -> Logan Rindfleisch of UW-Oshkosh Titans (score 3.15, 48% evidence)
    James Jacobs -> Greg Smith of Carroll (WI) Pioneers (score 3.14, 41% evidence)
    Logan Baumgartner -> Gevon Grant of Aurora Spartans (score 3.05, 63% evidence)
    Drew Daoust -> Isaiah Thompson of Aurora Spartans (score 3.04, 26% evidence)
    Max Raimer -> Jay Dalton of UW-Oshkosh Titans (score 2.94, 26% evidence)
    Josh Bocher -> Reyce Allen of St. Thomas (TX) Celts (score 2.83, 63% evidence)
    Grant Manz -> Cai Joseph of Carroll (WI) Pioneers (score 2.79, 26% evidence)
    Josiah Butler -> Logan Rindfleisch of UW-Oshkosh Titans (score 2.53, 48% evidence)
    Seth Miron -> Gevon Grant of Aurora Spartans (score 2.21, 63% evidence)
    Carter Combs -> Reyce Allen of St. Thomas (TX) Celts (score 2.19, 63% evidence)
    Cal Krohn -> Gevon Grant of Aurora Spartans (score 2.02, 63% evidence)

In [179]:
# --- OPTIONAL: re-derive the coach-note theme taxonomy with an LLM ----------------------------------------
# Code: parser_lib\77_rebuild_player_comparisons_with_pbp_2.py  --  settings below, then the section runs.
REBUILD_NOTE_THEMES = False   # set True (with USE_LLM=True) to re-derive themes from the current notes
# APP_DATA_DIR is assigned in the CSV-export cell further down; this cell runs before it, so resolve
# it here rather than depending on run order (both point at OUTPUT_DIR either way).
APP_DATA_DIR = globals().get("APP_DATA_DIR") or OUTPUT_DIR
NOTE_THEMES_PATH = os.path.join(APP_DATA_DIR, "note_themes.json")

run_section("77_rebuild_player_comparisons_with_pbp_2")

Note-theme rebuild skipped (needs USE_LLM=True and REBUILD_NOTE_THEMES=True). The app keeps using the existing data/note_themes.json -- classification is unaffected.

In [180]:
# CONFIRMED BUG (fixed): this cell used urllib.request without importing it -- harmless while every roster photo
# Code: parser_lib\78_rebuild_player_comparisons_with_pbp_3.py  --  settings below, then the section runs.
UWW_ROSTER_FORCE_REFRESH = False   # True to re-fetch photos that are already on disk
# APP_DATA_DIR is assigned in the CSV-export cell further down; this cell runs before it, so resolve
# it here rather than depending on run order (both point at OUTPUT_DIR either way).
APP_DATA_DIR = globals().get("APP_DATA_DIR") or OUTPUT_DIR

run_section("78_rebuild_player_comparisons_with_pbp_3")

Found 15 roster snapshot(s):
 - 2025-26 Men's Basketball Roster - University of Wisconsin-Whitewater Athletics.mhtml
 - Alma Scots - Roster_2025.html
 - Aurora Spartans - Roster_2025.html
 - Carroll (WI) Pioneers - Roster_2025.html
 - Coe Kohawks - Roster_2025.html
 - Elmhurst Bluejays - Roster_2025.html
 - Eureka Red Devils - Roster_2025.html
 - Hope Flying Dutchmen - Roster_2025.html
 - Lawrence Vikings - Roster_2025.html
 - Ripon Red Hawks - Roster_2025.html
 - Simpson Storm - Roster_2025.html
 - St. Thomas (TX) Celts - Roster_2025.html
 - UW-Oshkosh Titans - Roster_2025.html
 - UW-Stevens Point Pointers - Roster_2025.html
 - UW-Whitewater Warhawks - Roster_2025.html
  2025-26 Men's Basketball Roster - University of Wisconsin-Whitewater Athletics.mhtml: 21 player photo(s) referenced
  Alma Scots - Roster_2025.html: 0 player photo(s) referenced
  Aurora Spartans - Roster_2025.html: 0 player photo(s) referenced
  Carroll (WI) Pioneers - Roster_2025.html: 0 player photo(s) referenced
  Coe Kohawks - Roster_2025.html: 0 player photo(s) referenced
  Elmhurst Bluejays - Roster_2025.html: 0 player photo(s) referenced
  Eureka Red Devils - Roster_2025.html: 0 player photo(s) referenced
  Hope Flying Dutchmen - Roster_2025.html: 0 player photo(s) referenced
  Lawrence Vikings - Roster_2025.html: 0 player photo(s) referenced
  Ripon Red Hawks - Roster_2025.html: 0 player photo(s) referenced
  Simpson Storm - Roster_2025.html: 0 player photo(s) referenced
  St. Thomas (TX) Celts - Roster_2025.html: 0 player photo(s) referenced
  UW-Oshkosh Titans - Roster_2025.html: 0 player photo(s) referenced
  UW-Stevens Point Pointers - Roster_2025.html: 0 player photo(s) referenced
  UW-Whitewater Warhawks - Roster_2025.html: 0 player photo(s) referenced

Headshots: 0 saved, 21 already on disk, 0 failed.  ->  ../data\uww_player_pictures


### Head-to-head: previous meetings with the upcoming opponent

Opponents recur — conference teams twice a season, most of them again the next year — so the brief and the app open with how the last meeting(s) actually went.

Sources, in order: **this season's schedule** (already parsed), then **local schedule snapshots for earlier seasons** (captures are already saved season-suffixed, so a previous year's file on disk needs no scraping), then a **live scrape of any earlier season with no local file** — FastScout's team URL takes a season code, and the result is saved season-suffixed so it's a once-per-season cost.

Exports `uww_head_to_head.csv`.

In [182]:
# --- Head-to-head: every previous meeting with the upcoming opponent, this season and earlier ---------------
# Code: parser_lib\79_head_to_head.py  --  settings below, then the section runs.

run_section("79_head_to_head")

  Meeting box scores: team labels were swapped in 2 meeting(s) -- fixed (the side whose players are ours is UWW).
  Do the previous meetings matter? Yes -- mostly the same teams. Last met Wed, Jan 8 (last season). 66% of their points against us came from players still on their roster, and 70% of ours from players still on ours.
  Meeting play-by-play parsed: 2024-25 Wed, Jan 8 (cached), 2024-25 Wed, Jan 29 (cached), 2024-25 Mon, Feb 24 (cached), 2023-24 Wed, Jan 10 (cached), 2023-24 Wed, Feb 7 (cached), 2023-24 Tue, Feb 20 (cached).
  Roster continuity: 10 of 27 players who faced us are back; 219 of their points against us are gone.
Head-to-head vs UW-Stevens Point Pointers: 6 previous meeting(s), 1-5.

    season         date home_away outcome  team_score  opponent_score
0  2024-25   Wed, Jan 8      Home       L          67              86
1  2024-25  Wed, Jan 29      Away       L          52              83
2  2024-25  Mon, Feb 24      Away       L          79              81
3  2023-24  Wed, Jan 10      Away       L          92             100
4  2023-24   Wed, Feb 7      Home       W          81              55
5  2023-24  Tue, Feb 20      Away       L          70              76

In [183]:
# --- Export the same tables as CSV files directly into the Streamlit app's source directory, so the app can
# Code: parser_lib\80_head_to_head_2.py  --  settings below, then the section runs.
APP_DATA_DIR = OUTPUT_DIR
CLUTCH_EVENTS_EXPORT_COLS = [
    "opponent", "game_date", "event_order", "period", "time_remaining", "team", "player", "event_type",
    "raw_text", "shot_type", "uww_score", "opp_score", "uww_lineup", "opp_lineup", "video_description",
]
APPEND_TABLES = {
    "uww_projected_box_score": ["opponent", "game_date"],
    "uww_opponent_projected_box_score": ["opponent", "game_date"],
}

run_section("80_head_to_head_2")

C:\Users\frits\OneDrive\Documents\GitHub\uwwmensbball\parser\parser_lib\80_head_to_head_2.py:152: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([prior, df], ignore_index=True)

                               table  rows  csv_bytes
0                       uww_schedule   179      85199
1                   uww_season_stats    25       2707
2                     uww_pbp_events  6202    1556367
3                  uww_pbp_box_score   321      35149
4                  uww_lineup_stints   577     136546
5                 uww_coaching_flags    35      12520
6               uww_opponent_rosters   112      19513
7                uww_player_profiles   150      41415
8            uww_opponent_game_plans   153      30534
9                     uww_ktv_splits     7        477
10           uww_ktv_game_categories    21       1432
11              uww_pbp_derived_keys     3       1071
12          uww_opponent_team_totals    12        291
13           uww_projected_box_score    69      19590
14  uww_opponent_projected_box_score    45      12212

  ... 68 more row(s) of 83 (SHOW_ROWS = 15)


### Extract and save team logos from PBP MHTML files

Pulls each team's logo image out of the play-by-play MHTML snapshots and saves it into the app's `data/logo` directory, for the Streamlit app's UI.

In [185]:
# --- Extract team logos embedded in the PBP/schedule MHTML files and save them into the Streamlit app's
# Code: parser_lib\81_extract_and_save_team_logos_from_pbp_mhtml.py  --  settings below, then the section runs.

run_section("81_extract_and_save_team_logos_from_pbp_mhtml")

Saved 21 team logos to ../data\logo:
  - Alma (226,793 bytes)
  - Aurora (136,971 bytes)
  - Carroll (WI) (109,313 bytes)
  - Coe (115,946 bytes)
  - Elmhurst (118,533 bytes)
  - Eureka (150,170 bytes)
  - Hope (66,665 bytes)
  - Lawrence (84,599 bytes)
  - Loras (95,745 bytes)
  - Ripon (87,371 bytes)
  - Simpson (76,108 bytes)
  - St. Thomas (TX) (188,379 bytes)
  - UW-Eau Claire (70,774 bytes)
  - UW-La Crosse (26,203 bytes)
  - UW-Oshkosh (166,949 bytes)
  - UW-Platteville (71,166 bytes)
  - UW-River Falls (89,021 bytes)
  - UW-Stevens Point (139,555 bytes)
  - UW-Stout (194,873 bytes)
  - UW-Whitewater (145,562 bytes)
  - Washington-St. Louis (87,899 bytes)


### Extract player headshots from scouting report PDFs

Pulls each scouted player's headshot image out of their FastScout scouting-report PDF, for the Streamlit app's player-comparison UI.

In [187]:
# --- Extract player headshot images from scouting reports (PDF or HTML) and save them to the Streamlit
# Code: parser_lib\82_extract_player_headshots_from_scouting.py  --  settings below, then the section runs.

run_section("82_extract_player_headshots_from_scouting")

warning: The `fitz` API is deprecated and will be removed in future. Use `import pymupdf` instead.
Processing 12 scout report(s) from scout_report_files...
    [DIAG] Found 9 playerGroup tiles in PrintableNode
    [DIAG] First playerGroup: has player-info-line=True, has img=True
    [DIAG] First img src: https://stats-assets.fastmodelsports.com/images/personnel/St. Thomas (TX)/2025-2026/Angel Johnson/17
    [DIAG] info_div found: True
    [DIAG] info_text = '#10 • Angel Johnson • G • 6\'2" • SR'
    [DIAG] regex match: True
    [DIAG] captured name: 'Angel Johnson'
    [DIAG] Found 7 playerGroup tiles in PrintableNode
    [DIAG] First playerGroup: has player-info-line=True, has img=True
    [DIAG] First img src: https://stats-assets.fastmodelsports.com/images/personnel/Eureka/2025-2026/Jaxson Provost/1762669410
    [DIAG] info_div found: True
    [DIAG] info_text = '#12 • Jaxson Provost • G • 5\'10" • 170 lbs • JR'
    [DIAG] regex match: True
    [DIAG] captured name: 'Jaxson Provost'
    [DIAG] Found 9 playerGroup tiles in PrintableNode
    [DIAG] First playerGroup: has player-info-line=True, has img=True
    [DIAG] First img src: https://stats-assets.fastmodelsports.com/images/personnel/Aurora/2025-2026/Mekhi Doby/1763067641902
    [DIAG] info_div found: True
    [DIAG] info_text = '#11 • Mekhi Doby • G • 6\'3" • JR'
    [DIAG] regex match: True
    [DIAG] captured name: 'Mekhi Doby'
    [DIAG] Found 8 playerGroup tiles in PrintableNode
    [DIAG] First playerGroup: has player-info-line=True, has img=True
    [DIAG] First img src: https://stats-assets.fastmodelsports.com/images/personnel/Simpson/2025-2026/Cam Henderson/1762760111
    [DIAG] info_div found: True
    [DIAG] info_text = '#23 • Cam Henderson • G • 5\'10" • SO'
    [DIAG] regex match: True
    [DIAG] captured name: 'Cam Henderson'
    [DIAG] Found 7 playerGroup tiles in PrintableNode
    [DIAG] First playerGroup: has player-info-line=True, has img=True
    [DIAG] First img src: https://media-attachments.fastmodelsports.com/prod/0e0cbfb6-a4fd-4065-aa12-2c4565175719
    [DIAG] info_div found: True
    [DIAG] info_text = '#3 • Seth Bunders • G • 6\'0" • 140 lbs • JR'
    [DIAG] regex match: True
    [DIAG] captured name: 'Seth Bunders'
    [DIAG] Found 9 playerGroup tiles in PrintableNode
    [DIAG] First playerGroup: has player-info-line=True, has img=True
    [DIAG] First img src: https://stats-assets.fastmodelsports.com/images/personnel/Lawrence/2025-2026/Nathan Valentine/176136
    [DIAG] info_div found: True
    [DIAG] info_text = '#3 • Nathan Valentine • G • 5\'11" • 170 lbs • SR'
    [DIAG] regex match: True
    [DIAG] captured name: 'Nathan Valentine'
    [DIAG] Found 8 playerGroup tiles in PrintableNode
    [DIAG] First playerGroup: has player-info-line=True, has img=True
    [DIAG] First img src: https://stats-assets.fastmodelsports.com/images/personnel/Carroll (WI)/2025-2026/Dennis Estepp/17626
    [DIAG] info_div found: True
    [DIAG] info_text = '#33 • Dennis Estepp • G • 6\'0" • 170 lbs • JR'
    [DIAG] regex match: True
    [DIAG] captured name: 'Dennis Estepp'
    [DIAG] Found 9 playerGroup tiles in PrintableNode
    [DIAG] First playerGroup: has player-info-line=True, has img=True
    [DIAG] First img src: https://stats-assets.fastmodelsports.com/images/personnel/Alma/2025-2026/Raine Rodich/1769015496078
    [DIAG] info_div found: True
    [DIAG] info_text = '#14 • Raine Rodich • G • 6\'0" • 185 lbs • SO'
    [DIAG] regex match: True
    [DIAG] captured name: 'Raine Rodich'
    [DIAG] Found 9 playerGroup tiles in PrintableNode
    [DIAG] First playerGroup: has player-info-line=True, has img=True
    [DIAG] First img src: https://stats-assets.fastmodelsports.com/images/personnel/Elmhurst/2025-2026/Luke Smith/176345659508
    [DIAG] info_div found: True
    [DIAG] info_text = '#2 • Luke Smith • G • 6\'0" • 185 lbs • FR'
    [DIAG] regex match: True
    [DIAG] captured name: 'Luke Smith'
    [DIAG] Found 8 playerGroup tiles in PrintableNode
    [DIAG] First playerGroup: has player-info-line=True, has img=True
    [DIAG] First img src: https://stats-assets.fastmodelsports.com/images/personnel/Coe/2025-2026/Cooper Nailor/1763573358105
    [DIAG] info_div found: True
    [DIAG] info_text = '#5 • Cooper Nailor • G • 6\'1" • SR'
    [DIAG] regex match: True
    [DIAG] captured name: 'Cooper Nailor'
    [DIAG] Found 10 playerGroup tiles in PrintableNode
    [DIAG] First playerGroup: has player-info-line=True, has img=True
    [DIAG] First img src: https://stats-assets.fastmodelsports.com/images/personnel/UW-Oshkosh/2025-2026/Joey LaChapell/176276
    [DIAG] info_div found: True
    [DIAG] info_text = '#2 • Joey LaChapell • G • 6\'0" • 175 lbs • SO'
    [DIAG] regex match: True
    [DIAG] captured name: 'Joey LaChapell'

[INFO] No headshots required authenticated download.

Extracted 0 new player headshot(s) to ../data\player_images
Skipped 93 already-on-disk headshot(s)
[before_scout=yes] Scouting report PDF: none on disk for UW-Stevens Point Pointers to hide.


### Assemble every Key to Victory into one table

Builds `uww_ktv_keys.csv` -- one row per key, in display order -- from all seven generators: the data-driven play-by-play keys, the staff's written Keys to Victory and Team Strengths, the four Lineup Scouting keys, and the three video-tagged shot-look keys. Keys are now built in the parser and merely rendered downstream, so the HTML brief and the app's Upcoming Game page can't produce different lists. Read the cell's header comment before validating against the app.

In [189]:
# --- Assemble every Key to Victory into ONE table -----------------------------------------------------------
# Code: parser_lib\83_assemble_every_key_to_victory_into_one.py  --  settings below, then the section runs.

run_section("83_assemble_every_key_to_victory_into_one")

  3-man combos: 357 ours, 276 UW-Stevens Point Pointers -> uww_three_man_combos.csv
Wrote uww_ktv_keys.csv -- 13 key(s) for UW-Stevens Point Pointers: {'Defense': 7, 'Offense': 3, 'Personnel': 3}
  Brief will show 6 of 13 (score >= 55, max 6); Bottom Line keys are added and re-ranked in the brief cell:
   *  85.5  #8 Take away their go-to set: Chin
   *  79.5  #1 Feature our best look: Ball Screen
   *  78.6  #13 Feature the Chestnut, Quast, Berezowitz combo
   *  74.7  #10 Finish every defensive possession with a box-out
   *  74.0  #2 Attack their weakest look: Cut to the basket
   *  72.5  #9 Know their best set: Pistol
      63.6  #12 Attack UW-Stevens Point Pointers's Krohn, Combs, Butler combo
      63.0  #7 What UW-Stevens Point Pointers goes to most: Drive to the basket
      62.5  #4 Take away their most efficient high-volume actions
      62.5  #6 Pressure the actions they turn it over on
      58.4  #11 Attack UW-Stevens Point Pointers's Krohn, Combs, Butler, Baumgartner, Miron line
      55.9  #3 Call our best set: Ball Screen
      55.5  #5 Funnel them into their worst high-volume looks
  Generators that FAILED (their keys are missing from the table above):
    - Lineup Scouting (counter lineup): cannot convert float NaN to integer


### Style matchups: teams like them, and teams like us

Builds `uww_style_matchups.csv` -- both halves of the app's STYLE MATCHUPS section, computed here so the brief and the app render one answer. One weighted seventeen-feature style model, run in two directions: target the upcoming opponent against the pool of teams UWW has played, and target UWW against the pool of teams the opponent has played. A match score means the same thing in both. See the cell's header comment for the one deliberate omission (the prior-season pool top-up).

In [191]:
# --- Style matchups: teams like them that we've played, and teams like us that have played them -------------
# Code: parser_lib\84_style_matchups.py  --  settings below, then the section runs.

run_section("84_style_matchups")

Wrote uww_style_matchups.csv -- 6 matched team(s) for UW-Stevens Point Pointers: {'like_them': 3, 'like_us': 3}


### Scouting notes and keys to defending

Builds `uww_scouting_notes.csv`: one row per subject per source, covering both players and five-man units. Coach-written notes from the `_scout.html` report are passed through verbatim; the data-driven notes, keys, strengths and weaknesses are generated from the opponent's own box scores. Players and units carry the same four fields so one renderer draws both sections. Every percentage read carries a volume floor.

In [193]:
# --- Scouting notes and keys to defending, derived from the opponent's own box scores ------------------------
# Code: parser_lib\85_scouting_notes_and_keys_to_defending.py  --  settings below, then the section runs.

run_section("85_scouting_notes_and_keys_to_defending")

Wrote uww_scouting_notes.csv -- 156 row(s) for UW-Stevens Point Pointers: {('lineup', 'Data-Driven'): 137, ('player', 'Data-Driven'): 19}


### Game plan, practice plan and staff inputs (SAMPLE placeholders where the files don't cover it)

Writes one CSV per game-plan section so the app and the brief render the same thing:

* **Real, from the exported tables:** `uww_late_game_foul_list`, `uww_sample_size_warnings`, and the emphasis items inside `uww_practice_plan` (pulled from the Keys to Victory and player flags).
* **SAMPLE until the staff supplies them:** `uww_opp_sets`, `uww_opp_defense`, `uww_opp_personnel`, `uww_opp_shot_zones`, `uww_opp_tendencies`, `uww_matchups`, `uww_scout_team`, `uww_uww_availability`, `uww_film_clips`, and the practice calendar.

Every row carries `is_sample`. Renderers must draw sample rows inside a red **SAMPLE DATA** box. To replace a section with real input, fill the matching template from `OUTPUT_DIR/staff_input_templates/` and save it to `INPUT_DIR/staff_inputs/` — rows for the upcoming opponent replace the sample for that whole section.

In [195]:
# --- Game-plan and practice-plan tables, with SAMPLE placeholders for what the files don't carry yet --------
# Code: parser_lib\86_game_plan.py  --  settings below, then the section runs.

run_section("86_game_plan")

  opp_defense: real data for 3 item(s).
  player_shot_profile: 17 of theirs, 21 of ours (rim / other 2 / three, from play-by-play).
  defense_by_situation: real data for 2 situation(s).
  ball_screen_coverage: real data for 4 coverage type(s).
  ball_screen_coverage: real data from structured tags -- 81 ball screen(s).
  trend_profile: only 1 tagged game(s) -- needs 4+ before an earlier-vs-recent split says anything. Staying sample.
  rebound_tendencies: 922 misses across 13 game(s), 901 paired to a rebound, 480 of them UW-Stevens Point Pointers's -> 8 row(s).
Wrote game-plan tables for UW-Stevens Point Pointers:
  uww_late_game_foul_list        8 row(s)  [real]
  uww_sample_size_warnings       4 row(s)  [real]
  uww_opp_sets                  12 row(s)  [real]
  uww_opp_defense                3 row(s)  [real]
  uww_opp_personnel             17 row(s)  [real]
  uww_opp_shot_zones             5 row(s)  [SAMPLE]
  uww_opp_tendencies             5 row(s)  [SAMPLE]
  uww_matchups                   5 row(s)  [SAMPLE]
  uww_scout_team                 5 row(s)  [SAMPLE]
  uww_uww_availability           5 row(s)  [SAMPLE]
  uww_film_clips                 6 row(s)  [real]
  uww_shot_clock_tendencies      3 row(s)  [real]
  uww_defense_by_situation       2 row(s)  [real]
  uww_ball_screen_coverage      10 row(s)  [real]
  uww_help_rotation_tendencies   4 row(s)  [SAMPLE]
  uww_personnel_grouping        10 row(s)  [real]
  uww_rebound_tendencies         8 row(s)  [real]
  uww_game_situation_splits      2 row(s)  [real]
  uww_shot_quality_by_contest    4 row(s)  [SAMPLE]
  uww_double_team_tendencies     2 row(s)  [SAMPLE]
  uww_offball_screen_navigation   3 row(s)  [SAMPLE]
  uww_matchup_history            4 row(s)  [SAMPLE]
  uww_play_counters              3 row(s)  [SAMPLE]
  uww_practice_plan             21 row(s)  [SAMPLE]
  uww_personnel_tiers           40 row(s)  [real]
  uww_tempo_profile              4 row(s)  [real]
  uww_trend_profile              1 row(s)  [SAMPLE]
  uww_uww_lineup_season        163 row(s)  [real]
  Staff input templates: C:\Users\frits\OneDrive\Documents\GitHub\uwwmensbball\data\staff_input_templates


### Build an HTML scouting brief for the upcoming opponent

A one-file executive summary for the coaching staff to read before they write their own scouting reports: how the two teams stack up, where the game is won, their personnel and how to guard them, the five-man units they trust, their recent form, our own watch-outs, and the projection. Built from the CSVs the export cell above just wrote -- the same files the Streamlit app reads -- so the brief and the app can't disagree about a number. Lands in `<OUTPUT_DIR>/scouting_briefs/`.

In [197]:
# --- Build a one-file HTML scouting brief for the upcoming opponent ----------------------------------------
# Code: parser_lib\87_build_html_scouting_brief_for_upcoming.py  --  settings below, then the section runs.
ROSTER_LAYOUT = "table"

run_section("87_build_html_scouting_brief_for_upcoming")

Sample data left out of the brief (still in the app): uww_double_team_tendencies, uww_offball_screen_navigation, uww_opp_shot_zones, uww_opp_tendencies, uww_play_counters, uww_shot_quality_by_contest, uww_uww_availability
Wrote C:\Users\frits\OneDrive\Documents\GitHub\uwwmensbball\data\scouting_briefs\scouting_brief_UW_Stevens_Point_Pointers.html (532,212 bytes) -- open it in a browser, or attach it to an email as-is.
  14 methodology note(s) -> uww_brief_notes.csv (the brief links to these instead of printing them).
  Opponent headshots: 7 found, 1 missing -- Josh Bocher
  UWW headshots: 12 found, 0 missing
  Tables that were empty or missing (their sections were left out of the brief): uww_double_team_tendencies, uww_offball_screen_navigation, uww_opp_shot_zones, uww_opp_tendencies, uww_play_counters, uww_shot_quality_by_contest, uww_uww_availability

### Tracking review export (optional)

Packs the first `REVIEW_POSSESSIONS` tracked possessions of `REVIEW_GAME` -- their frames, what tracking and court mapping concluded, the saved detections / arm positions / court positions trimmed to those frames, the calibration and the check images -- into `INPUT_DIR/tracking_review_first5.zip`, to upload for a frame-by-frame review. Off unless `EXPORT_TRACKING_REVIEW = True`.

In [199]:
# --- Tracking review export (requested: a permanent version of the review export, instead of pasting code) ------
# Code: parser_lib\88_tracking_review_export.py  --  settings below, then the section runs.
EXPORT_TRACKING_REVIEW = True
REVIEW_GAME = "WOS"          # part of the export's Game column (e.g. "WOS" for WOS@WWW)
REVIEW_POSSESSIONS = 5       # the first N tracked possessions of that game

run_section("88_tracking_review_export")

Tracking review export: ./inputs\tracking_review_first5.zip (129,869 KB) -- upload this file for a review.

### Cleanup: free disk space (dry run first)

Lists (and, with `CLEANUP_DRY_RUN = False`, deletes) what nothing uses anymore: old tracking-frame folders and pre-fix key frames, detection/pose files from old models, saved entries for frames that are gone, answers of readers no longer tested, TrOCR's model, old review zips. Frames your court calibration uses are always kept.

In [201]:
# --- Cleanup: free the disk space taken by things the parser no longer uses -------------------------------------------
# Code: parser_lib\89_cleanup.py  --  settings below, then the section runs.
RUN_CLEANUP = True
CLEANUP_DRY_RUN = True

run_section("89_cleanup")

Cleanup (DRY RUN -- nothing deleted): 2 item(s), 155 MB
  old review zip: 1 (133 MB)  e.g. ./inputs\tracking_review_first5.zip
  old detection / pose file: 1 (22 MB)  e.g. ./inputs\_tracking\pose_yolo11n_pose_pt_768_tiles3x2.pkl
  -> set CLEANUP_DRY_RUN = False and run this cell again to delete these.

### Model versions

Writes `uww_model_versions.csv` (current version of each model) and `uww_model_version_history.csv` (a row each time a model gets a new version). A version is the date the model was trained (`v2026.10.03`; a second training that day is `.2`). Models that don't learn (tracking, court mapping, roles, player comparison) are versioned by the date their code or model settings last changed. Shown in the app on Analytics > Player Number Tracking.

In [203]:
# --- Model versions: which version of each model is in use (by date trained) ---------------------------------------
# Code: parser_lib\90_model_versions.py  --  no settings.

run_section("90_model_versions")

Model versions: Tag model: ball_screen_coverage -> v2026.10.07
Model versions: Tag model: defense -> v2026.10.07
Model versions: Tag model: formation -> v2026.10.07
Model versions: Tag model: offball_coverage -> v2026.10.07
Model versions: Tag model: play_call -> v2026.10.07
Model versions: Tag model: press -> v2026.10.07
Model versions: Tag model: primary_action -> v2026.10.07
Model versions: Tag model: screen_defender -> v2026.10.07
Model versions: Tag model: situation -> v2026.10.07
Model versions: Tag model (overall) -> v2026.10.07
Model versions: Player tracking -> v2026.10.06
Model versions: Player comparison -> v2026.10.07
Model versions: 17 model(s) -> ../data\uww_model_versions.csv