# 2) New clips for Film Tagging -- fast

Captures new clips (frame capture), builds the play calls, and writes the **Film Tagging** batches for the coaches. **No automatic Titles** (the tag model is not run -- the last automatic answers are kept), no player tracking, no brief. Commit and push the data folder when it finishes.
**Settings live in `parser_nb.ipynb`** -- this notebook runs that notebook's own cells (only the ones this job needs), so change a setting there and **save it** (Ctrl+S) before running this one. Run this notebook from the same folder as `parser_nb.ipynb`. The full notebook still works as before for a complete run.

In [ ]:
import os
PARSER_LIB = os.path.join(os.getcwd(), "parser_lib")
exec(open(os.path.join(PARSER_LIB, "00_parser_modes.py"), encoding="utf-8").read())
run_parser("tagging")

=== TAGGING: New clips for Film Tagging, fast (no automatic Titles, no tracking) ===
EXTRA_GAMES is set: the run's date is 2026-3-8, the day after UWW's last game on file (03/07/26) -- every game on file counts as played, the extra game is next. (REFERENCE_DATE is ignored while EXTRA_GAMES is set.)
Input directory: ./inputs
Output directory: ../data
LLM comparisons: disabled
Reference date: 2026-3-8
Before scout: yes -- ignoring the upcoming opponent's own scouting report for this run
APP_BASE_URL taken from UWW_APP_URL in .env
  APP_BASE_URL normalized: 'uwwmensbball-new.streamlit.app' -> https://uwwmensbball-new.streamlit.app
Brief links -> https://uwwmensbball-new.streamlit.app
Found 26 schedule MHTML file(s) in ./inputs:
 - Alma Scots - Schedule.html
 - Aurora Spartans - Schedule.html
 - Carroll (WI) Pioneers - Schedule.html
 - Coe Kohawks - Schedule.html
 - Elmhurst Bluejays - Schedule.html
 - Eureka Red Devils - Schedule.html
 - Hope Flying Dutchmen - Schedule.html
 - Lawrence Vikings - Schedule.html
 - Loras Duhawks - Schedule.html
 - MSOE Raiders - Schedule_2025.html
 - Ripon Red Hawks - Schedule.html
 - Simpson Storm - Schedule.html
 - St. Thomas (TX) Celts - Schedule.html
 - UW-Eau Claire Blugolds - Schedule.html
 - UW-La Crosse Eagles - Schedule.html
 - UW-Oshkosh Titans - Schedule.html
 - UW-Platteville Pioneers - Schedule.html
 - UW-River Falls Falcons - Schedule.html
 - UW-Stevens Point Pointers - Schedule.html
 - UW-Stout Blue Devils - Schedule.html
 - UW-Whitewater - Schedule.mhtml
 - UW-Whitewater - Schedule_2023.html
 - UW-Whitewater - Schedule_2024.html
 - Washington-St. Louis Bears - Schedule_2025.html
 - Wheaton (IL) Thunder - Schedule_2025.html
 - Wheaton Thunder - Schedule_2025.html
Detected season 2025 from UWW's local schedule snapshot -- using FASTSCOUT_DOCS_SEASON='25' for any live-scrape URLs below (was hardcoded to '25').
Skipping live scrape for UW-Whitewater's own schedule -- a local schedule file already exists: UW-Whitewater - Schedule.mhtml

Every game already has a local scouting-report PDF, or is missing required data -- nothing to download from FastScout. (29 raw game(s) found; 0 missing opponent_url, 0 missing a parseable date.)
  UW-Whitewater Warhawks (UW-Whitewater - Schedule.mhtml): 29 game(s) -- scouted opponents: ['St. Thomas (TX) Celts', 'Eureka Red Devils', 'Aurora Spartans', 'Simpson Storm', 'Ripon Red Hawks', 'Lawrence Vikings', 'Carroll (WI) Pioneers', 'Hope Flying Dutchmen', 'Alma Scots', 'Elmhurst Bluejays', 'Coe Kohawks', 'UW-River Falls Falcons', 'UW-La Crosse Eagles', 'UW-Stout Blue Devils', 'UW-Platteville Pioneers', 'UW-Eau Claire Blugolds', 'UW-Oshkosh Titans', 'UW-Stevens Point Pointers', 'UW-Platteville Pioneers', 'UW-Eau Claire Blugolds', 'UW-La Crosse Eagles', 'UW-Stout Blue Devils', 'Loras Duhawks', 'Washington-St. Louis Bears']
  EXTRA_GAMES: Wheaton (IL) Thunder -- FastScout team page from opponent_url: https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A?league=NCAAB-III&season=25
  EXTRA_GAMES: added Wheaton (IL) Thunder as the UPCOMING game (scrimmage, real date Oct 30, 2026), placed on Sun, Mar 08, 1 day(s) after UWW's last 2025-26 game

Fetching 21 opponent schedule(s) (scrape opponent_url, MHTML backup on failure):
    [login] navigating to https://fastscout.fastmodelsports.com/teams/myTeam/analytics/dashboard?league=NCAAB-III&season=25
    [auth-retry] got redirected to identity.hudl.com while waiting on https://fastscout.fastmodelsports.com/teams/myTeam/analytics/dashboard?league=NCAAB-III&season=25 -- logging in and retrying
    [auth-retry] login_to_fastscout returned, now at https://fastscout.fastmodelsports.com/#access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZaYjBkN0VpWG9TQ0FhUTdYaW90SCJ9.eyJodHRwczovL2lkZW50aXR5Lmh1ZGwuY29tL2Nvbm5lY3Rpb25fbmFtZSI6InByb2QtaHVkbC11c2Vycy10ZXJyYWZvcm0iLCJodHRwczovL2lkZW50aXR5Lmh1ZGwuY29tL3VzZXJfaWQiOiI2NDM1MDQ3IiwiaHR0cHM6Ly9pZGVudGl0eS5odWRsLmNvbS90b2siOiJpZCIsImh0dHBzOi8vaWRlbnRpdHkuaHVkbC5jb20vaXNfc3lzYWRtaW4iOmZhbHNlLCJodHRwczovL2lkZW50aXR5Lmh1ZGwuY29tL2ludGVybmFsX2lkX2h1ZGwiOiI2NDM1MDQ3IiwiZ2l2ZW5fbmFtZSI6IkNvcmV5IiwiZmFtaWx5X25hbWUiOiJGcml0c2NoIiwibmlja25hbWUiOiJmcml0c2NoY20yNyIsIm5hbWUiOiJmcml0c2NoY20yN0BnbWFpbC5jb20iLCJwaWN0dXJlIjoiaHR0cHM6Ly9zLmdyYXZhdGFyLmNvbS9hdmF0YXIvOTY3OWI2Mzk1N2E1ZTJmZmE2NjMyYWZhYjVmMGExYTU_cz00ODAmcj1wZyZkPWh0dHBzJTNBJTJGJTJGY2RuLmF1dGgwLmNvbSUyRmF2YXRhcnMlMkZmci5wbmciLCJ1cGRhdGVkX2F0IjoiMjAyNi0xMC0yOFQxNzo1MjoyNC44NTdaIiwiZW1haWwiOiJmcml0c2NoY20yN0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5odWRsLmNvbS8iLCJhdWQiOiJ1UFJyRFVpWkZOU3d2RnJ0cnVsQ3lBWDBwaDZBckx6VSIsInN1YiI6ImF1dGgwfGh1ZGx8NjQzNTA0NyIsImlhdCI6MTc5MzIwOTk0NSwiZXhwIjoxNzk0NDE5NTQ1LCJzaWQiOiI2QWlrWng2dWFXZEhETm4tY0NNV0ctVl9TaGNQNnFlYSIsImNfaGFzaCI6IkY5bG9vMlRYNzZmal9VLUw2QnZmbFEiLCJub25jZSI6IjUxMGFmYzI1LTIyOTQtNGMyYS04ZjczLWUxYzYwNGNmMWRmNSJ9.k5dh8PTmQPSL8ZXa4VvAuDo-6Vkv2RbT0EMFWYU4TgoaN_d9fRsy1qxFJGMumGLf4DH6JGDaeeGF3SG6I_cmdjAHOTvNvZafkaw5ayiqVAAwYRw_c5leQtSCSFl-wTDwB3tHQghaxZsytUNGKoXkZrgyYLhiOwwzbYU7ycx8MljLVSWZmSjFrFh-eA9M_fqIbZsxw9wh3Dr4lF1YtDGAL4XNuT78rzoN6DFFxNFEob83xRlz81sw2vVHbEtiuuTCCa0zzGlMPnpLfRF7RAxH2UpdyZmzIe_aEQwfda7NY26vlTPHGKDvY8b6pKZ581ED7h42RL2uL6x4W6t2MWSYEw&token_type=Bearer&expires_at=1794419545 -- re-navigating to https://fastscout.fastmodelsports.com/teams/myTeam/analytics/dashboard?league=NCAAB-III&season=25
    [auth-retry] re-navigated, now at https://fastscout.fastmodelsports.com/teams/myTeam/analytics/dashboard?league=NCAAB-III&season=25 -- waiting for 'text=SCHEDULE'
    [login] confirmed logged in, landed on https://fastscout.fastmodelsports.com/teams/myTeam/analytics/dashboard?league=NCAAB-III&season=26
    [login] WARNING: requested season='25' but FastScout's "myTeam" redirect landed on season='26' instead -- this account's "current" season has moved on. Any view reached via "myTeam" from here (e.g. the live schedule scrape below) may now be showing season 26 data instead of season 25. Verify the scraped schedule's games actually belong to the intended season before trusting this run's output.
    [save] myTeam analytics dashboard (diagnostic) -> myTeam - Analytics Dashboard.html
  Skipping live scrape for Ripon Red Hawks -- a local schedule file already exists.
  Skipping live scrape for St. Thomas (TX) Celts -- a local schedule file already exists.
  Skipping live scrape for Eureka Red Devils -- a local schedule file already exists.
  Skipping live scrape for Aurora Spartans -- a local schedule file already exists.
  Skipping live scrape for Simpson Storm -- a local schedule file already exists.
  Skipping live scrape for Elmhurst Bluejays -- a local schedule file already exists.
  Skipping live scrape for Lawrence Vikings -- a local schedule file already exists.
  Skipping live scrape for Carroll (WI) Pioneers -- a local schedule file already exists.
  Skipping live scrape for Hope Flying Dutchmen -- a local schedule file already exists.
  Skipping live scrape for Alma Scots -- a local schedule file already exists.
  Skipping live scrape for Coe Kohawks -- a local schedule file already exists.
  Skipping live scrape for UW-Oshkosh Titans -- a local schedule file already exists.
  Skipping live scrape for UW-Stevens Point Pointers -- a local schedule file already exists.
  Skipping live scrape for UW-River Falls Falcons -- a local schedule file already exists.
  Skipping live scrape for UW-La Crosse Eagles -- a local schedule file already exists.
  Skipping live scrape for UW-Stout Blue Devils -- a local schedule file already exists.
  Skipping live scrape for UW-Platteville Pioneers -- a local schedule file already exists.
  Skipping live scrape for UW-Eau Claire Blugolds -- a local schedule file already exists.
  Skipping live scrape for Loras Duhawks -- a local schedule file already exists.
  Skipping live scrape for Washington-St. Louis Bears -- a local schedule file already exists.
  Skipping live scrape for Wheaton (IL) Thunder -- a local schedule file already exists.
  Falling back to local backup MHTML for Ripon Red Hawks: Ripon Red Hawks - Schedule.html
  Ripon Red Hawks (Ripon Red Hawks - Schedule.html): 26 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for St. Thomas (TX) Celts: St. Thomas (TX) Celts - Schedule.html
  St. Thomas (TX) Celts (St. Thomas (TX) Celts - Schedule.html): 30 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Eureka Red Devils: Eureka Red Devils - Schedule.html
  Eureka Red Devils (Eureka Red Devils - Schedule.html): 27 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Aurora Spartans: Aurora Spartans - Schedule.html
  Aurora Spartans (Aurora Spartans - Schedule.html): 29 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Simpson Storm: Simpson Storm - Schedule.html
  Simpson Storm (Simpson Storm - Schedule.html): 26 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Elmhurst Bluejays: Elmhurst Bluejays - Schedule.html
  Elmhurst Bluejays (Elmhurst Bluejays - Schedule.html): 28 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Lawrence Vikings: Lawrence Vikings - Schedule.html
  Lawrence Vikings (Lawrence Vikings - Schedule.html): 26 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Carroll (WI) Pioneers: Carroll (WI) Pioneers - Schedule.html
  Carroll (WI) Pioneers (Carroll (WI) Pioneers - Schedule.html): 26 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Hope Flying Dutchmen: Hope Flying Dutchmen - Schedule.html
  Hope Flying Dutchmen (Hope Flying Dutchmen - Schedule.html): 28 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Alma Scots: Alma Scots - Schedule.html
  Alma Scots (Alma Scots - Schedule.html): 27 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Coe Kohawks: Coe Kohawks - Schedule.html
  Coe Kohawks (Coe Kohawks - Schedule.html): 29 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for UW-Oshkosh Titans: UW-Oshkosh Titans - Schedule.html
  UW-Oshkosh Titans (UW-Oshkosh Titans - Schedule.html): 26 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for UW-Stevens Point Pointers: UW-Stevens Point Pointers - Schedule.html
  UW-Stevens Point Pointers (UW-Stevens Point Pointers - Schedule.html): 28 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for UW-River Falls Falcons: UW-River Falls Falcons - Schedule.html
  UW-River Falls Falcons (UW-River Falls Falcons - Schedule.html): 26 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for UW-La Crosse Eagles: UW-La Crosse Eagles - Schedule.html
  UW-La Crosse Eagles (UW-La Crosse Eagles - Schedule.html): 30 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for UW-Stout Blue Devils: UW-Stout Blue Devils - Schedule.html
  UW-Stout Blue Devils (UW-Stout Blue Devils - Schedule.html): 27 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for UW-Platteville Pioneers: UW-Platteville Pioneers - Schedule.html
  UW-Platteville Pioneers (UW-Platteville Pioneers - Schedule.html): 29 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for UW-Eau Claire Blugolds: UW-Eau Claire Blugolds - Schedule.html
  UW-Eau Claire Blugolds (UW-Eau Claire Blugolds - Schedule.html): 25 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Loras Duhawks: Loras Duhawks - Schedule.html
  Loras Duhawks (Loras Duhawks - Schedule.html): 29 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Washington-St. Louis Bears: Washington-St. Louis Bears - Schedule_2025.html
  Washington-St. Louis Bears (Washington-St. Louis Bears - Schedule_2025.html): 27 game(s) -- all games before 2026-3-8
  Falling back to local backup MHTML for Wheaton (IL) Thunder: Wheaton (IL) Thunder - Schedule_2025.html
  Wheaton (IL) Thunder (Wheaton (IL) Thunder - Schedule_2025.html): 26 game(s) -- all games before 2026-3-8
Synergy game IDs: 28 of 29 played UWW game(s), 586 game row(s) in all -- no video link on FastScout for: Wed, Feb 18 UW-Stevens Point Pointers
            date               opponent                    team  \
0     Fri, Nov 7        Ripon Red Hawks  UW-Whitewater Warhawks
1    Fri, Nov 14  St. Thomas (TX) Celts  UW-Whitewater Warhawks
2    Sat, Nov 15      Eureka Red Devils  UW-Whitewater Warhawks
3    Wed, Nov 19        Aurora Spartans  UW-Whitewater Warhawks
4    Tue, Nov 25          Simpson Storm  UW-Whitewater Warhawks
..           ...                    ...                     ...
600  Wed, Feb 11      Elmhurst Bluejays    Wheaton (IL) Thunder
601  Sat, Feb 14     North Park Vikings    Wheaton (IL) Thunder
602  Wed, Feb 18     Carthage Firebirds    Wheaton (IL) Thunder
603  Sat, Feb 21      Millikin Big Blue    Wheaton (IL) Thunder
604  Tue, Feb 24     North Park Vikings    Wheaton (IL) Thunder

          location                                       opponent_url  \
0             Away  https://fastscout.fastmodelsports.com/teams/NY...
1    Neutral Court  https://fastscout.fastmodelsports.com/teams/an...
2    Neutral Court  https://fastscout.fastmodelsports.com/teams/jV...
3             Home  https://fastscout.fastmodelsports.com/teams/Ux...
4             Home  https://fastscout.fastmodelsports.com/teams/gJ...
..             ...                                                ...
600           Away  https://fastscout.fastmodelsports.com/teams/wI...
601           Away  https://fastscout.fastmodelsports.com/teams/23...
602           Home  https://fastscout.fastmodelsports.com/teams/m-...
603           Home  https://fastscout.fastmodelsports.com/teams/PZ...
604           Away  https://fastscout.fastmodelsports.com/teams/23...

                                              game_url  \
0    https://fastscout.fastmodelsports.com/teams/YN...
1    https://fastscout.fastmodelsports.com/teams/YN...
2    https://fastscout.fastmodelsports.com/teams/YN...
3    https://fastscout.fastmodelsports.com/teams/YN...
4    https://fastscout.fastmodelsports.com/teams/YN...
..                                                 ...
600  https://fastscout.fastmodelsports.com/teams/iw...
601  https://fastscout.fastmodelsports.com/teams/iw...
602  https://fastscout.fastmodelsports.com/teams/iw...
603  https://fastscout.fastmodelsports.com/teams/iw...
604  https://fastscout.fastmodelsports.com/teams/iw...

                                             video_url  \
0    https://editor-web.synergysports.com/video?pla...
1    https://editor-web.synergysports.com/video?pla...
2    https://editor-web.synergysports.com/video?pla...
3    https://editor-web.synergysports.com/video?pla...
4    https://editor-web.synergysports.com/video?pla...
..                                                 ...
600  https://editor-web.synergysports.com/video?pla...
601  https://editor-web.synergysports.com/video?pla...
602  https://editor-web.synergysports.com/video?pla...
603  https://editor-web.synergysports.com/video?pla...
604  https://editor-web.synergysports.com/video?pla...

              synergy_game_id  \
0    68dce749ed0cee8bbd101a32
1    68deda8125423a1fd110a592
2    68dd65d8fe000370dae0eae6
3    68dc5148e106e7b276af199f
4    68d7de383c744037aaf49e8f
..                        ...
600  68d9b0a1c95ff04e3e97d06a
601  68d9bc59012933168a26c364
602  68e30e48ad39451edb2982a9
603  68d9b67caa23efd9b2af7c2c
604  699dc391dc2261b6874ffc38

                                  synergy_boxscore_url outcome  team_score  \
0    https://apps.synergysports.com/basketball/game...       W        76.0
1    https://apps.synergysports.com/basketball/game...       L        73.0
2    https://apps.synergysports.com/basketball/game...       W       116.0
3    https://apps.synergysports.com/basketball/game...       W        82.0
4    https://apps.synergysports.com/basketball/game...       W       100.0
..                                                 ...     ...         ...
600  https://apps.synergysports.com/basketball/game...       L        79.0
601  https://apps.synergysports.com/basketball/game...       L        92.0
602  https://apps.synergysports.com/basketball/game...       W        96.0
603  https://apps.synergysports.com/basketball/game...       L        67.0
604  https://apps.synergysports.com/basketball/game...       L       100.0

     opponent_score  point_margin   season Upcoming game_type  note
0              58.0          18.0  2025-26       No      None  None
1              81.0          -8.0  2025-26       No      None  None
2              73.0          43.0  2025-26       No      None  None
3              73.0           9.0  2025-26       No      None  None
4              78.0          22.0  2025-26       No      None  None
..              ...           ...      ...      ...       ...   ...
600            80.0          -1.0  2025-26       No       NaN   NaN
601            95.0          -3.0  2025-26       No       NaN   NaN
602            88.0           8.0  2025-26       No       NaN   NaN
603            70.0          -3.0  2025-26       No       NaN   NaN
604           107.0          -7.0  2025-26       No       NaN   NaN

[605 rows x 17 columns]
  [time] 02_parse_every_team_schedule_scrape_live_from: 1.1 min
    jersey_number                  PLAYER  GP-GS   MIN      FGM-A    FG%  \
0            14.0            Mikey Wildes    4-0     2    0.0-0.2     0%
1            24.0           Richie Warren  29-24    22    3.5-8.1  43.2%
2             0.0            Isaac Verges  27-26    23    3.5-6.7  52.5%
3            23.0          Mauryon Turner      -     -          -      -
4            23.0         Maurquis Turner    3-0     3    0.7-1.0  66.7%
5            40.0  Tyshawn Teague-Johnson   18-1    11    1.7-3.9  42.9%
6            35.0           Rashad Rogers   19-2     9    0.8-1.7  48.5%
7             5.0         Isaiah Robinson   20-0     8    0.4-1.0  33.3%
8            12.0              Jake Quast   28-0    16    2.0-4.0  51.4%
9            30.0           Matthew McKay    3-0     2    0.7-0.7   100%
10            2.0           Kelton McEwen   28-0    11    1.1-2.6  41.7%
11           21.0            Brock Marino  28-27    21    3.2-6.1  52.3%
12           15.0           Collin Madson  29-29    33   5.8-10.5  55.6%
13           25.0          Tristian Lynch    2-0     4    0.5-1.5  33.3%
14           11.0            JR Lukenbill   26-6    13    1.1-2.3  45.9%
15            1.0         Agape Keyes Jr.    6-0     4    0.5-2.0    25%
16            3.0              Zay Howard    3-0     1    0.0-0.7     0%
17           33.0         Trent Grunewald    6-0     4    0.2-1.2  14.3%
18           30.0          Spencer Cullum      -     -          -      -
19           10.0         Darius Chestnut   18-0    10    1.3-2.5  51.1%
20           22.0         Joey Berezowitz   29-1    14    1.2-2.4  49.3%
21           32.0               Luke Bara  29-29    24    3.2-8.2  38.7%
22           20.0          Austin Ambrose    8-0     9    1.1-2.5    45%
23            NaN              Team Total     29  5825  27.3-57.3  47.6%
24            NaN                Opponent     29  5825  24.3-53.6  45.4%

       3PM-A    3P%   3P-R      FTM-A    FT%   PTS   ORB   DRB   REB   AST  \
0    0.0-0.0      -     0%    0.0-0.0      -   0.0   0.0   0.2   0.2   0.2
1    0.3-1.2    25%  15.3%    1.3-2.1    65%   8.7   1.5   3.4   4.9   1.1
2    0.4-1.2  37.5%  17.7%    2.3-3.3  71.6%   9.8   1.5   2.9   4.4   1.9
3          -      -      -          -      -     -     -     -     -     -
4    0.0-0.0      -     0%    0.0-0.7     0%   1.3   0.0   0.3   0.3   0.0
5    0.4-1.0  38.9%  25.7%    0.4-1.2  36.4%   4.2   0.9   1.1   2.0   0.3
6    0.1-0.4  28.6%  21.2%    0.5-0.7  69.2%   2.3   0.6   1.4   2.1   0.5
7    0.2-0.6  23.1%  61.9%    0.2-0.5    50%   1.1   0.2   0.3   0.5   0.6

                             category         stat_cols                                                        example_phrases                                                             why_chosen
0           Ball Security / Turnovers                TO  ball security, turnover, protect/take care of the ball, limit turn...  Directly named -- "ball security"/"turnovers" have a 1:1 stat colu...
1                          Rebounding     REB, ORB, DRB  own the paint, bully/dominate the glass, rebound, board, second ch...  "Glass"/"board"/"crash"/"own the paint" possession language in thi...
2                Three-Point Shooting        3PM-A, 3P%  three, 3 pt, 3pt, perimeter shooting, spacing, shooting ability, s...  Direct stat match for perimeter shot volume/efficiency. Expanded w...
3                         Free Throws        FTM-A, FT%                                     free throw, ft line, getting to ft  Direct stat match. Added "ft line" / "getting to ft" from Aurora (...
4                  Fouls / Discipline                PF                                           foul, wall up, drawing fouls  Direct stat match for foul-discipline emphasis. Added "wall up" (A...
5             Ball Movement / Assists               AST   assist, ball movement, share the ball, playmaking, playmaker, create  Direct stat match for offensive ball-sharing emphasis. Added "play...
6           Paint Protection / Blocks               BLK                               block, protect the rim, paint protection                 Direct stat match for interior shot-blocking emphasis.
7   Perimeter Defense / Ball Pressure               STL  steal, press capable, full court press, force turnovers, force to'...  Renamed from "Ball Pressure / Steals" once Aurora/Eureka/Elmhurst ...
8                      Scoring Inside  FG2M, FG2A, FG2%  dominate the paint, attack the paint, live in the paint, attack th...  Interior-scoring emphasis -- uses derived 2PT FG stats (FGM-FG3M, ...
9               Field Goal Efficiency        FGM-A, FG%                                                    limit their scoring  Overall shooting efficiency emphasis -- used when the scouting not...
10           (intentionally unmapped)                 -  communication screening action / communicate screens & actions (Ri...  No corresponding stat exists in a season box score for screen-navi...

No season boxscore table found for 'Hope Flying Dutchmen'.
Adding 64 box-score-only player(s) with no scouting writeup (defaulted to role=Bench):

                 opponent jersey_number              name
8   St. Thomas (TX) Celts           #23        Jaden Ross
10  St. Thomas (TX) Celts           #11   Tamarcus Butler
11  St. Thomas (TX) Celts           #13     Legborsi Mato
18      Eureka Red Devils           #35    Max Richardson
20      Eureka Red Devils           #20        Nolan Kerr
21      Eureka Red Devils           #22        Tony Mabon
22      Eureka Red Devils           #15   Amare Brokemond
23      Eureka Red Devils            #3     Blake Logsdon
24      Eureka Red Devils            #0     Colin DeLaere
25      Eureka Red Devils            #1     Dylan Logsdon
33        Aurora Spartans            #0      Cullen Rauls
36        Aurora Spartans           #30         Alex Ross
37        Aurora Spartans           #21   Isaiah Thompson
46          Simpson Storm           #35  Nathaniel Winter
47          Simpson Storm           #15       Seth Gipple

  ... 49 more row(s) of 64 (SHOW_ROWS = 15)
Scouting-report player statistics are disabled by design (PDF reports are last-season data) -- player_profiles stat columns start blank and are only filled in by the PBP-derived override further down this notebook, from real current-season games.
                       opponent jersey_number                name     role  \
0         St. Thomas (TX) Celts           #10       Angel Johnson  Starter
1         St. Thomas (TX) Celts            #1      Corey Thompson  Starter
2         St. Thomas (TX) Celts            #0      Nathan Kongolo  Starter
3         St. Thomas (TX) Celts           #12    Nicholas Buffalo  Starter
4         St. Thomas (TX) Celts           #25     Charles Gitonga  Starter
..                          ...           ...                 ...      ...
221               Loras Duhawks           #35          Dylan Kurt    Bench
222               Loras Duhawks           #15        Brock Massey    Bench
223               Loras Duhawks           #30        Patrick Coen    Bench
224               Loras Duhawks           #22  Patrick Quarnstrom    Bench
225  Washington-St. Louis Bears           #15          Jake Davis    Bench

                      notes_tags_display  \
0                              playmaker
1    slasher_driver, three_point_shooter
2                         slasher_driver
3              rebounder, slasher_driver
4                         slasher_driver
..                                   ...
221
222
223
224
225

                         keys_tags_display   PTS   REB   AST   FG%   3P%
0    anticipate_move, deny_catch_and_shoot  None  None  None  None  None
1                          anticipate_move  None  None  None  None  None
2                          anticipate_move  None  None  None  None  None
3                         box_out_priority  None  None  None  None  None
4                          anticipate_move  None  None  None  None  None
..                                     ...   ...   ...   ...   ...   ...
221                                         None  None  None  None  None
222                                         None  None  None  None  None
223                                         None  None  None  None  None
224                                         None  None  None  None  None
225                                         None  None  None  None  None

[226 rows x 11 columns]
Opponent production by role (Starter vs Bench) for the stat(s) behind each matched Keys-to-Victory category:
Empty DataFrame
Columns: [opponent, outcome, category, role, stat, players_with_data, avg_per_player, role_total]
Index: []
No count-type stats available yet to compare Starter vs Bench totals for the matched categories.
No scout report on file for the next scheduled opponent (Wheaton (IL) Thunder) -- using the schedule's own name for them as the short name, so their prior-game PBP (season leaders, team stats, lineups) is still built. Only the scouting-report-sourced output (game plan, keys to victory, player notes, tag-based comparisons) will be missing.
Roster targets this run: ['UW-Whitewater Warhawks', 'Ripon Red Hawks', 'St. Thomas (TX) Celts', 'Eureka Red Devils', 'Aurora Spartans', 'Simpson Storm', 'Elmhurst Bluejays', 'Lawrence Vikings', 'Carroll (WI) Pioneers', 'Hope Flying Dutchmen', 'Alma Scots', 'Coe Kohawks', 'UW-Oshkosh Titans', 'UW-Stevens Point Pointers', 'UW-River Falls Falcons', 'UW-La Crosse Eagles', 'UW-Stout Blue Devils', 'UW-Platteville Pioneers', 'UW-Eau Claire Blugolds', 'Loras Duhawks', 'Washington-St. Louis Bears', 'Wheaton (IL) Thunder']
  Skipping live roster scrape for UW-Whitewater Warhawks -- a local roster file already exists.
  Skipping live roster scrape for Ripon Red Hawks -- a local roster file already exists.
  Skipping live roster scrape for St. Thomas (TX) Celts -- a local roster file already exists.
  Skipping live roster scrape for Eureka Red Devils -- a local roster file already exists.
  Skipping live roster scrape for Aurora Spartans -- a local roster file already exists.
  Skipping live roster scrape for Simpson Storm -- a local roster file already exists.
  Skipping live roster scrape for Elmhurst Bluejays -- a local roster file already exists.
  Skipping live roster scrape for Lawrence Vikings -- a local roster file already exists.
  Skipping live roster scrape for Carroll (WI) Pioneers -- a local roster file already exists.
  Skipping live roster scrape for Hope Flying Dutchmen -- a local roster file already exists.
  Skipping live roster scrape for Alma Scots -- a local roster file already exists.
  Skipping live roster scrape for Coe Kohawks -- a local roster file already exists.
  Skipping live roster scrape for UW-Oshkosh Titans -- a local roster file already exists.
  Skipping live roster scrape for UW-Stevens Point Pointers -- a local roster file already exists.
  Skipping live roster scrape for UW-River Falls Falcons -- a local roster file already exists.
  Skipping live roster scrape for UW-La Crosse Eagles -- a local roster file already exists.
  Skipping live roster scrape for UW-Stout Blue Devils -- a local roster file already exists.
  Skipping live roster scrape for UW-Platteville Pioneers -- a local roster file already exists.
  Skipping live roster scrape for UW-Eau Claire Blugolds -- a local roster file already exists.
  Skipping live roster scrape for Loras Duhawks -- a local roster file already exists.
  Skipping live roster scrape for Washington-St. Louis Bears -- a local roster file already exists.
  Skipping live roster scrape for Wheaton (IL) Thunder -- a local roster file already exists.
    [roster] UW-Whitewater Warhawks: 19 photo(s) matched by name in the URL, 2 fell back to page position (lower confidence -- spot-check these).
    [roster] St. Thomas (TX) Celts: 20 photo(s) matched by name in the URL, 1 fell back to page position (lower confidence -- spot-check these).
    [roster] Eureka Red Devils: 25 photo(s) matched by name in the URL, 6 fell back to page position (lower confidence -- spot-check these).
    [roster] Aurora Spartans: 23 photo(s) matched by name in the URL, 4 fell back to page position (lower confidence -- spot-check these).
    [roster] Carroll (WI) Pioneers: 16 photo(s) matched by name in the URL, 2 fell back to page position (lower confidence -- spot-check these).
    [roster] UW-Stevens Point Pointers: 18 photo(s) matched by name in the URL, 2 fell back to page position (lower confidence -- spot-check these).
    [roster] UW-River Falls Falcons: 15 photo(s) matched by name in the URL, 1 fell back to page position (lower confidence -- spot-check these).
    [roster] UW-La Crosse Eagles: 16 photo(s) matched by name in the URL, 1 fell back to page position (lower confidence -- spot-check these).
    [roster] UW-Stout Blue Devils: 19 photo(s) matched by name in the URL, 1 fell back to page position (lower confidence -- spot-check these).
    [roster] UW-Platteville Pioneers: 18 photo(s) matched by name in the URL, 1 fell back to page position (lower confidence -- spot-check these).
    [roster] Wheaton (IL) Thunder: 21 photo(s) matched by name in the URL, 2 fell back to page position (lower confidence -- spot-check these).

live_rosters: 476 player(s) across 22 team(s).

                        value
team
Alma Scots                 29
Aurora Spartans            27
Carroll (WI) Pioneers      18
Coe Kohawks                23
Elmhurst Bluejays          25
Eureka Red Devils          31
Hope Flying Dutchmen       19
Lawrence Vikings           20
Loras Duhawks              20
Ripon Red Hawks            26
Simpson Storm              21
St. Thomas (TX) Celts      21
UW-Eau Claire Blugolds     20
UW-La Crosse Eagles        17
UW-Oshkosh Titans          22

  ... 7 more row(s) of 22 (SHOW_ROWS = 15)
Wheaton (IL) Thunder's games before facing UW-Whitewater on 2026-03-08:
           date   game_date                      opponent outcome  team_score  \
0    Sat, Nov 8  2025-11-08   Concordia Wisconsin Falcons       W        99.0
1   Wed, Nov 12  2025-11-12         Lake Forest Foresters       W        93.0
2   Sat, Nov 15  2025-11-15          Hope Flying Dutchmen       L        75.0
3   Tue, Nov 18  2025-11-18       Benedictine (IL) Eagles       W        95.0
4   Fri, Nov 21  2025-11-21        St. Scholastica Saints       W        85.0
5   Sat, Nov 22  2025-11-22           UW-La Crosse Eagles       L        66.0
6   Tue, Nov 25  2025-11-25           Manchester Spartans       W        95.0
7    Wed, Dec 3  2025-12-03        Augustana (IL) Vikings       L        81.0
8    Sat, Dec 6  2025-12-06             Elmhurst Bluejays       W        82.0
9   Sat, Dec 13  2025-12-13            Carthage Firebirds       L        59.0
10  Wed, Dec 31  2025-12-31   Wisconsin Lutheran Warriors       W        83.0
11   Sat, Jan 3  2026-01-03               Chicago Maroons       L        73.0
12   Wed, Jan 7  2026-01-07         Carroll (WI) Pioneers       W        85.0
13  Sat, Jan 10  2026-01-10  North Central (IL) Cardinals       W        72.0
14  Wed, Jan 14  2026-01-14             Millikin Big Blue       W        88.0
15  Sat, Jan 17  2026-01-17      Illinois Wesleyan Titans       L        61.0
16  Sat, Jan 24  2026-01-24            North Park Vikings       W        94.0
17  Wed, Jan 28  2026-01-28        Augustana (IL) Vikings       W        71.0
18  Sat, Jan 31  2026-01-31         Carroll (WI) Pioneers       L        84.0
19   Wed, Feb 4  2026-02-04      Illinois Wesleyan Titans       L        71.0
20   Sat, Feb 7  2026-02-07  North Central (IL) Cardinals       L        74.0
21  Wed, Feb 11  2026-02-11             Elmhurst Bluejays       L        79.0
22  Sat, Feb 14  2026-02-14            North Park Vikings       L        92.0
23  Wed, Feb 18  2026-02-18            Carthage Firebirds       W        96.0
24  Sat, Feb 21  2026-02-21             Millikin Big Blue       L        67.0
25  Tue, Feb 24  2026-02-24            North Park Vikings       L       100.0

    opponent_score  \
0             95.0
1             89.0
2             76.0
3             80.0
4             64.0
5             70.0
6             88.0
7             84.0
8             81.0
9             77.0
10            56.0
11            94.0
12            84.0
13            71.0
14            76.0
15            80.0
16            85.0
17            65.0
18            90.0
19            82.0
20            81.0
21            80.0
22            95.0
23            88.0
24            70.0
25           107.0

                                                                                                                                                                 video_url  \
0   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9beaf12352eede8950383%2ffullgamevideo%2fclips
1   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9beb012352eede8950384%2ffullgamevideo%2fclips
2   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9beb012352eede8950385%2ffullgamevideo%2fclips
3   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9beb012352eede8950386%2ffullgamevideo%2fclips
4   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9beb012352eede8950387%2ffullgamevideo%2fclips
5   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f692134d71462205e0d8144da%2ffullgamevideo%2fclips
6   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9beb012352eede8950388%2ffullgamevideo%2fclips
7   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d936c1736bdd6d0380609e%2ffullgamevideo%2fclips
8   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9b0a0c95ff04e3e97d05d%2ffullgamevideo%2fclips
9   https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9beb012352eede8950389%2ffullgamevideo%2fclips
10  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9beb012352eede895038a%2ffullgamevideo%2fclips
11  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68dac788c34cc4b7283e6081%2ffullgamevideo%2fclips
12  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a3e%2ffullgamevideo%2fclips
13  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9ba00c24a7211210753bd%2ffullgamevideo%2fclips
14  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9b67caa23efd9b2af7c27%2ffullgamevideo%2fclips
15  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9b426302de8e9f52a6a55%2ffullgamevideo%2fclips
16  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9bc58012933168a26c362%2ffullgamevideo%2fclips
17  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d936c2736bdd6d038060a9%2ffullgamevideo%2fclips
18  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a44%2ffullgamevideo%2fclips
19  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9b426302de8e9f52a6a59%2ffullgamevideo%2fclips
20  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9ba00c24a7211210753c0%2ffullgamevideo%2fclips
21  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9b0a1c95ff04e3e97d06a%2ffullgamevideo%2fclips
22  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9bc59012933168a26c364%2ffullgamevideo%2fclips
23  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68e30e48ad39451edb2982a9%2ffullgamevideo%2fclips
24  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9b67caa23efd9b2af7c2c%2ffullgamevideo%2fclips
25  https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f699dc391dc2261b6874ffc38%2ffullgamevideo%2fclips

             synergy_game_id  \
0   68d9beaf12352eede8950383
1   68d9beb012352eede8950384
2   68d9beb012352eede8950385
3   68d9beb012352eede8950386
4   68d9beb012352eede8950387
5   692134d71462205e0d8144da
6   68d9beb012352eede8950388
7   68d936c1736bdd6d0380609e
8   68d9b0a0c95ff04e3e97d05d
9   68d9beb012352eede8950389
10  68d9beb012352eede895038a
11  68dac788c34cc4b7283e6081
12  68d9391a7965f79863570a3e
13  68d9ba00c24a7211210753bd
14  68d9b67caa23efd9b2af7c27
15  68d9b426302de8e9f52a6a55
16  68d9bc58012933168a26c362
17  68d936c2736bdd6d038060a9
18  68d9391a7965f79863570a44
19  68d9b426302de8e9f52a6a59
20  68d9ba00c24a7211210753c0
21  68d9b0a1c95ff04e3e97d06a
22  68d9bc59012933168a26c364
23  68e30e48ad39451edb2982a9
24  68d9b67caa23efd9b2af7c2c
25  699dc391dc2261b6874ffc38

                                                                 synergy_boxscore_url  \
0   https://apps.synergysports.com/basketball/games/68d9beaf12352eede8950383/boxscore
1   https://apps.synergysports.com/basketball/games/68d9beb012352eede8950384/boxscore
2   https://apps.synergysports.com/basketball/games/68d9beb012352eede8950385/boxscore
3   https://apps.synergysports.com/basketball/games/68d9beb012352eede8950386/boxscore
4   https://apps.synergysports.com/basketball/games/68d9beb012352eede8950387/boxscore
5   https://apps.synergysports.com/basketball/games/692134d71462205e0d8144da/boxscore
6   https://apps.synergysports.com/basketball/games/68d9beb012352eede8950388/boxscore
7   https://apps.synergysports.com/basketball/games/68d936c1736bdd6d0380609e/boxscore
8   https://apps.synergysports.com/basketball/games/68d9b0a0c95ff04e3e97d05d/boxscore
9   https://apps.synergysports.com/basketball/games/68d9beb012352eede8950389/boxscore
10  https://apps.synergysports.com/basketball/games/68d9beb012352eede895038a/boxscore
11  https://apps.synergysports.com/basketball/games/68dac788c34cc4b7283e6081/boxscore
12  https://apps.synergysports.com/basketball/games/68d9391a7965f79863570a3e/boxscore
13  https://apps.synergysports.com/basketball/games/68d9ba00c24a7211210753bd/boxscore
14  https://apps.synergysports.com/basketball/games/68d9b67caa23efd9b2af7c27/boxscore
15  https://apps.synergysports.com/basketball/games/68d9b426302de8e9f52a6a55/boxscore
16  https://apps.synergysports.com/basketball/games/68d9bc58012933168a26c362/boxscore
17  https://apps.synergysports.com/basketball/games/68d936c2736bdd6d038060a9/boxscore
18  https://apps.synergysports.com/basketball/games/68d9391a7965f79863570a44/boxscore
19  https://apps.synergysports.com/basketball/games/68d9b426302de8e9f52a6a59/boxscore
20  https://apps.synergysports.com/basketball/games/68d9ba00c24a7211210753c0/boxscore
21  https://apps.synergysports.com/basketball/games/68d9b0a1c95ff04e3e97d06a/boxscore
22  https://apps.synergysports.com/basketball/games/68d9bc59012933168a26c364/boxscore
23  https://apps.synergysports.com/basketball/games/68e30e48ad39451edb2982a9/boxscore
24  https://apps.synergysports.com/basketball/games/68d9b67caa23efd9b2af7c2c/boxscore
25  https://apps.synergysports.com/basketball/games/699dc391dc2261b6874ffc38/boxscore

                                                                                                                               game_url  \
0   https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/JXnJHeFGSNi-Shuw8g1qsQ/boxscore?league=NCAAB-III&season=25
1   https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/oMElBQchQ_C6GvxtEwr5bA/boxscore?league=NCAAB-III&season=25
2   https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/SdRPh_2GRVqJQ35iszUE-A/boxscore?league=NCAAB-III&season=25
3   https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/slG7g7CcSzWM4R6sEK6MpQ/boxscore?league=NCAAB-III&season=25
4   https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/4uwO3_sqRsa2IdCqvIrLAg/boxscore?league=NCAAB-III&season=25
5   https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/TSz31BsFRqKQHI8mYVLgSA/boxscore?league=NCAAB-III&season=25
6   https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/y7SHo9SmQBaAs-yujTH9Fw/boxscore?league=NCAAB-III&season=25
7   https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/Kobb0t8-SpavHOHkk3RDHw/boxscore?league=NCAAB-III&season=25
8   https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/PILckfbdTTGrbVvFqS9zLQ/boxscore?league=NCAAB-III&season=25
9   https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/ML9gAzpTQ0uKKzXFpwWTYQ/boxscore?league=NCAAB-III&season=25
10  https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/gEEA3YZdQFyaISrkidI6_Q/boxscore?league=NCAAB-III&season=25
11  https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/1xTeumBRTViT68O17RdV9g/boxscore?league=NCAAB-III&season=25
12  https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/auMExbXKTI2SOivcRw-0iA/boxscore?league=NCAAB-III&season=25
13  https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/Qyaso4i3QWC-UDZcKBv90w/boxscore?league=NCAAB-III&season=25
14  https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/WKjFCaq0RymDJcxDg59sOA/boxscore?league=NCAAB-III&season=25
15  https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/wxDNi1XaTHKydU6r90pr5g/boxscore?league=NCAAB-III&season=25
16  https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/zGCWxRp2R6W-BOq8xaP59A/boxscore?league=NCAAB-III&season=25
17  https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/tTirI1EZSgag88WVqtP0dg/boxscore?league=NCAAB-III&season=25
18  https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/h9QY9YxpQg6A_z7rcfdu3g/boxscore?league=NCAAB-III&season=25
19  https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/v4RO0jRpSn2SEomlqODSfA/boxscore?league=NCAAB-III&season=25
20  https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/AC-uKF_JRpeSuoHrA9uidg/boxscore?league=NCAAB-III&season=25
21  https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/V1idRejdRnS8wD2PNQHqfw/boxscore?league=NCAAB-III&season=25
22  https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/0ohRiTrPRF2fIciBNG4CBw/boxscore?league=NCAAB-III&season=25
23  https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/km9YAHnCTmuyXNmMaH3oSg/boxscore?league=NCAAB-III&season=25
24  https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/QHtymbUtQZ2Iogq68Kjycw/boxscore?league=NCAAB-III&season=25
25  https://fastscout.fastmodelsports.com/teams/iwxO1TLaTX6JnFKJRaBV8A/games/yASwkxY8Tf62MdF5Ks7_lQ/boxscore?league=NCAAB-III&season=25

   location
0      Away
1      Home
2      Away
3      Home
4      Home
5      Home
6      Away
7      Away
8      Home
9      Away
10     Away
11     Away
12     Home
13     Away
14     Away
15     Home
16     Home
17     Home
18     Away
19     Away
20     Home
21     Away
22     Away
23     Home
24     Home
25     Away

Video links for these games (raw full-game film, independent of any manually-tagged _video.mhtml export):
  2025-11-08 vs Concordia Wisconsin Falcons: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9beaf12352eede8950383%2ffullgamevideo%2fclips
  2025-11-12 vs Lake Forest Foresters: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9beb012352eede8950384%2ffullgamevideo%2fclips
  2025-11-15 vs Hope Flying Dutchmen: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9beb012352eede8950385%2ffullgamevideo%2fclips
  2025-11-18 vs Benedictine (IL) Eagles: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9beb012352eede8950386%2ffullgamevideo%2fclips
  2025-11-21 vs St. Scholastica Saints: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9beb012352eede8950387%2ffullgamevideo%2fclips
  2025-11-22 vs UW-La Crosse Eagles: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f692134d71462205e0d8144da%2ffullgamevideo%2fclips
  2025-11-25 vs Manchester Spartans: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9beb012352eede8950388%2ffullgamevideo%2fclips
  2025-12-03 vs Augustana (IL) Vikings: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d936c1736bdd6d0380609e%2ffullgamevideo%2fclips
  2025-12-06 vs Elmhurst Bluejays: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9b0a0c95ff04e3e97d05d%2ffullgamevideo%2fclips
  2025-12-13 vs Carthage Firebirds: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9beb012352eede8950389%2ffullgamevideo%2fclips
  2025-12-31 vs Wisconsin Lutheran Warriors: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9beb012352eede895038a%2ffullgamevideo%2fclips
  2026-01-03 vs Chicago Maroons: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68dac788c34cc4b7283e6081%2ffullgamevideo%2fclips
  2026-01-07 vs Carroll (WI) Pioneers: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a3e%2ffullgamevideo%2fclips
  2026-01-10 vs North Central (IL) Cardinals: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9ba00c24a7211210753bd%2ffullgamevideo%2fclips
  2026-01-14 vs Millikin Big Blue: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9b67caa23efd9b2af7c27%2ffullgamevideo%2fclips
  2026-01-17 vs Illinois Wesleyan Titans: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9b426302de8e9f52a6a55%2ffullgamevideo%2fclips
  2026-01-24 vs North Park Vikings: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9bc58012933168a26c362%2ffullgamevideo%2fclips
  2026-01-28 vs Augustana (IL) Vikings: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d936c2736bdd6d038060a9%2ffullgamevideo%2fclips
  2026-01-31 vs Carroll (WI) Pioneers: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9391a7965f79863570a44%2ffullgamevideo%2fclips
  2026-02-04 vs Illinois Wesleyan Titans: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9b426302de8e9f52a6a59%2ffullgamevideo%2fclips
  2026-02-07 vs North Central (IL) Cardinals: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9ba00c24a7211210753c0%2ffullgamevideo%2fclips
  2026-02-11 vs Elmhurst Bluejays: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9b0a1c95ff04e3e97d06a%2ffullgamevideo%2fclips
  2026-02-14 vs North Park Vikings: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9bc59012933168a26c364%2ffullgamevideo%2fclips
  2026-02-18 vs Carthage Firebirds: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68e30e48ad39451edb2982a9%2ffullgamevideo%2fclips
  2026-02-21 vs Millikin Big Blue: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f68d9b67caa23efd9b2af7c2c%2ffullgamevideo%2fclips
  2026-02-24 vs North Park Vikings: https://editor-web.synergysports.com/video?playlistUrl=https%3a%2f%2fbasketball.synergysportstech.com%2fapi%2fgames%2f699dc391dc2261b6874ffc38%2ffullgamevideo%2fclips


,opponent,game_date,event_order,period,time_remaining,time_remaining_seconds,team,event_type,raw_text,uww_score,opp_score,player,shot_type,shot_desc,foul_type,turnover_type,ft_num,ft_total
0,Concordia Wisconsin Falcons,2025-11-08,0,None,None,NaN,None,period_marker,Start 1st Half,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Concordia Wisconsin Falcons,2025-11-08,1,H1,19:59 (H1),1199.0,Concordia Wisconsin Falcons,jump_ball_won,Logan Landers Wins Jump Ball,0.0,0.0,Logan Landers,NaN,NaN,NaN,NaN,NaN,NaN
2,Concordia Wisconsin Falcons,2025-11-08,2,H1,19:59 (H1),1199.0,Wheaton (IL) Thunder,jump_ball_lost,Carson Grier Loses Jump Ball,0.0,0.0,Carson Grier,NaN,NaN,NaN,NaN,NaN,NaN
3,Concordia Wisconsin Falcons,2025-11-08,3,H1,19:48 (H1),1188.0,Concordia Wisconsin Falcons,missed_shot,Luke Eggemeyer Misses 3PT Jump Shot,0.0,0.0,Luke Eggemeyer,3,Jump Shot,NaN,NaN,NaN,NaN
4,Concordia Wisconsin Falcons,2025-11-08,4,H1,19:44 (H1),1184.0,Wheaton (IL) Thunder,team_deadball_rebound_defensive,Wheaton (IL) Defensive Deadball Rebound,0.0,0.0,Wheaton (IL),NaN,NaN,NaN,NaN,NaN,NaN
5,Concordia Wisconsin Falcons,2025-11-08,5,H1,19:20 (H1),1160.0,Wheaton (IL) Thunder,missed_shot,Soren Richardson Misses 2PT Jump Shot,0.0,0.0,Soren Richardson,2,Jump Shot,NaN,NaN,NaN,NaN
6,Concordia Wisconsin Falcons,2025-11-08,6,H1,19:17 (H1),1157.0,Concordia Wisconsin Falcons,rebound_defensive,Severin Hilt Defensive Rebound,0.0,0.0,Severin Hilt,NaN,NaN,NaN,NaN,NaN,NaN
7,Concordia Wisconsin Falcons,2025-11-08,7,H1,19:12 (H1),1152.0,Concordia Wisconsin Falcons,made_shot,Matt Merlo Makes 2PT Layup,0.0,2.0,Matt Merlo,2,Layup,NaN,NaN,NaN,NaN
8,Concordia Wisconsin Falcons,2025-11-08,8,H1,19:01 (H1),1141.0,Wheaton (IL) Thunder,missed_shot,Soren Richardson Misses 3PT Jump Shot,0.0,2.0,Soren Richardson,3,Jump Shot,NaN,NaN,NaN,NaN
9,Concordia Wisconsin Falcons,2025-11-08,9,H1,18:59 (H1),1139.0,Concordia Wisconsin Falcons,rebound_defensive,Casey Verhagen Defensive Rebound,0.0,2.0,Casey Verhagen,NaN,NaN,NaN,NaN,NaN,NaN
10,Concordia Wisconsin Falcons,2025-11-08,10,H1,18:53 (H1),1133.0,Concordia Wisconsin Falcons,made_shot,Casey Verhagen Makes 2PT Jump Shot,0.0,4.0,Casey Verhagen,2,Jump Shot,NaN,NaN,NaN,NaN
11,Concordia Wisconsin Falcons,2025-11-08,11,H1,18:33 (H1),1113.0,Wheaton (IL) Thunder,missed_shot,Soren Richardson Misses 2PT Jump Shot,0.0,4.0,Soren Richardson,2,Jump Shot,NaN,NaN,NaN,NaN
12,Concordia Wisconsin Falcons,2025-11-08,12,H1,18:30 (H1),1110.0,Concordia Wisconsin Falcons,rebound_defensive,Luke Eggemeyer Defensive Rebound,0.0,4.0,Luke Eggemeyer,NaN,NaN,NaN,NaN,NaN,NaN
13,Concordia Wisconsin Falcons,2025-11-08,13,H1,18:26 (H1),1106.0,Concordia Wisconsin Falcons,foul,Logan Landers Commits Personal Foul,0.0,4.0,Logan Landers,NaN,NaN,Personal Foul,NaN,NaN,NaN
14,Concordia Wisconsin Falcons,2025-11-08,14,H1,18:07 (H1),1087.0,Wheaton (IL) Thunder,made_shot,Carson Grier Makes 2PT Jump Shot,2.0,4.0,Carson Grier,2,Jump Shot,NaN,NaN,NaN,NaN
15,Concordia Wisconsin Falcons,2025-11-08,15,H1,18:07 (H1),1087.0,Wheaton (IL) Thunder,assist,Kyan VanderWoude Assists,2.0,4.0,Kyan VanderWoude,NaN,NaN,NaN,NaN,NaN,NaN
16,Concordia Wisconsin Falcons,2025-11-08,16,H1,17:51 (H1),1071.0,Concordia Wisconsin Falcons,made_shot,Severin Hilt Makes 3PT Jump Shot,2.0,7.0,Severin Hilt,3,Jump Shot,NaN,NaN,NaN,NaN
17,Concordia Wisconsin Falcons,2025-11-08,17,H1,17:51 (H1),1071.0,Concordia Wisconsin Falcons,assist,Casey Verhagen Assists,2.0,7.0,Casey Verhagen,NaN,NaN,NaN,NaN,NaN,NaN
18,Concordia Wisconsin Falcons,2025-11-08,18,H1,17:42 (H1),1062.0,Wheaton (IL) Thunder,turnover,Devin Martin Turnover (Lost Ball),2.0,7.0,Devin Martin,NaN,NaN,NaN,Lost Ball,NaN,NaN
19,Concordia Wisconsin Falcons,2025-11-08,19,H1,17:42 (H1),1062.0,Concordia Wisconsin Falcons,steal,Logan Landers Steals,2.0,7.0,Logan Landers,NaN,NaN,NaN,NaN,NaN,NaN

  ... 12,803 more row(s) of 12,823 (SHOW_ROWS = 20)
  Concordia Wisconsin Falcons: matched 236/245 eligible pbp events to 250 video sub-events (254 clips)
  Lake Forest Foresters: matched 225/238 eligible pbp events to 230 video sub-events (235 clips)
  Hope Flying Dutchmen: matched 207/222 eligible pbp events to 214 video sub-events (224 clips)
  Benedictine (IL) Eagles: matched 216/231 eligible pbp events to 223 video sub-events (228 clips)
  St. Scholastica Saints: matched 187/194 eligible pbp events to 188 video sub-events (197 clips)
  UW-La Crosse Eagles: matched 186/199 eligible pbp events to 190 video sub-events (194 clips)
  Manchester Spartans: matched 172/201 eligible pbp events to 196 video sub-events (195 clips)
  Augustana (IL) Vikings: matched 209/230 eligible pbp events to 219 video sub-events (226 clips)
  Elmhurst Bluejays: matched 213/233 eligible pbp events to 217 video sub-events (223 clips)
  Carthage Firebirds: matched 174/188 eligible pbp events to 180 video sub-events (182 clips)
  Wisconsin Lutheran Warriors: matched 215/232 eligible pbp events to 219 video sub-events (224 clips)
  Chicago Maroons: matched 186/199 eligible pbp events to 190 video sub-events (191 clips)
  Carroll (WI) Pioneers: matched 207/229 eligible pbp events to 215 video sub-events (223 clips)
  North Central (IL) Cardinals: matched 201/221 eligible pbp events to 211 video sub-events (218 clips)
  Millikin Big Blue: matched 189/205 eligible pbp events to 195 video sub-events (206 clips)
  Illinois Wesleyan Titans: matched 199/209 eligible pbp events to 203 video sub-events (207 clips)
  North Park Vikings: matched 217/238 eligible pbp events to 226 video sub-events (237 clips)
  Augustana (IL) Vikings: matched 204/221 eligible pbp events to 208 video sub-events (216 clips)
  Carroll (WI) Pioneers: matched 215/239 eligible pbp events to 226 video sub-events (223 clips)
  Illinois Wesleyan Titans: matched 166/179 eligible pbp events to 169 video sub-events (181 clips)
  North Central (IL) Cardinals: matched 221/235 eligible pbp events to 228 video sub-events (228 clips)
  Elmhurst Bluejays: matched 182/197 eligible pbp events to 186 video sub-events (196 clips)
  North Park Vikings: matched 210/231 eligible pbp events to 222 video sub-events (219 clips)
  Carthage Firebirds: matched 216/232 eligible pbp events to 224 video sub-events (221 clips)
  Millikin Big Blue: matched 214/224 eligible pbp events to 221 video sub-events (226 clips)
  North Park Vikings: matched 280/310 eligible pbp events to 292 video sub-events (301 clips)

Tagged-video coverage for Wheaton (IL) Thunder: 26 of 26 game(s) before facing UWW contributed tagged shots.

     game_date                            vs                                                             video_file  pbp_rows  clips  matched why
0   2025-11-08   Concordia Wisconsin Falcons  11_8_25 Wheaton (IL) Thunder @ Concordia Wisconsin Falcons_video.html       492    254      236
1   2025-11-12         Lake Forest Foresters       11_12_25 Lake Forest Foresters @ Wheaton (IL) Thunder_video.html       522    235      225
2   2025-11-15          Hope Flying Dutchmen        11_15_25 Wheaton (IL) Thunder @ Hope Flying Dutchmen_video.html       498    224      207
3   2025-11-18       Benedictine (IL) Eagles     11_18_25 Benedictine (IL) Eagles @ Wheaton (IL) Thunder_video.html       528    228      216
4   2025-11-21        St. Scholastica Saints      11_21_25 St. Scholastica Saints @ Wheaton (IL) Thunder_video.html       463    197      187
5   2025-11-22           UW-La Crosse Eagles         11_22_25 UW-La Crosse Eagles @ Wheaton (IL) Thunder_video.html       432    194      186
6   2025-11-25           Manchester Spartans         11_25_25 Wheaton (IL) Thunder @ Manchester Spartans_video.html       397    195      172
7   2025-12-03        Augustana (IL) Vikings       12_3_25 Wheaton (IL) Thunder @ Augustana (IL) Vikings_video.html       494    226      209
8   2025-12-06             Elmhurst Bluejays            12_6_25 Elmhurst Bluejays @ Wheaton (IL) Thunder_video.html       536    223      213
9   2025-12-13            Carthage Firebirds          12_13_25 Wheaton (IL) Thunder @ Carthage Firebirds_video.html       413    182      174
10  2025-12-31   Wisconsin Lutheran Warriors  12_31_25 Wheaton (IL) Thunder @ Wisconsin Lutheran Warriors_video....       574    224      215
11  2026-01-03               Chicago Maroons               1_3_26 Wheaton (IL) Thunder @ Chicago Maroons_video.html       456    191      186
12  2026-01-07         Carroll (WI) Pioneers         1_7_26 Carroll (WI) Pioneers @ Wheaton (IL) Thunder_video.html       502    223      207
13  2026-01-10  North Central (IL) Cardinals  1_10_26 Wheaton (IL) Thunder @ North Central (IL) Cardinals_video....       486    218      201
14  2026-01-14             Millikin Big Blue            1_14_26 Wheaton (IL) Thunder @ Millikin Big Blue_video.html       484    206      189

  ... 11 more row(s) of 26 (SHOW_ROWS = 15)

Games with a video-tagging file: ['Concordia Wisconsin Falcons', 'Lake Forest Foresters', 'Hope Flying Dutchmen', 'Benedictine (IL) Eagles', 'St. Scholastica Saints', 'UW-La Crosse Eagles', 'Manchester Spartans', 'Augustana (IL) Vikings', 'Elmhurst Bluejays', 'Carthage Firebirds', 'Wisconsin Lutheran Warriors', 'Chicago Maroons', 'Carroll (WI) Pioneers', 'North Central (IL) Cardinals', 'Millikin Big Blue', 'Illinois Wesleyan Titans', 'North Park Vikings', 'Augustana (IL) Vikings', 'Carroll (WI) Pioneers', 'Illinois Wesleyan Titans', 'North Central (IL) Cardinals', 'Elmhurst Bluejays', 'North Park Vikings', 'Carthage Firebirds', 'Millikin Big Blue', 'North Park Vikings']
pbp_events_upcoming rows with a matched video description: 5347 of 12823

,opponent,game_date,event_order,period,time_remaining,time_remaining_seconds,team,event_type,raw_text,uww_score,opp_score,player,shot_type,shot_desc,foul_type,turnover_type,ft_num,ft_total,video_description,video_result,video_player,video_clip_number
3,Concordia Wisconsin Falcons,2025-11-08,3,H1,19:48 (H1),1188.0,Concordia Wisconsin Falcons,missed_shot,Luke Eggemeyer Misses 3PT Jump Shot,0.0,0.0,Luke Eggemeyer,3,Jump Shot,NaN,NaN,NaN,NaN,34 Luke Eggemeyer > Spot-Up > No Dribble Jumper > Open > Long/3pt ...,Miss 3 Pts,Luke Eggemeyer,1.0
5,Concordia Wisconsin Falcons,2025-11-08,5,H1,19:20 (H1),1160.0,Wheaton (IL) Thunder,missed_shot,Soren Richardson Misses 2PT Jump Shot,0.0,0.0,Soren Richardson,2,Jump Shot,NaN,NaN,NaN,NaN,12 Devin Martin > P&R Ball Handler > Left P&R > Side > Dribble Off...,Miss 2 Pts,Soren Richardson,2.0
7,Concordia Wisconsin Falcons,2025-11-08,7,H1,19:12 (H1),1152.0,Concordia Wisconsin Falcons,made_shot,Matt Merlo Makes 2PT Layup,0.0,2.0,Matt Merlo,2,Layup,NaN,NaN,NaN,NaN,14 Matt Merlo > Transition > Left Wing > To Basket > Make 2 Pts,Make 2 Pts,Matt Merlo,3.0
8,Concordia Wisconsin Falcons,2025-11-08,8,H1,19:01 (H1),1141.0,Wheaton (IL) Thunder,missed_shot,Soren Richardson Misses 3PT Jump Shot,0.0,2.0,Soren Richardson,3,Jump Shot,NaN,NaN,NaN,NaN,4 Kyan VanderWoude > ISO > Right > Defense Commits > Ball Delivere...,Miss 3 Pts,Soren Richardson,4.0
10,Concordia Wisconsin Falcons,2025-11-08,10,H1,18:53 (H1),1133.0,Concordia Wisconsin Falcons,made_shot,Casey Verhagen Makes 2PT Jump Shot,0.0,4.0,Casey Verhagen,2,Jump Shot,NaN,NaN,NaN,NaN,0 Casey Verhagen > P&R Ball Handler > High P&R > Dribble Off Pick ...,Make 2 Pts,Casey Verhagen,5.0
11,Concordia Wisconsin Falcons,2025-11-08,11,H1,18:33 (H1),1113.0,Wheaton (IL) Thunder,missed_shot,Soren Richardson Misses 2PT Jump Shot,0.0,4.0,Soren Richardson,2,Jump Shot,NaN,NaN,NaN,NaN,20 Soren Richardson > Off Screen > To Shooter's Left > Straight > ...,Miss 2 Pts,Soren Richardson,6.0
14,Concordia Wisconsin Falcons,2025-11-08,14,H1,18:07 (H1),1087.0,Wheaton (IL) Thunder,made_shot,Carson Grier Makes 2PT Jump Shot,2.0,4.0,Carson Grier,2,Jump Shot,NaN,NaN,NaN,NaN,34 Carson Grier > Offensive Rebound > Short > Scoring Attempt > At...,Make 2 Pts,Carson Grier,9.0
16,Concordia Wisconsin Falcons,2025-11-08,16,H1,17:51 (H1),1071.0,Concordia Wisconsin Falcons,made_shot,Severin Hilt Makes 3PT Jump Shot,2.0,7.0,Severin Hilt,3,Jump Shot,NaN,NaN,NaN,NaN,0 Casey Verhagen > P&R Ball Handler > High P&R > Dribble Off Pick ...,Make 3 Pts,Severin Hilt,10.0
18,Concordia Wisconsin Falcons,2025-11-08,18,H1,17:42 (H1),1062.0,Wheaton (IL) Thunder,turnover,Devin Martin Turnover (Lost Ball),2.0,7.0,Devin Martin,NaN,NaN,NaN,Lost Ball,NaN,NaN,12 Devin Martin > P&R Ball Handler > High P&R > Dribble Off Pick >...,Turnover,Devin Martin,11.0
20,Concordia Wisconsin Falcons,2025-11-08,20,H1,17:35 (H1),1055.0,Concordia Wisconsin Falcons,made_shot,Severin Hilt Makes 2PT Layup,2.0,9.0,Severin Hilt,2,Layup,NaN,NaN,NaN,NaN,15 Severin Hilt > Transition > Leak Outs > To Basket > Make 2 Pts,Make 2 Pts,Severin Hilt,12.0
22,Concordia Wisconsin Falcons,2025-11-08,22,H1,17:27 (H1),1047.0,Wheaton (IL) Thunder,made_shot,Kyan VanderWoude Makes 2PT Layup,4.0,9.0,Kyan VanderWoude,2,Layup,NaN,NaN,NaN,NaN,4 Kyan VanderWoude > No Play Type > To Basket > Make 2 Pts,Make 2 Pts,Kyan VanderWoude,13.0
23,Concordia Wisconsin Falcons,2025-11-08,23,H1,17:17 (H1),1037.0,Concordia Wisconsin Falcons,missed_shot,Severin Hilt Misses 3PT Jump Shot,4.0,9.0,Severin Hilt,3,Jump Shot,NaN,NaN,NaN,NaN,15 Severin Hilt > Transition > Trailer > Dribble Jumper > Long/3pt...,Miss 3 Pts,Severin Hilt,14.0
27,Concordia Wisconsin Falcons,2025-11-08,27,H1,16:56 (H1),1016.0,Concordia Wisconsin Falcons,foul,Luke Eggemeyer Commits Personal Foul,4.0,9.0,Luke Eggemeyer,NaN,NaN,Personal Foul,NaN,NaN,NaN,20 Soren Richardson > Non Possession > Non Shooting Foul,Non Shooting Foul,Soren Richardson,15.0
28,Concordia Wisconsin Falcons,2025-11-08,28,H1,16:44 (H1),1004.0,Wheaton (IL) Thunder,missed_shot,Kyan VanderWoude Misses 2PT Layup,4.0,9.0,Kyan VanderWoude,2,Layup,NaN,NaN,NaN,NaN,4 Kyan VanderWoude > Spot-Up > Drives Right > To Basket > Miss 2 Pts,Miss 2 Pts,Kyan VanderWoude,16.0
30,Concordia Wisconsin Falcons,2025-11-08,30,H1,16:38 (H1),998.0,Wheaton (IL) Thunder,made_shot,Soren Richardson Makes 3PT Jump Shot,7.0,9.0,Soren Richardson,3,Jump Shot,NaN,NaN,NaN,NaN,20 Soren Richardson > Spot-Up > No Dribble Jumper > Open > Long/3p...,Make 3 Pts,Soren Richardson,17.0
32,Concordia Wisconsin Falcons,2025-11-08,32,H1,16:15 (H1),975.0,Concordia Wisconsin Falcons,missed_shot,Casey Verhagen Misses 2PT Layup,7.0,9.0,Casey Verhagen,2,Layup,NaN,NaN,NaN,NaN,0 Casey Verhagen > Spot-Up > Drives Left > Dribble Jumper > Short ...,Miss 2 Pts,Casey Verhagen,18.0
34,Concordia Wisconsin Falcons,2025-11-08,34,H1,16:08 (H1),968.0,Concordia Wisconsin Falcons,foul,Matt Merlo Commits Personal Foul,7.0,9.0,Matt Merlo,NaN,NaN,Personal Foul,NaN,NaN,NaN,35 Brady Wynja > Transition > First Middle > To Basket > Foul,Foul,Brady Wynja,19.0
35,Concordia Wisconsin Falcons,2025-11-08,35,H1,16:08 (H1),968.0,Wheaton (IL) Thunder,free_throw_missed,Brady Wynja Misses Free Throw (1 of 2),7.0,9.0,Brady Wynja,NaN,NaN,NaN,NaN,1,2,35 Brady Wynja > Non Possession > Free Throw,Free Throw,Brady Wynja,20.0
37,Concordia Wisconsin Falcons,2025-11-08,37,H1,16:08 (H1),968.0,Wheaton (IL) Thunder,free_throw_made,Brady Wynja Makes Free Throw (2 of 2),8.0,9.0,Brady Wynja,NaN,NaN,NaN,NaN,2,2,35 Brady Wynja > Non Possession > Free Throw,Free Throw,Brady Wynja,21.0
40,Concordia Wisconsin Falcons,2025-11-08,40,H1,15:57 (H1),957.0,Concordia Wisconsin Falcons,made_shot,Matt Merlo Makes 2PT Dunk,8.0,11.0,Matt Merlo,2,Dunk,NaN,NaN,NaN,NaN,14 Matt Merlo > Cut > Basket > Make 2 Pts,Make 2 Pts,Matt Merlo,22.0

  ... 5,327 more row(s) of 5,347 (SHOW_ROWS = 20)
Wheaton (IL) Thunder's own events across their 26 games before Whitewater: 6273
Their opponents' events across those same games: 6440

Wheaton (IL) Thunder's shot-type tendencies (volume + efficiency, tagged by play_type/guarded) across their last 26 games:

   shot_type      shot_desc         play_type guarded  attempts  makes  fg_pct
0          2          Layup               Cut     N/A       138    110    79.7
1          3      Jump Shot           Spot-Up     Yes       134     47    35.1
2          3      Jump Shot           Spot-Up      No       120     47    39.2
3          2          Layup        Transition     N/A       103     71    68.9
4          3      Jump Shot        Off Screen     Yes        70     21    30.0
5          2  Driving Layup        Transition     N/A        56     44    78.6
6          3      Jump Shot        Off Screen      No        52     19    36.5
7          3      Jump Shot        Transition      No        45     14    31.1
8          2          Layup           Post-Up     N/A        43     29    67.4
9          2          Layup           Spot-Up     N/A        31     12    38.7
10         2      Jump Shot               ISO     N/A        25      4    16.0
11         3      Jump Shot        Transition     Yes        24      8    33.3
12         2          Layup  P&R Ball Handler     N/A        24      8    33.3
13         2          Layup               ISO     N/A        23     15    65.2
14         2      Jump Shot           Spot-Up     N/A        23     10    43.5

  ... 116 more row(s) of 131 (SHOW_ROWS = 15)

Wheaton (IL) Thunder's shot attempts by play type:

            play_type  attempts  makes  fg_pct
0             Spot-Up       379    150    39.6
1          Transition       299    156    52.2
2          Off Screen       230     87    37.8
3                 Cut       193    132    68.4
4                 ISO       109     49    45.0
5             Post-Up        94     53    56.4
6    P&R Ball Handler        89     33    37.1
7            Hand Off        73     32    43.8
8   Offensive Rebound        47     37    78.7
9        P&R Roll Man        29     14    48.3
10       No Play Type        18      7    38.9

Wheaton (IL) Thunder's shot attempts by contest level:

  guarded  attempts  makes  fg_pct
0     N/A      1016    549    54.0
1     Yes       292    101    34.6
2      No       252    100    39.7

Wheaton (IL) Thunder's turnover types (290 total, tagged by play_type):

     turnover_type         play_type  count
3         Bad Pass      No Play Type     42
13       Lost Ball      No Play Type     28
18       Lost Ball        Transition     18
9         Bad Pass        Transition     15
20  Offensive Foul      No Play Type     13
5         Bad Pass  P&R Ball Handler     12
15       Lost Ball  P&R Ball Handler     11
14       Lost Ball        Off Screen     11
8         Bad Pass           Spot-Up     10
4         Bad Pass        Off Screen      9
17       Lost Ball           Spot-Up      9
11       Lost Ball          Hand Off      8
29          Travel           Spot-Up      5
30          Travel        Transition      5
12       Lost Ball               ISO      5

  ... 16 more row(s) of 31 (SHOW_ROWS = 15)

Wheaton (IL) Thunder's foul types (421 total, with video_description):

         foul_type                                                      video_description  count
64   Personal Foul              12 Chris Schlesinger > Non Possession > Non Shooting Foul      5
28   Personal Foul                             1 Dominic Trelenberg > No Play Type > Foul      3
240  Personal Foul                    5 Andre Klaver > Non Possession > Non Shooting Foul      3
261  Personal Foul                    7 Lane Thomann > Non Possession > Non Shooting Foul      3
235  Personal Foul                    44 Lamar Smith > Non Possession > Non Shooting Foul      3
16   Personal Foul                  0 Noah Cleveland > Non Possession > Non Shooting Foul      3
224  Personal Foul  4 Mike Vuckovic > P&R Ball Handler > High P&R > Dribble Off Pick >...      3
102  Personal Foul                      2 Luke Smith > Non Possession > Non Shooting Foul      2
112  Personal Foul                                 2 Tyvin Garrison > No Play Type > Foul      2
230  Personal Foul                                   41 Jacob Naber > Cut > Basket > Foul      2
164  Personal Foul  25 Marquis Vance > Offensive Rebound > Short > Scoring Attempt > A...      2
166  Personal Foul          25 Marquis Vance > Transition > Right Wing > To Basket > Foul      2
0    Personal Foul                  0 Casey Verhagen > Non Possession > Non Shooting Foul      2
217  Personal Foul  4 Michael McNabb > Offensive Rebound > Short > Scoring Attempt > A...      2
26   Personal Foul                             1 Dominic Trelenberg > Cut > Basket > Foul      2

  ... 249 more row(s) of 264 (SHOW_ROWS = 15)

Wheaton (IL) Thunder's top scorers across their last 26 games (from play-by-play):

             player  total_points_across_26_games
0  Soren Richardson                         580.0
1  Kyan VanderWoude                         378.0
2      Carson Grier                         369.0
3      Devin Martin                         244.0
4        Reid Olson                         174.0
5       Brady Wynja                         146.0
6       Kyle Neibch                         117.0
7      Noah Hedrick                          44.0
8    Luca Carbonaro                          36.0
9   Christian Veirs                          21.0

UWW's own scouting notes for Wheaton (IL) Thunder [SOURCE: SCOUTING REPORT]:

--- Comparing PBP evidence to the stated Keys to Victory [SOURCE: SCOUTING REPORT] ---

KEY 1 [SCOUTING REPORT] -- COMMUNICATE SCREENS & ACTIONS:
  Not directly measurable from play-by-play event types (no screen-action tagging) -- this is a
  communication/technique key tied to their offensive scheme (per the scout's own Offensive Scheme notes),
  not something the event log alone can confirm or refute.

KEY 2 [SCOUTING REPORT] -- DOMINATE THE PAINT:
  Their own rebounding split across their 26 games: [{'rebound_type': 'defensive', 'count': 643}, {'rebound_type': 'offensive', 'count': 335}]
  Their layup-area attempts (Layup + Driving Layup): 637 of 1507 total FGA
  Blocks recorded against them by opponents: 91
  Compare against their own Defensive Scheme notes and layup-area conversion rate to judge whether this key
  is supported by the evidence.

KEY 3 [SCOUTING REPORT] -- GUARD 1 ON 1:
  Measured 3PT jump-shot rate: 566 attempts at 34.3%.
  Scoring balance (top 5 scorers): [{'player': 'Soren Richardson', 'total_points_across_26_games': 580.0}, {'player': 'Kyan VanderWoude', 'total_points_across_26_games': 378.0}, {'player': 'Carson Grier', 'total_points_across_26_games': 369.0}, {'player': 'Devin Martin', 'total_points_across_26_games': 244.0}, {'player': 'Reid Olson', 'total_points_across_26_games': 174.0}]
  Compare against the scout's own TEAM STRENGTHS note on shooting/scoring balance to judge whether
  over-helping creates open catch-and-shoot looks that straight man coverage would limit.


--- New Keys to Victory, derived from PBP data/tendencies [SOURCE: PBP-DERIVED] ---

DATA-KEY 1 [PBP-DERIVED] -- TAKE AWAY THEIR MOST EFFICIENT HIGH-VOLUME ACTIONS:
  Offensive Rebound: 78.7% on 47 attempts; Cut: 68.4% on 193 attempts
  Each is 5+ points above their 47.9% overall clip on 15+ attempts. Offensive Rebound: hit a body on every shot before going to the ball. Cut: jump to the ball on every pass and see man and ball -- no back-cuts behind ball-watchers.

DATA-KEY 2 [PBP-DERIVED] -- FUNNEL THEM INTO THEIR WORST HIGH-VOLUME LOOKS:
  P&R Ball Handler: 37.1% on 89 attempts; Off Screen: 37.8% on 230 attempts
  Each is 5+ points below their 47.9% overall clip -- don't help off these actions; make them keep taking them.

DATA-KEY 3 [PBP-DERIVED] -- PRESSURE THE ACTIONS THEY TURN IT OVER ON:
  P&R Ball Handler: 24 TO in 113 uses (21.2% vs 9.6% across all actions); Hand Off: 14 TO in 87 uses (16.1% vs 9.6% across all actions)
  Loosest actions per use, not the most common ones -- load ball pressure and gap help onto these specifically rather than pressing everything.


Structured PBP-derived keys, ready for CSV export:

,opponent,key_number,title,source,supporting_stats,recommendation
0,Wheaton (IL) Thunder,1,Take away their most efficient high-volume actions,PBP-DERIVED,Offensive Rebound: 78.7% on 47 attempts; Cut: 68.4% on 193 attempts,Each is 5+ points above their 47.9% overall clip on 15+ attempts. ...
1,Wheaton (IL) Thunder,2,Funnel them into their worst high-volume looks,PBP-DERIVED,P&R Ball Handler: 37.1% on 89 attempts; Off Screen: 37.8% on 230 a...,Each is 5+ points below their 47.9% overall clip -- don't help off...
2,Wheaton (IL) Thunder,3,Pressure the actions they turn it over on,PBP-DERIVED,P&R Ball Handler: 24 TO in 113 uses (21.2% vs 9.6% across all acti...,"Loosest actions per use, not the most common ones -- load ball pre..."

Wheaton (IL) Thunder's video-tagged play types, across their 26 games before Whitewater (1560 video-matched attempts):

            play_type  attempts  makes  fg_pct
0             Spot-Up       379    150    39.6
1          Transition       299    156    52.2
2          Off Screen       230     87    37.8
3                 Cut       193    132    68.4
4                 ISO       109     49    45.0
5             Post-Up        94     53    56.4
6    P&R Ball Handler        89     33    37.1
7            Hand Off        73     32    43.8
8   Offensive Rebound        47     37    78.7
9        P&R Roll Man        29     14    48.3
10       No Play Type        18      7    38.9

Weakest high-volume play type (>= 10 attempts): 'P&R Ball Handler' at 37.1% (33/89)

'P&R Ball Handler' shot-quality breakdown (89 attempts):

By shot mechanic:

             shot_mechanic  attempts  makes  fg_pct
1      Drive to the basket        44     21    47.7
2  Pull-up off the dribble        43     11    25.6
0          Catch-and-shoot         2      1    50.0

By contest level:

                                                 contest  attempts  makes  fg_pct
1  Not tagged (contest recorded only on catch-and-shoot)        87     32    36.8
0                                                Guarded         1      0     0.0
2                                                   Open         1      1   100.0

By shot distance:

            distance  attempts  makes  fg_pct
2                N/A        44     21    47.7
0           Long/3pt        23      4    17.4
3     Short to < 17'        15      6    40.0
1  Medium/17' to <3p         7      2    28.6

Per-player 'P&R Ball Handler' volume/efficiency, with catch-and-shoot% and guarded% of those attempts:

             player  attempts  makes  fg_pct  pct_catch_and_shoot  pct_guarded
2      Devin Martin        29      9    31.0                  0.0          0.0
8  Soren Richardson        26     11    42.3                  7.7          3.8
4  Kyan VanderWoude        11      4    36.4                  0.0          0.0
7        Reid Olson         9      2    22.2                  0.0          0.0
1      Carson Grier         5      3    60.0                  0.0          0.0
5    Luca Carbonaro         3      2    66.7                  0.0          0.0
6      Noah Hedrick         3      0     0.0                  0.0          0.0
0       Brady Wynja         2      2   100.0                  0.0          0.0
3        Jace Olson         1      0     0.0                  0.0          0.0

WARNING: upcoming opponent 'Wheaton (IL) Thunder' has no scout report loaded (scouted: ['Alma Scots', 'Aurora Spartans', 'Carroll (WI) Pioneers', 'Coe Kohawks', 'Elmhurst Bluejays', 'Eureka Red Devils', 'Hope Flying Dutchmen', 'Lawrence Vikings', 'Loras Duhawks', 'Ripon Red Hawks', 'Simpson Storm', 'St. Thomas (TX) Celts', 'UW-Eau Claire Blugolds', 'UW-La Crosse Eagles', 'UW-Oshkosh Titans', 'UW-Platteville Pioneers', 'UW-River Falls Falcons', 'UW-Stevens Point Pointers', 'UW-Stout Blue Devils', 'Washington-St. Louis Bears']) -- player comparisons will be empty for them. Add their scout report to INPUT_DIR and re-run.
LLM comparison skipped (use_llm=False) -- using tag-based similarity only.
Loaded player comparison algorithms (version 2026-07-29-portable). use_llm=False

Scouted opponents and their game number on the schedule:
  Game #1: Ripon Red Hawks
  Game #2: St. Thomas (TX) Celts
  Game #3: Eureka Red Devils
  Game #4: Aurora Spartans
  Game #5: Simpson Storm
  Game #6: Elmhurst Bluejays
  Game #7: Lawrence Vikings
  Game #8: Carroll (WI) Pioneers
  Game #9: Hope Flying Dutchmen
  Game #10: Alma Scots
  Game #11: Coe Kohawks
  Game #12: UW-Oshkosh Titans
  Game #13: UW-Stevens Point Pointers
  Game #14: UW-River Falls Falcons
  Game #15: UW-La Crosse Eagles
  Game #16: UW-Stout Blue Devils
  Game #17: UW-Platteville Pioneers
  Game #18: UW-Eau Claire Blugolds
  Game #28: Loras Duhawks
  Game #29: Washington-St. Louis Bears

Target (most recently scouted game): Wheaton (IL) Thunder (game #None)
Previous scouted opponents to compare against: ['St. Thomas (TX) Celts', 'Eureka Red Devils', 'Aurora Spartans', 'Simpson Storm', 'Ripon Red Hawks', 'Lawrence Vikings', 'Carroll (WI) Pioneers', 'Hope Flying Dutchmen', 'Alma Scots', 'Elmhurst Bluejays', 'Coe Kohawks', 'UW-River Falls Falcons', 'UW-La Crosse Eagles', 'UW-Stout Blue Devils', 'UW-Platteville Pioneers', 'UW-Eau Claire Blugolds', 'UW-Oshkosh Titans', 'UW-Stevens Point Pointers', 'Loras Duhawks', 'Washington-St. Louis Bears']

player_notes-derived tag frequency and rarity-based importance weight (rarer tags count more toward similarity):

                   tag  count  importance_weight
0  three_point_shooter     91              1.903
1       slasher_driver     81              2.018
2          post_scorer     22              3.289
3            rebounder      7              4.346
4      catch_and_shoot      5              4.633
5            playmaker      4              4.816
6           high_usage      3              5.039
7    physical_finisher      3              5.039
8      pull_up_shooter      3              5.039
9               cutter      1              5.732

keys_to_defending-derived tag frequency and rarity-based importance weight:

                     tag  count  importance_weight
0   deny_catch_and_shoot     53              2.436
1        anticipate_move     38              2.761
2           post_defense     16              3.592
3           help_defense     10              4.027
4       box_out_priority      8              4.228
5    physical_discipline      8              4.228
6       pressure_disrupt      7              4.346
7     transition_defense      7              4.346
8          keep_in_front      6              4.479
9              deny_cuts      2              5.326
10     screen_navigation      1              5.732

No player comparisons available for Wheaton (IL) Thunder yet -- there's no previously-scouted opponent on record to compare their players against. Expected for the first scouted game of the season; comparisons will start appearing once a second opponent has been scouted.
LLM-based comparison was skipped (USE_LLM=False). Set the USE_LLM config variable to True to run this cell.
LLM-based comparison was skipped (USE_LLM=False). Set the USE_LLM config variable to True to run this cell.
LLM-based comparison was skipped (USE_LLM=False), so there is no LLM score to blend with the tag-based score. Set the USE_LLM config variable to True to run this cell.
Empty DataFrame
Columns: []
Index: []
Found 29 UW-Whitewater play-by-play file(s):
 - 11_14_25 UW-Whitewater @ St. Thomas (TX) Celts_pbp.html
 - 11_15_25 UW-Whitewater @ Eureka Red Devils_pbp.html
 - 11_19_25 Aurora Spartans @ UW-Whitewater_pbp.html
 - 11_25_25 Simpson Storm @ UW-Whitewater_pbp.html
 - 11_7_25 UW-Whitewater @ Ripon Red Hawks_pbp.html
 - 12_10_25 UW-Whitewater @ Lawrence Vikings_pbp.html
 - 12_13_25 Carroll (WI) Pioneers @ UW-Whitewater_pbp.html
 - 12_19_25 UW-Whitewater @ Hope Flying Dutchmen_pbp.html
 - 12_20_25 UW-Whitewater @ Alma Scots_pbp.html
 - 12_2_25 Elmhurst Bluejays @ UW-Whitewater_pbp.html
 - 12_30_25 UW-Whitewater @ Coe Kohawks_pbp.html
 - 1_10_26 UW-Whitewater @ UW-River Falls Falcons_pbp.html
 - 1_14_26 UW-Whitewater @ UW-La Crosse Eagles_pbp.html
 - 1_17_26 UW-Stout Blue Devils @ UW-Whitewater_pbp.html
 - 1_21_26 UW-Whitewater @ UW-Platteville Pioneers_pbp.html
 - 1_24_26 UW-Eau Claire Blugolds @ UW-Whitewater_pbp.html
 - 1_28_26 UW-Whitewater @ UW-Oshkosh Titans_pbp.html
 - 1_3_26 UW-Oshkosh Titans @ UW-Whitewater_pbp.html
 - 1_7_26 UW-Stevens Point Pointers @ UW-Whitewater_pbp.html
 - 2_11_26 UW-Platteville Pioneers @ UW-Whitewater_pbp.html
 - 2_14_26 UW-Whitewater @ UW-Eau Claire Blugolds_pbp.html
 - 2_18_26 UW-Stevens Point Pointers @ UW-Whitewater_pbp.html
 - 2_21_26 UW-River Falls Falcons @ UW-Whitewater_pbp.html
 - 2_26_26 UW-Platteville Pioneers @ UW-Whitewater_pbp.html
 - 2_28_26 UW-La Crosse Eagles @ UW-Whitewater_pbp.html
 - 2_4_26 UW-La Crosse Eagles @ UW-Whitewater_pbp.html
 - 2_7_26 UW-Whitewater @ UW-Stout Blue Devils_pbp.html
 - 3_6_26 UW-Whitewater @ Loras Duhawks_pbp.html
 - 3_7_26 UW-Whitewater @ Washington-St. Louis Bears_pbp.html
  Parsed 'St. Thomas (TX) Celts': 444 events
  Parsed 'Eureka Red Devils': 496 events
  WARNING: Detected swapped columns for 'Aurora Spartans' (UWW roster found in right column) -- auto-corrected
  Parsed 'Aurora Spartans': 515 events
  WARNING: Detected swapped columns for 'Simpson Storm' (UWW roster found in right column) -- auto-corrected
  Parsed 'Simpson Storm': 542 events
  Parsed 'Ripon Red Hawks': 482 events
  Parsed 'Lawrence Vikings': 508 events
  WARNING: Detected swapped columns for 'Carroll (WI) Pioneers' (UWW roster found in right column) -- auto-corrected
  Parsed 'Carroll (WI) Pioneers': 495 events
  Parsed 'Hope Flying Dutchmen': 557 events
  Parsed 'Alma Scots': 465 events
  WARNING: Detected swapped columns for 'Elmhurst Bluejays' (UWW roster found in right column) -- auto-corrected
  Parsed 'Elmhurst Bluejays': 430 events
  Parsed 'Coe Kohawks': 423 events
  Parsed 'UW-River Falls Falcons': 484 events
  Parsed 'UW-La Crosse Eagles': 536 events
  WARNING: Detected swapped columns for 'UW-Stout Blue Devils' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-Stout Blue Devils': 480 events
  Parsed 'UW-Platteville Pioneers': 435 events
  WARNING: Detected swapped columns for 'UW-Eau Claire Blugolds' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-Eau Claire Blugolds': 495 events
  Parsed 'UW-Oshkosh Titans': 846 events
  WARNING: Detected swapped columns for 'UW-Oshkosh Titans' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-Oshkosh Titans': 845 events
  WARNING: Detected swapped columns for 'UW-Stevens Point Pointers' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-Stevens Point Pointers': 493 events
  WARNING: Detected swapped columns for 'UW-Platteville Pioneers' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-Platteville Pioneers': 428 events
  Parsed 'UW-Eau Claire Blugolds': 450 events
  WARNING: Detected swapped columns for 'UW-Stevens Point Pointers' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-Stevens Point Pointers': 467 events
  WARNING: Detected swapped columns for 'UW-River Falls Falcons' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-River Falls Falcons': 470 events
  WARNING: Detected swapped columns for 'UW-Platteville Pioneers' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-Platteville Pioneers': 476 events
  WARNING: Detected swapped columns for 'UW-La Crosse Eagles' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-La Crosse Eagles': 449 events
  WARNING: Detected swapped columns for 'UW-La Crosse Eagles' (UWW roster found in right column) -- auto-corrected
  Parsed 'UW-La Crosse Eagles': 478 events
  Parsed 'UW-Stout Blue Devils': 488 events
  WARNING: Detected swapped columns for 'Loras Duhawks' (UWW roster found in right column) -- auto-corrected
  Parsed 'Loras Duhawks': 495 events
  Parsed 'Washington-St. Louis Bears': 393 events

Every play-by-play line was classified.

,opponent,game_date,event_order,period,time_remaining,time_remaining_seconds,team,event_type,raw_text,uww_score,opp_score,player,shot_type,shot_desc,turnover_type,foul_type,ft_num,ft_total
0,St. Thomas (TX) Celts,2025-11-14,0,None,None,NaN,None,period_marker,Start 1st Half,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,St. Thomas (TX) Celts,2025-11-14,1,H1,19:58 (H1),1198.0,St. Thomas (TX) Celts,jump_ball_won,Charles Gitonga Wins Jump Ball,0.0,0.0,Charles Gitonga,NaN,NaN,NaN,NaN,NaN,NaN
2,St. Thomas (TX) Celts,2025-11-14,2,H1,19:58 (H1),1198.0,UW-Whitewater,jump_ball_lost,Brock Marino Loses Jump Ball,0.0,0.0,Brock Marino,NaN,NaN,NaN,NaN,NaN,NaN
3,St. Thomas (TX) Celts,2025-11-14,3,H1,19:34 (H1),1174.0,St. Thomas (TX) Celts,made_shot,Corey Thompson Makes 2PT Turnaround Jump Shot,0.0,2.0,Corey Thompson,2,Turnaround Jump Shot,NaN,NaN,NaN,NaN
4,St. Thomas (TX) Celts,2025-11-14,4,H1,19:22 (H1),1162.0,UW-Whitewater,turnover,Isaac Verges Turnover (Lost Ball),0.0,2.0,Isaac Verges,NaN,NaN,Lost Ball,NaN,NaN,NaN
5,St. Thomas (TX) Celts,2025-11-14,5,H1,19:22 (H1),1162.0,St. Thomas (TX) Celts,steal,Angel Johnson Steals,0.0,2.0,Angel Johnson,NaN,NaN,NaN,NaN,NaN,NaN
6,St. Thomas (TX) Celts,2025-11-14,6,H1,19:16 (H1),1156.0,St. Thomas (TX) Celts,missed_shot,Nathan Kongolo Misses 3PT Jump Shot,0.0,2.0,Nathan Kongolo,3,Jump Shot,NaN,NaN,NaN,NaN
7,St. Thomas (TX) Celts,2025-11-14,7,H1,19:14 (H1),1154.0,UW-Whitewater,rebound_defensive,Collin Madson Defensive Rebound,0.0,2.0,Collin Madson,NaN,NaN,NaN,NaN,NaN,NaN
8,St. Thomas (TX) Celts,2025-11-14,8,H1,19:09 (H1),1149.0,UW-Whitewater,turnover,Isaac Verges Turnover (Bad Pass),0.0,2.0,Isaac Verges,NaN,NaN,Bad Pass,NaN,NaN,NaN
9,St. Thomas (TX) Celts,2025-11-14,9,H1,19:09 (H1),1149.0,St. Thomas (TX) Celts,steal,Nathan Kongolo Steals,0.0,2.0,Nathan Kongolo,NaN,NaN,NaN,NaN,NaN,NaN
10,St. Thomas (TX) Celts,2025-11-14,10,H1,19:05 (H1),1145.0,St. Thomas (TX) Celts,made_shot,Angel Johnson Makes 2PT Layup,0.0,4.0,Angel Johnson,2,Layup,NaN,NaN,NaN,NaN
11,St. Thomas (TX) Celts,2025-11-14,11,H1,19:05 (H1),1145.0,St. Thomas (TX) Celts,assist,Nathan Kongolo Assists,0.0,4.0,Nathan Kongolo,NaN,NaN,NaN,NaN,NaN,NaN
12,St. Thomas (TX) Celts,2025-11-14,12,H1,18:34 (H1),1114.0,UW-Whitewater,missed_shot,Isaac Verges Misses 2PT Layup,0.0,4.0,Isaac Verges,2,Layup,NaN,NaN,NaN,NaN
13,St. Thomas (TX) Celts,2025-11-14,13,H1,18:31 (H1),1111.0,St. Thomas (TX) Celts,rebound_defensive,Nicholas Buffalo Defensive Rebound,0.0,4.0,Nicholas Buffalo,NaN,NaN,NaN,NaN,NaN,NaN
14,St. Thomas (TX) Celts,2025-11-14,14,H1,18:22 (H1),1102.0,St. Thomas (TX) Celts,missed_shot,Corey Thompson Misses 2PT Layup,0.0,4.0,Corey Thompson,2,Layup,NaN,NaN,NaN,NaN
15,St. Thomas (TX) Celts,2025-11-14,15,H1,18:19 (H1),1099.0,St. Thomas (TX) Celts,rebound_offensive,Corey Thompson Offensive Rebound,0.0,4.0,Corey Thompson,NaN,NaN,NaN,NaN,NaN,NaN
16,St. Thomas (TX) Celts,2025-11-14,16,H1,18:18 (H1),1098.0,St. Thomas (TX) Celts,turnover,Corey Thompson Turnover,0.0,4.0,Corey Thompson,NaN,NaN,None,NaN,NaN,NaN
17,St. Thomas (TX) Celts,2025-11-14,17,H1,18:04 (H1),1084.0,UW-Whitewater,made_shot,Collin Madson Makes 2PT Layup,2.0,4.0,Collin Madson,2,Layup,NaN,NaN,NaN,NaN
18,St. Thomas (TX) Celts,2025-11-14,18,H1,18:04 (H1),1084.0,UW-Whitewater,assist,Luke Bara Assists,2.0,4.0,Luke Bara,NaN,NaN,NaN,NaN,NaN,NaN
19,St. Thomas (TX) Celts,2025-11-14,19,H1,17:43 (H1),1063.0,St. Thomas (TX) Celts,made_shot,Angel Johnson Makes 2PT Pull Up Jump Shot,2.0,6.0,Angel Johnson,2,Pull Up Jump Shot,NaN,NaN,NaN,NaN

  ... 14,545 more row(s) of 14,565 (SHOW_ROWS = 20)
Found 1 playbook catalog file(s):
 - UW-Whitewater - Plays.mhtml

Parsed 27 play(s) across 9 series and 17 family/families.

        series play_family       play_name aliases
0         ELOB        ELOB            "20"      20
1         Snap        Snap  20 Snap (flip)
2         Snap        Snap       30 (flip)
3         Snap        Snap         40 Snap
4         Over     Cheetah         Cheetah
5       Bursts       Cobra           Cobra
6       Bursts         Fox             Fox
7   Transition         Get             Get
8     Specials    Kentucky        Kentucky
9     Specials     Panther  Panther 2 "P2"      P2
10    Specials     Panther  Panther-4 "P4"      P4
11    Specials     Panther     Panther "P"       P
12        Over         Pin       Pin Flair
13     Entries      Pistol          Pistol
14  Transition       Pitch           Pitch

  ... 12 more row(s) of 27 (SHOW_ROWS = 15)
Found 0 coach-note/play-log CSV(s):
Lineup column check: 0 game(s) had our lineup in the opponent's column and were corrected.

,opponent,period,time_remaining,team,event_type,raw_text,uww_lineup,opp_lineup
0,St. Thomas (TX) Celts,None,None,None,period_marker,Start 1st Half,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
1,St. Thomas (TX) Celts,H1,19:58 (H1),St. Thomas (TX) Celts,jump_ball_won,Charles Gitonga Wins Jump Ball,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
2,St. Thomas (TX) Celts,H1,19:58 (H1),UW-Whitewater,jump_ball_lost,Brock Marino Loses Jump Ball,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
3,St. Thomas (TX) Celts,H1,19:34 (H1),St. Thomas (TX) Celts,made_shot,Corey Thompson Makes 2PT Turnaround Jump Shot,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
4,St. Thomas (TX) Celts,H1,19:22 (H1),UW-Whitewater,turnover,Isaac Verges Turnover (Lost Ball),"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
5,St. Thomas (TX) Celts,H1,19:22 (H1),St. Thomas (TX) Celts,steal,Angel Johnson Steals,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
6,St. Thomas (TX) Celts,H1,19:16 (H1),St. Thomas (TX) Celts,missed_shot,Nathan Kongolo Misses 3PT Jump Shot,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
7,St. Thomas (TX) Celts,H1,19:14 (H1),UW-Whitewater,rebound_defensive,Collin Madson Defensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
8,St. Thomas (TX) Celts,H1,19:09 (H1),UW-Whitewater,turnover,Isaac Verges Turnover (Bad Pass),"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
9,St. Thomas (TX) Celts,H1,19:09 (H1),St. Thomas (TX) Celts,steal,Nathan Kongolo Steals,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
10,St. Thomas (TX) Celts,H1,19:05 (H1),St. Thomas (TX) Celts,made_shot,Angel Johnson Makes 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
11,St. Thomas (TX) Celts,H1,19:05 (H1),St. Thomas (TX) Celts,assist,Nathan Kongolo Assists,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
12,St. Thomas (TX) Celts,H1,18:34 (H1),UW-Whitewater,missed_shot,Isaac Verges Misses 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
13,St. Thomas (TX) Celts,H1,18:31 (H1),St. Thomas (TX) Celts,rebound_defensive,Nicholas Buffalo Defensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
14,St. Thomas (TX) Celts,H1,18:22 (H1),St. Thomas (TX) Celts,missed_shot,Corey Thompson Misses 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
15,St. Thomas (TX) Celts,H1,18:19 (H1),St. Thomas (TX) Celts,rebound_offensive,Corey Thompson Offensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
16,St. Thomas (TX) Celts,H1,18:18 (H1),St. Thomas (TX) Celts,turnover,Corey Thompson Turnover,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
17,St. Thomas (TX) Celts,H1,18:04 (H1),UW-Whitewater,made_shot,Collin Madson Makes 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
18,St. Thomas (TX) Celts,H1,18:04 (H1),UW-Whitewater,assist,Luke Bara Assists,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
19,St. Thomas (TX) Celts,H1,17:43 (H1),St. Thomas (TX) Celts,made_shot,Angel Johnson Makes 2PT Pull Up Jump Shot,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
20,St. Thomas (TX) Celts,H1,17:19 (H1),UW-Whitewater,made_shot,JR Lukenbill Makes 3PT Jump Shot,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
21,St. Thomas (TX) Celts,H1,17:19 (H1),UW-Whitewater,assist,Collin Madson Assists,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
22,St. Thomas (TX) Celts,H1,17:05 (H1),UW-Whitewater,foul,Luke Bara Commits Personal Foul,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
23,St. Thomas (TX) Celts,H1,16:55 (H1),St. Thomas (TX) Celts,made_shot,Angel Johnson Makes 2PT Driving Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
24,St. Thomas (TX) Celts,H1,16:37 (H1),UW-Whitewater,missed_shot,Luke Bara Misses 3PT Jump Shot,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
25,St. Thomas (TX) Celts,H1,16:34 (H1),St. Thomas (TX) Celts,rebound_defensive,Charles Gitonga Defensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
26,St. Thomas (TX) Celts,H1,16:17 (H1),St. Thomas (TX) Celts,missed_shot,Nicholas Buffalo Misses 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
27,St. Thomas (TX) Celts,H1,16:15 (H1),St. Thomas (TX) Celts,rebound_offensive,Nicholas Buffalo Offensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
28,St. Thomas (TX) Celts,H1,16:13 (H1),St. Thomas (TX) Celts,missed_shot,Nicholas Buffalo Misses 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
29,St. Thomas (TX) Celts,H1,16:11 (H1),UW-Whitewater,rebound_defensive,Brock Marino Defensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."

  ... 14,535 more row(s) of 14,565 (SHOW_ROWS = 30)

Lineup size check (every non-null value should be exactly 5 players):
 uww_lineup sizes: {5: 14565}
 opp_lineup sizes: {5: 14565}
                         opponent  \
4376                   Alma Scots
4453                   Alma Scots
4393                   Alma Scots
4355                   Alma Scots
4341                   Alma Scots
...                           ...
14242  Washington-St. Louis Bears
14172  Washington-St. Louis Bears
14490  Washington-St. Louis Bears
14282  Washington-St. Louis Bears
14511  Washington-St. Louis Bears

                                                                            opp_lineup  \
4376   Donovan Collins, Josh Elliott, Joss Bradley, Luciano Guerrazzi, Preston Malpass
4453   Donovan Collins, Josh Elliott, Joss Bradley, Korbin Heitzman, Luciano Guerrazzi
4393   Donovan Collins, Josh Elliott, Korbin Heitzman, Luciano Guerrazzi, Raine Rodich
4355   Donovan Collins, Elijah Sykes, Joss Bradley, Luciano Guerrazzi, Preston Malpass
4341   Elijah Sykes, Joss Bradley, Korbin Heitzman, Luciano Guerrazzi, Preston Malpass
...                                                                                ...
14242            Anthony Przybilla, George Gale, Josh Kim, Theo Rocca, Will Grudzinski
14172                      Calvin Kapral, Connor May, Josh Kim, Ryan Cohen, Yogi Oliff
14490                Anthony Przybilla, Connor May, Ryan Cohen, Theo Rocca, Yogi Oliff
14282               Anthony Przybilla, Connor May, George Gale, Ryan Cohen, Yogi Oliff
14511                  Anthony Przybilla, Connor May, Josh Kim, Ryan Cohen, Theo Rocca

                                                                                                                                                                                           opp_lineup_summary
4376                   3 Bench / 2 Starter | Pos: 3 Guard, 2 Forward/Post | Style: three_point_shooter x3, slasher_driver x1 | Defend: deny_catch_and_shoot x2, transition_defense x1, physical_discipline x1
4453          3 Starter / 2 Bench | Pos: 3 Guard, 2 Forward/Post | Style: three_point_shooter x2, slasher_driver x2, post_scorer x1 | Defend: post_defense x2, deny_catch_and_shoot x1, transition_defense x1
4393                    4 Starter / 1 Bench | Pos: 3 Guard, 2 Forward/Post | Style: slasher_driver x2, three_point_shooter x2, post_scorer x1 | Defend: post_defense x2, anticipate_move x1, keep_in_front x1
4355                         4 Bench / 1 Starter | Pos: 3 Guard, 2 Forward/Post | Style: three_point_shooter x3, slasher_driver x2 | Defend: deny_catch_and_shoot x3, physical_discipline x1, post_defense x1
4341         4 Bench / 1 Starter | Pos: 3 Forward/Post, 2 Guard | Style: slasher_driver x3, three_point_shooter x2, post_scorer x1 | Defend: post_defense x2, deny_catch_and_shoot x2, physical_discipline x1
...                                                                                                                                                                                                       ...
14242            4 Bench / 1 Starter | Pos: 3 Guard, 2 Forward/Post | Style: slasher_driver x4, three_point_shooter x3, post_scorer x1 | Defend: deny_catch_and_shoot x2, anticipate_move x1, post_defense x1
14172                   5 Starter | Pos: 3 Guard, 2 Forward/Post | Style: three_point_shooter x4, slasher_driver x3, catch_and_shoot x1 | Defend: anticipate_move x2, keep_in_front x1, transition_defense x1
14490         3 Starter / 2 Bench | Pos: 3 Guard, 2 Forward/Post | Style: three_point_shooter x4, slasher_driver x3, catch_and_shoot x1 | Defend: keep_in_front x1, transition_defense x1, anticipate_move x1
14282         3 Starter / 2 Bench | Pos: 3 Forward/Post, 2 Guard | Style: three_point_shooter x3, slasher_driver x2, catch_and_shoot x1 | Defend: keep_in_front x1, transition_defense x1, anticipate_move x1
14511  3 Starter / 2 Bench | Pos: 3 Guard, 2 Forward/Post | Style: three_point_shooter x4, slasher_driver x3, catch_and_shoot x1 | Defend: anticipate_move x2, transition_defense x1, deny_catch_and_shoot x1

[472 rows x 3 columns]
Skipping 123 video file(s) for games UWW didn't play in (handled by the opponent prior-games cell).
Found 28 video-tagging file(s):
 - 11_14_25 UW-Whitewater @ St. Thomas (TX) Celts_video.html
 - 11_15_25 UW-Whitewater @ Eureka Red Devils_video.html
 - 11_19_25 Aurora Spartans @ UW-Whitewater_video.html
 - 11_25_25 Simpson Storm @ UW-Whitewater_video.html
 - 11_7_25 UW-Whitewater @ Ripon Red Hawks_video.html
 - 12_10_25 UW-Whitewater @ Lawrence Vikings_video.html
 - 12_13_25 Carroll (WI) Pioneers @ UW-Whitewater_video.html
 - 12_19_25 UW-Whitewater @ Hope Flying Dutchmen_video.html
 - 12_20_25 UW-Whitewater @ Alma Scots_video.html
 - 12_2_25 Elmhurst Bluejays @ UW-Whitewater_video.html
 - 12_30_25 UW-Whitewater @ Coe Kohawks_video.html
 - 1_10_26 UW-Whitewater @ UW-River Falls Falcons_video.html
 - 1_14_26 UW-Whitewater @ UW-La Crosse Eagles_video.html
 - 1_17_26 UW-Stout Blue Devils @ UW-Whitewater_video.html
 - 1_21_26 UW-Whitewater @ UW-Platteville Pioneers_video.html
 - 1_24_26 UW-Eau Claire Blugolds @ UW-Whitewater_video.html
 - 1_28_26 UW-Whitewater @ UW-Oshkosh Titans_video.html
 - 1_3_26 UW-Oshkosh Titans @ UW-Whitewater_video.html
 - 1_7_26 UW-Stevens Point Pointers @ UW-Whitewater_video.html
 - 2_11_26 UW-Platteville Pioneers @ UW-Whitewater_video.html
 - 2_14_26 UW-Whitewater @ UW-Eau Claire Blugolds_video.html
 - 2_21_26 UW-River Falls Falcons @ UW-Whitewater_video.html
 - 2_26_26 UW-Platteville Pioneers @ UW-Whitewater_video.html
 - 2_28_26 UW-La Crosse Eagles @ UW-Whitewater_video.html
 - 2_4_26 UW-La Crosse Eagles @ UW-Whitewater_video.html
 - 2_7_26 UW-Whitewater @ UW-Stout Blue Devils_video.html
 - 3_6_26 UW-Whitewater @ Loras Duhawks_video.html
 - 3_7_26 UW-Whitewater @ Washington-St. Louis Bears_video.html
  St. Thomas (TX) Celts: matched 195/222 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 53/55 are free throws, and 28/41 are fouls). video log had 213 taggable sub-events of these types.
  Eureka Red Devils: matched 208/223 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 38/38 are free throws, and 25/31 are fouls). video log had 220 taggable sub-events of these types.
  Aurora Spartans: matched 213/242 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 55/63 are free throws, and 41/51 are fouls). video log had 224 taggable sub-events of these types.
  Simpson Storm: matched 200/220 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 34/34 are free throws, and 20/32 are fouls). video log had 210 taggable sub-events of these types.
  Ripon Red Hawks: matched 200/217 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 49/49 are free throws, and 30/40 are fouls). video log had 208 taggable sub-events of these types.
  Lawrence Vikings: matched 208/227 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 46/46 are free throws, and 30/41 are fouls). video log had 213 taggable sub-events of these types.
  Carroll (WI) Pioneers: matched 214/235 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 45/45 are free throws, and 34/45 are fouls). video log had 220 taggable sub-events of these types.
  Hope Flying Dutchmen: matched 239/258 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 67/67 are free throws, and 40/50 are fouls). video log had 249 taggable sub-events of these types.
  Alma Scots: matched 194/214 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 34/34 are free throws, and 19/32 are fouls). video log had 203 taggable sub-events of these types.
  Elmhurst Bluejays: matched 190/202 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 35/37 are free throws, and 25/34 are fouls). video log had 198 taggable sub-events of these types.
  Coe Kohawks: matched 195/213 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 36/36 are free throws, and 29/35 are fouls). video log had 199 taggable sub-events of these types.
  UW-River Falls Falcons: matched 196/214 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 34/34 are free throws, and 26/36 are fouls). video log had 202 taggable sub-events of these types.
  UW-La Crosse Eagles: matched 231/244 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 58/58 are free throws, and 38/44 are fouls). video log had 237 taggable sub-events of these types.
  UW-Stout Blue Devils: matched 191/214 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 35/35 are free throws, and 26/37 are fouls). video log had 197 taggable sub-events of these types.
  UW-Platteville Pioneers: matched 183/196 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 39/39 are free throws, and 28/37 are fouls). video log had 191 taggable sub-events of these types.
  UW-Eau Claire Blugolds: matched 217/230 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 50/50 are free throws, and 35/44 are fouls). video log had 221 taggable sub-events of these types.
  UW-Oshkosh Titans: matched 236/256 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 59/59 are free throws, and 35/51 are fouls). video log had 242 taggable sub-events of these types.
  UW-Oshkosh Titans: matched 234/252 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 61/61 are free throws, and 40/47 are fouls). video log had 241 taggable sub-events of these types.
  UW-Stevens Point Pointers: matched 220/237 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 60/60 are free throws, and 32/48 are fouls). video log had 228 taggable sub-events of these types.
  UW-Platteville Pioneers: matched 164/176 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 20/20 are free throws, and 19/26 are fouls). video log had 165 taggable sub-events of these types.
  UW-Eau Claire Blugolds: matched 194/212 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 48/48 are free throws, and 31/40 are fouls). video log had 203 taggable sub-events of these types.
  UW-River Falls Falcons: matched 189/202 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 42/42 are free throws, and 28/35 are fouls). video log had 198 taggable sub-events of these types.
  UW-Platteville Pioneers: matched 184/201 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 41/42 are free throws, and 26/38 are fouls). video log had 191 taggable sub-events of these types.
  UW-La Crosse Eagles: matched 198/216 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 51/51 are free throws, and 28/39 are fouls). video log had 203 taggable sub-events of these types.
  UW-La Crosse Eagles: matched 208/227 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 54/56 are free throws, and 32/46 are fouls). video log had 214 taggable sub-events of these types.
  UW-Stout Blue Devils: matched 216/224 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 59/59 are free throws, and 39/43 are fouls). video log had 219 taggable sub-events of these types.
  Loras Duhawks: matched 220/238 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 54/56 are free throws, and 38/42 are fouls). video log had 232 taggable sub-events of these types.
  Washington-St. Louis Bears: matched 169/175 made/missed-shot, turnover, free-throw & foul pbp_events rows to a video clip description via a single global order-preserving alignment across the whole game (of which 18/18 are free throws, and 17/19 are fouls). video log had 171 taggable sub-events of these types.
                 opponent  event_order                   team  \
0   St. Thomas (TX) Celts            0                   None
1   St. Thomas (TX) Celts            1  St. Thomas (TX) Celts
2   St. Thomas (TX) Celts            2          UW-Whitewater
3   St. Thomas (TX) Celts            3  St. Thomas (TX) Celts
4   St. Thomas (TX) Celts            4          UW-Whitewater
5   St. Thomas (TX) Celts            5  St. Thomas (TX) Celts
6   St. Thomas (TX) Celts            6  St. Thomas (TX) Celts
7   St. Thomas (TX) Celts            7          UW-Whitewater
8   St. Thomas (TX) Celts            8          UW-Whitewater
9   St. Thomas (TX) Celts            9  St. Thomas (TX) Celts
10  St. Thomas (TX) Celts           10  St. Thomas (TX) Celts
11  St. Thomas (TX) Celts           11  St. Thomas (TX) Celts
12  St. Thomas (TX) Celts           12          UW-Whitewater
13  St. Thomas (TX) Celts           13  St. Thomas (TX) Celts
14  St. Thomas (TX) Celts           14  St. Thomas (TX) Celts
15  St. Thomas (TX) Celts           15  St. Thomas (TX) Celts
16  St. Thomas (TX) Celts           16  St. Thomas (TX) Celts
17  St. Thomas (TX) Celts           17          UW-Whitewater
18  St. Thomas (TX) Celts           18          UW-Whitewater
19  St. Thomas (TX) Celts           19  St. Thomas (TX) Celts

              player         event_type  \
0                NaN      period_marker
1    Charles Gitonga      jump_ball_won
2       Brock Marino     jump_ball_lost
3     Corey Thompson          made_shot
4       Isaac Verges           turnover
5      Angel Johnson              steal
6     Nathan Kongolo        missed_shot
7      Collin Madson  rebound_defensive
8       Isaac Verges           turnover
9     Nathan Kongolo              steal
10     Angel Johnson          made_shot
11    Nathan Kongolo             assist
12      Isaac Verges        missed_shot
13  Nicholas Buffalo  rebound_defensive
14    Corey Thompson        missed_shot
15    Corey Thompson  rebound_offensive
16    Corey Thompson           turnover
17     Collin Madson          made_shot
18         Luke Bara             assist
19     Angel Johnson          made_shot

                                         raw_text  video_clip_number  \
0                                  Start 1st Half                NaN
1                  Charles Gitonga Wins Jump Ball                NaN
2                    Brock Marino Loses Jump Ball                NaN
3   Corey Thompson Makes 2PT Turnaround Jump Shot                1.0
4               Isaac Verges Turnover (Lost Ball)                2.0
5                            Angel Johnson Steals                NaN
6             Nathan Kongolo Misses 3PT Jump Shot                3.0
7                 Collin Madson Defensive Rebound                NaN
8                Isaac Verges Turnover (Bad Pass)                4.0
9                           Nathan Kongolo Steals                NaN
10                  Angel Johnson Makes 2PT Layup                5.0
11                         Nathan Kongolo Assists                NaN
12                  Isaac Verges Misses 2PT Layup                6.0
13             Nicholas Buffalo Defensive Rebound                NaN
14                Corey Thompson Misses 2PT Layup                7.0
15               Corey Thompson Offensive Rebound                NaN
16                        Corey Thompson Turnover                8.0
17                  Collin Madson Makes 2PT Layup                9.0
18                              Luke Bara Assists                NaN
19      Angel Johnson Makes 2PT Pull Up Jump Shot               10.0

   video_result    video_player  \
0           NaN             NaN
1           NaN             NaN
2           NaN             NaN
3    Make 2 Pts  Corey Thompson
4      Turnover    Isaac Verges
5           NaN             NaN
6    Miss 3 Pts  Nathan Kongolo
7           NaN             NaN
8      Turnover    Isaac Verges
9           NaN             NaN
10   Make 2 Pts   Angel Johnson
11          NaN             NaN
12   Miss 2 Pts    Isaac Verges
13          NaN             NaN
14   Miss 2 Pts  Corey Thompson
15          NaN             NaN
16     Turnover  Corey Thompson
17   Make 2 Pts   Collin Madson
18          NaN             NaN
19   Make 2 Pts   Angel Johnson

                                                                                                           video_description
0                                                                                                                        NaN
1                                                                                                                        NaN
2                                                                                                                        NaN
3                                                       1 Corey Thompson > ISO > Top > Drives Right > To Basket > Make 2 Pts
4                                                                                   0 Isaac Verges > No Play Type > Turnover
5                                                                                                                        NaN
6                            0 Nathan Kongolo > Transition > Left Wing > No Dribble Jumper > Guarded > Long/3pt > Miss 3 Pts
7                                                                                                                        NaN

      opponent   game_date           team                  player  started  PTS  FGM  FGA  FG3M  FG3A  FTM  FTA  OREB  DREB  REB  AST  STL  BLK  TO  PF    FG%    3P%    FT%
0   Alma Scots  2025-12-20     Alma Scots         Donovan Collins     True   17    5   10     5     9    2    3     0     0    0    1    0    0   0   0   50.0   55.6   66.7
16  Alma Scots  2025-12-20  UW-Whitewater         Joey Berezowitz    False   16    6    8     4     5    0    0     2     0    2    0    2    0   0   0   75.0   80.0    NaN
4   Alma Scots  2025-12-20     Alma Scots         Korbin Heitzman     True   14    4   10     0     1    6    8     5    11   16    1    0    1   6   4   40.0    0.0   75.0
11  Alma Scots  2025-12-20  UW-Whitewater           Collin Madson     True   13    4    7     0     0    5    6     1     5    6    3    2    0   0   2   57.1    NaN   83.3
15  Alma Scots  2025-12-20  UW-Whitewater              Jake Quast    False   11    5    7     1     2    0    1     0     3    3    0    3    0   2   3   71.4   50.0    0.0
12  Alma Scots  2025-12-20  UW-Whitewater         Darius Chestnut    False   10    4    4     2     2    0    0     0     0    0    0    0    0   0   2  100.0  100.0    NaN
2   Alma Scots  2025-12-20     Alma Scots            Josh Elliott     True    9    3    7     2     6    1    1     0     3    3    0    1    0   3   1   42.9   33.3  100.0
13  Alma Scots  2025-12-20  UW-Whitewater            Isaac Verges     True    9    4    7     1     2    0    0     0     2    2    1    0    0   1   3   57.1   50.0    NaN
23  Alma Scots  2025-12-20  UW-Whitewater  Tyshawn Teague-Johnson    False    9    4    7     1     1    0    1     1     2    3    2    0    0   2   1   57.1  100.0    0.0
1   Alma Scots  2025-12-20     Alma Scots            Elijah Sykes    False    7    3    9     1     4    0    0     0     0    0    2    1    0   1   0   33.3   25.0    NaN
10  Alma Scots  2025-12-20  UW-Whitewater            Brock Marino     True    7    1    6     0     0    5    6     1     1    2    1    4    0   1   3   16.7    NaN   83.3
6   Alma Scots  2025-12-20     Alma Scots       Luciano Guerrazzi    False    5    2    2     1     1    0    0     1     1    2    1    1    1   5   1  100.0  100.0    NaN
21  Alma Scots  2025-12-20  UW-Whitewater           Richie Warren     True    5    1    6     0     1    3    3     2     2    4    2    3    1   1   2   16.7    0.0  100.0
3   Alma Scots  2025-12-20     Alma Scots            Joss Bradley    False    3    0    2     0     0    3    4     1     1    2    4    0    1   0   2    0.0    NaN   75.0
9   Alma Scots  2025-12-20  UW-Whitewater         Agape Keyes Jr.    False    3    1    1     1     1    0    0     0     0    0    0    1    0   0   1  100.0  100.0    NaN

  ... 684 more row(s) of 699 (SHOW_ROWS = 15)

Found 0 official box-score file(s) to cross-validate against:

Validating PBP-reconstructed per-player box score against the official box-score file, where available:

Every played, scouted game in uww_team_schedule has a box score in pbp_box_score. No gaps found.
Validating lineup-level PTS totals against the schedule:

  St. Thomas (TX) Celts 2025-11-14: lineup box score 73-81 vs. schedule 73.0-81.0 [OK]
  Eureka Red Devils 2025-11-15: lineup box score 116-73 vs. schedule 116.0-73.0 [OK]
  Aurora Spartans 2025-11-19: lineup box score 82-73 vs. schedule 82.0-73.0 [OK]
  Simpson Storm 2025-11-25: lineup box score 100-78 vs. schedule 100.0-78.0 [OK]
  Ripon Red Hawks 2025-11-07: lineup box score 76-58 vs. schedule 76.0-58.0 [OK]
  Lawrence Vikings 2025-12-10: lineup box score 88-58 vs. schedule 88.0-58.0 [OK]
  Carroll (WI) Pioneers 2025-12-13: lineup box score 64-60 vs. schedule 64.0-60.0 [OK]
  Hope Flying Dutchmen 2025-12-19: lineup box score 95-92 vs. schedule 95.0-92.0 [OK]
  Alma Scots 2025-12-20: lineup box score 90-61 vs. schedule 90.0-61.0 [OK]
  Elmhurst Bluejays 2025-12-02: lineup box score 88-72 vs. schedule 88.0-72.0 [OK]
  Coe Kohawks 2025-12-30: lineup box score 73-86 vs. schedule 73.0-86.0 [OK]
  UW-River Falls Falcons 2026-01-10: lineup box score 67-59 vs. schedule 67.0-59.0 [OK]
  UW-La Crosse Eagles 2026-01-14: lineup box score 63-60 vs. schedule 63.0-60.0 [OK]
  UW-Stout Blue Devils 2026-01-17: lineup box score 72-54 vs. schedule 72.0-54.0 [OK]
  UW-Platteville Pioneers 2026-01-21: lineup box score 60-70 vs. schedule 60.0-70.0 [OK]
  UW-Eau Claire Blugolds 2026-01-24: lineup box score 83-76 vs. schedule 83.0-76.0 [OK]
  UW-Oshkosh Titans 2026-01-28: lineup box score 101-91 vs. schedule 101.0-91.0 [OK]
  UW-Oshkosh Titans 2026-01-03: lineup box score 78-90 vs. schedule 78.0-90.0 [OK]
  UW-Stevens Point Pointers 2026-01-07: lineup box score 71-79 vs. schedule 71.0-79.0 [OK]
  UW-Platteville Pioneers 2026-02-11: lineup box score 66-51 vs. schedule 66.0-51.0 [OK]
  UW-Eau Claire Blugolds 2026-02-14: lineup box score 76-68 vs. schedule 76.0-68.0 [OK]
  UW-Stevens Point Pointers 2026-02-18: lineup box score 80-70 vs. schedule 80.0-70.0 [OK]
  UW-River Falls Falcons 2026-02-21: lineup box score 69-62 vs. schedule 69.0-62.0 [OK]
  UW-Platteville Pioneers 2026-02-26: lineup box score 66-56 vs. schedule 66.0-56.0 [OK]
  UW-La Crosse Eagles 2026-02-28: lineup box score 78-81 vs. schedule 78.0-81.0 [OK]
  UW-La Crosse Eagles 2026-02-04: lineup box score 65-68 vs. schedule 65.0-68.0 [OK]
  UW-Stout Blue Devils 2026-02-07: lineup box score 78-77 vs. schedule 78.0-77.0 [OK]
  Loras Duhawks 2026-03-06: lineup box score 85-76 vs. schedule 85.0-76.0 [OK]
  Washington-St. Louis Bears 2026-03-07: lineup box score 71-74 vs. schedule 71.0-74.0 [OK]

,opponent,game_date,team,lineup,MIN,+/-,PTS,FGM,FGA,FG3M,FG3A,FTM,FTA,OREB,DREB,REB,AST,STL,BLK,TO,PF,FG%,3P%,FT%
6,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Korbin Heitzman, Logan St. Martin, ...",12.62,-14.0,11,2,13,2,6,5,6,4,7,11,1,1,0,9,4,15.4,33.3,83.3
8,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Korbin Heitzman, Preston Malpass, R...",3.42,-0.0,9,4,6,1,2,0,1,1,1,2,2,0,0,1,1,66.7,50.0,0.0
9,Alma Scots,2025-12-20,Alma Scots,"Elijah Sykes, Josh Elliott, Joss Bradley, Korbin Heitzman, Logan S...",3.74,1.0,9,3,4,1,2,2,2,0,3,3,1,0,1,3,2,75.0,50.0,100.0
2,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Elijah Sykes, Luciano Guerrazzi, Preston Malpass,...",3.44,-0.0,8,3,6,2,4,0,0,1,1,2,3,3,0,2,1,50.0,50.0,NaN
4,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Joss Bradley, Korbin Heitzman, Luci...",3.55,-6.0,6,1,4,1,4,3,4,2,3,5,1,1,1,2,1,25.0,25.0,75.0
3,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Joss Bradley, Korbin Heitzman, Loga...",3.34,-4.0,5,2,3,0,0,1,2,0,2,2,1,0,2,1,3,66.7,NaN,50.0
0,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Elijah Sykes, Joss Bradley, Korbin Heitzman, Luci...",1.87,2.0,4,2,4,0,0,0,0,0,1,1,1,0,0,0,0,50.0,NaN,NaN
1,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Elijah Sykes, Joss Bradley, Luciano Guerrazzi, Pr...",1.95,3.0,3,1,2,1,1,0,0,0,3,3,1,0,0,1,1,50.0,100.0,NaN
5,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Joss Bradley, Luciano Guerrazzi, Pr...",1.45,-1.0,3,1,2,1,2,0,0,1,1,2,1,0,0,1,1,50.0,50.0,NaN
10,Alma Scots,2025-12-20,Alma Scots,"Elijah Sykes, Josh Elliott, Joss Bradley, Korbin Heitzman, Luciano...",1.82,-4.0,3,1,2,0,1,1,2,2,0,2,0,0,0,1,0,50.0,0.0,50.0
7,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Korbin Heitzman, Luciano Guerrazzi,...",0.03,-0.0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,NaN,NaN,NaN
11,Alma Scots,2025-12-20,Alma Scots,"Elijah Sykes, Josh Elliott, Korbin Heitzman, Preston Malpass, Rain...",1.30,-3.0,0,0,3,0,2,0,0,1,1,2,0,0,0,0,0,0.0,0.0,NaN
12,Alma Scots,2025-12-20,Alma Scots,"Elijah Sykes, Joss Bradley, Korbin Heitzman, Luciano Guerrazzi, Pr...",1.20,-3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,NaN,NaN,NaN
17,Alma Scots,2025-12-20,UW-Whitewater,"Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren",12.04,8.0,21,7,17,1,3,6,7,4,5,9,3,6,0,2,5,41.2,33.3,85.7
22,Alma Scots,2025-12-20,UW-Whitewater,"Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren, Tyshawn ...",3.62,3.0,11,4,7,3,4,0,0,0,2,2,2,1,0,0,1,57.1,75.0,NaN

  ... 1,020 more row(s) of 1,035 (SHOW_ROWS = 15)
Wheaton (IL) Thunder season 5-man lineup box scores (22 game(s) of PBP data, 143 distinct units):
                                                                           lineup  \
0     Brady Wynja, Carson Grier, Devin Martin, Kyan VanderWoude, Soren Richardson
1     Carson Grier, Devin Martin, Kyan VanderWoude, Kyle Neibch, Soren Richardson
2      Carson Grier, Devin Martin, Kyan VanderWoude, Reid Olson, Soren Richardson
3    Carson Grier, Devin Martin, Kyan VanderWoude, Noah Hedrick, Soren Richardson
4       Brady Wynja, Carson Grier, Kyan VanderWoude, Reid Olson, Soren Richardson
..                                                                            ...
138                 Cayden Mudd, Jace Olson, Jack Speers, Reid Olson, Ty Ferguson
139           Brady Wynja, Christian Veirs, Devin Martin, Jack Speers, Reid Olson
140       Carson Grier, Kyan VanderWoude, Kyle Neibch, Luca Carbonaro, Reid Olson
141           Carson Grier, Jace Olson, Kyan VanderWoude, Kyle Neibch, Reid Olson
142             Carson Grier, Evan Montandon, Jace Olson, Jack Speers, Reid Olson

     GP    MIN   +/-  PTS  FGM  FGA   FG%  FG3M  FG3A  ...  FTA   FT%  OREB  \
0    22  147.8  -1.0  309  123  250  49.2    21    59  ...   68  61.8    61
1    18  103.3 -47.0  219   80  155  51.6    18    54  ...   64  64.1    27
2    19   63.8  -7.0  135   46  101  45.5    13    39  ...   41  73.2    24
3     8   45.5  -9.0  118   35   69  50.7     9    23  ...   46  84.8    20
4    14   36.6 -19.0   72   26   52  50.0     7    22  ...   14  92.9     9
..   ..    ...   ...  ...  ...  ...   ...   ...   ...  ...  ...   ...   ...
138   1    0.0   0.0    0    0    0   NaN     0     0  ...    0   NaN     0
139   1    0.0   0.0    0    0    0   NaN     0     0  ...    0   NaN     0
140   1    0.0   2.0    0    0    0   NaN     0     0  ...    0   NaN     0
141   1    0.0  -1.0    0    0    0   NaN     0     0  ...    0   NaN     0
142   1    0.0   0.0    0    0    0   NaN     0     0  ...    0   NaN     0

     DREB  REB  AST  STL  BLK  TO  PF
0     106  167   61   26    6  42  44
1      73  100   38   22    8  29  34
2      21   45   29    7    1  11  31
3      29   49   19    8    4  12  15
4      21   30   15    5    2  10  11
..    ...  ...  ...  ...  ...  ..  ..
138     0    0    0    0    0   0   0
139     0    0    0    0    0   0   0
140     0    0    0    0    0   0   1
141     0    0    0    0    0   0   1
142     0    0    0    0    0   0   0

[143 rows x 22 columns]
Frame archive: 32,487 tracking frame(s) are packed in clip videos -- unpacked automatically when a step reads them.
Frame capture: VISION_ALSO_GAMES '2_21_26 Millikin @ Wheaton' -- already captured, or not one of the games in the window
Frame capture: UWW -- working on 2026-03-07 Washington-St. Louis Bears (45 of 167 clips still untagged -- Analytics > Film Tagging); its next game waits until the coaches finish it.
Frame capture: opponent -- working on 2026-02-24 Wheaton (IL) Thunder vs North Park Vikings (164 of 244 clips still untagged -- Analytics > Film Tagging); its next game waits until the coaches finish it.
Frame capture: game pages still to capture -- 0 of the upcoming opponent's (Wheaton (IL) Thunder), 0 of UWW's; UWW games first (VISION_CAPTURE_FIRST), newest first.
Frame capture: every game with a clip page is already in the cache (set VISION_RETAG = True to redo).
Clips with frames: 1671 of 1685 in uww_clip_frames.csv
  (15 more row(s) with errors are from an old TEST capture of 2026-03-06 Loras Duhawks -- replaced when that game is captured)
  Captured clips with no Title: 1138 clip(s) from 8 game(s) not in uww_plays.csv added as play calls (553 placed on the play-by-play clock through the video-tagging match; the rest have no half / clock, so no lineups). The app's Play review is where they get tagged.
  Blank Team on 21 clip(s) (Synergy's Non Shooting Foul clips): filled with the named player's own team -- 20 from his other clips in the game, 0 from the play-by-play (he drew the foul, so his team had the ball)
  Play clips by game type: UWW 784 clip(s) in 6 game(s), Opponent 423 clip(s) in 2 game(s), Other 675 clip(s) in 4 game(s)
  [saves] fetched branch 'saves': 0 new saved review file(s) copied into data/play_review_saves (47 on the branch; its newest commit: 2026-10-28 11:15:51 -0500  Play review: 2026-02-21|Millikin@WheatonIL by Corey)
  [saves] 46 saved review file(s) read from play_review_saves:
    2025-12-30|WWW@COE: 1 file(s) by Corey (latest 2026-10-05 13:45 UTC) -- 20 play(s) with coach answers
    2026-01-03|WOS@WWW: 12 file(s) by Corey, someone (latest 2026-10-10 00:18 UTC) -- 77 play(s) with coach answers
    2026-02-21|Millikin@WheatonIL: 4 file(s) by Corey (latest 2026-10-28 16:15 UTC) -- 1 play(s) with coach answers
    2026-02-24|WheatonIL@NorthPark: 7 file(s) by Coach Jake, Corey (latest 2026-10-27 14:07 UTC) -- 115 play(s) with coach answers
    2026-02-26|MarianWI@MSOE: 2 file(s) by Coach Jake, CoreyTEST (latest 2026-10-21 15:41 UTC) -- 14 play(s) with coach answers
    2026-03-07|UWWhitewater@Wash(StLouis): 20 file(s) by COACH JAKE, Coach Jake, Corey (latest 2026-10-27 13:54 UTC) -- 137 play(s) with coach answers
  Film Tagging: answers saved before the tracking reset, and test saves, are set aside (TITLE_CHECKS_BEFORE_RESET = True uses the old ones again):
    - 2026-01-03|WOS@WWW by unknown coach, saved 2026-10-01T17:23:50.635Z -- before the restart on the Synergy exports
    - 2026-01-03|WOS@WWW by unknown coach, saved 2026-09-30T18:14:20.554Z -- before the restart on the Synergy exports
    - 2026-01-03|WOS@WWW by unknown coach, saved 2026-10-01T19:48:37.750Z -- before the restart on the Synergy exports
    - 2026-01-03|WOS@WWW by Corey, saved 2026-10-07T19:03:11+00:00 -- before the restart on the Synergy exports
    - 2026-01-03|WOS@WWW by Corey, saved 2026-10-09T00:23:56+00:00 -- before the restart on the Synergy exports
    - 2026-01-03|WOS@WWW by Corey, saved 2026-10-10T00:18:04+00:00 -- before the restart on the Synergy exports
    - 2026-02-26|MarianWI@MSOE by CoreyTEST, saved 2026-10-13T21:18:09+00:00 -- a test save
  App tags: 122 clip(s) tagged in the app (no Title) and 0 coach Title(s) corrected in the app -- used in every play-call table like a Title; 18 play(s) with more than one action recorded
  Lineups: 19 clip(s) with no matched play-by-play event got their uww lineup from the game clock
  Lineups: 19 clip(s) with no matched play-by-play event got their opp lineup from the game clock
  App tags: 80 clip(s) tagged in the app (no Title) and 0 coach Title(s) corrected in the app -- used in every play-call table like a Title; 2 play(s) with more than one action recorded
  Upcoming-opponent games: 215 clip(s) are the OTHER team's offense -- kept, but excluded from Wheaton (IL) Thunder's play-call scouting.
  Lineups: 65 clip(s) with no matched play-by-play event got their self lineup from the game clock
  Lineups: 65 clip(s) with no matched play-by-play event got their their lineup from the game clock
  App tags: 20 clip(s) tagged in the app (no Title) and 0 coach Title(s) corrected in the app -- used in every play-call table like a Title
  Frames matched to 1671 of 1882 clip(s) (1685 captured).
    captured page '2025-12-20 Alma Scots': 174 clip(s), 174 matched to tagged clips
    captured page '2025-12-30 Coe Kohawks': 175 clip(s), 175 matched to tagged clips
    captured page '2026-01-03 UW-Oshkosh Titans': 196 clip(s), 196 matched to tagged clips
    captured page '2026-02-21 MSOE Raiders vs Aurora Spartans': 165 clip(s), 165 matched to tagged clips
    captured page '2026-02-21 Wheaton (IL) Thunder vs Millikin B': 179 clip(s), 179 matched to tagged clips
    captured page '2026-02-24 MSOE Raiders vs Lakeland Muskies': 179 clip(s), 179 matched to tagged clips
    captured page '2026-02-24 Wheaton (IL) Thunder vs North Park': 244 clip(s), 244 matched to tagged clips
    captured page '2026-02-26 MSOE Raiders vs Marian (WI) Sabres': 191 clip(s), 191 matched to tagged clips
    captured page '2026-03-06 Loras Duhawks': 15 clip(s), 1 matched to tagged clips
    captured page '2026-03-07 Washington-St. Louis Bears': 167 clip(s), 167 matched to tagged clips
    tagged game 2026-01-03 WEC@WSP: 140 clip(s), no frames -- a game between two other teams (not UWW or the upcoming opponent), which Frame capture doesn't capture; used from its Titles only
  (frame check: 34 non-possession line(s) (free throws, no violation) in 2025-12-20 WWW@AC have no clip on Synergy's page and are not counted)
  (frame check: 36 non-possession line(s) (free throws, no violation) in 2025-12-30 WWW@COE have no clip on Synergy's page and are not counted)
  (frame check: 1 non-possession line(s) (free throws, no violation) in 2026-01-03 WOS@WWW have no clip on Synergy's page and are not counted)
  play_call_summary: 191 offensive row(s), 179 defensive.
  screen_coverage: 113 tagged screen coverage(s) -- Defenses UWW faced: 54, UWW defense: 49, Opponent defense: 9, Defenses opponent faced: 1
  screen defense by defender: 7 row(s) (defenders with 2+ tagged screens); action reads: 88 row(s) from Film Tagging's Actions / Players -- 4 team(s), 2 defender reaction row(s)
UWW games: 784 clip(s) across 5 game(s); decoded {'No call': 526, 'App tag': 116, 'Clean': 83, 'Untagged': 58, 'Partial': 1}; matched to play-by-play 679/784 ({'synergy string': 561, 'player + clock': 77, 'clip order + foul by the defense': 24, 'clip order + player': 11, 'clock + result': 6}).
  First unmatched clips (date, period, clock, player, result):

     game_date period  Clock           player                result
0   2025-12-20     H1    NaN  Donovan Collins          No Violation
3   2025-12-20     H1  19:11     Brock Marino            Miss 2 Pts
5   2025-12-20     H1    NaN    Collin Madson          No Violation
8   2025-12-20     H1    NaN    Richie Warren            Free Throw
21  2025-12-20     H1    NaN  Korbin Heitzman  Shot Clock Violation
29  2025-12-20     H1    NaN  Korbin Heitzman            Free Throw

  ... 99 more row(s) of 105 (SHOW_ROWS = 6)
  Most-called: {'5 Out Motion': 95, 'Ball Screen': 15, 'BLOB Line Motion': 7, 'BLOB': 7, 'BLOB Box Motion': 6, 'BLOB Set': 6}
  Shot clock estimated for 679/784 clip(s) (needs a matched pbp event).
  Defense tagged on 264/784 clip(s): {'Man-to-Man': 263, 'ZONE': 1}; press on 67, coverage called on 216.
    Possessions: 399 offensive, 385 defensive -> 163 defense-faced tag(s), 101 defense-played tag(s).
upcoming-opponent games: 423 clip(s) across 2 game(s); decoded {'Untagged': 343, 'App tag': 62, 'No call': 18}; matched to play-by-play 336/423 ({'synergy string': 231, 'player + clock': 51, 'clip order + player': 27, 'clock + result': 17, 'clip order + foul by the defense': 10}).
  First unmatched clips (date, period, clock, player, result):

     game_date period Clock            player             result
15  2026-02-21     H1  None      Devin Martin               Foul
24  2026-02-21     H1  None   Nate Straughter  Non Shooting Foul
27  2026-02-21     H1  None  Kyan VanderWoude         Make 2 Pts
31  2026-02-21     H1  None     Caden Nichols         Miss 3 Pts
34  2026-02-21     H1  None    Pat Origliasso        Run Offense
44  2026-02-21     H1  None      Carson Grier  Non Shooting Foul

  ... 81 more row(s) of 87 (SHOW_ROWS = 6)
  Most-called: {'5 Out Motion': 41, 'Set': 8, 'BLOB Set': 4, 'Motion': 2, 'SLOB 5 Out Motion': 1, 'Spain': 1}
  Shot clock estimated for 336/423 clip(s) (needs a matched pbp event).
  Defense tagged on 79/423 clip(s): {'Man-to-Man': 79}; press on 9, coverage called on 422.
    Possessions: 208 offensive, 215 defensive -> 41 defense-faced tag(s), 38 defense-played tag(s).
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  CLIP ORDER CHECK: 56 clip(s) sit at a spot in the game video that doesn't match their game clock (captured at the wrong place?):

     game_date game_code period  clip_number  video_start_s   clock                                                            description
0   2025-12-20    WWW@AC     H1            4          356.5  1151.0  21 Brock Marino > Post-Up > Left Block > Right Shoulder > Dribble ...
1   2025-12-20    WWW@AC     H1           12          465.5  1084.0                            24 Richie Warren > Cut > Flash > Miss 2 Pts
2   2025-12-20    WWW@AC     H2          145         4755.5   609.0        12 Jake Quast > Spot-Up > Drives Right > To Basket > Miss 2 Pts
3   2025-12-20    WWW@AC     H2          179         5566.3   238.0  2 Kelton Mcewen > Transition > Ballhandler > Dribble Jumper > Long...
4   2025-12-30   WWW@COE     H2          466         5734.7   810.0                4 Deuce Walters > No Play Type > To Basket > Miss 2 Pts
5   2026-01-03   WOS@WWW     H2           85         2060.2  1191.0                   2 Joey LaChapell > Spot-Up > Drives Right > Turnover
6   2026-01-03   WOS@WWW     H2           87         2088.5  1177.0                      32 Luke Bara > Non Possession > Non Shooting Foul
7   2026-01-03   WOS@WWW     H2           88         2108.6  1175.0                            21 Brock Marino > Cut > Basket > Make 2 Pts
8   2026-01-03   WOS@WWW     H2           89         2118.2  1163.0  4 Michael Metcalf-Grassman > Spot-Up > Drives Right > To Basket > ...
9   2026-01-03   WOS@WWW     H2           90         2130.6  1139.0                              21 Brock Marino > No Play Type > Turnover
10  2026-01-03   WOS@WWW     H2           93         2153.9  1130.0  21 Carter Thomas > Spot-Up > No Dribble Jumper > Guarded > Long/3p...
11  2026-01-03   WOS@WWW     H2           91         2156.0  1134.0  4 Michael Metcalf-Grassman > Transition > Ballhandler > To Basket ...
12  2026-01-03   WOS@WWW     H2           95         2196.9  1104.0                           24 Richie Warren > Cut > Basket > Miss 2 Pts
13  2026-01-03   WOS@WWW     H2           96         2220.4  1087.0  23 Oskar Kangas > P&R Ball Handler > Right P&R > Baseline > Dribbl...
14  2026-01-03   WOS@WWW     H2           97         2236.5  1067.0  15 Collin Madson > ISO > Right > Drives Right > To Basket > Miss 2...

  ... 41 more row(s) of 56 (SHOW_ROWS = 15)
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  [reuse] uww_player_tracks: the last run's 44,090 row(s)
  [reuse] uww_tracking_report: the last run's 2 row(s)
  [reuse] uww_trk_event_candidates: the last run's 23 row(s)
  [reuse] uww_trk_lineup_slots: the last run's 4,080 row(s)
  [reuse] player tracking (switched off this run): the last run's results put back on 411 clip(s) (18 column(s))
  [reuse] tag model (switched off this run): the last run's results put back on 1,028 clip(s) (21 column(s))
  [reuse] uww_tag_model_report: the last run's 10 row(s)
  Automatic answers used for untagged plays / prefilled in Film Tagging: defense, situation | offered as 'not sure' only: formation, play_call, press, primary_action, ball_screen_coverage, offball_coverage, screener, screen_defender
  Tag model history: 1 field(s) changed since the last run -> uww_tag_model_history.csv (the app: Analytics > Film Tagging > How good is the automatic tagging?)
Film Tagging: checking which of 1,136 captured clip(s) still have their film on disk...
Film Tagging: reading the coaches' saved answers...
Film Tagging: answer lists -- Situation 7, Formation 20, Play call 37, Main action 41, Defense 2, Press 6, Ball-screen coverage 16, Off-ball coverage 17, Screener 34, Screen defender 34
Film Tagging: removed the open batch for 2026-01-03 UWOshkosh@UWWhitewater from the app -- not part of this run (answers already saved are kept)
Film Tagging: 2026-02-21 Millikin@WheatonIL: making the video of each of 79 play(s) for the app...
  [film tagging] Millikin@WheatonIL play videos made: 0 / 79 (0%) -- 0.0 min so far
  [film tagging] Millikin@WheatonIL play videos made: 5 / 79 (6%) -- 0.6 min so far, ~8.7 min left
  [film tagging] Millikin@WheatonIL play videos made: 10 / 79 (12%) -- 1.0 min so far, ~6.6 min left
  [film tagging] Millikin@WheatonIL play videos made: 15 / 79 (18%) -- 1.4 min so far, ~6.1 min left
  [film tagging] Millikin@WheatonIL play videos made: 19 / 79 (24%) -- 2.1 min so far, ~6.7 min left
  [film tagging] Millikin@WheatonIL play videos made: 20 / 79 (25%) -- 2.4 min so far, ~7.0 min left
  [film tagging] Millikin@WheatonIL play videos made: 24 / 79 (30%) -- 3.1 min so far, ~7.0 min left
  [film tagging] Millikin@WheatonIL play videos made: 25 / 79 (31%) -- 3.2 min so far, ~6.9 min left
  [film tagging] Millikin@WheatonIL play videos made: 28 / 79 (35%) -- 3.8 min so far, ~6.9 min left
  [film tagging] Millikin@WheatonIL play videos made: 30 / 79 (37%) -- 4.2 min so far, ~6.9 min left
  [film tagging] Millikin@WheatonIL play videos made: 34 / 79 (43%) -- 5.0 min so far, ~6.6 min left
  [film tagging] Millikin@WheatonIL play videos made: 35 / 79 (44%) -- 5.2 min so far, ~6.5 min left
  [film tagging] Millikin@WheatonIL play videos made: 38 / 79 (48%) -- 6.0 min so far, ~6.4 min left
  [film tagging] Millikin@WheatonIL play videos made: 40 / 79 (50%) -- 6.4 min so far, ~6.2 min left
  [film tagging] Millikin@WheatonIL play videos made: 42 / 79 (53%) -- 6.9 min so far, ~6.1 min left
  [film tagging] Millikin@WheatonIL play videos made: 45 / 79 (56%) -- 7.5 min so far, ~5.6 min left
  [film tagging] Millikin@WheatonIL play videos made: 49 / 79 (62%) -- 8.0 min so far, ~4.9 min left
  [film tagging] Millikin@WheatonIL play videos made: 50 / 79 (63%) -- 8.2 min so far, ~4.7 min left
  [film tagging] Millikin@WheatonIL play videos made: 54 / 79 (68%) -- 8.8 min so far, ~4.1 min left
  [film tagging] Millikin@WheatonIL play videos made: 55 / 79 (69%) -- 8.9 min so far, ~3.9 min left
  [film tagging] Millikin@WheatonIL play videos made: 60 / 79 (75%) -- 9.5 min so far, ~3.0 min left
  [film tagging] Millikin@WheatonIL play videos made: 63 / 79 (79%) -- 10.0 min so far, ~2.5 min left
  [film tagging] Millikin@WheatonIL play videos made: 65 / 79 (82%) -- 10.2 min so far, ~2.2 min left
  [film tagging] Millikin@WheatonIL play videos made: 69 / 79 (87%) -- 10.8 min so far, ~1.6 min left
  [film tagging] Millikin@WheatonIL play videos made: 72 / 79 (91%) -- 11.4 min so far, ~1.1 min left
  [film tagging] Millikin@WheatonIL play videos made: 75 / 79 (94%) -- 11.6 min so far, ~0.6 min left
  [film tagging] Millikin@WheatonIL play videos made: 79 / 79 (100%) -- 12.2 min so far
  [film tagging] copying Millikin@WheatonIL's batch into the app's data folder...
  [play review] copied to the app: ../data\play_tag\tag_2026_02_21_Millikin_WheatonIL (219 MB) -- commit and push it with the data
Film Tagging: 2026-02-21 Millikin@WheatonIL: 79 clip(s) to tag -- the scouted team's offense (every untagged play; the rest once those are tagged) (of 179 untagged) -- in the app: Analytics > Film Tagging
Film Tagging: 2026-02-24 WheatonIL@NorthPark: making the video of each of 88 play(s) for the app...
  [film tagging] WheatonIL@NorthPark play videos made: 0 / 88 (0%) -- 0.0 min so far
  [film tagging] WheatonIL@NorthPark play videos made: 3 / 88 (3%) -- 0.9 min so far, ~24.3 min left
  [film tagging] WheatonIL@NorthPark play videos made: 5 / 88 (5%) -- 1.3 min so far, ~21.7 min left
  [film tagging] WheatonIL@NorthPark play videos made: 7 / 88 (7%) -- 1.9 min so far, ~21.5 min left
  [film tagging] WheatonIL@NorthPark play videos made: 10 / 88 (11%) -- 2.3 min so far, ~17.8 min left
  [film tagging] WheatonIL@NorthPark play videos made: 12 / 88 (13%) -- 2.8 min so far, ~17.6 min left
  [film tagging] WheatonIL@NorthPark play videos made: 15 / 88 (17%) -- 3.1 min so far, ~15.0 min left
  [film tagging] WheatonIL@NorthPark play videos made: 18 / 88 (20%) -- 3.8 min so far, ~14.7 min left
  [film tagging] WheatonIL@NorthPark play videos made: 20 / 88 (22%) -- 4.0 min so far, ~13.7 min left
  [film tagging] WheatonIL@NorthPark play videos made: 23 / 88 (26%) -- 4.6 min so far, ~12.9 min left
  [film tagging] WheatonIL@NorthPark play videos made: 25 / 88 (28%) -- 5.0 min so far, ~12.6 min left
  [film tagging] WheatonIL@NorthPark play videos made: 29 / 88 (32%) -- 5.7 min so far, ~11.6 min left
  [film tagging] WheatonIL@NorthPark play videos made: 30 / 88 (34%) -- 5.8 min so far, ~11.3 min left
  [film tagging] WheatonIL@NorthPark play videos made: 33 / 88 (37%) -- 6.5 min so far, ~10.8 min left
  [film tagging] WheatonIL@NorthPark play videos made: 35 / 88 (39%) -- 6.8 min so far, ~10.3 min left
  [film tagging] WheatonIL@NorthPark play videos made: 38 / 88 (43%) -- 7.4 min so far, ~9.7 min left
  [film tagging] WheatonIL@NorthPark play videos made: 40 / 88 (45%) -- 7.8 min so far, ~9.3 min left
  [film tagging] WheatonIL@NorthPark play videos made: 43 / 88 (48%) -- 8.3 min so far, ~8.7 min left
  [film tagging] WheatonIL@NorthPark play videos made: 45 / 88 (51%) -- 8.6 min so far, ~8.2 min left
  [film tagging] WheatonIL@NorthPark play videos made: 48 / 88 (54%) -- 9.1 min so far, ~7.6 min left
  [film tagging] WheatonIL@NorthPark play videos made: 50 / 88 (56%) -- 9.6 min so far, ~7.3 min left
  [film tagging] WheatonIL@NorthPark play videos made: 52 / 88 (59%) -- 10.1 min so far, ~7.0 min left
  [film tagging] WheatonIL@NorthPark play videos made: 55 / 88 (62%) -- 10.8 min so far, ~6.5 min left
  [film tagging] WheatonIL@NorthPark play videos made: 58 / 88 (65%) -- 11.3 min so far, ~5.9 min left
  [film tagging] WheatonIL@NorthPark play videos made: 60 / 88 (68%) -- 11.8 min so far, ~5.5 min left
  [film tagging] WheatonIL@NorthPark play videos made: 63 / 88 (71%) -- 12.4 min so far, ~4.9 min left
  [film tagging] WheatonIL@NorthPark play videos made: 65 / 88 (73%) -- 12.7 min so far, ~4.5 min left
  [film tagging] WheatonIL@NorthPark play videos made: 69 / 88 (78%) -- 13.4 min so far, ~3.7 min left
  [film tagging] WheatonIL@NorthPark play videos made: 70 / 88 (79%) -- 13.5 min so far, ~3.5 min left
  [film tagging] WheatonIL@NorthPark play videos made: 72 / 88 (81%) -- 14.0 min so far, ~3.1 min left
  [film tagging] WheatonIL@NorthPark play videos made: 75 / 88 (85%) -- 14.5 min so far, ~2.5 min left
  [film tagging] WheatonIL@NorthPark play videos made: 77 / 88 (87%) -- 15.0 min so far, ~2.1 min left
  [film tagging] WheatonIL@NorthPark play videos made: 80 / 88 (90%) -- 15.5 min so far, ~1.6 min left
  [film tagging] WheatonIL@NorthPark play videos made: 82 / 88 (93%) -- 16.1 min so far, ~1.2 min left
  [film tagging] WheatonIL@NorthPark play videos made: 85 / 88 (96%) -- 16.6 min so far, ~0.6 min left
  [film tagging] WheatonIL@NorthPark play videos made: 88 / 88 (100%) -- 17.0 min so far
  [film tagging] copying WheatonIL@NorthPark's batch into the app's data folder...
  [play review] copied to the app: ../data\play_tag\tag_2026_02_24_WheatonIL_NorthPark (368 MB) -- commit and push it with the data
Film Tagging: 2026-02-24 WheatonIL@NorthPark: 88 clip(s) to tag -- the scouted team's offense (every untagged play; the rest once those are tagged) (of 164 untagged) -- in the app: Analytics > Film Tagging
Film Tagging: 2026-03-07 UWWhitewater@Wash(StLouis): making the video of each of 45 play(s) for the app...
  [film tagging] UWWhitewater@Wash(StLouis) play videos made: 0 / 45 (0%) -- 0.0 min so far
  [film tagging] UWWhitewater@Wash(StLouis) play videos made: 3 / 45 (6%) -- 0.6 min so far, ~8.6 min left
  [film tagging] UWWhitewater@Wash(StLouis) play videos made: 5 / 45 (11%) -- 0.9 min so far, ~6.9 min left
  [film tagging] UWWhitewater@Wash(StLouis) play videos made: 8 / 45 (17%) -- 1.4 min so far, ~6.6 min left
  [film tagging] UWWhitewater@Wash(StLouis) play videos made: 10 / 45 (22%) -- 1.9 min so far, ~6.8 min left
  [film tagging] UWWhitewater@Wash(StLouis) play videos made: 15 / 45 (33%) -- 2.6 min so far, ~5.2 min left
  [film tagging] UWWhitewater@Wash(StLouis) play videos made: 19 / 45 (42%) -- 3.2 min so far, ~4.4 min left
  [film tagging] UWWhitewater@Wash(StLouis) play videos made: 20 / 45 (44%) -- 3.3 min so far, ~4.1 min left
  [film tagging] UWWhitewater@Wash(StLouis) play videos made: 22 / 45 (48%) -- 3.9 min so far, ~4.1 min left
  [film tagging] UWWhitewater@Wash(StLouis) play videos made: 25 / 45 (55%) -- 4.4 min so far, ~3.5 min left
  [film tagging] UWWhitewater@Wash(StLouis) play videos made: 29 / 45 (64%) -- 4.9 min so far, ~2.7 min left
  [film tagging] UWWhitewater@Wash(StLouis) play videos made: 30 / 45 (66%) -- 5.1 min so far, ~2.6 min left
  [film tagging] UWWhitewater@Wash(StLouis) play videos made: 33 / 45 (73%) -- 5.7 min so far, ~2.1 min left
  [film tagging] UWWhitewater@Wash(StLouis) play videos made: 35 / 45 (77%) -- 6.0 min so far, ~1.7 min left
  [film tagging] UWWhitewater@Wash(StLouis) play videos made: 38 / 45 (84%) -- 6.6 min so far, ~1.2 min left
  [film tagging] UWWhitewater@Wash(StLouis) play videos made: 40 / 45 (88%) -- 6.8 min so far, ~0.9 min left

### Continue

In [ ]:
# Continue from a section after an error, e.g.:
# run_parser("tagging", start_at="55c_play_review")