# 3) Scouting brief + app data for the upcoming opponent -- fast

Builds the scouting brief and every table the app reads, from everything done before: **nothing is captured, tracked or trained** -- the last run's tracking, court and automatic-Title results are reused (and kept in the app's files). Commit and push the data folder when it finishes.
**Settings live in `parser_nb.ipynb`** -- this notebook runs that notebook's own cells (only the ones this job needs), so change a setting there and **save it** (Ctrl+S) before running this one. Run this notebook from the same folder as `parser_nb.ipynb`. The full notebook still works as before for a complete run.

In [2]:
import os
PARSER_LIB = os.path.join(os.getcwd(), "parser_lib")
exec(open(os.path.join(PARSER_LIB, "00_parser_modes.py"), encoding="utf-8").read())
run_parser("brief")

=== BRIEF: Scouting brief + app data for the upcoming opponent, from everything done before ===
(quiet: one line per section; everything else goes to ./inputs\_logs\brief_20261029_125855.log)
done  00b_season_switch  (0 s)
done  01_uw_whitewater_scouting_parser  (1 s)
done  02_parse_every_team_schedule_scrape_live_from  (58 s)
done  08_parse_each_opponent_fastscout_scoutbuilder  (9 s)
done  09_extract_each_opponent_roster  (0 s)
      3                          Box out!!!                 True
done  10_extract_uw_whitewater_offensive_and  (0 s)
done  11_cross_reference_each_scouted_opponent  (1 s)
      Pre-game keys to victory: 1. GUARD YOUR YARD (+ Early Gap Help) | 2. WALL UP, DON'T FOUL | 3. ATTACK THE PAINT!!!
      Pre-game keys to victory: 1. TAKE AWAY PERSONNEL TENDANCIES | 2. LIVE IN THE PAINT!!! | 3. DOMINATE THE GLASS
      Pre-game keys to victory: 1. DOMINATE THE GLASS | 2. ATTACK THE BASKET | 3. COMMUNICATION SCREENING ACTION!!!
      Pre-game keys to victory: 1. DRIVE DOWN 3PT ATTEMPTS!!! | 2. FINISH DEFENSIVE POSSESSIONS (LATE CLOCK) | 3. ATTACK THE PAINT
      Pre-game keys to victory: 1. TRANSITION DEFENSE!!! | 2. SQUEEZE & LIMIT #4 (Guard 1 on 1 + Gap Help) | 3. ATTACK THE PAINT OFFENSIVELY!!
done  12_win_loss_splits_by_keys_to_victory  (0 s)

                             category         stat_cols                                                        example_phrases                                                             why_chosen
0           Ball Security / Turnovers                TO  ball security, turnover, protect/take care of the ball, limit turn...  Directly named -- "ball security"/"turnovers" have a 1:1 stat colu...
1                          Rebounding     REB, ORB, DRB  own the paint, bully/dominate the glass, rebound, board, second ch...  "Glass"/"board"/"crash"/"own the paint" possession language in thi...
2                Three-Point Shooting        3PM-A, 3P%  three, 3 pt, 3pt, perimeter shooting, spacing, shooting ability, s...  Direct stat match for perimeter shot volume/efficiency. Expanded w...
3                         Free Throws        FTM-A, FT%                                     free throw, ft line, getting to ft  Direct stat match. Added "ft line" / "getting to ft" from Aurora (...
4                  Fouls / Discipline                PF                                           foul, wall up, drawing fouls  Direct stat match for foul-discipline emphasis. Added "wall up" (A...
5             Ball Movement / Assists               AST   assist, ball movement, share the ball, playmaking, playmaker, create  Direct stat match for offensive ball-sharing emphasis. Added "play...
6           Paint Protection / Blocks               BLK                               block, protect the rim, paint protection                 Direct stat match for interior shot-blocking emphasis.
7   Perimeter Defense / Ball Pressure               STL  steal, press capable, full court press, force turnovers, force to'...  Renamed from "Ball Pressure / Steals" once Aurora/Eureka/Elmhurst ...
8                      Scoring Inside  FG2M, FG2A, FG2%  dominate the paint, attack the paint, live in the paint, attack th...  Interior-scoring emphasis -- uses derived 2PT FG stats (FGM-FG3M, ...
9               Field Goal Efficiency        FGM-A, FG%                                                    limit their scoring  Overall shooting efficiency emphasis -- used when the scouting not...
10           (intentionally unmapped)                 -  communication screening action / communicate screens & actions (Ri...  No corresponding stat exists in a season box score for screen-navi...

done  13_keys_to_victory_category_reference  (0 s)

                 opponent jersey_number              name
8   St. Thomas (TX) Celts           #23        Jaden Ross
10  St. Thomas (TX) Celts           #11   Tamarcus Butler
11  St. Thomas (TX) Celts           #13     Legborsi Mato
18      Eureka Red Devils           #35    Max Richardson
20      Eureka Red Devils           #20        Nolan Kerr
21      Eureka Red Devils           #22        Tony Mabon
22      Eureka Red Devils           #15   Amare Brokemond
23      Eureka Red Devils            #3     Blake Logsdon
24      Eureka Red Devils            #0     Colin DeLaere
25      Eureka Red Devils            #1     Dylan Logsdon
33        Aurora Spartans            #0      Cullen Rauls
36        Aurora Spartans           #30         Alex Ross
37        Aurora Spartans           #21   Isaiah Thompson
46          Simpson Storm           #35  Nathaniel Winter
47          Simpson Storm           #15       Seth Gipple

done  14_build_per_player_scouting_profiles  (1 s)
done  15_break_out_keys_to_victory_categories_by  (0 s)
done  16_play_by_play_parsing_functions  (0 s)
done  17_classify_each_raw_play_by_play_text_string  (0 s)
done  18_turn_raw_4_column_play_by_play_table_into  (0 s)
done  19_extract_opponent_name_from_pbp_mhtml  (0 s)
done  20_identify_upcoming_opponent  (0 s)

                        value
team
Alma Scots                 29
Aurora Spartans            27
Carroll (WI) Pioneers      25
Coe Kohawks                23
Elmhurst Bluejays          25
Eureka Red Devils          31
Hope Flying Dutchmen       19
Lawrence Vikings           20
Loras Duhawks              20
Ripon Red Hawks            26
Simpson Storm              21
St. Thomas (TX) Celts      21
UW-Eau Claire Blugolds     20
UW-La Crosse Eagles        17
UW-Oshkosh Titans          22

done  21_roster_pages  (45 s)
done  22_locate_opponent_own_schedule_backup_file  (0 s)
done  23_build_opp_schedule  (0 s)
done  24_find_opponent_games_before_they_played_uw  (0 s)
done  25_live_scrape_any_missing_play_by_play_files  (0 s)

,opponent,game_date,event_order,period,time_remaining,time_remaining_seconds,team,event_type,raw_text,uww_score,opp_score,player,shot_type,shot_desc,foul_type,turnover_type,ft_num,ft_total
0,Washington-St. Louis Bears,2025-11-07,0,None,None,NaN,None,period_marker,Start 1st Half,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Washington-St. Louis Bears,2025-11-07,1,H1,19:59 (H1),1199.0,Washington-St. Louis Bears,jump_ball_won,Calvin Kapral Wins Jump Ball,0.0,0.0,Calvin Kapral,NaN,NaN,NaN,NaN,NaN,NaN
2,Washington-St. Louis Bears,2025-11-07,2,H1,19:59 (H1),1199.0,Carroll (WI) Pioneers,jump_ball_lost,Jacob Naber Loses Jump Ball,0.0,0.0,Jacob Naber,NaN,NaN,NaN,NaN,NaN,NaN
3,Washington-St. Louis Bears,2025-11-07,3,H1,19:46 (H1),1186.0,Washington-St. Louis Bears,missed_shot,Calvin Kapral Misses 2PT Layup,0.0,0.0,Calvin Kapral,2,Layup,NaN,NaN,NaN,NaN
4,Washington-St. Louis Bears,2025-11-07,4,H1,19:39 (H1),1179.0,Carroll (WI) Pioneers,rebound_defensive,Evan Bland Defensive Rebound,0.0,0.0,Evan Bland,NaN,NaN,NaN,NaN,NaN,NaN
5,Washington-St. Louis Bears,2025-11-07,5,H1,19:31 (H1),1171.0,Carroll (WI) Pioneers,made_shot,Lamar Smith Makes 3PT Jump Shot,3.0,0.0,Lamar Smith,3,Jump Shot,NaN,NaN,NaN,NaN
6,Washington-St. Louis Bears,2025-11-07,6,H1,19:31 (H1),1171.0,Carroll (WI) Pioneers,assist,Evan Bland Assists,3.0,0.0,Evan Bland,NaN,NaN,NaN,NaN,NaN,NaN
7,Washington-St. Louis Bears,2025-11-07,7,H1,19:23 (H1),1163.0,Carroll (WI) Pioneers,foul,Evan Bland Commits Personal Foul,3.0,0.0,Evan Bland,NaN,NaN,Personal Foul,NaN,NaN,NaN
8,Washington-St. Louis Bears,2025-11-07,8,H1,19:14 (H1),1154.0,Washington-St. Louis Bears,turnover,Connor May Turnover (Bad Pass),3.0,0.0,Connor May,NaN,NaN,NaN,Bad Pass,NaN,NaN
9,Washington-St. Louis Bears,2025-11-07,9,H1,19:14 (H1),1154.0,Carroll (WI) Pioneers,steal,Michael McNabb Steals,3.0,0.0,Michael McNabb,NaN,NaN,NaN,NaN,NaN,NaN
10,Washington-St. Louis Bears,2025-11-07,10,H1,18:59 (H1),1139.0,Carroll (WI) Pioneers,missed_shot,Peyton McKenna Misses 3PT Jump Shot,3.0,0.0,Peyton McKenna,3,Jump Shot,NaN,NaN,NaN,NaN
11,Washington-St. Louis Bears,2025-11-07,11,H1,18:56 (H1),1136.0,Washington-St. Louis Bears,rebound_defensive,Calvin Kapral Defensive Rebound,3.0,0.0,Calvin Kapral,NaN,NaN,NaN,NaN,NaN,NaN
12,Washington-St. Louis Bears,2025-11-07,12,H1,18:50 (H1),1130.0,Washington-St. Louis Bears,missed_shot,Ryan Cohen Misses 3PT Jump Shot,3.0,0.0,Ryan Cohen,3,Jump Shot,NaN,NaN,NaN,NaN
13,Washington-St. Louis Bears,2025-11-07,13,H1,18:46 (H1),1126.0,Carroll (WI) Pioneers,rebound_defensive,Lamar Smith Defensive Rebound,3.0,0.0,Lamar Smith,NaN,NaN,NaN,NaN,NaN,NaN
14,Washington-St. Louis Bears,2025-11-07,14,H1,18:34 (H1),1114.0,Carroll (WI) Pioneers,missed_shot,Jacob Naber Misses 2PT Layup,3.0,0.0,Jacob Naber,2,Layup,NaN,NaN,NaN,NaN
15,Washington-St. Louis Bears,2025-11-07,15,H1,18:31 (H1),1111.0,Washington-St. Louis Bears,rebound_defensive,Calvin Kapral Defensive Rebound,3.0,0.0,Calvin Kapral,NaN,NaN,NaN,NaN,NaN,NaN
16,Washington-St. Louis Bears,2025-11-07,16,H1,18:15 (H1),1095.0,Washington-St. Louis Bears,missed_shot,Will Grudzinski Misses 3PT Jump Shot,3.0,0.0,Will Grudzinski,3,Jump Shot,NaN,NaN,NaN,NaN
17,Washington-St. Louis Bears,2025-11-07,17,H1,18:11 (H1),1091.0,Washington-St. Louis Bears,rebound_offensive,Calvin Kapral Offensive Rebound,3.0,0.0,Calvin Kapral,NaN,NaN,NaN,NaN,NaN,NaN
18,Washington-St. Louis Bears,2025-11-07,18,H1,18:07 (H1),1087.0,Washington-St. Louis Bears,made_shot,Will Grudzinski Makes 2PT Layup,3.0,2.0,Will Grudzinski,2,Layup,NaN,NaN,NaN,NaN
19,Washington-St. Louis Bears,2025-11-07,19,H1,17:52 (H1),1072.0,Carroll (WI) Pioneers,turnover,Evan Bland Turnover (Lost Ball),3.0,2.0,Evan Bland,NaN,NaN,NaN,Lost Ball,NaN,NaN

done  26_parse_play_by_play_events_for_opponent  (15 s)
done  27_shared_video_tagging_helper_functions  (0 s)

     game_date                                vs                                                             video_file  pbp_rows  clips  matched why
0   2025-11-07        Washington-St. Louis Bears  11_7_25 Carroll (WI) Pioneers @ Washington-St. Louis Bears_video.html       543    247      227
1   2025-11-12                 Beloit Buccaneers          11_12_25 Beloit Buccaneers @ Carroll (WI) Pioneers_video.html       500    209      186
2   2025-11-14  Wisconsin-Superior Yellowjackets  11_14_25 Carroll (WI) Pioneers @ Wisconsin-Superior Yellowjackets_...       535    217      201
3   2025-11-15           UW-Platteville Pioneers    11_15_25 Carroll (WI) Pioneers @ UW-Platteville Pioneers_video.html       544    226      208
4   2025-11-22                 UW-Oshkosh Titans          11_22_25 UW-Oshkosh Titans @ Carroll (WI) Pioneers_video.html       872    245      230
5   2025-11-25                      MSOE Raiders               11_25_25 Carroll (WI) Pioneers @ MSOE Raiders_video.html       477    210      198
6   2025-12-03                North Park Vikings          12_3_25 North Park Vikings @ Carroll (WI) Pioneers_video.html       465    208      193
7   2025-12-06                Carthage Firebirds          12_6_25 Carroll (WI) Pioneers @ Carthage Firebirds_video.html       466    210      194
8   2025-12-13            UW-Whitewater Warhawks              12_13_25 Carroll (WI) Pioneers @ UW-Whitewater_video.html       495    229      214
9   2025-12-20                Marian (WI) Sabres         12_20_25 Marian (WI) Sabres @ Carroll (WI) Pioneers_video.html       450    204      188
10  2025-12-30                   Edgewood Eagles            12_30_25 Edgewood Eagles @ Carroll (WI) Pioneers_video.html       545    229      212
11  2026-01-03          Illinois Wesleyan Titans     1_3_26 Carroll (WI) Pioneers @ Illinois Wesleyan Titans_video.html       501    217      199
12  2026-01-07              Wheaton (IL) Thunder         1_7_26 Carroll (WI) Pioneers @ Wheaton (IL) Thunder_video.html       502    223      207
13  2026-01-10                 Millikin Big Blue           1_10_26 Millikin Big Blue @ Carroll (WI) Pioneers_video.html       509    226      214
14  2026-01-14                 Elmhurst Bluejays           1_14_26 Elmhurst Bluejays @ Carroll (WI) Pioneers_video.html       470    200      187

,opponent,game_date,event_order,period,time_remaining,time_remaining_seconds,team,event_type,raw_text,uww_score,opp_score,player,shot_type,shot_desc,foul_type,turnover_type,ft_num,ft_total,video_description,video_result,video_player,video_clip_number
3,Washington-St. Louis Bears,2025-11-07,3,H1,19:46 (H1),1186.0,Washington-St. Louis Bears,missed_shot,Calvin Kapral Misses 2PT Layup,0.0,0.0,Calvin Kapral,2,Layup,NaN,NaN,NaN,NaN,34 Calvin Kapral > Post-Up > Right Block > Left Shoulder > Dribble...,Miss 2 Pts,Calvin Kapral,1.0
5,Washington-St. Louis Bears,2025-11-07,5,H1,19:31 (H1),1171.0,Carroll (WI) Pioneers,made_shot,Lamar Smith Makes 3PT Jump Shot,3.0,0.0,Lamar Smith,3,Jump Shot,NaN,NaN,NaN,NaN,15 Evan Bland > P&R Ball Handler > High P&R > Dribble Off Pick > D...,Make 3 Pts,Lamar Smith,3.0
7,Washington-St. Louis Bears,2025-11-07,7,H1,19:23 (H1),1163.0,Carroll (WI) Pioneers,foul,Evan Bland Commits Personal Foul,3.0,0.0,Evan Bland,NaN,NaN,Personal Foul,NaN,NaN,NaN,3 Josh Kim > Non Possession > Non Shooting Foul,Non Shooting Foul,Josh Kim,4.0
8,Washington-St. Louis Bears,2025-11-07,8,H1,19:14 (H1),1154.0,Washington-St. Louis Bears,turnover,Connor May Turnover (Bad Pass),3.0,0.0,Connor May,NaN,NaN,NaN,Bad Pass,NaN,NaN,21 Connor May > Transition > First Middle > Turnover,Turnover,Connor May,5.0
10,Washington-St. Louis Bears,2025-11-07,10,H1,18:59 (H1),1139.0,Carroll (WI) Pioneers,missed_shot,Peyton McKenna Misses 3PT Jump Shot,3.0,0.0,Peyton McKenna,3,Jump Shot,NaN,NaN,NaN,NaN,12 Peyton McKenna > Spot-Up > No Dribble Jumper > Guarded > Long/3...,Miss 3 Pts,Peyton McKenna,6.0
12,Washington-St. Louis Bears,2025-11-07,12,H1,18:50 (H1),1130.0,Washington-St. Louis Bears,missed_shot,Ryan Cohen Misses 3PT Jump Shot,3.0,0.0,Ryan Cohen,3,Jump Shot,NaN,NaN,NaN,NaN,11 Ryan Cohen > Spot-Up > No Dribble Jumper > Open > Long/3pt > Mi...,Miss 3 Pts,Ryan Cohen,7.0
14,Washington-St. Louis Bears,2025-11-07,14,H1,18:34 (H1),1114.0,Carroll (WI) Pioneers,missed_shot,Jacob Naber Misses 2PT Layup,3.0,0.0,Jacob Naber,2,Layup,NaN,NaN,NaN,NaN,41 Jacob Naber > ISO > Right > Drives Right > To Basket > Miss 2 Pts,Miss 2 Pts,Jacob Naber,8.0
16,Washington-St. Louis Bears,2025-11-07,16,H1,18:15 (H1),1095.0,Washington-St. Louis Bears,missed_shot,Will Grudzinski Misses 3PT Jump Shot,3.0,0.0,Will Grudzinski,3,Jump Shot,NaN,NaN,NaN,NaN,32 Will Grudzinski > Spot-Up > No Dribble Jumper > Open > Long/3pt...,Miss 3 Pts,Will Grudzinski,9.0
18,Washington-St. Louis Bears,2025-11-07,18,H1,18:07 (H1),1087.0,Washington-St. Louis Bears,made_shot,Will Grudzinski Makes 2PT Layup,3.0,2.0,Will Grudzinski,2,Layup,NaN,NaN,NaN,NaN,32 Will Grudzinski > Spot-Up > Drives Right > To Basket > Make 2 Pts,Make 2 Pts,Will Grudzinski,10.0
19,Washington-St. Louis Bears,2025-11-07,19,H1,17:52 (H1),1072.0,Carroll (WI) Pioneers,turnover,Evan Bland Turnover (Lost Ball),3.0,2.0,Evan Bland,NaN,NaN,NaN,Lost Ball,NaN,NaN,15 Evan Bland > Spot-Up > Drives Left > Turnover,Turnover,Evan Bland,11.0
21,Washington-St. Louis Bears,2025-11-07,21,H1,17:40 (H1),1060.0,Washington-St. Louis Bears,missed_shot,Will Grudzinski Misses 3PT Jump Shot,3.0,2.0,Will Grudzinski,3,Jump Shot,NaN,NaN,NaN,NaN,32 Will Grudzinski > Spot-Up > No Dribble Jumper > Guarded > Long/...,Miss 3 Pts,Will Grudzinski,12.0
23,Washington-St. Louis Bears,2025-11-07,23,H1,17:36 (H1),1056.0,Washington-St. Louis Bears,made_shot,Calvin Kapral Makes 2PT Layup,3.0,4.0,Calvin Kapral,2,Layup,NaN,NaN,NaN,NaN,34 Calvin Kapral > Offensive Rebound > Short > Scoring Attempt > A...,Make 2 Pts,Calvin Kapral,13.0
24,Washington-St. Louis Bears,2025-11-07,24,H1,17:19 (H1),1039.0,Carroll (WI) Pioneers,made_shot,Jacob Naber Makes 2PT Driving Layup,5.0,4.0,Jacob Naber,2,Driving Layup,NaN,NaN,NaN,NaN,44 Lamar Smith > Post-Up > Left Block > Defense Commits > Ball Del...,Make 2 Pts,Jacob Naber,14.0
28,Washington-St. Louis Bears,2025-11-07,28,H1,17:00 (H1),1020.0,Washington-St. Louis Bears,missed_shot,Ryan Cohen Misses 3PT Jump Shot,5.0,4.0,Ryan Cohen,3,Jump Shot,NaN,NaN,NaN,NaN,11 Ryan Cohen > Spot-Up > No Dribble Jumper > Guarded > Long/3pt >...,Miss 3 Pts,Ryan Cohen,16.0
30,Washington-St. Louis Bears,2025-11-07,30,H1,16:40 (H1),1000.0,Washington-St. Louis Bears,foul,Connor May Commits Personal Foul,5.0,4.0,Connor May,NaN,NaN,Personal Foul,NaN,NaN,NaN,44 Lamar Smith > No Play Type > To Basket > Foul,Foul,Lamar Smith,17.0
31,Washington-St. Louis Bears,2025-11-07,31,H1,16:40 (H1),1000.0,Carroll (WI) Pioneers,free_throw_made,Lamar Smith Makes Free Throw (1 of 2),6.0,4.0,Lamar Smith,NaN,NaN,NaN,NaN,1,2,44 Lamar Smith > Non Possession > Free Throw,Free Throw,Lamar Smith,18.0
32,Washington-St. Louis Bears,2025-11-07,32,H1,16:40 (H1),1000.0,Carroll (WI) Pioneers,free_throw_made,Lamar Smith Makes Free Throw (2 of 2),7.0,4.0,Lamar Smith,NaN,NaN,NaN,NaN,2,2,44 Lamar Smith > Non Possession > Free Throw,Free Throw,Lamar Smith,19.0
39,Washington-St. Louis Bears,2025-11-07,39,H1,16:25 (H1),985.0,Washington-St. Louis Bears,missed_shot,Connor May Misses 2PT Jump Shot,7.0,4.0,Connor May,2,Jump Shot,NaN,NaN,NaN,NaN,21 Connor May > Spot-Up > Drives Left > Dribble Jumper > Medium/17...,Miss 2 Pts,Connor May,20.0
43,Washington-St. Louis Bears,2025-11-07,43,H1,16:15 (H1),975.0,Washington-St. Louis Bears,made_shot,George Gale Makes 2PT,7.0,6.0,George Gale,2,None,NaN,NaN,NaN,NaN,33 George Gale > Offensive Rebound > Short > Scoring Attempt > At ...,Make 2 Pts,George Gale,21.0
44,Washington-St. Louis Bears,2025-11-07,44,H1,16:08 (H1),968.0,Carroll (WI) Pioneers,turnover,Michael McNabb Turnover,7.0,6.0,Michael McNabb,NaN,NaN,NaN,None,NaN,NaN,4 Michael McNabb > P&R Ball Handler > Right P&R > Side > Go Away f...,Turnover,Michael McNabb,22.0

done  28_attach_video_tagging_clip_descriptions  (2 s)

   shot_type      shot_desc         play_type guarded  attempts  makes  fg_pct
0          3      Jump Shot           Spot-Up     Yes       191     73    38.2
1          2          Layup        Transition     N/A       126     84    66.7
2          3      Jump Shot           Spot-Up      No       104     41    39.4
3          2          Layup           Spot-Up     N/A        82     39    47.6
4          2          Layup               Cut     N/A        69     53    76.8
5          2  Driving Layup        Transition     N/A        66     53    80.3
6          2          Layup           Post-Up     N/A        56     24    42.9
7          2          Layup  P&R Ball Handler     N/A        55     27    49.1
8          2  Driving Layup           Spot-Up     N/A        51     32    62.7
9          3      Jump Shot        Transition     Yes        46     10    21.7
10         3      Jump Shot        Transition      No        45     15    33.3
11         3      Jump Shot  P&R Ball Handler     N/A        41      9    22.0
12         2          Layup          Hand Off     N/A        36     18    50.0
13         2  Driving Layup  P&R Ball Handler     N/A        29     17    58.6
14         3      Jump Shot          Hand Off     Yes        26     12    46.2

            play_type  attempts  makes  fg_pct
0             Spot-Up       490    204    41.6
1          Transition       347    181    52.2
2    P&R Ball Handler       162     59    36.4
3            Hand Off       132     50    37.9
4             Post-Up        93     44    47.3
5                 Cut        92     63    68.5
6                 ISO        47     24    51.1
7        P&R Roll Man        33     19    57.6
8          Off Screen        31     10    32.3
9   Offensive Rebound        29     20    69.0
10       No Play Type        18     11    61.1

  guarded  attempts  makes  fg_pct
0     N/A       992    515    51.9
1     Yes       291    101    34.7
2      No       191     69    36.1

     turnover_type         play_type  count
3         Bad Pass      No Play Type     50
9         Bad Pass        Transition     26
20       Lost Ball        Transition     20
5         Bad Pass  P&R Ball Handler     20
19       Lost Ball           Spot-Up     20
8         Bad Pass           Spot-Up     17
16       Lost Ball  P&R Ball Handler     16
11       Lost Ball          Hand Off     15
22  Offensive Foul      No Play Type      9
13       Lost Ball      No Play Type      9
18       Lost Ball           Post-Up      9
12       Lost Ball               ISO      6
1         Bad Pass          Hand Off      6
10       Lost Ball               Cut      5
27  Offensive Foul        Transition      5

         foul_type                                          video_description  count
155  Personal Foul       21 Caiden Lecce > Non Possession > Non Shooting Foul      4
53   Personal Foul                      10 Ryan Johnson > No Play Type > Foul      4
219  Personal Foul     30 Alejandro Diaz > Non Possession > Non Shooting Foul      4
15   Personal Foul        0 Isaac Verges > Non Possession > Non Shooting Foul      3
250  Personal Foul    4 Kyan VanderWoude > Non Possession > Non Shooting Foul      3
30   Personal Foul                 1 Dominic Trelenberg > No Play Type > Foul      3
292  Personal Foul  5 Jonathan Burroughs > Non Possession > Non Shooting Foul      3
279  Personal Foul        5 Andre Klaver > Non Possession > Non Shooting Foul      3
156  Personal Foul                     21 Carter Thomas > No Play Type > Foul      3
160  Personal Foul         21 Connor May > Non Possession > Non Shooting Foul      3
185  Personal Foul       23 Cam Atkinson > Non Possession > Non Shooting Foul      2
244  Personal Foul                        4 EJ Marshall > No Play Type > Foul      2
232  Personal Foul    33 Miles Hettinger > Non Possession > Non Shooting Foul      2
235  Personal Foul                      34 Carson Grier > No Play Type > Foul      2
238  Personal Foul       34 Ray Maurchie > Non Possession > Non Shooting Foul      2

           player  total_points_across_26_games
0  Michael McNabb                         558.0
1     Lamar Smith                         436.0
2  Peyton McKenna                         266.0
3     Jacob Naber                         247.0
4   Dennis Estepp                         166.0
5      Evan Bland                         141.0
6    Lucas Parker                         121.0
7    Jimmy Tarjan                          47.0
8      Cai Joseph                          16.0
9      Greg Smith                          12.0

done  29_scout_upcoming_opponent_own_tendencies  (0 s)

,opponent,key_number,title,source,supporting_stats,recommendation
0,Carroll (WI) Pioneers,1,Take away their most efficient high-volume actions,PBP-DERIVED,Offensive Rebound: 69.0% on 29 attempts; Cut: 68.5% on 92 attempts,Each is 5+ points above their 47.1% overall clip on 15+ attempts. ...
1,Carroll (WI) Pioneers,2,Funnel them into their worst high-volume looks,PBP-DERIVED,Off Screen: 32.3% on 31 attempts; P&R Ball Handler: 36.4% on 162 a...,Each is 5+ points below their 47.1% overall clip -- don't help off...
2,Carroll (WI) Pioneers,3,Pressure the actions they turn it over on,PBP-DERIVED,P&R Ball Handler: 48 TO in 210 uses (22.9% vs 13.8% across all act...,"Loosest actions per use, not the most common ones -- load ball pre..."

done  30_compare_pbp_derived_opponent_tendencies_to  (0 s)
      KEYS TO VICTORY: 1. TRANSITION DEFENSE!!! | 2. SQUEEZE & LIMIT #4 (Guard 1 on 1 + Gap Help) | 3. ATTACK THE PAINT OFFENSIVELY!!

            play_type  attempts  makes  fg_pct
0             Spot-Up       490    204    41.6
1          Transition       347    181    52.2
2    P&R Ball Handler       162     59    36.4
3            Hand Off       132     50    37.9
4             Post-Up        93     44    47.3
5                 Cut        92     63    68.5
6                 ISO        47     24    51.1
7        P&R Roll Man        33     19    57.6
8          Off Screen        31     10    32.3
9   Offensive Rebound        29     20    69.0
10       No Play Type        18     11    61.1

             shot_mechanic  attempts  makes  fg_pct
0          Catch-and-shoot        23      6    26.1
1      Drive to the basket         6      3    50.0
2  Pull-up off the dribble         2      1    50.0

                                                 contest  attempts  makes  fg_pct
0                                                Guarded        15      3    20.0
1  Not tagged (contest recorded only on catch-and-shoot)         8      4    50.0
2                                                   Open         8      3    37.5

   distance  attempts  makes  fg_pct
0  Long/3pt        25      7    28.0
1       N/A         6      3    50.0

           player  attempts  makes  fg_pct  pct_catch_and_shoot  pct_guarded
4  Peyton McKenna        16      3    18.8                 87.5         68.8
3  Michael McNabb         7      3    42.9                 42.9         28.6
2    Lucas Parker         5      2    40.0                100.0         40.0
1     Lamar Smith         2      1    50.0                  0.0          0.0
0   Dennis Estepp         1      1   100.0                100.0          0.0

done  31_diagnose_opponent_weakest_video_tagged  (0 s)

                   tag  count  importance_weight
0  three_point_shooter     91              1.903
1       slasher_driver     81              2.018
2          post_scorer     22              3.289
3            rebounder      7              4.346
4      catch_and_shoot      5              4.633
5            playmaker      4              4.816
6           high_usage      3              5.039
7    physical_finisher      3              5.039
8      pull_up_shooter      3              5.039
9               cutter      1              5.732

                     tag  count  importance_weight
0   deny_catch_and_shoot     53              2.436
1        anticipate_move     38              2.761
2           post_defense     16              3.592
3           help_defense     10              4.027
4       box_out_priority      8              4.228
5    physical_discipline      8              4.228
6       pressure_disrupt      7              4.346
7     transition_defense      7              4.346
8          keep_in_front      6              4.479
9              deny_cuts      2              5.326
10     screen_navigation      1              5.732

done  32_load_player_comparison_algorithms_and  (1 s)
done  33_surface_tag_based_best_match_per_target  (0 s)
done  34_surface_llm_best_match_per_player  (0 s)
done  35_blend_tag_based_and_llm_similarity_scores  (0 s)

,opponent,game_date,event_order,period,time_remaining,time_remaining_seconds,team,event_type,raw_text,uww_score,opp_score,player,shot_type,shot_desc,turnover_type,foul_type,ft_num,ft_total
0,St. Thomas (TX) Celts,2025-11-14,0,None,None,NaN,None,period_marker,Start 1st Half,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,St. Thomas (TX) Celts,2025-11-14,1,H1,19:58 (H1),1198.0,St. Thomas (TX) Celts,jump_ball_won,Charles Gitonga Wins Jump Ball,0.0,0.0,Charles Gitonga,NaN,NaN,NaN,NaN,NaN,NaN
2,St. Thomas (TX) Celts,2025-11-14,2,H1,19:58 (H1),1198.0,UW-Whitewater,jump_ball_lost,Brock Marino Loses Jump Ball,0.0,0.0,Brock Marino,NaN,NaN,NaN,NaN,NaN,NaN
3,St. Thomas (TX) Celts,2025-11-14,3,H1,19:34 (H1),1174.0,St. Thomas (TX) Celts,made_shot,Corey Thompson Makes 2PT Turnaround Jump Shot,0.0,2.0,Corey Thompson,2,Turnaround Jump Shot,NaN,NaN,NaN,NaN
4,St. Thomas (TX) Celts,2025-11-14,4,H1,19:22 (H1),1162.0,UW-Whitewater,turnover,Isaac Verges Turnover (Lost Ball),0.0,2.0,Isaac Verges,NaN,NaN,Lost Ball,NaN,NaN,NaN
5,St. Thomas (TX) Celts,2025-11-14,5,H1,19:22 (H1),1162.0,St. Thomas (TX) Celts,steal,Angel Johnson Steals,0.0,2.0,Angel Johnson,NaN,NaN,NaN,NaN,NaN,NaN
6,St. Thomas (TX) Celts,2025-11-14,6,H1,19:16 (H1),1156.0,St. Thomas (TX) Celts,missed_shot,Nathan Kongolo Misses 3PT Jump Shot,0.0,2.0,Nathan Kongolo,3,Jump Shot,NaN,NaN,NaN,NaN
7,St. Thomas (TX) Celts,2025-11-14,7,H1,19:14 (H1),1154.0,UW-Whitewater,rebound_defensive,Collin Madson Defensive Rebound,0.0,2.0,Collin Madson,NaN,NaN,NaN,NaN,NaN,NaN
8,St. Thomas (TX) Celts,2025-11-14,8,H1,19:09 (H1),1149.0,UW-Whitewater,turnover,Isaac Verges Turnover (Bad Pass),0.0,2.0,Isaac Verges,NaN,NaN,Bad Pass,NaN,NaN,NaN
9,St. Thomas (TX) Celts,2025-11-14,9,H1,19:09 (H1),1149.0,St. Thomas (TX) Celts,steal,Nathan Kongolo Steals,0.0,2.0,Nathan Kongolo,NaN,NaN,NaN,NaN,NaN,NaN
10,St. Thomas (TX) Celts,2025-11-14,10,H1,19:05 (H1),1145.0,St. Thomas (TX) Celts,made_shot,Angel Johnson Makes 2PT Layup,0.0,4.0,Angel Johnson,2,Layup,NaN,NaN,NaN,NaN
11,St. Thomas (TX) Celts,2025-11-14,11,H1,19:05 (H1),1145.0,St. Thomas (TX) Celts,assist,Nathan Kongolo Assists,0.0,4.0,Nathan Kongolo,NaN,NaN,NaN,NaN,NaN,NaN
12,St. Thomas (TX) Celts,2025-11-14,12,H1,18:34 (H1),1114.0,UW-Whitewater,missed_shot,Isaac Verges Misses 2PT Layup,0.0,4.0,Isaac Verges,2,Layup,NaN,NaN,NaN,NaN
13,St. Thomas (TX) Celts,2025-11-14,13,H1,18:31 (H1),1111.0,St. Thomas (TX) Celts,rebound_defensive,Nicholas Buffalo Defensive Rebound,0.0,4.0,Nicholas Buffalo,NaN,NaN,NaN,NaN,NaN,NaN
14,St. Thomas (TX) Celts,2025-11-14,14,H1,18:22 (H1),1102.0,St. Thomas (TX) Celts,missed_shot,Corey Thompson Misses 2PT Layup,0.0,4.0,Corey Thompson,2,Layup,NaN,NaN,NaN,NaN
15,St. Thomas (TX) Celts,2025-11-14,15,H1,18:19 (H1),1099.0,St. Thomas (TX) Celts,rebound_offensive,Corey Thompson Offensive Rebound,0.0,4.0,Corey Thompson,NaN,NaN,NaN,NaN,NaN,NaN
16,St. Thomas (TX) Celts,2025-11-14,16,H1,18:18 (H1),1098.0,St. Thomas (TX) Celts,turnover,Corey Thompson Turnover,0.0,4.0,Corey Thompson,NaN,NaN,None,NaN,NaN,NaN
17,St. Thomas (TX) Celts,2025-11-14,17,H1,18:04 (H1),1084.0,UW-Whitewater,made_shot,Collin Madson Makes 2PT Layup,2.0,4.0,Collin Madson,2,Layup,NaN,NaN,NaN,NaN
18,St. Thomas (TX) Celts,2025-11-14,18,H1,18:04 (H1),1084.0,UW-Whitewater,assist,Luke Bara Assists,2.0,4.0,Luke Bara,NaN,NaN,NaN,NaN,NaN,NaN
19,St. Thomas (TX) Celts,2025-11-14,19,H1,17:43 (H1),1063.0,St. Thomas (TX) Celts,made_shot,Angel Johnson Makes 2PT Pull Up Jump Shot,2.0,6.0,Angel Johnson,2,Pull Up Jump Shot,NaN,NaN,NaN,NaN

done  36_parse_play_by_play_mhtml_files_into  (17 s)

        series play_family       play_name aliases
0         ELOB        ELOB            "20"      20
1         Snap        Snap  20 Snap (flip)
2         Snap        Snap       30 (flip)
3         Snap        Snap         40 Snap
4         Over     Cheetah         Cheetah
5       Bursts       Cobra           Cobra
6       Bursts         Fox             Fox
7   Transition         Get             Get
8     Specials    Kentucky        Kentucky
9     Specials     Panther  Panther 2 "P2"      P2
10    Specials     Panther  Panther-4 "P4"      P4
11    Specials     Panther     Panther "P"       P
12        Over         Pin       Pin Flair
13     Entries      Pistol          Pistol
14  Transition       Pitch           Pitch

done  37_load_coach_tagged_recap_csvs  (0 s)
done  38_load_coach_tagged_recap_csvs_2  (0 s)

,opponent,period,time_remaining,team,event_type,raw_text,uww_lineup,opp_lineup
0,St. Thomas (TX) Celts,None,None,None,period_marker,Start 1st Half,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
1,St. Thomas (TX) Celts,H1,19:58 (H1),St. Thomas (TX) Celts,jump_ball_won,Charles Gitonga Wins Jump Ball,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
2,St. Thomas (TX) Celts,H1,19:58 (H1),UW-Whitewater,jump_ball_lost,Brock Marino Loses Jump Ball,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
3,St. Thomas (TX) Celts,H1,19:34 (H1),St. Thomas (TX) Celts,made_shot,Corey Thompson Makes 2PT Turnaround Jump Shot,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
4,St. Thomas (TX) Celts,H1,19:22 (H1),UW-Whitewater,turnover,Isaac Verges Turnover (Lost Ball),"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
5,St. Thomas (TX) Celts,H1,19:22 (H1),St. Thomas (TX) Celts,steal,Angel Johnson Steals,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
6,St. Thomas (TX) Celts,H1,19:16 (H1),St. Thomas (TX) Celts,missed_shot,Nathan Kongolo Misses 3PT Jump Shot,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
7,St. Thomas (TX) Celts,H1,19:14 (H1),UW-Whitewater,rebound_defensive,Collin Madson Defensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
8,St. Thomas (TX) Celts,H1,19:09 (H1),UW-Whitewater,turnover,Isaac Verges Turnover (Bad Pass),"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
9,St. Thomas (TX) Celts,H1,19:09 (H1),St. Thomas (TX) Celts,steal,Nathan Kongolo Steals,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
10,St. Thomas (TX) Celts,H1,19:05 (H1),St. Thomas (TX) Celts,made_shot,Angel Johnson Makes 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
11,St. Thomas (TX) Celts,H1,19:05 (H1),St. Thomas (TX) Celts,assist,Nathan Kongolo Assists,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
12,St. Thomas (TX) Celts,H1,18:34 (H1),UW-Whitewater,missed_shot,Isaac Verges Misses 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
13,St. Thomas (TX) Celts,H1,18:31 (H1),St. Thomas (TX) Celts,rebound_defensive,Nicholas Buffalo Defensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
14,St. Thomas (TX) Celts,H1,18:22 (H1),St. Thomas (TX) Celts,missed_shot,Corey Thompson Misses 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
15,St. Thomas (TX) Celts,H1,18:19 (H1),St. Thomas (TX) Celts,rebound_offensive,Corey Thompson Offensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
16,St. Thomas (TX) Celts,H1,18:18 (H1),St. Thomas (TX) Celts,turnover,Corey Thompson Turnover,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
17,St. Thomas (TX) Celts,H1,18:04 (H1),UW-Whitewater,made_shot,Collin Madson Makes 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
18,St. Thomas (TX) Celts,H1,18:04 (H1),UW-Whitewater,assist,Luke Bara Assists,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
19,St. Thomas (TX) Celts,H1,17:43 (H1),St. Thomas (TX) Celts,made_shot,Angel Johnson Makes 2PT Pull Up Jump Shot,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
20,St. Thomas (TX) Celts,H1,17:19 (H1),UW-Whitewater,made_shot,JR Lukenbill Makes 3PT Jump Shot,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
21,St. Thomas (TX) Celts,H1,17:19 (H1),UW-Whitewater,assist,Collin Madson Assists,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
22,St. Thomas (TX) Celts,H1,17:05 (H1),UW-Whitewater,foul,Luke Bara Commits Personal Foul,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
23,St. Thomas (TX) Celts,H1,16:55 (H1),St. Thomas (TX) Celts,made_shot,Angel Johnson Makes 2PT Driving Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
24,St. Thomas (TX) Celts,H1,16:37 (H1),UW-Whitewater,missed_shot,Luke Bara Misses 3PT Jump Shot,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
25,St. Thomas (TX) Celts,H1,16:34 (H1),St. Thomas (TX) Celts,rebound_defensive,Charles Gitonga Defensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
26,St. Thomas (TX) Celts,H1,16:17 (H1),St. Thomas (TX) Celts,missed_shot,Nicholas Buffalo Misses 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
27,St. Thomas (TX) Celts,H1,16:15 (H1),St. Thomas (TX) Celts,rebound_offensive,Nicholas Buffalo Offensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
28,St. Thomas (TX) Celts,H1,16:13 (H1),St. Thomas (TX) Celts,missed_shot,Nicholas Buffalo Misses 2PT Layup,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."
29,St. Thomas (TX) Celts,H1,16:11 (H1),UW-Whitewater,rebound_defensive,Brock Marino Defensive Rebound,"Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara","Angel Johnson, Charles Gitonga, Corey Thompson, Nathan Kongolo, Ni..."

done  39_reconstruct_on_court_5_man_lineup_for_both  (1 s)
done  40_classify_each_on_court_opponent_lineup  (1 s)
done  41_attach_video_tagging_clip_descriptions_2  (3 s)
done  41b_offensive_roles  (10 s)

      opponent   game_date           team                  player  started  PTS  FGM  FGA  FG3M  FG3A  FTM  FTA  OREB  DREB  REB  AST  STL  BLK  TO  PF    FG%    3P%    FT%
0   Alma Scots  2025-12-20     Alma Scots         Donovan Collins     True   17    5   10     5     9    2    3     0     0    0    1    0    0   0   0   50.0   55.6   66.7
16  Alma Scots  2025-12-20  UW-Whitewater         Joey Berezowitz    False   16    6    8     4     5    0    0     2     0    2    0    2    0   0   0   75.0   80.0    NaN
4   Alma Scots  2025-12-20     Alma Scots         Korbin Heitzman     True   14    4   10     0     1    6    8     5    11   16    1    0    1   6   4   40.0    0.0   75.0
11  Alma Scots  2025-12-20  UW-Whitewater           Collin Madson     True   13    4    7     0     0    5    6     1     5    6    3    2    0   0   2   57.1    NaN   83.3
15  Alma Scots  2025-12-20  UW-Whitewater              Jake Quast    False   11    5    7     1     2    0    1     0     3    3    0    3    0   2   3   71.4   50.0    0.0
12  Alma Scots  2025-12-20  UW-Whitewater         Darius Chestnut    False   10    4    4     2     2    0    0     0     0    0    0    0    0   0   2  100.0  100.0    NaN
2   Alma Scots  2025-12-20     Alma Scots            Josh Elliott     True    9    3    7     2     6    1    1     0     3    3    0    1    0   3   1   42.9   33.3  100.0
13  Alma Scots  2025-12-20  UW-Whitewater            Isaac Verges     True    9    4    7     1     2    0    0     0     2    2    1    0    0   1   3   57.1   50.0    NaN
23  Alma Scots  2025-12-20  UW-Whitewater  Tyshawn Teague-Johnson    False    9    4    7     1     1    0    1     1     2    3    2    0    0   2   1   57.1  100.0    0.0
1   Alma Scots  2025-12-20     Alma Scots            Elijah Sykes    False    7    3    9     1     4    0    0     0     0    0    2    1    0   1   0   33.3   25.0    NaN
10  Alma Scots  2025-12-20  UW-Whitewater            Brock Marino     True    7    1    6     0     0    5    6     1     1    2    1    4    0   1   3   16.7    NaN   83.3
6   Alma Scots  2025-12-20     Alma Scots       Luciano Guerrazzi    False    5    2    2     1     1    0    0     1     1    2    1    1    1   5   1  100.0  100.0    NaN
21  Alma Scots  2025-12-20  UW-Whitewater           Richie Warren     True    5    1    6     0     1    3    3     2     2    4    2    3    1   1   2   16.7    0.0  100.0
3   Alma Scots  2025-12-20     Alma Scots            Joss Bradley    False    3    0    2     0     0    3    4     1     1    2    4    0    1   0   2    0.0    NaN   75.0
9   Alma Scots  2025-12-20  UW-Whitewater         Agape Keyes Jr.    False    3    1    1     1     1    0    0     0     0    0    0    1    0   0   1  100.0  100.0    NaN

done  42_reconstruct_and_validate_per_game_box  (0 s)
done  43_diagnostic  (0 s)

,opponent,game_date,team,lineup,MIN,+/-,PTS,FGM,FGA,FG3M,FG3A,FTM,FTA,OREB,DREB,REB,AST,STL,BLK,TO,PF,FG%,3P%,FT%
6,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Korbin Heitzman, Logan St. Martin, ...",12.62,-14.0,11,2,13,2,6,5,6,4,7,11,1,1,0,9,4,15.4,33.3,83.3
8,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Korbin Heitzman, Preston Malpass, R...",3.42,-0.0,9,4,6,1,2,0,1,1,1,2,2,0,0,1,1,66.7,50.0,0.0
9,Alma Scots,2025-12-20,Alma Scots,"Elijah Sykes, Josh Elliott, Joss Bradley, Korbin Heitzman, Logan S...",3.74,1.0,9,3,4,1,2,2,2,0,3,3,1,0,1,3,2,75.0,50.0,100.0
2,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Elijah Sykes, Luciano Guerrazzi, Preston Malpass,...",3.44,-0.0,8,3,6,2,4,0,0,1,1,2,3,3,0,2,1,50.0,50.0,NaN
4,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Joss Bradley, Korbin Heitzman, Luci...",3.55,-6.0,6,1,4,1,4,3,4,2,3,5,1,1,1,2,1,25.0,25.0,75.0
3,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Joss Bradley, Korbin Heitzman, Loga...",3.34,-4.0,5,2,3,0,0,1,2,0,2,2,1,0,2,1,3,66.7,NaN,50.0
0,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Elijah Sykes, Joss Bradley, Korbin Heitzman, Luci...",1.87,2.0,4,2,4,0,0,0,0,0,1,1,1,0,0,0,0,50.0,NaN,NaN
1,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Elijah Sykes, Joss Bradley, Luciano Guerrazzi, Pr...",1.95,3.0,3,1,2,1,1,0,0,0,3,3,1,0,0,1,1,50.0,100.0,NaN
5,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Joss Bradley, Luciano Guerrazzi, Pr...",1.45,-1.0,3,1,2,1,2,0,0,1,1,2,1,0,0,1,1,50.0,50.0,NaN
10,Alma Scots,2025-12-20,Alma Scots,"Elijah Sykes, Josh Elliott, Joss Bradley, Korbin Heitzman, Luciano...",1.82,-4.0,3,1,2,0,1,1,2,2,0,2,0,0,0,1,0,50.0,0.0,50.0
7,Alma Scots,2025-12-20,Alma Scots,"Donovan Collins, Josh Elliott, Korbin Heitzman, Luciano Guerrazzi,...",0.03,-0.0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,NaN,NaN,NaN
11,Alma Scots,2025-12-20,Alma Scots,"Elijah Sykes, Josh Elliott, Korbin Heitzman, Preston Malpass, Rain...",1.30,-3.0,0,0,3,0,2,0,0,1,1,2,0,0,0,0,0,0.0,0.0,NaN
12,Alma Scots,2025-12-20,Alma Scots,"Elijah Sykes, Joss Bradley, Korbin Heitzman, Luciano Guerrazzi, Pr...",1.20,-3.0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,NaN,NaN,NaN
17,Alma Scots,2025-12-20,UW-Whitewater,"Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren",12.04,8.0,21,7,17,1,3,6,7,4,5,9,3,6,0,2,5,41.2,33.3,85.7
22,Alma Scots,2025-12-20,UW-Whitewater,"Collin Madson, Joey Berezowitz, Luke Bara, Richie Warren, Tyshawn ...",3.62,3.0,11,4,7,3,4,0,0,0,2,2,2,1,0,0,1,57.1,75.0,NaN

done  44_reconstruct_single_game_box_score_by_5_man  (1 s)
done  45_aggregate_upcoming_opponent_5_man_lineup  (1 s)
done  46_frame_capture  (13 s)

     game_date period  Clock           player                result
0   2025-12-20     H1    NaN  Donovan Collins          No Violation
3   2025-12-20     H1  19:11     Brock Marino            Miss 2 Pts
5   2025-12-20     H1    NaN    Collin Madson          No Violation
8   2025-12-20     H1    NaN    Richie Warren            Free Throw
21  2025-12-20     H1    NaN  Korbin Heitzman  Shot Clock Violation
29  2025-12-20     H1    NaN  Korbin Heitzman            Free Throw

     game_date period Clock             player        result
7   2026-02-24   None  None  Sebastian Blachut  No Violation
44  2026-02-24     H1  None      Dennis Estepp  No Violation
48  2026-02-24     H1  None        Lamar Smith    Make 2 Pts
75  2026-02-24     H1  None      Dennis Estepp    Make 3 Pts
78  2026-02-24     H1  None        Aidyn Boone          Foul
81  2026-02-24     H1  None        Jacob Naber          Foul

     game_date game_code period  clip_number  video_start_s   clock                                                            description
0   2025-12-20    WWW@AC     H1            4          356.5  1151.0  21 Brock Marino > Post-Up > Left Block > Right Shoulder > Dribble ...
1   2025-12-20    WWW@AC     H1           12          465.5  1084.0                            24 Richie Warren > Cut > Flash > Miss 2 Pts
2   2025-12-20    WWW@AC     H2          145         4755.5   609.0        12 Jake Quast > Spot-Up > Drives Right > To Basket > Miss 2 Pts
3   2025-12-20    WWW@AC     H2          179         5566.3   238.0  2 Kelton Mcewen > Transition > Ballhandler > Dribble Jumper > Long...
4   2025-12-30   WWW@COE     H2          466         5734.7   810.0                4 Deuce Walters > No Play Type > To Basket > Miss 2 Pts
5   2026-01-03   WOS@WWW     H2           85         2060.2  1191.0                   2 Joey LaChapell > Spot-Up > Drives Right > Turnover
6   2026-01-03   WOS@WWW     H2           87         2088.5  1177.0                      32 Luke Bara > Non Possession > Non Shooting Foul
7   2026-01-03   WOS@WWW     H2           88         2108.6  1175.0                            21 Brock Marino > Cut > Basket > Make 2 Pts
8   2026-01-03   WOS@WWW     H2           89         2118.2  1163.0  4 Michael Metcalf-Grassman > Spot-Up > Drives Right > To Basket > ...
9   2026-01-03   WOS@WWW     H2           90         2130.6  1139.0                              21 Brock Marino > No Play Type > Turnover
10  2026-01-03   WOS@WWW     H2           93         2153.9  1130.0  21 Carter Thomas > Spot-Up > No Dribble Jumper > Guarded > Long/3p...
11  2026-01-03   WOS@WWW     H2           91         2156.0  1134.0  4 Michael Metcalf-Grassman > Transition > Ballhandler > To Basket ...
12  2026-01-03   WOS@WWW     H2           95         2196.9  1104.0                           24 Richie Warren > Cut > Basket > Miss 2 Pts
13  2026-01-03   WOS@WWW     H2           96         2220.4  1087.0  23 Oskar Kangas > P&R Ball Handler > Right P&R > Baseline > Dribbl...
14  2026-01-03   WOS@WWW     H2           97         2236.5  1067.0  15 Collin Madson > ISO > Right > Drives Right > To Basket > Miss 2...

done  47_play_calls  (18 s)
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
done  50_player_tracking  (1 s)
done  51_court_mapping  (0 s)
done  53_tag_model  (1 s)
done  54_tracking_insights  (11 s)
done  55_court_insights  (0 s)
done  55c_play_review  (0 s)
done  55d_defensive_roles  (3 s)
done  55e_film_quality  (0 s)

          date                opponent  UWW run  opp run  UWW lead  opp lead
0   2025-12-20              Alma Scots        8        8        29         3
1   2025-11-19         Aurora Spartans       13       10        23         4
2   2025-12-13   Carroll (WI) Pioneers        7        8        17         6
3   2025-12-30             Coe Kohawks        7       13         6        26
4   2025-12-02       Elmhurst Bluejays       10        7        22         3
5   2025-11-15       Eureka Red Devils       12        5        46         1
6   2025-12-19    Hope Flying Dutchmen        8       14         6        12
7   2025-12-10        Lawrence Vikings        9        7        32         2
8   2026-03-06           Loras Duhawks       15        9        24         2
9   2025-11-07         Ripon Red Hawks        7       10        20        10
10  2025-11-25           Simpson Storm       15       11        33         0
11  2025-11-14   St. Thomas (TX) Celts        6        6        13        12
12  2026-01-24  UW-Eau Claire Blugolds        7        7         7        10
13  2026-02-14  UW-Eau Claire Blugolds        8        6        11         5
14  2026-01-14     UW-La Crosse Eagles        9        8        19         0

done  56_compute_biggest_scoring_runs_and_largest  (1 s)
done  57_surface_clutch_time_events_with_lineup  (0 s)
done  58_cross_reference_actual_pbp_turnovers  (0 s)
done  59_cross_reference_actual_pbp_rebounding  (0 s)

                      opponent                                                             uww_lineup  total_minutes  stints  net_margin  margin_per_min
461       UW-Stout Blue Devils    Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren           23.1      18        20.0             0.9
304          UW-Oshkosh Titans    Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren           12.1      16        17.0             1.4
440  UW-Stevens Point Pointers  Collin Madson, Isaiah Robinson, Jake Quast, Kelton McEwen, Tyshawn...            5.6       4        14.0             2.5
144           Lawrence Vikings  Collin Madson, JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton M...            4.6       6        12.0             2.6
377    UW-Platteville Pioneers  Collin Madson, Joey Berezowitz, Kelton McEwen, Richie Warren, Tysh...            2.2       4        11.0             4.9

                   opponent                                                             uww_lineup  total_minutes  stints  net_margin  margin_per_min
225  UW-Eau Claire Blugolds    Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren           25.2       8        -9.0            -0.4
298       UW-Oshkosh Titans  Brock Marino, Collin Madson, Darius Chestnut, Luke Bara, Richie Wa...            2.6       2        -9.0            -3.4
327       UW-Oshkosh Titans   Collin Madson, Isaiah Robinson, Jake Quast, Luke Bara, Rashad Rogers            2.1       3        -8.0            -3.8
39    Carroll (WI) Pioneers  Brock Marino, Collin Madson, Jake Quast, Joey Berezowitz, Kelton M...            0.7       1        -7.0            -9.6
157           Loras Duhawks  Collin Madson, Jake Quast, Joey Berezowitz, Kelton McEwen, Richie ...            6.2       7        -7.0            -1.1

                       opponent                                                             opp_lineup  total_minutes  stints  net_margin_for_uww  margin_per_min_for_uww
132        Hope Flying Dutchmen  Brendan Cargill, Justice Mims, Marcus Wourman, Orion Yant, Parker ...           10.7       8               -15.0                    -1.4
395      UW-River Falls Falcons  Gavin Ralph, Jack Leifker, Jeremy Wanguhu, Micah Thompson, Owen Ha...            9.5       6               -14.0                    -1.5
459  Washington-St. Louis Bears     Anthony Przybilla, Calvin Kapral, Connor May, Josh Kim, Ryan Cohen            4.9       4               -11.0                    -2.2
325           UW-Oshkosh Titans  Brandon Beck, Carter Thomas, Joey LaChapell, Michael Metcalf-Grass...           19.4      30               -10.0                    -0.5
303           UW-Oshkosh Titans  AJ Ohrmundt, Carter Thomas, Joey LaChapell, Nate Nazos, Vitorio Dante            2.7       3               -10.0                    -3.7

done  60_compute_scoring_margin_and_minutes_played  (0 s)
done  61_add_minutes_played_onto_reconstructed_box  (0 s)
done  62_identify_lineups_on_court_during_each_team  (0 s)

                                                                uww_lineup  games                                                              opponents  stints  total_minutes  net_margin  margin_per_min
74     Brock Marino, Collin Madson, Isaac Verges, Luke Bara, Richie Warren     23  [Alma Scots, Carroll (WI) Pioneers, Elmhurst Bluejays, Hope Flying...     140         224.66        25.0            0.11
61      Brock Marino, Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara      7  [Aurora Spartans, Eureka Red Devils, Ripon Red Hawks, St. Thomas (...      29          39.31         4.0            0.10
100  Brock Marino, Collin Madson, Joey Berezowitz, Luke Bara, Richie Wa...     11  [Alma Scots, Aurora Spartans, Coe Kohawks, Elmhurst Bluejays, Hope...      22          26.50         9.0            0.34
187      Collin Madson, Isaac Verges, Jake Quast, Luke Bara, Richie Warren      9  [Hope Flying Dutchmen, Loras Duhawks, St. Thomas (TX) Celts, UW-La...      32          24.95        -1.0           -0.04
199   Collin Madson, Isaac Verges, Luke Bara, Rashad Rogers, Richie Warren      6  [Elmhurst Bluejays, Hope Flying Dutchmen, Simpson Storm, UW-Platte...      17          24.44         1.0            0.04
169       Collin Madson, Isaac Verges, JR Lukenbill, Jake Quast, Luke Bara      6  [Aurora Spartans, Elmhurst Bluejays, UW-Eau Claire Blugolds, UW-La...      27          17.50        18.0            1.03
89     Brock Marino, Collin Madson, JR Lukenbill, Luke Bara, Richie Warren      2                         [UW-Oshkosh Titans, UW-Stevens Point Pointers]      19          17.41         4.0            0.23
176    Collin Madson, Isaac Verges, JR Lukenbill, Luke Bara, Richie Warren      8  [Elmhurst Bluejays, St. Thomas (TX) Celts, UW-Eau Claire Blugolds,...      23          17.03        -2.0           -0.12
229  Collin Madson, Jake Quast, Joey Berezowitz, Kelton McEwen, Richie ...      6  [Elmhurst Bluejays, Lawrence Vikings, Loras Duhawks, St. Thomas (T...      15          16.42         5.0            0.30
64        Brock Marino, Collin Madson, Isaac Verges, Jake Quast, Luke Bara      8  [Aurora Spartans, Elmhurst Bluejays, Eureka Red Devils, St. Thomas...      19          15.15       -17.0           -1.12

                                                                uww_lineup  games                                                          opponents  stints  total_minutes  net_margin  margin_per_min
71     Brock Marino, Collin Madson, Isaac Verges, Kelton McEwen, Luke Bara      4  [Hope Flying Dutchmen, UW-La Crosse Eagles, UW-Stout Blue Devils]       7           2.02         9.0            4.46
237  Collin Madson, Joey Berezowitz, Kelton McEwen, Richie Warren, Tysh...      2                             [Coe Kohawks, UW-Platteville Pioneers]       5           2.85        11.0            3.86
154  Collin Madson, Darius Chestnut, Jake Quast, Joey Berezowitz, Richi...      2                         [Elmhurst Bluejays, St. Thomas (TX) Celts]       3           2.04         7.0            3.43
79   Brock Marino, Collin Madson, Isaiah Robinson, Jake Quast, Kelton M...      2                        [UW-Eau Claire Blugolds, UW-Oshkosh Titans]       5           2.13         7.0            3.29
103  Brock Marino, Collin Madson, Kelton McEwen, Mauryon Turner, Richie...      1                                                [Eureka Red Devils]       3           3.04         9.0            2.96
151  Collin Madson, Darius Chestnut, JR Lukenbill, Luke Bara, Richie Wa...      2                         [Simpson Storm, UW-Stevens Point Pointers]       7           3.72        11.0            2.96
209  Collin Madson, Isaiah Robinson, Jake Quast, Kelton McEwen, Tyshawn...      1                                        [UW-Stevens Point Pointers]       4           5.59        14.0            2.50
216  Collin Madson, JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton M...      3               [Elmhurst Bluejays, Lawrence Vikings, Simpson Storm]      13           9.61        24.0            2.50
84   Brock Marino, Collin Madson, Isaiah Robinson, Luke Bara, Tyshawn T...      1                                           [UW-River Falls Falcons]       2           2.85         7.0            2.46
248  Darius Chestnut, JR Lukenbill, Jake Quast, Joey Berezowitz, Kelton...      1                                                    [Simpson Storm]       4           2.46         5.0            2.03

                                                                uww_lineup  games                                                              opponents  stints  total_minutes  net_margin  margin_per_min
210   Collin Madson, Isaiah Robinson, Jake Quast, Luke Bara, Rashad Rogers      1                                                    [UW-Oshkosh Titans]       3           2.13        -8.0           -3.76
160  Collin Madson, Darius Chestnut, Luke Bara, Rashad Rogers, Richie W...      1                                                 [Hope Flying Dutchmen]       2           2.28        -7.0           -3.07
34   Austin Ambrose, Collin Madson, Jake Quast, Joey Berezowitz, Luke Bara      1                                                  [UW-La Crosse Eagles]       1           2.07        -6.0           -2.90
27   Austin Ambrose, Collin Madson, Isaac Verges, Joey Berezowitz, Rich...      1                                              [UW-Platteville Pioneers]       2           2.87        -7.0           -2.44
135  Brock Marino, JR Lukenbill, Joey Berezowitz, Kelton McEwen, Richie...      1                                               [UW-River Falls Falcons]       1           2.18        -5.0           -2.29
22   Austin Ambrose, Collin Madson, Darius Chestnut, Joey Berezowitz, T...      1                                               [UW-River Falls Falcons]       3           2.51        -5.0           -1.99
83   Brock Marino, Collin Madson, Isaiah Robinson, Luke Bara, Richie Wa...      2                          [UW-Eau Claire Blugolds, UW-La Crosse Eagles]       2           2.20        -4.0           -1.82
55   Brock Marino, Collin Madson, Darius Chestnut, Luke Bara, Richie Wa...      4  [Alma Scots, Aurora Spartans, UW-Oshkosh Titans, UW-Stevens Point ...       9           8.22       -14.0           -1.70
223  Collin Madson, JR Lukenbill, Joey Berezowitz, Luke Bara, Tyshawn T...      2                               [Loras Duhawks, UW-Platteville Pioneers]       3           3.35        -5.0           -1.49
218  Collin Madson, JR Lukenbill, Jake Quast, Joey Berezowitz, Richie W...      2                             [St. Thomas (TX) Celts, UW-Oshkosh Titans]       3           4.19        -6.0           -1.43

done  63_season_wide_5_man_lineup_analysis_across  (0 s)

             player          play_type  attempts  makes  fg_pct
4   Agape Keyes Jr.            Spot-Up         4      1    25.0
5   Agape Keyes Jr.         Transition         4      1    25.0
0   Agape Keyes Jr.       No Play Type         1      1   100.0
1   Agape Keyes Jr.         Off Screen         1      0     0.0
2   Agape Keyes Jr.  Offensive Rebound         1      0     0.0
3   Agape Keyes Jr.   P&R Ball Handler         1      0     0.0
11   Austin Ambrose            Spot-Up         7      2    28.6
10   Austin Ambrose            Post-Up         5      3    60.0
9    Austin Ambrose       P&R Roll Man         3      1    33.3
6    Austin Ambrose                Cut         2      2   100.0
7    Austin Ambrose       No Play Type         1      0     0.0
8    Austin Ambrose  Offensive Rebound         1      1   100.0
12   Austin Ambrose         Transition         1      0     0.0
18     Brock Marino            Post-Up        62     34    54.8
17     Brock Marino       P&R Roll Man        33     15    45.5

done  64_uww_performance_vs_opponent_lineup_profile  (0 s)

             shot_mechanic  attempts  makes  fg_pct
0          Catch-and-shoot       283    108    38.2
1      Drive to the basket       116     55    47.4
2  Pull-up off the dribble        61     18    29.5

                                                 contest  attempts  makes  fg_pct
1  Not tagged (contest recorded only on catch-and-shoot)       177     73    41.2
0                                                Guarded       166     61    36.7
2                                                   Open       117     47    40.2

            distance  attempts  makes  fg_pct
0           Long/3pt       297    113    38.0
2                N/A       116     55    47.4
3     Short to < 17'        28      6    21.4
1  Medium/17' to <3p        19      7    36.8

   contest           distance  attempts  makes  fg_pct
0  Guarded           Long/3pt       163     59    36.2
2     Open           Long/3pt       111     45    40.5
3     Open  Medium/17' to <3p         6      2    33.3
1  Guarded  Medium/17' to <3p         3      2    66.7

done  65_diagnose_spot_up_struggles  (0 s)

          play_type  attempts  makes  fg_pct
6           Spot-Up       283    108    38.2
3        Off Screen        56     20    35.7
7        Transition        51     20    39.2
5      P&R Roll Man        22      7    31.8
0          Hand Off        11      3    27.3
4  P&R Ball Handler         9      2    22.2
1               ISO         3      1    33.3
2      No Play Type         3      1    33.3

   contest  attempts  makes  fg_pct
0  Guarded       247     85    34.4
1     Open       191     77    40.3

            play_type                    shot_mechanic  attempts  makes  fg_pct
19         Transition              Drive to the basket       144     91    63.2
0                 Cut                Cut to the basket       129     81    62.8
17            Spot-Up              Drive to the basket       116     55    47.4
11   P&R Ball Handler          Pull-up off the dribble       100     37    37.0
10   P&R Ball Handler              Drive to the basket        92     49    53.3
16            Post-Up                          Post-up        84     37    44.0
3                 ISO              Drive to the basket        65     33    50.8
18            Spot-Up          Pull-up off the dribble        61     18    29.5
4                 ISO          Pull-up off the dribble        59     23    39.0
9   Offensive Rebound  Putback off the offensive glass        58     52    89.7
15            Post-Up              Drive to the basket        55     34    61.8
1            Hand Off              Drive to the basket        24     11    45.8
8          Off Screen          Pull-up off the dribble        23      9    39.1
20         Transition          Pull-up off the dribble        20      7    35.0
14       P&R Roll Man   Unclassified (no mechanic tag)        19     11    57.9

done  66_check_contest_mechanic_patterns_across_all  (0 s)
done  67_contest_level  (0 s)

                 opponent   game_date  contest  attempts  makes  fg_pct
0              Alma Scots  2025-12-20  Guarded         3      1    33.3
1              Alma Scots  2025-12-20     Open        13      8    61.5
2         Aurora Spartans  2025-11-19  Guarded         4      1    25.0
3         Aurora Spartans  2025-11-19     Open        12      5    41.7
4   Carroll (WI) Pioneers  2025-12-13  Guarded        13      3    23.1
5   Carroll (WI) Pioneers  2025-12-13     Open         5      0     0.0
6             Coe Kohawks  2025-12-30  Guarded        12      3    25.0
7             Coe Kohawks  2025-12-30     Open         2      0     0.0
8       Elmhurst Bluejays  2025-12-02  Guarded         3      2    66.7
9       Elmhurst Bluejays  2025-12-02     Open         8      1    12.5
10      Eureka Red Devils  2025-11-15  Guarded         8      4    50.0
11      Eureka Red Devils  2025-11-15     Open        16      9    56.2
12   Hope Flying Dutchmen  2025-12-19  Guarded         7      2    28.6
13   Hope Flying Dutchmen  2025-12-19     Open         5      3    60.0
14       Lawrence Vikings  2025-12-10  Guarded        21      8    38.1

done  68_investigate_why_guarded_catch_and_shoot  (0 s)

,player,player_key,role,sentiment,category,flag,evidence,recommendation,confidence
9,Brock Marino,brock marino,Starter,Positive,Play-type efficiency,Efficient secondary action: Offensive Rebound,9-for-10 (90%) on Offensive Rebound this season.,"A reliable look worth calling more often, even if not his primary ...",Medium (n=10 Offensive Rebound attempts)
8,Brock Marino,brock marino,Starter,Negative,Free-throw shooting,Below-average free-throw shooter with meaningful attempt volume,53.2% FT this season -- 59-for-111 over 28 games (4.0 attempts a g...,Target free-throw shooting in individual workouts -- meaningful at...,"High (n=111 FT attempts, season-long sample)"
7,Brock Marino,brock marino,Starter,Negative,Shooting efficiency,Missing predominantly OPEN catch-and-shoot looks,5-for-16 (31%) on open catch-and-shoot attempts this season -- bel...,"Since these are UNCONTESTED misses, treat as a shooting-mechanics/...",Medium (n=16 open catch-and-shoot attempts)
10,Collin Madson,collin madson,Starter,Positive,Play-type efficiency,Efficient secondary action: Offensive Rebound,10-for-11 (91%) on Offensive Rebound this season.,"A reliable look worth calling more often, even if not his primary ...",Medium (n=11 Offensive Rebound attempts)
13,Isaac Verges,isaac verges,Starter,Positive,Play-type efficiency,Efficient secondary action: No Play Type,4-for-4 (100%) on No Play Type this season.,"A reliable look worth calling more often, even if not his primary ...","Low (n=4 No Play Type attempts -- small sample, re-check as more g..."
12,Isaac Verges,isaac verges,Starter,Negative,Shooting efficiency,Missing predominantly OPEN catch-and-shoot looks,7-for-20 (35%) on open catch-and-shoot attempts this season -- bel...,"Since these are UNCONTESTED misses, treat as a shooting-mechanics/...",Medium (n=20 open catch-and-shoot attempts)
21,JR Lukenbill,jr lukenbill,Starter,Positive,Play-type efficiency,Efficient secondary action: Cut,10-for-11 (91%) on Cut this season.,"A reliable look worth calling more often, even if not his primary ...",Medium (n=11 Cut attempts)
20,JR Lukenbill,jr lukenbill,Starter,Negative,Free-throw shooting,Below-average free-throw shooter with meaningful attempt volume,54.5% FT this season -- 12-for-22 over 26 games (0.8 attempts a ga...,Target free-throw shooting in individual workouts -- meaningful at...,Medium (n=22 FT attempts)
19,Joey Berezowitz,joey berezowitz,Starter,Positive,Play-type efficiency,Efficient secondary action: Cut,5-for-6 (83%) on Cut this season.,"A reliable look worth calling more often, even if not his primary ...",Medium (n=6 Cut attempts)
23,Luke Bara,luke bara,Starter,Positive,Free-throw shooting,Reliable free-throw shooter,"89.7% FT this season (1.8-2.0 per game, 58 attempts).",A safe option to have on the floor in late-game free-throw situati...,"High (n=58 FT attempts, season-long sample)"
27,Rashad Rogers,rashad rogers,Starter,Positive,Play-type efficiency,Efficient secondary action: Transition,2-for-3 (67%) on Transition this season.,"A reliable look worth calling more often, even if not his primary ...","Low (n=3 Transition attempts -- small sample, re-check as more gam..."
29,Richie Warren,richie warren,Starter,Positive,Play-type efficiency,Efficient secondary action: Offensive Rebound,11-for-12 (92%) on Offensive Rebound this season.,"A reliable look worth calling more often, even if not his primary ...",Medium (n=12 Offensive Rebound attempts)
28,Richie Warren,richie warren,Starter,Negative,Shooting efficiency,Missing predominantly OPEN catch-and-shoot looks,7-for-20 (35%) on open catch-and-shoot attempts this season -- bel...,"Since these are UNCONTESTED misses, treat as a shooting-mechanics/...",Medium (n=20 open catch-and-shoot attempts)
36,Tyshawn Teague-Johnson,tyshawn teague-johnson,Starter,Positive,Play-type efficiency,Efficient secondary action: ISO,7-for-10 (70%) on ISO this season.,"A reliable look worth calling more often, even if not his primary ...",Medium (n=10 ISO attempts)
35,Tyshawn Teague-Johnson,tyshawn teague-johnson,Starter,Negative,Free-throw shooting,Below-average free-throw shooter with meaningful attempt volume,36.4% FT this season -- 8-for-22 over 18 games (1.2 attempts a game).,Target free-throw shooting in individual workouts -- meaningful at...,Medium (n=22 FT attempts)

done  69_structured_coaching_flags_recommendations  (0 s)
done  70_expected_box_score_for_upcoming_game  (0 s)
      Carroll (WI) Pioneers's pre-game keys to victory: 1. TRANSITION DEFENSE!!! | 2. SQUEEZE & LIMIT #4 (Guard 1 on 1 + Gap Help) | 3. ATTACK THE PAINT OFFENSIVELY!!
done  71_reconstruct_box_score_for_opponent_games  (0 s)
done  72_minutes_played_for_upcoming_opponent_prior  (0 s)

                 name   PTS
51     Michael McNabb  21.5
52        Lamar Smith  16.8
50     Peyton McKenna  10.2
53        Jacob Naber   9.5
55         Evan Bland   6.7
49      Dennis Estepp   6.4
54       Lucas Parker   4.8
227  Brendan Beaumont   3.0
231      Jimmy Tarjan   2.4
186  Andrew Hollerich   1.7
187        Cai Joseph   1.1
56         Greg Smith   0.6
185       Evan Oleson   0.5
228      Cale Buboltz   0.5
226    Auggie Hoffman   0.0

done  73_replace_upcoming_opponent_pdf_scouting  (0 s)
done  74_replace_upcoming_opponent_team_totals_with  (0 s)

                      opponent UWW matchup  prior games on schedule  with _pbp file  players filled  roster rows  no PBP match
0        St. Thomas (TX) Celts  2025-11-14                        2               2              12           12             0
1            Eureka Red Devils  2025-11-15                        3               3              14           14             0
2              Aurora Spartans  2025-11-19                        4               4              12           12             0
3         Hope Flying Dutchmen  2025-12-19                        8               2               0            0             0
4                   Alma Scots  2025-12-20                       11              11              10           10             0
5            Elmhurst Bluejays  2025-12-02                        5               5              10           10             0
6                  Coe Kohawks  2025-12-30                       13               1               9           11             2
7          UW-La Crosse Eagles  2026-01-14                       14               1               9           12             3
8      UW-Platteville Pioneers  2026-01-21                       17               1               8           10             2
9       UW-Eau Claire Blugolds  2026-01-24                       17               1              10           12             2
10           UW-Oshkosh Titans  2026-01-03                       11              11              17           17             0
11   UW-Stevens Point Pointers  2026-01-07                       13              13              10           11             1
12               Loras Duhawks  2026-03-06                       28              28              12           12             0
13  Washington-St. Louis Bears  2026-03-07                       26               2              10           10             0

                     name games_played   PTS  REB AST     FG%    3P%
66             Luke Smith            5  11.6  3.4  15   41.2%  33.3%
67      Sebastian Blachut            5  10.8  2.2  14   41.5%  38.5%
68     Dominic Trelenberg            5  16.4  6.6  14   49.1%  37.0%
69            Aidyn Boone            5  10.0  6.2   3   47.1%  45.5%
70   Vinnie Adjahoungbeta            5  11.6  8.4   9   46.8%  58.3%
71          Talen Pearson            5   2.2  0.8   5   26.3%   9.1%
72            Jack Cherry            5   4.4  1.2   5   46.2%  33.3%
73            EJ Marshall            5   2.2  0.8   4   30.8%  50.0%
74       Jeffrey Williams            5   2.6  0.2   0   71.4%  75.0%
189          Oliver Adams            5   0.6  0.6   0  100.0%      -

done  75_back_fill_past_scouted_opponents_player  (56 s)
done  76_rebuild_player_comparisons_with_pbp  (1 s)
done  77_rebuild_player_comparisons_with_pbp_2  (0 s)
done  78_rebuild_player_comparisons_with_pbp_3  (11 s)

    season         date home_away outcome  team_score  opponent_score
0  2025-26  Sat, Dec 13      Home       W        64.0            60.0
1  2024-25  Tue, Nov 12      Away       W        77.0            71.0
2  2023-24  Wed, Nov 15      Home       W        86.0            77.0

done  79_head_to_head  (2 s)

                               table   rows  csv_bytes
0                       uww_schedule    579     337139
1                   uww_season_stats     25       2707
2                     uww_pbp_events  14565    3695998
3                  uww_pbp_box_score    699      79281
4                  uww_lineup_stints   1377     326452
5                 uww_coaching_flags     38      13245
6               uww_opponent_rosters    169      32410
7                uww_player_profiles    233      69451
8            uww_opponent_game_plans    261      54420
9                     uww_ktv_splits      9        598
10           uww_ktv_game_categories     33       2304
11              uww_pbp_derived_keys      3       1074
12          uww_opponent_team_totals     19        464
13           uww_projected_box_score    138      39124
14  uww_opponent_projected_box_score    104      32646

done  80_head_to_head_2  (2 s)
done  81_extract_and_save_team_logos_from_pbp_mhtml  (1 s)
done  82_extract_player_headshots_from_scouting  (9 s)
done  83_assemble_every_key_to_victory_into_one  (2 s)
      *  80.0  #8 TRANSITION DEFENSE!!!
      *  80.0  #1 ATTACK THE PAINT OFFENSIVELY!!
done  84_style_matchups  (0 s)
done  85_scouting_notes_and_keys_to_defending  (0 s)
done  86_game_plan  (2 s)
done  86b_two_for_one  (7 s)
done  87_build_html_scouting_brief_for_upcoming  (5 s)
done  90_model_versions  (0 s)
[brief] finished -- everything the sections printed is in ./inputs\_logs\brief_20261029_125855.log
[brief] skipped 7 section(s) this job doesn't need: 48_jersey_number_recognizer, 49_jersey_number_reader_test, 50c_outfit_check, 50d_reid_check, 88_tracking_review_export, 46a_frame_archive, 89_cleanup

### Continue

In [4]:
# Continue from a section after an error, e.g.:
# run_parser("brief", start_at="56_compute_biggest_scoring_runs_and_largest")